add_executable(${CMAKE_PROJECT_NAME}
    layer_airconditioner.c
    layer_audioplayer.c
    layer_button.c
    layer_calendar.c
    layer_check_anim.c
    layer_check_list.c
    layer_circlectrl.c
    layer_clock.c
    layer_imageplayer.c
    layer_imageview.c    
    layer_keyboard2.c    
    layer_list.c
    layer_logo.c
    layer_main.c
    layer_main_menu.c
    layer_meter.c
    layer_screensaver.c
    layer_setting_display.c
    layer_setting_lang.c
    layer_setting_sound.c
    layer_setting_sysinfo.c
    layer_setting_wifi_main.c
    layer_setting_wifi_network.c
    layer_setting_wifi_password.c
    layer_setting_wifi_ssid.c
    layer_touch_calibration.c
    layer_usb_device_mode.c
    layer_videoplayer.c
    layer_videoview.c
    )
