add_executable(${CMAKE_PROJECT_NAME}
    layer_airconditioner.c
    layer_logo.c
    layer_main.c
    layer_main_menu.c
    layer_screensaver.c
    layer_touch_calibration.c
    layer_usb_device_mode.c
    layer_videoview.c
    )
