/* DO NOT EDIT, FILE GENERATED BY COREMAKE */

#ifndef T
#define T(x) x
#define HAS_DEFINED_T
#endif /* T */

#define PROJECT_NAME T("libmatroska2")
#define PROJECT_VERSION T("0.22.1")
#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 22
#define PROJECT_VERSION_REVISION 1
#define MATROSKA2_PROJECT_VERSION 0x001601
#define PROJECT_VENDOR T("Matroska")

#ifdef HAS_DEFINED_T
#undef T
#undef HAS_DEFINED_T
#endif /* HAS_DEFINED_T */

