#define COREMAKE_STATIC
#define COREMAKE_UNICODE
#define CONFIG_EBML_WRITING
#define CONFIG_EBML_UNICODE
#define HAVE_EBML2
#ifdef CFG_BUILD_ZLIB
    #define CONFIG_ZLIB
#endif
#define CONFIG_MATROSKA2
#define USE_PRECOMPILED_HEADERS
#define CONFIG_DEBUGCHECKS
#define CONFIG_STDIO
#define CONFIG_FILEPOS_64
//#define COREMAKE_CONFIG_HELPER
//#define CONFIG_DEBUG_LEAKS
