/* Automatically generated by configure - do not modify! */
#define VERSION CFG_VERSION_MAJOR_STR "." CFG_VERSION_MINOR_STR "." CFG_VERSION_PATCH_STR "." CFG_VERSION_CUSTOM_STR "." CFG_VERSION_TWEAK_STR
#define PACKAGE "urender"
#define PACKAGE_NAME CFG_SYSTEM_NAME
#define SYSCONFDIR CFG_PRIVATE_DRIVE ":"
#define LOCALEDIR "/usr/local/share/locale"

#ifdef _WIN32
    #define inline
    #define __attribute__()
#endif