ITE SoC SDK: webserver.c File Reference
doorbell_outdoor/webserver.c File Reference
#include <sys/ioctl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "ite/itp.h"
#include "platform.h"
#include "microhttpd.h"
#include "libxml/xpath.h"
#include "ite/ug.h"
#include "doorbell.h"
#include "scene.h"
Macros
#define PAGE "<html><head><meta http-equiv=\"pragma\" content=\"no-cache\"/><meta http-equiv=\"expires\" content=\"0\"/><meta http-equiv=\"refresh\" content=\"0; URL=/setting.html\"/></head></html>"
#define MAX_DEVICE_INFO 100
Functions
static int iterate_post (void *cls, enum MHD_ValueKind kind, const char *key, const char *filename, const char *content_type, const char *transfer_encoding, const char *data, uint64_t off, size_t size)
static ssize_t file_reader (void *cls, uint64_t pos, char *buf, size_t max)
static void file_free_callback (void *cls)
static int ahc_echo (void *cls, struct MHD_Connection *connection, const char *url, const char *method, const char *version, const char *upload_data, size_t *upload_data_size, void **ptr)
void WebServerInit (void)
Initializes web server module.
void WebServerExit (void)
Exits web server module.
Variables
struct MHD_Daemon * webServerDaemon
static uint8_t * filebuf = NULL
static uint32_t filesize = 0
Macro Definition Documentation
#define MAX_DEVICE_INFO 100
Referenced by ahc_echo().
#define PAGE "<html><head><meta http-equiv=\"pragma\" content=\"no-cache\"/><meta http-equiv=\"expires\" content=\"0\"/><meta http-equiv=\"refresh\" content=\"0; URL=/setting.html\"/></head></html>"
Definition at line 13 of file doorbell_outdoor/webserver.c.
Referenced by ahc_echo().
Function Documentation
static int ahc_echo (void * cls, struct MHD_Connection * connection, const char * url, const char * method, const char * version, const char * upload_data, size_t * upload_data_size, void ** ptr) static
Definition at line 74 of file doorbell_outdoor/webserver.c.
References AddressBookGetDeviceInfo(), AddressBookGetDeviceInfoArray(), AddressBookGetDeviceIP(), AddressBookGetManagerInfoArray(), AddressBookGetVersion(), DeviceInfo::area, Config::area, arrayStream, DeviceInfo::building, Config::building, Config::calling_time, ConfigSave(), ConfigSaveAll(), DEVICE_MANAGER, Config::dial_time, EVENT_OPENDOOR_REMOTE, EventWriteOpenDoorLog(), DeviceInfo::ext, Config::ext, file_free_callback(), file_reader(), filebuf, filesize, DeviceInfo::floor, Config::floor, ITPEthernetInfo::hardwareAddress, ITPWifiInfo::hardwareAddress, HINT_SOUND_OPENDOOR, i, ITPEthernetInfo::index, DeviceInfo::ip, itcArrayStreamOpen(), iterate_post(), ITP_DEVICE_ETHERNET, ITP_DEVICE_NOR, ITP_DEVICE_WIFI, ITP_IOCTL_FLUSH, ITP_IOCTL_GET_INFO, ITP_IOCTL_WIRTE_MAC, LinphoneGetMicLevel(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphonePlayHintSound(), LinphoneSetMicLevel(), LinphoneSetRingLevel(), LinphoneSetVoiceLevel(), MAX_DEVICE_INFO, Config::mgsalarm_time, PAGE, PeripheralCallElevator(), PeripheralOpenDoor(), QUIT_RESET_FACTORY, QUIT_RESET_NETWORK, QUIT_UPGRADE_ADDRESSBOOK, QUIT_UPGRADE_CARDLIST, QUIT_UPGRADE_FIRMWARE, QUIT_UPGRADE_RESOURCE, QUIT_UPGRADE_WEB, DeviceInfo::room, Config::room, SceneGetQuitValue(), SceneQuit(), SnapshotGet(), SnapshotTake(), ITCArrayStream::stream, font::t, theCenterInfo, theConfig, theDeviceInfo, DeviceInfo::type, ugCheckCrc(), DeviceInfo::unit, Config::unit, UpgradeGetDeviceInfo(), UpgradeGetResult(), UpgradeIsFinished(), UpgradeSetStream(), UpgradeSetUrl(), and Config::voicememo_time.
Referenced by WebServerInit().
static void file_free_callback (void * cls) static
Definition at line 67 of file doorbell_outdoor/webserver.c.
Referenced by ahc_echo().
static ssize_t file_reader (void * cls, uint64_t pos, char * buf, size_t max) static
Definition at line 58 of file doorbell_outdoor/webserver.c.
Referenced by ahc_echo().
static int iterate_post (void * cls, enum MHD_ValueKind kind, const char * key, const char * filename, const char * content_type, const char * transfer_encoding, const char * data, uint64_t off, size_t size) static
Definition at line 20 of file doorbell_outdoor/webserver.c.
References filebuf, and filesize.
Referenced by ahc_echo().
Variable Documentation
uint8_t* filebuf = NULL static
Definition at line 16 of file doorbell_outdoor/webserver.c.
Referenced by AddressBookExport(), AddressBookInit(), ahc_echo(), iterate_post(), and Parse_UCL2MEM().
uint32_t filesize = 0 static
Definition at line 17 of file doorbell_outdoor/webserver.c.
Referenced by ahc_echo(), GetPackageSize(), iterate_post(), and OpenFtpPackage().
struct MHD_Daemon* webServerDaemon
Definition at line 15 of file doorbell_outdoor/webserver.c.
Referenced by WebServerExit(), and WebServerInit().