ITE SoC SDK: scene.c File Reference
doorbell_indoor/scene.c File Reference
#include <sys/time.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "SDL/SDL.h"
#include "linphone/linphone_castor3.h"
#include "scene.h"
#include "doorbell.h"
Data Structures
struct Command
Macros
#define GESTURE_THRESHOLD 40
#define MAX_COMMAND_QUEUE_SIZE 8
#define MS_PER_FRAME 33
#define HOTKEY_DELAY 5
#define WARNPLAY_DELAY 5
#define MAX_MISSED_CALL_COUNT 999
#define PRDRAW_DELAY 2
#define MAX_STRARG_LEN 32
Enumerations
enum CommandID {
CMD_NONE, CMD_LOAD_SCENE, CMD_CALL_CONNECTED, CMD_CALL_RECEIVED,
CMD_CALL_SPOTTED, CMD_CALL_END, CMD_CALL_ERROR, CMD_CALL_FIRST_SNAPSHOT,
CMD_UPDATE_INDICATORS, CMD_NONE, CMD_CALL_CONNECTED, CMD_CALL_RECEIVED,
CMD_CALL_END, CMD_CALL_ERROR
}
Functions
void resetScene (void)
void SceneInit (void)
Initializes scene module.
void SceneExit (void)
Exits scene module.
void SceneLoad (void)
Loads ITU file.
static void SceneCallConnected (char *addr, int id)
static void SceneCallReceived (char *username, char *addr, int id, int video)
static void SceneCallEnd (char *addr, int id)
static void SceneCallError (char *addr, int id, int code)
void SceneUpdateIndicators (void)
Resets all the status of indicator UI.
static int SceneCallOnDoNotDisturb (char *ip)
static int SceneCallAllowCallWaiting (char *ip)
void SceneCameraSetViewing (bool viewing)
Sets the status of watching camera or video message.
int SceneCameraIsViewing (void)
Is watching camera or video message right now.
int SceneisCalling (void)
void SceneSetReady (bool ready)
Sets the status of scene.
static void SceneNewLog (time_t start_time)
int SceneCallSpottedOrNot (char *addr, int id, int video)
void SceneCameraConnectError (bool bError)
void SceneContinuePlayGuardAlarm (void)
Try to continue play guard alarm.
void SceneCaptureRecordStatus (char bStatus)
static void SceneCallFirstSnapshot (char *addr)
static void LoadScene (void)
void SceneEnterVideoState (void)
scene erter to video state.
void SceneLeaveVideoState (void)
scene leave from video state.
static void CallConnected (char *addr, int id)
static void CallReceived (char *addr, int id, int video)
static void CallSpotted (char *addr, int id, int video)
static void CallEnd (char *addr, int id)
static void CallError (char *addr, int id, int code)
static void CallFirstSnapshot (char *addr)
static void UpdateIndicators (void)
static bool ProcessCommand (void)
static void CheckMissedCalls (void)
void SceneClearMissedCalls (void)
Clears all the missed calls.
void CheckNewMessages (void)
static void CheckGuard (void)
static void CheckNetwork (void)
static void CheckDoNotDisturb (void)
static bool CheckQuitValue (void)
void SceneOpenDoor (char *ip)
Opens the door on the remote device.
void SceneSetRemoteIP (char *ip)
Sets the IP address of remote side.
void SceneHangUp (void)
Hangs up the phone.
bool SceneIsCallConnected (void)
Is the call connected or not.
void SceneSetLastDoNotDisturbMode (DoNotDisturbMode mode)
Sets the last do not disturb mode.
static void ToggleMute (void)
int SceneRun (void)
Runs the main loop to receive events, update and draw scene.
void SceneQuit (QuitValue value)
Quits the scene.
QuitValue SceneGetQuitValue (void)
Gets the current quit value.
Variables
ITUActionFunction actionFunctions []
bool captureRecording
static bool callReceived
static bool callConnected
static bool networkReady
static bool guardOn
static bool guardRobAlarming
static int textMsgCount
static int videoMsgCount
static QuitValue quitValue
static time_t lastLogTime
static bool cameraViewing
static DoNotDisturbMode lastDoNotDisturbMode
static int hotkeyDelay
static int warnPlayDelay
static bool inVideoState
SPOTTED_STATUS callSpottedStatus = SPOTTED_NONE
static int predrawDelay
static mqd_t commandQueue = -1
ITUScene theScene
Global instance variable of scene.
static SDL_Window * window
static ITUSurface * screenSurf
static bool isReady
static int currCallID
static char currRemoteAddr [16]
static int pendingCallID
static char pendingRemoteAddr [16]
static int currCallingCount
Macro Definition Documentation
#define GESTURE_THRESHOLD 40
Examples:
test_itu/test_sdl.c.
Definition at line 19 of file doorbell_indoor/scene.c.
Referenced by SceneRun().
#define HOTKEY_DELAY 5
Definition at line 22 of file doorbell_indoor/scene.c.
Referenced by SceneCameraSetViewing(), and SceneHangUp().
#define MAX_COMMAND_QUEUE_SIZE 8
Definition at line 20 of file doorbell_indoor/scene.c.
Referenced by SceneInit().
#define MAX_MISSED_CALL_COUNT 999
Definition at line 24 of file doorbell_indoor/scene.c.
Referenced by CheckMissedCalls().
#define MAX_STRARG_LEN 32
Definition at line 63 of file doorbell_indoor/scene.c.
#define MS_PER_FRAME 33
Definition at line 21 of file doorbell_indoor/scene.c.
Referenced by SceneRun().
#define PRDRAW_DELAY 2
Definition at line 25 of file doorbell_indoor/scene.c.
Referenced by LoadScene().
#define WARNPLAY_DELAY 5
Definition at line 23 of file doorbell_indoor/scene.c.
Referenced by SceneContinuePlayGuardAlarm().
Enumeration Type Documentation
enum CommandID
Enumerator
CMD_NONE
CMD_LOAD_SCENE
CMD_CALL_CONNECTED
CMD_CALL_RECEIVED
CMD_CALL_SPOTTED
CMD_CALL_END
CMD_CALL_ERROR
CMD_CALL_FIRST_SNAPSHOT
CMD_UPDATE_INDICATORS
CMD_NONE
CMD_CALL_CONNECTED
CMD_CALL_RECEIVED
CMD_CALL_END
CMD_CALL_ERROR
Definition at line 50 of file doorbell_indoor/scene.c.
Function Documentation
static void CallConnected (char * addr, int id) static
Definition at line 513 of file doorbell_indoor/scene.c.
References callConnected, currCallID, currRemoteAddr, EVENT_CALLOUT_START, EVENT_CUSTOM_CALL_CONNECTED, EventWriteCalloutLog(), ituSceneSendEvent(), linphoneCastor3, LinphoneTerminateOthers(), and LinphoneCastor3::video_msg_uri.
Referenced by ProcessCommand().
static void CallEnd (char * addr, int id) static
Definition at line 578 of file doorbell_indoor/scene.c.
References callConnected, LinphoneCastor3::calling_ip_count, callReceived, LinphoneCastor3::camera_id, cameraViewing, currCallID, currCallingCount, currRemoteAddr, EVENT_CALLOUT_END, EVENT_CALLOUT_NOACK, EVENT_CUSTOM_CALL_END, EVENT_CUSTOM_CAMERA_TIMEOUT, EventWriteCalloutLog(), ituSceneSendEvent(), linphoneCastor3, LinphoneTerminateOthers(), SceneContinuePlayGuardAlarm(), and LinphoneCastor3::video_msg_uri.
Referenced by ProcessCommand().
static void CallError (char * addr, int id, int code) static
Definition at line 613 of file doorbell_indoor/scene.c.
References callConnected, LinphoneCastor3::calling_ip_count, callReceived, LinphoneCastor3::camera_id, cameraViewing, captureRecording, currCallID, currCallingCount, currRemoteAddr, EVENT_CALLOUT_END, EVENT_CALLOUT_NOACK, EVENT_CUSTOM_CALL_ERROR, EVENT_CUSTOM_CAMERA_TIMEOUT, EventWriteCalloutLog(), ituSceneSendEvent(), linphoneCastor3, LinphoneTerminateOthers(), SceneContinuePlayGuardAlarm(), and LinphoneCastor3::video_msg_uri.
Referenced by ProcessCommand().
static void CallFirstSnapshot (char * addr) static
Definition at line 658 of file doorbell_indoor/scene.c.
References CaptureSnapshot().
Referenced by ProcessCommand().
static void CallReceived (char * addr, int id, int video) static
Definition at line 532 of file doorbell_indoor/scene.c.
References callConnected, callReceived, currCallID, currRemoteAddr, Config::do_not_disturb_option, DONOT_DISTURB_VOICEMEMO, EVENT_CUSTOM_CALL_INCOMMING, EVENT_CUSTOM_VOICEMEMO, isReady, ituSceneSendEvent(), LinphoneIsInDoNotDisturb(), pendingCallID, pendingRemoteAddr, ScreenSaverRefresh(), and theConfig.
Referenced by ProcessCommand().
static void CallSpotted (char * addr, int id, int video) static
Definition at line 570 of file doorbell_indoor/scene.c.
References EVENT_CUSTOM_CALL_INCOMMING, and ituSceneSendEvent().
Referenced by ProcessCommand().
static void CheckDoNotDisturb (void) static
Definition at line 937 of file doorbell_indoor/scene.c.
References AudioIsMuted(), Config::do_not_disturb_mode, DONOT_DISTURB_NONE, EVENT_CUSTOM_DISTURB_MODE, isReady, ituSceneSendEvent(), LinphoneCheckDoNotDisturb(), and theConfig.
Referenced by SceneRun().
static void CheckGuard (void) static
Definition at line 846 of file doorbell_indoor/scene.c.
References AudioIsMuted(), AudioMute(), AudioUnMute(), EVENT_CUSTOM_GUARD, Config::guard_mode, GUARD_NONE, GuardCheck(), GuardIsAlarming(), guardOn, guardRobAlarming, GuardSetAlarming(), isReady, ituLayerGoto(), ituSceneFindWidget(), ituSceneSendEvent(), LinphonePlayWarnSound(), LinphoneStopSound(), ScreenSaverRefresh(), theConfig, and warnPlayDelay.
Referenced by SceneRun().
static void CheckMissedCalls (void) static
Definition at line 784 of file doorbell_indoor/scene.c.
References CallLogGetCurrMissedCount(), ConfigSave(), EVENT_CUSTOM_MISS_CALLS, ituSceneSendEvent(), MAX_MISSED_CALL_COUNT, Config::missed_call_count, and theConfig.
Referenced by SceneRun().
static void CheckNetwork (void) static
Definition at line 916 of file doorbell_indoor/scene.c.
References EVENT_CUSTOM_NETWORK, ituSceneSendEvent(), NetworkIsReady(), networkReady, and ScreenSaverIsScreenSaving().
Referenced by SceneRun().
void CheckNewMessages (void)
Definition at line 813 of file doorbell_indoor/scene.c.
References DEVICE_INDOOR2, EVENT_CUSTOM_MESSAGE, EVENT_CUSTOM_MESSAGE_TEXT, EVENT_CUSTOM_MESSAGE_VIDEO, isReady, ituSceneSendEvent(), textMsgCount, theDeviceInfo, DeviceInfo::type, VideoMemoGetUnplayCount(), videoMsgCount, WebServerGetNewTextMsgCount(), and WebServerGetNewVideoMsgCount().
Referenced by SceneRun().
static bool CheckQuitValue (void) static
Definition at line 964 of file doorbell_indoor/scene.c.
References EVENT_CUSTOM_UPGRADE, ituSceneSendEvent(), QUIT_UPGRADE_ADDRESSBOOK, QUIT_UPGRADE_CARDLIST, quitValue, SCREENSAVER_BLANK, Config::screensaver_type, ScreenSaverIsScreenSaving(), ScreenSaverRefresh(), and theConfig.
Referenced by SceneRun().
static void LoadScene (void) static
Definition at line 423 of file doorbell_indoor/scene.c.
References Config::itufile, ituSceneExit(), ituSceneLoadFile(), linphonec_call_allow_call_waiting_callback, linphonec_call_camera_connect_error_callback, linphonec_call_capture_record_status_callback, linphonec_call_connected_notify_callback, linphonec_call_end_notify_callback, linphonec_call_error_notify_callback, linphonec_call_first_snapshot_callback, linphonec_call_imcoming_received_notify_callback, linphonec_call_is_allowing_spotted_callback, linphonec_call_is_calling_callback, linphonec_call_is_camera_viewing_callback, linphonec_call_on_do_not_disturb_callback, linphonec_new_log_notify_callback, PRDRAW_DELAY, predrawDelay, resetScene(), ITUScene::root, SceneCallAllowCallWaiting(), SceneCallConnected(), SceneCallEnd(), SceneCallError(), SceneCallFirstSnapshot(), SceneCallOnDoNotDisturb(), SceneCallReceived(), SceneCallSpottedOrNot(), SceneCameraConnectError(), SceneCameraIsViewing(), SceneCaptureRecordStatus(), SceneisCalling(), SceneNewLog(), and theConfig.
Referenced by ProcessCommand().
static bool ProcessCommand (void) static
Definition at line 738 of file doorbell_indoor/scene.c.
References Command::arg1, Command::arg2, CallConnected(), CallEnd(), CallError(), CallFirstSnapshot(), CallReceived(), CallSpotted(), CMD_CALL_CONNECTED, CMD_CALL_END, CMD_CALL_ERROR, CMD_CALL_FIRST_SNAPSHOT, CMD_CALL_RECEIVED, CMD_CALL_SPOTTED, CMD_LOAD_SCENE, CMD_UPDATE_INDICATORS, commandQueue, Command::id, LoadScene(), Command::strarg1, and UpdateIndicators().
Referenced by SceneRun().
void resetScene (void)
Definition at line 77 of file reset.c.
References CalledReset(), CallingReset(), CameraOutdoorReset(), CameraReset(), CameraViewReset(), GuardLogReset(), GuardModeReset(), GuardPasswordReset(), GuardStatusReset(), GuardUserReset(), GuardUserSettingReset(), HouseAirConditionerReset(), HouseCurtainReset(), HouseLightReset(), HouseModeReset(), HousePlugReset(), HouseTVReset(), MainMenuReset(), MainReset(), MainVoiceMemoReset(), MainWeatherReset(), MessagePhotoReset(), MessagePhotoViewReset(), MessageRecordReset(), MessageRecordViewReset(), MessageReset(), MessageServiceReset(), MessageServiceViewReset(), PhoneContactsAddReset(), PhoneContactsKeyboardReset(), PhoneContactsKeypadReset(), PhoneContactsModifyReset(), PhoneContactsReset(), PhoneDialLobbyReset(), PhoneDialManagerReset(), PhoneDialResidentReset(), PhoneLogMissedReset(), PhoneLogReceivedReset(), PhoneLogSentReset(), PhoneLogViewReset(), ScreensaverReset(), SettingDisplayReset(), SettingEngineerMiscTerminalReset(), SettingEngineerMiscTwiceReset(), SettingEngineerNetworkIPReset(), SettingEngineerNetworkMacReset(), SettingEngineerNetworkReset(), SettingEngineerNetworkWiFiPasswordReset(), SettingEngineerNetworkWiFiReset(), SettingEngineerReset(), SettingEngineerSensorReset(), SettingOutdoorMainReset(), SettingOutdoorMiscReset(), SettingPhoneAudioReset(), SettingPhoneDisturbReset(), SettingPhoneVoiceReset(), SettingSystemReset(), TimeReset(), TouchCalibrationReset(), UpgradeReset(), and VideoRecordReset().
Referenced by LoadScene().
static int SceneCallAllowCallWaiting (char * ip) static
Definition at line 285 of file doorbell_indoor/scene.c.
References callConnected, callReceived, currRemoteAddr, DeviceInfo::ip, SceneCameraIsViewing(), theCenterInfo, theEntranceInfo, and theOutdoorInfo.
Referenced by LoadScene().
static void SceneCallConnected (char * addr, int id) static
Definition at line 179 of file doorbell_indoor/scene.c.
References Command::arg1, CMD_CALL_CONNECTED, commandQueue, Command::id, and Command::strarg1.
Referenced by LoadScene().
static void SceneCallEnd (char * addr, int id) static
Definition at line 208 of file doorbell_indoor/scene.c.
References Command::arg1, CMD_CALL_END, commandQueue, Command::id, and Command::strarg1.
Referenced by LoadScene().
static void SceneCallError (char * addr, int id, int code) static
Definition at line 222 of file doorbell_indoor/scene.c.
References Command::arg1, Command::arg2, CMD_CALL_ERROR, commandQueue, Command::id, and Command::strarg1.
Referenced by LoadScene().
static void SceneCallFirstSnapshot (char * addr) static
Definition at line 405 of file doorbell_indoor/scene.c.
References CMD_CALL_FIRST_SNAPSHOT, commandQueue, Command::id, and Command::strarg1.
Referenced by LoadScene().
static int SceneCallOnDoNotDisturb (char * ip) static
Definition at line 248 of file doorbell_indoor/scene.c.
References callConnected, Config::do_not_disturb_option, DONOT_DISTURB_HANGUP, DONOT_DISTURB_MESSAGE, DONOT_DISTURB_REDIRECT, DONOT_DISTURB_VOICEMEMO, EventWriteSmsLog(), DeviceInfo::ext, DeviceInfo::ip, LinphoneRedirect(), theCenterInfo, theConfig, and theDeviceInfo.
Referenced by LoadScene().
static void SceneCallReceived (char * username, char * addr, int id, int video) static
Definition at line 193 of file doorbell_indoor/scene.c.
References Command::arg1, Command::arg2, CMD_CALL_RECEIVED, commandQueue, Command::id, and Command::strarg1.
Referenced by LoadScene().
int SceneCallSpottedOrNot (char * addr, int id, int video)
Definition at line 353 of file doorbell_indoor/scene.c.
References Command::arg1, Command::arg2, callConnected, callReceived, callSpottedStatus, CMD_CALL_SPOTTED, commandQueue, currCallID, currCallingCount, currRemoteAddr, Command::id, SPOTTED_ALLOW, SPOTTED_INIT, SPOTTED_REJECT, and Command::strarg1.
Referenced by LoadScene().
void SceneCameraConnectError (bool bError)
Definition at line 385 of file doorbell_indoor/scene.c.
References captureRecording.
Referenced by LoadScene().
void SceneCaptureRecordStatus (char bStatus)
Definition at line 397 of file doorbell_indoor/scene.c.
References captureRecording.
Referenced by LoadScene().
int SceneisCalling (void)
Definition at line 338 of file doorbell_indoor/scene.c.
References callConnected.
Referenced by LoadScene().
static void SceneNewLog (time_t start_time) static
Definition at line 348 of file doorbell_indoor/scene.c.
References lastLogTime.
Referenced by LoadScene().
static void ToggleMute (void) static
Definition at line 1031 of file doorbell_indoor/scene.c.
References AudioMute(), AudioUnMute(), ConfigSave(), Config::do_not_disturb_mode, DONOT_DISTURB_ALL, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_TIME, EVENT_CUSTOM_DISTURB_MODE, GuardIsAlarming(), ituSceneSendEvent(), lastDoNotDisturbMode, LinphoneDisableDoNotDisturb(), LinphoneEnableDoNotDisturb(), LinphoneIsInDoNotDisturb(), Config::muted, and theConfig.
Referenced by SceneRun().
static void UpdateIndicators (void) static
Definition at line 664 of file doorbell_indoor/scene.c.
References AudioMute(), AudioUnMute(), CallLogGetCurrMissedCount(), Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_mode, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, DONOT_DISTURB_ALL, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_TIME, EVENT_CUSTOM_DISTURB_MODE, EVENT_CUSTOM_GUARD, EVENT_CUSTOM_MISS_CALLS, EVENT_CUSTOM_NETWORK, Config::guard_mode, GUARD_NONE, guardOn, ituSceneSendEvent(), LinphoneDisableDoNotDisturb(), LinphoneEnableDoNotDisturb(), Config::muted, NetworkIsReady(), textMsgCount, theConfig, and videoMsgCount.
Referenced by ProcessCommand().
Variable Documentation
ITUActionFunction actionFunctions[]
Definition at line 501 of file function_table.c.
bool callConnected static
Definition at line 33 of file doorbell_indoor/scene.c.
Referenced by CallConnected(), CallEnd(), CallError(), CallReceived(), SceneCallAllowCallWaiting(), SceneCallOnDoNotDisturb(), SceneCallSpottedOrNot(), SceneHangUp(), SceneInit(), SceneIsCallConnected(), SceneisCalling(), and SceneRun().
bool callReceived static
Definition at line 32 of file doorbell_indoor/scene.c.
Referenced by CallEnd(), CallError(), CallReceived(), SceneCallAllowCallWaiting(), SceneCallSpottedOrNot(), SceneCameraSetViewing(), SceneHangUp(), SceneInit(), and SceneRun().
SPOTTED_STATUS callSpottedStatus = SPOTTED_NONE
Definition at line 46 of file doorbell_indoor/scene.c.
Referenced by CalledIncomingOnCustom(), CalledOnTimer(), CalledWaitingCancelButtonOnPress(), CalledWaitingConfirmButtonOnPress(), CalledWaitingConfirmButtonOnSimulatePressing(), CallingIncomingOnCustom(), CallingOnTimer(), CallingWaitingCancelButtonOnPress(), CallingWaitingConfirmButtonOnPress(), CallingWaitingConfirmButtonOnSimulatePressing(), SceneCallSpottedOrNot(), and SceneRun().
bool cameraViewing static
Definition at line 41 of file doorbell_indoor/scene.c.
Referenced by CallEnd(), CallError(), SceneCameraIsViewing(), SceneCameraSetViewing(), and SceneInit().
bool captureRecording
Definition at line 21 of file capture.c.
Referenced by CallError(), CaptureInit(), CaptureStartRecord(), CaptureStopRecord(), SceneCameraConnectError(), and SceneCaptureRecordStatus().
mqd_t commandQueue = -1 static
Definition at line 73 of file doorbell_indoor/scene.c.
Referenced by ProcessCommand(), SceneCallConnected(), SceneCallEnd(), SceneCallError(), SceneCallFirstSnapshot(), SceneCallReceived(), SceneCallSpottedOrNot(), SceneExit(), SceneInit(), SceneLoad(), and SceneUpdateIndicators().
int currCallID static
Definition at line 80 of file doorbell_indoor/scene.c.
Referenced by CallConnected(), CallEnd(), CallError(), CallReceived(), SceneCallSpottedOrNot(), SceneHangUp(), and SceneInit().
int currCallingCount static
Definition at line 84 of file doorbell_indoor/scene.c.
Referenced by CallEnd(), CallError(), SceneCallSpottedOrNot(), SceneHangUp(), and SceneInit().
char currRemoteAddr[16] static
Definition at line 81 of file doorbell_indoor/scene.c.
Referenced by CallConnected(), CallEnd(), CallError(), CallReceived(), SceneCallAllowCallWaiting(), SceneCallSpottedOrNot(), SceneHangUp(), SceneInit(), SceneOpenDoor(), SceneRun(), and SceneSetRemoteIP().
bool guardOn static
Definition at line 35 of file doorbell_indoor/scene.c.
Referenced by CheckGuard(), SceneInit(), SceneRun(), and UpdateIndicators().
bool guardRobAlarming static
Definition at line 36 of file doorbell_indoor/scene.c.
Referenced by CheckGuard(), SceneContinuePlayGuardAlarm(), and SceneInit().
int hotkeyDelay static
Definition at line 43 of file doorbell_indoor/scene.c.
Referenced by SceneCameraSetViewing(), SceneHangUp(), SceneInit(), and SceneRun().
bool inVideoState static
Definition at line 45 of file doorbell_indoor/scene.c.
Referenced by SceneEnterVideoState(), SceneInit(), and SceneLeaveVideoState().
bool isReady static
Definition at line 79 of file doorbell_indoor/scene.c.
Referenced by CallReceived(), CheckDoNotDisturb(), CheckGuard(), CheckNewMessages(), SceneInit(), SceneLoad(), and SceneSetReady().
DoNotDisturbMode lastDoNotDisturbMode static
Definition at line 42 of file doorbell_indoor/scene.c.
Referenced by SceneInit(), SceneSetLastDoNotDisturbMode(), and ToggleMute().
time_t lastLogTime static
Definition at line 40 of file doorbell_indoor/scene.c.
Referenced by SceneNewLog().
bool networkReady static
Definition at line 34 of file doorbell_indoor/scene.c.
Referenced by CheckNetwork(), and SceneInit().
int pendingCallID static
Definition at line 82 of file doorbell_indoor/scene.c.
Referenced by CallReceived(), and SceneInit().
char pendingRemoteAddr[16] static
Definition at line 83 of file doorbell_indoor/scene.c.
Referenced by CallReceived(), and SceneInit().
int predrawDelay static
Definition at line 47 of file doorbell_indoor/scene.c.
Referenced by LoadScene(), and SceneRun().
QuitValue quitValue static
Definition at line 39 of file doorbell_indoor/scene.c.
Referenced by CheckQuitValue(), SceneGetQuitValue(), SceneQuit(), and SceneRun().
ITUSurface* screenSurf static
Definition at line 78 of file doorbell_indoor/scene.c.
int textMsgCount static
Definition at line 37 of file doorbell_indoor/scene.c.
Referenced by CheckNewMessages(), SceneInit(), SceneRun(), and UpdateIndicators().
int videoMsgCount static
Definition at line 38 of file doorbell_indoor/scene.c.
Referenced by CheckNewMessages(), SceneInit(), and UpdateIndicators().
int warnPlayDelay static
Definition at line 44 of file doorbell_indoor/scene.c.
Referenced by CheckGuard(), SceneContinuePlayGuardAlarm(), and SceneInit().
SDL_Window* window static
Examples:
test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, and test_itu/test_trackbar.c.
Definition at line 77 of file doorbell_indoor/scene.c.
Referenced by SceneExit(), and SceneInit().