ITE SoC SDK: upgrade.c File Reference
doorbell_indoor/upgrade.c File Reference
#include <sys/ioctl.h>
#include <assert.h>
#include <errno.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "curl/curl.h"
#include "libxml/xpath.h"
#include "ite/ite_sd.h"
#include "ite/ug.h"
#include "doorbell.h"
Data Structures
struct MemoryStruct
Macros
#define URL_LEN 256
Functions
int UpgradeInit (void)
Initializes upgrade module.
static void UpgradeLcdConsoleEnable (void)
static int UpgradeResetFactory (void)
static int UpgradeResetTempDrive (void)
static ITCStream * OpenUsbPackage (char *path)
static size_t throw_away (void *ptr, size_t size, size_t nmemb, void *data)
static int GetPackageSize (char *ftpurl)
static size_t WriteMemoryCallback (void *contents, size_t size, size_t nmemb, void *userp)
static ITCStream * DownloadPackage (char *ftpurl, int filesize)
static ITCStream * OpenFtpPackage (char *path)
static int UpgradePackage (void)
void UpgradeSetFileCrc (char *filepath)
Sets the CRC value of the specified file path.
static void UpgradeFilesCrc (void)
char * UpgradeGetDeviceInfo (int *size)
Gets the XML string of the device information.
void UpgradeSetUrl (char *url)
Sets the URL to upgrade.
void UpgradeSetStream (void *stream)
Sets the stream to upgrade.
static void * UpgradeProcessTask (void *arg)
int UpgradeProcess (int code)
Processes the upgrade procedure by QuitValue.
bool UpgradeIsReady (void)
Is upgrading ready or not.
bool UpgradeIsFinished (void)
Is upgrading finished or not.
int UpgradeGetResult (void)
Gets the upgrading result.
char * UpgradeGetSDPath (void)
Gets the SD drive path.
Variables
static char upgradeUrl [URL_LEN]
static bool upgradeIsReady
static bool upgradeIsFinished
static int upgradeResult
static ITCArrayStream arrayStream
static ITCFileStream fileStream
static ITCStream * upgradeStream
static char pkgFilePath [PATH_MAX]
Macro Definition Documentation
#define URL_LEN 256
Definition at line 14 of file doorbell_indoor/upgrade.c.
Referenced by UpgradeSetUrl().
Function Documentation
static ITCStream* DownloadPackage (char * ftpurl, int filesize) static
Definition at line 235 of file doorbell_indoor/upgrade.c.
References itcArrayStreamOpen(), MemoryStruct::memory, MemoryStruct::size, ITCArrayStream::stream, and WriteMemoryCallback().
Referenced by OpenFtpPackage().
static int GetPackageSize (char * ftpurl) static
Definition at line 168 of file doorbell_indoor/upgrade.c.
References filesize, and throw_away().
Referenced by OpenFtpPackage().
static ITCStream* OpenFtpPackage (char * path) static
Definition at line 298 of file doorbell_indoor/upgrade.c.
References DownloadPackage(), filesize, and GetPackageSize().
Referenced by UpgradePackage().
static ITCStream* OpenUsbPackage (char * path) static
Definition at line 118 of file doorbell_indoor/upgrade.c.
References ITPDriveStatus::avail, ITPDriveStatus::disk, i, itcFileStreamOpen(), ITP_DEVICE_DRIVE, ITP_DISK_MSC00, ITP_DISK_MSC17, ITP_IOCTL_GET_TABLE, ITP_MAX_DRIVE, ITPDriveStatus::name, pkgFilePath, and ITCFileStream::stream.
Referenced by UpgradePackage().
static size_t throw_away (void * ptr, size_t size, size_t nmemb, void * data) static
Definition at line 159 of file doorbell_indoor/upgrade.c.
Referenced by GetPackageSize().
static void UpgradeFilesCrc (void) static
Definition at line 392 of file doorbell_indoor/upgrade.c.
References ugUpgradeFilesCrc().
Referenced by UpgradeProcess(), and UpgradeProcessTask().
static void UpgradeLcdConsoleEnable (void) static
Definition at line 64 of file doorbell_indoor/upgrade.c.
References ITP_DEVICE_LCDCONSOLE, ITP_DEVICE_STD, ITP_IOCTL_CLEAR, ITP_IOCTL_INIT, itpDeviceLcdConsole, and itpRegisterDevice().
Referenced by UpgradeProcess().
static int UpgradePackage (void) static
Definition at line 328 of file doorbell_indoor/upgrade.c.
References OpenFtpPackage(), OpenUsbPackage(), pkgFilePath, ugCheckCrc(), ugUpgradePackage(), and upgradeUrl.
Referenced by UpgradeProcess(), and UpgradeProcessTask().
static void* UpgradeProcessTask (void * arg) static
Definition at line 512 of file doorbell_indoor/upgrade.c.
References AddressBookInit(), CardListReload(), DeviceInfoInit(), ITP_DEVICE_NOR, ITP_IOCTL_FLUSH, QUIT_UPGRADE_ADDRESSBOOK, QUIT_UPGRADE_CARDLIST, UpgradeFilesCrc(), upgradeIsFinished, and UpgradePackage().
Referenced by UpgradeProcess().
static int UpgradeResetFactory (void) static
Definition at line 73 of file doorbell_indoor/upgrade.c.
References ITP_DEVICE_FAT, ITP_DISK_NOR, ITP_IOCTL_FORCE_MOUNT, ITP_IOCTL_FORMAT, ITP_IOCTL_UNMOUNT, and ugResetFactory().
Referenced by UpgradeProcess().
static int UpgradeResetTempDrive (void) static
Definition at line 83 of file doorbell_indoor/upgrade.c.
References ITPPartition::count, ITP_DEVICE_FAT, ITP_DEVICE_WATCHDOG, ITP_DISK_NOR, ITP_IOCTL_DISABLE, ITP_IOCTL_ENABLE, ITP_IOCTL_FORCE_MOUNT, ITP_IOCTL_FORMAT, ITP_IOCTL_UNMOUNT, ITPPartition::size, ITPPartition::start, and UpgradeGetSDPath().
Referenced by UpgradeProcess().
static size_t WriteMemoryCallback (void * contents, size_t size, size_t nmemb, void * userp) static
Definition at line 222 of file doorbell_indoor/upgrade.c.
References MemoryStruct::memory, and MemoryStruct::size.
Referenced by DownloadPackage().
Variable Documentation
ITCArrayStream arrayStream static
Definition at line 20 of file doorbell_indoor/upgrade.c.
Referenced by ahc_echo(), and create_response().
ITCFileStream fileStream static
Definition at line 21 of file doorbell_indoor/upgrade.c.
char pkgFilePath[PATH_MAX] static
Definition at line 23 of file doorbell_indoor/upgrade.c.
Referenced by OpenUsbPackage(), and UpgradePackage().
bool upgradeIsFinished static
Definition at line 18 of file doorbell_indoor/upgrade.c.
Referenced by UpgradeInit(), UpgradeIsFinished(), UpgradeProcess(), UpgradeProcessTask(), and UpgradeSetStream().
bool upgradeIsReady static
Definition at line 17 of file doorbell_indoor/upgrade.c.
Referenced by UpgradeInit(), UpgradeIsReady(), and UpgradeProcess().
int upgradeResult static
Definition at line 19 of file doorbell_indoor/upgrade.c.
Referenced by UpgradeGetResult(), UpgradeInit(), UpgradeProcess(), and UpgradeSetStream().
ITCStream* upgradeStream static
Definition at line 22 of file doorbell_indoor/upgrade.c.
char upgradeUrl[URL_LEN] static
Definition at line 16 of file doorbell_indoor/upgrade.c.
Referenced by UpgradePackage(), and UpgradeSetUrl().