ITE SoC SDK: main.c File Reference
doorbell_outdoor/main.c File Reference
#include <unistd.h>
#include "SDL/SDL.h"
#include "doorbell.h"
#include "scene.h"
#include "video_encoder/video_encoder_it9910.h"
Macros
#define PULL_DOWN_NONUSE_GPIO 1
#define GPIO_BASE 0xDE000000
Functions
int SDL_main (int argc, char *argv[])
Macro Definition Documentation
#define GPIO_BASE 0xDE000000
Definition at line 8 of file doorbell_outdoor/main.c.
Referenced by SDL_main().
#define PULL_DOWN_NONUSE_GPIO 1
Definition at line 7 of file doorbell_outdoor/main.c.
Function Documentation
int SDL_main (int argc, char * argv[])
Definition at line 10 of file doorbell_outdoor/main.c.
References AddressBookExit(), AddressBookInit(), CardListExit(), CardListInit(), ConfigLoad(), DeviceInfoInit(), EventExit(), EventInit(), GPIO_BASE, LinphoneExit(), LinphoneInit(), NetworkInit(), PeripheralInit(), QUIT_UPGRADE_WEB, SceneExit(), SceneInit(), SceneRun(), SnapshotInit(), UpgradeInit(), UpgradeProcess(), WebServerExit(), and WebServerInit().