ITE SoC SDK: addressbook.c File Reference
doorbell_indoor/addressbook.c File Reference
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "libxml/xpath.h"
#include "ite/itp.h"
#include "ucl/ucl.h"
#include "doorbell.h"
Data Structures
struct ABDevice
Functions
static DeviceType _ToDeviceType (xmlChar *value)
static void GetDeviceInfo (DeviceInfo *info, ABDevice *dev)
static uint32_t DcpsGetSize (uint8_t *Src, uint32_t SrcLen)
static ucl_uint32 xread32 (unsigned char *b)
static int SoftwareDecompress (uint8_t *outbuf, uint8_t *inbuf)
void AddressBookInit (void)
Initializes address book module.
void AddressBookExit (void)
Exits address book module.
char * AddressBookGetVersion (void)
Gets version of addressbook.
void AddressBookGetCenterInfo (DeviceInfo *info)
Gets device information of control server from addressbook.
void AddressBookGetDeviceInfo (DeviceInfo *info, char *ip)
Gets device information from addressbook by IP address.
void AddressBookGetEntranceInfo (DeviceInfo *info, DeviceInfo *deviceInfo)
Gets device information of lobby phone from addressbook.
void AddressBookGetOutdoorInfo (DeviceInfo *info, DeviceInfo *deviceInfo)
Gets device information of door camera from addressbook.
char * AddressBookGetDeviceIP (char *area, char *building, char *unit, char *floor, char *room, char *ext)
Gets IP address by address information from addressbook.
int AddressBookGetDeviceInfoArray (DeviceInfo infoArray[], int count, char *area, char *building, char *unit, char *floor, char *room)
Gets array of indoor phones by address information from addressbook.
int AddressBookGetCameraInfoArray (DeviceInfo infoArray[], int count, DeviceInfo *devinfo)
Gets array of devices with camera from addressbook.
int AddressBookGetLobbyInfoArray (DeviceInfo infoArray[], int count)
Gets array of lobby devices from addressbook.
int AddressBookGetManagerInfoArray (DeviceInfo infoArray[], int count)
Gets array of administrator units from addressbook.
int AddressBookGetIPCameraInfoArray (DeviceInfo infoArray[], int count)
Gets array of ip camera from addressbook.
char * AddressBookGetGateway (DeviceInfo *info)
Gets IP address of gateway from addressbook.
char * AddressBookGetNetMask (DeviceInfo *info)
Gets netmask from addressbook.
bool AddressBookIsOutdoorExist (char *area, char *building, char *unit, char *floor, char *room, char *ext)
Is the outdoor address exist in the addressbook.
int AddressBookGetOutdoorInfoArray (DeviceInfo infoArray[], int count, char *area, char *building, char *unit, char *floor, char *room)
Gets array of door cameras by address information from addressbook.
void AddressBookExport (void)
Variables
static int abDeviceCount
static ABDevice * abDevices
static char abVersion [32]
static char abGateway [32]
static char abNetMask [32]
Function Documentation
static DeviceType _ToDeviceType (xmlChar * value) static
Definition at line 27 of file doorbell_indoor/addressbook.c.
References DEVICE_BUILDING, DEVICE_CENTER, DEVICE_ENTRANCE, DEVICE_INDOOR, DEVICE_INDOOR2, DEVICE_INTERCOM, DEVICE_IPCAM, DEVICE_MANAGER, DEVICE_MOBILE, DEVICE_OUTDOOR, DEVICE_UNKNOWN, and DEVICE_WALL.
Referenced by AddressBookInit().
void AddressBookExport (void)
Definition at line 792 of file doorbell_indoor/addressbook.c.
References ITPDriveStatus::avail, DcpsGetSize(), ITPDriveStatus::disk, font::f, filebuf, i, ITP_DEVICE_DECOMPRESS, ITP_DEVICE_DRIVE, ITP_DISK_MSC00, ITP_DISK_MSC17, ITP_DISK_SD0, ITP_DISK_SD1, ITP_IOCTL_EXIT, ITP_IOCTL_GET_TABLE, ITP_IOCTL_INIT, ITP_MAX_DRIVE, ITPDriveStatus::name, and SoftwareDecompress().
static uint32_t DcpsGetSize (uint8_t * Src, uint32_t SrcLen) static
Definition at line 104 of file doorbell_indoor/addressbook.c.
References i.
Referenced by AddressBookExport(), and AddressBookInit().
static void GetDeviceInfo (DeviceInfo * info, ABDevice * dev) static
Definition at line 68 of file doorbell_indoor/addressbook.c.
References DeviceInfo::alias, DeviceInfo::area, DeviceInfo::building, DEVICE_ENTRANCE, DEVICE_INDOOR, DEVICE_INDOOR2, DEVICE_INTERCOM, DEVICE_IPCAM, DEVICE_OUTDOOR, DeviceInfo::ext, DeviceInfo::floor, ABDevice::ip, DeviceInfo::ip, ABDevice::room, DeviceInfo::room, StringGetCameraPosition(), StringGetDeviceType(), StringGetRoomAddress(), ABDevice::type, DeviceInfo::type, and DeviceInfo::unit.
Referenced by AddressBookGetCameraInfoArray(), AddressBookGetCenterInfo(), AddressBookGetDeviceInfo(), AddressBookGetDeviceInfoArray(), AddressBookGetEntranceInfo(), AddressBookGetIPCameraInfoArray(), AddressBookGetLobbyInfoArray(), AddressBookGetManagerInfoArray(), AddressBookGetOutdoorInfo(), and AddressBookGetOutdoorInfoArray().
static int SoftwareDecompress (uint8_t * outbuf, uint8_t * inbuf) static
Definition at line 140 of file doorbell_indoor/addressbook.c.
References xread32().
Referenced by AddressBookExport(), and AddressBookInit().
static ucl_uint32 xread32 (unsigned char * b) static
Definition at line 129 of file doorbell_indoor/addressbook.c.
Referenced by SoftwareDecompress().
Variable Documentation
int abDeviceCount static
Definition at line 21 of file doorbell_indoor/addressbook.c.
Referenced by AddressBookGetCameraInfoArray(), AddressBookGetCenterInfo(), AddressBookGetDeviceInfo(), AddressBookGetDeviceInfoArray(), AddressBookGetDeviceIP(), AddressBookGetEntranceInfo(), AddressBookGetIPCameraInfoArray(), AddressBookGetLobbyInfoArray(), AddressBookGetManagerInfoArray(), AddressBookGetOutdoorInfo(), AddressBookGetOutdoorInfoArray(), AddressBookInit(), and AddressBookIsOutdoorExist().
ABDevice* abDevices static
Definition at line 22 of file doorbell_indoor/addressbook.c.
char abGateway[32] static
Definition at line 24 of file doorbell_indoor/addressbook.c.
Referenced by AddressBookGetGateway(), and AddressBookInit().
char abNetMask[32] static
Definition at line 25 of file doorbell_indoor/addressbook.c.
Referenced by AddressBookGetNetMask(), and AddressBookInit().
char abVersion[32] static
Definition at line 23 of file doorbell_indoor/addressbook.c.
Referenced by AddressBookGetVersion(), and AddressBookInit().