ITE SoC SDK: layer_calling.c File Reference
doorbell_indoor/layer_calling.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lwip/ip.h"
#include "SDL/SDL.h"
#include "scene.h"
#include "doorbell.h"
#include "linphone/linphone_castor3.h"
Macros
#define ERROR_COUNTDOWN (3.999f)
#define SNAPSHOT_COUNT (1 * 1000 / 33)
Functions
static bool CallingWaitingConfirmButtonOnSimulatePressing ()
bool CallingVolDownButtonOnPress (ITUWidget *widget, char *param)
bool CallingVolUpButtonOnPress (ITUWidget *widget, char *param)
bool CallingRecordButtonOnPress (ITUWidget *widget, char *param)
bool CallingStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool CallingAnswerButtonOnPress (ITUWidget *widget, char *param)
bool CallingUnlockButtonOnPress (ITUWidget *widget, char *param)
bool CallingSnapshotButtonOnPress (ITUWidget *widget, char *param)
bool CallingHangUpButtonOnPress (ITUWidget *widget, char *param)
bool CallingErrorConfirmButtonOnPress (ITUWidget *widget, char *param)
bool CallingWaitingCancelButtonOnPress (ITUWidget *widget, char *param)
bool CallingWaitingConfirmButtonOnPress (ITUWidget *widget, char *param)
int CallingCall (char *area, char *building, char *unit, char *floor, char *room, char *ext)
Makes a phone call to the specified address.
int CallingCallByIP (char *ip)
Makes a phone call to the specified IP address.
int CallingCallManager (char *ip)
Makes a phone call to the specified IP address of administrator unit device.
bool CallingConnectedOnCustom (ITUWidget *widget, char *param)
bool CallingErrorOnCustom (ITUWidget *widget, char *param)
bool CallingIncomingOnCustom (ITUWidget *widget, char *param)
bool CallingOnTimer (ITUWidget *widget, char *param)
bool CallingOnEnter (ITUWidget *widget, char *param)
bool CallingOnLeave (ITUWidget *widget, char *param)
void CallingReset (void)
Variables
static ITULayer * mainVoiceMemoLayer
static ITUText * callingSourceText
static ITUBackground * callingRemoteBackground
static ITUSprite * callingRemoteSprite
static ITUSprite * callingVolBar
static ITUText * callingCountDownText
static ITUBackground * callingErrorBackground
static ITUText * callingErrorCountDownText
static ITUBackground * callingWaitingBackground
static ITUText * callingWaitingTypeText
static ITUText * callingWaitingRoomText
static ITUButton * callingUnlockButton
static ITUButton * callingSnapshotButton
static ITUButton * callingRecordButton
static ITUButton * callingStopRecordButton
static ITUButton * callingAnswerButton
static ITUButton * callingButtonContainer
static int callingMaxVol
static bool callingInVideoState
static bool callingConnected
static float callingCountDown
static float callingErrorCountDown
static float dialCountDown
static float spotCountDown
static float LockRecordButtonCountDown
static uint32_t callingLastTick
static uint32_t callingErrorLastTick
static uint32_t dialLastTick
static uint32_t spotLastTick
static uint32_t LockRecordButtonLastTick
static int callingID
static int callingPendingID
static bool callingPendingVideo
static char callingPendingAddr [32]
static DeviceInfo callingDeviceInfo
static int callingVoiceLevelOld
static int callingRingLevelOld
static bool callingHangUp
static int snapshotCountDown
static bool callingVideoRecordEnable
static DeviceInfo callingManagerInfoArray [MAX_MANAGER_COUNT]
static int callingManagerIndex
static int callingManagerCount
static char callingManagerIPAddr [16]
static bool LockRecordButton
SPOTTED_STATUS callSpottedStatus
Macro Definition Documentation
#define ERROR_COUNTDOWN (3.999f)
Definition at line 11 of file doorbell_indoor/layer_calling.c.
Referenced by CallingErrorOnCustom().
#define SNAPSHOT_COUNT (1 * 1000 / 33)
Definition at line 53 of file doorbell_indoor/layer_calling.c.
Referenced by CallingSnapshotButtonOnPress().
Function Documentation
bool CallingAnswerButtonOnPress (ITUWidget * widget, char * param)
Definition at line 188 of file doorbell_indoor/layer_calling.c.
References callingConnected, callingID, ituLayerGoto(), LinphoneAnswer(), LinphoneTerminate(), and SceneHangUp().
bool CallingConnectedOnCustom (ITUWidget * widget, char * param)
Definition at line 599 of file doorbell_indoor/layer_calling.c.
References Config::calling_time, callingConnected, callingCountDown, callingID, callingLastTick, callingMaxVol, dialCountDown, ituSpriteGoto(), ituTextSetString, LinphoneGetVoiceLevel(), and theConfig.
Referenced by CallConnected().
bool CallingErrorConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 231 of file doorbell_indoor/layer_calling.c.
References callingErrorCountDown.
bool CallingErrorOnCustom (ITUWidget * widget, char * param)
Definition at line 624 of file doorbell_indoor/layer_calling.c.
References callingErrorCountDown, callingErrorLastTick, callingInVideoState, callingManagerCount, callingManagerIndex, callingManagerIPAddr, Config::dial_time, dialCountDown, dialLastTick, ERROR_COUNTDOWN, DeviceInfo::ip, ituTextSetString, ituWidgetSetVisible, SceneSetRemoteIP(), theCenterInfo, and theConfig.
bool CallingHangUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 219 of file doorbell_indoor/layer_calling.c.
References callingHangUp, ituButtonSetPressed(), LinphoneTerminate(), and SceneHangUp().
bool CallingIncomingOnCustom (ITUWidget * widget, char * param)
Definition at line 690 of file doorbell_indoor/layer_calling.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, callingErrorCountDown, callingPendingAddr, callingPendingID, callingPendingVideo, callSpottedStatus, Config::dial_time, DeviceInfo::floor, ituTextSetString, ituWidgetDisable, ituWidgetSetVisible, DeviceInfo::room, spotCountDown, spotLastTick, SPOTTED_INIT, StringGetDeviceType(), StringGetRoomAddress(), theConfig, DeviceInfo::type, and DeviceInfo::unit.
bool CallingOnEnter (ITUWidget * widget, char * param)
Definition at line 901 of file doorbell_indoor/layer_calling.c.
References callingConnected, callingCountDown, callingErrorCountDown, callingHangUp, callingInVideoState, callingMaxVol, callingRingLevelOld, callingVoiceLevelOld, itcTreeGetChildCount, ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, ituWidgetSetVisible, LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetWindowID(), snapshotCountDown, spotCountDown, and theScene.
bool CallingOnLeave (ITUWidget * widget, char * param)
Definition at line 983 of file doorbell_indoor/layer_calling.c.
References callingHangUp, callingID, callingInVideoState, callingPendingID, callingRingLevelOld, callingVoiceLevelOld, CaptureStopRecord(), ConfigSave(), ituWidgetSetVisible, LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneTerminate(), and SceneHangUp().
bool CallingOnTimer (ITUWidget * widget, char * param)
Definition at line 724 of file doorbell_indoor/layer_calling.c.
References callingCountDown, callingErrorCountDown, callingErrorLastTick, callingInVideoState, callingLastTick, callingManagerCount, callingManagerIndex, callingManagerIPAddr, callingPendingID, CallingWaitingConfirmButtonOnSimulatePressing(), callSpottedStatus, Config::dial_time, dialCountDown, dialLastTick, font::f, DeviceInfo::ip, ituLayerGoto(), ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, LinphoneTerminate(), LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, SceneHangUp(), SceneSetRemoteIP(), snapshotCountDown, spotCountDown, spotLastTick, SPOTTED_INIT, SPOTTED_REJECT, theCenterInfo, and theConfig.
Referenced by SceneRun().
bool CallingRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 169 of file doorbell_indoor/layer_calling.c.
References callingInVideoState, CaptureStartRecord(), DeviceInfo::ip, LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, MEDIA_AUDIO, and MEDIA_VIDEO.
void CallingReset (void)
Definition at line 1005 of file doorbell_indoor/layer_calling.c.
Referenced by resetScene().
bool CallingSnapshotButtonOnPress (ITUWidget * widget, char * param)
Definition at line 209 of file doorbell_indoor/layer_calling.c.
References CaptureSnapshot(), DeviceInfo::ip, SNAPSHOT_COUNT, and snapshotCountDown.
bool CallingStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 181 of file doorbell_indoor/layer_calling.c.
References CaptureStopRecord(), and LockRecordButton.
bool CallingUnlockButtonOnPress (ITUWidget * widget, char * param)
Definition at line 203 of file doorbell_indoor/layer_calling.c.
References SceneOpenDoor().
bool CallingVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 101 of file doorbell_indoor/layer_calling.c.
References callingConnected, callingMaxVol, ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetRingLevel(), and LinphoneSetVoiceLevel().
bool CallingVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 135 of file doorbell_indoor/layer_calling.c.
References callingConnected, callingMaxVol, ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetRingLevel(), and LinphoneSetVoiceLevel().
bool CallingWaitingCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 237 of file doorbell_indoor/layer_calling.c.
References callingPendingID, callSpottedStatus, ituButtonSetPressed(), ituWidgetEnable, and SPOTTED_REJECT.
bool CallingWaitingConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 250 of file doorbell_indoor/layer_calling.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, callingID, callingInVideoState, callingPendingAddr, callingPendingID, callingPendingVideo, callingVideoRecordEnable, callSpottedStatus, CaptureStopRecord(), DEVICE_OUTDOOR, DEVICE_WALL, DeviceInfo::floor, ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, DeviceInfo::room, SPOTTED_ALLOW, StringGetRoomAddress(), DeviceInfo::type, and DeviceInfo::unit.
static bool CallingWaitingConfirmButtonOnSimulatePressing () static
Definition at line 55 of file doorbell_indoor/layer_calling.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, callingID, callingInVideoState, callingPendingAddr, callingPendingID, callingPendingVideo, callingVideoRecordEnable, callSpottedStatus, CaptureStopRecord(), DEVICE_OUTDOOR, DEVICE_WALL, DeviceInfo::floor, ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, DeviceInfo::room, SPOTTED_ALLOW, StringGetRoomAddress(), DeviceInfo::type, and DeviceInfo::unit.
Referenced by CallingOnTimer().
Variable Documentation
ITUButton* callingAnswerButton static
Definition at line 28 of file doorbell_indoor/layer_calling.c.
ITUButton* callingButtonContainer static
Definition at line 29 of file doorbell_indoor/layer_calling.c.
bool callingConnected static
Definition at line 34 of file doorbell_indoor/layer_calling.c.
Referenced by CallingAnswerButtonOnPress(), CallingConnectedOnCustom(), CallingOnEnter(), CallingVolDownButtonOnPress(), and CallingVolUpButtonOnPress().
float callingCountDown static
Definition at line 35 of file doorbell_indoor/layer_calling.c.
Referenced by CallingConnectedOnCustom(), CallingOnEnter(), and CallingOnTimer().
ITUText* callingCountDownText static
Definition at line 18 of file doorbell_indoor/layer_calling.c.
DeviceInfo callingDeviceInfo static
Definition at line 40 of file doorbell_indoor/layer_calling.c.
ITUBackground* callingErrorBackground static
Definition at line 19 of file doorbell_indoor/layer_calling.c.
float callingErrorCountDown static
Definition at line 35 of file doorbell_indoor/layer_calling.c.
Referenced by CallingErrorConfirmButtonOnPress(), CallingErrorOnCustom(), CallingIncomingOnCustom(), CallingOnEnter(), and CallingOnTimer().
ITUText* callingErrorCountDownText static
Definition at line 20 of file doorbell_indoor/layer_calling.c.
uint32_t callingErrorLastTick static
Definition at line 36 of file doorbell_indoor/layer_calling.c.
Referenced by CallingErrorOnCustom(), and CallingOnTimer().
bool callingHangUp static
Definition at line 42 of file doorbell_indoor/layer_calling.c.
Referenced by CallingHangUpButtonOnPress(), CallingOnEnter(), and CallingOnLeave().
int callingID static
Definition at line 37 of file doorbell_indoor/layer_calling.c.
Referenced by CallingAnswerButtonOnPress(), CallingConnectedOnCustom(), CallingOnLeave(), CallingWaitingConfirmButtonOnPress(), and CallingWaitingConfirmButtonOnSimulatePressing().
bool callingInVideoState static
Definition at line 33 of file doorbell_indoor/layer_calling.c.
Referenced by CallingCall(), CallingCallByIP(), CallingCallManager(), CallingErrorOnCustom(), CallingOnEnter(), CallingOnLeave(), CallingOnTimer(), CallingRecordButtonOnPress(), CallingWaitingConfirmButtonOnPress(), and CallingWaitingConfirmButtonOnSimulatePressing().
uint32_t callingLastTick static
Definition at line 36 of file doorbell_indoor/layer_calling.c.
Referenced by CallingConnectedOnCustom(), and CallingOnTimer().
int callingManagerCount static
Definition at line 47 of file doorbell_indoor/layer_calling.c.
Referenced by CallingCall(), CallingCallManager(), CallingErrorOnCustom(), and CallingOnTimer().
int callingManagerIndex static
Definition at line 46 of file doorbell_indoor/layer_calling.c.
Referenced by CallingCall(), CallingCallByIP(), CallingCallManager(), CallingConnectedOnCustom(), CallingErrorOnCustom(), and CallingOnTimer().
DeviceInfo callingManagerInfoArray[MAX_MANAGER_COUNT] static
Definition at line 45 of file doorbell_indoor/layer_calling.c.
char callingManagerIPAddr[16] static
Definition at line 48 of file doorbell_indoor/layer_calling.c.
Referenced by CallingCallManager(), CallingErrorOnCustom(), and CallingOnTimer().
int callingMaxVol static
Definition at line 32 of file doorbell_indoor/layer_calling.c.
Referenced by CallingConnectedOnCustom(), CallingOnEnter(), CallingVolDownButtonOnPress(), and CallingVolUpButtonOnPress().
char callingPendingAddr[32] static
Definition at line 39 of file doorbell_indoor/layer_calling.c.
Referenced by CallingIncomingOnCustom(), CallingWaitingConfirmButtonOnPress(), and CallingWaitingConfirmButtonOnSimulatePressing().
int callingPendingID static
Definition at line 37 of file doorbell_indoor/layer_calling.c.
Referenced by CallingIncomingOnCustom(), CallingOnLeave(), CallingOnTimer(), CallingWaitingCancelButtonOnPress(), CallingWaitingConfirmButtonOnPress(), and CallingWaitingConfirmButtonOnSimulatePressing().
bool callingPendingVideo static
Definition at line 38 of file doorbell_indoor/layer_calling.c.
Referenced by CallingIncomingOnCustom(), CallingWaitingConfirmButtonOnPress(), and CallingWaitingConfirmButtonOnSimulatePressing().
ITUButton* callingRecordButton static
Definition at line 26 of file doorbell_indoor/layer_calling.c.
ITUBackground* callingRemoteBackground static
Definition at line 15 of file doorbell_indoor/layer_calling.c.
ITUSprite* callingRemoteSprite static
Definition at line 16 of file doorbell_indoor/layer_calling.c.
int callingRingLevelOld static
Definition at line 41 of file doorbell_indoor/layer_calling.c.
Referenced by CallingOnEnter(), and CallingOnLeave().
ITUButton* callingSnapshotButton static
Definition at line 25 of file doorbell_indoor/layer_calling.c.
ITUText* callingSourceText static
Definition at line 14 of file doorbell_indoor/layer_calling.c.
ITUButton* callingStopRecordButton static
Definition at line 27 of file doorbell_indoor/layer_calling.c.
ITUButton* callingUnlockButton static
Definition at line 24 of file doorbell_indoor/layer_calling.c.
bool callingVideoRecordEnable static
Definition at line 44 of file doorbell_indoor/layer_calling.c.
Referenced by CallingCall(), CallingCallByIP(), CallingWaitingConfirmButtonOnPress(), and CallingWaitingConfirmButtonOnSimulatePressing().
int callingVoiceLevelOld static
Definition at line 41 of file doorbell_indoor/layer_calling.c.
Referenced by CallingOnEnter(), and CallingOnLeave().
ITUSprite* callingVolBar static
Definition at line 17 of file doorbell_indoor/layer_calling.c.
ITUBackground* callingWaitingBackground static
Definition at line 21 of file doorbell_indoor/layer_calling.c.
ITUText* callingWaitingRoomText static
Definition at line 23 of file doorbell_indoor/layer_calling.c.
ITUText* callingWaitingTypeText static
Definition at line 22 of file doorbell_indoor/layer_calling.c.
SPOTTED_STATUS callSpottedStatus
Definition at line 46 of file doorbell_indoor/scene.c.
Referenced by CallingIncomingOnCustom(), CallingOnTimer(), CallingWaitingCancelButtonOnPress(), CallingWaitingConfirmButtonOnPress(), CallingWaitingConfirmButtonOnSimulatePressing(), SceneCallSpottedOrNot(), and SceneRun().
float dialCountDown static
Definition at line 35 of file doorbell_indoor/layer_calling.c.
Referenced by CallingCall(), CallingCallByIP(), CallingCallManager(), CallingConnectedOnCustom(), CallingErrorOnCustom(), and CallingOnTimer().
uint32_t dialLastTick static
Definition at line 36 of file doorbell_indoor/layer_calling.c.
Referenced by CallingCall(), CallingCallByIP(), CallingCallManager(), CallingErrorOnCustom(), and CallingOnTimer().
bool LockRecordButton static
Definition at line 49 of file doorbell_indoor/layer_calling.c.
Referenced by CallingOnTimer(), CallingRecordButtonOnPress(), and CallingStopRecordButtonOnPress().
float LockRecordButtonCountDown static
Definition at line 35 of file doorbell_indoor/layer_calling.c.
Referenced by CallingOnTimer(), and CallingRecordButtonOnPress().
uint32_t LockRecordButtonLastTick static
Definition at line 36 of file doorbell_indoor/layer_calling.c.
Referenced by CallingOnTimer(), and CallingRecordButtonOnPress().
ITULayer* mainVoiceMemoLayer static
Definition at line 13 of file doorbell_indoor/layer_calling.c.
int snapshotCountDown static
Definition at line 43 of file doorbell_indoor/layer_calling.c.
Referenced by CallingOnEnter(), CallingOnTimer(), and CallingSnapshotButtonOnPress().
float spotCountDown static
Definition at line 35 of file doorbell_indoor/layer_calling.c.
Referenced by CallingIncomingOnCustom(), CallingOnEnter(), and CallingOnTimer().
uint32_t spotLastTick static
Definition at line 36 of file doorbell_indoor/layer_calling.c.
Referenced by CallingIncomingOnCustom(), and CallingOnTimer().