ITE SoC SDK: network.c File Reference
doorbell_indoor/network.c File Reference
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <pthread.h>
#include <time.h>
#include "lwip/ip.h"
#include "lwip/dns.h"
#include "ite/itp.h"
#include "iniparser/iniparser.h"
#include "sntp.h"
#include "doorbell.h"
#include "wifiMgr.h"
Macros
#define DHCP_TIMEOUT_MSEC (60 * 1000)
#define HEARTBEAT_TIMEOUT_SEC (30 * 60)
Functions
bool NetworkIsReady (void)
Determines whether the network is ready or not.
bool NetworkServerIsReady (void)
Determines whether the control server is online or not.
void ResetAddr (uint8_t *eth_setting, char *config_addr)
static void NetworkMultiNetif (ITPEthernetSetting *setting)
static void ResetEthernet (void)
static void * NetworkTask (void *arg)
void NetworkSntpUpdate (void)
Updates current time from SNTP server.
void NetworkInit (void)
Initializes network module.
void NetworkExit (void)
Exits network module.
void NetworkReset (void)
Resets network module.
Variables
static bool networkIsReady
static bool networkServerIsReady
static bool networkHeartbeatIsReady
static time_t networkLastRecvTime
static int networkSocket
static bool networkToReset
static bool networkQuit
static ITPEthernetSetting settingCopy
static struct timeval tvStart = {0, 0}
static struct timeval tvEnd = {0, 0}
static int gInit =0
Macro Definition Documentation
#define DHCP_TIMEOUT_MSEC (60 * 1000)
Definition at line 14 of file doorbell_indoor/network.c.
Referenced by ResetEthernet().
#define HEARTBEAT_TIMEOUT_SEC (30 * 60)
Definition at line 15 of file doorbell_indoor/network.c.
Referenced by NetworkTask().
Function Documentation
static void NetworkMultiNetif (ITPEthernetSetting * setting) static
Definition at line 57 of file doorbell_indoor/network.c.
References ITPEthernetSetting::autoip, Config::dhcp, ITPEthernetSetting::dhcp, Config::gw, Config::gw_0, Config::ipaddr, Config::ipaddr_0, ITP_DEVICE_ETHERNET, ITP_IOCTL_RESET, Config::netmask, Config::netmask_0, ResetAddr(), and theConfig.
Referenced by ResetEthernet().
static void* NetworkTask (void * arg) static
Definition at line 336 of file doorbell_indoor/network.c.
References ITPEthernetSetting::dhcp, gInit, HEARTBEAT_TIMEOUT_SEC, ITP_DEVICE_ETHERNET, ITP_IOCTL_IP_DUPLICATE, ITP_IOCTL_IS_CONNECTED, ITP_IOCTL_RESET, itpTimevalDiff(), networkHeartbeatIsReady, networkIsReady, networkLastRecvTime, networkQuit, networkServerIsReady, networkSocket, networkToReset, ResetEthernet(), tvEnd, and tvStart.
Referenced by NetworkInit().
void ResetAddr (uint8_t * eth_setting, char * config_addr)
Definition at line 42 of file doorbell_indoor/network.c.
Referenced by NetworkMultiNetif(), and ResetEthernet().
static void ResetEthernet (void) static
Definition at line 100 of file doorbell_indoor/network.c.
References ITPEthernetInfo::address, AddressBookGetManagerInfoArray(), Config::area, ITPEthernetSetting::autoip, Config::building, DeviceInfoInitByDhcp(), Config::dhcp, ITPEthernetSetting::dhcp, DHCP_TIMEOUT_MSEC, EventWriteRegisterDevice(), DeviceInfo::ext, Config::ext, Config::floor, Config::gw, ITPEthernetInfo::hardwareAddress, i, ITPEthernetInfo::index, ITPEthernetSetting::index, DeviceInfo::ip, Config::ipaddr, ITP_DEVICE_ETHERNET, ITP_IOCTL_ARP_REPLY, ITP_IOCTL_GET_INFO, ITP_IOCTL_IS_AVAIL, ITP_IOCTL_IS_CONNECTED, ITP_IOCTL_RESET, MAX_MANAGER_COUNT, Config::netmask, networkIsReady, NetworkMultiNetif(), RemoteGetDontDisturbConfig(), RemoteSetDontDisturbConfig(), ResetAddr(), Config::room, theCenterInfo, theConfig, theDeviceInfo, and Config::unit.
Referenced by NetworkTask().
Variable Documentation
int gInit =0 static
Definition at line 30 of file doorbell_indoor/network.c.
Referenced by NetworkTask().
bool networkHeartbeatIsReady static
Definition at line 19 of file doorbell_indoor/network.c.
Referenced by NetworkInit(), and NetworkTask().
bool networkIsReady static
Definition at line 17 of file doorbell_indoor/network.c.
Referenced by NetworkInit(), NetworkIsReady(), NetworkServerIsReady(), NetworkTask(), and ResetEthernet().
time_t networkLastRecvTime static
Definition at line 20 of file doorbell_indoor/network.c.
Referenced by NetworkInit(), and NetworkTask().
bool networkQuit static
Definition at line 22 of file doorbell_indoor/network.c.
Referenced by NetworkExit(), NetworkInit(), and NetworkTask().
bool networkServerIsReady static
Definition at line 18 of file doorbell_indoor/network.c.
Referenced by NetworkInit(), NetworkServerIsReady(), and NetworkTask().
int networkSocket static
Definition at line 21 of file doorbell_indoor/network.c.
Referenced by NetworkInit(), and NetworkTask().
bool networkToReset static
Definition at line 22 of file doorbell_indoor/network.c.
Referenced by NetworkInit(), NetworkReset(), and NetworkTask().
ITPEthernetSetting settingCopy static
Definition at line 23 of file doorbell_indoor/network.c.
struct timeval tvEnd = {0, 0} static
Definition at line 28 of file doorbell_indoor/network.c.
Referenced by NetworkTask().
struct timeval tvStart = {0, 0} static
Definition at line 28 of file doorbell_indoor/network.c.
Referenced by NetworkInit(), and NetworkTask().