ITE SoC SDK: webserver.c File Reference
doorbell_indoor/webserver.c File Reference
#include <sys/ioctl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "ite/itp.h"
#include "platform.h"
#include "microhttpd.h"
#include "libxml/xpath.h"
#include "ite/ug.h"
#include "doorbell.h"
#include "scene.h"
Data Structures
struct Request
Data kept per request.
Macros
#define PAGE "<html><head><meta http-equiv=\"pragma\" content=\"no-cache\"/><meta http-equiv=\"expires\" content=\"0\"/><meta http-equiv=\"refresh\" content=\"0; URL=/setting.html\"/></head></html>"
Functions
static int iterate_post (void *cls, enum MHD_ValueKind kind, const char *key, const char *filename, const char *content_type, const char *transfer_encoding, const char *data, uint64_t off, size_t size)
static ssize_t file_reader (void *cls, uint64_t pos, char *buf, size_t max)
static void file_free_callback (void *cls)
static int create_response (void *cls, struct MHD_Connection *connection, const char *url, const char *method, const char *version, const char *upload_data, size_t *upload_data_size, void **ptr)
static void request_completed_callback (void *cls, struct MHD_Connection *connection, void **con_cls, enum MHD_RequestTerminationCode toe)
void WebServerInit (void)
Initializes web server module.
void WebServerExit (void)
Exits web server module.
int WebServerGetNewTextMsgCount (void)
Gets the count of new text messages.
int WebServerGetNewVideoMsgCount (void)
Gets the count of new video messages.
Variables
struct MHD_Daemon * webServerDaemon
static uint8_t * fwFileBuf
static uint32_t fwFileSize
static int wsNewTextMsgCount = 0
static wsNewVideoMsgCount = 0
Macro Definition Documentation
#define PAGE "<html><head><meta http-equiv=\"pragma\" content=\"no-cache\"/><meta http-equiv=\"expires\" content=\"0\"/><meta http-equiv=\"refresh\" content=\"0; URL=/setting.html\"/></head></html>"
Definition at line 13 of file doorbell_indoor/webserver.c.
Referenced by create_response().
Function Documentation
static int create_response (void * cls, struct MHD_Connection * connection, const char * url, const char * method, const char * version, const char * upload_data, size_t * upload_data_size, void ** ptr) static
Definition at line 90 of file doorbell_indoor/webserver.c.
References AddressBookGetVersion(), ServerInfo::addressBookVersion, DeviceInfo::area, Config::area, arrayStream, Config::brightness, DeviceInfo::building, Config::building, ConfigSave(), ConfigSaveAll(), Request::connection, DeviceInfoIsInEngineerMode(), Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_mode, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, DONOT_DISTURB_TIME, Config::engineer_password, DeviceInfo::ext, Config::ext, file_free_callback(), file_reader(), Request::filebuf, Request::filesize, DeviceInfo::floor, Config::floor, fwFileBuf, fwFileSize, GUARD_AREA, GUARD_DOOR, GUARD_EMERGENCY, GUARD_GAS, GUARD_INFRARED, GUARD_NONE, GUARD_ROB, GUARD_SMOKE, GUARD_WINDOW, GuardGetSensorStatus(), GuardReceiveSyncLog(), GuardSetMode(), Config::gw, ITPEthernetInfo::hardwareAddress, ITPEthernetInfo::index, DeviceInfo::ip, itcArrayStreamOpen(), iterate_post(), itp_codec_standby(), ITP_DEVICE_ETHERNET, ITP_DEVICE_NOR, ITP_IOCTL_FLUSH, ITP_IOCTL_GET_INFO, ITP_IOCTL_WIRTE_MAC, Config::itufile, Request::key, Config::keylevel, Config::keysound, Config::lang, LinphoneGetMicLevel(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetKeyLevel(), LinphoneSetMicLevel(), LinphoneSetRingLevel(), LinphoneSetRingSound(), LinphoneSetVoiceLevel(), PAGE, Request::pp, QUIT_RESET_FACTORY, QUIT_RESET_NETWORK, QUIT_UPGRADE_ADDRESSBOOK, QUIT_UPGRADE_CARDLIST, QUIT_UPGRADE_FIRMWARE, QUIT_UPGRADE_RESOURCE, QUIT_UPGRADE_WEB, Config::ringsound, DeviceInfo::room, Config::room, SceneGetQuitValue(), SceneLoad(), SceneQuit(), SceneUpdateIndicators(), SCREENSAVER_BLANK, SCREENSAVER_CLOCK, SCREENSAVER_NONE, SCREENSAVER_PHOTO, Config::screensaver_time, Config::screensaver_type, ScreenSaverIsScreenSaving(), ScreenSaverRefresh(), ScreenSetBrightness(), ITCArrayStream::stream, StringGetGuardStatus(), StringGetWorkMode(), theConfig, theDeviceInfo, theEntranceInfo, theOutdoorInfo, theOutdoorServerInfo, DeviceInfo::type, ugCheckCrc(), DeviceInfo::unit, Config::unit, UpgradeGetDeviceInfo(), UpgradeGetResult(), UpgradeIsFinished(), UpgradeSetStream(), UpgradeSetUrl(), Config::warnlevel, wsNewTextMsgCount, and wsNewVideoMsgCount.
Referenced by WebServerInit().
static void file_free_callback (void * cls) static
Definition at line 83 of file doorbell_indoor/webserver.c.
Referenced by create_response().
static ssize_t file_reader (void * cls, uint64_t pos, char * buf, size_t max) static
Definition at line 74 of file doorbell_indoor/webserver.c.
Referenced by create_response().
static int iterate_post (void * cls, enum MHD_ValueKind kind, const char * key, const char * filename, const char * content_type, const char * transfer_encoding, const char * data, uint64_t off, size_t size) static
Definition at line 34 of file doorbell_indoor/webserver.c.
References Request::connection, Request::filebuf, Request::filesize, Request::key, and UpgradeIsReady().
Referenced by create_response().
static void request_completed_callback (void * cls, struct MHD_Connection * connection, void ** con_cls, enum MHD_RequestTerminationCode toe) static
Definition at line 1367 of file doorbell_indoor/webserver.c.
References Request::filebuf, and Request::pp.
Referenced by WebServerInit().
Variable Documentation
uint8_t* fwFileBuf static
Definition at line 28 of file doorbell_indoor/webserver.c.
Referenced by create_response().
uint32_t fwFileSize static
Definition at line 29 of file doorbell_indoor/webserver.c.
Referenced by create_response().
struct MHD_Daemon* webServerDaemon
Definition at line 27 of file doorbell_indoor/webserver.c.
Referenced by WebServerExit(), and WebServerInit().
int wsNewTextMsgCount = 0 static
Definition at line 30 of file doorbell_indoor/webserver.c.
Referenced by create_response(), WebServerGetNewTextMsgCount(), and WebServerInit().
wsNewVideoMsgCount = 0 static
Definition at line 31 of file doorbell_indoor/webserver.c.
Referenced by create_response(), and WebServerGetNewVideoMsgCount().