ITE SoC SDK: remote.c File Reference
doorbell_indoor/remote.c File Reference
#include <sys/ioctl.h>
#include <assert.h>
#include <string.h>
#include <pthread.h>
#include <unistd.h>
#include "curl/curl.h"
#include "libxml/xpath.h"
#include "ite/itp.h"
#include "linphone/linphone_castor3.h"
#include "doorbell.h"
#include "scene.h"
Data Structures
struct Buffer
struct Memory
Macros
#define BUFSIZE 8
Functions
static void * RemoteOpenDoorTask (void *arg)
static void GetOutdoorInfoCallback (ServerInfo *info)
void RemoteInit (void)
Initializes remote module.
void RemoteExit (void)
Exits remote module.
static size_t WriteBufferData (void *ptr, size_t size, size_t nmemb, void *data)
static size_t WriteMemoryData (void *ptr, size_t size, size_t nmemb, void *data)
void RemoteOpenDoor (char *ip)
Opens door of the specified IP address.
bool RemoteCheckCard (char *cardnum)
Verifies the card number from the control server.
static void * RemoteInvokeCallElevatorTask (void *arg)
void RemoteCallElevator (bool up)
Invokes the elevator.
ServerInfo * RemoteGetServerInfo (void)
Gets the information of control server.
int RemoteSetOutdoorSetting (char *ip, char *area, char *building, char *unit, char *floor, char *room, char *ext)
Sets the configuration to door camera.
static void * RemoteGetWeatherTask (void *arg)
void RemoteGetWeather (RemoteGetWeatherCallback func)
Gets the weather information.
static void * RemoteSetDontDisturbConfigTask (void *arg)
void RemoteSetDontDisturbConfig (void)
Sets the do not disturb configuration to the other extension devices of indoor phone.
static void * RemoteGetDontDisturbConfigTask (void *arg)
void RemoteGetDontDisturbConfig (void)
Gets the do not disturb configuration from the first device of indoor phone.
static void * RemoteGetOutdoorInfoTask (void *arg)
void RemoteGetOutdoorInfo (char *ip, RemoteGetOutdoorInfoCallback func)
Gets the door camera information.
static void * RemoteSetOutdoorConfigTask (void *arg)
void RemoteSetOutdoorConfig (char *ip, int ringLevel, int playLevel, int recLevel, int dialTime, int voiceMemoTime, int callingTime)
Sets the door camera configuration.
Variables
ServerInfo theOutdoorServerInfo
Door camera information.
static ServerInfo serverInfo
static char * remoteOpenDoorIP
static sem_t remoteOpenDoorSem
static pthread_t remoteOpenDoorTask
static bool remoteCallElevatorTasking
static bool remoteGetWeatherTasking
static bool remoteSetDontDisturbConfigTasking
static bool remoteGetDontDisturbConfigTasking
static bool remoteGetOutdoorInfoTasking
static bool remoteQuit
Macro Definition Documentation
#define BUFSIZE 8
Definition at line 13 of file doorbell_indoor/remote.c.
Referenced by WriteBufferData().
Function Documentation
static void GetOutdoorInfoCallback (ServerInfo * info) static
Definition at line 30 of file doorbell_indoor/remote.c.
Referenced by RemoteInit().
static void* RemoteGetDontDisturbConfigTask (void * arg) static
Definition at line 755 of file doorbell_indoor/remote.c.
References Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_mode, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, Memory::memory, remoteGetDontDisturbConfigTasking, SceneUpdateIndicators(), Memory::size, theConfig, and WriteMemoryData().
Referenced by RemoteGetDontDisturbConfig().
static void* RemoteGetOutdoorInfoTask (void * arg) static
Definition at line 907 of file doorbell_indoor/remote.c.
References ServerInfo::addressBookVersion, ServerInfo::callingTime, ServerInfo::dialTime, ServerInfo::firmwareVersion, Memory::memory, ServerInfo::playLevel, ServerInfo::recLevel, remoteGetOutdoorInfoTasking, ServerInfo::ringLevel, Memory::size, ServerInfo::voiceMemoTime, and WriteMemoryData().
Referenced by RemoteGetOutdoorInfo().
static void* RemoteGetWeatherTask (void * arg) static
Definition at line 589 of file doorbell_indoor/remote.c.
References DeviceInfo::ip, Memory::memory, NetworkServerIsReady(), remoteGetWeatherTasking, Memory::size, theCenterInfo, and WriteMemoryData().
Referenced by RemoteGetWeather().
static void* RemoteInvokeCallElevatorTask (void * arg) static
Definition at line 238 of file doorbell_indoor/remote.c.
References DeviceInfo::area, DeviceInfo::building, DeviceInfo::ext, DeviceInfo::floor, DeviceInfo::ip, remoteCallElevatorTasking, DeviceInfo::room, theDeviceInfo, theEntranceInfo, and DeviceInfo::unit.
Referenced by RemoteCallElevator().
static void * RemoteOpenDoorTask (void * arg) static
Definition at line 118 of file doorbell_indoor/remote.c.
References DeviceInfo::area, DeviceInfo::building, DeviceInfo::ext, DeviceInfo::floor, remoteOpenDoorIP, remoteOpenDoorSem, remoteQuit, DeviceInfo::room, theDeviceInfo, and DeviceInfo::unit.
Referenced by RemoteInit().
static void* RemoteSetDontDisturbConfigTask (void * arg) static
Definition at line 664 of file doorbell_indoor/remote.c.
References Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_mode, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, DONOT_DISTURB_TIME, i, remoteSetDontDisturbConfigTasking, and theConfig.
Referenced by RemoteSetDontDisturbConfig().
static void* RemoteSetOutdoorConfigTask (void * arg) static
Definition at line 1113 of file doorbell_indoor/remote.c.
References remoteQuit.
Referenced by RemoteSetOutdoorConfig().
static size_t WriteBufferData (void * ptr, size_t size, size_t nmemb, void * data) static
Definition at line 80 of file doorbell_indoor/remote.c.
References Buffer::buf, BUFSIZE, and Buffer::size.
Referenced by RemoteCheckCard().
static size_t WriteMemoryData (void * ptr, size_t size, size_t nmemb, void * data) static
Definition at line 98 of file doorbell_indoor/remote.c.
References Memory::memory, and Memory::size.
Referenced by RemoteGetDontDisturbConfigTask(), RemoteGetOutdoorInfoTask(), RemoteGetServerInfo(), and RemoteGetWeatherTask().
Variable Documentation
bool remoteCallElevatorTasking static
Definition at line 21 of file doorbell_indoor/remote.c.
Referenced by RemoteCallElevator(), RemoteInit(), and RemoteInvokeCallElevatorTask().
bool remoteGetDontDisturbConfigTasking static
Definition at line 24 of file doorbell_indoor/remote.c.
Referenced by RemoteGetDontDisturbConfig(), RemoteGetDontDisturbConfigTask(), and RemoteInit().
bool remoteGetOutdoorInfoTasking static
Definition at line 25 of file doorbell_indoor/remote.c.
Referenced by RemoteGetOutdoorInfo(), RemoteGetOutdoorInfoTask(), and RemoteInit().
bool remoteGetWeatherTasking static
Definition at line 22 of file doorbell_indoor/remote.c.
Referenced by RemoteGetWeather(), RemoteGetWeatherTask(), and RemoteInit().
char* remoteOpenDoorIP static
Definition at line 18 of file doorbell_indoor/remote.c.
Referenced by RemoteInit(), RemoteOpenDoor(), and RemoteOpenDoorTask().
sem_t remoteOpenDoorSem static
Definition at line 19 of file doorbell_indoor/remote.c.
Referenced by RemoteExit(), RemoteInit(), RemoteOpenDoor(), and RemoteOpenDoorTask().
pthread_t remoteOpenDoorTask static
Definition at line 20 of file doorbell_indoor/remote.c.
Referenced by RemoteExit(), and RemoteInit().
bool remoteQuit static
Definition at line 26 of file doorbell_indoor/remote.c.
Referenced by RemoteExit(), RemoteInit(), RemoteOpenDoorTask(), and RemoteSetOutdoorConfigTask().
bool remoteSetDontDisturbConfigTasking static
Definition at line 23 of file doorbell_indoor/remote.c.
Referenced by RemoteInit(), and RemoteSetDontDisturbConfigTask().
ServerInfo serverInfo static
Definition at line 17 of file doorbell_indoor/remote.c.
Referenced by RemoteGetServerInfo(), and SettingEngineerMiscUpgradeButtonOnPress().