ITE SoC SDK: function_table.c File Reference
function_table.c File Reference
#include "ite/itu.h"
Functions
bool LogoOnEnter (ITUWidget *widget, char *param)
bool MainSetDoNotDisturbModeOnCustom (ITUWidget *widget, char *param)
bool MainNotifyMissedCallsOnCustom (ITUWidget *widget, char *param)
bool MainNotifyMessagesOnCustom (ITUWidget *widget, char *param)
bool MainNotifyGuardOnCustom (ITUWidget *widget, char *param)
bool MainNotifyNetworkOnCustom (ITUWidget *widget, char *param)
bool MainNotifyCallIncomingOnCustom (ITUWidget *widget, char *param)
bool MainNotifyVoiceMemoIncomingOnCustom (ITUWidget *widget, char *param)
bool TimeNumberButtonOnPress (ITUWidget *widget, char *param)
bool TimeClearButtonOnPress (ITUWidget *widget, char *param)
bool TimeConfirmButtonOnPress (ITUWidget *widget, char *param)
bool TimeOnEnter (ITUWidget *widget, char *param)
bool TouchCalibrationCheckBoxOnPress (ITUWidget *widget, char *param)
bool TouchCalibrationOnEnter (ITUWidget *widget, char *param)
bool TouchCalibrationOnLeave (ITUWidget *widget, char *param)
bool UpgradeOnTimer (ITUWidget *widget, char *param)
bool UpgradeOnEnter (ITUWidget *widget, char *param)
bool ScreensaverOnEnter (ITUWidget *widget, char *param)
bool MainVoiceMemoOnEnter (ITUWidget *widget, char *param)
bool MainVoiceMemoOnLeave (ITUWidget *widget, char *param)
bool MainVoiceMemoNumberListBoxOnLoad (ITUWidget *widget, char *param)
bool MainVoiceMemoTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool MainVoiceMemoLengthListBoxOnLoad (ITUWidget *widget, char *param)
bool MainVoiceMemoViewButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoStopPlayButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoRecordButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoDeleteButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoOnTimer (ITUWidget *widget, char *param)
bool MainCallElevatorDownButtonOnPress (ITUWidget *widget, char *param)
bool MainCallElevatorUpButtonOnPress (ITUWidget *widget, char *param)
bool MainWeatherOnTimer (ITUWidget *widget, char *param)
bool MainWeatherOnEnter (ITUWidget *widget, char *param)
bool MainWeatherOnLeave (ITUWidget *widget, char *param)
bool PhoneBackButtonOnPress (ITUWidget *widget, char *param)
bool PhoneNumberButtonOnPress (ITUWidget *widget, char *param)
bool PhoneManagerButtonOnPress (ITUWidget *widget, char *param)
bool PhoneCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneDialResidentOnEnter (ITUWidget *widget, char *param)
bool PhoneManagerListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneManagerCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneDialManagerOnEnter (ITUWidget *widget, char *param)
bool PhoneLobbyListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLobbyCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneDialLobbyOnEnter (ITUWidget *widget, char *param)
bool PhoneContactsRoomListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneContactsCommentListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneContactsCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsAddButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsModifyButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsDeleteButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsClearConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsOnEnter (ITUWidget *widget, char *param)
bool PhoneContactsAddConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsAddCancelButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsAddRoomButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsAddCommentButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsAddOnEnter (ITUWidget *widget, char *param)
bool PhoneContactsModifyConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsModifyCancelButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsModifyRoomButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsModifyCommentButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsModifyOnEnter (ITUWidget *widget, char *param)
bool PhoneContactsKeypadCloseButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeypadBackButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeypadConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeypadNumberButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeypadOnEnter (ITUWidget *widget, char *param)
bool PhoneContactsKeyboardCloseButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeyboardEnterButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeyboardBackButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeyboardEnUpperButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeyboardChsButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeyboardPageUpButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeyboardPageDownButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeyboardChsCharButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeyboardOnEnter (ITUWidget *widget, char *param)
bool PhoneLogMissedRoomListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogMissedTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogMissedDurationListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogMissedCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedAddButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedViewButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedDeleteButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedClearConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedOnEnter (ITUWidget *widget, char *param)
bool PhoneLogReceivedRoomListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogReceivedTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogReceivedDurationListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogReceivedCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedAddButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedViewButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedDeleteButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedClearConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedOnEnter (ITUWidget *widget, char *param)
bool PhoneLogSentRoomListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogSentTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogSentDurationListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogSentCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentAddButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentViewButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentDeleteButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentClearConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentOnEnter (ITUWidget *widget, char *param)
bool PhoneLogViewCloseButtonOnPress (ITUWidget *widget, char *param)
bool CallingVolDownButtonOnPress (ITUWidget *widget, char *param)
bool CallingVolUpButtonOnPress (ITUWidget *widget, char *param)
bool CallingRecordButtonOnPress (ITUWidget *widget, char *param)
bool CallingStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool CallingSnapshotButtonOnPress (ITUWidget *widget, char *param)
bool CallingAnswerButtonOnPress (ITUWidget *widget, char *param)
bool CallingUnlockButtonOnPress (ITUWidget *widget, char *param)
bool CallingHangUpButtonOnPress (ITUWidget *widget, char *param)
bool CallingErrorConfirmButtonOnPress (ITUWidget *widget, char *param)
bool CallingWaitingCancelButtonOnPress (ITUWidget *widget, char *param)
bool CallingWaitingConfirmButtonOnPress (ITUWidget *widget, char *param)
bool CallingConnectedOnCustom (ITUWidget *widget, char *param)
bool CallingErrorOnCustom (ITUWidget *widget, char *param)
bool CallingIncomingOnCustom (ITUWidget *widget, char *param)
bool CallingOnTimer (ITUWidget *widget, char *param)
bool CallingOnEnter (ITUWidget *widget, char *param)
bool CallingOnLeave (ITUWidget *widget, char *param)
bool CalledVolDownButtonOnPress (ITUWidget *widget, char *param)
bool CalledVolUpButtonOnPress (ITUWidget *widget, char *param)
bool CalledRecordButtonOnPress (ITUWidget *widget, char *param)
bool CalledStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool CalledSnapshotButtonOnPress (ITUWidget *widget, char *param)
bool CalledAnswerButtonOnPress (ITUWidget *widget, char *param)
bool CalledUnlockButtonOnPress (ITUWidget *widget, char *param)
bool CalledHangUpButtonOnPress (ITUWidget *widget, char *param)
bool CalledWaitingCancelButtonOnPress (ITUWidget *widget, char *param)
bool CalledWaitingConfirmButtonOnPress (ITUWidget *widget, char *param)
bool CalledIncomingOnCustom (ITUWidget *widget, char *param)
bool CalledConnectedOnCustom (ITUWidget *widget, char *param)
bool CalledOnTimer (ITUWidget *widget, char *param)
bool CalledOnEnter (ITUWidget *widget, char *param)
bool CalledOnLeave (ITUWidget *widget, char *param)
bool CalledSourceButtonOnPress (ITUWidget *widget, char *param)
bool CalledSourceListBoxOnLoad (ITUWidget *widget, char *param)
bool CalledSourceListBoxOnSelection (ITUWidget *widget, char *param)
bool MessageNotifyVideoMessageOnCustom (ITUWidget *widget, char *param)
bool MessageNotifyTextMessageOnCustom (ITUWidget *widget, char *param)
bool MessagePhotoTopicListBoxOnLoad (ITUWidget *widget, char *param)
bool MessagePhotoTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool MessagePhotoViewButtonOnPress (ITUWidget *widget, char *param)
bool MessagePhotoDeleteOnPress (ITUWidget *widget, char *param)
bool MessagePhotoDeleteConfirmOnPress (ITUWidget *widget, char *param)
bool MessagePhotoOnEnter (ITUWidget *widget, char *param)
bool MessagePhotoOnLeave (ITUWidget *widget, char *param)
bool MessagePhotoViewOnEnter (ITUWidget *widget, char *param)
bool MessagePhotoViewOnLeave (ITUWidget *widget, char *param)
bool MessagePhotoViewOnTimer (ITUWidget *widget, char *param)
bool MessageRecordIconListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageRecordTopicListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageRecordTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageRecordViewButtonOnPress (ITUWidget *widget, char *param)
bool MessageRecordDeleteOnPress (ITUWidget *widget, char *param)
bool MessageRecordDeleteConfirmOnPress (ITUWidget *widget, char *param)
bool MessageRecordOnEnter (ITUWidget *widget, char *param)
bool MessageRecordViewOnEnter (ITUWidget *widget, char *param)
bool MessageRecordViewOnLeave (ITUWidget *widget, char *param)
bool MessageRecordViewOnTimer (ITUWidget *widget, char *param)
bool MessageServiceTopicListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageServiceTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageServiceViewButtonOnPress (ITUWidget *widget, char *param)
bool MessageServiceDeleteOnPress (ITUWidget *widget, char *param)
bool MessageServiceDeleteConfirmOnPress (ITUWidget *widget, char *param)
bool MessageServiceOnEnter (ITUWidget *widget, char *param)
bool MessageServiceOnLeave (ITUWidget *widget, char *param)
bool MessageServiceViewOnEnter (ITUWidget *widget, char *param)
bool MessageServiceViewOnLeave (ITUWidget *widget, char *param)
bool MessageServiceViewOnTimer (ITUWidget *widget, char *param)
bool CameraListBoxOnLoad (ITUWidget *widget, char *param)
bool CameraListOnSelection (ITUWidget *widget, char *param)
bool CameraButtonOnPress (ITUWidget *widget, char *param)
bool CameraOnEnter (ITUWidget *widget, char *param)
bool CameraOnLeave (ITUWidget *widget, char *param)
bool CameraOnTimer (ITUWidget *widget, char *param)
bool CameraViewOnLeave (ITUWidget *widget, char *param)
bool CameraViewButtonOnPress (ITUWidget *widget, char *param)
bool CameraViewRecordButtonOnPress (ITUWidget *widget, char *param)
bool CameraViewStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool CameraViewUnlockButtonOnPress (ITUWidget *widget, char *param)
bool CameraViewSnapshotButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorOnEnter (ITUWidget *widget, char *param)
bool CameraOutdoorOnLeave (ITUWidget *widget, char *param)
bool CameraOutdoorOnTimer (ITUWidget *widget, char *param)
bool CameraOutdoorButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorRecordButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorUnlockButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorSnapshotButtonOnPress (ITUWidget *widget, char *param)
bool GuardCheckSensorListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardCheckStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardCheckOnEnter (ITUWidget *widget, char *param)
bool GuardLogSensorListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardLogTypeListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardLogTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardLogDeleteOnPress (ITUWidget *widget, char *param)
bool GuardLogDeleteConfirmOnPress (ITUWidget *widget, char *param)
bool GuardLogClearConfirmOnPress (ITUWidget *widget, char *param)
bool GuardLogOnEnter (ITUWidget *widget, char *param)
bool GuardModeIndoorRadioBoxOnPress (ITUWidget *widget, char *param)
bool GuardModeOutdoorRadioBoxOnPress (ITUWidget *widget, char *param)
bool GuardModeSleepRadioBoxOnPress (ITUWidget *widget, char *param)
bool GuardModeStopKeypadConfirmButtonOnPress (ITUWidget *widget, char *param)
bool GuardModeStopKeypadCancelButtonOnPress (ITUWidget *widget, char *param)
bool GuardModeOnEnter (ITUWidget *widget, char *param)
bool GuardModeOnLeave (ITUWidget *widget, char *param)
bool GuardPasswordOldDeleteButtonOnPress (ITUWidget *widget, char *param)
bool GuardPasswordNewDeleteButtonOnPress (ITUWidget *widget, char *param)
bool GuardPasswordConfirmDeleteButtonOnPress (ITUWidget *widget, char *param)
bool GuardPasswordNumberButtonOnPress (ITUWidget *widget, char *param)
bool GuardPasswordClearButtonOnPress (ITUWidget *widget, char *param)
bool GuardPasswordConfirmButtonOnPress (ITUWidget *widget, char *param)
bool GuardPasswordSaveButtonOnPress (ITUWidget *widget, char *param)
bool GuardPasswordOnEnter (ITUWidget *widget, char *param)
bool GuardStatusSensorListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardStatusTypeListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardStatusTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardStatusCheckButtonOnPress (ITUWidget *widget, char *param)
bool GuardStatusOnEnter (ITUWidget *widget, char *param)
bool GuardUserPasswordConfirmButtonOnPress (ITUWidget *widget, char *param)
bool GuardUserPasswordOnEnter (ITUWidget *widget, char *param)
bool GuardUserSettingSaveButtonOnPress (ITUWidget *widget, char *param)
bool GuardUserSettingCancelButtonOnPress (ITUWidget *widget, char *param)
bool GuardUserSettingOnEnter (ITUWidget *widget, char *param)
bool HouseAirConditionerNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseAirConditionerStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseAirConditionerOnButtonOnPress (ITUWidget *widget, char *param)
bool HouseAirConditionerOffButtonOnPress (ITUWidget *widget, char *param)
bool HouseAirConditionerOnEnter (ITUWidget *widget, char *param)
bool HouseCurtainNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseCurtainStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseCurtainOnButtonOnPress (ITUWidget *widget, char *param)
bool HouseCurtainOffButtonOnPress (ITUWidget *widget, char *param)
bool HouseCurtainStopButtonOnPress (ITUWidget *widget, char *param)
bool HouseCurtainOnEnter (ITUWidget *widget, char *param)
bool HouseLightNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseLightStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseLightOnButtonOnPress (ITUWidget *widget, char *param)
bool HouseLightOffButtonOnPress (ITUWidget *widget, char *param)
bool HouseLightOnEnter (ITUWidget *widget, char *param)
bool HouseModeIndoorRadioBoxOnPress (ITUWidget *widget, char *param)
bool HouseModeOutdoorRadioBoxOnPress (ITUWidget *widget, char *param)
bool HouseModeSleepRadioBoxOnPress (ITUWidget *widget, char *param)
bool HouseModeNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseModeStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseModeStatusListBoxOnSelection (ITUWidget *widget, char *param)
bool HouseModeIndoorButtonOnPress (ITUWidget *widget, char *param)
bool HouseModeOutdoorButtonOnPress (ITUWidget *widget, char *param)
bool HouseModeSleepButtonOnPress (ITUWidget *widget, char *param)
bool HouseModeSettingSaveButtonOnPress (ITUWidget *widget, char *param)
bool HouseModeOnEnter (ITUWidget *widget, char *param)
bool HouseModeOnLeave (ITUWidget *widget, char *param)
bool HousePlugNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HousePlugStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HousePlugOnButtonOnPress (ITUWidget *widget, char *param)
bool HousePlugOffButtonOnPress (ITUWidget *widget, char *param)
bool HousePlugOnEnter (ITUWidget *widget, char *param)
bool HouseTVNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseTVStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseTVOnButtonOnPress (ITUWidget *widget, char *param)
bool HouseTVOffButtonOnPress (ITUWidget *widget, char *param)
bool HouseTVOnEnter (ITUWidget *widget, char *param)
bool SettingDisplayBrightnessDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayBrightnessUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayScreensaverTimeButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayTimeKeypadConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplaySaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayOnEnter (ITUWidget *widget, char *param)
bool SettingDisplayOnLeave (ITUWidget *widget, char *param)
bool SettingEngineerPasswordConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerOnEnter (ITUWidget *widget, char *param)
bool SettingEngineerMiscClearConfirmOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscUpgradeButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscDefaultButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTerminalNumberButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTerminalBackButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTerminalClearButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTerminalConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTerminalOnEnter (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceNumberButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceBackButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceClearButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceSettingButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceOnEnter (ITUWidget *widget, char *param)
bool SettingEngineerMiscGuardWarnVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscGuardWarnVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscGuardOnEnter (ITUWidget *widget, char *param)
bool SettingEngineerMiscGuardOnLeave (ITUWidget *widget, char *param)
bool SettingEngineerNetworkIPButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkNetmaskButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkMacButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkDnsButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkGatewayButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkOnEnter (ITUWidget *widget, char *param)
bool SettingEngineerNetworkIPBackButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkIPNumberButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkIPClearButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkIPConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkIPCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkIPOnEnter (ITUWidget *widget, char *param)
bool SettingEngineerNetworkMacKeypadCloseButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkMacKeypadConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiNameListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiConnectButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiDisconnectButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiOnEnter (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiOnTimer (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiPasswordCloseButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiPasswordConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerSensorSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerSensorCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerSensorOnEnter (ITUWidget *widget, char *param)
bool SettingPhoneAudioRingRadioBoxOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioRingVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioRingVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioKeypadSoundRadioBoxOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioKeypadSoundVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioKeypadSoundVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioOnEnter (ITUWidget *widget, char *param)
bool SettingPhoneAudioOnLeave (ITUWidget *widget, char *param)
bool SettingPhoneVoiceVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceMicVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceMicVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceOnEnter (ITUWidget *widget, char *param)
bool SettingPhoneVoiceOnLeave (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeRadioBoxOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeTextBoxOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbOnEnter (ITUWidget *widget, char *param)
bool SettingSystemItemListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingSystemMessageListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingSystemOnEnter (ITUWidget *widget, char *param)
bool SettingOutdoorMainOnEnter (ITUWidget *widget, char *param)
bool SettingOutdoorMainOnLeave (ITUWidget *widget, char *param)
bool SettingOutdoorMainOnTimer (ITUWidget *widget, char *param)
bool SettingOutdoorMainMessageListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingOutdoorMainMessageListBoxOnSelection (ITUWidget *widget, char *param)
bool SettingOutdoorMainRingVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainRingVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainPlayVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainPlayVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainMicVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainMicVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMiscDialTimeDeleteButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMiscVoiceMemoTimeDeleteButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMiscCallingTimeDeleteButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMiscNumberButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMiscClearButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMiscConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMiscSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMiscOnEnter (ITUWidget *widget, char *param)
bool VideoRecordHangUpButtonOnPress (ITUWidget *widget, char *param)
bool VideoRecordOnTimer (ITUWidget *widget, char *param)
bool VideoRecordOnEnter (ITUWidget *widget, char *param)
bool VideoRecordOnLeave (ITUWidget *widget, char *param)
Variables
ITUActionFunction actionFunctions []
Function Documentation
bool CalledAnswerButtonOnPress (ITUWidget * widget, char * param)
Definition at line 205 of file layer_called.c.
References calledConnected, calledID, calledSpotted, ituLayerGoto(), LinphoneAnswer(), LinphoneTerminate(), and SceneHangUp().
bool CalledConnectedOnCustom (ITUWidget * widget, char * param)
Definition at line 509 of file layer_called.c.
References calledConnected, calledCountDown, calledLastTick, calledMaxVol, Config::calling_time, ituSpriteGoto(), ituTextSetString, LinphoneGetVoiceLevel(), and theConfig.
bool CalledHangUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 228 of file layer_called.c.
References ituButtonSetPressed(), LinphoneTerminate(), and SceneHangUp().
bool CalledIncomingOnCustom (ITUWidget * widget, char * param)
Definition at line 401 of file layer_called.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, calledPendingAddr, calledPendingID, calledPendingVideo, callSpottedStatus, Config::dial_time, DeviceInfo::floor, ituTextSetString, ituWidgetDisable, ituWidgetSetVisible, DeviceInfo::room, spotCountDown, spotLastTick, SPOTTED_INIT, StringGetDeviceType(), StringGetRoomAddress(), theConfig, DeviceInfo::type, and DeviceInfo::unit.
bool CalledOnEnter (ITUWidget * widget, char * param)
Definition at line 620 of file layer_called.c.
References calledConnected, calledCountDown, calledInVideoState, calledIPCameraInfoCount, calledMaxVol, calledRingLevelOld, calledSpotted, calledVoiceLevelOld, itcTreeGetChildCount, ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, ituWidgetSetVisible, LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetWindowID(), snapshotCountDown, spotCountDown, and theScene.
bool CalledOnLeave (ITUWidget * widget, char * param)
Definition at line 707 of file layer_called.c.
References calledID, calledInVideoState, calledPendingID, calledRingLevelOld, calledVoiceLevelOld, CaptureStopRecord(), ConfigSave(), LinphoneGetRingLevel(), and LinphoneGetVoiceLevel().
bool CalledOnTimer (ITUWidget * widget, char * param)
Definition at line 530 of file layer_called.c.
References calledCountDown, calledID, calledLastTick, calledPendingID, CalledWaitingConfirmButtonOnSimulatePressing(), callSpottedStatus, font::f, ituLayerGoto(), ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, LinphoneAnswer(), LinphoneTerminate(), LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, SceneHangUp(), snapshotCountDown, spotCountDown, spotLastTick, SPOTTED_INIT, and SPOTTED_REJECT.
bool CalledRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 176 of file layer_called.c.
References calledInVideoState, CaptureStartRecord(), DeviceInfo::ip, LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, MEDIA_AUDIO, and MEDIA_VIDEO.
bool CalledSnapshotButtonOnPress (ITUWidget * widget, char * param)
Definition at line 195 of file layer_called.c.
References CaptureSnapshot(), DeviceInfo::ip, SNAPSHOT_COUNT, and snapshotCountDown.
bool CalledSourceButtonOnPress (ITUWidget * widget, char * param)
Definition at line 304 of file layer_called.c.
References ituWidgetIsVisible, and ituWidgetSetVisible.
bool CalledSourceListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 318 of file layer_called.c.
References AddressBookGetIPCameraInfoArray(), DeviceInfo::alias, ITUColor::blue, calledIPCameraInfoCount, ITCTreeTag::child, ITUWidgetTag::color, ITUListBoxTag::focusIndex, ITUColor::green, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetBackColor(), ituTextSetString, ituWidgetSetCustomData, MAX_IPCAMERA_COUNT, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITUColor::red, ITCTreeTag::sibling, and ITUScrollText::text.
bool CalledSourceListBoxOnSelection (ITUWidget * widget, char * param)
Definition at line 371 of file layer_called.c.
References calledVideoRecordEnable, CaptureStopRecord(), ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituWidgetGetCustomData, ituWidgetSetVisible, and SceneCameraIsViewing().
bool CalledStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 188 of file layer_called.c.
References CaptureStopRecord(), and LockRecordButton.
bool CalledUnlockButtonOnPress (ITUWidget * widget, char * param)
Definition at line 222 of file layer_called.c.
References SceneOpenDoor().
bool CalledVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 108 of file layer_called.c.
References calledConnected, calledMaxVol, ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetRingLevel(), and LinphoneSetVoiceLevel().
bool CalledVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 142 of file layer_called.c.
References calledConnected, calledMaxVol, ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetRingLevel(), and LinphoneSetVoiceLevel().
bool CalledWaitingCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 238 of file layer_called.c.
References calledPendingID, calledSpotted, callSpottedStatus, ituButtonSetPressed(), ituWidgetEnable, and SPOTTED_REJECT.
bool CalledWaitingConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 252 of file layer_called.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, calledID, calledInVideoState, calledPendingAddr, calledPendingID, calledPendingVideo, calledSpotted, calledVideoRecordEnable, callSpottedStatus, CaptureStopRecord(), DEVICE_OUTDOOR, DEVICE_WALL, DeviceInfo::floor, ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, LinphoneSetWindowID(), DeviceInfo::room, SPOTTED_ALLOW, StringGetRoomAddress(), DeviceInfo::type, and DeviceInfo::unit.
bool CallingAnswerButtonOnPress (ITUWidget * widget, char * param)
Definition at line 188 of file doorbell_indoor/layer_calling.c.
References callingConnected, callingID, ituLayerGoto(), LinphoneAnswer(), LinphoneTerminate(), and SceneHangUp().
bool CallingConnectedOnCustom (ITUWidget * widget, char * param)
Definition at line 599 of file doorbell_indoor/layer_calling.c.
References Config::calling_time, callingConnected, callingCountDown, callingID, callingLastTick, callingMaxVol, dialCountDown, ituSpriteGoto(), ituTextSetString, LinphoneGetVoiceLevel(), and theConfig.
Referenced by CallConnected().
bool CallingErrorConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 231 of file doorbell_indoor/layer_calling.c.
References callingErrorCountDown.
bool CallingErrorOnCustom (ITUWidget * widget, char * param)
Definition at line 624 of file doorbell_indoor/layer_calling.c.
References callingErrorCountDown, callingErrorLastTick, callingInVideoState, callingManagerCount, callingManagerIndex, callingManagerIPAddr, Config::dial_time, dialCountDown, dialLastTick, ERROR_COUNTDOWN, DeviceInfo::ip, ituTextSetString, ituWidgetSetVisible, SceneSetRemoteIP(), theCenterInfo, and theConfig.
bool CallingHangUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 219 of file doorbell_indoor/layer_calling.c.
References callingHangUp, ituButtonSetPressed(), LinphoneTerminate(), and SceneHangUp().
bool CallingIncomingOnCustom (ITUWidget * widget, char * param)
Definition at line 690 of file doorbell_indoor/layer_calling.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, callingErrorCountDown, callingPendingAddr, callingPendingID, callingPendingVideo, callSpottedStatus, Config::dial_time, DeviceInfo::floor, ituTextSetString, ituWidgetDisable, ituWidgetSetVisible, DeviceInfo::room, spotCountDown, spotLastTick, SPOTTED_INIT, StringGetDeviceType(), StringGetRoomAddress(), theConfig, DeviceInfo::type, and DeviceInfo::unit.
bool CallingOnEnter (ITUWidget * widget, char * param)
Definition at line 901 of file doorbell_indoor/layer_calling.c.
References callingConnected, callingCountDown, callingErrorCountDown, callingHangUp, callingInVideoState, callingMaxVol, callingRingLevelOld, callingVoiceLevelOld, itcTreeGetChildCount, ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, ituWidgetSetVisible, LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetWindowID(), snapshotCountDown, spotCountDown, and theScene.
bool CallingOnLeave (ITUWidget * widget, char * param)
Definition at line 983 of file doorbell_indoor/layer_calling.c.
References callingHangUp, callingID, callingInVideoState, callingPendingID, callingRingLevelOld, callingVoiceLevelOld, CaptureStopRecord(), ConfigSave(), ituWidgetSetVisible, LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneTerminate(), and SceneHangUp().
bool CallingOnTimer (ITUWidget * widget, char * param)
Definition at line 724 of file doorbell_indoor/layer_calling.c.
References callingCountDown, callingErrorCountDown, callingErrorLastTick, callingInVideoState, callingLastTick, callingManagerCount, callingManagerIndex, callingManagerIPAddr, callingPendingID, CallingWaitingConfirmButtonOnSimulatePressing(), callSpottedStatus, Config::dial_time, dialCountDown, dialLastTick, font::f, DeviceInfo::ip, ituLayerGoto(), ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, LinphoneTerminate(), LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, SceneHangUp(), SceneSetRemoteIP(), snapshotCountDown, spotCountDown, spotLastTick, SPOTTED_INIT, SPOTTED_REJECT, theCenterInfo, and theConfig.
Referenced by SceneRun().
bool CallingRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 169 of file doorbell_indoor/layer_calling.c.
References callingInVideoState, CaptureStartRecord(), DeviceInfo::ip, LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, MEDIA_AUDIO, and MEDIA_VIDEO.
bool CallingSnapshotButtonOnPress (ITUWidget * widget, char * param)
Definition at line 209 of file doorbell_indoor/layer_calling.c.
References CaptureSnapshot(), DeviceInfo::ip, SNAPSHOT_COUNT, and snapshotCountDown.
bool CallingStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 181 of file doorbell_indoor/layer_calling.c.
References CaptureStopRecord(), and LockRecordButton.
bool CallingUnlockButtonOnPress (ITUWidget * widget, char * param)
Definition at line 203 of file doorbell_indoor/layer_calling.c.
References SceneOpenDoor().
bool CallingVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 101 of file doorbell_indoor/layer_calling.c.
References callingConnected, callingMaxVol, ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetRingLevel(), and LinphoneSetVoiceLevel().
bool CallingVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 135 of file doorbell_indoor/layer_calling.c.
References callingConnected, callingMaxVol, ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetRingLevel(), and LinphoneSetVoiceLevel().
bool CallingWaitingCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 237 of file doorbell_indoor/layer_calling.c.
References callingPendingID, callSpottedStatus, ituButtonSetPressed(), ituWidgetEnable, and SPOTTED_REJECT.
bool CallingWaitingConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 250 of file doorbell_indoor/layer_calling.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, callingID, callingInVideoState, callingPendingAddr, callingPendingID, callingPendingVideo, callingVideoRecordEnable, callSpottedStatus, CaptureStopRecord(), DEVICE_OUTDOOR, DEVICE_WALL, DeviceInfo::floor, ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, DeviceInfo::room, SPOTTED_ALLOW, StringGetRoomAddress(), DeviceInfo::type, and DeviceInfo::unit.
bool CameraButtonOnPress (ITUWidget * widget, char * param)
Definition at line 140 of file layer_camera.c.
References CameraViewShow(), ITUListBoxTag::focusIndex, DeviceInfo::ip, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, LinphoneSetWindowID(), and ITUScrollText::text.
bool CameraListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 30 of file layer_camera.c.
References AddressBookGetCameraInfoArray(), DeviceInfo::alias, DeviceInfo::area, DeviceInfo::building, ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, MAX_CAMERA_COUNT, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, StringGetCameraPosition(), theDeviceInfo, and DeviceInfo::unit.
bool CameraListOnSelection (ITUWidget * widget, char * param)
Definition at line 109 of file layer_camera.c.
References cameraVideoRecordEnable, CameraWatch(), CaptureStopRecord(), ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, ituWidgetSetVisible, LinphoneStopCamera(), SceneCameraIsViewing(), and theScene.
bool CameraOnEnter (ITUWidget * widget, char * param)
Definition at line 219 of file layer_camera.c.
References cameraCountDown, cameraVideoRecordEnable, cameraViewTimeout, CaptureGetPath(), DEVICE_INDOOR2, ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, LinphoneSetWindowID(), SceneCameraSetViewing(), theDeviceInfo, theScene, and DeviceInfo::type.
bool CameraOnLeave (ITUWidget * widget, char * param)
Definition at line 278 of file layer_camera.c.
References cameraVideoRecordEnable, CaptureStopRecord(), LinphoneStopCamera(), SceneCameraSetViewing(), and SceneContinuePlayGuardAlarm().
bool CameraOnTimer (ITUWidget * widget, char * param)
Definition at line 153 of file layer_camera.c.
References cameraCountDown, cameraLastTick, CameraLockRecordButton, CameraLockRecordButtonCountDown, CameraLockRecordButtonLastTick, cameraVideoRecordEnable, cameraViewTimeout, CaptureStopRecord(), EVENT_CUSTOM_CAMERA_TIMEOUT, font::f, ituSceneSendEvent(), ituTextSetString, ituWidgetSetVisible, LinphoneStopCamera(), SceneCameraIsViewing(), SceneCameraSetViewing(), SceneContinuePlayGuardAlarm(), and theScene.
bool CameraOutdoorButtonOnPress (ITUWidget * widget, char * param)
Definition at line 23 of file layer_camera_outdoor.c.
References ituSceneFindWidget(), LinphoneSetWindowID(), and theScene.
bool CameraOutdoorOnEnter (ITUWidget * widget, char * param)
Definition at line 133 of file layer_camera_outdoor.c.
References DeviceInfo::alias, DeviceInfo::area, DeviceInfo::building, CAMERA_TIMEOUT, cameraOutdoorCountDown, cameraOutdoorLastTick, cameraOutdoorVideoRecordEnable, CaptureGetPath(), DEVICE_INDOOR2, DeviceInfo::ip, ituSceneFindWidget(), ituTextSetString, LinphoneSetWindowID(), LinphoneWatchCamera(), SceneCameraSetViewing(), SceneSetRemoteIP(), snapshotCountDown, StringGetCameraPosition(), theDeviceInfo, theEntranceInfo, theScene, DeviceInfo::type, and DeviceInfo::unit.
bool CameraOutdoorOnLeave (ITUWidget * widget, char * param)
Definition at line 186 of file layer_camera_outdoor.c.
References cameraOutdoorCountDown, cameraOutdoorVideoRecordEnable, CaptureStopRecord(), LinphoneStopCamera(), SceneCameraSetViewing(), and SceneContinuePlayGuardAlarm().
bool CameraOutdoorOnTimer (ITUWidget * widget, char * param)
Definition at line 73 of file layer_camera_outdoor.c.
References cameraOutdoorCountDown, cameraOutdoorLastTick, cameraOutdoorVideoRecordEnable, CaptureStopRecord(), EVENT_CUSTOM_CAMERA_TIMEOUT, font::f, ituSceneSendEvent(), ituTextSetString, LinphoneStopCamera(), LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, snapshotCountDown, and theScene.
bool CameraOutdoorRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 34 of file layer_camera_outdoor.c.
References cameraOutdoorVideoRecordEnable, CaptureStartRecord(), DeviceInfo::ip, LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, MEDIA_VIDEO, and theEntranceInfo.
bool CameraOutdoorSnapshotButtonOnPress (ITUWidget * widget, char * param)
Definition at line 63 of file layer_camera_outdoor.c.
References CaptureSnapshot(), DeviceInfo::ip, SNAPSHOT_COUNT, snapshotCountDown, and theEntranceInfo.
bool CameraOutdoorStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 48 of file layer_camera_outdoor.c.
References cameraOutdoorVideoRecordEnable, CaptureStopRecord(), and LockRecordButton.
bool CameraOutdoorUnlockButtonOnPress (ITUWidget * widget, char * param)
Definition at line 57 of file layer_camera_outdoor.c.
References DeviceInfo::ip, SceneOpenDoor(), and theEntranceInfo.
bool CameraViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 29 of file layer_camera_view.c.
References cameraViewIsLeaving, CameraViewSetCameraBackgroundWindowID(), ituSceneExecuteCommand(), ituSceneFindWidget(), and theScene.
bool CameraViewOnLeave (ITUWidget * widget, char * param)
Definition at line 99 of file layer_camera_view.c.
References cameraViewVideoRecordEnable, CaptureStopRecord(), LinphoneStopCamera(), SceneCameraSetViewing(), and SceneContinuePlayGuardAlarm().
bool CameraViewRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 41 of file layer_camera_view.c.
References CameraLockRecordButton, CameraLockRecordButtonCountDown, CameraLockRecordButtonLastTick, cameraViewVideoRecordEnable, CaptureStartRecord(), DeviceInfo::ip, and MEDIA_VIDEO.
bool CameraViewSnapshotButtonOnPress (ITUWidget * widget, char * param)
Definition at line 70 of file layer_camera_view.c.
References CameraViewEnableSnapshot(), cameraViewIsSnapshoting, CaptureSnapshot(), DeviceInfo::ip, ituSceneExecuteCommand(), and theScene.
bool CameraViewStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 55 of file layer_camera_view.c.
References CameraLockRecordButton, cameraViewVideoRecordEnable, and CaptureStopRecord().
bool CameraViewUnlockButtonOnPress (ITUWidget * widget, char * param)
Definition at line 64 of file layer_camera_view.c.
References DeviceInfo::ip, and SceneOpenDoor().
bool GuardCheckOnEnter (ITUWidget * widget, char * param)
Definition at line 114 of file layer_guard_check.c.
References GUARD_INDOOR, Config::guard_indoor_sensors, Config::guard_mode, GUARD_OUTDOOR, Config::guard_outdoor_sensors, GUARD_SLEEP, Config::guard_sleep_sensors, guardSensors, and theConfig.
bool GuardCheckSensorListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 10 of file layer_guard_check.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GUARD_SENSOR_COUNT, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and StringGetGuardSensor().
bool GuardCheckStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 59 of file layer_guard_check.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GUARD_ALARM, GUARD_SENSOR_COUNT, GuardGetSensorStatus(), guardSensors, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and StringGetGuardSensorStatus().
bool GuardLogClearConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 215 of file layer_guard_log.c.
References GuardClearLog(), GuardLogReload(), ituSceneExecuteCommand(), and theScene.
bool GuardLogDeleteConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 192 of file layer_guard_log.c.
References ITUListBoxTag::focusIndex, GuardDeleteLog(), GuardLogReload(), i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, and theScene.
bool GuardLogDeleteOnPress (ITUWidget * widget, char * param)
Definition at line 177 of file layer_guard_log.c.
References ITUListBoxTag::focusIndex.
bool GuardLogOnEnter (ITUWidget * widget, char * param)
Definition at line 222 of file layer_guard_log.c.
References ituSceneFindWidget(), and theScene.
bool GuardLogSensorListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 13 of file layer_guard_log.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GUARD_HANDLED, GuardGetLog(), GuardGetLogCount(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, GuardLog::sensor, ITCTreeTag::sibling, GuardLog::state, StringGetGuardSensor(), StringGetGuardType(), and GuardLog::type.
bool GuardLogTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 121 of file layer_guard_log.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GuardGetLog(), GuardGetLogCount(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and GuardLog::timestamp.
bool GuardLogTypeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 68 of file layer_guard_log.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GUARD_HANDLED, GuardGetLog(), GuardGetLogCount(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, GuardLog::state, GuardLog::status, StringGetGuardState(), and StringGetGuardStatus().
bool GuardModeIndoorRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 16 of file layer_guard_mode.c.
References GUARD_INDOOR, Config::guard_mode, GuardIsAlarming(), GuardSetMode(), and theConfig.
bool GuardModeOnEnter (ITUWidget * widget, char * param)
Definition at line 108 of file layer_guard_mode.c.
References GUARD_INDOOR, Config::guard_mode, GUARD_NONE, GUARD_OUTDOOR, GUARD_SLEEP, GuardIsAlarming(), guardModeOld, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituWidgetDisable, theConfig, and theScene.
bool GuardModeOnLeave (ITUWidget * widget, char * param)
Definition at line 177 of file layer_guard_mode.c.
References ConfigSave(), Config::guard_mode, guardModeOld, and theConfig.
bool GuardModeOutdoorRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 29 of file layer_guard_mode.c.
References Config::guard_mode, GUARD_OUTDOOR, GuardIsAlarming(), GuardSetMode(), and theConfig.
bool GuardModeSleepRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 43 of file layer_guard_mode.c.
References Config::guard_mode, GUARD_SLEEP, GuardIsAlarming(), GuardSetMode(), and theConfig.
bool GuardModeStopKeypadCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 89 of file layer_guard_mode.c.
References GUARD_INDOOR, Config::guard_mode, GUARD_OUTDOOR, GUARD_SLEEP, ituRadioBoxSetChecked(), and theConfig.
bool GuardModeStopKeypadConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 56 of file layer_guard_mode.c.
References GUARD_INDOOR, Config::guard_mode, GUARD_NONE, GUARD_OUTDOOR, Config::guard_password, GUARD_SLEEP, GuardSetMode(), ituRadioBoxSetChecked(), ituTextGetString, ituWidgetEnable, and theConfig.
bool GuardPasswordClearButtonOnPress (ITUWidget * widget, char * param)
Definition at line 58 of file layer_guard_password.c.
References guardPasswordNewTextBox, guardPasswordOldTextBox, and ituTextBoxSetString().
bool GuardPasswordConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 73 of file layer_guard_password.c.
References guardPasswordConfirmTextBox, and guardPasswordNewTextBox.
bool GuardPasswordConfirmDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 27 of file layer_guard_password.c.
References guardPasswordConfirmTextBox, and ituTextBoxBack().
bool GuardPasswordNewDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 20 of file layer_guard_password.c.
References guardPasswordNewTextBox, and ituTextBoxBack().
bool GuardPasswordNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 34 of file layer_guard_password.c.
References guardPasswordConfirmTextBox, guardPasswordNewTextBox, ituTextBoxInput(), ituTextGetString, ituTextSetString, ITUTextBox::maxLen, and ITUButton::text.
bool GuardPasswordOldDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 13 of file layer_guard_password.c.
References guardPasswordOldTextBox, and ituTextBoxBack().
bool GuardPasswordOnEnter (ITUWidget * widget, char * param)
Definition at line 107 of file layer_guard_password.c.
References guardPasswordOldTextBox, ituSceneFindWidget(), ituTextBoxSetString(), and theScene.
bool GuardPasswordSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 85 of file layer_guard_password.c.
References ConfigSave(), Config::guard_password, ituTextBoxGetString(), and theConfig.
bool GuardStatusCheckButtonOnPress (ITUWidget * widget, char * param)
Definition at line 164 of file layer_guard_status.c.
bool GuardStatusOnEnter (ITUWidget * widget, char * param)
Definition at line 169 of file layer_guard_status.c.
References ituSceneFindWidget(), and theScene.
bool GuardStatusSensorListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 12 of file layer_guard_status.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GUARD_SENSOR_COUNT, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and StringGetGuardSensor().
bool GuardStatusTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 111 of file layer_guard_status.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GUARD_SENSOR_COUNT, GuardGetSensorTime(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool GuardStatusTypeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 60 of file layer_guard_status.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GUARD_SENSOR_COUNT, GuardGetSensorStatus(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and StringGetGuardStatus().
bool GuardUserPasswordConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 10 of file layer_guard_user.c.
References Config::guard_password, ituTextGetString, and theConfig.
bool GuardUserPasswordOnEnter (ITUWidget * widget, char * param)
Definition at line 20 of file layer_guard_user.c.
References ituSceneFindWidget(), ituTextBoxSetString(), and theScene.
bool GuardUserSettingCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_guard_user_setting.c.
References ituCheckBoxSetChecked().
bool GuardUserSettingOnEnter (ITUWidget * widget, char * param)
Definition at line 94 of file layer_guard_user_setting.c.
References GUARD_AREA, GUARD_DOOR, GUARD_EMERGENCY, GUARD_GAS, Config::guard_indoor_sensors, GUARD_INFRARED, Config::guard_outdoor_sensors, GUARD_ROB, Config::guard_sleep_sensors, GUARD_SMOKE, GUARD_WINDOW, ituCheckBoxSetChecked(), ituSceneFindWidget(), theConfig, and theScene.
bool GuardUserSettingSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 33 of file layer_guard_user_setting.c.
References ConfigSave(), GUARD_AREA, GUARD_DOOR, GUARD_EMERGENCY, GUARD_GAS, Config::guard_indoor_sensors, GUARD_INFRARED, Config::guard_mode, Config::guard_outdoor_sensors, GUARD_ROB, Config::guard_sleep_sensors, GUARD_SMOKE, GUARD_WINDOW, GuardSetMode(), ituCheckBoxIsChecked(), and theConfig.
bool HouseAirConditionerNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_house_airconditioner.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_AIRCONDITIONER, HOUSE_MAX_AIRCONDITIONER_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseAirConditionerOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 136 of file layer_house_airconditioner.c.
References ITUListBoxTag::focusIndex, HOUSE_AIRCONDITIONER, HOUSE_CLOSE, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseAirConditionerOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 113 of file layer_house_airconditioner.c.
References ITUListBoxTag::focusIndex, HOUSE_AIRCONDITIONER, HOUSE_OPEN, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseAirConditionerOnEnter (ITUWidget * widget, char * param)
Definition at line 160 of file layer_house_airconditioner.c.
References ituSceneFindWidget(), and theScene.
bool HouseAirConditionerStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 63 of file layer_house_airconditioner.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_AIRCONDITIONER, HOUSE_MAX_AIRCONDITIONER_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
bool HouseCurtainNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_house_curtain.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_CURTAIN, HOUSE_MAX_CURTAIN_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseCurtainOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 136 of file layer_house_curtain.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_CURTAIN, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpritePlay(), and ituWidgetGetCustomData.
bool HouseCurtainOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 113 of file layer_house_curtain.c.
References ITUListBoxTag::focusIndex, HOUSE_CURTAIN, HOUSE_OPEN, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpritePlay(), and ituWidgetGetCustomData.
bool HouseCurtainOnEnter (ITUWidget * widget, char * param)
Definition at line 172 of file layer_house_curtain.c.
References ituSceneFindWidget(), and theScene.
bool HouseCurtainStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 63 of file layer_house_curtain.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_CURTAIN, HOUSE_MAX_CURTAIN_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
bool HouseCurtainStopButtonOnPress (ITUWidget * widget, char * param)
Definition at line 159 of file layer_house_curtain.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_CURTAIN, HouseExecAction(), itcTreeGetChildAt, ituSpriteStop(), and ituWidgetGetCustomData.
bool HouseLightNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_house_light.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_LIGHT, HOUSE_MAX_LIGHT_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseLightOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 137 of file layer_house_light.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_LIGHT, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseLightOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 113 of file layer_house_light.c.
References ITUListBoxTag::focusIndex, HOUSE_LIGHT, HOUSE_OPEN, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseLightOnEnter (ITUWidget * widget, char * param)
Definition at line 160 of file layer_house_light.c.
References ituSceneFindWidget(), and theScene.
bool HouseLightStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 63 of file layer_house_light.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_LIGHT, HOUSE_MAX_LIGHT_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
bool HouseModeIndoorButtonOnPress (ITUWidget * widget, char * param)
Definition at line 188 of file layer_house_mode.c.
References HOUSE_AIRCONDITIONER, HOUSE_CURTAIN, HOUSE_INDOOR, Config::house_indoor_airconditioners, Config::house_indoor_curtains, Config::house_indoor_lights, Config::house_indoor_plugs, Config::house_indoor_tvs, HOUSE_LIGHT, HOUSE_OFF, HOUSE_ON, HOUSE_PLUG, HOUSE_TV, HouseGetInfoArray(), houseMode, houseModeCount, i, ituTextSetString, MAX_MODE_COUNT, HouseInfo::status, StringGetHouseMode(), and theConfig.
bool HouseModeIndoorRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 19 of file layer_house_mode.c.
References HOUSE_INDOOR, Config::house_mode, HOUSE_NONE, HouseSetMode(), ituRadioBoxSetChecked(), and theConfig.
bool HouseModeNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 67 of file layer_house_mode.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, houseModeCount, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseModeOnEnter (ITUWidget * widget, char * param)
Definition at line 565 of file layer_house_mode.c.
References HOUSE_INDOOR, Config::house_mode, HOUSE_NONE, HOUSE_OUTDOOR, HOUSE_SLEEP, houseModeCount, houseModeOld, ituRadioBoxSetChecked(), ituSceneFindWidget(), theConfig, and theScene.
bool HouseModeOnLeave (ITUWidget * widget, char * param)
Definition at line 606 of file layer_house_mode.c.
References ConfigSave(), Config::house_mode, houseModeOld, and theConfig.
bool HouseModeOutdoorButtonOnPress (ITUWidget * widget, char * param)
Definition at line 254 of file layer_house_mode.c.
References HOUSE_AIRCONDITIONER, HOUSE_CURTAIN, HOUSE_LIGHT, HOUSE_OFF, HOUSE_ON, HOUSE_OUTDOOR, Config::house_outdoor_airconditioners, Config::house_outdoor_curtains, Config::house_outdoor_lights, Config::house_outdoor_plugs, Config::house_outdoor_tvs, HOUSE_PLUG, HOUSE_TV, HouseGetInfoArray(), houseMode, houseModeCount, i, ituTextSetString, MAX_MODE_COUNT, HouseInfo::status, StringGetHouseMode(), and theConfig.
bool HouseModeOutdoorRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 35 of file layer_house_mode.c.
References Config::house_mode, HOUSE_NONE, HOUSE_OUTDOOR, HouseSetMode(), ituRadioBoxSetChecked(), and theConfig.
bool HouseModeSettingSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 386 of file layer_house_mode.c.
References ConfigSave(), HOUSE_AIRCONDITIONER, HOUSE_CURTAIN, HOUSE_INDOOR, Config::house_indoor_airconditioners, Config::house_indoor_curtains, Config::house_indoor_lights, Config::house_indoor_plugs, Config::house_indoor_tvs, HOUSE_LIGHT, HOUSE_ON, HOUSE_OUTDOOR, Config::house_outdoor_airconditioners, Config::house_outdoor_curtains, Config::house_outdoor_lights, Config::house_outdoor_plugs, Config::house_outdoor_tvs, HOUSE_PLUG, HOUSE_SLEEP, Config::house_sleep_airconditioners, Config::house_sleep_curtains, Config::house_sleep_lights, Config::house_sleep_plugs, Config::house_sleep_tvs, HOUSE_TV, houseMode, houseModeCount, i, and theConfig.
bool HouseModeSleepButtonOnPress (ITUWidget * widget, char * param)
Definition at line 320 of file layer_house_mode.c.
References HOUSE_AIRCONDITIONER, HOUSE_CURTAIN, HOUSE_LIGHT, HOUSE_OFF, HOUSE_ON, HOUSE_PLUG, HOUSE_SLEEP, Config::house_sleep_airconditioners, Config::house_sleep_curtains, Config::house_sleep_lights, Config::house_sleep_plugs, Config::house_sleep_tvs, HOUSE_TV, HouseGetInfoArray(), houseMode, houseModeCount, i, ituTextSetString, MAX_MODE_COUNT, HouseInfo::status, StringGetHouseMode(), and theConfig.
bool HouseModeSleepRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 51 of file layer_house_mode.c.
References Config::house_mode, HOUSE_NONE, HOUSE_SLEEP, HouseSetMode(), ituRadioBoxSetChecked(), and theConfig.
bool HouseModeStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 116 of file layer_house_mode.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, houseModeCount, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
bool HouseModeStatusListBoxOnSelection (ITUWidget * widget, char * param)
Definition at line 168 of file layer_house_mode.c.
References ITUListBoxTag::focusIndex, HOUSE_OFF, HOUSE_ON, itcTreeGetChildAt, ituListBoxSelect(), ituTextSetString, ituWidgetGetCustomData, HouseInfo::status, and StringGetHouseStatus().
bool HousePlugNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_house_plug.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_MAX_PLUG_COUNT, HOUSE_PLUG, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HousePlugOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 136 of file layer_house_plug.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_PLUG, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HousePlugOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 113 of file layer_house_plug.c.
References ITUListBoxTag::focusIndex, HOUSE_OPEN, HOUSE_PLUG, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HousePlugOnEnter (ITUWidget * widget, char * param)
Definition at line 159 of file layer_house_plug.c.
References ituSceneFindWidget(), and theScene.
bool HousePlugStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 63 of file layer_house_plug.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_MAX_PLUG_COUNT, HOUSE_PLUG, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
bool HouseTVNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 15 of file layer_house_tv.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_MAX_TV_COUNT, HOUSE_TV, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseTVOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 138 of file layer_house_tv.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_TV, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseTVOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 114 of file layer_house_tv.c.
References ITUListBoxTag::focusIndex, HOUSE_OPEN, HOUSE_TV, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseTVOnEnter (ITUWidget * widget, char * param)
Definition at line 162 of file layer_house_tv.c.
References ituSceneFindWidget(), and theScene.
bool HouseTVStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 64 of file layer_house_tv.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_MAX_TV_COUNT, HOUSE_TV, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
bool LogoOnEnter (ITUWidget * widget, char * param)
Definition at line 11 of file layer_logo.c.
References ituLayerGoto(), ituSceneFindWidget(), theConfig, theScene, and Config::touch_calibration.
bool MainCallElevatorDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 8 of file layer_main_callelevator.c.
References RemoteCallElevator().
bool MainCallElevatorUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 14 of file layer_main_callelevator.c.
References RemoteCallElevator().
bool MainNotifyCallIncomingOnCustom (ITUWidget * widget, char * param)
Definition at line 175 of file layer_main.c.
References CalledIncomingShow(), ituLayerGoto(), ituSceneFindWidget(), and theScene.
bool MainNotifyGuardOnCustom (ITUWidget * widget, char * param)
Definition at line 139 of file layer_main.c.
References ituSceneFindWidget(), ituSpriteGoto(), and theScene.
bool MainNotifyMessagesOnCustom (ITUWidget * widget, char * param)
Definition at line 107 of file layer_main.c.
References ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, ituWidgetSetVisible, and theScene.
bool MainNotifyMissedCallsOnCustom (ITUWidget * widget, char * param)
Definition at line 57 of file layer_main.c.
References ITUSpriteTag::frame, ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, ituWidgetSetVisible, and theScene.
bool MainNotifyNetworkOnCustom (ITUWidget * widget, char * param)
Definition at line 157 of file layer_main.c.
References ituSceneFindWidget(), ituSpriteGoto(), and theScene.
bool MainNotifyVoiceMemoIncomingOnCustom (ITUWidget * widget, char * param)
Definition at line 192 of file layer_main.c.
References DEVICE_INDOOR2, ituLayerGoto(), ituSceneFindWidget(), theDeviceInfo, theScene, DeviceInfo::type, and VideoRecordIncomingShow().
bool MainSetDoNotDisturbModeOnCustom (ITUWidget * widget, char * param)
Definition at line 22 of file layer_main.c.
References DONOT_DISTURB_ALL, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_TIME, ituSceneFindWidget(), ituSpriteGoto(), ituWidgetIsVisible, and theScene.
bool MainVoiceMemoDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 205 of file layer_main_voicememo.c.
References ITUListBoxTag::focusIndex.
bool MainVoiceMemoDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 227 of file layer_main_voicememo.c.
References ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, MainMenuNotifyUnplayVoiceMemo(), mainVoiceMemoPlaying, mainVoiceMemoPlayingIndex, MainVoiceMemoReload(), SceneContinuePlayGuardAlarm(), theScene, VoiceMemoDeleteEntry(), VoiceMemoGetUnplayCount(), and VoiceMemoStopPlay().
bool MainVoiceMemoLengthListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 139 of file layer_main_voicememo.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VoiceMemoEntry::played, VoiceMemoEntry::sec, ITCTreeTag::sibling, VoiceMemoGetCount(), and VoiceMemoGetEntry().
bool MainVoiceMemoNumberListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 22 of file layer_main_voicememo.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, VoiceMemoEntry::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VoiceMemoEntry::played, ITCTreeTag::sibling, VoiceMemoGetCount(), and VoiceMemoGetEntry().
bool MainVoiceMemoOnEnter (ITUWidget * widget, char * param)
Definition at line 360 of file layer_main_voicememo.c.
References ituSceneFindWidget(), ituWidgetSetVisible, MainMenuNotifyUnplayVoiceMemo(), mainVoiceMemoPlaying, mainVoiceMemoPlayingCountDown, mainVoiceMemoPlayingIndex, mainVoiceMemoRecording, SceneSetReady(), theScene, and VoiceMemoGetUnplayCount().
bool MainVoiceMemoOnLeave (ITUWidget * widget, char * param)
Definition at line 403 of file layer_main_voicememo.c.
References DEVICE_INDOOR2, LinphoneDisableBusy(), LinphoneIsInDoNotDisturb(), mainVoiceMemoPlaying, mainVoiceMemoRecording, SceneContinuePlayGuardAlarm(), theDeviceInfo, DeviceInfo::type, VoiceMemoStopPlay(), and VoiceMemoStopRecord().
bool MainVoiceMemoOnTimer (ITUWidget * widget, char * param)
Definition at line 319 of file layer_main_voicememo.c.
References DEVICE_INDOOR2, font::f, ituSceneExecuteCommand(), ituWidgetSetVisible, LinphoneDisableBusy(), LinphoneIsInDoNotDisturb(), mainVoiceMemoPlaying, mainVoiceMemoPlayingCountDown, mainVoiceMemoPlayingLastTick, mainVoiceMemoRecording, MainVoiceMemoReload(), MainVoiceMemoResetPlayButton(), SceneContinuePlayGuardAlarm(), ScreenSaverRefresh(), theDeviceInfo, theScene, DeviceInfo::type, VoiceMemoCheckDiskSpace(), and VoiceMemoStopRecord().
bool MainVoiceMemoRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 293 of file layer_main_voicememo.c.
References DEVICE_INDOOR2, LinphoneEnableBusy(), LinphoneIsInDoNotDisturb(), mainVoiceMemoRecording, SceneCameraSetViewing(), theDeviceInfo, DeviceInfo::type, and VoiceMemoStartRecord().
bool MainVoiceMemoStopPlayButtonOnPress (ITUWidget * widget, char * param)
Definition at line 282 of file layer_main_voicememo.c.
References ituWidgetSetVisible, mainVoiceMemoPlaying, mainVoiceMemoPlayingIndex, SceneCameraSetViewing(), SceneContinuePlayGuardAlarm(), and VoiceMemoStopPlay().
bool MainVoiceMemoStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 306 of file layer_main_voicememo.c.
References DEVICE_INDOOR2, ituSceneExecuteCommand(), LinphoneDisableBusy(), LinphoneIsInDoNotDisturb(), mainVoiceMemoRecording, MainVoiceMemoReload(), SceneCameraSetViewing(), SceneContinuePlayGuardAlarm(), theDeviceInfo, theScene, DeviceInfo::type, and VoiceMemoStopRecord().
bool MainVoiceMemoTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 78 of file layer_main_voicememo.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VoiceMemoEntry::played, ITCTreeTag::sibling, VoiceMemoEntry::time, VoiceMemoGetCount(), and VoiceMemoGetEntry().
bool MainVoiceMemoViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 248 of file layer_main_voicememo.c.
References ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, ituWidgetSetColor, ituWidgetSetVisible, mainVoiceMemoPlaying, mainVoiceMemoPlayingCountDown, mainVoiceMemoPlayingIndex, mainVoiceMemoPlayingLastTick, MainVoiceMemoResetPlayButton(), SceneCameraSetViewing(), VoiceMemoEntry::sec, theScene, VoiceMemoGetEntry(), and VoiceMemoStartPlay().
bool MainWeatherOnEnter (ITUWidget * widget, char * param)
Definition at line 170 of file layer_main_weather.c.
References ituSceneFindWidget(), mainWeatherFilled, MainWeatherGetWeather(), RemoteGetWeather(), and theScene.
bool MainWeatherOnLeave (ITUWidget * widget, char * param)
Definition at line 269 of file layer_main_weather.c.
bool MainWeatherOnTimer (ITUWidget * widget, char * param)
Definition at line 50 of file layer_main_weather.c.
References ituSpriteGoto(), ituTextSetString, mainWeatherFilled, WeatherGetDate(), WeatherGetSymbolIndex(), WeatherGetSymbolName(), WeatherGetTemperatureMax(), WeatherGetTemperatureMin(), WeatherGetWindSpeedName(), and WeatherIsAvailable().
bool MessageNotifyTextMessageOnCustom (ITUWidget * widget, char * param)
Definition at line 67 of file layer_message.c.
References ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, and theScene.
bool MessageNotifyVideoMessageOnCustom (ITUWidget * widget, char * param)
Definition at line 39 of file layer_message.c.
References ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, and theScene.
bool MessagePhotoDeleteConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 229 of file layer_message_video.c.
References DEVICE_INDOOR2, ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, MessagePhotoDeleteComplete(), MessagePhotoReload(), MessageVideoDelete(), theDeviceInfo, theScene, DeviceInfo::type, and VideoMemoDeleteEntry().
bool MessagePhotoDeleteOnPress (ITUWidget * widget, char * param)
Definition at line 221 of file layer_message_video.c.
References ITUListBoxTag::focusIndex.
bool MessagePhotoOnEnter (ITUWidget * widget, char * param)
Definition at line 247 of file layer_message_video.c.
References CaptureGetUnplayCount(), DEVICE_INDOOR2, ituSceneFindWidget(), MessageNotifyUnreadRecordMessage(), MessagePhotoGetList(), MessagePhotoReload(), MessageVideoListGet(), theDeviceInfo, theScene, and DeviceInfo::type.
bool MessagePhotoOnLeave (ITUWidget * widget, char * param)
Definition at line 266 of file layer_message_video.c.
References DEVICE_INDOOR2, MessagePhotoClear(), theDeviceInfo, and DeviceInfo::type.
bool MessagePhotoTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 89 of file layer_message_video.c.
References ITCTreeTag::child, DEVICE_INDOOR2, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, messageVideoCount, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VideoMemoEntry::played, Message::read, ITCTreeTag::sibling, theDeviceInfo, Message::time, VideoMemoEntry::time, DeviceInfo::type, VideoMemoGetCount(), and VideoMemoGetEntry().
bool MessagePhotoTopicListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 13 of file layer_message_video.c.
References ITCTreeTag::child, DEVICE_INDOOR2, ITUListBoxTag::focusIndex, i, Message::id, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, messageVideoCount, VideoMemoEntry::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VideoMemoEntry::played, Message::read, ITCTreeTag::sibling, theDeviceInfo, Message::topic, DeviceInfo::type, VideoMemoGetCount(), and VideoMemoGetEntry().
bool MessagePhotoViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 168 of file layer_message_video.c.
References ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, MessagePhotoViewShow(), and ITUScrollText::text.
bool MessagePhotoViewOnEnter (ITUWidget * widget, char * param)
Definition at line 49 of file layer_message_video_view.c.
References DEVICE_INDOOR2, DeviceInfo::ip, ituSceneFindWidget(), LinphonePlayVideoMessage(), LinphoneSetWindowID(), messagePhotoViewID, messagePhotoViewPlaying, SceneCameraSetViewing(), theCenterInfo, theDeviceInfo, theScene, DeviceInfo::type, and VideoMemoStartPlay().
bool MessagePhotoViewOnLeave (ITUWidget * widget, char * param)
Definition at line 71 of file layer_message_video_view.c.
References DEVICE_INDOOR2, LinphoneTerminate(), messagePhotoViewPlaying, SceneCameraSetViewing(), SceneHangUp(), theDeviceInfo, DeviceInfo::type, and VideoMemoStopPlay().
bool MessagePhotoViewOnTimer (ITUWidget * widget, char * param)
Definition at line 15 of file layer_message_video_view.c.
References DEVICE_INDOOR2, ituLayerGoto(), ituSceneFindWidget(), messagePhotoViewPlaying, theDeviceInfo, theScene, DeviceInfo::type, and VideoMemoIsPlayFinished().
bool MessageRecordDeleteConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 207 of file layer_message_record.c.
References CaptureDeleteEntry(), CaptureGetEntry(), CaptureGetUnplayCount(), CaptureSnapshotDeleteEntry(), ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituListBoxReload(), ituWidgetGetCustomData, MEDIA_IMAGE, MessageNotifyUnreadRecordMessage(), and CaptureEntry::type.
bool MessageRecordDeleteOnPress (ITUWidget * widget, char * param)
Definition at line 199 of file layer_message_record.c.
References ITUListBoxTag::focusIndex.
bool MessageRecordIconListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 12 of file layer_message_record.c.
References CaptureGetCount(), CaptureGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and CaptureEntry::type.
bool MessageRecordOnEnter (ITUWidget * widget, char * param)
Definition at line 231 of file layer_message_record.c.
References ituListBoxReload(), ituSceneFindWidget(), MessageRecordTimeListBoxOnLoad(), MessageRecordTopicListBoxOnLoad(), and theScene.
bool MessageRecordTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 120 of file layer_message_record.c.
References CaptureGetCount(), CaptureGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, CaptureEntry::played, CaptureEntry::sec, and ITCTreeTag::sibling.
Referenced by MessageRecordOnEnter().
bool MessageRecordTopicListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 64 of file layer_message_record.c.
References CaptureGetCount(), CaptureGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, CaptureEntry::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, CaptureEntry::played, and ITCTreeTag::sibling.
Referenced by MessageRecordOnEnter().
bool MessageRecordViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 185 of file layer_message_record.c.
References CaptureGetEntry(), ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, MessageRecordViewShow(), and ITUScrollText::text.
bool MessageRecordViewOnEnter (ITUWidget * widget, char * param)
Definition at line 52 of file layer_message_record_view.c.
References CaptureGetUnplayCount(), CaptureStartPlay(), data, font::f, CaptureEntry::filename, ituIconLoadJpegData(), ituSceneFindWidget(), ituWidgetSetVisible, LinphoneSetWindowID(), MEDIA_AUDIO, MEDIA_IMAGE, MEDIA_VIDEO, MessageNotifyUnreadRecordMessage(), messageRecordViewID, messageRecordViewPlaying, SceneCameraSetViewing(), SceneLeaveVideoState(), SNAPSHOT_PATH, theScene, and CaptureEntry::type.
bool MessageRecordViewOnLeave (ITUWidget * widget, char * param)
Definition at line 130 of file layer_message_record_view.c.
References CaptureStopPlay(), messageRecordViewPlaying, SceneCameraSetViewing(), SceneContinuePlayGuardAlarm(), and SceneEnterVideoState().
bool MessageRecordViewOnTimer (ITUWidget * widget, char * param)
Definition at line 20 of file layer_message_record_view.c.
References CaptureIsPlayFinished(), ituLayerGoto(), ituSceneFindWidget(), messageRecordViewPlaying, and theScene.
bool MessageServiceDeleteConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 183 of file layer_message_service.c.
References ITUListBoxTag::focusIndex, Message::id, itcTreeGetChildAt, ituWidgetGetCustomData, MessageServiceDeleteComplete(), and MessageTextDelete().
bool MessageServiceDeleteOnPress (ITUWidget * widget, char * param)
Definition at line 175 of file layer_message_service.c.
References ITUListBoxTag::focusIndex.
bool MessageServiceOnEnter (ITUWidget * widget, char * param)
Definition at line 194 of file layer_message_service.c.
References ituSceneFindWidget(), MessageServiceGetList(), MessageTextListGet(), and theScene.
bool MessageServiceOnLeave (ITUWidget * widget, char * param)
Definition at line 211 of file layer_message_service.c.
References MessageServiceClear().
bool MessageServiceTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 68 of file layer_message_service.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, messageTextCount, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, Message::read, ITCTreeTag::sibling, and Message::time.
bool MessageServiceTopicListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_message_service.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, messageTextCount, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, Message::read, ITCTreeTag::sibling, and Message::topic.
bool MessageServiceViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 121 of file layer_message_service.c.
References ITUListBoxTag::focusIndex, Message::image, itcTreeGetChildAt, ituWidgetGetCustomData, and MessageServiceViewShow().
bool MessageServiceViewOnEnter (ITUWidget * widget, char * param)
Definition at line 57 of file layer_message_service_view.c.
References ituSceneFindWidget(), SceneLeaveVideoState(), and theScene.
bool MessageServiceViewOnLeave (ITUWidget * widget, char * param)
Definition at line 82 of file layer_message_service_view.c.
References MessageServiceViewClear(), and SceneEnterVideoState().
bool MessageServiceViewOnTimer (ITUWidget * widget, char * param)
Definition at line 69 of file layer_message_service_view.c.
References ituIconLoadJpegData(), messageImageContent, messageImageContentSize, and PicPlayerLoaded.
bool PhoneBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 22 of file layer_phone_dial_resident.c.
References ituTextBoxBack(), ituTextGetString, ituTextSetString, ituWidgetSetVisible, phoneAreaTextBox, phoneBuildingTextBox, phoneFloorTextBox, and phoneUnitTextBox.
bool PhoneCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 116 of file layer_phone_dial_resident.c.
References CallingCall(), CallingCallByIP(), and ituTextGetString.
bool PhoneContactsAddButtonOnPress (ITUWidget * widget, char * param)
Definition at line 154 of file layer_phone_contacts.c.
References PhoneContactsAddShow().
bool PhoneContactsAddCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 51 of file layer_phone_contacts_add.c.
References ituLayerGoto().
bool PhoneContactsAddCommentButtonOnPress (ITUWidget * widget, char * param)
Definition at line 64 of file layer_phone_contacts_add.c.
References ituTextGetString, and PhoneContactsKeyboardShow().
bool PhoneContactsAddConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 31 of file layer_phone_contacts_add.c.
References AddressBookGetDeviceIP(), DeviceInfo::area, DeviceInfo::building, DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, DeviceInfo::ip, ituCheckBoxIsChecked(), ituSceneExecuteCommand(), ituTextBoxGetString(), LinphoneAddFriend(), PhoneContactsGotoLastLayer(), DeviceInfo::room, theScene, DeviceInfo::type, and DeviceInfo::unit.
bool PhoneContactsAddOnEnter (ITUWidget * widget, char * param)
Definition at line 114 of file layer_phone_contacts_add.c.
References ituSceneFindWidget(), ituWidgetDisable, ituWidgetSetVisible, and theScene.
bool PhoneContactsAddRoomButtonOnPress (ITUWidget * widget, char * param)
Definition at line 58 of file layer_phone_contacts_add.c.
References PhoneContactsKeypadShow().
bool PhoneContactsCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 132 of file layer_phone_contacts.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, LinphoneCastor3Friend::blacklist, DeviceInfo::building, CallingCall(), DEVICE_ENTRANCE, DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituWidgetGetCustomData, DeviceInfo::room, DeviceInfo::type, DeviceInfo::unit, and LinphoneCastor3Friend::uri.
bool PhoneContactsClearConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 201 of file layer_phone_contacts.c.
References ituSceneExecuteCommand(), LinphoneClearFriends(), PhoneContactsReload(), and theScene.
bool PhoneContactsCommentListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 77 of file layer_phone_contacts.c.
References LinphoneCastor3Friend::blacklist, ITCTreeTag::child, LinphoneCastor3Friend::comment, ITUListBoxTag::focusIndex, LinphoneCastor3::friend_count, LinphoneCastor3::friends, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, linphoneCastor3, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool PhoneContactsDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 174 of file layer_phone_contacts.c.
References ITUListBoxTag::focusIndex.
bool PhoneContactsDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 188 of file layer_phone_contacts.c.
References ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, LinphoneDeleteFriend(), PhoneContactsReload(), LinphoneCastor3Friend::refkey, and theScene.
bool PhoneContactsKeyboardBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 63 of file layer_phone_contacts_keyboard.c.
References ituButtonSetString, ituTextBoxBack(), ituTextBoxSetString(), ituTextGetString, and phoneContactsKeyboardChsIndex.
bool PhoneContactsKeyboardChsButtonOnPress (ITUWidget * widget, char * param)
Definition at line 95 of file layer_phone_contacts_keyboard.c.
References ituButtonSetString.
bool PhoneContactsKeyboardChsCharButtonOnPress (ITUWidget * widget, char * param)
Definition at line 285 of file layer_phone_contacts_keyboard.c.
References i, ituButtonSetString, ituTextBoxInput(), ituTextBoxSetString(), ituTextGetString, phoneContactsKeyboardChs0Button, phoneContactsKeyboardChs1Button, phoneContactsKeyboardChs2Button, phoneContactsKeyboardChs3Button, phoneContactsKeyboardChs4Button, phoneContactsKeyboardChs5Button, phoneContactsKeyboardChs6Button, phoneContactsKeyboardChs7Button, phoneContactsKeyboardChs8Button, phoneContactsKeyboardChs9Button, phoneContactsKeyboardChsIndex, phoneContactsKeyboardChsString, phoneContactsKeyboardChsStringIndex, py_ime(), and ITUButton::text.
bool PhoneContactsKeyboardCloseButtonOnPress (ITUWidget * widget, char * param)
Definition at line 38 of file layer_phone_contacts_keyboard.c.
References ituLayerGoto(), PhoneContactsAddShow(), and PhoneContactsModifyShow().
bool PhoneContactsKeyboardEnterButtonOnPress (ITUWidget * widget, char * param)
Definition at line 50 of file layer_phone_contacts_keyboard.c.
References ituLayerGoto(), ituTextGetString, PhoneContactsAddShow(), and PhoneContactsModifyShow().
bool PhoneContactsKeyboardEnUpperButtonOnPress (ITUWidget * widget, char * param)
Definition at line 89 of file layer_phone_contacts_keyboard.c.
References phoneContactsKeyboardChsString.
bool PhoneContactsKeyboardOnEnter (ITUWidget * widget, char * param)
Definition at line 408 of file layer_phone_contacts_keyboard.c.
References ituButtonSetString, ituSceneFindWidget(), ituWidgetSetVisible, phoneContactsKeyboardChsIndex, phoneContactsKeyboardChsString, phoneContactsKeyboardChsStringIndex, and theScene.
bool PhoneContactsKeyboardPageDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 197 of file layer_phone_contacts_keyboard.c.
References i, ituButtonSetString, phoneContactsKeyboardChs0Button, phoneContactsKeyboardChs1Button, phoneContactsKeyboardChs2Button, phoneContactsKeyboardChs3Button, phoneContactsKeyboardChs4Button, phoneContactsKeyboardChs5Button, phoneContactsKeyboardChs6Button, phoneContactsKeyboardChs7Button, phoneContactsKeyboardChs8Button, phoneContactsKeyboardChs9Button, phoneContactsKeyboardChsString, and phoneContactsKeyboardChsStringIndex.
bool PhoneContactsKeyboardPageUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 110 of file layer_phone_contacts_keyboard.c.
References i, ituButtonSetString, phoneContactsKeyboardChs0Button, phoneContactsKeyboardChs1Button, phoneContactsKeyboardChs2Button, phoneContactsKeyboardChs3Button, phoneContactsKeyboardChs4Button, phoneContactsKeyboardChs5Button, phoneContactsKeyboardChs6Button, phoneContactsKeyboardChs7Button, phoneContactsKeyboardChs8Button, phoneContactsKeyboardChs9Button, phoneContactsKeyboardChsString, and phoneContactsKeyboardChsStringIndex.
bool PhoneContactsKeypadBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 31 of file layer_phone_contacts_keypad.c.
References ituTextSetString, phoneContactsKeypadAreaTextBox, phoneContactsKeypadBuildingTextBox, phoneContactsKeypadFloorTextBox, and phoneContactsKeypadUnitTextBox.
bool PhoneContactsKeypadCloseButtonOnPress (ITUWidget * widget, char * param)
Definition at line 19 of file layer_phone_contacts_keypad.c.
References ituLayerGoto(), PhoneContactsAddShow(), and PhoneContactsModifyShow().
bool PhoneContactsKeypadConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 54 of file layer_phone_contacts_keypad.c.
References DeviceInfo::area, DeviceInfo::building, DeviceInfo::floor, ituLayerGoto(), ituTextGetString, PhoneContactsAddShow(), PhoneContactsModifyShow(), DeviceInfo::room, and DeviceInfo::unit.
bool PhoneContactsKeypadNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 75 of file layer_phone_contacts_keypad.c.
References ituTextBoxInput(), ituTextGetString, ITUTextBox::maxLen, phoneContactsKeypadBuildingTextBox, phoneContactsKeypadFloorTextBox, phoneContactsKeypadRoomTextBox, phoneContactsKeypadUnitTextBox, and ITUButton::text.
bool PhoneContactsKeypadOnEnter (ITUWidget * widget, char * param)
Definition at line 139 of file layer_phone_contacts_keypad.c.
References ituSceneFindWidget(), and theScene.
bool PhoneContactsModifyButtonOnPress (ITUWidget * widget, char * param)
Definition at line 160 of file layer_phone_contacts.c.
References AddressBookGetDeviceInfo(), LinphoneCastor3Friend::blacklist, LinphoneCastor3Friend::comment, ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituWidgetGetCustomData, PhoneContactsModifyShow(), LinphoneCastor3Friend::refkey, and LinphoneCastor3Friend::uri.
bool PhoneContactsModifyCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 52 of file layer_phone_contacts_modify.c.
References ituLayerGoto().
bool PhoneContactsModifyCommentButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_phone_contacts_modify.c.
References ituTextGetString, and PhoneContactsKeyboardShow().
bool PhoneContactsModifyConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 28 of file layer_phone_contacts_modify.c.
References AddressBookGetDeviceIP(), DeviceInfo::area, DeviceInfo::building, DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, DeviceInfo::ip, ituCheckBoxIsChecked(), ituSceneExecuteCommand(), ituTextBoxGetString(), LinphoneAddFriend(), LinphoneDeleteFriend(), PhoneContactsModifyGotoLastLayer(), phoneContactsModifyRefkey, DeviceInfo::room, theScene, DeviceInfo::type, and DeviceInfo::unit.
bool PhoneContactsModifyOnEnter (ITUWidget * widget, char * param)
Definition at line 111 of file layer_phone_contacts_modify.c.
References ituSceneFindWidget(), ituWidgetDisable, ituWidgetSetVisible, and theScene.
bool PhoneContactsModifyRoomButtonOnPress (ITUWidget * widget, char * param)
Definition at line 59 of file layer_phone_contacts_modify.c.
References PhoneContactsKeypadShow().
bool PhoneContactsOnEnter (ITUWidget * widget, char * param)
Definition at line 208 of file layer_phone_contacts.c.
References ituSceneFindWidget(), and theScene.
bool PhoneContactsRoomListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 16 of file layer_phone_contacts.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, LinphoneCastor3Friend::blacklist, DeviceInfo::building, ITCTreeTag::child, DeviceInfo::floor, ITUListBoxTag::focusIndex, LinphoneCastor3::friend_count, LinphoneCastor3::friends, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, linphoneCastor3, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, ITCTreeTag::sibling, StringGetRoomAddress(), DeviceInfo::unit, and LinphoneCastor3Friend::uri.
bool PhoneDialLobbyOnEnter (ITUWidget * widget, char * param)
Definition at line 80 of file layer_phone_dial_lobby.c.
References ituSceneFindWidget(), and theScene.
bool PhoneDialManagerOnEnter (ITUWidget * widget, char * param)
Definition at line 80 of file layer_phone_dial_manager.c.
References ituSceneFindWidget(), and theScene.
bool PhoneDialResidentOnEnter (ITUWidget * widget, char * param)
Definition at line 143 of file layer_phone_dial_resident.c.
References ituSceneFindWidget(), ituTextBoxSetString(), ituWidgetSetVisible, phoneAreaTextBox, and theScene.
bool PhoneLobbyCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_phone_dial_lobby.c.
References CallingCallByIP(), ITUListBoxTag::focusIndex, DeviceInfo::ip, itcTreeGetChildAt, and ituWidgetGetCustomData.
bool PhoneLobbyListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_phone_dial_lobby.c.
References AddressBookGetCameraInfoArray(), DeviceInfo::alias, ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, MAX_CAMERA_COUNT, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, phoneCallLobbyInfoCount, ITCTreeTag::sibling, and theDeviceInfo.
bool PhoneLogMissedAddButtonOnPress (ITUWidget * widget, char * param)
Definition at line 187 of file layer_phone_log_missed.c.
References AddressBookGetDeviceInfo(), CALLLOG_MISSED, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, and PhoneContactsAddShow().
bool PhoneLogMissedCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 171 of file layer_phone_log_missed.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CallingCall(), CALLLOG_MISSED, CallLogGetEntry(), DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, DeviceInfo::room, DeviceInfo::type, and DeviceInfo::unit.
bool PhoneLogMissedClearConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 254 of file layer_phone_log_missed.c.
References CALLLOG_MISSED, CallLogClearEntries(), ituSceneExecuteCommand(), PhoneLogMissedReload(), and theScene.
bool PhoneLogMissedDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 226 of file layer_phone_log_missed.c.
References ITUListBoxTag::focusIndex.
bool PhoneLogMissedDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 241 of file layer_phone_log_missed.c.
References CALLLOG_MISSED, CallLogDeleteEntry(), CallLogGetEntry(), ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, PhoneLogMissedReload(), and theScene.
bool PhoneLogMissedDurationListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 119 of file layer_phone_log_missed.c.
References CALLLOG_MISSED, CallLogGetCount(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool PhoneLogMissedOnEnter (ITUWidget * widget, char * param)
Definition at line 261 of file layer_phone_log_missed.c.
References ituSceneFindWidget(), SceneClearMissedCalls(), and theScene.
bool PhoneLogMissedRoomListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 15 of file layer_phone_log_missed.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CALLLOG_MISSED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, ITCTreeTag::sibling, StringGetRoomAddress(), and DeviceInfo::unit.
bool PhoneLogMissedTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 69 of file layer_phone_log_missed.c.
References CALLLOG_MISSED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and CallLogEntry::time.
bool PhoneLogMissedViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 203 of file layer_phone_log_missed.c.
References AddressBookGetDeviceInfo(), DeviceInfo::alias, CALLLOG_MISSED, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, PhoneLogViewShow(), StringGetCallLogType(), ITUScrollText::text, and CallLogEntry::time.
bool PhoneLogReceivedAddButtonOnPress (ITUWidget * widget, char * param)
Definition at line 185 of file layer_phone_log_received.c.
References AddressBookGetDeviceInfo(), CALLLOG_RECEIVED, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, and PhoneContactsAddShow().
bool PhoneLogReceivedCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 169 of file layer_phone_log_received.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CallingCall(), CALLLOG_RECEIVED, CallLogGetEntry(), DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, DeviceInfo::room, DeviceInfo::type, and DeviceInfo::unit.
bool PhoneLogReceivedClearConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 252 of file layer_phone_log_received.c.
References CALLLOG_RECEIVED, CallLogClearEntries(), ituSceneExecuteCommand(), PhoneLogReceivedReload(), and theScene.
bool PhoneLogReceivedDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 224 of file layer_phone_log_received.c.
References ITUListBoxTag::focusIndex.
bool PhoneLogReceivedDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 239 of file layer_phone_log_received.c.
References CALLLOG_RECEIVED, CallLogDeleteEntry(), CallLogGetEntry(), ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, PhoneLogReceivedReload(), and theScene.
bool PhoneLogReceivedDurationListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 118 of file layer_phone_log_received.c.
References CALLLOG_RECEIVED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, CallLogEntry::duration, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool PhoneLogReceivedOnEnter (ITUWidget * widget, char * param)
Definition at line 259 of file layer_phone_log_received.c.
References ituSceneFindWidget(), and theScene.
bool PhoneLogReceivedRoomListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_phone_log_received.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CALLLOG_RECEIVED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, ITCTreeTag::sibling, StringGetRoomAddress(), and DeviceInfo::unit.
bool PhoneLogReceivedTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 68 of file layer_phone_log_received.c.
References CALLLOG_RECEIVED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and CallLogEntry::time.
bool PhoneLogReceivedViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 201 of file layer_phone_log_received.c.
References AddressBookGetDeviceInfo(), DeviceInfo::alias, CALLLOG_RECEIVED, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, PhoneLogViewShow(), StringGetCallLogType(), ITUScrollText::text, and CallLogEntry::time.
bool PhoneLogSentAddButtonOnPress (ITUWidget * widget, char * param)
Definition at line 185 of file layer_phone_log_sent.c.
References AddressBookGetDeviceInfo(), CALLLOG_SENT, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, and PhoneContactsAddShow().
bool PhoneLogSentCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 169 of file layer_phone_log_sent.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CallingCall(), CALLLOG_SENT, CallLogGetEntry(), DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, DeviceInfo::room, DeviceInfo::type, and DeviceInfo::unit.
bool PhoneLogSentClearConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 252 of file layer_phone_log_sent.c.
References CALLLOG_SENT, CallLogClearEntries(), ituSceneExecuteCommand(), PhoneLogSentReload(), and theScene.
bool PhoneLogSentDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 224 of file layer_phone_log_sent.c.
References ITUListBoxTag::focusIndex.
bool PhoneLogSentDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 239 of file layer_phone_log_sent.c.
References CALLLOG_SENT, CallLogDeleteEntry(), CallLogGetEntry(), ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, PhoneLogSentReload(), and theScene.
bool PhoneLogSentDurationListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 118 of file layer_phone_log_sent.c.
References CALLLOG_SENT, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, CallLogEntry::duration, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool PhoneLogSentOnEnter (ITUWidget * widget, char * param)
Definition at line 259 of file layer_phone_log_sent.c.
References ituSceneFindWidget(), and theScene.
bool PhoneLogSentRoomListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_phone_log_sent.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CALLLOG_SENT, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, ITCTreeTag::sibling, StringGetRoomAddress(), and DeviceInfo::unit.
bool PhoneLogSentTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 68 of file layer_phone_log_sent.c.
References CALLLOG_SENT, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and CallLogEntry::time.
bool PhoneLogSentViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 201 of file layer_phone_log_sent.c.
References AddressBookGetDeviceInfo(), DeviceInfo::alias, CALLLOG_SENT, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, PhoneLogViewShow(), StringGetCallLogType(), ITUScrollText::text, and CallLogEntry::time.
bool PhoneLogViewCloseButtonOnPress (ITUWidget * widget, char * param)
Definition at line 16 of file layer_phone_log_view.c.
References ituLayerGoto().
bool PhoneManagerButtonOnPress (ITUWidget * widget, char * param)
Definition at line 108 of file layer_phone_dial_resident.c.
References CallingCallManager().
bool PhoneManagerCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_phone_dial_manager.c.
References CallingCallManager(), ITUListBoxTag::focusIndex, DeviceInfo::ip, itcTreeGetChildAt, and ituWidgetGetCustomData.
bool PhoneManagerListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_phone_dial_manager.c.
References AddressBookGetManagerInfoArray(), DeviceInfo::alias, ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, MAX_MANAGER_COUNT, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, phoneCallManagerInfoCount, and ITCTreeTag::sibling.
bool PhoneNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_phone_dial_resident.c.
References ituTextBoxInput(), ituTextGetString, ituWidgetSetVisible, ITUTextBox::maxLen, phoneBuildingTextBox, phoneFloorTextBox, phoneIPTextBox, phoneRoomTextBox, phoneUnitTextBox, and ITUButton::text.
bool ScreensaverOnEnter (ITUWidget * widget, char * param)
Definition at line 10 of file layer_screensaver.c.
References data, font::f, ituIconLoadJpegData(), ituSceneFindWidget(), ituWidgetSetVisible, SCREENSAVER_CLOCK, SCREENSAVER_PHOTO, Config::screensaver_type, theConfig, and theScene.
bool SettingDisplayBrightnessDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 30 of file layer_setting_display.c.
References ITUSpriteTag::frame, ituSpriteGoto(), and ScreenSetBrightness().
bool SettingDisplayBrightnessUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 42 of file layer_setting_display.c.
References ITUSpriteTag::frame, ituSpriteGoto(), ScreenSetBrightness(), and settingDisplayMaxBrigntness.
bool SettingDisplayCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 125 of file layer_setting_display.c.
References Config::brightness, CHS, CHT, ituRadioBoxSetChecked(), ituSpriteGoto(), ituTextSetString, Config::lang, SCREENSAVER_BLANK, SCREENSAVER_CLOCK, SCREENSAVER_PHOTO, Config::screensaver_time, Config::screensaver_type, ScreenSetBrightness(), and theConfig.
bool SettingDisplayOnEnter (ITUWidget * widget, char * param)
Definition at line 159 of file layer_setting_display.c.
References Config::brightness, CHS, CHT, itcTreeGetChildCount, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, Config::lang, SCREENSAVER_BLANK, SCREENSAVER_CLOCK, SCREENSAVER_PHOTO, Config::screensaver_time, Config::screensaver_type, settingDisplayMaxBrigntness, theConfig, and theScene.
bool SettingDisplayOnLeave (ITUWidget * widget, char * param)
Definition at line 229 of file layer_setting_display.c.
References Config::brightness, CHS, CHT, ituRadioBoxSetChecked(), ituSpriteGoto(), ituTextSetString, Config::lang, SCREENSAVER_BLANK, SCREENSAVER_CLOCK, SCREENSAVER_PHOTO, Config::screensaver_time, Config::screensaver_type, ScreenSetBrightness(), and theConfig.
bool SettingDisplaySaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 70 of file layer_setting_display.c.
References Config::brightness, CHS, CHT, ConfigSave(), ENG, ITUSpriteTag::frame, Config::itufile, ituLayerGoto(), ituRadioBoxIsChecked(), ituTextGetString, Config::lang, SceneLoad(), SceneUpdateIndicators(), SCREENSAVER_BLANK, SCREENSAVER_CLOCK, SCREENSAVER_NONE, SCREENSAVER_PHOTO, Config::screensaver_time, Config::screensaver_type, and theConfig.
bool SettingDisplayScreensaverTimeButtonOnPress (ITUWidget * widget, char * param)
Definition at line 54 of file layer_setting_display.c.
References ituTextBoxSetString(), and ituTextGetString.
bool SettingDisplayTimeKeypadConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 60 of file layer_setting_display.c.
References ituTextGetString, and ituTextSetString.
bool SettingEngineerMiscClearConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 9 of file layer_setting_engineer_misc.c.
References QUIT_RESET_TEMP_DRIVE, and SceneQuit().
bool SettingEngineerMiscDefaultButtonOnPress (ITUWidget * widget, char * param)
Definition at line 23 of file layer_setting_engineer_misc.c.
References QUIT_RESET_FACTORY, and SceneQuit().
bool SettingEngineerMiscGuardOnEnter (ITUWidget * widget, char * param)
Definition at line 48 of file layer_setting_engineer_misc_guard.c.
References itcTreeGetChildCount, ituSceneFindWidget(), ituSpriteGoto(), settingEngineerMiscGuardLastWarnLevel, settingEngineerMiscGuardMaxWarnVol, theConfig, theScene, and Config::warnlevel.
bool SettingEngineerMiscGuardOnLeave (ITUWidget * widget, char * param)
Definition at line 67 of file layer_setting_engineer_misc_guard.c.
References ConfigSave(), settingEngineerMiscGuardLastWarnLevel, theConfig, and Config::warnlevel.
bool SettingEngineerMiscGuardWarnVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 14 of file layer_setting_engineer_misc_guard.c.
References ituSpriteGoto(), LinphoneSetWarnLevel(), settingEngineerMiscGuardMaxWarnVol, theConfig, and Config::warnlevel.
bool SettingEngineerMiscGuardWarnVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 31 of file layer_setting_engineer_misc_guard.c.
References ituSpriteGoto(), LinphoneSetWarnLevel(), settingEngineerMiscGuardMaxWarnVol, theConfig, and Config::warnlevel.
bool SettingEngineerMiscTerminalBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_setting_engineer_misc_terminal.c.
References ituTextBoxSetString(), settingEngineerMiscTerminalAreaTextBox, settingEngineerMiscTerminalBuildingTextBox, settingEngineerMiscTerminalFloorTextBox, settingEngineerMiscTerminalRoomTextBox, and settingEngineerMiscTerminalUnitTextBox.
bool SettingEngineerMiscTerminalClearButtonOnPress (ITUWidget * widget, char * param)
Definition at line 92 of file layer_setting_engineer_misc_terminal.c.
References ituTextBoxSetString(), and settingEngineerMiscTerminalAreaTextBox.
bool SettingEngineerMiscTerminalConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 104 of file layer_setting_engineer_misc_terminal.c.
References Config::area, Config::building, ConfigSaveAll(), Config::ext, Config::floor, ituTextBoxGetString(), QUIT_RESET_NETWORK, Config::room, SceneQuit(), theConfig, and Config::unit.
bool SettingEngineerMiscTerminalNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 41 of file layer_setting_engineer_misc_terminal.c.
References ituTextBoxGetString(), ituTextBoxInput(), ituTextGetString, ITUTextBox::maxLen, settingEngineerMiscTerminalBuildingTextBox, settingEngineerMiscTerminalExtTextBox, settingEngineerMiscTerminalFloorTextBox, settingEngineerMiscTerminalRoomTextBox, settingEngineerMiscTerminalUnitTextBox, and ITUButton::text.
bool SettingEngineerMiscTerminalOnEnter (ITUWidget * widget, char * param)
Definition at line 144 of file layer_setting_engineer_misc_terminal.c.
References Config::area, Config::building, Config::ext, Config::floor, ituSceneFindWidget(), ituTextBoxSetString(), Config::room, settingEngineerMiscTerminalAreaTextBox, settingEngineerMiscTerminalBuildingTextBox, settingEngineerMiscTerminalExtTextBox, settingEngineerMiscTerminalFloorTextBox, settingEngineerMiscTerminalRoomTextBox, settingEngineerMiscTerminalUnitTextBox, theConfig, theScene, and Config::unit.
bool SettingEngineerMiscTwiceBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 51 of file layer_setting_engineer_misc_twice.c.
References ituTextSetString, settingEngineerMiscTwiceAreaTextBox, settingEngineerMiscTwiceBuildingTextBox, settingEngineerMiscTwiceFloorTextBox, settingEngineerMiscTwiceRoomTextBox, and settingEngineerMiscTwiceUnitTextBox.
bool SettingEngineerMiscTwiceClearButtonOnPress (ITUWidget * widget, char * param)
Definition at line 78 of file layer_setting_engineer_misc_twice.c.
References ituTextSetString, and settingEngineerMiscTwiceAreaTextBox.
bool SettingEngineerMiscTwiceConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 90 of file layer_setting_engineer_misc_twice.c.
References settingEngineerMiscTwiceBuildingTextBox, settingEngineerMiscTwiceExtTextBox, settingEngineerMiscTwiceFloorTextBox, settingEngineerMiscTwiceRoomTextBox, and settingEngineerMiscTwiceUnitTextBox.
bool SettingEngineerMiscTwiceNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 26 of file layer_setting_engineer_misc_twice.c.
References ituTextBoxInput(), ituTextGetString, ITUTextBox::maxLen, settingEngineerMiscTwiceBuildingTextBox, settingEngineerMiscTwiceExtTextBox, settingEngineerMiscTwiceFloorTextBox, settingEngineerMiscTwiceRoomTextBox, settingEngineerMiscTwiceUnitTextBox, and ITUButton::text.
bool SettingEngineerMiscTwiceOnEnter (ITUWidget * widget, char * param)
Definition at line 194 of file layer_setting_engineer_misc_twice.c.
References ituSceneFindWidget(), ituTextBoxSetString(), settingEngineerMiscTwiceAreaTextBox, settingEngineerMiscTwiceOutdoorInfoSem, and theScene.
bool SettingEngineerMiscTwiceSettingButtonOnPress (ITUWidget * widget, char * param)
Definition at line 111 of file layer_setting_engineer_misc_twice.c.
References AddressBookGetDeviceIP(), AddressBookGetVersion(), AddressBookIsOutdoorExist(), ServerInfo::addressBookVersion, ConfigSave(), DeviceInfoIsInEngineerMode(), GetOutdoorInfoCallback(), itpSemWaitTimeout(), ituTextGetString, ituTextSetString, ituWidgetDisable, ituWidgetSetVisible, Config::outdoor_ipaddr, RemoteGetOutdoorInfo(), RemoteSetOutdoorSetting(), settingEngineerMiscTwiceOutdoorInfoSem, and theConfig.
bool SettingEngineerMiscUpgradeButtonOnPress (ITUWidget * widget, char * param)
Definition at line 15 of file layer_setting_engineer_misc.c.
References ServerInfo::firmwareUrl, QUIT_UPGRADE_FIRMWARE, RemoteGetServerInfo(), SceneQuit(), serverInfo, and UpgradeSetUrl().
bool SettingEngineerNetworkDnsButtonOnPress (ITUWidget * widget, char * param)
Definition at line 72 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkDnsCallback(), and SettingEngineerNetworkIPShow().
bool SettingEngineerNetworkGatewayButtonOnPress (ITUWidget * widget, char * param)
Definition at line 78 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkGatewayCallback(), and SettingEngineerNetworkIPShow().
bool SettingEngineerNetworkIPBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 24 of file layer_setting_engineer_network_ip.c.
References ituTextSetString, settingEngineerNetworkIP1TextBox, settingEngineerNetworkIP2TextBox, and settingEngineerNetworkIP3TextBox.
bool SettingEngineerNetworkIPButtonOnPress (ITUWidget * widget, char * param)
Definition at line 54 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkIPCallback(), and SettingEngineerNetworkIPShow().
bool SettingEngineerNetworkIPCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 116 of file layer_setting_engineer_network_ip.c.
References settingEngineerNetworkIPCloseCallback.
bool SettingEngineerNetworkIPClearButtonOnPress (ITUWidget * widget, char * param)
Definition at line 74 of file layer_setting_engineer_network_ip.c.
References ituTextBoxSetString(), and settingEngineerNetworkIP1TextBox.
bool SettingEngineerNetworkIPConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 84 of file layer_setting_engineer_network_ip.c.
References ituTextGetString, ituWidgetEnable, ituWidgetSetVisible, settingEngineerNetworkIP2TextBox, settingEngineerNetworkIP3TextBox, settingEngineerNetworkIP4TextBox, and settingEngineerNetworkIPCloseCallback.
bool SettingEngineerNetworkIPNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 43 of file layer_setting_engineer_network_ip.c.
References ituTextBoxInput(), ituTextGetString, ITUTextBox::maxLen, settingEngineerNetworkIP2TextBox, settingEngineerNetworkIP3TextBox, settingEngineerNetworkIP4TextBox, and ITUButton::text.
bool SettingEngineerNetworkIPOnEnter (ITUWidget * widget, char * param)
Definition at line 177 of file layer_setting_engineer_network_ip.c.
References ituSceneFindWidget(), and theScene.
bool SettingEngineerNetworkMacButtonOnPress (ITUWidget * widget, char * param)
Definition at line 66 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkMacCallback(), and SettingEngineerNetworkMacShow().
bool SettingEngineerNetworkMacKeypadCloseButtonOnPress (ITUWidget * widget, char * param)
Definition at line 15 of file layer_setting_engineer_network_mac.c.
References settingEngineerNetworkMacCloseCallback.
bool SettingEngineerNetworkMacKeypadConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 21 of file layer_setting_engineer_network_mac.c.
References ituSceneFindWidget(), ituTextGetString, settingEngineerNetworkMacCloseCallback, and theScene.
bool SettingEngineerNetworkNetmaskButtonOnPress (ITUWidget * widget, char * param)
Definition at line 60 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkIPShow(), and SettingEngineerNetworkNetmaskCallback().
bool SettingEngineerNetworkOnEnter (ITUWidget * widget, char * param)
Definition at line 142 of file layer_setting_engineer_network.c.
References Config::dhcp, Config::dns, Config::gw, ITPEthernetInfo::hardwareAddress, ITPEthernetInfo::index, Config::ipaddr, ITP_DEVICE_ETHERNET, ITP_IOCTL_GET_INFO, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituTextBoxSetString(), ituWidgetSetVisible, Config::netmask, theConfig, and theScene.
bool SettingEngineerNetworkSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 84 of file layer_setting_engineer_network.c.
References Config::area, Config::building, ConfigSave(), Config::dhcp, Config::dns, Config::ext, Config::floor, Config::gw, ITPEthernetInfo::hardwareAddress, i, Config::ipaddr, itp_codec_standby(), ITP_DEVICE_ETHERNET, ITP_IOCTL_WIRTE_MAC, ituRadioBoxIsChecked(), ituTextGetString, Config::netmask, QUIT_RESET_NETWORK, Config::room, SceneQuit(), theConfig, and Config::unit.
bool SettingEngineerNetworkWiFiConnectButtonOnPress (ITUWidget * widget, char * param)
Definition at line 120 of file layer_setting_engineer_network_wifi.c.
References ITUListBoxTag::focusIndex, gnApSecurity, i, itcTreeGetChildAt, ituWidgetGetCustomData, nApCount, pList, Config::secumode, settingEngineerNetworkWiFiShowPasswordDialog, Config::ssid, ITUText::string, ITUScrollText::text, and theConfig.
bool SettingEngineerNetworkWiFiDisconnectButtonOnPress (ITUWidget * widget, char * param)
Definition at line 230 of file layer_setting_engineer_network_wifi.c.
References ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituWidgetGetCustomData, Config::ssid, ITUText::string, ITUScrollText::text, and theConfig.
bool SettingEngineerNetworkWiFiNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 20 of file layer_setting_engineer_network_wifi.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, nApCount, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, pList, and ITCTreeTag::sibling.
bool SettingEngineerNetworkWiFiOnEnter (ITUWidget * widget, char * param)
Definition at line 270 of file layer_setting_engineer_network_wifi.c.
References ituSceneFindWidget(), settingEngineerNetworkWiFiShowPasswordDialog, and theScene.
bool SettingEngineerNetworkWiFiOnTimer (ITUWidget * widget, char * param)
Definition at line 244 of file layer_setting_engineer_network_wifi.c.
References ConfigSave(), gnApSecurity, i, ituWidgetDisable, Config::password, Config::secumode, SettingEngineerNetworkWiFiPasswordCallback(), SettingEngineerNetworkWiFiPasswordShow(), settingEngineerNetworkWiFiShowPasswordDialog, Config::ssid, and theConfig.
bool SettingEngineerNetworkWiFiPasswordCloseButtonOnPress (ITUWidget * widget, char * param)
Definition at line 16 of file layer_setting_engineer_network_wifi_password.c.
References settingEngineerNetworkWiFiPasswordCloseCallback.
bool SettingEngineerNetworkWiFiPasswordConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 22 of file layer_setting_engineer_network_wifi_password.c.
References ituSceneFindWidget(), ituTextGetString, settingEngineerNetworkWiFiPasswordCloseCallback, and theScene.
bool SettingEngineerNetworkWiFiStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 73 of file layer_setting_engineer_network_wifi.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool SettingEngineerOnEnter (ITUWidget * widget, char * param)
Definition at line 24 of file layer_setting_engineer.c.
References ituSceneFindWidget(), ituTextBoxSetString(), and theScene.
bool SettingEngineerPasswordConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 10 of file layer_setting_engineer.c.
References Config::engineer_password, ituTextBoxSetString(), ituTextGetString, and theConfig.
bool SettingEngineerSensorCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 40 of file layer_setting_engineer_sensor.c.
References ituRadioBoxSetChecked().
bool SettingEngineerSensorOnEnter (ITUWidget * widget, char * param)
Definition at line 53 of file layer_setting_engineer_sensor.c.
References GUARD_AREA, GUARD_DOOR, GUARD_EMERGENCY, GUARD_GAS, GUARD_INFRARED, GUARD_ROB, Config::guard_sensor_initvalues, GUARD_SMOKE, GUARD_WINDOW, ituRadioBoxSetChecked(), ituSceneFindWidget(), theConfig, and theScene.
bool SettingEngineerSensorSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 25 of file layer_setting_engineer_sensor.c.
References ConfigSave(), GUARD_AREA, GUARD_DOOR, GUARD_EMERGENCY, GUARD_GAS, GUARD_INFRARED, GUARD_ROB, Config::guard_sensor_initvalues, GUARD_SMOKE, GUARD_WINDOW, ituRadioBoxIsChecked(), and theConfig.
bool SettingOutdoorMainMessageListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 130 of file layer_setting_outdoor_main.c.
References ServerInfo::addressBookVersion, DeviceInfo::area, DeviceInfo::building, ITCTreeTag::child, DeviceInfo::ext, ServerInfo::firmwareVersion, DeviceInfo::floor, ITUListBoxTag::focusIndex, GetOutdoorInfoCallback(), i, DeviceInfo::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituSpriteGoto(), ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ServerInfo::playLevel, ServerInfo::recLevel, RemoteGetOutdoorInfo(), ServerInfo::ringLevel, DeviceInfo::room, settingOutdoorMainInfoCount, settingOutdoorMainInfoFilled, settingOutdoorMainInfoIndex, settingOutdoorMainLastMicLevel, settingOutdoorMainLastPlayLevel, settingOutdoorMainLastRingLevel, settingOutdoorMainMaxMicVol, settingOutdoorMainMaxPlayVol, settingOutdoorMainMaxRingVol, ITCTreeTag::sibling, StringGetDeviceType(), StringGetRoomAddress(), DeviceInfo::type, and DeviceInfo::unit.
Referenced by SettingOutdoorMainOnTimer().
bool SettingOutdoorMainMessageListBoxOnSelection (ITUWidget * widget, char * param)
Definition at line 255 of file layer_setting_outdoor_main.c.
References ituListBoxSelect().
bool SettingOutdoorMainMicVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 92 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastMicLevel, and settingOutdoorMainMaxMicVol.
bool SettingOutdoorMainMicVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 108 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastMicLevel, and settingOutdoorMainMaxMicVol.
bool SettingOutdoorMainOnEnter (ITUWidget * widget, char * param)
Definition at line 274 of file layer_setting_outdoor_main.c.
References AddressBookGetOutdoorInfoArray(), DeviceInfo::area, DeviceInfo::building, DeviceInfo::floor, itcTreeGetChildCount, ituListBoxReload(), ituSceneFindWidget(), ituSpriteGoto(), MAX_OUTDOOR_COUNT, DeviceInfo::room, settingOutdoorMainInfoCount, settingOutdoorMainInfoFilled, settingOutdoorMainInfoIndex, settingOutdoorMainLastMicLevel, settingOutdoorMainLastPlayLevel, settingOutdoorMainLastRingLevel, settingOutdoorMainMaxMicVol, settingOutdoorMainMaxPlayVol, settingOutdoorMainMaxRingVol, theDeviceInfo, theScene, and DeviceInfo::unit.
bool SettingOutdoorMainOnLeave (ITUWidget * widget, char * param)
Definition at line 313 of file layer_setting_outdoor_main.c.
bool SettingOutdoorMainOnTimer (ITUWidget * widget, char * param)
Definition at line 264 of file layer_setting_outdoor_main.c.
References settingOutdoorMainInfoFilled, and SettingOutdoorMainMessageListBoxOnLoad().
bool SettingOutdoorMainPlayVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 60 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastPlayLevel, and settingOutdoorMainMaxPlayVol.
bool SettingOutdoorMainPlayVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 76 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastPlayLevel, and settingOutdoorMainMaxPlayVol.
bool SettingOutdoorMainRingVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 28 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastRingLevel, and settingOutdoorMainMaxRingVol.
bool SettingOutdoorMainRingVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 44 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastRingLevel, and settingOutdoorMainMaxRingVol.
bool SettingOutdoorMiscCallingTimeDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 35 of file layer_setting_outdoor_misc.c.
References ituTextBoxBack(), and settingOutdoorMiscCallingTimeTextBox.
bool SettingOutdoorMiscClearButtonOnPress (ITUWidget * widget, char * param)
Definition at line 66 of file layer_setting_outdoor_misc.c.
References ituTextBoxSetString(), settingOutdoorMiscDialTimeTextBox, and settingOutdoorMiscVoiceMemoTimeTextBox.
bool SettingOutdoorMiscConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 81 of file layer_setting_outdoor_misc.c.
References settingOutdoorMiscCallingTimeTextBox, and settingOutdoorMiscVoiceMemoTimeTextBox.
bool SettingOutdoorMiscDialTimeDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 21 of file layer_setting_outdoor_misc.c.
References ituTextBoxBack(), and settingOutdoorMiscDialTimeTextBox.
bool SettingOutdoorMiscNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 42 of file layer_setting_outdoor_misc.c.
References ituTextBoxInput(), ituTextGetString, ituTextSetString, ITUTextBox::maxLen, settingOutdoorMiscCallingTimeTextBox, settingOutdoorMiscVoiceMemoTimeTextBox, and ITUButton::text.
bool SettingOutdoorMiscOnEnter (ITUWidget * widget, char * param)
Definition at line 122 of file layer_setting_outdoor_misc.c.
References ServerInfo::callingTime, ServerInfo::dialTime, ituSceneFindWidget(), ituTextBoxSetString(), settingOutdoorMainInfoIndex, settingOutdoorMiscDialTimeTextBox, theScene, and ServerInfo::voiceMemoTime.
bool SettingOutdoorMiscSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 93 of file layer_setting_outdoor_misc.c.
References ServerInfo::callingTime, ServerInfo::dialTime, DeviceInfo::ip, ituTextBoxGetString(), ServerInfo::playLevel, ServerInfo::recLevel, RemoteSetOutdoorConfig(), ServerInfo::ringLevel, settingOutdoorMainInfoIndex, settingOutdoorMainLastMicLevel, settingOutdoorMainLastPlayLevel, settingOutdoorMainLastRingLevel, and ServerInfo::voiceMemoTime.
bool SettingOutdoorMiscVoiceMemoTimeDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 28 of file layer_setting_outdoor_misc.c.
References ituTextBoxBack(), and settingOutdoorMiscVoiceMemoTimeTextBox.
bool SettingPhoneAudioCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 157 of file layer_setting_phone_audio.c.
References ituRadioBoxSetChecked(), ituSpriteGoto(), KEY1, KEY2, KEY3, Config::keylevel, Config::keysound, LinphoneSetRingLevel(), LinphoneSetRingSound(), RING2, RING3, settingPhoneLastKeypadSoundLevel, settingPhoneLastKeySound, settingPhoneLastRingLevel, settingPhoneLastRingSound, settingPhoneMaxKeypadSoundVol, settingPhoneMaxRingVol, and theConfig.
bool SettingPhoneAudioKeypadSoundRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 92 of file layer_setting_phone_audio.c.
References KEY1, KEY2, KEY3, Config::keysound, and theConfig.
bool SettingPhoneAudioKeypadSoundVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 111 of file layer_setting_phone_audio.c.
References ituSpriteGoto(), Config::keylevel, LinphoneSetKeyLevel(), settingPhoneMaxKeypadSoundVol, and theConfig.
bool SettingPhoneAudioKeypadSoundVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 128 of file layer_setting_phone_audio.c.
References ituSpriteGoto(), Config::keylevel, LinphoneSetKeyLevel(), settingPhoneMaxKeypadSoundVol, and theConfig.
bool SettingPhoneAudioOnEnter (ITUWidget * widget, char * param)
Definition at line 190 of file layer_setting_phone_audio.c.
References itcTreeGetChildCount, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituSpriteGoto(), KEY1, KEY2, KEY3, Config::keylevel, Config::keysound, LinphoneGetRingLevel(), RING2, RING3, Config::ringsound, settingPhoneLastKeypadSoundLevel, settingPhoneLastKeySound, settingPhoneLastRingLevel, settingPhoneLastRingSound, settingPhoneMaxKeypadSoundVol, settingPhoneMaxRingVol, theConfig, and theScene.
bool SettingPhoneAudioOnLeave (ITUWidget * widget, char * param)
Definition at line 250 of file layer_setting_phone_audio.c.
References Config::keylevel, Config::keysound, LinphoneGetRingLevel(), LinphoneSetRingLevel(), LinphoneSetRingSound(), Config::ringsound, settingPhoneLastKeypadSoundLevel, settingPhoneLastKeySound, settingPhoneLastRingLevel, settingPhoneLastRingSound, and theConfig.
bool SettingPhoneAudioRingRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 38 of file layer_setting_phone_audio.c.
References ituSceneExecuteCommand(), LinphoneSetRingSound(), RING1, RING2, RING3, SettingPhoneAudioPlayRingSound(), and theScene.
bool SettingPhoneAudioRingVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 58 of file layer_setting_phone_audio.c.
References ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneSetRingLevel(), and settingPhoneMaxRingVol.
bool SettingPhoneAudioRingVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 75 of file layer_setting_phone_audio.c.
References ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneSetRingLevel(), and settingPhoneMaxRingVol.
bool SettingPhoneAudioSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 145 of file layer_setting_phone_audio.c.
References ConfigSave(), Config::keylevel, Config::keysound, LinphoneGetRingLevel(), Config::ringsound, settingPhoneLastKeypadSoundLevel, settingPhoneLastKeySound, settingPhoneLastRingLevel, settingPhoneLastRingSound, and theConfig.
bool SettingPhoneDisturbCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 129 of file layer_setting_phone_disturb.c.
References Config::do_not_disturb_mode, Config::do_not_disturb_option, DONOT_DISTURB_ALL, DONOT_DISTURB_HANGUP, DONOT_DISTURB_MESSAGE, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_REDIRECT, DONOT_DISTURB_TIME, DONOT_DISTURB_VOICEMEMO, ituRadioBoxSetChecked(), ituWidgetSetVisible, and theConfig.
bool SettingPhoneDisturbOnEnter (ITUWidget * widget, char * param)
Definition at line 264 of file layer_setting_phone_disturb.c.
References Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_mode, Config::do_not_disturb_option, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, DONOT_DISTURB_ALL, DONOT_DISTURB_HANGUP, DONOT_DISTURB_MESSAGE, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_REDIRECT, DONOT_DISTURB_TIME, DONOT_DISTURB_VOICEMEMO, DeviceInfo::ext, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituTextBoxSetString(), ituWidgetSetVisible, theConfig, theDeviceInfo, and theScene.
bool SettingPhoneDisturbSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 40 of file layer_setting_phone_disturb.c.
References AudioMute(), AudioUnMute(), ConfigSave(), Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_mode, Config::do_not_disturb_option, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, DONOT_DISTURB_ALL, DONOT_DISTURB_HANGUP, DONOT_DISTURB_MESSAGE, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_REDIRECT, DONOT_DISTURB_TIME, DONOT_DISTURB_VOICEMEMO, EVENT_CUSTOM_DISTURB_MODE, DeviceInfo::ext, GuardIsAlarming(), ituRadioBoxIsChecked(), ituRadioBoxSetChecked(), ituSceneSendEvent(), ituTextBoxGetString(), LinphoneDisableDoNotDisturb(), LinphoneEnableDoNotDisturb(), RemoteSetDontDisturbConfig(), SceneSetLastDoNotDisturbMode(), theConfig, theDeviceInfo, and theScene.
bool SettingPhoneDisturbTimeCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 226 of file layer_setting_phone_disturb.c.
References Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, ituTextBoxSetString(), ituWidgetEnable, ituWidgetSetVisible, and theConfig.
bool SettingPhoneDisturbTimeConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 244 of file layer_setting_phone_disturb.c.
References ituRadioBoxSetChecked(), ituTextBoxGetString(), ituWidgetEnable, and ituWidgetSetVisible.
bool SettingPhoneDisturbTimeDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 203 of file layer_setting_phone_disturb.c.
References ituTextBoxGetString(), and ituTextBoxSetString().
bool SettingPhoneDisturbTimeRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 32 of file layer_setting_phone_disturb.c.
References ituWidgetDisable, ituWidgetSetVisible, and settingPhoneDisturbTimeStartHourTextBox.
bool SettingPhoneDisturbTimeTextBoxOnPress (ITUWidget * widget, char * param)
Definition at line 174 of file layer_setting_phone_disturb.c.
bool SettingPhoneDisturbTimeUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 180 of file layer_setting_phone_disturb.c.
References ituTextBoxGetString(), and ituTextBoxSetString().
bool SettingPhoneVoiceCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 95 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneSetMicLevel(), LinphoneSetVoiceLevel(), settingPhoneLastMicLevel, settingPhoneLastVoiceLevel, settingPhoneMaxVoiceMicVol, and settingPhoneMaxVoiceVol.
bool SettingPhoneVoiceMicVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 51 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneGetMicLevel(), LinphoneSetMicLevel(), and settingPhoneMaxVoiceMicVol.
bool SettingPhoneVoiceMicVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 68 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneGetMicLevel(), LinphoneSetMicLevel(), and settingPhoneMaxVoiceMicVol.
bool SettingPhoneVoiceOnEnter (ITUWidget * widget, char * param)
Definition at line 109 of file layer_setting_phone_voice.c.
References itcTreeGetChildCount, ituSceneFindWidget(), ituSpriteGoto(), LinphoneGetMicLevel(), LinphoneGetVoiceLevel(), settingPhoneLastMicLevel, settingPhoneLastVoiceLevel, settingPhoneMaxVoiceMicVol, settingPhoneMaxVoiceVol, and theScene.
bool SettingPhoneVoiceOnLeave (ITUWidget * widget, char * param)
Definition at line 135 of file layer_setting_phone_voice.c.
References LinphoneGetMicLevel(), LinphoneGetVoiceLevel(), LinphoneSetMicLevel(), LinphoneSetVoiceLevel(), settingPhoneLastMicLevel, and settingPhoneLastVoiceLevel.
bool SettingPhoneVoiceSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 85 of file layer_setting_phone_voice.c.
References ConfigSave(), LinphoneGetMicLevel(), LinphoneGetVoiceLevel(), settingPhoneLastMicLevel, and settingPhoneLastVoiceLevel.
bool SettingPhoneVoiceVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 17 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneGetVoiceLevel(), LinphoneSetVoiceLevel(), and settingPhoneMaxVoiceVol.
bool SettingPhoneVoiceVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 34 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneGetVoiceLevel(), LinphoneSetVoiceLevel(), and settingPhoneMaxVoiceVol.
bool SettingSystemItemListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_setting_system.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, settingSystemInfoArray, settingSystemInfoCount, ITCTreeTag::sibling, and StringGetSystemInfoArray().
bool SettingSystemMessageListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 64 of file layer_setting_system.c.
References AddressBookGetVersion(), ServerInfo::addressBookVersion, DeviceInfo::area, DeviceInfo::building, ITCTreeTag::child, DeviceInfoIsInEngineerMode(), DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, Config::gw, i, DeviceInfo::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, settingSystemInfoArray, settingSystemInfoCount, ITCTreeTag::sibling, StringGetDeviceType(), StringGetRoomAddress(), StringGetSystemInfoArray(), StringGetWorkMode(), theConfig, theDeviceInfo, theEntranceInfo, theOutdoorInfo, theOutdoorServerInfo, DeviceInfo::type, and DeviceInfo::unit.
bool SettingSystemOnEnter (ITUWidget * widget, char * param)
Definition at line 170 of file layer_setting_system.c.
References ituSceneFindWidget(), and theScene.
bool TimeClearButtonOnPress (ITUWidget * widget, char * param)
Definition at line 47 of file layer_time.c.
References ituTextSetString, timeDayTextBox, timeHourTextBox, timeMinuteTextBox, timeMonthTextBox, and timeYearTextBox.
bool TimeConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 74 of file layer_time.c.
References ituTextGetString.
bool TimeNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 19 of file layer_time.c.
References ituTextBoxInput(), ituTextGetString, ITUTextBox::maxLen, ITUButton::text, timeDayTextBox, timeHourTextBox, timeMinuteTextBox, timeMonthTextBox, and timeSecondTextBox.
bool TimeOnEnter (ITUWidget * widget, char * param)
Definition at line 123 of file layer_time.c.
References ituSceneFindWidget(), ituTextBoxSetString(), theScene, and timeYearTextBox.
bool TouchCalibrationCheckBoxOnPress (ITUWidget * widget, char * param)
Definition at line 23 of file layer_touch_calibration.c.
References Castor3_CalibrateTouch(), Castor3_ReadTouchRawPosition(), ConfigSave(), itp_codec_standby(), ituCheckBoxIsChecked(), ituCheckBoxSetChecked(), screenX, screenY, theConfig, Config::touch_calibration, touchX, touchY, and font::x.
bool TouchCalibrationOnEnter (ITUWidget * widget, char * param)
Definition at line 87 of file layer_touch_calibration.c.
References Castor3_ChangeTouchMode(), ituCheckBoxSetChecked(), ituSceneFindWidget(), ituWidgetGetGlobalPosition, ituWidgetGetHeight, ituWidgetGetWidth, ituWidgetSetVisible, screenX, screenY, theScene, and font::x.
bool TouchCalibrationOnLeave (ITUWidget * widget, char * param)
Definition at line 141 of file layer_touch_calibration.c.
References Castor3_ChangeTouchMode().
bool UpgradeOnEnter (ITUWidget * widget, char * param)
Definition at line 21 of file layer_upgrade.c.
References ituSceneFindWidget(), SceneGetQuitValue(), theScene, and UpgradeProcess().
bool UpgradeOnTimer (ITUWidget * widget, char * param)
Definition at line 10 of file layer_upgrade.c.
References ituLayerGoto(), NetworkSntpUpdate(), QUIT_NONE, SceneQuit(), and UpgradeIsFinished().
bool VideoRecordHangUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 21 of file layer_videorecord.c.
References ituButtonSetPressed(), LinphoneTerminate(), and SceneHangUp().
bool VideoRecordOnEnter (ITUWidget * widget, char * param)
Definition at line 119 of file layer_videorecord.c.
References ituSceneFindWidget(), LinphoneSetWindowID(), theScene, and videoRecordInVideoState.
bool VideoRecordOnLeave (ITUWidget * widget, char * param)
Definition at line 149 of file layer_videorecord.c.
References VideoMemoStopRecord(), videoRecordID, and videoRecordInVideoState.
bool VideoRecordOnTimer (ITUWidget * widget, char * param)
Definition at line 81 of file layer_videorecord.c.
References font::f, ituLayerGoto(), ituTextSetString, LinphoneTerminate(), SceneHangUp(), videoRecordCountDown, and videoRecordLastTick.
Variable Documentation
ITUActionFunction actionFunctions[]
Examples:
test_itu/test_trackbar.c.
Definition at line 501 of file function_table.c.