ITE SoC SDK: Chip ID
Chip ID
ITE Hardware Library
Enumerations
enum ITHPackageId {
ITH_IT9072 = 0x6, ITH_IT9076 = 0x4, ITH_IT9078 = 0x1, ITH_IT9079 = 0x5,
ITH_IT9079H = 0x7, ITH_IT9852_WB = 0x4, ITH_IT9852_ET = 0x5, ITH_IT9856_WB = 0x6,
ITH_IT9856_ET = 0x7, ITH_IT9854_WB = 0x0, ITH_IT9854_ET = 0x1, ITH_IT9866_WB = 0x2,
ITH_IT9866_ET = 0x3
}
Functions
static unsigned int ithGetDeviceId (void)
Gets device ID.
static unsigned int ithGetRevisionId (void)
Gets device revision ID.
static unsigned int ithIsTilingModeOn (void)
static unsigned int ithTilingPitch (void)
ITHPackageId ithGetPackageId (void)
Gets device package ID.
Detailed Description
Enumeration Type Documentation
enum ITHPackageId
Enumerator
ITH_IT9072
128 LQFP
ITH_IT9076
128 LQFP
ITH_IT9078
216 LQFP
ITH_IT9079
176 TQFP
ITH_IT9079H
144 TQFP
ITH_IT9852_WB
128 LQFP
ITH_IT9852_ET
128 LQFP
ITH_IT9856_WB
144 TQFP
ITH_IT9856_ET
144 TQFP
ITH_IT9854_WB
128 LQFP
ITH_IT9854_ET
128 LQFP
ITH_IT9866_WB
144 TQFP
ITH_IT9866_ET
144 TQFP
Definition at line 627 of file ith.h.
Function Documentation
static unsigned int ithGetDeviceId (void) inline static
Gets device ID.
Returns
The device ID.
Definition at line 649 of file ith.h.
References ITH_DEVICE_ID_REG, and ithReadRegH().
ITHPackageId ithGetPackageId (void)
Gets device package ID.
Returns
The device package ID.
static unsigned int ithGetRevisionId (void) inline static
Gets device revision ID.
Returns
The device revision ID.
Definition at line 659 of file ith.h.
References ITH_DEVICE_ID_REG, ITH_GPIO1_PULLEN_REG, ITH_GPIO_BASE, ITH_REVISION_ID_REG, ithReadRegA(), and ithReadRegH().
static unsigned int ithIsTilingModeOn (void) inline static
Definition at line 693 of file ith.h.
References ithReadRegH().
static unsigned int ithTilingPitch (void) inline static
Definition at line 718 of file ith.h.
References ithReadRegH().