ITE SoC SDK: Remote
Remote
ITE DoorBell Indoor Modules
Data Structures
struct ServerInfo
Control Server/Door Camera information definition.
Typedefs
typedef void(* RemoteGetWeatherCallback)(char *xml, int size)
The function definition of getting the weather information.
typedef void(* RemoteGetOutdoorInfoCallback)(ServerInfo *info)
The function definition of getting the door camera information.
Functions
void RemoteInit (void)
Initializes remote module.
void RemoteExit (void)
Exits remote module.
void RemoteOpenDoor (char *ip)
Opens door of the specified IP address.
bool RemoteCheckCard (char *cardnum)
Verifies the card number from the control server.
void RemoteCallElevator (bool up)
Invokes the elevator.
ServerInfo * RemoteGetServerInfo (void)
Gets the information of control server.
int RemoteSetOutdoorSetting (char *ip, char *area, char *building, char *unit, char *floor, char *room, char *ext)
Sets the configuration to door camera.
void RemoteGetWeather (RemoteGetWeatherCallback func)
Gets the weather information.
void RemoteSetDontDisturbConfig (void)
Sets the do not disturb configuration to the other extension devices of indoor phone.
void RemoteGetDontDisturbConfig (void)
Gets the do not disturb configuration from the first device of indoor phone.
void RemoteGetOutdoorInfo (char *ip, RemoteGetOutdoorInfoCallback func)
Gets the door camera information.
void RemoteSetOutdoorConfig (char *ip, int ringLevel, int playLevel, int recLevel, int dialTime, int voiceMemoTime, int callingTime)
Sets the door camera configuration.
Variables
ServerInfo theOutdoorServerInfo
Door camera information.
Detailed Description
Typedef Documentation
typedef void(* RemoteGetOutdoorInfoCallback)(ServerInfo *info)
The function definition of getting the door camera information.
Parameters
info The pointer to retrieve ServerInfo.
Definition at line 1727 of file doorbell_indoor/doorbell.h.
typedef void(* RemoteGetWeatherCallback)(char *xml, int size)
The function definition of getting the weather information.
Parameters
xml The pointer to retrieve the weather XML data.
size The XML size.
Definition at line 1720 of file doorbell_indoor/doorbell.h.
Function Documentation
void RemoteCallElevator (bool up)
Invokes the elevator.
Parameters
up The direction is up or not.
Definition at line 289 of file doorbell_indoor/remote.c.
References attr, NetworkIsReady(), remoteCallElevatorTasking, and RemoteInvokeCallElevatorTask().
Referenced by MainCallElevatorDownButtonOnPress(), and MainCallElevatorUpButtonOnPress().
bool RemoteCheckCard (char * cardnum)
Verifies the card number from the control server.
Parameters
cardnum The card number to verify.
Returns
true for valid; false for invalid.
Definition at line 188 of file doorbell_indoor/remote.c.
Referenced by CardListCheckTask().
void RemoteExit (void)
Exits remote module.
Definition at line 60 of file doorbell_indoor/remote.c.
References remoteOpenDoorSem, remoteOpenDoorTask, and remoteQuit.
Referenced by SDL_main().
void RemoteGetDontDisturbConfig (void)
Gets the do not disturb configuration from the first device of indoor phone.
Definition at line 887 of file doorbell_indoor/remote.c.
References AddressBookGetDeviceIP(), DeviceInfo::area, attr, DeviceInfo::building, DeviceInfo::floor, NetworkIsReady(), RemoteGetDontDisturbConfigTask(), remoteGetDontDisturbConfigTasking, DeviceInfo::room, theDeviceInfo, and DeviceInfo::unit.
Referenced by ResetEthernet().
void RemoteGetOutdoorInfo (char * ip, RemoteGetOutdoorInfoCallback func)
Gets the door camera information.
Parameters
ip The door camera ip.
func The callback function to call when the downloading finished.
Definition at line 1096 of file doorbell_indoor/remote.c.
References attr, NetworkIsReady(), RemoteGetOutdoorInfoTask(), and remoteGetOutdoorInfoTasking.
Referenced by RemoteInit(), SettingEngineerMiscTwiceSettingButtonOnPress(), and SettingOutdoorMainMessageListBoxOnLoad().
ServerInfo* RemoteGetServerInfo (void)
Gets the information of control server.
Returns
The ServerInfo of control server.
Definition at line 302 of file doorbell_indoor/remote.c.
Referenced by SettingEngineerMiscUpgradeButtonOnPress().
void RemoteGetWeather (RemoteGetWeatherCallback func)
Gets the weather information.
Parameters
func The callback function to call when the downloading finished.
Definition at line 651 of file doorbell_indoor/remote.c.
References attr, NetworkServerIsReady(), RemoteGetWeatherTask(), and remoteGetWeatherTasking.
Referenced by MainWeatherOnEnter().
void RemoteInit (void)
Initializes remote module.
Definition at line 35 of file doorbell_indoor/remote.c.
Referenced by SDL_main().
void RemoteOpenDoor (char * ip)
Opens door of the specified IP address.
Parameters
ip The IP address to open door.
Definition at line 179 of file doorbell_indoor/remote.c.
References NetworkIsReady(), remoteOpenDoorIP, and remoteOpenDoorSem.
Referenced by SceneOpenDoor().
void RemoteSetDontDisturbConfig (void)
Sets the do not disturb configuration to the other extension devices of indoor phone.
Definition at line 730 of file doorbell_indoor/remote.c.
References AddressBookGetDeviceInfoArray(), DeviceInfo::area, attr, DeviceInfo::building, DeviceInfo::floor, LINPHONE_CASTOR3_MAX_IP_COUNT, NetworkIsReady(), RemoteSetDontDisturbConfigTask(), DeviceInfo::room, theDeviceInfo, and DeviceInfo::unit.
Referenced by ResetEthernet(), and SettingPhoneDisturbSaveButtonOnPress().
void RemoteSetOutdoorConfig (char * ip, int ringLevel, int playLevel, int recLevel, int dialTime, int voiceMemoTime, int callingTime)
Sets the door camera configuration.
Parameters
ip The door camera ip.
ringLevel The ring level.
playLevel The play level.
recLevel The record level.
dialTime The dial time.
voiceMemoTime The voice memo time.
callingTime The calling time.
Definition at line 1171 of file doorbell_indoor/remote.c.
References attr, NetworkIsReady(), and RemoteSetOutdoorConfigTask().
Referenced by SettingOutdoorMiscSaveButtonOnPress().
int RemoteSetOutdoorSetting (char * ip, char * area, char * building, char * unit, char * floor, char * room, char * ext)
Sets the configuration to door camera.
Parameters
ip the IP address string.
area The area code of address.
building The building code of address.
unit The unit code of address.
floor The floor code of address.
room The room code of address.
ext The ext code of address.
Returns
0 for success; otherwise for fail.
Definition at line 551 of file doorbell_indoor/remote.c.
Referenced by SettingEngineerMiscTwiceSettingButtonOnPress().
Variable Documentation
ServerInfo theOutdoorServerInfo
Door camera information.
Definition at line 15 of file doorbell_indoor/remote.c.
Referenced by create_response(), and SettingSystemMessageListBoxOnLoad().