ITE SoC SDK: LCD
LCD
ITE Hardware Library
Enumerations
enum ITHLcdFormat {
ITH_LCD_RGB565 = 0, ITH_LCD_ARGB1555 = 1, ITH_LCD_ARGB4444 = 2, ITH_LCD_ARGB8888 = 3,
ITH_LCD_YUV = 4
}
enum ITHLcdCursorCtrl { ITH_LCD_CURSOR_ALPHABLEND_ENABLE = 0, ITH_LCD_CURSOR_DEFDEST_ENABLE, ITH_LCD_CURSOR_INVDEST_ENABLE }
Cursor control definition.
enum ITHLcdCursorColor { ITH_LCD_CURSOR_DEF_COLOR = 0, ITH_LCD_CURSOR_FG_COLOR, ITH_LCD_CURSOR_BG_COLOR }
Cursor color definition.
enum ITHLcdIntrCtrl {
ITH_LCD_INTR_ENABLE = 0, ITH_LCD_INTR_OUTPUT2, ITH_LCD_INTR_FIELDMODE2, ITH_LCD_INTR_OUTPUT1,
ITH_LCD_INTR_FIELDMODE1
}
LCD interupt controls definition.
Functions
void ithLcdReset (void)
Resets LCD module.
void ithLcdLoadScriptFirst (const uint16_t *script, unsigned int count)
Loads the first part of LCD initial script.
void ithLcdLoadScriptNext (void)
Runs the next part of LCD initial script.
void ithLcdEnable (void)
Enables LCD module.
void ithLcdDisable (void)
Disables LCD module.
void ithLcdSetBaseAddrA (uint32_t addr)
Sets LCD base address A.
static uint32_t ithLcdGetBaseAddrA (void)
Gets LCD base address A.
void ithLcdSetBaseAddrB (uint32_t addr)
Sets LCD base address A.
uint32_t ithLcdGetBaseAddrB (void)
Gets LCD base address B.
void ithLcdSetBaseAddrC (uint32_t addr)
Sets LCD base address C.
uint32_t ithLcdGetBaseAddrC (void)
Gets LCD base address C.
void ithLcdEnableHwFlip (void)
Enables hardware flip.
void ithLcdDisableHwFlip (void)
Disables hardware flip.
void ithLcdEnableVideoFlip (void)
Enables video flip.
void ithLcdDisableVideoFlip (void)
Disables video flip.
ITHLcdFormat ithLcdGetFormat (void)
Gets current LCD format.
static unsigned int ithLcdGetWidth (void)
Gets current LCD width.
void ithLcdSetWidth (uint32_t width)
Sets current LCD width.
static unsigned int ithLcdGetHeight (void)
Gets current LCD height.
void ithLcdSetHeight (uint32_t height)
Sets current LCD height.
static unsigned int ithLcdGetPitch (void)
Gets current LCD pitch.
void ithLcdSetPitch (uint32_t pitch)
Sets current LCD pitch.
unsigned int ithLcdGetXCounter (void)
Gets current LCD scanline on X coordinate.
unsigned int ithLcdGetYCounter (void)
Gets current LCD scanline on Y coordinate.
void ithLcdSyncFire (void)
Synchronize fire LCD.
bool ithLcdIsSyncFired (void)
Is LCD synchronize fire or not.
bool ithLcdIsEnabled (void)
Is LCD enabled or not.
unsigned int ithLcdGetFlip (void)
Gets current LCD flip counter.
unsigned int ithLcdGetMaxLcdBufCount (void)
void ithLcdSwFlip (unsigned int index)
Software flip the LCD.
void ithLcdCursorEnable (void)
Enables hardware cursor.
void ithLcdCursorDisable (void)
Disables hardware cursor.
void ithLcdCursorCtrlEnable (ITHLcdCursorCtrl ctrl)
Enables specified cursor controls.
void ithLcdCursorCtrlDisable (ITHLcdCursorCtrl ctrl)
Disables specified cursor controls.
void ithLcdCursorSetWidth (unsigned int width)
Sets the width of cursor.
void ithLcdCursorSetHeight (unsigned int height)
Sets the height of cursor.
void ithLcdCursorSetPitch (unsigned int pitch)
Sets the pitch of cursor.
void ithLcdCursorSetX (unsigned int x)
Sets the X coordinate of cursor.
void ithLcdCursorSetY (unsigned int y)
Sets the Y coordinate of cursor.
void ithLcdCursorSetBaseAddr (uint32_t addr)
Sets base address of cursor.
void ithLcdCursorSetColor (ITHLcdCursorColor color, uint16_t value)
Sets the color of cursor.
void ithLcdCursorSetColorWeight (ITHLcdCursorColor color, uint8_t value)
Sets the color weight of cursor.
void ithLcdCursorUpdate (void)
Updates the cursor.
bool ithLcdCursorIsUpdateDone (void)
Is cursor updated or not.
void ithLcdIntrCtrlEnable (ITHLcdIntrCtrl ctrl)
Enables specified interrupt controls.
void ithLcdIntrCtrlDisable (ITHLcdIntrCtrl ctrl)
Disables specified interrupt controls.
void ithLcdIntrEnable (void)
Enables LCD interrupt.
void ithLcdIntrDisable (void)
Disables LCD interrupt.
void ithLcdIntrClear (void)
Clears LCD interrupt.
void ithLcdIntrSetScanLine1 (unsigned int line)
Sets the first scanline to interrupt.
void ithLcdIntrSetScanLine2 (unsigned int line)
Sets the second scanline to interrupt.
Detailed Description
Enumeration Type Documentation
enum ITHLcdCursorColor
Cursor color definition.
Enumerator
ITH_LCD_CURSOR_DEF_COLOR
Hardware cursor default color (RGB565)
ITH_LCD_CURSOR_FG_COLOR
Hardware cursor foreground color (RGB565)
ITH_LCD_CURSOR_BG_COLOR
Hardware cursor background color (RGB565)
Definition at line 1870 of file ith.h.
enum ITHLcdCursorCtrl
Cursor control definition.
Enumerator
ITH_LCD_CURSOR_ALPHABLEND_ENABLE
Enable hardware cursor alpha blending function.
ITH_LCD_CURSOR_DEFDEST_ENABLE
Enable hardware cursor default destination data (RGB565)
ITH_LCD_CURSOR_INVDEST_ENABLE
Inverse hardware cursor re-define dstination color when hardware cursor is "11".
Definition at line 1860 of file ith.h.
enum ITHLcdFormat
Enumerator
ITH_LCD_RGB565
RGB565 format.
ITH_LCD_ARGB1555
ARGB1555 format.
ITH_LCD_ARGB4444
ARGB4444 format.
ITH_LCD_ARGB8888
ARGB8888 format.
ITH_LCD_YUV
YUV format.
Definition at line 1620 of file ith.h.
enum ITHLcdIntrCtrl
LCD interupt controls definition.
Enumerator
ITH_LCD_INTR_ENABLE
Enable LCD Interrupt.
ITH_LCD_INTR_OUTPUT2
Interrupt from output2 (9070)
ITH_LCD_INTR_FIELDMODE2
Output2 Interrupt on field mode (9070)
ITH_LCD_INTR_OUTPUT1
Interrupt from output1 (9070)
ITH_LCD_INTR_FIELDMODE1
output1 Interrupt on field mode (9070/9850)
Definition at line 1975 of file ith.h.
Function Documentation
void ithLcdCursorCtrlDisable (ITHLcdCursorCtrl ctrl)
Disables specified cursor controls.
Parameters
ctrl the controls to disable.
void ithLcdCursorCtrlEnable (ITHLcdCursorCtrl ctrl)
Enables specified cursor controls.
Parameters
ctrl the controls to enable.
void ithLcdCursorDisable (void)
Disables hardware cursor.
void ithLcdCursorEnable (void)
Enables hardware cursor.
bool ithLcdCursorIsUpdateDone (void)
Is cursor updated or not.
Returns
Is cursor updated or not.
void ithLcdCursorSetBaseAddr (uint32_t addr)
Sets base address of cursor.
Parameters
addr the base address to set.
void ithLcdCursorSetColor (ITHLcdCursorColor color, uint16_t value)
Sets the color of cursor.
Parameters
color the color type to set.
value the color value to set.
void ithLcdCursorSetColorWeight (ITHLcdCursorColor color, uint8_t value)
Sets the color weight of cursor.
Parameters
color the color type to set.
value the weight value to set.
void ithLcdCursorSetHeight (unsigned int height)
Sets the height of cursor.
Parameters
height the height.
void ithLcdCursorSetPitch (unsigned int pitch)
Sets the pitch of cursor.
Parameters
pitch the pitch.
void ithLcdCursorSetWidth (unsigned int width)
Sets the width of cursor.
Parameters
width the width.
void ithLcdCursorSetX (unsigned int x)
Sets the X coordinate of cursor.
Parameters
x the X coordinate.
void ithLcdCursorSetY (unsigned int y)
Sets the Y coordinate of cursor.
Parameters
y the Y coordinate.
void ithLcdCursorUpdate (void)
Updates the cursor.
void ithLcdDisable (void)
Disables LCD module.
void ithLcdDisableHwFlip (void)
Disables hardware flip.
void ithLcdDisableVideoFlip (void)
Disables video flip.
void ithLcdEnable (void)
Enables LCD module.
void ithLcdEnableHwFlip (void)
Enables hardware flip.
void ithLcdEnableVideoFlip (void)
Enables video flip.
static uint32_t ithLcdGetBaseAddrA (void) inline static
Gets LCD base address A.
Returns
the address A.
Examples:
test_lcd/test_backlight.c, and test_lcd/test_lcd.c.
Definition at line 1673 of file ith.h.
References ITH_LCD_BASEA_HI_MASK, ITH_LCD_BASEA_HI_REG, ITH_LCD_BASEA_LO_MASK, ITH_LCD_BASEA_LO_REG, ithReadRegA(), and ithReadRegH().
Referenced by UpgradeInit().
uint32_t ithLcdGetBaseAddrB (void)
Gets LCD base address B.
Returns
the address B.
uint32_t ithLcdGetBaseAddrC (void)
Gets LCD base address C.
Returns
the address C.
unsigned int ithLcdGetFlip (void)
Gets current LCD flip counter.
Returns
the flip counter. 0 is A, 1 is B, 2 is C.
ITHLcdFormat ithLcdGetFormat (void)
Gets current LCD format.
Returns
the LCD format.
static unsigned int ithLcdGetHeight (void) inline static
Gets current LCD height.
Returns
the LCD height.
Examples:
test_lcd/test_backlight.c, and test_lcd/test_lcd.c.
Definition at line 1766 of file ith.h.
References ITH_LCD_HEIGHT_BIT, ITH_LCD_HEIGHT_MASK, ITH_LCD_HEIGHT_REG, ithReadRegA(), and ithReadRegH().
Referenced by UpgradeInit().
unsigned int ithLcdGetMaxLcdBufCount (void)
static unsigned int ithLcdGetPitch (void) inline static
Gets current LCD pitch.
Returns
the LCD pitch.
Examples:
test_lcd/test_backlight.c, and test_lcd/test_lcd.c.
Definition at line 1789 of file ith.h.
References ITH_LCD_PITCH_BIT, ITH_LCD_PITCH_MASK, ITH_LCD_PITCH_REG, ithReadRegA(), and ithReadRegH().
Referenced by UpgradeInit().
static unsigned int ithLcdGetWidth (void) inline static
Gets current LCD width.
Returns
the LCD width.
Definition at line 1745 of file ith.h.
References ITH_LCD_WIDTH_BIT, ITH_LCD_WIDTH_MASK, ITH_LCD_WIDTH_REG, ithReadRegA(), and ithReadRegH().
unsigned int ithLcdGetXCounter (void)
Gets current LCD scanline on X coordinate.
Returns
the LCD scanline on X coordinate.
unsigned int ithLcdGetYCounter (void)
Gets current LCD scanline on Y coordinate.
Returns
the LCD scanline on Y coordinate.
void ithLcdIntrClear (void)
Clears LCD interrupt.
void ithLcdIntrCtrlDisable (ITHLcdIntrCtrl ctrl)
Disables specified interrupt controls.
Parameters
ctrl the controls to disable.
void ithLcdIntrCtrlEnable (ITHLcdIntrCtrl ctrl)
Enables specified interrupt controls.
Parameters
ctrl the controls to enable.
void ithLcdIntrDisable (void)
Disables LCD interrupt.
void ithLcdIntrEnable (void)
Enables LCD interrupt.
void ithLcdIntrSetScanLine1 (unsigned int line)
Sets the first scanline to interrupt.
Parameters
line the scanline to interrupt.
void ithLcdIntrSetScanLine2 (unsigned int line)
Sets the second scanline to interrupt.
Parameters
line the scanline to interrupt.
bool ithLcdIsEnabled (void)
Is LCD enabled or not.
Returns
Is LCD enabled or not.
bool ithLcdIsSyncFired (void)
Is LCD synchronize fire or not.
Returns
Is LCD synchronize fire or not.
void ithLcdLoadScriptFirst (const uint16_t * script, unsigned int count)
Loads the first part of LCD initial script.
Parameters
script the script array.
count the item count in the script array.
void ithLcdLoadScriptNext (void)
Runs the next part of LCD initial script.
void ithLcdReset (void)
Resets LCD module.
void ithLcdSetBaseAddrA (uint32_t addr)
Sets LCD base address A.
Parameters
addr the address to set.
void ithLcdSetBaseAddrB (uint32_t addr)
Sets LCD base address A.
Parameters
addr the address to set.
void ithLcdSetBaseAddrC (uint32_t addr)
Sets LCD base address C.
Parameters
addr the address to set.
void ithLcdSetHeight (uint32_t height)
Sets current LCD height.
Parameters
width the LCD height.
void ithLcdSetPitch (uint32_t pitch)
Sets current LCD pitch.
Parameters
width the LCD pitch.
void ithLcdSetWidth (uint32_t width)
Sets current LCD width.
Parameters
width the LCD width.
void ithLcdSwFlip (unsigned int index)
Software flip the LCD.
Parameters
index the index to flip. 0 is A, 1 is B, 2 is C.
void ithLcdSyncFire (void)
Synchronize fire LCD.