ITE SoC SDK: Upgrade
Upgrade
ITE DoorBell Indoor Modules
Enumerations
enum QuitValue {
QUIT_NONE, QUIT_DEFAULT, QUIT_RESET_FACTORY, QUIT_RESET_TEMP_DRIVE,
QUIT_UPGRADE_FIRMWARE, QUIT_UPGRADE_RESOURCE, QUIT_UPGRADE_ADDRESSBOOK, QUIT_UPGRADE_CARDLIST,
QUIT_UPGRADE_WEB, QUIT_RESET_NETWORK, QUIT_NONE, QUIT_DEFAULT,
QUIT_RESET_FACTORY, QUIT_RESET_TEMP_DRIVE, QUIT_UPGRADE_FIRMWARE, QUIT_UPGRADE_RESOURCE,
QUIT_UPGRADE_ADDRESSBOOK, QUIT_UPGRADE_CARDLIST, QUIT_UPGRADE_WEB, QUIT_RESET_NETWORK
}
Quit value definition.
Functions
int UpgradeInit (void)
Initializes upgrade module.
void UpgradeSetFileCrc (char *filepath)
Sets the CRC value of the specified file path.
char * UpgradeGetDeviceInfo (int *size)
Gets the XML string of the device information.
void UpgradeSetUrl (char *url)
Sets the URL to upgrade.
void UpgradeSetStream (void *stream)
Sets the stream to upgrade.
int UpgradeProcess (int code)
Processes the upgrade procedure by QuitValue.
bool UpgradeIsReady (void)
Is upgrading ready or not.
bool UpgradeIsFinished (void)
Is upgrading finished or not.
int UpgradeGetResult (void)
Gets the upgrading result.
char * UpgradeGetSDPath (void)
Gets the SD drive path.
Detailed Description
Enumeration Type Documentation
enum QuitValue
Quit value definition.
Enumerator
QUIT_NONE
Do not quit.
QUIT_DEFAULT
Quit for nothing.
QUIT_RESET_FACTORY
Quit to reset to factory setting.
QUIT_RESET_TEMP_DRIVE
Quit to reset temp drive.
QUIT_UPGRADE_FIRMWARE
Quit to upgrade firmware.
QUIT_UPGRADE_RESOURCE
Quit to upgrade resource.
QUIT_UPGRADE_ADDRESSBOOK
Quit to upgrade address book.
QUIT_UPGRADE_CARDLIST
Quit to upgrade card list.
QUIT_UPGRADE_WEB
Quit to wait web upgrading.
QUIT_RESET_NETWORK
Quit to reset network.
QUIT_NONE
Do not quit.
QUIT_DEFAULT
Quit for nothing.
QUIT_RESET_FACTORY
Quit to reset to factory setting.
QUIT_RESET_TEMP_DRIVE
Quit to reset temp drive.
QUIT_UPGRADE_FIRMWARE
Quit to upgrade firmware.
QUIT_UPGRADE_RESOURCE
Quit to upgrade resource.
QUIT_UPGRADE_ADDRESSBOOK
Quit to upgrade address book.
QUIT_UPGRADE_CARDLIST
Quit to upgrade card list.
QUIT_UPGRADE_WEB
Quit to wait web upgrading.
QUIT_RESET_NETWORK
Quit to reset network.
Definition at line 2021 of file doorbell_indoor/doorbell.h.
Function Documentation
char* UpgradeGetDeviceInfo (int * size)
Gets the XML string of the device information.
Parameters
size The pointer to retrieve the string size.
Returns
The XML string. Remember to free it after used to avoid memory leak.
Definition at line 397 of file doorbell_indoor/upgrade.c.
Referenced by ahc_echo(), and create_response().
int UpgradeGetResult (void)
Gets the upgrading result.
Returns
0 for success, failed otherwise.
Definition at line 624 of file doorbell_indoor/upgrade.c.
Referenced by ahc_echo(), and create_response().
char* UpgradeGetSDPath (void)
Gets the SD drive path.
Returns
the SD drive path. NULL for SD not exist.
Definition at line 629 of file doorbell_indoor/upgrade.c.
References ITPDriveStatus::avail, ITPDriveStatus::disk, i, ITP_DEVICE_DRIVE, ITP_DISK_NAND, ITP_DISK_SD0, ITP_DISK_SD1, ITP_IOCTL_GET_TABLE, ITP_MAX_DRIVE, and ITPDriveStatus::name.
Referenced by CaptureGetPath(), UpgradeResetTempDrive(), and VideoMemoGetPath().
int UpgradeInit (void)
Initializes upgrade module.
Returns
0 for initializing success, non-zero for initializing failed and the value will be the QuitValue.
Definition at line 31 of file doorbell_indoor/upgrade.c.
Referenced by SDL_main().
bool UpgradeIsFinished (void)
Is upgrading finished or not.
Returns
true for finished; otherwise not finish yet.
Definition at line 619 of file doorbell_indoor/upgrade.c.
Referenced by ahc_echo(), CheckQuitValue(), create_response(), and UpgradeOnTimer().
bool UpgradeIsReady (void)
Is upgrading ready or not.
Returns
true for ready; otherwise not ready yet.
Definition at line 614 of file doorbell_indoor/upgrade.c.
References upgradeIsReady.
Referenced by iterate_post().
int UpgradeProcess (int code)
Processes the upgrade procedure by QuitValue.
Parameters
code The QuitValue.
Returns
0 for process success; otherwise failed.
Definition at line 543 of file doorbell_indoor/upgrade.c.
Referenced by CheckQuitValue(), SDL_main(), and UpgradeOnEnter().
void UpgradeSetFileCrc (char * filepath)
Sets the CRC value of the specified file path.
Parameters
filepath The file path to update the CRC value.
Definition at line 386 of file doorbell_indoor/upgrade.c.
Referenced by ConfigSaveTask(), and ConfigUpdateCrc().
void UpgradeSetStream (void * stream)
Sets the stream to upgrade.
Parameters
stream The stream to upgrade.
Definition at line 505 of file doorbell_indoor/upgrade.c.
Referenced by ahc_echo(), and create_response().
void UpgradeSetUrl (char * url)
Sets the URL to upgrade.
Parameters
url The url to download and upgrade.
Definition at line 494 of file doorbell_indoor/upgrade.c.
Referenced by ahc_echo(), create_response(), and SettingEngineerMiscUpgradeButtonOnPress().