ITE SoC SDK: Event
Event
ITE DoorBell Indoor Modules
Enumerations
enum EventCalloutAction {
EVENT_CALLOUT_START, EVENT_CALLOUT_END, EVENT_CALLOUT_NOACK, EVENT_CALLOUT_START,
EVENT_CALLOUT_END, EVENT_CALLOUT_NOACK
}
Calling out actions of uploading event definitions.
enum EventOpenDoorMode {
EVENT_OPENDOOR_REMOTE, EVENT_OPENDOOR_PASSWORD, EVENT_OPENDOOR_CARD, EVENT_OPENDOOR_REMOTE,
EVENT_OPENDOOR_PASSWORD, EVENT_OPENDOOR_CARD
}
Opening door mode of uploading event definitions.
Functions
void EventInit (void)
Initializes event module.
void EventExit (void)
Exits event module.
void EventWriteCalloutLog (char *ip, EventCalloutAction action)
Writes calling out log to upload.
void EventWriteGuardLog (GuardSensor sensor, GuardStatus status, time_t timestamp)
Writes guard log to upload.
void EventWriteRegisterDevice (uint8_t hardwareAddress[])
Writes registering device event to upload.
void EventWriteOpenDoorLog (EventOpenDoorMode mode, DeviceInfo *info, bool verified, char *card)
Writes opening door event to upload.
void EventWriteSmsLog (char *ip)
Writes SMS event to upload.
Detailed Description
Enumeration Type Documentation
enum EventCalloutAction
Calling out actions of uploading event definitions.
Enumerator
EVENT_CALLOUT_START
Calling out starting.
EVENT_CALLOUT_END
Calling out ended.
EVENT_CALLOUT_NOACK
No response of calling out.
EVENT_CALLOUT_START
Calling out starting.
EVENT_CALLOUT_END
Calling out ended.
EVENT_CALLOUT_NOACK
No response of calling out.
Definition at line 1133 of file doorbell_indoor/doorbell.h.
enum EventOpenDoorMode
Opening door mode of uploading event definitions.
Enumerator
EVENT_OPENDOOR_REMOTE
Opening door by remote device.
EVENT_OPENDOOR_PASSWORD
Opening door by password.
EVENT_OPENDOOR_CARD
Opening door by card.
EVENT_OPENDOOR_REMOTE
Opening door by remote device.
EVENT_OPENDOOR_PASSWORD
Opening door by password.
EVENT_OPENDOOR_CARD
Opening door by card.
Definition at line 1143 of file doorbell_indoor/doorbell.h.
Function Documentation
void EventExit (void)
Exits event module.
Definition at line 180 of file doorbell_indoor/event.c.
Referenced by SDL_main().
void EventInit (void)
Initializes event module.
Definition at line 161 of file doorbell_indoor/event.c.
Referenced by SDL_main().
void EventWriteCalloutLog (char * ip, EventCalloutAction action)
Writes calling out log to upload.
Parameters
ip The IP address of target to call out.
action The action occured.
Definition at line 185 of file doorbell_indoor/event.c.
Referenced by CallConnected(), CallEnd(), CallError(), SceneHangUp(), and SceneRun().
void EventWriteGuardLog (GuardSensor sensor, GuardStatus status, time_t timestamp)
Writes guard log to upload.
Parameters
sensor The trigged sensor.
status The guard status.
timestamp The trigged time-stamp.
Definition at line 267 of file doorbell_indoor/event.c.
Referenced by GuardCheck(), GuardDisableSensor(), GuardEnableSensor(), and SceneRun().
void EventWriteOpenDoorLog (EventOpenDoorMode mode, DeviceInfo * info, bool verified, char * card)
Writes opening door event to upload.
Parameters
mode The mode of open door.
info The device information. Can be NULL.
verified Success to open door or not.
card Card number if opening door by card. Can be NULL.
Definition at line 442 of file doorbell_indoor/event.c.
References DeviceInfo::area, DeviceInfo::building, evDoc, EVENT_OPENDOOR_CARD, EVENT_OPENDOOR_PASSWORD, EVENT_OPENDOOR_REMOTE, evItemCount, evMutex, evQuit, DeviceInfo::ext, DeviceInfo::floor, MAX_EVENT_COUNT, DeviceInfo::room, theDeviceInfo, DeviceInfo::type, and DeviceInfo::unit.
Referenced by ahc_echo(), and CardListCheckTask().
void EventWriteRegisterDevice (uint8_t hardwareAddress[])
Writes registering device event to upload.
Parameters
hardwareAddress The MAC address of this device to upload.
Definition at line 382 of file doorbell_indoor/event.c.
Referenced by ResetEthernet().
void EventWriteSmsLog (char * ip)
Writes SMS event to upload.
Parameters
ip The IP address of target which need to send ths SMS message.
Definition at line 532 of file doorbell_indoor/event.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, evDoc, evItemCount, evMutex, evQuit, DeviceInfo::ext, DeviceInfo::floor, MAX_EVENT_COUNT, DeviceInfo::room, theDeviceInfo, DeviceInfo::type, and DeviceInfo::unit.
Referenced by SceneCallOnDoNotDisturb().