ITE SoC SDK: USB
USB
ITE Hardware Library
Enumerations
enum ITHUsbModule { ITH_USB0 = ITH_USB0_BASE, ITH_USB1 = ITH_USB1_BASE }
USB module definition.
enum ITHUsbInterface { ITH_USB_WRAP = 0, ITH_USB_AMBA = 1 }
USB AHB master interface type.
Functions
void ithUsbSuspend (ITHUsbModule usb)
Enters suspend mode on specified USB module.
void ithUsbResume (ITHUsbModule usb)
Resumes from suspend mode on specified USB module.
void ithUsbEnableClock (void)
Enables the clock of USB module.
void ithUsbDisableClock (void)
Disables the clock of USB module.
void ithUsbReset (void)
Reset the USB module.
void ithUsbInterfaceSel (ITHUsbInterface intf)
USB AHB master interface select.
void ithUsbPhyPowerOn (ITHUsbModule usb)
USB PHY power on.
static void ithUsbPhyEnableClock (ITHUsbModule usb)
Enables the clock of USB's PHY module.
static void ithUsbPhyDisableClock (ITHUsbModule usb)
Disables the clock of USB's PHY module.
Detailed Description
Enumeration Type Documentation
enum ITHUsbInterface
USB AHB master interface type.
Enumerator
ITH_USB_WRAP
Select USBWrap.
ITH_USB_AMBA
Select AMBA.
Definition at line 1465 of file ith.h.
enum ITHUsbModule
USB module definition.
Enumerator
ITH_USB0
USB #0.
ITH_USB1
USB #1.
Definition at line 1427 of file ith.h.
Function Documentation
void ithUsbDisableClock (void)
Disables the clock of USB module.
void ithUsbEnableClock (void)
Enables the clock of USB module.
void ithUsbInterfaceSel (ITHUsbInterface intf)
USB AHB master interface select.
static void ithUsbPhyDisableClock (ITHUsbModule usb) inline static
Disables the clock of USB's PHY module.
Definition at line 1499 of file ith.h.
References ITH_USB0, ITH_USB0_PHY_CTRL_REG, ITH_USB1, ITH_USB1_PHY_CTRL_REG, ithWriteRegMaskA(), and ithWriteRegMaskH().
static void ithUsbPhyEnableClock (ITHUsbModule usb) inline static
Enables the clock of USB's PHY module.
Definition at line 1484 of file ith.h.
References ITH_USB0, ITH_USB0_PHY_CTRL_REG, ITH_USB1, ITH_USB1_PHY_CTRL_REG, ithWriteRegMaskA(), and ithWriteRegMaskH().
void ithUsbPhyPowerOn (ITHUsbModule usb)
USB PHY power on.
void ithUsbReset (void)
Reset the USB module.
void ithUsbResume (ITHUsbModule usb)
Resumes from suspend mode on specified USB module.
Parameters
usb The USB module to resume.
void ithUsbSuspend (ITHUsbModule usb)
Enters suspend mode on specified USB module.
Parameters
usb The USB module to suspend.