ITE SoC SDK: TextBox
TextBox
ITE UI Library » Widgets
Data Structures
struct ITUTextBox
Text box widget definition.
Macros
#define ITU_TEXTBOX_PASSWORD 0x1
This is a password text box.
#define ITU_TEXTBOX_CURSOR 0x2
Shows cursor on text box.
#define ITU_TEXTBOX_UPPER 0x4
Auto convert input character to to upper character.
#define ITU_TEXTBOX_LOWER 0x8
Auto convert input character to to lower character.
#define ITU_TEXTBOX_MULTILINE 0x10
This is a multi-line text box.
#define ITU_TEXTBOX_WORDWRAP 0x20
Word wrap on a multi-line text box.
Functions
void ituTextBoxInit (ITUTextBox *textbox)
Initializes the text box widget.
void ituTextBoxLoad (ITUTextBox *textbox, uint32_t base)
Loads the text box widget.
bool ituTextBoxClone (ITUWidget *widget, ITUWidget **cloned)
Clones the text box widget.
bool ituTextBoxUpdate (ITUWidget *widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the text box widget by specified event.
void ituTextBoxDraw (ITUWidget *widget, ITUSurface *dest, int x, int y, uint8_t alpha)
Draws the text box widget to the specified surface.
void ituTextBoxOnAction (ITUWidget *widget, ITUActionType action, char *param)
Do the specified action.
void ituTextBoxSetString (ITUTextBox *textbox, char *string)
Sets string of the text box widget.
void ituTextBoxInput (ITUTextBox *textbox, char *input)
Inputs characters to the text box.
void ituTextBoxBack (ITUTextBox *textbox)
Backs a character of the text box.
char * ituTextBoxGetString (ITUTextBox *textbox)
Gets string of the text box widget.
Detailed Description
Macro Definition Documentation
#define ITU_TEXTBOX_CURSOR 0x2
Shows cursor on text box.
Definition at line 2676 of file itu.h.
#define ITU_TEXTBOX_LOWER 0x8
Auto convert input character to to lower character.
Definition at line 2678 of file itu.h.
#define ITU_TEXTBOX_MULTILINE 0x10
This is a multi-line text box.
Definition at line 2679 of file itu.h.
#define ITU_TEXTBOX_PASSWORD 0x1
This is a password text box.
Definition at line 2675 of file itu.h.
#define ITU_TEXTBOX_UPPER 0x4
Auto convert input character to to upper character.
Definition at line 2677 of file itu.h.
#define ITU_TEXTBOX_WORDWRAP 0x20
Word wrap on a multi-line text box.
Definition at line 2680 of file itu.h.
Function Documentation
void ituTextBoxBack (ITUTextBox * textbox)
Backs a character of the text box.
Parameters
textbox The text box widget to back.
Referenced by GuardPasswordConfirmDeleteButtonOnPress(), GuardPasswordNewDeleteButtonOnPress(), GuardPasswordOldDeleteButtonOnPress(), PhoneBackButtonOnPress(), PhoneContactsKeyboardBackButtonOnPress(), SettingOutdoorMiscCallingTimeDeleteButtonOnPress(), SettingOutdoorMiscDialTimeDeleteButtonOnPress(), and SettingOutdoorMiscVoiceMemoTimeDeleteButtonOnPress().
bool ituTextBoxClone (ITUWidget * widget, ITUWidget ** cloned)
Clones the text box widget.
Parameters
widget The text box widget to clone.
cloned Retrieved cloned text box widget.
Returns
true if clone is success, false otherwise.
void ituTextBoxDraw (ITUWidget * widget, ITUSurface * dest, int x, int y, uint8_t alpha)
Draws the text box widget to the specified surface.
Parameters
widget The text box widget to draw.
dest The surface to draw to.
x The x coordinate of destination surface, in pixels.
y The y coordinate of destination surface, in pixels.
alpha the alpha value to do the constant alphablending to the surface.
char* ituTextBoxGetString (ITUTextBox * textbox)
Gets string of the text box widget.
Parameters
textbox Pointer referring to the text box widget.
Returns
The string.
Referenced by GuardPasswordSaveButtonOnPress(), PhoneContactsAddConfirmButtonOnPress(), PhoneContactsModifyConfirmButtonOnPress(), SettingEngineerMiscTerminalConfirmButtonOnPress(), SettingEngineerMiscTerminalNumberButtonOnPress(), SettingOutdoorMiscSaveButtonOnPress(), SettingPhoneDisturbSaveButtonOnPress(), SettingPhoneDisturbTimeConfirmButtonOnPress(), SettingPhoneDisturbTimeDownButtonOnPress(), and SettingPhoneDisturbTimeUpButtonOnPress().
void ituTextBoxInit (ITUTextBox * textbox)
Initializes the text box widget.
Parameters
textbox The text box widget to initialize.
void ituTextBoxInput (ITUTextBox * textbox, char * input)
Inputs characters to the text box.
Parameters
textbox The text box widget to input.
input The characters to input.
Referenced by GuardPasswordNumberButtonOnPress(), PhoneContactsKeyboardChsCharButtonOnPress(), PhoneContactsKeypadNumberButtonOnPress(), PhoneNumberButtonOnPress(), SettingEngineerMiscTerminalNumberButtonOnPress(), SettingEngineerMiscTwiceNumberButtonOnPress(), SettingEngineerNetworkIPNumberButtonOnPress(), SettingOutdoorMiscNumberButtonOnPress(), and TimeNumberButtonOnPress().
void ituTextBoxLoad (ITUTextBox * textbox, uint32_t base)
Loads the text box widget.
This is called by scene manager.
Parameters
textbox The text box widget to load.
base The address in the scene file buffer.
void ituTextBoxOnAction (ITUWidget * widget, ITUActionType action, char * param)
Do the specified action.
This is triggered by other widget's event.
Parameters
widget The text box widget to do the action.
action The action to do.
param The parameter of action.
void ituTextBoxSetString (ITUTextBox * textbox, char * string)
Sets string of the text box widget.
Parameters
textbox Pointer referring to the text box widget.
string The string to set.
Referenced by GuardPasswordClearButtonOnPress(), GuardPasswordOnEnter(), GuardUserPasswordOnEnter(), PhoneContactsAddShow(), PhoneContactsKeyboardBackButtonOnPress(), PhoneContactsKeyboardChsCharButtonOnPress(), PhoneContactsKeyboardShow(), PhoneContactsKeypadShow(), PhoneContactsModifyShow(), PhoneDialResidentOnEnter(), SettingDisplayScreensaverTimeButtonOnPress(), SettingEngineerMiscTerminalBackButtonOnPress(), SettingEngineerMiscTerminalClearButtonOnPress(), SettingEngineerMiscTerminalOnEnter(), SettingEngineerMiscTwiceOnEnter(), SettingEngineerNetworkDnsCallback(), SettingEngineerNetworkGatewayCallback(), SettingEngineerNetworkIPCallback(), SettingEngineerNetworkIPClearButtonOnPress(), SettingEngineerNetworkIPShow(), SettingEngineerNetworkMacCallback(), SettingEngineerNetworkMacShow(), SettingEngineerNetworkNetmaskCallback(), SettingEngineerNetworkOnEnter(), SettingEngineerNetworkWiFiPasswordShow(), SettingEngineerOnEnter(), SettingEngineerPasswordConfirmButtonOnPress(), SettingOutdoorMiscClearButtonOnPress(), SettingOutdoorMiscOnEnter(), SettingPhoneDisturbOnEnter(), SettingPhoneDisturbTimeCancelButtonOnPress(), SettingPhoneDisturbTimeDownButtonOnPress(), SettingPhoneDisturbTimeUpButtonOnPress(), and TimeOnEnter().
bool ituTextBoxUpdate (ITUWidget * widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the text box widget by specified event.
Parameters
widget The text box widget to update.
ev The event to notify.
arg1 The event related argument #1.
arg2 The event related argument #2.
arg3 The event related argument #3.
Returns
true if the text box widget is modified and need to be redraw, false if no need to be redraw.