ITE SoC SDK: House
House
ITE DoorBell Indoor Modules
Data Structures
struct HouseInfo
House device information definition.
struct HouseAirConditionerSetting
Air conditioner setting definition.
struct HouseEntry
House entry definition.
Macros
#define HOUSE_MAX_AIRCONDITIONER_COUNT 8
Maximum count of air conditioner.
#define HOUSE_MAX_CURTAIN_COUNT 8
Maximum count of curtain.
#define HOUSE_MAX_LIGHT_COUNT 8
Maximum count of light.
#define HOUSE_MAX_PLUG_COUNT 8
Maximum count of plug.
#define HOUSE_MAX_TV_COUNT 8
Maximum count of TV.
Typedefs
typedef void(* HouseInitFunc)(void)
The function definition of initializing house module.
typedef void(* HouseExitFunc)(void)
The function definition of exiting house module.
typedef int(* HouseGetInfoArrayFunc)(HouseInfo infoArray[], int count)
The function definition of getting information array of house module.
typedef int(* HouseExecActionFunc)(int index, HouseAction action, void *data)
The function definition of executing action command on house module.
Enumerations
enum HouseMode { HOUSE_NONE, HOUSE_INDOOR, HOUSE_OUTDOOR, HOUSE_SLEEP }
House mode definition.
enum HouseDevice {
HOUSE_AIRCONDITIONER, HOUSE_CURTAIN, HOUSE_LIGHT, HOUSE_PLUG,
HOUSE_TV, HOUSE_DEVICE_COUNT
}
House device definition.
enum HouseAction {
HOUSE_OPEN, HOUSE_CLOSE, HOUSE_STOP, HOUSE_GET,
HOUSE_SET
}
Action commands for house devices.
enum HouseStatus { HOUSE_OFF, HOUSE_ON }
Status definition of house device.
enum HouseAirConditionerMode { HOUSE_AC_OFF, HOUSE_AC_COOL, HOUSE_AC_WARM, HOUSE_AC_FAN }
Air conditioner mode definition.
Functions
void HouseInit (void)
Initializes house module.
void HouseExit (void)
Exits house module.
void HouseSetMode (HouseMode mode)
Sets house mode.
int HouseGetInfoArray (HouseDevice dev, HouseInfo infoArray[], int count)
Gets array of HouseInfo by house device type.
int HouseExecAction (HouseDevice dev, int index, HouseAction action, void *data)
Executes action command on specified house module.
Detailed Description
Macro Definition Documentation
#define HOUSE_MAX_AIRCONDITIONER_COUNT 8
Maximum count of air conditioner.
Definition at line 648 of file doorbell_indoor/doorbell.h.
Referenced by HouseAirConditionerNameListBoxOnLoad(), and HouseAirConditionerStatusListBoxOnLoad().
#define HOUSE_MAX_CURTAIN_COUNT 8
Maximum count of curtain.
Definition at line 649 of file doorbell_indoor/doorbell.h.
Referenced by HouseCurtainNameListBoxOnLoad(), and HouseCurtainStatusListBoxOnLoad().
#define HOUSE_MAX_LIGHT_COUNT 8
Maximum count of light.
Definition at line 650 of file doorbell_indoor/doorbell.h.
Referenced by HouseLightNameListBoxOnLoad(), HouseLightStatusListBoxOnLoad(), and HouseSetMode().
#define HOUSE_MAX_PLUG_COUNT 8
Maximum count of plug.
Definition at line 651 of file doorbell_indoor/doorbell.h.
Referenced by HousePlugNameListBoxOnLoad(), and HousePlugStatusListBoxOnLoad().
#define HOUSE_MAX_TV_COUNT 8
Maximum count of TV.
Definition at line 652 of file doorbell_indoor/doorbell.h.
Referenced by HouseTVNameListBoxOnLoad(), and HouseTVStatusListBoxOnLoad().
Typedef Documentation
typedef int(* HouseExecActionFunc)(int index, HouseAction action, void *data)
The function definition of executing action command on house module.
Parameters
index The index of module instance to execute.
action The action command to execute.
data Additional data. NULL if no data.
Returns
The result value depends on the action command.
Definition at line 757 of file doorbell_indoor/doorbell.h.
typedef void(* HouseExitFunc)(void)
The function definition of exiting house module.
Definition at line 739 of file doorbell_indoor/doorbell.h.
typedef int(* HouseGetInfoArrayFunc)(HouseInfo infoArray[], int count)
The function definition of getting information array of house module.
Parameters
infoArray The pointer to retrieve the array of HouseInfo of module instance.
count Maximum count of HouseInfo in array.
Definition at line 747 of file doorbell_indoor/doorbell.h.
typedef void(* HouseInitFunc)(void)
The function definition of initializing house module.
Definition at line 734 of file doorbell_indoor/doorbell.h.
Enumeration Type Documentation
enum HouseAction
Action commands for house devices.
Enumerator
HOUSE_OPEN
Open/Turn on command.
HOUSE_CLOSE
Close/Turn off command.
HOUSE_STOP
Stop command.
HOUSE_GET
Get information command.
HOUSE_SET
Set information command.
Definition at line 682 of file doorbell_indoor/doorbell.h.
enum HouseAirConditionerMode
Air conditioner mode definition.
Enumerator
HOUSE_AC_OFF
Off mode.
HOUSE_AC_COOL
Cool mode.
HOUSE_AC_WARM
Warm mode.
HOUSE_AC_FAN
Fan mode.
Definition at line 713 of file doorbell_indoor/doorbell.h.
enum HouseDevice
House device definition.
Enumerator
HOUSE_AIRCONDITIONER
Air Conditioner.
HOUSE_CURTAIN
Curtain.
HOUSE_LIGHT
Light.
HOUSE_PLUG
Plug.
HOUSE_TV
TV.
HOUSE_DEVICE_COUNT
Total type count of house devices.
Definition at line 668 of file doorbell_indoor/doorbell.h.
enum HouseMode
House mode definition.
Enumerator
HOUSE_NONE
Non-setting mode.
HOUSE_INDOOR
Indoor mode.
HOUSE_OUTDOOR
Outdoor mode.
HOUSE_SLEEP
Sleep mode.
Definition at line 657 of file doorbell_indoor/doorbell.h.
enum HouseStatus
Status definition of house device.
Enumerator
HOUSE_OFF
The device is off/closed.
HOUSE_ON
The device is on/opened.
Definition at line 694 of file doorbell_indoor/doorbell.h.
Function Documentation
int HouseExecAction (HouseDevice dev, int index, HouseAction action, void * data)
Executes action command on specified house module.
Parameters
dev The house device type.
index The index of module instance to execute.
action The action command to execute.
data Additional data. NULL if no data.
Returns
The result value depends on the action command.
Definition at line 91 of file house.c.
References HouseEntry::ExecAction.
Referenced by HouseAirConditionerOffButtonOnPress(), HouseAirConditionerOnButtonOnPress(), HouseCurtainOffButtonOnPress(), HouseCurtainOnButtonOnPress(), HouseCurtainStopButtonOnPress(), HouseLightOffButtonOnPress(), HouseLightOnButtonOnPress(), HousePlugOffButtonOnPress(), HousePlugOnButtonOnPress(), HouseSetMode(), HouseTVOffButtonOnPress(), and HouseTVOnButtonOnPress().
void HouseExit (void)
Exits house module.
Definition at line 34 of file house.c.
References HouseEntry::Exit, HOUSE_DEVICE_COUNT, and i.
Referenced by SDL_main().
int HouseGetInfoArray (HouseDevice dev, HouseInfo infoArray[], int count)
Gets array of HouseInfo by house device type.
Parameters
dev The house device type.
infoArray The array of HouseInfo to fill in.
count Maximum count of HouseInfo in array.
Returns
The actual count of filled HouseInfo in array.
Definition at line 86 of file house.c.
References HouseEntry::GetInfoArray.
Referenced by HouseAirConditionerNameListBoxOnLoad(), HouseAirConditionerStatusListBoxOnLoad(), HouseCurtainNameListBoxOnLoad(), HouseCurtainStatusListBoxOnLoad(), HouseLightNameListBoxOnLoad(), HouseLightStatusListBoxOnLoad(), HouseModeIndoorButtonOnPress(), HouseModeOutdoorButtonOnPress(), HouseModeSleepButtonOnPress(), HousePlugNameListBoxOnLoad(), HousePlugStatusListBoxOnLoad(), HouseTVNameListBoxOnLoad(), and HouseTVStatusListBoxOnLoad().
void HouseInit (void)
Initializes house module.
Definition at line 23 of file house.c.
References HOUSE_DEVICE_COUNT, Config::house_mode, HouseSetMode(), i, HouseEntry::Init, and theConfig.
Referenced by SDL_main().
void HouseSetMode (HouseMode mode)
Sets house mode.
Parameters
mode The mode to set.
Definition at line 44 of file house.c.
References HOUSE_CLOSE, HOUSE_INDOOR, Config::house_indoor_lights, HOUSE_LIGHT, HOUSE_MAX_LIGHT_COUNT, Config::house_mode, HOUSE_OPEN, HOUSE_OUTDOOR, Config::house_outdoor_lights, HOUSE_SLEEP, Config::house_sleep_lights, HouseExecAction(), i, and theConfig.
Referenced by HouseInit(), HouseModeIndoorRadioBoxOnPress(), HouseModeOutdoorRadioBoxOnPress(), and HouseModeSleepRadioBoxOnPress().