ITE SoC SDK: RTC
RTC
Enumerations
enum ITHRtcCtrl {
ITH_RTC_EN = 0, ITH_RTC_INTR_SEC = 1, ITH_RTC_INTR_MIN = 2, ITH_RTC_INTR_HOUR = 3,
ITH_RTC_INTR_DAY = 4, ITH_RTC_ALARM_INTR = 5, ITH_RTC_DAY_ALARM_INTR = 6, ITH_RTC_WEEK_ALARM_INTR = 7,
ITH_RTC_COUNTER_LOAD = 8, ITH_RTC_PWREN_ALARM_SEL = 15, ITH_RTC_PWREN_CTRL1 = 16, ITH_RTC_SW_POWEROFF = 17,
ITH_RTC_PWREN_IO_DIR = 21, ITH_RTC_PWREN_GPIO = 24, ITH_RTC_RESET = 31
}
RTC control definition.
enum ITHRtcIntr {
ITH_RTC_SEC = 0, ITH_RTC_MIN = 1, ITH_RTC_HOUR = 2, ITH_RTC_DAY = 3,
ITH_RTC_ALARM = 4, ITH_RTC_MAX_INTR
}
RTC interrupt definition.
enum ITHRtcPowerEnableIoSelection { ITH_RTC_PWREN = 0, ITH_RTC_VCC_OK = 1, ITH_RTC_INTR = 2, ITH_RTC_GPIO = 3 }
RTC power enable I/O selection definition.
enum ITHRtcClockSource { ITH_RTC_DIV_SRC_INNER_12MHZ = 0, ITH_RTC_DIV_SRC_EXT_32KHZ = 1 }
RTC power enable I/O selection definition.
Functions
static void ithRtcCtrlEnable (ITHRtcCtrl ctrl)
Enables specified RTC control.
static void ithRtcCtrlDisable (ITHRtcCtrl ctrl)
Disables specified RTC control.
static void ithRtcClearIntr (ITHRtcIntr intr)
Clears specified RTC interrupt.
static uint32_t ithRtcGetIntrState (void)
Gets the state of RTC interrupt.
static void ithRtcSetPowerEnableIoSelection (ITHRtcPowerEnableIoSelection sel)
Sets the RTC power enable I/O selection.
void ithRtcSetDivSrc (ITHRtcClockSource clkSrc)
Set RTC source.
void ithRtcInit (unsigned long extClk)
Initializes RTC module.
bool ithRtcEnable (void)
Enables RTC module.
unsigned long ithRtcGetTime (void)
Gets RTC time.
void ithRtcSetTime (unsigned long t)
Sets RTC time.
static uint8_t ithRtcGetState (void)
Gets RTC state.
static void ithRtcSetState (uint8_t state)
Sets RTC state.
Detailed Description
Enumeration Type Documentation
enum ITHRtcClockSource
RTC power enable I/O selection definition.
Enumerator
ITH_RTC_DIV_SRC_INNER_12MHZ
divider source is internal 12Mhz clock
ITH_RTC_DIV_SRC_EXT_32KHZ
divider source is external 32kHz clock
Definition at line 3256 of file ith.h.
enum ITHRtcCtrl
RTC control definition.
Enumerator
ITH_RTC_EN
RTC enable.
ITH_RTC_INTR_SEC
RTC auto alarm per second.
ITH_RTC_INTR_MIN
RTC auto alarm per minute.
ITH_RTC_INTR_HOUR
RTC auto alarm per hour.
ITH_RTC_INTR_DAY
RTC auto alarm per day.
ITH_RTC_ALARM_INTR
RTC alarm interrupt.
ITH_RTC_DAY_ALARM_INTR
RTC day alarm interrupt.
ITH_RTC_WEEK_ALARM_INTR
RTC week alarm interrupt.
ITH_RTC_COUNTER_LOAD
RTC counter load.
ITH_RTC_PWREN_ALARM_SEL
PWREN Alarm Type.
ITH_RTC_PWREN_CTRL1
PWREN Alarm Control.
ITH_RTC_SW_POWEROFF
Software power down (auto set zero)
ITH_RTC_PWREN_IO_DIR
PWREN pin driving strength.
ITH_RTC_PWREN_GPIO
PWREN GPIO Data.
ITH_RTC_RESET
Asynchronous reset.
Definition at line 3209 of file ith.h.
enum ITHRtcIntr
RTC interrupt definition.
Enumerator
ITH_RTC_SEC
Indicate that rtc_sec interrupt has occurred.
ITH_RTC_MIN
Indicate that rtc_min interrupt has occurred.
ITH_RTC_HOUR
Indicate that rtc_hour interrupt has occurred.
ITH_RTC_DAY
Indicate that rtc_day interrupt has occurred.
ITH_RTC_ALARM
Indicate that rtc_alarm interrupt has occurred.
ITH_RTC_MAX_INTR
Definition at line 3231 of file ith.h.
enum ITHRtcPowerEnableIoSelection
RTC power enable I/O selection definition.
Enumerator
ITH_RTC_PWREN
PWREN.
ITH_RTC_VCC_OK
VCC_OK.
ITH_RTC_INTR
RTC interrupt.
ITH_RTC_GPIO
GPIO.
Definition at line 3245 of file ith.h.
Function Documentation
static void ithRtcClearIntr (ITHRtcIntr intr) inline static
Clears specified RTC interrupt.
Parameters
intr the interrupt to clear.
Definition at line 3287 of file ith.h.
References ITH_RTC_BASE, ITH_RTC_INTRSTATE_REG, and ithClearRegBitA().
static void ithRtcCtrlDisable (ITHRtcCtrl ctrl) inline static
Disables specified RTC control.
Parameters
ctrl the control to disable.
Definition at line 3277 of file ith.h.
References ITH_RTC_BASE, ITH_RTC_CR_REG, and ithClearRegBitA().
static void ithRtcCtrlEnable (ITHRtcCtrl ctrl) inline static
Enables specified RTC control.
Parameters
ctrl the control to enable.
Definition at line 3267 of file ith.h.
References ITH_RTC_BASE, ITH_RTC_CR_REG, and ithSetRegBitA().
bool ithRtcEnable (void)
Enables RTC module.
Returns
First booting or not.
static uint32_t ithRtcGetIntrState (void) inline static
Gets the state of RTC interrupt.
Returns
the state of RTC interrupt.
Definition at line 3297 of file ith.h.
References ITH_RTC_BASE, ITH_RTC_INTRSTATE_REG, and ithReadRegA().
static uint8_t ithRtcGetState (void) inline static
Gets RTC state.
Returns
the RTC state.
Definition at line 3352 of file ith.h.
References ITH_RTC_BASE, ITH_RTC_STATE_BIT, ITH_RTC_STATE_MASK, ITH_RTC_STATE_REG, and ithReadRegA().
unsigned long ithRtcGetTime (void)
Gets RTC time.
Returns
the RTC time.
void ithRtcInit (unsigned long extClk)
Initializes RTC module.
Parameters
extClk The frequency of external clock.
void ithRtcSetDivSrc (ITHRtcClockSource clkSrc)
Set RTC source.
Parameters
clkSrc The clock source.
static void ithRtcSetPowerEnableIoSelection (ITHRtcPowerEnableIoSelection sel) inline static
Sets the RTC power enable I/O selection.
Parameters
sel the RTC power enable I/O selection.
Definition at line 3307 of file ith.h.
References ITH_RTC_BASE, ITH_RTC_PWREN_IOSEL_BIT, ITH_RTC_PWREN_IOSEL_MASK, ITH_RTC_PWREN_IOSEL_REG, and ithWriteRegMaskA().
static void ithRtcSetState (uint8_t state) inline static
Sets RTC state.
Returns
the RTC state.
Definition at line 3362 of file ith.h.
References ITH_RTC_BASE, ITH_RTC_STATE_BIT, ITH_RTC_STATE_MASK, ITH_RTC_STATE_REG, and ithWriteRegMaskA().
void ithRtcSetTime (unsigned long t)
Sets RTC time.
Parameters
t the RTC time.