ITE SoC SDK: FreeType
FreeType
ITE UI Library
Macros
#define ITU_FT_STYLE_DEFAULT 0x0
Default style.
#define ITU_FT_STYLE_BOLD 0x1
Bold style.
Functions
int ituFtInit (void)
Initializes FreeType module.
void ituFtExit (void)
Exits FreeType module.
int ituFtLoadFont (int index, char *filename, ITUGlyphFormat format)
Loads font file to specified index.
void ituFtSetCurrentFont (int index)
Sets current font to use.
void ituFtSetFontSize (int width, int height)
Sets the size of current font.
void ituFtGetTextDimension (const char *text, int *width, int *height)
Gets the dimension of text on current font.
int ituFtDrawText (ITUSurface *surf, int x, int y, const char *text)
Draws text to the specified surface.
int ituFtGetCharWidth (const char *text, int *width)
Gets the width and size of specified character.
int ituFtDrawChar (ITUSurface *surf, int x, int y, const char *text)
Draws a character to the specified surface.
void ituFtResetCache (void)
Resets font cache to release memory resource.
bool ituFtIsCharValid (const char *text)
Is the character valid or not.
void ituFtSetFontStyle (unsigned int style)
Sets the style of current font.
void ituFtSetFontStyleValue (unsigned int style, int value)
Sets the style value of current font.
Detailed Description
Macro Definition Documentation
#define ITU_FT_STYLE_BOLD 0x1
Bold style.
Definition at line 729 of file itu.h.
#define ITU_FT_STYLE_DEFAULT 0x0
Default style.
Definition at line 728 of file itu.h.
Function Documentation
int ituFtDrawChar (ITUSurface * surf, int x, int y, const char * text)
Draws a character to the specified surface.
Parameters
surf the surface to draw to.
x the x coordinate of surface, in pixels.
y the y coordinate of surface, in pixels.
text the text to draw.
Returns
0 if success. non-zero value if failed.
int ituFtDrawText (ITUSurface * surf, int x, int y, const char * text)
Draws text to the specified surface.
Parameters
surf the surface to draw to.
x the x coordinate of surface, in pixels.
y the y coordinate of surface, in pixels.
text the text to draw.
Returns
0 if success. non-zero value if failed.
void ituFtExit (void)
Exits FreeType module.
Referenced by SceneExit().
int ituFtGetCharWidth (const char * text, int * width)
Gets the width and size of specified character.
Parameters
text the text of character.
width the width of character to get.
Returns
the size of character, in bytes.
void ituFtGetTextDimension (const char * text, int * width, int * height)
Gets the dimension of text on current font.
Parameters
text the text to get dimension.
width the pointer to retrieved width.
height the pointer to retrieved height.
int ituFtInit (void)
Initializes FreeType module.
Returns
0 if success. non-zero value if failed.
Examples:
test_itu/test_array.c, test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_helloworld.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, test_itu/test_stnlcd.c, and test_itu/test_trackbar.c.
Referenced by SceneInit().
bool ituFtIsCharValid (const char * text)
Is the character valid or not.
Parameters
text the text of character.
Returns
is the character valid or not.
int ituFtLoadFont (int index, char * filename, ITUGlyphFormat format)
Loads font file to specified index.
Parameters
index the index to load to. Must small than ITU_FREETYPE_MAX_FONTS.
filename the font file to load.
format the glyph format to convert to.
Returns
0 if success. non-zero value if failed.
Examples:
test_itu/test_array.c, test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_helloworld.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, test_itu/test_stnlcd.c, and test_itu/test_trackbar.c.
Referenced by SceneInit().
void ituFtResetCache (void)
Resets font cache to release memory resource.
void ituFtSetCurrentFont (int index)
Sets current font to use.
Parameters
index the index of loaded font to use.
void ituFtSetFontSize (int width, int height)
Sets the size of current font.
Parameters
width the font width.
height the font height.
void ituFtSetFontStyle (unsigned int style)
Sets the style of current font.
Parameters
style the font style.
void ituFtSetFontStyleValue (unsigned int style, int value)
Sets the style value of current font.
Parameters
style the font style to set.
value the style value.