ITE SoC SDK: ListBox
ListBox
ITE UI Library » Widgets
Data Structures
struct ITUListBoxTag
List box widget definition.
Macros
#define ituListBoxOnLoadPage(listbox, pageIndex) ((ITUListBox*)(listbox))->OnLoadPage((ITUListBox*)(listbox), (pageIndex))
Do loading page.
#define ituListBoxSetOnLoadPage(listbox, onLoadPage) (((ITUListBox*)(listbox))->OnLoadPage = (onLoadPage))
Sets OnLoadPage callback function of list box.
#define ituListBoxOnSelection(listbox, item, confirm) ((ITUListBox*)(listbox))->OnSelection((ITUListBox*)(listbox), (item), (confirm))
Do selection.
#define ituListBoxSetOnSelection(listbox, onSelection) (((ITUListBox*)(listbox))->OnSelection = (onSelection))
Sets OnSelection callback function of list box.
#define ituListBoxPrev(listbox) ituListBoxPrevImpl((ITUListBox*)(listbox))
#define ituListBoxNext(listbox) ituListBoxNextImpl((ITUListBox*)(listbox))
Typedefs
typedef struct ITUListBoxTag ITUListBox
List box widget definition.
Functions
void ituListBoxInit (ITUListBox *listbox, int width)
Initializes the list box widget.
void ituListBoxLoad (ITUListBox *listbox, uint32_t base)
Loads the list box widget.
bool ituListBoxUpdate (ITUWidget *widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the list box widget by specified event.
void ituListBoxDraw (ITUWidget *widget, ITUSurface *dest, int x, int y, uint8_t alpha)
Draws the list box widget to the specified surface.
void ituListBoxOnAction (ITUWidget *widget, ITUActionType action, char *param)
Do the specified action.
void ituListBoxSelect (ITUListBox *listbox, int index)
Selects the specified index of item of the list box widget.
void ituListBoxCheck (ITUListBox *listbox, int index)
Selects the specified index of item of the list box widget without executing actions.
void ituListBoxReload (ITUListBox *listbox)
Reloads the list box widget.
void ituListBoxGoto (ITUListBox *listbox, int index)
Gotos the specified index of page of the list box widget.
void ituListBoxPrevImpl (ITUListBox *listbox)
void ituListBoxNextImpl (ITUListBox *listbox)
ITUWidget * ituListBoxGetFocusItem (ITUListBox *listbox)
Gets the focus item of list box widget.
void ituListBoxSetItemRead (ITUListBox *listbox, ITUWidget *item, bool read)
Sets the specified item as read or not.
Detailed Description
Macro Definition Documentation
#define ituListBoxNext (listbox) ituListBoxNextImpl((ITUListBox*)(listbox))
Definition at line 3533 of file itu.h.
#define ituListBoxOnLoadPage (listbox, pageIndex) ((ITUListBox*)(listbox))->OnLoadPage((ITUListBox*)(listbox), (pageIndex))
Do loading page.
This is called when user goto previous/next page.
Parameters
listbox The list box widget to load page.
pageIndex The page index to load.
Returns
The actual count of loaded items.
Definition at line 3502 of file itu.h.
#define ituListBoxOnSelection (listbox, item, confirm) ((ITUListBox*)(listbox))->OnSelection((ITUListBox*)(listbox), (item), (confirm))
Do selection.
This is called when user select an item of the list.
Parameters
listbox The list box widget to select.
item The item to select.
confirm true if user press enter key or double-click the item, false for just select this item.
Definition at line 3519 of file itu.h.
#define ituListBoxPrev (listbox) ituListBoxPrevImpl((ITUListBox*)(listbox))
Definition at line 3530 of file itu.h.
#define ituListBoxSetOnLoadPage (listbox, onLoadPage) (((ITUListBox*)(listbox))->OnLoadPage = (onLoadPage))
Sets OnLoadPage callback function of list box.
Parameters
listbox Pointer referring to the list box.
onLoadPage The callback function to set.
Examples:
test_itu/test_listbox.c.
Definition at line 3510 of file itu.h.
#define ituListBoxSetOnSelection (listbox, onSelection) (((ITUListBox*)(listbox))->OnSelection = (onSelection))
Sets OnSelection callback function of list box.
Parameters
listbox Pointer referring to the list box.
onSelection The callback function to set.
Examples:
test_itu/test_listbox.c.
Definition at line 3527 of file itu.h.
Typedef Documentation
typedef struct ITUListBoxTag ITUListBox
List box widget definition.
This is a container of scroll text widgets to draw list of texts.
Function Documentation
void ituListBoxCheck (ITUListBox * listbox, int index)
Selects the specified index of item of the list box widget without executing actions.
Parameters
listbox The list box widget to select.
index The index of item to select.
void ituListBoxDraw (ITUWidget * widget, ITUSurface * dest, int x, int y, uint8_t alpha)
Draws the list box widget to the specified surface.
Parameters
widget The list box widget to draw.
dest The surface to draw to.
x The x coordinate of destination surface, in pixels.
y The y coordinate of destination surface, in pixels.
alpha the alpha value to do the constant alphablending to the surface.
ITUWidget* ituListBoxGetFocusItem (ITUListBox * listbox)
Gets the focus item of list box widget.
Parameters
listbox The list box widget.
Returns
the focus item. NULL if not focused item.
void ituListBoxGoto (ITUListBox * listbox, int index)
Gotos the specified index of page of the list box widget.
Parameters
listbox The list box widget to goto.
index The index of page to goto.
void ituListBoxInit (ITUListBox * listbox, int width)
Initializes the list box widget.
Parameters
listbox The list box widget to initialize.
width The width of the list box widget.
void ituListBoxLoad (ITUListBox * listbox, uint32_t base)
Loads the list box widget.
This is called by scene manager.
Parameters
listbox The list box widget to load.
base The address in the scene file buffer.
void ituListBoxNextImpl (ITUListBox * listbox)
void ituListBoxOnAction (ITUWidget * widget, ITUActionType action, char * param)
Do the specified action.
This is triggered by other widget's event.
Parameters
widget The list box widget to do the action.
action The action to do.
param The parameter of action.
void ituListBoxPrevImpl (ITUListBox * listbox)
void ituListBoxReload (ITUListBox * listbox)
Reloads the list box widget.
Parameters
listbox The list box widget to select.
Referenced by GuardLogReload(), MainVoiceMemoReload(), MessagePhotoReload(), MessageRecordDeleteConfirmOnPress(), MessageRecordOnEnter(), MessageServiceReload(), PhoneContactsReload(), PhoneLogMissedReload(), PhoneLogReceivedReload(), PhoneLogSentReload(), and SettingOutdoorMainOnEnter().
void ituListBoxSelect (ITUListBox * listbox, int index)
Selects the specified index of item of the list box widget.
Parameters
listbox The list box widget to select.
index The index of item to select.
Referenced by HouseModeStatusListBoxOnSelection(), and SettingOutdoorMainMessageListBoxOnSelection().
void ituListBoxSetItemRead (ITUListBox * listbox, ITUWidget * item, bool read)
Sets the specified item as read or not.
Parameters
listbox The list box widget to set.
item The item to set.
read Read or not.
bool ituListBoxUpdate (ITUWidget * widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the list box widget by specified event.
Parameters
widget The list box widget to update.
ev The event to notify.
arg1 The event related argument #1.
arg2 The event related argument #2.
arg3 The event related argument #3.
Returns
true if the list box widget is modified and need to be redraw, false if no need to be redraw.