ITE SoC SDK: UART
UART
Enumerations
enum ITHUartPort { ITH_UART0 = ITH_UART0_BASE, ITH_UART1 = ITH_UART1_BASE, ITH_UART2 = ITH_UART2_BASE, ITH_UART3 = ITH_UART3_BASE }
UART port definition.
enum ITHUartMode { ITH_UART_DEFAULT = 0x0, ITH_UART_SIR = 0x1, ITH_UART_FIR = 0x2, ITH_UART_TX = 0x3 }
UART mode definition.
enum ITHUartParity {
ITH_UART_NONE = 0, ITH_UART_ODD = 1, ITH_UART_EVEN = 2, ITH_UART_MARK = 3,
ITH_UART_SPACE = 4
}
UART parity definition.
enum ITHUartFifoDepth { ITH_UART_FIFO16 = 0x1, ITH_UART_FIFO32 = 0x2, ITH_UART_FIFO64 = 0x4, ITH_UART_FIFO128 = 0x8 }
UART FIFO depth definition.
enum ITHUartFifoCtrl { ITH_UART_FIFO_EN = 0, ITH_UART_DMA = 3 }
UART FIFO control definition.
enum ITHUartTriggerLevel { ITH_UART_TRGL0 = 0x0, ITH_UART_TRGL1 = 0x1, ITH_UART_TRGL2 = 0x2, ITH_UART_TRGL3 = 0x3 }
UART trigger level of the TX/RX FIFO interrupt.
enum ITHUartIntr { ITH_UART_RX_READY = 0, ITH_UART_TX_READY = 1, ITH_UART_RECV_STATUS = 2, ITH_UART_MODEM_STATUS = 3 }
UART interrupt definition.
Functions
void ithUartSetMode (ITHUartPort port, ITHUartMode mode, unsigned int txPin, unsigned int rxPin)
Sets UART mode.
void ithUartSetParity (ITHUartPort port, ITHUartParity parity, unsigned int stop, unsigned int len)
Only sets UART parity.
void ithUartSetBaudRate (ITHUartPort port, unsigned int baud)
Only sets UART baudrate.
void ithUartReset (ITHUartPort port, unsigned int baud, ITHUartParity parity, unsigned int stop, unsigned int len)
Resets UART.
void ithUartFifoCtrlEnable (ITHUartPort port, ITHUartFifoCtrl ctrl)
Enables specified FIFO controls.
void ithUartFifoCtrlDisable (ITHUartPort port, ITHUartFifoCtrl ctrl)
Disables specified FIFO controls.
void ithUartSetTxTriggerLevel (ITHUartPort port, ITHUartTriggerLevel level)
Sets UART TX interrupt trigger level.
void ithUartSetRxTriggerLevel (ITHUartPort port, ITHUartTriggerLevel level)
Sets UART RX interrupt trigger level.
static ITHUartFifoDepth ithUartGetFifoDepth (ITHUartPort port)
Whether RX is ready.
static bool ithUartIsRxReady (ITHUartPort port)
Whether RX is ready.
static char ithUartGetChar (ITHUartPort port)
Gets a character from UART RX.
static bool ithUartIsTxEmpty (ITHUartPort port)
Whether TX FIFO is empty.
static bool ithUartIsTxWIthFifoEmpty (ITHUartPort port)
static bool ithUartIsTxFull (ITHUartPort port)
Whether TX FIFO is full.
static void ithUartPutChar (ITHUartPort port, char c)
Puts character to UART TX.
static void ithUartEnableIntr (ITHUartPort port, ITHUartIntr intr)
Enables UART interrupt.
static void ithUartDisableIntr (ITHUartPort port, ITHUartIntr intr)
Disables UART interrupt.
static uint32_t ithUartClearIntr (ITHUartPort port)
Clears UART interrupt.
static void ithUartEnableDmaMode2 (ITHUartPort port)
Enables UART DMA MODE2.
static void ithUartDisableDmaMode2 (ITHUartPort port)
Disables UART DMA MODE2.
Detailed Description
Enumeration Type Documentation
enum ITHUartFifoCtrl
UART FIFO control definition.
Enumerator
ITH_UART_FIFO_EN
Set this bit to logic 1 enables both transmit and receive FIFOs (And Status FIFO)
ITH_UART_DMA
This bit selects the UART DMA mode.
Definition at line 3421 of file ith.h.
enum ITHUartFifoDepth
UART FIFO depth definition.
Enumerator
ITH_UART_FIFO16
TX/RX FIFOs are 16-byte deep.
ITH_UART_FIFO32
TX/RX FIFOs are 32-byte deep.
ITH_UART_FIFO64
TX/RX FIFOs are 64-byte deep.
ITH_UART_FIFO128
TX/RX FIFOs are 128-byte deep.
Definition at line 3410 of file ith.h.
enum ITHUartIntr
UART interrupt definition.
Enumerator
ITH_UART_RX_READY
Receiver Data Available.
ITH_UART_TX_READY
THR Empty.
ITH_UART_RECV_STATUS
Receiver Line Status.
ITH_UART_MODEM_STATUS
MODEM Status.
Definition at line 3441 of file ith.h.
enum ITHUartMode
UART mode definition.
Enumerator
ITH_UART_DEFAULT
UART TX/RX mode.
ITH_UART_SIR
SIR mode.
ITH_UART_FIR
FIR mode.
ITH_UART_TX
UART TX only mode.
Definition at line 3387 of file ith.h.
enum ITHUartParity
UART parity definition.
Enumerator
ITH_UART_NONE
None.
ITH_UART_ODD
Odd.
ITH_UART_EVEN
Even.
ITH_UART_MARK
Mark.
ITH_UART_SPACE
Space.
Definition at line 3398 of file ith.h.
enum ITHUartPort
UART port definition.
Enumerator
ITH_UART0
UART port #0.
ITH_UART1
UART port #1.
ITH_UART2
UART port #2.
ITH_UART3
UART port #3.
Definition at line 3376 of file ith.h.
enum ITHUartTriggerLevel
UART trigger level of the TX/RX FIFO interrupt.
Enumerator
ITH_UART_TRGL0
FIFO Trigger Level0.
ITH_UART_TRGL1
FIFO Trigger Level1.
ITH_UART_TRGL2
FIFO Trigger Level2.
ITH_UART_TRGL3
FIFO Trigger Level3.
Definition at line 3430 of file ith.h.
Function Documentation
static uint32_t ithUartClearIntr (ITHUartPort port) inline static
Clears UART interrupt.
Parameters
port The UART port.
Examples:
test_uart/test_uart.c.
Definition at line 3630 of file ith.h.
References ITH_UART_IIR_REG, and ithReadRegA().
static void ithUartDisableDmaMode2 (ITHUartPort port) inline static
Disables UART DMA MODE2.
Parameters
port The UART port.
Definition at line 3650 of file ith.h.
References ITH_UART_MCR_DMAMODE2, ITH_UART_MCR_REG, and ithWriteRegMaskA().
static void ithUartDisableIntr (ITHUartPort port, ITHUartIntr intr) inline static
Disables UART interrupt.
Parameters
port The UART port.
intr The UART interrupt.
Definition at line 3620 of file ith.h.
References ITH_UART_IER_REG, and ithClearRegBitA().
static void ithUartEnableDmaMode2 (ITHUartPort port) inline static
Enables UART DMA MODE2.
Parameters
port The UART port.
Definition at line 3640 of file ith.h.
References ITH_UART_MCR_DMAMODE2, ITH_UART_MCR_REG, and ithWriteRegMaskA().
static void ithUartEnableIntr (ITHUartPort port, ITHUartIntr intr) inline static
Enables UART interrupt.
Parameters
port The UART port.
intr The UART interrupt.
Examples:
test_uart/test_uart.c.
Definition at line 3609 of file ith.h.
References ITH_UART_IER_REG, and ithSetRegBitA().
void ithUartFifoCtrlDisable (ITHUartPort port, ITHUartFifoCtrl ctrl)
Disables specified FIFO controls.
Parameters
port The UART port.
ctrl the controls to disable.
void ithUartFifoCtrlEnable (ITHUartPort port, ITHUartFifoCtrl ctrl)
Enables specified FIFO controls.
Parameters
port The UART port.
ctrl the controls to enable.
static char ithUartGetChar (ITHUartPort port) inline static
Gets a character from UART RX.
Parameters
port The UART port.
Definition at line 3561 of file ith.h.
References ITH_UART_RBR_REG, and ithReadRegA().
static ITHUartFifoDepth ithUartGetFifoDepth (ITHUartPort port) inline static
Whether RX is ready.
Returns
the result of RX is ready or not
Definition at line 3541 of file ith.h.
References ITH_UART_FEATURE_REG, ITH_UART_FIFO_DEPTH_BIT, ITH_UART_FIFO_DEPTH_MASK, and ithReadRegA().
static bool ithUartIsRxReady (ITHUartPort port) inline static
Whether RX is ready.
Returns
the result of RX is ready or not
Definition at line 3551 of file ith.h.
References ITH_UART_LSR_DR, ITH_UART_LSR_REG, and ithReadRegA().
static bool ithUartIsTxEmpty (ITHUartPort port) inline static
Whether TX FIFO is empty.
Returns
the result of TX FIFO is empty or not
Definition at line 3571 of file ith.h.
References ITH_UART_LSR_REG, ITH_UART_LSR_THRE, and ithReadRegA().
static bool ithUartIsTxFull (ITHUartPort port) inline static
Whether TX FIFO is full.
Returns
the result of TX FIFO is full or not
Definition at line 3587 of file ith.h.
References ITH_UART_IIR_REG, ITH_UART_IIR_TXFIFOFULL, and ithReadRegA().
static bool ithUartIsTxWIthFifoEmpty (ITHUartPort port) inline static
Definition at line 3576 of file ith.h.
References ITH_UART_LSR_REG, ITH_UART_LSR_TRANS_EMPTY, and ithReadRegA().
static void ithUartPutChar (ITHUartPort port, char c) inline static
Puts character to UART TX.
Parameters
port The UART port.
c The character.
Definition at line 3598 of file ith.h.
References ITH_UART_THR_REG, and ithWriteRegA().
void ithUartReset (ITHUartPort port, unsigned int baud, ITHUartParity parity, unsigned int stop, unsigned int len)
Resets UART.
Parameters
port The UART port.
baud The UART baudrate.
parity The UART parity.
stop The UART stop bit.
len The UART word length.
void ithUartSetBaudRate (ITHUartPort port, unsigned int baud)
Only sets UART baudrate.
Parameters
port The UART port.
baud The UART baudrate.
void ithUartSetMode (ITHUartPort port, ITHUartMode mode, unsigned int txPin, unsigned int rxPin)
Sets UART mode.
Parameters
port The UART port
mode The UART mode
txPin The UART TX GPIO pin. for UART1 only.
rxPin The UART RX GPIO pin.
void ithUartSetParity (ITHUartPort port, ITHUartParity parity, unsigned int stop, unsigned int len)
Only sets UART parity.
Parameters
port The UART port.
parity The UART parity.
stop The UART stop bit.
len The UART word length.
void ithUartSetRxTriggerLevel (ITHUartPort port, ITHUartTriggerLevel level)
Sets UART RX interrupt trigger level.
Parameters
port The UART port
level The UART RX trigger level
void ithUartSetTxTriggerLevel (ITHUartPort port, ITHUartTriggerLevel level)
Sets UART TX interrupt trigger level.
Parameters
port The UART port
level The UART TX trigger level