ITE SoC SDK: Capture
Capture
ITE DoorBell Indoor Modules
Data Structures
struct CaptureEntry
Captured file entry.
Macros
#define CAPUTRE_MAX_FILENAME_SIZE 40
Maximum size of captured file name.
#define CAPUTRE_MAX_NAME_SIZE 40
Maximum count of capture item name.
Enumerations
enum MediaType { MEDIA_TEXT, MEDIA_IMAGE, MEDIA_VIDEO, MEDIA_AUDIO }
Capture media definitions.
Functions
void CaptureInit (void)
Initializes capture module.
void CaptureExit (void)
Exits capture module.
int CaptureGetCount (void)
Gets total count of captured file.
int CaptureGetUnplayCount (void)
Gets unplay count of captured file.
CaptureEntry * CaptureGetEntry (int index)
Gets the captured entry by index.
void CaptureDeleteEntry (int index)
Deletes the captured entry by index.
void CaptureSnapshotDeleteEntry (int index)
Deletes the Snapshotcaptured entry by index.
bool CaptureIsPlayFinished (void)
Playing the captured file is finished or not.
int CaptureStartPlay (int index)
Plays the captured file.
void CaptureStopPlay (void)
Stops playing captured file.
int CaptureStartRecord (MediaType type, char *addr)
Starts capturing.
int CaptureStopRecord (void)
Stops capturing.
int CaptureSnapshotStart (char *filepath)
start to Snapshots current image.
int CaptureSnapshot (char *addr, time_t t)
Snapshots current image.
char * CaptureGetSnapshotFileNameByTime (char *time)
Gets the file name of snapshot by time.
char * CaptureGetPath (void)
Gets the path of capture directory.
bool CaptureCheckDiskSpace (int max_file_size, MediaType media_type)
Checks the disk space is availabe to Snapshot current image.
Detailed Description
Macro Definition Documentation
#define CAPUTRE_MAX_FILENAME_SIZE 40
Maximum size of captured file name.
Definition at line 467 of file doorbell_indoor/doorbell.h.
Referenced by CaptureCreateTask(), CaptureSnapshot(), CaptureSnapShotSuccess(), and CaptureStopRecord().
#define CAPUTRE_MAX_NAME_SIZE 40
Maximum count of capture item name.
Definition at line 468 of file doorbell_indoor/doorbell.h.
Referenced by CaptureCreateTask(), CaptureSnapshot(), CaptureStopRecord(), VideoMemoCreateTask(), and VideoMemoStopRecord().
Enumeration Type Documentation
enum MediaType
Capture media definitions.
Enumerator
MEDIA_TEXT
Text media type.
MEDIA_IMAGE
Image media type.
MEDIA_VIDEO
Video media type.
MEDIA_AUDIO
Audio media type.
Definition at line 473 of file doorbell_indoor/doorbell.h.
Function Documentation
bool CaptureCheckDiskSpace (int max_file_size, MediaType media_type)
Checks the disk space is availabe to Snapshot current image.
Returns
true for success, otherwise failed.
Definition at line 837 of file capture.c.
References CaptureGetPath(), MEDIA_IMAGE, MEDIA_VIDEO, and SNAPSHOT_PATH.
Referenced by CaptureSnapshot(), and CaptureStopRecord().
void CaptureDeleteEntry (int index)
Deletes the captured entry by index.
Parameters
index The index of captured entry.
Definition at line 420 of file capture.c.
References captureCount, CaptureDeleteFile(), captureInited, captureQuit, i, and MAX_CAPTURE_COUNT.
Referenced by CaptureStopRecord(), and MessageRecordDeleteConfirmOnPress().
void CaptureExit (void)
Exits capture module.
Definition at line 325 of file capture.c.
References captureInited, and captureQuit.
Referenced by SDL_main().
int CaptureGetCount (void)
Gets total count of captured file.
Returns
the total count of captured file.
Definition at line 331 of file capture.c.
References captureCount, captureInited, and captureQuit.
Referenced by CaptureGetSnapshotFileNameByTime(), MessageRecordIconListBoxOnLoad(), MessageRecordTimeListBoxOnLoad(), and MessageRecordTopicListBoxOnLoad().
CaptureEntry* CaptureGetEntry (int index)
Gets the captured entry by index.
Parameters
index The index of captured entry.
Returns
The captured entry, NULL if not found.
Definition at line 347 of file capture.c.
References captureCount, CaptureGetPath(), captureInited, captureQuit, CaptureEntry::filename, i, MAX_CAPTURE_COUNT, MEDIA_AUDIO, MEDIA_VIDEO, CaptureEntry::sec, CaptureEntry::type, and VideoRecordGetTimeLength().
Referenced by CaptureGetSnapshotFileNameByTime(), CaptureStartPlay(), MessageRecordDeleteConfirmOnPress(), MessageRecordIconListBoxOnLoad(), MessageRecordTimeListBoxOnLoad(), MessageRecordTopicListBoxOnLoad(), and MessageRecordViewButtonOnPress().
char* CaptureGetPath (void)
Gets the path of capture directory.
Returns
The path.
Definition at line 812 of file capture.c.
References captureRunSDCardPath, DEVICE_INDOOR2, theDeviceInfo, DeviceInfo::type, and UpgradeGetSDPath().
Referenced by CalledIncomingShow(), CallingCall(), CameraOnEnter(), CameraOutdoorOnEnter(), CameraViewShow(), CaptureCheckDiskSpace(), CaptureCreateTask(), CaptureDeleteFile(), CaptureGetEntry(), CaptureStartPlay(), CaptureStartRecord(), CaptureStopRecord(), and PhoneLogViewShow().
char* CaptureGetSnapshotFileNameByTime (char * time)
Gets the file name of snapshot by time.
Parameters
time The snapshot time. The format is like 01/01/2014 12:00:00
Returns
The file name.
Definition at line 792 of file capture.c.
References CaptureGetCount(), CaptureGetEntry(), CaptureEntry::filename, i, MEDIA_IMAGE, font::t, CaptureEntry::time, and CaptureEntry::type.
Referenced by PhoneLogViewShow().
int CaptureGetUnplayCount (void)
Gets unplay count of captured file.
Returns
unplay count of captured file.
Definition at line 339 of file capture.c.
References captureInited, captureQuit, and captureUnplayCount.
Referenced by MessagePhotoOnEnter(), MessageRecordDeleteConfirmOnPress(), and MessageRecordViewOnEnter().
void CaptureInit (void)
Initializes capture module.
Definition at line 312 of file capture.c.
References attr, captureCount, CaptureCreateTask(), captureInited, capturePlayFinished, captureQuit, captureRecording, captureRunSDCardPath, captureSnapShotSuccess, and captureUnplayCount.
Referenced by SDL_main().
bool CaptureIsPlayFinished (void)
Playing the captured file is finished or not.
Returns
true for finished, false for otherwise.
Definition at line 474 of file capture.c.
References capturePlayFinished.
Referenced by MessageRecordViewOnTimer().
int CaptureSnapshot (char * addr, time_t t)
Snapshots current image.
Parameters
addr The IP address of target to snapshot.
t The snapshot time. 0 for current time.
Returns
0 for success, otherwise failed.
Definition at line 718 of file capture.c.
References AddressBookGetDeviceInfo(), DeviceInfo::building, CAPTURE_IMAGE_EXT, capture_mutex, CaptureCheckDiskSpace(), captureCount, captureInited, captureQuit, CaptureSnapshotDeleteEntry(), CaptureSnapshotEntryname, CaptureSnapshotStart(), CAPUTRE_MAX_FILENAME_SIZE, CAPUTRE_MAX_NAME_SIZE, CaptureEntry::filename, MAX_CAPTURE_COUNT, MEDIA_IMAGE, CaptureEntry::name, CaptureEntry::played, CaptureEntry::sec, SNAPSHOT_PATH, StringGetDeviceType(), font::t, CaptureEntry::time, DeviceInfo::type, and CaptureEntry::type.
Referenced by CalledSnapshotButtonOnPress(), CallFirstSnapshot(), CallingSnapshotButtonOnPress(), CameraOutdoorSnapshotButtonOnPress(), and CameraViewSnapshotButtonOnPress().
void CaptureSnapshotDeleteEntry (int index)
Deletes the Snapshotcaptured entry by index.
Parameters
index The index of captured entry.
Definition at line 447 of file capture.c.
References captureCount, captureInited, captureQuit, CaptureSnapshotDeleteFile(), i, and MAX_CAPTURE_COUNT.
Referenced by CaptureSnapshot(), and MessageRecordDeleteConfirmOnPress().
int CaptureSnapshotStart (char * filepath)
start to Snapshots current image.
Parameters
filepath The file path to save the snapshot.
Returns
0 for success, otherwise failed.
Definition at line 710 of file capture.c.
References captureSnapShotSuccess, CaptureSnapShotSuccess(), and LinphoneSnapshot().
Referenced by CaptureSnapshot().
int CaptureStartPlay (int index)
Plays the captured file.
Only for MEDIA_VIDEO and MEDIA_AUDIO types.
Parameters
index The index of captured file to play.
Returns
0 for success, otherwise failed.
Definition at line 484 of file capture.c.
References capture_mutex, CaptureGetEntry(), CaptureGetPath(), captureInited, capturePlayFinished, CapturePlayFinished(), captureQuit, captureUnplayCount, CaptureEntry::filename, ITP_DEVICE_NOR, ITP_IOCTL_FLUSH, MEDIA_AUDIO, MEDIA_IMAGE, MEDIA_VIDEO, CaptureEntry::played, SNAPSHOT_PATH, CaptureEntry::type, and VideoRecordStartPlay().
Referenced by MessageRecordViewOnEnter().
int CaptureStartRecord (MediaType type, char * addr)
Starts capturing.
Parameters
type The media type. Only for MEDIA_VIDEO and MEDIA_AUDIO types.
addr The IP address of target to capture.
Returns
0 for success, otherwise failed.
Definition at line 538 of file capture.c.
References CAPTURE_AUDIO_EXT, CAPTURE_IMAGE_EXT, capture_mutex, CAPTURE_VIDEO_EXT, CaptureGetPath(), captureInited, captureQuit, captureRecordFileName, captureRecording, MEDIA_AUDIO, MEDIA_IMAGE, MEDIA_VIDEO, and VideoRecordStartRecord().
Referenced by CalledRecordButtonOnPress(), CallingRecordButtonOnPress(), CameraOutdoorRecordButtonOnPress(), and CameraViewRecordButtonOnPress().
void CaptureStopPlay (void)
Stops playing captured file.
Definition at line 532 of file capture.c.
References capturePlayFinished, and VideoRecordStopPlay().
Referenced by MessageRecordViewOnLeave().
int CaptureStopRecord (void)
Stops capturing.
Returns
0 for success, otherwise failed.
Definition at line 593 of file capture.c.
References AddressBookGetDeviceInfo(), DeviceInfo::building, Config::calling_time, CAPTURE_AUDIO_EXT, CAPTURE_IMAGE_EXT, capture_mutex, CAPTURE_VIDEO_EXT, CaptureCheckDiskSpace(), captureCount, CaptureDeleteEntry(), CaptureGetPath(), captureInited, captureQuit, captureRecordFileName, captureRecording, captureUnplayCount, CAPUTRE_MAX_FILENAME_SIZE, CAPUTRE_MAX_NAME_SIZE, CaptureEntry::filename, MAX_CAPTURE_COUNT, MEDIA_AUDIO, MEDIA_IMAGE, MEDIA_TEXT, MEDIA_VIDEO, CaptureEntry::name, CaptureEntry::played, CaptureEntry::sec, StringGetDeviceType(), theConfig, CaptureEntry::time, DeviceInfo::type, CaptureEntry::type, and VideoRecordStopRecord().
Referenced by CalledOnLeave(), CalledSourceListBoxOnSelection(), CalledStopRecordButtonOnPress(), CalledWaitingConfirmButtonOnPress(), CalledWaitingConfirmButtonOnSimulatePressing(), CallingOnLeave(), CallingStopRecordButtonOnPress(), CallingWaitingConfirmButtonOnPress(), CallingWaitingConfirmButtonOnSimulatePressing(), CameraListOnSelection(), CameraOnLeave(), CameraOnTimer(), CameraOutdoorOnLeave(), CameraOutdoorOnTimer(), CameraOutdoorStopRecordButtonOnPress(), CameraViewOnLeave(), and CameraViewStopRecordButtonOnPress().