ITE SoC SDK: CheckBox
CheckBox
ITE UI Library » Widgets
Data Structures
struct ITUCheckBox
Check box widget definition.
Functions
void ituCheckBoxInit (ITUCheckBox *checkbox)
Initializes the check box widget.
void ituCheckBoxLoad (ITUCheckBox *checkbox, uint32_t base)
Loads the check box widget.
void ituCheckBoxExit (ITUWidget *widget)
Exits the check box widget.
bool ituCheckBoxClone (ITUWidget *widget, ITUWidget **cloned)
Clones the check box widget.
bool ituCheckBoxUpdate (ITUWidget *widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the check box widget by specified event.
void ituCheckBoxDraw (ITUWidget *widget, ITUSurface *dest, int x, int y, uint8_t alpha)
Draws the check box widget to the specified surface.
void ituCheckBoxOnAction (ITUWidget *widget, ITUActionType action, char *param)
Do the specified action.
void ituCheckBoxSetChecked (ITUCheckBox *checkbox, bool checked)
Sets the check box widget checked or not.
bool ituCheckBoxIsChecked (ITUCheckBox *checkbox)
Is the check box widget checked or not.
void ituCheckBoxLoadStaticData (ITUCheckBox *checkbox)
Loads static data to the check box widget.
void ituCheckBoxReleaseSurface (ITUCheckBox *checkbox)
Releases surface of check box widget.
Detailed Description
Function Documentation
bool ituCheckBoxClone (ITUWidget * widget, ITUWidget ** cloned)
Clones the check box widget.
Parameters
widget The check box widget to clone.
cloned Retrieved cloned check box widget.
Returns
true if clone is success, false otherwise.
void ituCheckBoxDraw (ITUWidget * widget, ITUSurface * dest, int x, int y, uint8_t alpha)
Draws the check box widget to the specified surface.
Parameters
widget The check box widget to draw.
dest The surface to draw to.
x The x coordinate of destination surface, in pixels.
y The y coordinate of destination surface, in pixels.
alpha the alpha value to do the constant alphablending to the surface.
void ituCheckBoxExit (ITUWidget * widget)
Exits the check box widget.
Parameters
widget The check box widget to exit.
void ituCheckBoxInit (ITUCheckBox * checkbox)
Initializes the check box widget.
Parameters
checkbox The check box widget to initialize.
bool ituCheckBoxIsChecked (ITUCheckBox * checkbox)
Is the check box widget checked or not.
Parameters
checkbox The check box widget.
Returns
Is checked or not.
Referenced by GuardUserSettingSaveButtonOnPress(), PhoneContactsAddConfirmButtonOnPress(), PhoneContactsModifyConfirmButtonOnPress(), and TouchCalibrationCheckBoxOnPress().
void ituCheckBoxLoad (ITUCheckBox * checkbox, uint32_t base)
Loads the check box widget.
This is called by scene manager.
Parameters
checkbox The check box widget to load.
base The address in the scene file buffer.
void ituCheckBoxLoadStaticData (ITUCheckBox * checkbox)
Loads static data to the check box widget.
Parameters
checkbox The check box widget to load.
void ituCheckBoxOnAction (ITUWidget * widget, ITUActionType action, char * param)
Do the specified action.
This is triggered by other widget's event.
Parameters
widget The check box widget to do the action.
action The action to do.
param The parameter of action.
void ituCheckBoxReleaseSurface (ITUCheckBox * checkbox)
Releases surface of check box widget.
Parameters
checkbox The check box widget to release.
void ituCheckBoxSetChecked (ITUCheckBox * checkbox, bool checked)
Sets the check box widget checked or not.
Parameters
checkbox The check box widget to set.
checked true for checked or false for un-checked.
Referenced by GuardUserSettingCancelButtonOnPress(), GuardUserSettingOnEnter(), PhoneContactsAddShow(), PhoneContactsModifyShow(), TouchCalibrationCheckBoxOnPress(), and TouchCalibrationOnEnter().
bool ituCheckBoxUpdate (ITUWidget * widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the check box widget by specified event.
Parameters
widget The check box widget to update.
ev The event to notify.
arg1 The event related argument #1.
arg2 The event related argument #2.
arg3 The event related argument #3.
Returns
true if the check box widget is modified and need to be redraw, false if no need to be redraw.