ITE SoC SDK: Button
Button
ITE UI Library » Widgets
Data Structures
struct ITUButton
Button widget definition.
Macros
#define ituButtonIsPressed(btn) (((ITUButton*)(btn))->pressed)
Is the button pressed or not.
#define ituButtonSetString(btn, string) ituButtonSetStringImpl((ITUButton*)(btn), (char*)(string))
Sets string of the button widget.
Functions
void ituButtonInit (ITUButton *btn)
Initializes the button widget.
void ituButtonLoad (ITUButton *btn, uint32_t base)
Loads the button widget.
void ituButtonExit (ITUWidget *widget)
Exits the button widget.
bool ituButtonClone (ITUWidget *widget, ITUWidget **cloned)
Clones the button widget.
bool ituButtonUpdate (ITUWidget *widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the button widget by specified event.
void ituButtonDraw (ITUWidget *widget, ITUSurface *dest, int x, int y, uint8_t alpha)
Draws the button widget to the specified surface.
void ituButtonOnAction (ITUWidget *widget, ITUActionType action, char *param)
Do the specified action.
void ituButtonSetPressed (ITUButton *btn, bool pressed)
Sets the button pressed or not.
void ituButtonSetStringImpl (ITUButton *btn, char *string)
Sets string of the button widget.
void ituButtonLoadStaticData (ITUButton *btn)
Loads static data to the button widget.
void ituButtonReleaseSurface (ITUButton *btn)
Releases surface of button widget.
Detailed Description
Macro Definition Documentation
#define ituButtonIsPressed (btn) (((ITUButton*)(btn))->pressed)
Is the button pressed or not.
Parameters
btn The button.
Returns
Is pressed or not.
Examples:
test_itu/test_button.c, and test_itu/test_cursor.c.
Definition at line 2960 of file itu.h.
#define ituButtonSetString (btn, string) ituButtonSetStringImpl((ITUButton*)(btn), (char*)(string))
Sets string of the button widget.
Parameters
btn Pointer referring to the button widget.
string The string to set.
Definition at line 2976 of file itu.h.
Referenced by PhoneContactsKeyboardBackButtonOnPress(), PhoneContactsKeyboardChsButtonOnPress(), PhoneContactsKeyboardChsCharButtonOnPress(), PhoneContactsKeyboardOnEnter(), PhoneContactsKeyboardPageDownButtonOnPress(), and PhoneContactsKeyboardPageUpButtonOnPress().
Function Documentation
bool ituButtonClone (ITUWidget * widget, ITUWidget ** cloned)
Clones the button widget.
Parameters
widget The button widget to clone.
cloned Retrieved cloned button widget.
Returns
true if clone is success, false otherwise.
void ituButtonDraw (ITUWidget * widget, ITUSurface * dest, int x, int y, uint8_t alpha)
Draws the button widget to the specified surface.
Parameters
widget The button widget to draw.
dest The surface to draw to.
x The x coordinate of destination surface, in pixels.
y The y coordinate of destination surface, in pixels.
alpha the alpha value to do the constant alphablending to the surface.
void ituButtonExit (ITUWidget * widget)
Exits the button widget.
Parameters
widget The button widget to exit.
void ituButtonInit (ITUButton * btn)
Initializes the button widget.
Parameters
btn The button widget to initialize.
void ituButtonLoad (ITUButton * btn, uint32_t base)
Loads the button widget.
This is called by scene manager.
Parameters
btn The button widget to load.
base The address in the scene file buffer.
void ituButtonLoadStaticData (ITUButton * btn)
Loads static data to the button widget.
Parameters
btn The button widget to load.
void ituButtonOnAction (ITUWidget * widget, ITUActionType action, char * param)
Do the specified action.
This is triggered by other widget's event.
Parameters
widget The button widget to do the action.
action The action to do.
param The parameter of action.
void ituButtonReleaseSurface (ITUButton * btn)
Releases surface of button widget.
Parameters
btn The button widget to release.
void ituButtonSetPressed (ITUButton * btn, bool pressed)
Sets the button pressed or not.
Parameters
btn The button to set.
pressed Is pressed or not.
Referenced by CalledHangUpButtonOnPress(), CalledWaitingCancelButtonOnPress(), CallingHangUpButtonOnPress(), CallingWaitingCancelButtonOnPress(), and VideoRecordHangUpButtonOnPress().
void ituButtonSetStringImpl (ITUButton * btn, char * string)
Sets string of the button widget.
This is the implementation of button widget.
Parameters
btn Pointer referring to the button widget.
string The string to set.
bool ituButtonUpdate (ITUWidget * widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the button widget by specified event.
Parameters
widget The button widget to update.
ev The event to notify.
arg1 The event related argument #1.
arg2 The event related argument #2.
arg3 The event related argument #3.
Returns
true if the button widget is modified and need to be redraw, false if no need to be redraw.