ITE SoC SDK: Upgrade
Upgrade
ITE Upgrade Library
Functions
int ugUpgradeCheck (void)
Checks last upgrade is success or not.
int ugUpgradePackage (ITCStream *file)
Do the upgrade procedure from the specified file stream.
int ugCheckCrc (ITCStream *f, uint8_t *buffer)
Checks the CRC value of the specified file stream.
int ugResetFactory (void)
Restores files from /backup directory of private partition disk.
Detailed Description
Function Documentation
int ugCheckCrc (ITCStream * f, uint8_t * buffer)
Checks the CRC value of the specified file stream.
Parameters
f the file stream.
buffer Retrieves file content if buffer address is available, null for ignore.
Returns
0 (OK), or otherwise (ERROR).
Example:
 ITCFileStream fileStream;
 int ret;
 // open package file to do the upgrade
 ret = itcFileStreamOpen(&fileStream, "B:/ITEPKG03.PKG", false);
 if (ret)
     return ret; // open file error
 ret = ugCheckCrc(&fileStream, NULL);
 if (ret)
     return ret; // check crc fail
 ret = ugUpgradePackage(&fileStream);
 if (ret)
     return ret; // upgrade fail
Referenced by ahc_echo(), create_response(), and UpgradePackage().
int ugResetFactory (void)
Restores files from /backup directory of private partition disk.
Returns
0 (OK), or otherwise (ERROR).
Referenced by UpgradeResetFactory().
int ugUpgradeCheck (void)
Checks last upgrade is success or not.
Returns
0 (success), or otherwise (failed).
int ugUpgradePackage (ITCStream * file)
Do the upgrade procedure from the specified file stream.
Parameters
file the file stream.
Returns
0 (OK), or otherwise (ERROR).
Referenced by UpgradePackage(), and UpgradeProcess().