ITE SoC SDK: ITE Hardware Library
ITE Hardware Library
Modules
Platform
Used by this module internal.
VRAM
Register
Chip ID
Clock
Memory Debug
Memory Statistic
Host
AHB0
ISP
USB
JPEG
Ui Encode
Capture controllor
Video
LCD
Command Queue
OpenVG
TV Encoder
FPC & STC
NAND
Gets extension clock of STC.
encryption/descryption
Decompress
Macros
#define ITH_REG_BASE 0
Typedefs
typedef void(* ITHIntrHandler)(void *arg)
Interrupt handler.
Enumerations
enum ITHIntr {
ITH_INTR_SW0 = 0, ITH_INTR_MC = 1, ITH_INTR_DMA = 2, ITH_INTR_TIMER = 4,
ITH_INTR_TIMER1 = 5, ITH_INTR_TIMER2 = 6, ITH_INTR_TIMER3 = 7, ITH_INTR_TIMER4 = 8,
ITH_INTR_TIMER5 = 9, ITH_INTR_TIMER6 = 10, ITH_INTR_TIMER7 = 11, ITH_INTR_TIMER8 = 12,
ITH_INTR_RTC = 13, ITH_INTR_RTCSEC = 14, ITH_INTR_RTCMIN = 15, ITH_INTR_RTCHOUR = 16,
ITH_INTR_RTCDAY = 17, ITH_INTR_RTCALARM = 18, ITH_INTR_WD = 19, ITH_INTR_CPU0 = 20,
ITH_INTR_CPU1 = 21, ITH_INTR_ALTCPU = 23, ITH_INTR_CMDQ = 24, ITH_INTR_LCD = 25,
ITH_INTR_2D = 26, ITH_INTR_GPIO = 27, ITH_INTR_VIDEO = 28, ITH_INTR_JPEG = 29,
ITH_INTR_I2C0 = 30, ITH_INTR_I2C1 = 31, ITH_INTR_SW1 = 32 + 0, ITH_INTR_USB0 = 32 + 1,
ITH_INTR_USB1 = 32 + 2, ITH_INTR_MAC = 32 + 3, ITH_INTR_WIEGAND0 = 32 + 4, ITH_INTR_WIEGAND1 = 32 + 5,
ITH_INTR_UART0 = 32 + 6, ITH_INTR_UART1 = 32 + 7, ITH_INTR_UART2 = 32 + 8, ITH_INTR_UART3 = 32 + 9,
ITH_INTR_UART4 = 32 + 10, ITH_INTR_UART5 = 32 + 11, ITH_INTR_ISP = 32 + 14, ITH_INTR_IQ = 32 + 15,
ITH_INTR_I2S = 32 + 16, ITH_INTR_DPU = 32 + 17, ITH_INTR_DECOMPRESS = 32 + 18, ITH_INTR_CAPTURE = 32 + 19,
ITH_INTR_TSI0 = 32 + 20, ITH_INTR_TSI1 = 32 + 21, ITH_INTR_TSM = 32 + 22, ITH_INTR_SARADC = 32 + 23,
ITH_INTR_SD0 = 32 + 24, ITH_INTR_SD1 = 32 + 25, ITH_INTR_IRRX = 32 + 26, ITH_INTR_IRTX = 32 + 27,
ITH_INTR_SSP0 = 32 + 28, ITH_INTR_SSP1 = 32 + 29, ITH_INTR_AXISPI = 32 + 30, ITH_INTR_MIPI = 32 + 31
}
Interrupt number definition.
enum ITHIntrTriggerMode { ITH_INTR_LEVEL = 0, ITH_INTR_EDGE = 1 }
Interrupt trigger mode definition.
enum ITHIntrTriggerLevel { ITH_INTR_HIGH_RISING = 0, ITH_INTR_LOW_FALLING = 1 }
Functions
void ithIntrInit (void)
Initializes interrupt module.
void ithIntrReset (void)
Resets interrupt module.
static void ithIntrEnableIrq (ITHIntr intr)
Enables specified IRQ.
static void ithIntrDisableIrq (ITHIntr intr)
Disables specified IRQ.
static void ithIntrClearIrq (ITHIntr intr)
Clears specified IRQ.
static void ithIntrGetStatusIrq (uint32_t *intr1, uint32_t *intr2)
Gets status of IRQ.
void ithIntrSetTriggerModeIrq (ITHIntr intr, ITHIntrTriggerMode mode)
Sets trigger mode of IRQ.
void ithIntrSetTriggerLevelIrq (ITHIntr intr, ITHIntrTriggerLevel level)
Sets trigger level of IRQ.
void ithIntrRegisterHandlerIrq (ITHIntr intr, ITHIntrHandler handler, void *arg)
Registers IRQ handler.
static void ithIntrSetSwIrq (int num)
Sets software IRQ.
static void ithIntrClearSwIrq (int num)
Clears software IRQ.
void ithIntrDoIrq (void)
Dispatches IRQ to handlers.
static void ithIntrEnableFiq (ITHIntr intr)
Enables specified FIQ.
static void ithIntrDisableFiq (ITHIntr intr)
Disables specified FIQ.
static void ithIntrClearFiq (ITHIntr intr)
Clears specified FIQ.
static void ithIntrGetStatusFiq (uint32_t *intr1, uint32_t *intr2)
Gets status of FIQ.
void ithIntrSetTriggerModeFiq (ITHIntr intr, ITHIntrTriggerMode mode)
Sets trigger mode of FIQ.
void ithIntrSetTriggerLevelFiq (ITHIntr intr, ITHIntrTriggerLevel level)
Sets trigger level of FIQ.
void ithIntrRegisterHandlerFiq (ITHIntr intr, ITHIntrHandler handler, void *arg)
Registers FIQ handler.
static void ithIntrSetSwFiq (int num)
Sets software FIQ.
static void ithIntrClearSwFiq (int num)
Clears software FIQ.
void ithIntrDoFiq (void)
Dispatches FIQ to handlers.
void ithIntrSuspend (void)
Suspends interrupt module.
void ithIntrResume (void)
Resumes from suspends for interrupt module.
void ithIntrStats (void)
Print interrupt information.
Detailed Description
Macro Definition Documentation
#define ITH_REG_BASE 0
Definition at line 56 of file ith.h.
Referenced by ithReadReg16(), ithReadReg8(), ithReadRegA(), ithReadRegH(), ithWriteReg16(), ithWriteReg8(), ithWriteRegA(), and ithWriteRegH().
Typedef Documentation
typedef void(* ITHIntrHandler)(void *arg)
Interrupt handler.
Custom argument.
Definition at line 2951 of file ith.h.
Enumeration Type Documentation
enum ITHIntr
Interrupt number definition.
Enumerator
ITH_INTR_SW0
Software (interrupt is invoking when write the software interrupt to 1)
ITH_INTR_MC
Memory Controller.
ITH_INTR_DMA
DMA / DMA Terminal Count /DMA Error.
ITH_INTR_TIMER
Timer (for All)
ITH_INTR_TIMER1
Timer 1.
ITH_INTR_TIMER2
Timer 2.
ITH_INTR_TIMER3
Timer 3.
ITH_INTR_TIMER4
Timer 4.
ITH_INTR_TIMER5
Timer 5.
ITH_INTR_TIMER6
Timer 6.
ITH_INTR_TIMER7
Timer 7.
ITH_INTR_TIMER8
Timer 8.
ITH_INTR_RTC
Real time clock.
ITH_INTR_RTCSEC
Real time clock second.
ITH_INTR_RTCMIN
Real time clock minute.
ITH_INTR_RTCHOUR
Real time clock hour.
ITH_INTR_RTCDAY
Real time day.
ITH_INTR_RTCALARM
Real time alarm.
ITH_INTR_WD
Watch dog.
ITH_INTR_CPU0
CPU0.
ITH_INTR_CPU1
CPU1.
ITH_INTR_ALTCPU
ALTCPU.
ITH_INTR_CMDQ
Command Queue.
ITH_INTR_LCD
LCD.
ITH_INTR_2D
2D
ITH_INTR_GPIO
GPIO.
ITH_INTR_VIDEO
Video.
ITH_INTR_JPEG
Jpeg.
ITH_INTR_I2C0
I2C0.
ITH_INTR_I2C1
I2C1.
ITH_INTR_SW1
Software (interrupt is invoking when write the software interrupt register to 1) // 0.
ITH_INTR_USB0
USB0.
ITH_INTR_USB1
USB1.
ITH_INTR_MAC
MAC / MAC WOL.
ITH_INTR_WIEGAND0
Wiegand0.
ITH_INTR_WIEGAND1
Wiegand1.
ITH_INTR_UART0
UART 0.
ITH_INTR_UART1
UART 1.
ITH_INTR_UART2
UART 2.
ITH_INTR_UART3
UART 3.
ITH_INTR_UART4
UART 4.
ITH_INTR_UART5
UART 5.
ITH_INTR_ISP
ISP.
ITH_INTR_IQ
IQ.
ITH_INTR_I2S
I2S.
ITH_INTR_DPU
DPU.
ITH_INTR_DECOMPRESS
Decompress.
ITH_INTR_CAPTURE
CCIR601/656 Capture.
ITH_INTR_TSI0
TSI 0 Interface.
ITH_INTR_TSI1
TSI 1 Interface.
ITH_INTR_TSM
TSM.
ITH_INTR_SARADC
TSM.
ITH_INTR_SD0
SD/MMC 0.
ITH_INTR_SD1
SD/MMC 1.
ITH_INTR_IRRX
Remote IR RX.
ITH_INTR_IRTX
Remote IR TX.
ITH_INTR_SSP0
SSP 0.
ITH_INTR_SSP1
SSP 1.
ITH_INTR_AXISPI
AXISPI.
ITH_INTR_MIPI
MIPI.
Definition at line 2701 of file ith.h.
enum ITHIntrTriggerLevel
Enumerator
ITH_INTR_HIGH_RISING
Active-high level trigger or rising-edge trigger.
ITH_INTR_LOW_FALLING
Active-low level trigger or falling-edge trigger.
Definition at line 2940 of file ith.h.
enum ITHIntrTriggerMode
Interrupt trigger mode definition.
Enumerator
ITH_INTR_LEVEL
Level-trigger mode.
ITH_INTR_EDGE
Edge-trigger mode.
Definition at line 2934 of file ith.h.
Function Documentation
static void ithIntrClearFiq (ITHIntr intr) inline static
Clears specified FIQ.
Parameters
intr The FIQ.
Definition at line 3109 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_FIQ1_CLR_REG, ITH_INTR_FIQ2_CLR_REG, and ithSetRegBitA().
static void ithIntrClearIrq (ITHIntr intr) inline static
Clears specified IRQ.
Parameters
intr The IRQ.
Examples:
test_uart/test_uart.c.
Definition at line 3002 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_IRQ1_CLR_REG, ITH_INTR_IRQ2_CLR_REG, and ithSetRegBitA().
static void ithIntrClearSwFiq (int num) inline static
Clears software FIQ.
Parameters
num The FIQ0 or FIQ1.
Definition at line 3172 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_FIQ1_SWINTR_REG, ITH_INTR_FIQ2_SWINTR_REG, ITH_INTR_SWINT_BIT, and ithClearRegBitA().
static void ithIntrClearSwIrq (int num) inline static
Clears software IRQ.
Parameters
num The IRQ0 or IRQ1.
Definition at line 3065 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_IRQ1_SWINTR_REG, ITH_INTR_IRQ2_SWINTR_REG, ITH_INTR_SWINT_BIT, and ithClearRegBitA().
static void ithIntrDisableFiq (ITHIntr intr) inline static
Disables specified FIQ.
Parameters
intr The FIQ.
Definition at line 3096 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_FIQ1_EN_REG, ITH_INTR_FIQ2_EN_REG, and ithClearRegBitA().
static void ithIntrDisableIrq (ITHIntr intr) inline static
Disables specified IRQ.
Parameters
intr The IRQ.
Examples:
test_uart/test_uart.c.
Definition at line 2985 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_IRQ1_EN_REG, ITH_INTR_IRQ2_EN_REG, ithClearRegBitA(), ithEnterCritical(), and ithExitCritical().
void ithIntrDoFiq (void)
Dispatches FIQ to handlers.
void ithIntrDoIrq (void)
Dispatches IRQ to handlers.
static void ithIntrEnableFiq (ITHIntr intr) inline static
Enables specified FIQ.
Parameters
intr The FIQ.
Definition at line 3083 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_FIQ1_EN_REG, ITH_INTR_FIQ2_EN_REG, and ithSetRegBitA().
static void ithIntrEnableIrq (ITHIntr intr) inline static
Enables specified IRQ.
Parameters
intr The IRQ.
Examples:
test_uart/test_uart.c.
Definition at line 2968 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_IRQ1_EN_REG, ITH_INTR_IRQ2_EN_REG, ithEnterCritical(), ithExitCritical(), and ithSetRegBitA().
static void ithIntrGetStatusFiq (uint32_t * intr1, uint32_t * intr2) inline static
Gets status of FIQ.
Parameters
intr1 The FIQ status 1.
intr2 The FIQ status 2.
Definition at line 3123 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_FIQ1_STATUS_REG, ITH_INTR_FIQ2_STATUS_REG, and ithReadRegA().
static void ithIntrGetStatusIrq (uint32_t * intr1, uint32_t * intr2) inline static
Gets status of IRQ.
Parameters
intr1 The IRQ status 1.
intr2 The IRQ status 2.
Definition at line 3016 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_IRQ1_STATUS_REG, ITH_INTR_IRQ2_STATUS_REG, and ithReadRegA().
void ithIntrInit (void)
Initializes interrupt module.
void ithIntrRegisterHandlerFiq (ITHIntr intr, ITHIntrHandler handler, void * arg)
Registers FIQ handler.
Parameters
intr The IRQ.
handler The callback function.
arg Custom argument to pass to handler.
void ithIntrRegisterHandlerIrq (ITHIntr intr, ITHIntrHandler handler, void * arg)
Registers IRQ handler.
Parameters
intr The IRQ.
handler The callback function.
arg Custom argument to pass to handler.
Examples:
test_uart/test_uart.c.
void ithIntrReset (void)
Resets interrupt module.
void ithIntrResume (void)
Resumes from suspends for interrupt module.
static void ithIntrSetSwFiq (int num) inline static
Sets software FIQ.
Parameters
num The FIQ0 or FIQ1.
Definition at line 3159 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_FIQ1_SWINTR_REG, ITH_INTR_FIQ2_SWINTR_REG, ITH_INTR_SWINT_BIT, and ithSetRegBitA().
static void ithIntrSetSwIrq (int num) inline static
Sets software IRQ.
Parameters
num The IRQ0 or IRQ1.
Definition at line 3052 of file ith.h.
References ITH_INTR_BASE, ITH_INTR_IRQ1_SWINTR_REG, ITH_INTR_IRQ2_SWINTR_REG, ITH_INTR_SWINT_BIT, and ithSetRegBitA().
void ithIntrSetTriggerLevelFiq (ITHIntr intr, ITHIntrTriggerLevel level)
Sets trigger level of FIQ.
Parameters
intr The FIQ.
level The trigger level.
void ithIntrSetTriggerLevelIrq (ITHIntr intr, ITHIntrTriggerLevel level)
Sets trigger level of IRQ.
Parameters
intr The IRQ.
level The trigger level.
Examples:
test_uart/test_uart.c.
void ithIntrSetTriggerModeFiq (ITHIntr intr, ITHIntrTriggerMode mode)
Sets trigger mode of FIQ.
Parameters
intr The FIQ.
mode The trigger mode.
void ithIntrSetTriggerModeIrq (ITHIntr intr, ITHIntrTriggerMode mode)
Sets trigger mode of IRQ.
Parameters
intr The IRQ.
mode The trigger mode.
Examples:
test_uart/test_uart.c.
void ithIntrStats (void)
Print interrupt information.
void ithIntrSuspend (void)
Suspends interrupt module.