ITE SoC SDK: Linphone
Linphone
ITE DoorBell Indoor Modules
Functions
void LinphoneInit (void)
Initializes linphone module.
void LinphoneExit (void)
Exits linphone module.
int LinphoneGetVoiceLevel (void)
Gets the percentage of voice volume.
void LinphoneSetVoiceLevel (int level)
Sets the percentage of voice volume.
int LinphoneGetMicLevel (void)
Gets the percentage of MIC volume.
void LinphoneSetMicLevel (int level)
Sets the percentage of MIC volume.
void LinphonePlayRingSound (void)
Plays ring sound.
void LinphoneSetRingSound (char *file)
Sets the file path of ring sound.
int LinphoneGetRingLevel (void)
Gets the percentage of ring volume.
void LinphoneSetRingLevel (int level, bool active)
Sets the percentage of ring volume.
void LinphonePlayKeySound (void)
Plays key sound.
void LinphoneSetKeyLevel (int level)
Sets the percentage of key volume.
int LinphoneGetWarnLevel (void)
Gets the percentage of warn volume.
void LinphoneSetWarnLevel (int level)
Sets the percentage of warn volume.
void LinphonePlayWarnSound (void)
Plays warning sound.
void LinphoneCall (char *ip, bool video, bool earlyMedia)
Makes a call to the specified IP address.
void LinphoneWatchCamera (char *ip)
Watches camera of the specified IP address.
void LinphoneStopCamera (void)
Stop watching camera.
void LinphoneAnswer (int id)
Answers a call for the specified call ID.
void LinphoneMuteMic (void)
Mutes microphone.
void LinphoneUnMuteMic (void)
Un-mutes microphone.
void LinphoneTerminate (int id)
Terminates the specified call ID.
void LinphoneAddFriend (DeviceInfo *info, bool blacklist, char *comment)
Adds a contact.
void LinphoneDeleteFriend (char *addr)
Deletes a contact.
void LinphoneClearFriends (void)
Clears all contacts.
void LinphoneClearMissedLogs (void)
Clears all missed logs.
void LinphoneClearReceivedLogs (void)
Clears all received logs.
void LinphoneClearSentLogs (void)
Clears all sent logs.
void LinphoneDeleteCallLog (int refkey)
Deletes a calling log.
void LinphoneSetWindowID (void *widget)
Sets the window ID to display video.
void LinphonePlayVideoMessage (char *ip, int id)
Plays the video message on the control server.
void LinphoneCallDevices (DeviceInfo infoArray[], int count, bool video, bool earlyMedia)
Makes calls to the devices in the same time.
void LinphoneTerminateOthers (long id)
Terminates all calls except the specified call ID.
void LinphoneStopSound (void)
Stops playing sound.
void LinphoneEnableDoNotDisturb (void)
Enables do not disturb mode.
void LinphoneDisableDoNotDisturb (void)
Disables do not disturb mode.
int LinphoneCheckDoNotDisturb (void)
Checks the status of do not disturb mode.
bool LinphoneIsInDoNotDisturb (void)
Determines whether it is in do not disturb mode or not.
void LinphoneEnableBusy (void)
Enables busy mode.
void LinphoneDisableBusy (void)
Disables busy mode.
void LinphoneRedirect (char *ip)
Redirects current call to the specified IP address.
void LinphoneSnapshot (char *filepath)
Snapshots current video to the specified file path.
void LinphoneStartVoiceMemoRecord (char *filepath)
Starts a voice memo recording to the specified file path.
void LinphoneStopVoiceMemoRecord (void)
Stops the voice memo recording.
void LinphoneStartVoiceMemoPlay (char *filepath)
Starts playing a voice memo recording.
void LinphoneStopVoiceMemoPlay (void)
Stops playing the voice memo.
void LinphoneRegister (void)
Registers to SIP server.
void LinphoneStartVideoMemoRecord (char *filepath)
Starts a video memo recording to the specified file path.
void LinphoneStopVideoMemoRecord (void)
Stops the video memo recording.
void LinphoneStartVideoMemoPlay (char *filepath)
Starts playing a video memo recording.
void LinphoneStopVideoMemoPlay (void)
Stops playing the video memo.
Detailed Description
Function Documentation
void LinphoneAddFriend (DeviceInfo * info, bool blacklist, char * comment)
Adds a contact.
Parameters
info The device information of the contact.
blacklist Adds the contact to black list or not.
comment The comment of the contact.
Definition at line 347 of file doorbell_indoor/linphone.c.
References DeviceInfo::area, DeviceInfo::building, DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, LinphoneCastor3::friend_addr, LinphoneCastor3::friend_comment, LinphoneCastor3::friend_sip, DeviceInfo::ip, linphoneCastor3, lpInited, LinphoneCastor3::mq, PROMPT_MAX_LEN, DeviceInfo::room, DeviceInfo::type, and DeviceInfo::unit.
Referenced by PhoneContactsAddConfirmButtonOnPress(), and PhoneContactsModifyConfirmButtonOnPress().
void LinphoneAnswer (int id)
Answers a call for the specified call ID.
Parameters
id The call ID to answer.
Definition at line 295 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CalledAnswerButtonOnPress(), CalledOnTimer(), CallingAnswerButtonOnPress(), CallReceived(), and SceneRun().
void LinphoneCall (char * ip, bool video, bool earlyMedia)
Makes a call to the specified IP address.
Parameters
ip The specified IP address to call.
video Enables video feature.
earlyMedia Enables early media feature.
Definition at line 252 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
void LinphoneCallDevices (DeviceInfo infoArray[], int count, bool video, bool earlyMedia)
Makes calls to the devices in the same time.
Parameters
infoArray the array of DeviceInfo to make calls.
count The count of DeviceInfo in the infoArray.
video Enables video feature.
earlyMedia Enables early media feature.
Definition at line 498 of file doorbell_indoor/linphone.c.
Referenced by CallingCall().
int LinphoneCheckDoNotDisturb (void)
Checks the status of do not disturb mode.
Returns
0 for not changed; 1 for enabling; -1 for disabling.
Definition at line 575 of file doorbell_indoor/linphone.c.
References Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_mode, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, DONOT_DISTURB_TIME, LinphoneDisableDoNotDisturb(), LinphoneEnableDoNotDisturb(), lpInDoNotDisturb, lpInited, and theConfig.
Referenced by CheckDoNotDisturb().
void LinphoneClearFriends (void)
Clears all contacts.
Definition at line 379 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by PhoneContactsClearConfirmButtonOnPress().
void LinphoneClearMissedLogs (void)
Clears all missed logs.
Definition at line 390 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CallLogClearEntries().
void LinphoneClearReceivedLogs (void)
Clears all received logs.
Definition at line 401 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CallLogClearEntries().
void LinphoneClearSentLogs (void)
Clears all sent logs.
Definition at line 412 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CallLogClearEntries().
void LinphoneDeleteCallLog (int refkey)
Deletes a calling log.
Parameters
refkey The reference key of the calling log to delete.
Definition at line 423 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CallLogDeleteEntry().
void LinphoneDeleteFriend (char * addr)
Deletes a contact.
Parameters
addr The address of the contact to delete.
Definition at line 367 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by PhoneContactsDeleteConfirmButtonOnPress(), and PhoneContactsModifyConfirmButtonOnPress().
void LinphoneDisableBusy (void)
Disables busy mode.
Definition at line 655 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by MainVoiceMemoOnLeave(), MainVoiceMemoOnTimer(), and MainVoiceMemoStopRecordButtonOnPress().
void LinphoneDisableDoNotDisturb (void)
Disables do not disturb mode.
Definition at line 562 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInDoNotDisturb, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by LinphoneCheckDoNotDisturb(), SettingPhoneDisturbSaveButtonOnPress(), ToggleMute(), and UpdateIndicators().
void LinphoneEnableBusy (void)
Enables busy mode.
Definition at line 644 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by MainVoiceMemoRecordButtonOnPress().
void LinphoneEnableDoNotDisturb (void)
Enables do not disturb mode.
Definition at line 549 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInDoNotDisturb, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by LinphoneCheckDoNotDisturb(), SettingPhoneDisturbSaveButtonOnPress(), ToggleMute(), and UpdateIndicators().
void LinphoneExit (void)
Exits linphone module.
Definition at line 103 of file doorbell_indoor/linphone.c.
Referenced by SDL_main().
int LinphoneGetMicLevel (void)
Gets the percentage of MIC volume.
Returns
The percentage of MIC volume, range is 0~100.
Definition at line 139 of file doorbell_indoor/linphone.c.
Referenced by ahc_echo(), AudioRecordStartRecord(), create_response(), SettingPhoneVoiceMicVolDownButtonOnPress(), SettingPhoneVoiceMicVolUpButtonOnPress(), SettingPhoneVoiceOnEnter(), SettingPhoneVoiceOnLeave(), SettingPhoneVoiceSaveButtonOnPress(), and UpgradeGetDeviceInfo().
int LinphoneGetRingLevel (void)
Gets the percentage of ring volume.
Returns
The percentage of ring volume, range is 0~100.
Definition at line 169 of file doorbell_indoor/linphone.c.
Referenced by ahc_echo(), AudioRecordStartRecord(), CalledOnEnter(), CalledOnLeave(), CalledVolDownButtonOnPress(), CalledVolUpButtonOnPress(), CallingOnEnter(), CallingOnLeave(), CallingVolDownButtonOnPress(), CallingVolUpButtonOnPress(), create_response(), SettingPhoneAudioOnEnter(), SettingPhoneAudioOnLeave(), SettingPhoneAudioRingVolDownButtonOnPress(), SettingPhoneAudioRingVolUpButtonOnPress(), SettingPhoneAudioSaveButtonOnPress(), and UpgradeGetDeviceInfo().
int LinphoneGetVoiceLevel (void)
Gets the percentage of voice volume.
Returns
The percentage of voice volume, range is 0~100.
Definition at line 121 of file doorbell_indoor/linphone.c.
Referenced by ahc_echo(), CalledConnectedOnCustom(), CalledOnEnter(), CalledOnLeave(), CalledVolDownButtonOnPress(), CalledVolUpButtonOnPress(), CallingConnectedOnCustom(), CallingOnEnter(), CallingOnLeave(), CallingVolDownButtonOnPress(), CallingVolUpButtonOnPress(), create_response(), SettingPhoneVoiceOnEnter(), SettingPhoneVoiceOnLeave(), SettingPhoneVoiceSaveButtonOnPress(), SettingPhoneVoiceVolDownButtonOnPress(), SettingPhoneVoiceVolUpButtonOnPress(), and UpgradeGetDeviceInfo().
int LinphoneGetWarnLevel (void)
Gets the percentage of warn volume.
Returns
The percentage of warn volume, range is 0~100.
Definition at line 225 of file doorbell_indoor/linphone.c.
References linphoneCastor3, and LinphoneCastor3::warn_level.
Referenced by AudioRecordStartRecord().
void LinphoneInit (void)
Initializes linphone module.
Definition at line 80 of file doorbell_indoor/linphone.c.
Referenced by SDL_main().
bool LinphoneIsInDoNotDisturb (void)
Determines whether it is in do not disturb mode or not.
Returns
true for it is in do not disturb mode, false otherwise.
Definition at line 639 of file doorbell_indoor/linphone.c.
References lpInDoNotDisturb.
Referenced by CallReceived(), MainVoiceMemoOnLeave(), MainVoiceMemoOnTimer(), MainVoiceMemoRecordButtonOnPress(), MainVoiceMemoStopRecordButtonOnPress(), and ToggleMute().
void LinphoneMuteMic (void)
Mutes microphone.
Definition at line 310 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
void LinphonePlayKeySound (void)
Plays key sound.
Definition at line 213 of file doorbell_indoor/linphone.c.
Referenced by SceneRun().
void LinphonePlayRingSound (void)
Plays ring sound.
Definition at line 157 of file doorbell_indoor/linphone.c.
Referenced by SettingPhoneAudioPlayRingSound().
void LinphonePlayVideoMessage (char * ip, int id)
Plays the video message on the control server.
Parameters
ip The IP address of control server.
id The ID of video message to play.
Definition at line 479 of file doorbell_indoor/linphone.c.
References linphoneCastor3, LinphoneInitVideoMessageUri(), lpInited, lpVideoMsgUri, LinphoneCastor3::mq, NetworkServerIsReady(), PROMPT_MAX_LEN, and LinphoneCastor3::video_msg_uri.
Referenced by MessagePhotoViewOnEnter().
void LinphonePlayWarnSound (void)
Plays warning sound.
Definition at line 239 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, lpWarnSoundPlaying, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CheckGuard().
void LinphoneRedirect (char * ip)
Redirects current call to the specified IP address.
Parameters
ip The IP address to redirect to.
Definition at line 666 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by SceneCallOnDoNotDisturb().
void LinphoneRegister (void)
Registers to SIP server.
The SIP server address is the center address. The SIP ID is the device address like 01-01-01-01-01-01.
Definition at line 742 of file doorbell_indoor/linphone.c.
void LinphoneSetKeyLevel (int level)
Sets the percentage of key volume.
Parameters
level The percentage of key volume, range is 0~100.
Definition at line 204 of file doorbell_indoor/linphone.c.
Referenced by create_response(), SettingPhoneAudioKeypadSoundVolDownButtonOnPress(), and SettingPhoneAudioKeypadSoundVolUpButtonOnPress().
void LinphoneSetMicLevel (int level)
Sets the percentage of MIC volume.
Parameters
level The percentage of MIC volume, range is 0~100.
Definition at line 144 of file doorbell_indoor/linphone.c.
Referenced by ahc_echo(), AudioRecordStartRecord(), AudioRecordStopRecord(), create_response(), SettingPhoneVoiceCancelButtonOnPress(), SettingPhoneVoiceMicVolDownButtonOnPress(), SettingPhoneVoiceMicVolUpButtonOnPress(), and SettingPhoneVoiceOnLeave().
void LinphoneSetRingLevel (int level, bool active)
Sets the percentage of ring volume.
Parameters
level The percentage of ring volume, range is 0~100.
active Active or not.
Definition at line 174 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, PROMPT_MAX_LEN, and LinphoneCastor3::ring_level.
Referenced by ahc_echo(), AudioRecordStartRecord(), AudioRecordStopRecord(), CalledVolDownButtonOnPress(), CalledVolUpButtonOnPress(), CallingVolDownButtonOnPress(), CallingVolUpButtonOnPress(), create_response(), SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnLeave(), SettingPhoneAudioRingVolDownButtonOnPress(), and SettingPhoneAudioRingVolUpButtonOnPress().
void LinphoneSetRingSound (char * file)
Sets the file path of ring sound.
Must be WAV file.
Parameters
file the file path of ring sound.
Definition at line 190 of file doorbell_indoor/linphone.c.
Referenced by create_response(), SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnLeave(), and SettingPhoneAudioRingRadioBoxOnPress().
void LinphoneSetVoiceLevel (int level)
Sets the percentage of voice volume.
Parameters
level The percentage of voice volume, range is 0~100.
Definition at line 126 of file doorbell_indoor/linphone.c.
Referenced by ahc_echo(), CalledVolDownButtonOnPress(), CalledVolUpButtonOnPress(), CallingVolDownButtonOnPress(), CallingVolUpButtonOnPress(), create_response(), SettingPhoneVoiceCancelButtonOnPress(), SettingPhoneVoiceOnLeave(), SettingPhoneVoiceVolDownButtonOnPress(), and SettingPhoneVoiceVolUpButtonOnPress().
void LinphoneSetWarnLevel (int level)
Sets the percentage of warn volume.
Parameters
level The percentage of warn volume, range is 0~100.
Definition at line 230 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, theConfig, LinphoneCastor3::warn_level, and Config::warnlevel.
Referenced by SettingEngineerMiscGuardWarnVolDownButtonOnPress(), and SettingEngineerMiscGuardWarnVolUpButtonOnPress().
void LinphoneSetWindowID (void * widget)
Sets the window ID to display video.
Parameters
widget The widget pointer to display video.
Definition at line 434 of file doorbell_indoor/linphone.c.
References ituWidgetGetGlobalPosition, ituWidgetGetHeight, ituWidgetGetWidth, itv_set_video_window(), linphoneCastor3, lpInited, LinphoneCastor3::mq, PROMPT_MAX_LEN, and font::x.
Referenced by CalledOnEnter(), CalledWaitingConfirmButtonOnPress(), CalledWaitingConfirmButtonOnSimulatePressing(), CallingOnEnter(), CameraButtonOnPress(), CameraOnEnter(), CameraOutdoorButtonOnPress(), CameraOutdoorOnEnter(), CameraViewSetCameraBackgroundWindowID(), MessagePhotoViewOnEnter(), MessageRecordViewOnEnter(), and VideoRecordOnEnter().
void LinphoneSnapshot (char * filepath)
Snapshots current video to the specified file path.
Parameters
filepath The file path to save the snapshot.
Definition at line 679 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CaptureSnapshotStart().
void LinphoneStartVideoMemoPlay (char * filepath)
Starts playing a video memo recording.
Parameters
filepath The file path of the video memo to play.
Definition at line 789 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by VideoRecordStartPlay().
void LinphoneStartVideoMemoRecord (char * filepath)
Starts a video memo recording to the specified file path.
Parameters
filepath The file path to save the video memo.
Definition at line 766 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by VideoRecordStartRecord().
void LinphoneStartVoiceMemoPlay (char * filepath)
Starts playing a voice memo recording.
Parameters
filepath The file path of the voice memo to play.
Definition at line 719 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by AudioRecordStartPlay().
void LinphoneStartVoiceMemoRecord (char * filepath)
Starts a voice memo recording to the specified file path.
Parameters
filepath The file path to save the voice memo.
Definition at line 692 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by AudioRecordStartRecord().
void LinphoneStopCamera (void)
Stop watching camera.
Definition at line 284 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CameraListOnSelection(), CameraOnLeave(), CameraOnTimer(), CameraOutdoorOnLeave(), CameraOutdoorOnTimer(), and CameraViewOnLeave().
void LinphoneStopSound (void)
Stops playing sound.
Definition at line 537 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, lpWarnSoundPlaying, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CheckGuard().
void LinphoneStopVideoMemoPlay (void)
Stops playing the video memo.
Definition at line 801 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by VideoRecordStopPlay().
void LinphoneStopVideoMemoRecord (void)
Stops the video memo recording.
Definition at line 778 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by VideoRecordStopRecord().
void LinphoneStopVoiceMemoPlay (void)
Stops playing the voice memo.
Definition at line 731 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by AudioRecordStopPlay().
void LinphoneStopVoiceMemoRecord (void)
Stops the voice memo recording.
Definition at line 704 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, PROMPT_MAX_LEN, and LinphoneCastor3::sync.
Referenced by AudioRecordStopRecord().
void LinphoneTerminate (int id)
Terminates the specified call ID.
Parameters
id The call ID to terminate.
Definition at line 332 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CalledAnswerButtonOnPress(), CalledHangUpButtonOnPress(), CalledOnTimer(), CallingAnswerButtonOnPress(), CallingHangUpButtonOnPress(), CallingOnLeave(), CallingOnTimer(), MessagePhotoViewOnLeave(), SceneRun(), VideoRecordHangUpButtonOnPress(), and VideoRecordOnTimer().
void LinphoneTerminateOthers (long id)
Terminates all calls except the specified call ID.
Parameters
id Only the specified ID don't to terminate.
Definition at line 526 of file doorbell_indoor/linphone.c.
Referenced by CallConnected(), CallEnd(), and CallError().
void LinphoneUnMuteMic (void)
Un-mutes microphone.
void LinphoneWatchCamera (char * ip)
Watches camera of the specified IP address.
Parameters
ip The specified IP address to watch.
Definition at line 271 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by CameraOutdoorOnEnter(), and CameraWatch().