ITE SoC SDK: Address Book
Address Book
ITE DoorBell Indoor Modules
Macros
#define MAX_OUTDOOR_COUNT 10
Maximum Door Camera count.
#define MAX_MANAGER_COUNT 10
Maximum Administrator Unit count.
#define MAX_CAMERA_COUNT 99
Maximum camera device count.
#define MAX_IPCAMERA_COUNT 9
Maximum ip camera count.
Functions
void AddressBookInit (void)
Initializes address book module.
void AddressBookExit (void)
Exits address book module.
char * AddressBookGetVersion (void)
Gets version of addressbook.
void AddressBookGetCenterInfo (DeviceInfo *info)
Gets device information of control server from addressbook.
void AddressBookGetDeviceInfo (DeviceInfo *info, char *ip)
Gets device information from addressbook by IP address.
void AddressBookGetEntranceInfo (DeviceInfo *info, DeviceInfo *deviceInfo)
Gets device information of lobby phone from addressbook.
void AddressBookGetOutdoorInfo (DeviceInfo *info, DeviceInfo *deviceInfo)
Gets device information of door camera from addressbook.
char * AddressBookGetDeviceIP (char *area, char *building, char *unit, char *floor, char *room, char *ext)
Gets IP address by address information from addressbook.
int AddressBookGetDeviceInfoArray (DeviceInfo infoArray[], int count, char *area, char *building, char *unit, char *floor, char *room)
Gets array of indoor phones by address information from addressbook.
int AddressBookGetCameraInfoArray (DeviceInfo infoArray[], int count, DeviceInfo *devinfo)
Gets array of devices with camera from addressbook.
int AddressBookGetLobbyInfoArray (DeviceInfo infoArray[], int count)
Gets array of lobby devices from addressbook.
int AddressBookGetManagerInfoArray (DeviceInfo infoArray[], int count)
Gets array of administrator units from addressbook.
int AddressBookGetIPCameraInfoArray (DeviceInfo infoArray[], int count)
Gets array of ip camera from addressbook.
char * AddressBookGetGateway (DeviceInfo *info)
Gets IP address of gateway from addressbook.
char * AddressBookGetNetMask (DeviceInfo *info)
Gets netmask from addressbook.
bool AddressBookIsOutdoorExist (char *area, char *building, char *unit, char *floor, char *room, char *ext)
Is the outdoor address exist in the addressbook.
int AddressBookGetOutdoorInfoArray (DeviceInfo infoArray[], int count, char *area, char *building, char *unit, char *floor, char *room)
Gets array of door cameras by address information from addressbook.
Detailed Description
Macro Definition Documentation
#define MAX_CAMERA_COUNT 99
Maximum camera device count.
Definition at line 104 of file doorbell_indoor/doorbell.h.
Referenced by CameraListBoxOnLoad(), and PhoneLobbyListBoxOnLoad().
#define MAX_IPCAMERA_COUNT 9
Maximum ip camera count.
Definition at line 109 of file doorbell_indoor/doorbell.h.
Referenced by CalledSourceListBoxOnLoad().
#define MAX_MANAGER_COUNT 10
Maximum Administrator Unit count.
Definition at line 99 of file doorbell_indoor/doorbell.h.
Referenced by CallingCallManager(), EventUploadTask(), NetworkSntpUpdate(), PhoneManagerListBoxOnLoad(), and ResetEthernet().
#define MAX_OUTDOOR_COUNT 10
Maximum Door Camera count.
Definition at line 94 of file doorbell_indoor/doorbell.h.
Referenced by SettingOutdoorMainOnEnter().
Function Documentation
void AddressBookExit (void)
Exits address book module.
Definition at line 444 of file doorbell_indoor/addressbook.c.
int AddressBookGetCameraInfoArray (DeviceInfo infoArray[], int count, DeviceInfo * devinfo)
Gets array of devices with camera from addressbook.
Parameters
infoArray The array of DeviceInfo to fill in.
count Maximum count of DeviceInfo in array.
info The pointer to the DeviceInfo of this device.
Returns
the actual count of filled DeviceInfo in array.
Definition at line 617 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DeviceInfo::area, DeviceInfo::building, DEVICE_ENTRANCE, DEVICE_INTERCOM, DEVICE_IPCAM, DEVICE_OUTDOOR, DeviceInfo::floor, GetDeviceInfo(), i, j, ABDevice::room, DeviceInfo::room, ABDevice::type, and DeviceInfo::unit.
Referenced by CameraListBoxOnLoad(), and PhoneLobbyListBoxOnLoad().
void AddressBookGetCenterInfo (DeviceInfo * info)
Gets device information of control server from addressbook.
Parameters
info The pointer to retrieve the DeviceInfo of control server.
Definition at line 462 of file doorbell_indoor/addressbook.c.
void AddressBookGetDeviceInfo (DeviceInfo * info, char * ip)
Gets device information from addressbook by IP address.
Parameters
info The pointer to retrieve the DeviceInfo.
ip The IP address of device.
Definition at line 480 of file doorbell_indoor/addressbook.c.
int AddressBookGetDeviceInfoArray (DeviceInfo infoArray[], int count, char * area, char * building, char * unit, char * floor, char * room)
Gets array of indoor phones by address information from addressbook.
Parameters
infoArray The array of DeviceInfo to fill in.
count Maximum count of DeviceInfo in array.
area The area code of address.
building The building code of address.
unit The unit code of address.
floor The floor code of address.
room The room code of address.
Returns
the actual count of filled DeviceInfo in array.
Definition at line 587 of file doorbell_indoor/addressbook.c.
char* AddressBookGetDeviceIP (char * area, char * building, char * unit, char * floor, char * room, char * ext)
Gets IP address by address information from addressbook.
Parameters
area The area code of address.
building The building code of address.
unit The unit code of address.
floor The floor code of address.
room The room code of address.
ext The ext code of address. Can be NULL if not exist.
Returns
the IP address string. Remember to free it after used to avoid memory leak.
Definition at line 545 of file doorbell_indoor/addressbook.c.
void AddressBookGetEntranceInfo (DeviceInfo * info, DeviceInfo * deviceInfo)
Gets device information of lobby phone from addressbook.
Parameters
info The pointer to retrieve the DeviceInfo of lobby phone.
deviceInfo The DeviceInfo of indoor phone which belong to the lobby phone.
Definition at line 499 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DeviceInfo::area, DeviceInfo::building, DEVICE_ENTRANCE, GetDeviceInfo(), i, ABDevice::room, ABDevice::type, and DeviceInfo::unit.
Referenced by DeviceInfoInit(), and DeviceInfoInitByDhcp().
char* AddressBookGetGateway (DeviceInfo * info)
Gets IP address of gateway from addressbook.
Parameters
info The pointer to the DeviceInfo of this device.
Returns
the IP address string of gateway. Remember to free it after used to avoid memory leak.
Definition at line 722 of file doorbell_indoor/addressbook.c.
int AddressBookGetIPCameraInfoArray (DeviceInfo infoArray[], int count)
Gets array of ip camera from addressbook.
Parameters
infoArray The array of DeviceInfo to fill in.
count Maximum count of DeviceInfo in array.
Returns
the actual count of filled DeviceInfo in array.
Definition at line 698 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DEVICE_IPCAM, GetDeviceInfo(), i, j, and ABDevice::type.
Referenced by CalledSourceListBoxOnLoad().
int AddressBookGetLobbyInfoArray (DeviceInfo infoArray[], int count)
Gets array of lobby devices from addressbook.
Parameters
infoArray The array of DeviceInfo to fill in.
count Maximum count of DeviceInfo in array.
Returns
the actual count of filled DeviceInfo in array.
Definition at line 650 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DEVICE_ENTRANCE, DEVICE_OUTDOOR, GetDeviceInfo(), i, j, and ABDevice::type.
int AddressBookGetManagerInfoArray (DeviceInfo infoArray[], int count)
Gets array of administrator units from addressbook.
Parameters
infoArray The array of DeviceInfo to fill in.
count Maximum count of DeviceInfo in array.
Returns
the actual count of filled DeviceInfo in array.
Definition at line 674 of file doorbell_indoor/addressbook.c.
char* AddressBookGetNetMask (DeviceInfo * info)
Gets netmask from addressbook.
Parameters
info The pointer to the DeviceInfo of this device.
Returns
the netmask string. Remember to free it after used to avoid memory leak.
Definition at line 730 of file doorbell_indoor/addressbook.c.
void AddressBookGetOutdoorInfo (DeviceInfo * info, DeviceInfo * deviceInfo)
Gets device information of door camera from addressbook.
Parameters
info The pointer to retrieve the DeviceInfo of door camera.
deviceInfo The DeviceInfo of indoor phone which the door camera belong to.
Definition at line 521 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DeviceInfo::area, DeviceInfo::building, DEVICE_OUTDOOR, DeviceInfo::floor, GetDeviceInfo(), i, ABDevice::room, DeviceInfo::room, ABDevice::type, and DeviceInfo::unit.
Referenced by DeviceInfoInit(), and DeviceInfoInitByDhcp().
int AddressBookGetOutdoorInfoArray (DeviceInfo infoArray[], int count, char * area, char * building, char * unit, char * floor, char * room)
Gets array of door cameras by address information from addressbook.
Parameters
infoArray The array of DeviceInfo to fill in.
count Maximum count of DeviceInfo in array.
area The area code of address.
building The building code of address.
unit The unit code of address.
floor The floor code of address.
room The room code of address.
Returns
the actual count of filled DeviceInfo in array.
Definition at line 762 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DEVICE_OUTDOOR, GetDeviceInfo(), i, j, ABDevice::room, and ABDevice::type.
Referenced by SettingOutdoorMainOnEnter().
char* AddressBookGetVersion (void)
Gets version of addressbook.
Returns
the version string. Remember to free it after used to avoid memory leak.
Definition at line 454 of file doorbell_indoor/addressbook.c.
void AddressBookInit (void)
Initializes address book module.
Definition at line 223 of file doorbell_indoor/addressbook.c.
bool AddressBookIsOutdoorExist (char * area, char * building, char * unit, char * floor, char * room, char * ext)
Is the outdoor address exist in the addressbook.
Parameters
area The area code of address.
building The building code of address.
unit The unit code of address.
floor The floor code of address.
room The room code of address.
ext The ext code of address.
Returns
true if exist, false otherwise.
Definition at line 738 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DEVICE_OUTDOOR, i, j, ABDevice::room, and ABDevice::type.
Referenced by SettingEngineerMiscTwiceSettingButtonOnPress().