ITE SoC SDK: Guard
Guard
ITE DoorBell Indoor Modules
Data Structures
struct GuardLog
Guard logging definition.
Enumerations
enum GuardMode { GUARD_NONE, GUARD_INDOOR, GUARD_OUTDOOR, GUARD_SLEEP }
Guard mode definition.
enum GuardSensor {
GUARD_EMERGENCY, GUARD_INFRARED, GUARD_DOOR, GUARD_WINDOW,
GUARD_SMOKE, GUARD_GAS, GUARD_AREA, GUARD_ROB,
GUARD_SENSOR_COUNT, GUARD_EMERGENCY, GUARD_SENSOR_COUNT
}
Guard sensors definition.
enum GuardStatus {
GUARD_ENABLE, GUARD_DISABLE, GUARD_ALARM, GUARD_UNALARM,
GUARD_ENABLE, GUARD_DISABLE, GUARD_ALARM, GUARD_UNALARM
}
Guard status definition.
enum GuardType {
GUARD_TYPE_EMERGENCY, GUARD_TYPE_INFRARED, GUARD_TYPE_DOOR, GUARD_TYPE_WINDOW,
GUARD_TYPE_SMOKE, GUARD_TYPE_GAS, GUARD_TYPE_AREA, GUARD_TYPE_ROB,
GUARD_TYPE_OPENDOOR
}
Guard type definition.
enum GuardState { GUARD_UNHANDLED, GUARD_HANDLED }
Guard state definition.
Functions
void GuardInit (void)
Initializes guard module.
void GuardExit (void)
Exits guard module.
void GuardSetMode (GuardMode mode)
Sets guard mode.
int GuardCheck (void)
Checks guard events.
GuardStatus GuardGetSensorStatus (GuardSensor sensor)
Gets the status of the specified sensor.
unsigned long GuardGetSensorTime (GuardSensor sensor)
Gets the last active time of the specified sensor.
int GuardGetLogCount (void)
Gets total count of guard logging.
GuardLog * GuardGetLog (int index)
Gets the guard logging entry by the specified index.
void GuardDeleteLog (int index)
Deletes the guard logging entry by the specified index.
void GuardClearLog (void)
Clears all the guard logging entries.
bool GuardIsAlarming (void)
Guard is alarming or not.
void GuardSetAlarming (bool alarming)
Sets the guard alarming status.
void GuardReceiveSyncLog (char *xml, int size)
Receives the XML of guard sync log.
Detailed Description
Enumeration Type Documentation
enum GuardMode
Guard mode definition.
Enumerator
GUARD_NONE
Disabling guard mode.
GUARD_INDOOR
Indoor guard mode.
GUARD_OUTDOOR
Outdoor guard mode.
GUARD_SLEEP
Sleep guard mode.
Definition at line 962 of file doorbell_indoor/doorbell.h.
enum GuardSensor
Guard sensors definition.
Enumerator
GUARD_EMERGENCY
Emergency sensor.
GUARD_INFRARED
Infrared sensor.
GUARD_DOOR
Door sensor.
GUARD_WINDOW
Window sensor.
GUARD_SMOKE
Smoke sensor.
GUARD_GAS
Gas sensor.
GUARD_AREA
Area sensor.
GUARD_ROB
Rob sensor.
GUARD_SENSOR_COUNT
Total sensor count.
GUARD_EMERGENCY
Emergency sensor.
GUARD_SENSOR_COUNT
Total sensor count.
Definition at line 973 of file doorbell_indoor/doorbell.h.
enum GuardState
Guard state definition.
Enumerator
GUARD_UNHANDLED
Guard event is unhandled.
GUARD_HANDLED
Guard event is handled.
Definition at line 1018 of file doorbell_indoor/doorbell.h.
enum GuardStatus
Guard status definition.
Enumerator
GUARD_ENABLE
Guard is enabled.
GUARD_DISABLE
Guard is disabled.
GUARD_ALARM
Guard is alarming.
GUARD_UNALARM
Guard is un-alarmed.
GUARD_ENABLE
Guard is enabled.
GUARD_DISABLE
Guard is disabled.
GUARD_ALARM
Guard is alarming.
GUARD_UNALARM
Guard is un-alarmed.
Definition at line 990 of file doorbell_indoor/doorbell.h.
enum GuardType
Guard type definition.
Enumerator
GUARD_TYPE_EMERGENCY
Emergency alarm.
GUARD_TYPE_INFRARED
Infrared alarm.
GUARD_TYPE_DOOR
Door alarm.
GUARD_TYPE_WINDOW
Window alarm.
GUARD_TYPE_SMOKE
Smoke alarm.
GUARD_TYPE_GAS
Gas alarm.
GUARD_TYPE_AREA
Area alarm.
GUARD_TYPE_ROB
Rob alarm.
GUARD_TYPE_OPENDOOR
Open door alarm.
Definition at line 1001 of file doorbell_indoor/doorbell.h.
Function Documentation
int GuardCheck (void)
Checks guard events.
Returns
0 for no event; 1 for events need to be silent; -1 for events need to be alarming.
Definition at line 295 of file guard.c.
Referenced by CheckGuard().
void GuardClearLog (void)
Clears all the guard logging entries.
Definition at line 497 of file guard.c.
References guardLogCount.
Referenced by GuardLogClearConfirmOnPress().
void GuardDeleteLog (int index)
Deletes the guard logging entry by the specified index.
Parameters
index The index to delete logging entry.
Definition at line 472 of file guard.c.
References guardLogCount, guardLogMutex, i, and MAX_GUARD_LOG_COUNT.
Referenced by GuardLogDeleteConfirmOnPress(), GuardWriteLog(), and GuardWriteSyncLog().
void GuardExit (void)
Exits guard module.
Definition at line 250 of file guard.c.
References guardLogMutex.
Referenced by SDL_main().
GuardLog* GuardGetLog (int index)
Gets the guard logging entry by the specified index.
Parameters
index The index to get logging entry.
Returns
The guard logging entry.
Definition at line 458 of file guard.c.
References guardLogCount, i, and MAX_GUARD_LOG_COUNT.
Referenced by GuardLogSensorListBoxOnLoad(), GuardLogTimeListBoxOnLoad(), and GuardLogTypeListBoxOnLoad().
int GuardGetLogCount (void)
Gets total count of guard logging.
Returns
The total count.
Definition at line 453 of file guard.c.
References guardLogCount.
Referenced by GuardLogSensorListBoxOnLoad(), GuardLogTimeListBoxOnLoad(), and GuardLogTypeListBoxOnLoad().
GuardStatus GuardGetSensorStatus (GuardSensor sensor)
Gets the status of the specified sensor.
Parameters
sensor The sensor to get status.
Returns
The status of sensor.
Definition at line 436 of file guard.c.
References GuardSensorStatus::alarming, GuardSensorStatus::enabled, GUARD_ALARM, GUARD_DISABLE, and GUARD_ENABLE.
Referenced by create_response(), GuardCheckStatusListBoxOnLoad(), and GuardStatusTypeListBoxOnLoad().
unsigned long GuardGetSensorTime (GuardSensor sensor)
Gets the last active time of the specified sensor.
Parameters
sensor The sensor to get time.
Returns
The timestamp of sensor.
Definition at line 448 of file guard.c.
References GuardSensorStatus::time.
Referenced by GuardStatusTimeListBoxOnLoad().
void GuardInit (void)
Initializes guard module.
Definition at line 200 of file guard.c.
Referenced by SDL_main().
bool GuardIsAlarming (void)
Guard is alarming or not.
Returns
The guard is alarming or not.
Definition at line 502 of file guard.c.
References guardAlarming.
Referenced by CheckGuard(), GuardModeIndoorRadioBoxOnPress(), GuardModeOnEnter(), GuardModeOutdoorRadioBoxOnPress(), GuardModeSleepRadioBoxOnPress(), SceneContinuePlayGuardAlarm(), SettingPhoneDisturbSaveButtonOnPress(), and ToggleMute().
void GuardReceiveSyncLog (char * xml, int size)
Receives the XML of guard sync log.
Parameters
xml The guard log XML to parse.
size The size of XML string.
Definition at line 512 of file guard.c.
References DeviceInfo::area, DeviceInfo::building, DeviceInfo::ext, DeviceInfo::floor, GUARD_TYPE_AREA, GUARD_TYPE_DOOR, GUARD_TYPE_EMERGENCY, GUARD_TYPE_GAS, GUARD_TYPE_INFRARED, GUARD_TYPE_OPENDOOR, GUARD_TYPE_ROB, GUARD_TYPE_SMOKE, GUARD_TYPE_WINDOW, GuardWriteSyncLog(), i, DeviceInfo::room, GuardLog::state, theDeviceInfo, GuardLog::timestamp, GuardLog::type, and DeviceInfo::unit.
Referenced by create_response().
void GuardSetAlarming (bool alarming)
Sets the guard alarming status.
Parameters
alarming The alarming status.
Definition at line 507 of file guard.c.
References guardAlarming.
Referenced by CheckGuard().
void GuardSetMode (GuardMode mode)
Sets guard mode.
Parameters
mode The mode to set.
Definition at line 255 of file guard.c.
References GUARD_INDOOR, Config::guard_indoor_sensors, Config::guard_mode, GUARD_OUTDOOR, Config::guard_outdoor_sensors, GUARD_SENSOR_COUNT, GUARD_SLEEP, Config::guard_sleep_sensors, GuardDisableSensor(), GuardEnableSensor(), guardSensors, i, and theConfig.
Referenced by create_response(), GuardInit(), GuardModeIndoorRadioBoxOnPress(), GuardModeOutdoorRadioBoxOnPress(), GuardModeSleepRadioBoxOnPress(), GuardModeStopKeypadConfirmButtonOnPress(), and GuardUserSettingSaveButtonOnPress().