ITE SoC SDK: Guard
Guard
ITE DoorBell Outdoor Modules
Enumerations
enum GuardSensor {
GUARD_EMERGENCY, GUARD_INFRARED, GUARD_DOOR, GUARD_WINDOW,
GUARD_SMOKE, GUARD_GAS, GUARD_AREA, GUARD_ROB,
GUARD_SENSOR_COUNT, GUARD_EMERGENCY, GUARD_SENSOR_COUNT
}
Guard sensors definition.
enum GuardStatus {
GUARD_ENABLE, GUARD_DISABLE, GUARD_ALARM, GUARD_UNALARM,
GUARD_ENABLE, GUARD_DISABLE, GUARD_ALARM, GUARD_UNALARM
}
Guard status definition.
Functions
void GuardInit (void)
Initializes guard module.
int GuardCheck (void)
Checks guard events.
Detailed Description
Enumeration Type Documentation
enum GuardSensor
Guard sensors definition.
Enumerator
GUARD_EMERGENCY
Emergency sensor.
GUARD_INFRARED
Infrared sensor.
GUARD_DOOR
Door sensor.
GUARD_WINDOW
Window sensor.
GUARD_SMOKE
Smoke sensor.
GUARD_GAS
Gas sensor.
GUARD_AREA
Area sensor.
GUARD_ROB
Rob sensor.
GUARD_SENSOR_COUNT
Total sensor count.
GUARD_EMERGENCY
Emergency sensor.
GUARD_SENSOR_COUNT
Total sensor count.
Definition at line 292 of file doorbell_outdoor/doorbell.h.
enum GuardStatus
Guard status definition.
Enumerator
GUARD_ENABLE
Guard is enabled.
GUARD_DISABLE
Guard is disabled.
GUARD_ALARM
Guard is alarming.
GUARD_UNALARM
Guard is un-alarmed.
GUARD_ENABLE
Guard is enabled.
GUARD_DISABLE
Guard is disabled.
GUARD_ALARM
Guard is alarming.
GUARD_UNALARM
Guard is un-alarmed.
Definition at line 302 of file doorbell_outdoor/doorbell.h.
Function Documentation
int GuardCheck (void)
Checks guard events.
Returns
0 for no event; -1 for events need to be alarming.
0 for no event; 1 for events need to be silent; -1 for events need to be alarming.
Definition at line 295 of file guard.c.
References GuardSensorStatus::alarmDelay, GuardSensorStatus::alarming, EventWriteGuardLog(), GUARD_ALARM, GUARD_ALARM_DELAY, GUARD_INDOOR, Config::guard_indoor_sensors, Config::guard_mode, GUARD_OUTDOOR, Config::guard_outdoor_sensors, GUARD_ROB, GUARD_SENSOR_COUNT, Config::guard_sensor_initvalues, GUARD_SLEEP, Config::guard_sleep_sensors, guardSensorLastValue, guardSensors, GuardWriteLog(), i, theConfig, and GuardSensorStatus::time.
void GuardInit (void)
Initializes guard module.
Definition at line 200 of file guard.c.
References GuardSensorStatus::alarmDelay, GuardSensorStatus::alarming, GuardSensorStatus::enabled, Config::guard_mode, GUARD_SENSOR_COUNT, guardAlarming, guardLogCount, guardLogMutex, guardSensorLastValue, GuardSetMode(), i, IOEXPANDER_0, ithGpioGet(), itpIOExpanderGet(), theConfig, and GuardSensorStatus::time.