ITE SoC SDK: Scene
Scene
ITE UI Library
Data Structures
struct ITUActionFunction
Action function definition.
struct ITUCommand
Command definition.
struct ITUVariable
Variable definition.
struct ITUScene
Scene manager definition.
Typedefs
typedef bool(* ITUActionFunc)(ITUWidget *widget, char *param)
Action callback function definition.
typedef void(* ITUCommandFunc)(int arg)
Command function definition.
Functions
void ituSceneInit (ITUScene *scene, ITUWidget *root)
Initializes scene.
void ituSceneExit (ITUScene *scene)
Exits scene.
int ituSceneLoadFile (ITUScene *scene, const char *filename)
Loads scene from a file.
int ituSceneLoadArray (ITUScene *scene, const char *array, int size)
Loads scene from an array.
int ituSceneLoadFileCore (ITUScene *scene, const char *filename)
Loads scene from a file without start.
void ituSceneStart (ITUScene *scene)
Starts scene.
bool ituSceneUpdate (ITUScene *scene, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the scene to notify all the visible widgets by specified event.
void ituSceneDraw (ITUScene *scene, ITUSurface *dest)
Draws the scene to the specified surface.
void ituScenePreDraw (ITUScene *scene, ITUSurface *dest)
Pre-draws the scene to the specified surface.
void ituSceneSetRotation (ITUScene *scene, ITURotation rot, int screenWidth, int screenHeight)
Rotates the scene.
void ituSceneSetFunctionTable (ITUScene *scene, ITUActionFunction *funcTable)
Sets the action function table.
ITUActionFunc ituSceneFindFunction (ITUScene *scene, const char *name)
Finds the action function by the specified name.
void * ituSceneFindWidget (ITUScene *scene, const char *name)
Finds the widget by the specified name.
ITUWidget * ituSceneFocusPrev (ITUScene *scene)
Finds the previous widget to focus.
ITUWidget * ituSceneFocusNext (ITUScene *scene)
Finds the next widget to focus.
void ituSceneExecuteCommand (ITUScene *scene, int delay, ITUCommandFunc func, int arg)
Execute delayed command.
static void ituSceneSendEvent (ITUScene *scene, int ev, char *param)
Sends custom event.
Variables
ITUScene * ituScene
Current loaded scene.
Detailed Description
Typedef Documentation
typedef bool(* ITUActionFunc)(ITUWidget *widget, char *param)
Action callback function definition.
Parameters
widget The widget to trigger the event.
param The parameter.
Returns
true to continue execute actions, false to stop execute the following actions on the widget.
Definition at line 7417 of file itu.h.
typedef void(* ITUCommandFunc)(int arg)
Command function definition.
Parameters
arg The argument.
Definition at line 7433 of file itu.h.
Function Documentation
void ituSceneDraw (ITUScene * scene, ITUSurface * dest)
Draws the scene to the specified surface.
Parameters
scene The scene to draw.
dest The surface to draw to.
Example:
 static ITUScene scene;
 ituLcdInit();
 ituSWInit();
 ituFtInit();
 ituFtLoadFont(0, "A:/font/DroidSansMono.ttf", ITU_GLYPH_8BPP);
 ituSceneInit(&scene, NULL);
 ituSceneLoadFile(&scene, "A:/helloworld.itu");
 for (;;)
 {
     if (ituSceneUpdate(&scene, ITU_EVENT_TIMER, 0, 0, 0))
     {
         ituSceneDraw(&scene, ituGetDisplaySurface());
         ituFlip(ituGetDisplaySurface());
     }
     usleep(33000);
 }
Examples:
test_itu/test_array.c, test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_helloworld.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, test_itu/test_stnlcd.c, and test_itu/test_trackbar.c.
Referenced by SceneRun().
void ituSceneExecuteCommand (ITUScene * scene, int delay, ITUCommandFunc func, int arg)
Execute delayed command.
Parameters
scene The scene to execute the command.
delay Delay timer count to execute this command.
func The command function to execute.
arg The command function argument.
Referenced by CameraListOnSelection(), CameraViewButtonOnPress(), CameraViewSnapshotButtonOnPress(), GuardLogClearConfirmOnPress(), GuardLogDeleteConfirmOnPress(), MainVoiceMemoDeleteConfirmButtonOnPress(), MainVoiceMemoOnTimer(), MainVoiceMemoStopRecordButtonOnPress(), MainVoiceMemoViewButtonOnPress(), MessagePhotoDeleteConfirmOnPress(), MessagePhotoGetList(), MessageServiceGetList(), PhoneContactsAddConfirmButtonOnPress(), PhoneContactsClearConfirmButtonOnPress(), PhoneContactsDeleteConfirmButtonOnPress(), PhoneContactsModifyConfirmButtonOnPress(), PhoneLogMissedClearConfirmButtonOnPress(), PhoneLogMissedDeleteConfirmButtonOnPress(), PhoneLogReceivedClearConfirmButtonOnPress(), PhoneLogReceivedDeleteConfirmButtonOnPress(), PhoneLogSentClearConfirmButtonOnPress(), PhoneLogSentDeleteConfirmButtonOnPress(), and SettingPhoneAudioRingRadioBoxOnPress().
void ituSceneExit (ITUScene * scene)
Exits scene.
Parameters
scene the scene to exit.
Referenced by LoadScene(), and SceneExit().
ITUActionFunc ituSceneFindFunction (ITUScene * scene, const char * name)
Finds the action function by the specified name.
Parameters
scene The scene to find.
name The action function name to find.
Returns
The found action function. NULL if not found.
void* ituSceneFindWidget (ITUScene * scene, const char * name)
Finds the widget by the specified name.
Parameters
scene The scene to find.
name The widget name to find.
Returns
The found widget. NULL if not found.
Example:
 ITUWidget* widget;
 widget = ituSceneFindWidget(&scene, "Button2");
 if (widget)
     ituWidgetSetOnPress(widget, OnPress);
Examples:
test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_jpeg.c, test_itu/test_listbox.c, and test_itu/test_progressbar.c.
Referenced by CalledIncomingShow(), CalledOnEnter(), CallingCall(), CallingCallByIP(), CallingCallManager(), CallingOnEnter(), CameraOnEnter(), CameraOutdoorButtonOnPress(), CameraOutdoorOnEnter(), CameraViewButtonOnPress(), CameraViewShow(), CheckGuard(), GuardLogOnEnter(), GuardModeOnEnter(), GuardPasswordOnEnter(), GuardStatusOnEnter(), GuardUserPasswordOnEnter(), GuardUserSettingOnEnter(), HouseAirConditionerOnEnter(), HouseCurtainOnEnter(), HouseLightOnEnter(), HouseModeOnEnter(), HousePlugOnEnter(), HouseTVOnEnter(), LogoOnEnter(), MainMenuNotifyUnplayVoiceMemo(), MainNotifyCallIncomingOnCustom(), MainNotifyGuardOnCustom(), MainNotifyMessagesOnCustom(), MainNotifyMissedCallsOnCustom(), MainNotifyNetworkOnCustom(), MainNotifyVoiceMemoIncomingOnCustom(), MainSetDoNotDisturbModeOnCustom(), MainVoiceMemoOnEnter(), MainWeatherOnEnter(), MessageNotifyTextMessageOnCustom(), MessageNotifyUnreadRecordMessage(), MessageNotifyVideoMessageOnCustom(), MessagePhotoOnEnter(), MessagePhotoViewOnEnter(), MessagePhotoViewOnTimer(), MessagePhotoViewShow(), MessageRecordOnEnter(), MessageRecordViewOnEnter(), MessageRecordViewOnTimer(), MessageRecordViewShow(), MessageServiceOnEnter(), MessageServiceViewOnEnter(), MessageServiceViewShow(), PhoneContactsAddOnEnter(), PhoneContactsAddShow(), PhoneContactsKeyboardOnEnter(), PhoneContactsKeyboardShow(), PhoneContactsKeypadOnEnter(), PhoneContactsKeypadShow(), PhoneContactsModifyOnEnter(), PhoneContactsModifyShow(), PhoneContactsOnEnter(), PhoneDialLobbyOnEnter(), PhoneDialManagerOnEnter(), PhoneDialResidentOnEnter(), PhoneLogMissedOnEnter(), PhoneLogReceivedOnEnter(), PhoneLogSentOnEnter(), PhoneLogViewShow(), SceneRun(), ScreensaverOnEnter(), SettingDisplayOnEnter(), SettingEngineerMiscGuardOnEnter(), SettingEngineerMiscTerminalOnEnter(), SettingEngineerMiscTwiceOnEnter(), SettingEngineerNetworkIPOnEnter(), SettingEngineerNetworkIPShow(), SettingEngineerNetworkMacKeypadConfirmButtonOnPress(), SettingEngineerNetworkMacShow(), SettingEngineerNetworkOnEnter(), SettingEngineerNetworkWiFiOnEnter(), SettingEngineerNetworkWiFiPasswordConfirmButtonOnPress(), SettingEngineerNetworkWiFiPasswordShow(), SettingEngineerOnEnter(), SettingEngineerSensorOnEnter(), SettingOutdoorMainOnEnter(), SettingOutdoorMiscOnEnter(), SettingPhoneAudioOnEnter(), SettingPhoneDisturbOnEnter(), SettingPhoneVoiceOnEnter(), SettingSystemOnEnter(), TimeOnEnter(), TouchCalibrationOnEnter(), UpgradeOnEnter(), VideoRecordIncomingShow(), and VideoRecordOnEnter().
ITUWidget* ituSceneFocusNext (ITUScene * scene)
Finds the next widget to focus.
Parameters
scene The scene to find.
Returns
The found widget. NULL if not found.
Examples:
test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, and test_itu/test_trackbar.c.
ITUWidget* ituSceneFocusPrev (ITUScene * scene)
Finds the previous widget to focus.
Parameters
scene The scene to find.
Returns
The found widget. NULL if not found.
Examples:
test_itu/test_sdl.c.
void ituSceneInit (ITUScene * scene, ITUWidget * root)
Initializes scene.
Parameters
scene The scene to initialize.
root The root widget. If you want to build the widget tree on runtime, set the root widget here, else set it the NULL value.
Examples:
test_itu/test_array.c, test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_helloworld.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, test_itu/test_stnlcd.c, and test_itu/test_trackbar.c.
Referenced by SceneInit().
int ituSceneLoadArray (ITUScene * scene, const char * array, int size)
Loads scene from an array.
Parameters
scene The scene to load to.
array The array buffer to load.
size The array size.
Returns
0 if success, else failed otherwise.
Examples:
test_itu/test_array.c.
int ituSceneLoadFile (ITUScene * scene, const char * filename)
Loads scene from a file.
Parameters
scene The scene to load to.
filename The file path to load.
Returns
0 if success, else failed otherwise.
Examples:
test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_helloworld.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, test_itu/test_stnlcd.c, and test_itu/test_trackbar.c.
Referenced by LoadScene().
int ituSceneLoadFileCore (ITUScene * scene, const char * filename)
Loads scene from a file without start.
Parameters
scene The scene to load to.
filename The file path to load.
Returns
0 if success, else failed otherwise.
void ituScenePreDraw (ITUScene * scene, ITUSurface * dest)
Pre-draws the scene to the specified surface.
Parameters
scene The scene to draw.
dest The surface to draw to.
Referenced by SceneRun().
static void ituSceneSendEvent (ITUScene * scene, int ev, char * param) inline static
Sends custom event.
Parameters
scene The scene to send.
ev The custom event to notify.
param The event related parameter.
Definition at line 7667 of file itu.h.
References ituSceneUpdate().
Referenced by CallConnected(), CallEnd(), CallError(), CallReceived(), CallSpotted(), CameraOnTimer(), CameraOutdoorOnTimer(), CheckDoNotDisturb(), CheckGuard(), CheckMissedCalls(), CheckNetwork(), CheckNewMessages(), CheckQuitValue(), SceneClearMissedCalls(), SceneRun(), SettingPhoneDisturbSaveButtonOnPress(), ToggleMute(), and UpdateIndicators().
void ituSceneSetFunctionTable (ITUScene * scene, ITUActionFunction * funcTable)
Sets the action function table.
Parameters
scene The scene to set.
funcTable The action function table to set.
Examples:
test_itu/test_trackbar.c.
Referenced by SceneInit().
void ituSceneSetRotation (ITUScene * scene, ITURotation rot, int screenWidth, int screenHeight)
Rotates the scene.
Parameters
scene The scene to rotate.
rot The rotation.
screenWidth Screen width
screenHeight Screen height
Examples:
test_itu/test_sdl.c.
void ituSceneStart (ITUScene * scene)
Starts scene.
Parameters
scene The scene to start.
bool ituSceneUpdate (ITUScene * scene, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the scene to notify all the visible widgets by specified event.
Parameters
scene The scene to update.
ev The event to notify.
arg1 The event related argument #1.
arg2 The event related argument #2.
arg3 The event related argument #3.
Returns
true if any widget is modified and need to redraw the scene, false if no need to redraw.
Examples:
test_itu/test_array.c, test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_helloworld.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, test_itu/test_stnlcd.c, and test_itu/test_trackbar.c.
Referenced by ituSceneSendEvent(), and SceneRun().
Variable Documentation
ITUScene* ituScene
Current loaded scene.