ITE SoC SDK: Linphone
Linphone
ITE DoorBell Outdoor Modules
Enumerations
enum HintSound { HINT_SOUND_OPENDOOR, HINT_SOUND_VOICEMEMO, HINT_SOUND_ROOM_NOT_EXIST, HINT_SOUND_REDIAL }
Hint sound definition.
Functions
void LinphoneInit (void)
Initializes linphone module.
void LinphoneExit (void)
Exits linphone module.
int LinphoneGetVoiceLevel (void)
Gets the percentage of voice volume.
void LinphoneSetVoiceLevel (int level)
Sets the percentage of voice volume.
int LinphoneGetMicLevel (void)
Gets the percentage of MIC volume.
void LinphoneSetMicLevel (int level)
Sets the percentage of MIC volume.
void LinphonePlayRingSound (void)
Plays ring sound.
void LinphoneSetRingSound (char *file)
Sets the file path of ring sound.
int LinphoneGetRingLevel (void)
Gets the percentage of ring volume.
void LinphoneSetRingLevel (int level)
Sets the percentage of ring volume.
void LinphonePlayKeySound (void)
Plays key sound.
void LinphoneEnableKeySound (void)
Enables key sound.
void LinphoneDisableKeySound (void)
Disables key sound.
int LinphoneGetKeyLevel (void)
Gets the percentage of key volume.
void LinphoneSetKeyLevel (int level)
Sets the percentage of key volume.
void LinphonePlayHintSound (HintSound snd)
Plays hint sound.
void LinphonePlayNumberKeySound (char num)
Plays key number sound.
void LinphoneCall (char *ip, bool video)
Makes a call to the specified IP address.
void LinphoneAnswer (void)
Answers current call.
void LinphoneTerminate (void)
Terminates current call.
void LinphoneCallDevices (DeviceInfo infoArray[], int count, bool video, bool earlyMedia)
Makes calls to the devices in the same time.
void LinphoneTerminateOthers (long id)
Terminates all calls except the specified call ID.
void LinphoneRecordVideoMessage (DeviceInfo *info)
Makes a video message to the specified device.
void LinphoneRegister (void)
Registers to SIP server.
Detailed Description
Enumeration Type Documentation
enum HintSound
Hint sound definition.
Enumerator
HINT_SOUND_OPENDOOR
Hint sound on opening door.
HINT_SOUND_VOICEMEMO
Hint sound on recording voice memo.
HINT_SOUND_ROOM_NOT_EXIST
Hint sound for calling wrong address.
HINT_SOUND_REDIAL
Hint sound for redialing.
Definition at line 406 of file doorbell_outdoor/doorbell.h.
Function Documentation
void LinphoneAnswer (void)
Answers current call.
Definition at line 263 of file doorbell_outdoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
void LinphoneCall (char * ip, bool video)
Makes a call to the specified IP address.
Parameters
ip The specified IP address to call.
video Enables video feature.
Definition at line 245 of file doorbell_outdoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
void LinphoneCallDevices (DeviceInfo infoArray[], int count, bool video, bool earlyMedia)
Makes calls to the devices in the same time.
Parameters
infoArray the array of DeviceInfo to make calls.
count The count of DeviceInfo in the infoArray.
video Enables video feature.
earlyMedia Enables early media feature.
Definition at line 498 of file doorbell_indoor/linphone.c.
References DeviceInfo::area, DeviceInfo::building, LinphoneCastor3::calling_ip_array, LinphoneCastor3::calling_ip_count, LinphoneCastor3::calling_mobile_array, LinphoneCastor3::calling_mobile_count, DEVICE_INDOOR, DEVICE_INDOOR2, DEVICE_MOBILE, DeviceInfo::ext, DeviceInfo::floor, i, DeviceInfo::ip, LINPHONE_CASTOR3_MAX_IP_COUNT, linphoneCastor3, lpInited, LinphoneCastor3::mq, PROMPT_MAX_LEN, DeviceInfo::room, LinphoneCastor3::sip_server_uri, theCenterInfo, and DeviceInfo::unit.
void LinphoneDisableKeySound (void)
Disables key sound.
Definition at line 196 of file doorbell_outdoor/linphone.c.
References lpKeySoundEnabled.
void LinphoneEnableKeySound (void)
Enables key sound.
Definition at line 191 of file doorbell_outdoor/linphone.c.
References lpKeySoundEnabled.
void LinphoneExit (void)
Exits linphone module.
Definition at line 103 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, lpQuit, LinphoneCastor3::mq, PROMPT_MAX_LEN, and LinphoneCastor3::quit.
int LinphoneGetKeyLevel (void)
Gets the percentage of key volume.
Returns
The percentage of key volume, range is 0~100.
Definition at line 165 of file doorbell_outdoor/linphone.c.
References LinphoneCastor3::key_level, and linphoneCastor3.
int LinphoneGetMicLevel (void)
Gets the percentage of MIC volume.
Returns
The percentage of MIC volume, range is 0~100.
Definition at line 139 of file doorbell_indoor/linphone.c.
References linphoneCastor3, and LinphoneCastor3::rec_level.
int LinphoneGetRingLevel (void)
Gets the percentage of ring volume.
Returns
The percentage of ring volume, range is 0~100.
Definition at line 169 of file doorbell_indoor/linphone.c.
References linphoneCastor3, and LinphoneCastor3::ring_level.
int LinphoneGetVoiceLevel (void)
Gets the percentage of voice volume.
Returns
The percentage of voice volume, range is 0~100.
Definition at line 121 of file doorbell_indoor/linphone.c.
References linphoneCastor3, and LinphoneCastor3::play_level.
void LinphoneInit (void)
Initializes linphone module.
Definition at line 80 of file doorbell_indoor/linphone.c.
References attr, LinphoneCastor3::key_level, Config::keylevel, LINPHONE_STACK_SIZE, linphonec_call_get_addr_callback, linphoneCastor3, LinphonecCallGetAddr(), LinphoneTask(), lpInDoNotDisturb, lpInited, lpInMute, lpQuit, lpVideoMsgUri, lpWarnSoundPlaying, theConfig, LinphoneCastor3::warn_level, and Config::warnlevel.
void LinphonePlayHintSound (HintSound snd)
Plays hint sound.
Parameters
snd The hint sound to play.
Definition at line 201 of file doorbell_outdoor/linphone.c.
References HINT_SOUND_OPENDOOR, HINT_SOUND_REDIAL, HINT_SOUND_ROOM_NOT_EXIST, HINT_SOUND_VOICEMEMO, linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
Referenced by ahc_echo(), CallError(), CallingCall(), CardListCheckTask(), and SceneFlagReset().
void LinphonePlayKeySound (void)
Plays key sound.
Definition at line 213 of file doorbell_indoor/linphone.c.
References Config::keysound, linphoneCastor3, lpInited, lpKeySoundEnabled, lpWarnSoundPlaying, LinphoneCastor3::mq, PROMPT_MAX_LEN, and theConfig.
void LinphonePlayNumberKeySound (char num)
Plays key number sound.
Parameters
num The key number sound to play.
Definition at line 234 of file doorbell_outdoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
void LinphonePlayRingSound (void)
Plays ring sound.
Definition at line 157 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, lpWarnSoundPlaying, LinphoneCastor3::mq, PROMPT_MAX_LEN, Config::ringsound, and theConfig.
void LinphoneRecordVideoMessage (DeviceInfo * info)
Makes a video message to the specified device.
Parameters
info The DeviceInfo to make a video message.
Definition at line 375 of file doorbell_outdoor/linphone.c.
References DeviceInfo::area, DeviceInfo::building, DEVICE_INDOOR2, DeviceInfo::floor, DeviceInfo::ip, linphoneCastor3, LinphoneInitVideoMessageUri(), lpInited, lpVideoMsgUri, LinphoneCastor3::mq, NetworkIsReady(), PROMPT_MAX_LEN, DeviceInfo::room, theCenterInfo, DeviceInfo::type, DeviceInfo::unit, and LinphoneCastor3::video_msg_uri.
void LinphoneRegister (void)
Registers to SIP server.
The SIP server address is the center address. The SIP ID is the device address like 01-01-01-01-01-01.
Definition at line 742 of file doorbell_indoor/linphone.c.
References DeviceInfo::area, DeviceInfo::building, DeviceInfo::ext, DeviceInfo::floor, DeviceInfo::ip, ITP_DEVICE_ETHERNET, ITP_IOCTL_IS_CONNECTED, linphoneCastor3, lpInited, LinphoneCastor3::mq, PROMPT_MAX_LEN, DeviceInfo::room, theCenterInfo, theDeviceInfo, and DeviceInfo::unit.
Referenced by LinphoneInitialized().
void LinphoneSetKeyLevel (int level)
Sets the percentage of key volume.
Parameters
level The percentage of key volume, range is 0~100.
Definition at line 204 of file doorbell_indoor/linphone.c.
References LinphoneCastor3::key_level, Config::keylevel, linphoneCastor3, lpInited, and theConfig.
void LinphoneSetMicLevel (int level)
Sets the percentage of MIC volume.
Parameters
level The percentage of MIC volume, range is 0~100.
Definition at line 144 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, PROMPT_MAX_LEN, and LinphoneCastor3::rec_level.
void LinphoneSetRingLevel (int level)
Sets the percentage of ring volume.
Parameters
level The percentage of ring volume, range is 0~100.
Definition at line 138 of file doorbell_outdoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, PROMPT_MAX_LEN, and LinphoneCastor3::ring_level.
void LinphoneSetRingSound (char * file)
Sets the file path of ring sound.
Must be WAV file.
Parameters
file the file path of ring sound.
Definition at line 190 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, PROMPT_MAX_LEN, Config::ringsound, and theConfig.
void LinphoneSetVoiceLevel (int level)
Sets the percentage of voice volume.
Parameters
level The percentage of voice volume, range is 0~100.
Definition at line 126 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, LinphoneCastor3::play_level, and PROMPT_MAX_LEN.
void LinphoneTerminate (void)
Terminates current call.
Definition at line 274 of file doorbell_outdoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.
void LinphoneTerminateOthers (long id)
Terminates all calls except the specified call ID.
Parameters
id Only the specified ID don't to terminate.
Definition at line 526 of file doorbell_indoor/linphone.c.
References linphoneCastor3, lpInited, LinphoneCastor3::mq, and PROMPT_MAX_LEN.