ITE SoC SDK: Call Logs
Call Logs
ITE DoorBell Indoor Modules
Data Structures
struct CallLogEntry
Calling log definition.
Enumerations
enum CallLogType { CALLLOG_UNKNOWN, CALLLOG_MISSED, CALLLOG_RECEIVED, CALLLOG_SENT }
Call log type definition.
Functions
void CallLogInit (void)
Initializes call log module.
void CallLogExit (void)
Exits call log module.
int CallLogGetCount (CallLogType type)
Gets total count of call logs.
CallLogEntry * CallLogGetEntry (int index, CallLogType type)
Gets the call log entry by index.
void CallLogDeleteEntry (int index, CallLogType type)
Deletes the call log entry by index.
void CallLogClearEntries (CallLogType type)
Clears the call log entries.
int CallLogGetCurrMissedCount (void)
Gets the count of current missed calls.
void CallLogClearCurrMissedCount (void)
Clears the count of current missed calls.
Detailed Description
Enumeration Type Documentation
enum CallLogType
Call log type definition.
Enumerator
CALLLOG_UNKNOWN
Unknown call.
CALLLOG_MISSED
Missed call.
CALLLOG_RECEIVED
Received call.
CALLLOG_SENT
Sent call.
Definition at line 388 of file doorbell_indoor/doorbell.h.
Function Documentation
void CallLogClearCurrMissedCount (void)
Clears the count of current missed calls.
Definition at line 262 of file calllog.c.
References callLogCurrMissedCount.
Referenced by SceneClearMissedCalls().
void CallLogClearEntries (CallLogType type)
Clears the call log entries.
Parameters
type The call log type.
Definition at line 235 of file calllog.c.
References CALLLOG_MISSED, CALLLOG_RECEIVED, CALLLOG_SENT, callLogMissedCount, callLogMissedIndex, callLogReceivedCount, callLogReceivedIndex, callLogSentCount, callLogSentIndex, clMutex, LinphoneClearMissedLogs(), LinphoneClearReceivedLogs(), and LinphoneClearSentLogs().
Referenced by PhoneLogMissedClearConfirmButtonOnPress(), PhoneLogReceivedClearConfirmButtonOnPress(), and PhoneLogSentClearConfirmButtonOnPress().
void CallLogDeleteEntry (int index, CallLogType type)
Deletes the call log entry by index.
Parameters
index The index of call log entry.
type The call log type.
Definition at line 153 of file calllog.c.
References CALLLOG_MISSED, CALLLOG_RECEIVED, CALLLOG_SENT, callLogMissedCount, callLogReceivedCount, callLogSentCount, clMutex, i, LinphoneDeleteCallLog(), MAX_CALLLOG_COUNT, and CallLogEntry::refkey.
Referenced by CallLogAddCallback(), PhoneLogMissedDeleteConfirmButtonOnPress(), PhoneLogReceivedDeleteConfirmButtonOnPress(), and PhoneLogSentDeleteConfirmButtonOnPress().
void CallLogExit (void)
Exits call log module.
Definition at line 92 of file calllog.c.
References clMutex.
Referenced by SDL_main().
int CallLogGetCount (CallLogType type)
Gets total count of call logs.
Parameters
type The call log type.
Returns
the total count of call logs.
Definition at line 97 of file calllog.c.
References CALLLOG_MISSED, CALLLOG_RECEIVED, CALLLOG_SENT, callLogMissedCount, callLogReceivedCount, and callLogSentCount.
Referenced by PhoneLogMissedDurationListBoxOnLoad(), PhoneLogMissedRoomListBoxOnLoad(), PhoneLogMissedTimeListBoxOnLoad(), PhoneLogReceivedDurationListBoxOnLoad(), PhoneLogReceivedRoomListBoxOnLoad(), PhoneLogReceivedTimeListBoxOnLoad(), PhoneLogSentDurationListBoxOnLoad(), PhoneLogSentRoomListBoxOnLoad(), and PhoneLogSentTimeListBoxOnLoad().
int CallLogGetCurrMissedCount (void)
Gets the count of current missed calls.
Returns
The call log entry, NULL if not found.
Definition at line 257 of file calllog.c.
References callLogCurrMissedCount.
Referenced by CheckMissedCalls(), and UpdateIndicators().
CallLogEntry* CallLogGetEntry (int index, CallLogType type)
Gets the call log entry by index.
Parameters
index The index of call log entry.
type The call log type.
Returns
The call log entry, NULL if not found.
Definition at line 113 of file calllog.c.
References CALLLOG_MISSED, CALLLOG_RECEIVED, CALLLOG_SENT, callLogMissedCount, callLogReceivedCount, callLogSentCount, i, and MAX_CALLLOG_COUNT.
Referenced by PhoneLogMissedAddButtonOnPress(), PhoneLogMissedCallButtonOnPress(), PhoneLogMissedDeleteConfirmButtonOnPress(), PhoneLogMissedRoomListBoxOnLoad(), PhoneLogMissedTimeListBoxOnLoad(), PhoneLogMissedViewButtonOnPress(), PhoneLogReceivedAddButtonOnPress(), PhoneLogReceivedCallButtonOnPress(), PhoneLogReceivedDeleteConfirmButtonOnPress(), PhoneLogReceivedDurationListBoxOnLoad(), PhoneLogReceivedRoomListBoxOnLoad(), PhoneLogReceivedTimeListBoxOnLoad(), PhoneLogReceivedViewButtonOnPress(), PhoneLogSentAddButtonOnPress(), PhoneLogSentCallButtonOnPress(), PhoneLogSentDeleteConfirmButtonOnPress(), PhoneLogSentDurationListBoxOnLoad(), PhoneLogSentRoomListBoxOnLoad(), PhoneLogSentTimeListBoxOnLoad(), and PhoneLogSentViewButtonOnPress().
void CallLogInit (void)
Initializes call log module.
Definition at line 80 of file calllog.c.
References CallLogAddCallback(), callLogCurrMissedCount, callLogMissedCount, callLogMissedIndex, callLogReceivedCount, callLogReceivedIndex, callLogSentCount, callLogSentIndex, clMutex, linphonec_call_log_add_callback, Config::missed_call_count, and theConfig.
Referenced by SDL_main().