ITE SoC SDK: Address Book
Address Book
ITE DoorBell Outdoor Modules
Macros
#define MAX_MANAGER_COUNT 10
Maximum Administrator Unit count.
Functions
void RemoveAddressbook (void)
Remove old AddressBook.
void AddressBookInit (void)
Initializes address book module.
void AddressBookExit (void)
Exits address book module.
char * AddressBookGetVersion (void)
Gets version of addressbook.
void AddressBookGetCenterInfo (DeviceInfo *info)
Gets device information of control server from addressbook.
void AddressBookGetDeviceInfo (DeviceInfo *info, char *ip)
Gets device information from addressbook by IP address.
char * AddressBookGetDeviceIP (char *area, char *building, char *unit, char *floor, char *room, char *ext)
Gets IP address by address information from addressbook.
int AddressBookGetDeviceInfoArray (DeviceInfo infoArray[], int count, char *area, char *building, char *unit, char *floor, char *room)
Gets array of indoor phones by address information from addressbook.
int AddressBookGetCameraInfoArray (DeviceInfo infoArray[], int count)
Gets array of devices with camera from addressbook.
int AddressBookGetManagerInfoArray (DeviceInfo infoArray[], int count)
Gets array of administrator units from addressbook.
char * AddressBookGetGateway (DeviceInfo *info)
Gets IP address of gateway from addressbook.
char * AddressBookGetNetMask (DeviceInfo *info)
Gets netmask from addressbook.
Detailed Description
Macro Definition Documentation
#define MAX_MANAGER_COUNT 10
Maximum Administrator Unit count.
Definition at line 84 of file doorbell_outdoor/doorbell.h.
Function Documentation
void AddressBookExit (void)
Exits address book module.
Definition at line 444 of file doorbell_indoor/addressbook.c.
References abDeviceCount.
Referenced by AddressBookInit(), and SDL_main().
int AddressBookGetCameraInfoArray (DeviceInfo infoArray[], int count)
Gets array of devices with camera from addressbook.
Parameters
infoArray The array of DeviceInfo to fill in.
count Maximum count of DeviceInfo in array.
Returns
the actual count of filled DeviceInfo in array.
Definition at line 669 of file doorbell_outdoor/addressbook.c.
References abDeviceCount, DEVICE_BUILDING, DEVICE_ENTRANCE, DEVICE_INTERCOM, DEVICE_IPCAM, DEVICE_OUTDOOR, DEVICE_WALL, GetDeviceInfo(), i, j, and ABDevice::type.
void AddressBookGetCenterInfo (DeviceInfo * info)
Gets device information of control server from addressbook.
Parameters
info The pointer to retrieve the DeviceInfo of control server.
Definition at line 462 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DEVICE_CENTER, GetDeviceInfo(), i, and ABDevice::type.
Referenced by DeviceInfoInit().
void AddressBookGetDeviceInfo (DeviceInfo * info, char * ip)
Gets device information from addressbook by IP address.
Parameters
info The pointer to retrieve the DeviceInfo.
ip The IP address of device.
Definition at line 480 of file doorbell_indoor/addressbook.c.
References abDeviceCount, GetDeviceInfo(), i, and ABDevice::ip.
Referenced by ahc_echo(), CalledIncomingOnCustom(), CalledIncomingShow(), CalledWaitingConfirmButtonOnPress(), CalledWaitingConfirmButtonOnSimulatePressing(), CallingCall(), CallingCallByIP(), CallingCallManager(), CallingIncomingOnCustom(), CallingWaitingConfirmButtonOnPress(), CallingWaitingConfirmButtonOnSimulatePressing(), CallReceived(), CameraViewShow(), CaptureCreateTask(), CaptureSnapshot(), CaptureStopRecord(), DeviceInfoInit(), DeviceInfoInitByDhcp(), EventWriteCalloutLog(), EventWriteSmsLog(), LinphonecCallGetAddr(), PhoneContactsCallButtonOnPress(), PhoneContactsModifyButtonOnPress(), PhoneContactsRoomListBoxOnLoad(), PhoneLogMissedAddButtonOnPress(), PhoneLogMissedCallButtonOnPress(), PhoneLogMissedRoomListBoxOnLoad(), PhoneLogMissedViewButtonOnPress(), PhoneLogReceivedAddButtonOnPress(), PhoneLogReceivedCallButtonOnPress(), PhoneLogReceivedRoomListBoxOnLoad(), PhoneLogReceivedViewButtonOnPress(), PhoneLogSentAddButtonOnPress(), PhoneLogSentCallButtonOnPress(), PhoneLogSentRoomListBoxOnLoad(), PhoneLogSentViewButtonOnPress(), SceneRun(), VideoMemoCreateTask(), VideoMemoStopRecord(), and VideoRecordIncomingShow().
int AddressBookGetDeviceInfoArray (DeviceInfo infoArray[], int count, char * area, char * building, char * unit, char * floor, char * room)
Gets array of indoor phones by address information from addressbook.
Parameters
infoArray The array of DeviceInfo to fill in.
count Maximum count of DeviceInfo in array.
area The area code of address.
building The building code of address.
unit The unit code of address.
floor The floor code of address.
room The room code of address.
Returns
the actual count of filled DeviceInfo in array.
Definition at line 587 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DEVICE_INDOOR, DEVICE_INDOOR2, DEVICE_MOBILE, GetDeviceInfo(), i, j, ABDevice::room, and ABDevice::type.
Referenced by ahc_echo(), CallingCall(), and RemoteSetDontDisturbConfig().
char* AddressBookGetDeviceIP (char * area, char * building, char * unit, char * floor, char * room, char * ext)
Gets IP address by address information from addressbook.
Parameters
area The area code of address.
building The building code of address.
unit The unit code of address.
floor The floor code of address.
room The room code of address.
ext The ext code of address. Can be NULL if not exist.
Returns
the IP address string. Remember to free it after used to avoid memory leak.
Definition at line 545 of file doorbell_indoor/addressbook.c.
References abDeviceCount, i, ABDevice::ip, and ABDevice::room.
Referenced by ahc_echo(), CallingCall(), DeviceInfoInit(), PhoneContactsAddConfirmButtonOnPress(), PhoneContactsModifyConfirmButtonOnPress(), RemoteGetDontDisturbConfig(), and SettingEngineerMiscTwiceSettingButtonOnPress().
char* AddressBookGetGateway (DeviceInfo * info)
Gets IP address of gateway from addressbook.
Parameters
info The pointer to the DeviceInfo of this device.
Returns
the IP address string of gateway. Remember to free it after used to avoid memory leak.
Definition at line 722 of file doorbell_indoor/addressbook.c.
References abGateway.
Referenced by DeviceInfoInit().
int AddressBookGetManagerInfoArray (DeviceInfo infoArray[], int count)
Gets array of administrator units from addressbook.
Parameters
infoArray The array of DeviceInfo to fill in.
count Maximum count of DeviceInfo in array.
Returns
the actual count of filled DeviceInfo in array.
Definition at line 674 of file doorbell_indoor/addressbook.c.
References abDeviceCount, DEVICE_MANAGER, GetDeviceInfo(), i, j, and ABDevice::type.
Referenced by ahc_echo(), CallingCallManager(), EventUploadTask(), NetworkSntpUpdate(), PhoneManagerListBoxOnLoad(), and ResetEthernet().
char* AddressBookGetNetMask (DeviceInfo * info)
Gets netmask from addressbook.
Parameters
info The pointer to the DeviceInfo of this device.
Returns
the netmask string. Remember to free it after used to avoid memory leak.
Definition at line 730 of file doorbell_indoor/addressbook.c.
References abNetMask.
Referenced by DeviceInfoInit().
char* AddressBookGetVersion (void)
Gets version of addressbook.
Returns
the version string. Remember to free it after used to avoid memory leak.
Definition at line 454 of file doorbell_indoor/addressbook.c.
References abVersion.
Referenced by ahc_echo(), create_response(), SettingEngineerMiscTwiceSettingButtonOnPress(), SettingSystemMessageListBoxOnLoad(), and UpgradeGetDeviceInfo().
void AddressBookInit (void)
Initializes address book module.
Definition at line 223 of file doorbell_indoor/addressbook.c.
References _ToDeviceType(), abDeviceCount, abGateway, abNetMask, abVersion, AddressBookExit(), Config::area, Config::building, CountAddressbook(), DcpsGetSize(), Config::ext, font::f, filebuf, Config::floor, ABDevice::group, i, ABDevice::ip, ITP_DEVICE_DECOMPRESS, ITP_IOCTL_EXIT, ITP_IOCTL_INIT, k, Parse_UCL2MEM(), ABDevice::room, Config::room, SoftwareDecompress(), theConfig, ABDevice::type, and Config::unit.
Referenced by SDL_main(), and UpgradeProcessTask().
void RemoveAddressbook (void)
Remove old AddressBook.
Definition at line 421 of file doorbell_outdoor/addressbook.c.
References i, and MAX_ADDRESSBOOK.
Referenced by UpgradeProcess(), and UpgradeProcessTask().