ITE SoC SDK: Audio Player
Audio Player
ITE DoorBell Indoor Modules
Functions
void AudioInit (void)
Initializes audio module.
void AudioExit (void)
Exits audio module.
int AudioPlay (char *filename)
Plays the specified wav file.
void AudioStop (void)
Stops playing sound.
void AudioPlayKeySound (void)
Plays keypad sound.
void AudioSetKeyLevel (int level)
Sets the volume of keypad sound.
void AudioPlayWarnSound (void)
Plays warning sound.
void AudioMute (void)
Mutes all audio.
void AudioUnMute (void)
Un-mutes all audio.
bool AudioIsMuted (void)
Determines whether this audio is muted or not.
Detailed Description
Function Documentation
void AudioExit (void)
Exits audio module.
Definition at line 23 of file audio.c.
Referenced by SDL_main().
void AudioInit (void)
Initializes audio module.
Definition at line 18 of file audio.c.
Referenced by SDL_main().
bool AudioIsMuted (void)
Determines whether this audio is muted or not.
Returns
true muted, false otherwise.
Definition at line 105 of file audio.c.
Referenced by CheckDoNotDisturb(), and CheckGuard().
void AudioMute (void)
Mutes all audio.
Definition at line 95 of file audio.c.
Referenced by CheckGuard(), SettingPhoneDisturbSaveButtonOnPress(), ToggleMute(), and UpdateIndicators().
int AudioPlay (char * filename)
Plays the specified wav file.
Parameters
filename The specified wav file to play.
Returns
0 for success, otherwise failed.
Definition at line 28 of file audio.c.
References AL_Local_player_http_handle, AUDIOLINK_LOCAL_PLAYER_BUFFER_LEN, and smtkAudioMgrPlayNetwork().
Referenced by AudioPlayKeySound(), and AudioPlayWarnSound().
void AudioPlayKeySound (void)
Plays keypad sound.
Definition at line 68 of file audio.c.
References AudioPlay(), Config::keylevel, Config::keysound, and theConfig.
void AudioPlayWarnSound (void)
Plays warning sound.
Definition at line 89 of file audio.c.
References AudioPlay(), theConfig, and Config::warnlevel.
void AudioSetKeyLevel (int level)
Sets the volume of keypad sound.
Parameters
level the percentage of volume.
Definition at line 81 of file audio.c.
References Config::keylevel, and theConfig.
void AudioStop (void)
Stops playing sound.
Definition at line 63 of file audio.c.
void AudioUnMute (void)
Un-mutes all audio.
Definition at line 100 of file audio.c.
Referenced by CheckGuard(), SettingPhoneDisturbSaveButtonOnPress(), ToggleMute(), and UpdateIndicators().