ITE SoC SDK: Layer
Layer
ITE UI Library » Widgets
Data Structures
struct ITULayerTag
Layer widget definition.
Typedefs
typedef struct ITULayerTag ITULayer
Layer widget definition.
Functions
void ituLayerInit (ITULayer *layer)
Initializes the layer widget.
void ituLayerLoad (ITULayer *layer, uint32_t base)
Loads the layer widget.
void ituLayerExit (ITUWidget *widget)
Exits the layer widget.
bool ituLayerClone (ITUWidget *widget, ITUWidget **cloned)
Clones the layer widget.
bool ituLayerUpdate (ITUWidget *widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the layer widget by specified event.
void ituLayerOnAction (ITUWidget *widget, ITUActionType action, char *param)
Do the specified action.
void ituLayerGoto (ITULayer *layer)
Goto the specified layer.
void ituLayerEnableOthers (ITULayer *layer)
Enables all other layers.
void ituLayerDisableOthers (ITULayer *layer)
Disables all other layers.
void ituLayerLoadExternal (ITULayer *layer)
Loads external module.
void ituLayerReleaseExternal (ITULayer *layer)
Releases external module.
void ituLayerLoadFont (ITULayer *layer)
Loads font.
ITUSurface * ituLayerLoadExternalSurface (ITULayer *layer, uint32_t offset)
Loads external surface.
Detailed Description
Typedef Documentation
typedef struct ITULayerTag ITULayer
Layer widget definition.
This is used for layer container.
Function Documentation
bool ituLayerClone (ITUWidget * widget, ITUWidget ** cloned)
Clones the layer widget.
Parameters
widget The layer widget to clone.
cloned Retrieved cloned layer widget.
Returns
true if clone is success, false otherwise.
void ituLayerDisableOthers (ITULayer * layer)
Disables all other layers.
Parameters
layer the layer not to disable.
void ituLayerEnableOthers (ITULayer * layer)
Enables all other layers.
Parameters
layer the layer not to enable.
void ituLayerExit (ITUWidget * widget)
Exits the layer widget.
Parameters
widget The layer widget to exit.
void ituLayerGoto (ITULayer * layer)
Goto the specified layer.
It will set the specified layer visible and set other layers invisible.
Parameters
layer the layer to goto.
Referenced by CalledAnswerButtonOnPress(), CalledOnTimer(), CallingAnswerButtonOnPress(), CallingOnTimer(), CheckGuard(), LogoOnEnter(), MainNotifyCallIncomingOnCustom(), MainNotifyVoiceMemoIncomingOnCustom(), MessagePhotoViewOnTimer(), MessageRecordViewOnTimer(), PhoneContactsAddCancelButtonOnPress(), PhoneContactsGotoLastLayer(), PhoneContactsKeyboardCloseButtonOnPress(), PhoneContactsKeyboardEnterButtonOnPress(), PhoneContactsKeypadCloseButtonOnPress(), PhoneContactsKeypadConfirmButtonOnPress(), PhoneContactsModifyCancelButtonOnPress(), PhoneContactsModifyGotoLastLayer(), PhoneLogViewCloseButtonOnPress(), SceneRun(), SettingDisplaySaveButtonOnPress(), UpgradeOnTimer(), and VideoRecordOnTimer().
void ituLayerInit (ITULayer * layer)
Initializes the layer widget.
Parameters
layer The layer widget to initialize.
void ituLayerLoad (ITULayer * layer, uint32_t base)
Loads the layer widget.
This is called by scene manager.
Parameters
layer The layer widget to load.
base The address in the scene file buffer.
void ituLayerLoadExternal (ITULayer * layer)
Loads external module.
Parameters
layer the layer to load external module.
ITUSurface* ituLayerLoadExternalSurface (ITULayer * layer, uint32_t offset)
Loads external surface.
Parameters
layer the layer to load.
offset the surface offset.
void ituLayerLoadFont (ITULayer * layer)
Loads font.
Parameters
layer the layer to load font.
void ituLayerOnAction (ITUWidget * widget, ITUActionType action, char * param)
Do the specified action.
This is triggered by other widget's event.
Parameters
widget The layer widget to do the action.
action The action to do.
param The parameter of action.
void ituLayerReleaseExternal (ITULayer * layer)
Releases external module.
Parameters
layer the layer to release external module.
bool ituLayerUpdate (ITUWidget * widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the layer widget by specified event.
Parameters
widget The layer widget to update.
ev The event to notify.
arg1 The event related argument #1.
arg2 The event related argument #2.
arg3 The event related argument #3.
Returns
true if the layer widget is modified and need to be redraw, false if no need to be redraw.