ITE SoC SDK: Sprite
Sprite
ITE UI Library » Widgets
Data Structures
struct ITUSpriteTag
Sprite widget definition.
Macros
#define ituSpriteOnStop(sprite) ((ITUSprite*)(sprite))->OnStop((ITUSprite*)(sprite))
This is called when the sprite stop playing.
#define ituSpriteSetOnStop(sprite, onStop) (((ITUSprite*)(sprite))->OnStop = (onStop))
Sets OnStop callback function of sprite.
Typedefs
typedef struct ITUSpriteTag ITUSprite
Sprite widget definition.
Functions
void ituSpriteInit (ITUSprite *sprite)
Initializes the sprite widget.
void ituSpriteLoad (ITUSprite *sprite, uint32_t base)
Loads the sprite widget.
bool ituSpriteClone (ITUWidget *widget, ITUWidget **cloned)
Clones the sprite widget.
bool ituSpriteUpdate (ITUWidget *widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the sprite widget by specified event.
void ituSpriteDraw (ITUWidget *widget, ITUSurface *dest, int x, int y, uint8_t alpha)
Draws the sprite widget to the specified surface.
void ituSpriteOnAction (ITUWidget *widget, ITUActionType action, char *param)
Do the specified action.
void ituSpriteSetDelay (ITUSprite *sprite, int delay)
Sets the delay value to the sprite widget.
void ituSpritePlay (ITUSprite *sprite, int frame)
Plays the sprite widget.
void ituSpriteStop (ITUSprite *sprite)
Stops the playing sprite widget.
void ituSpriteGoto (ITUSprite *sprite, int frame)
Gotos the specified frame of sprite widget.
Detailed Description
Macro Definition Documentation
#define ituSpriteOnStop (sprite) ((ITUSprite*)(sprite))->OnStop((ITUSprite*)(sprite))
This is called when the sprite stop playing.
Parameters
sprite The sprite widget.
Definition at line 3729 of file itu.h.
#define ituSpriteSetOnStop (sprite, onStop) (((ITUSprite*)(sprite))->OnStop = (onStop))
Sets OnStop callback function of sprite.
Parameters
sprite Pointer referring to the sprite.
onStop The callback function to set.
Definition at line 3737 of file itu.h.
Typedef Documentation
typedef struct ITUSpriteTag ITUSprite
Sprite widget definition.
This is used for drawing animation of sprite. It is a container of icon widgets to do the sprite job.
Function Documentation
bool ituSpriteClone (ITUWidget * widget, ITUWidget ** cloned)
Clones the sprite widget.
Parameters
widget The sprite widget to clone.
cloned Retrieved sprite widget.
Returns
true if clone is success, false otherwise.
void ituSpriteDraw (ITUWidget * widget, ITUSurface * dest, int x, int y, uint8_t alpha)
Draws the sprite widget to the specified surface.
Parameters
widget The sprite widget to draw.
dest The surface to draw to.
x The x coordinate of destination surface, in pixels.
y The y coordinate of destination surface, in pixels.
alpha the alpha value to do the constant alphablending to the surface.
void ituSpriteGoto (ITUSprite * sprite, int frame)
Gotos the specified frame of sprite widget.
Parameters
sprite The playing sprite widget to goto.
frame The specified frame of sprite widget to goto.
Referenced by CalledConnectedOnCustom(), CalledOnEnter(), CalledVolDownButtonOnPress(), CalledVolUpButtonOnPress(), CallingConnectedOnCustom(), CallingOnEnter(), CallingVolDownButtonOnPress(), CallingVolUpButtonOnPress(), HouseAirConditionerOffButtonOnPress(), HouseAirConditionerOnButtonOnPress(), HouseLightOffButtonOnPress(), HouseLightOnButtonOnPress(), HousePlugOffButtonOnPress(), HousePlugOnButtonOnPress(), HouseTVOffButtonOnPress(), HouseTVOnButtonOnPress(), MainNotifyGuardOnCustom(), MainNotifyMessagesOnCustom(), MainNotifyMissedCallsOnCustom(), MainNotifyNetworkOnCustom(), MainSetDoNotDisturbModeOnCustom(), MainWeatherOnTimer(), SettingDisplayBrightnessDownButtonOnPress(), SettingDisplayBrightnessUpButtonOnPress(), SettingDisplayCancelButtonOnPress(), SettingDisplayOnEnter(), SettingDisplayOnLeave(), SettingEngineerMiscGuardOnEnter(), SettingEngineerMiscGuardWarnVolDownButtonOnPress(), SettingEngineerMiscGuardWarnVolUpButtonOnPress(), SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainMicVolDownButtonOnPress(), SettingOutdoorMainMicVolUpButtonOnPress(), SettingOutdoorMainOnEnter(), SettingOutdoorMainPlayVolDownButtonOnPress(), SettingOutdoorMainPlayVolUpButtonOnPress(), SettingOutdoorMainRingVolDownButtonOnPress(), SettingOutdoorMainRingVolUpButtonOnPress(), SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioKeypadSoundVolDownButtonOnPress(), SettingPhoneAudioKeypadSoundVolUpButtonOnPress(), SettingPhoneAudioOnEnter(), SettingPhoneAudioRingVolDownButtonOnPress(), SettingPhoneAudioRingVolUpButtonOnPress(), SettingPhoneVoiceCancelButtonOnPress(), SettingPhoneVoiceMicVolDownButtonOnPress(), SettingPhoneVoiceMicVolUpButtonOnPress(), SettingPhoneVoiceOnEnter(), SettingPhoneVoiceVolDownButtonOnPress(), and SettingPhoneVoiceVolUpButtonOnPress().
void ituSpriteInit (ITUSprite * sprite)
Initializes the sprite widget.
Parameters
sprite The sprite widget to initialize.
void ituSpriteLoad (ITUSprite * sprite, uint32_t base)
Loads the sprite widget.
This is called by scene manager.
Parameters
sprite The sprite widget to load.
base The address in the scene file buffer.
void ituSpriteOnAction (ITUWidget * widget, ITUActionType action, char * param)
Do the specified action.
This is triggered by other widget's event.
Parameters
widget The sprite widget to do the action.
action The action to do.
param The parameter of action.
This is triggered by other widget's event.
Parameters
widget The sprite widget to do the action. It will bypass to current child widget.
action The action to do.
param The parameter of action.
void ituSpritePlay (ITUSprite * sprite, int frame)
Plays the sprite widget.
Parameters
sprite The sprite widget to play.
frame The specified frame of sprite widget to start playing. -1 indicates playing from current frame.
Referenced by HouseCurtainOffButtonOnPress(), and HouseCurtainOnButtonOnPress().
void ituSpriteSetDelay (ITUSprite * sprite, int delay)
Sets the delay value to the sprite widget.
Parameters
sprite The sprite widget to set.
delay The delay on playing. Unit is depend on ITU_EVENT_TIMER event.
void ituSpriteStop (ITUSprite * sprite)
Stops the playing sprite widget.
Parameters
sprite The playing sprite widget to stop.
Referenced by HouseCurtainStopButtonOnPress().
bool ituSpriteUpdate (ITUWidget * widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the sprite widget by specified event.
Parameters
widget The sprite widget to update.
ev The event to notify.
arg1 The event related argument #1.
arg2 The event related argument #2.
arg3 The event related argument #3.
Returns
true if the sprite widget is modified and need to be redraw, false if no need to be redraw.