ITE SoC SDK: String
String
ITE DoorBell Indoor Modules
Functions
char * StringGetRoomAddress (char *area, char *building, char *unit, char *floor, char *room, char *ext)
Gets address description by address information.
char * StringGetCameraPosition (char *area, char *building, char *unit)
Gets camera description by address information.
const char * StringGetSystemInfoArray (int *count)
Gets system information description.
const char * StringGetDeviceType (DeviceType type)
Gets device type description.
const char * StringGetCallLogType (CallLogType type)
Gets the description of calling log type.
const char * StringGetGuardSensor (GuardSensor sensor)
Gets the description of guard sensor.
const char * StringGetGuardSensorStatus (bool abnormal)
Gets the description of status of guard sensor.
const char * StringGetGuardStatus (GuardStatus status)
Gets the description of status of guard sensor.
const char * StringGetGuardType (GuardType type)
Gets the description of guard type.
const char * StringGetGuardState (GuardState state)
Gets the description of guard state.
const char * StringGetHouseStatus (HouseStatus status)
Gets the description of house status.
const char * StringGetHouseMode (HouseMode mode)
Gets the description of house mode.
const char * StringGetWorkMode (bool engineer)
Gets the description of working mode.
Detailed Description
Function Documentation
const char* StringGetCallLogType (CallLogType type)
Gets the description of calling log type.
Parameters
type The calling log type.
Returns
the string of calling log type.
Definition at line 543 of file string.c.
References Config::lang, stringCallLogArray, stringCallLogArrayChs, stringCallLogArrayCht, and theConfig.
Referenced by PhoneLogMissedViewButtonOnPress(), PhoneLogReceivedViewButtonOnPress(), and PhoneLogSentViewButtonOnPress().
char* StringGetCameraPosition (char * area, char * building, char * unit)
Gets camera description by address information.
Parameters
area The area code of address.
building The building code of address.
unit The unit code of address.
Returns
the camera string. Remember to free it after used to avoid memory leak.
Definition at line 450 of file string.c.
References Config::lang, STR_CAMARA, STR_CAMERA_CHS, STR_CAMERA_CHT, stringAddressArray, stringAddressArrayChs, stringAddressArrayCht, and theConfig.
Referenced by CameraListBoxOnLoad(), CameraOutdoorOnEnter(), and GetDeviceInfo().
const char* StringGetDeviceType (DeviceType type)
Gets device type description.
Parameters
type The device type.
Returns
the device type string.
Definition at line 527 of file string.c.
References Config::lang, stringDeviceTypes, stringDeviceTypesChs, stringDeviceTypesCht, and theConfig.
Referenced by CalledIncomingOnCustom(), CallingIncomingOnCustom(), CaptureCreateTask(), CaptureSnapshot(), CaptureStopRecord(), GetDeviceInfo(), SettingOutdoorMainMessageListBoxOnLoad(), and SettingSystemMessageListBoxOnLoad().
const char* StringGetGuardSensor (GuardSensor sensor)
Gets the description of guard sensor.
Parameters
sensor The guard sensor.
Returns
the string of guard sensor.
Definition at line 559 of file string.c.
References Config::lang, stringGuardSensorArray, stringGuardSensorArrayChs, stringGuardSensorArrayCht, and theConfig.
Referenced by GuardCheckSensorListBoxOnLoad(), GuardLogSensorListBoxOnLoad(), and GuardStatusSensorListBoxOnLoad().
const char* StringGetGuardSensorStatus (bool abnormal)
Gets the description of status of guard sensor.
Parameters
abnormal Is abnormal or not.
Returns
the string of status of guard sensor.
Definition at line 575 of file string.c.
References Config::lang, stringGuardSensorStatusArray, stringGuardSensorStatusArrayChs, stringGuardSensorStatusArrayCht, and theConfig.
Referenced by GuardCheckStatusListBoxOnLoad().
const char* StringGetGuardState (GuardState state)
Gets the description of guard state.
Returns
the string of guard state.
Definition at line 623 of file string.c.
References Config::lang, stringGuardStateArray, stringGuardStateArrayChs, stringGuardStateArrayCht, and theConfig.
Referenced by GuardLogTypeListBoxOnLoad().
const char* StringGetGuardStatus (GuardStatus status)
Gets the description of status of guard sensor.
Parameters
status The status of guard sensor.
Returns
the string of status of guard sensor.
Definition at line 591 of file string.c.
References Config::lang, stringGuardStatusArray, stringGuardStatusArrayChs, stringGuardStatusArrayCht, and theConfig.
Referenced by create_response(), GuardLogTypeListBoxOnLoad(), and GuardStatusTypeListBoxOnLoad().
const char* StringGetGuardType (GuardType type)
Gets the description of guard type.
Returns
the string of guard type.
Definition at line 607 of file string.c.
References Config::lang, stringGuardTypeArray, stringGuardTypeArrayChs, stringGuardTypeArrayCht, and theConfig.
Referenced by GuardLogSensorListBoxOnLoad().
const char* StringGetHouseMode (HouseMode mode)
Gets the description of house mode.
Parameters
mode The house mode.
Returns
the string of house mode.
Definition at line 655 of file string.c.
References Config::lang, stringHouseModeArray, stringHouseModeArrayChs, stringHouseModeArrayCht, and theConfig.
Referenced by HouseModeIndoorButtonOnPress(), HouseModeOutdoorButtonOnPress(), and HouseModeSleepButtonOnPress().
const char* StringGetHouseStatus (HouseStatus status)
Gets the description of house status.
Parameters
status The house status.
Returns
the string of house status.
Definition at line 639 of file string.c.
References Config::lang, stringHouseStatusArray, stringHouseStatusArrayChs, stringHouseStatusArrayCht, and theConfig.
Referenced by HouseAirConditionerStatusListBoxOnLoad(), HouseCurtainStatusListBoxOnLoad(), HouseLightStatusListBoxOnLoad(), HouseModeStatusListBoxOnLoad(), HouseModeStatusListBoxOnSelection(), HousePlugStatusListBoxOnLoad(), and HouseTVStatusListBoxOnLoad().
char* StringGetRoomAddress (char * area, char * building, char * unit, char * floor, char * room, char * ext)
Gets address description by address information.
Parameters
area The area code of address.
building The building code of address.
unit The unit code of address.
floor The floor code of address.
room The room code of address.
ext The ext code of address. Can be NULL if not exist.
Returns
the address string. Remember to free it after used to avoid memory leak.
Definition at line 355 of file string.c.
References Config::lang, stringAddressArray, stringAddressArrayChs, stringAddressArrayCht, and theConfig.
Referenced by CalledIncomingOnCustom(), CalledIncomingShow(), CalledWaitingConfirmButtonOnPress(), CalledWaitingConfirmButtonOnSimulatePressing(), CallingCall(), CallingCallByIP(), CallingCallManager(), CallingIncomingOnCustom(), CallingWaitingConfirmButtonOnPress(), CallingWaitingConfirmButtonOnSimulatePressing(), GetDeviceInfo(), PhoneContactsAddShow(), PhoneContactsModifyShow(), PhoneContactsRoomListBoxOnLoad(), PhoneLogMissedRoomListBoxOnLoad(), PhoneLogReceivedRoomListBoxOnLoad(), PhoneLogSentRoomListBoxOnLoad(), SettingOutdoorMainMessageListBoxOnLoad(), SettingSystemMessageListBoxOnLoad(), VideoMemoCreateTask(), VideoMemoStopRecord(), and VideoRecordIncomingShow().
const char* StringGetSystemInfoArray (int * count)
Gets system information description.
Parameters
count The pointer to retrieve the count of entry.
Returns
the array of system information strings.
Definition at line 502 of file string.c.
References Config::lang, stringSystemInfoArray, stringSystemInfoArrayChs, stringSystemInfoArrayCht, and theConfig.
Referenced by SettingSystemItemListBoxOnLoad(), and SettingSystemMessageListBoxOnLoad().
const char* StringGetWorkMode (bool engineer)
Gets the description of working mode.
Parameters
engineer Is in engineer mode or not.
Returns
the string of working mode.
Definition at line 671 of file string.c.
References Config::lang, stringWorkModeArray, stringWorkModeArrayChs, stringWorkModeArrayCht, and theConfig.
Referenced by create_response(), and SettingSystemMessageListBoxOnLoad().