ITE SoC SDK: Memory Debug
Memory Debug
ITE Hardware Library
Enumerations
enum ITHMemDbgModule { ITH_MEMDBG0 = ITH_MEMDBG0_BASE_REG, ITH_MEMDBG1 = ITH_MEMDBG1_BASE_REG }
Memory Debug module definition.
enum ITHMemDbgMode { ITH_MEMDBG_READWRITE = 0x0, ITH_MEMDGB_READONLY = 0x1, ITH_MEMDGB_WRITEONLY = 0x2 }
Memory Debug mode definition.
Functions
static void ithMemDbgEnableIntr (void)
Enables memory debug.
static void ithMemDbgDisableIntr (void)
Disable memory debug.
static void ithMemDbgEnable (ITHMemDbgModule module)
Enables memory debug.
static void ithMemDbgDisable (ITHMemDbgModule module)
Disables memory debug.
static void ithMemDbgSetMode (ITHMemDbgModule module, ITHMemDbgMode mode)
Sets memory debug mode.
static void ithMemDbgSetRange (ITHMemDbgModule module, uint32_t topAddr, uint32_t bottomAddr)
Sets memory debug range.
static uint16_t ithMemDbgGetStatus (void)
Gets memory debug status.
static int32_t ithMemDbgGetFlag (ITHMemDbgModule module)
Gets memory debug status.
static void ithMemDbgClearIntr (void)
Clear interrupt.
Detailed Description
Enumeration Type Documentation
enum ITHMemDbgMode
Memory Debug mode definition.
Enumerator
ITH_MEMDBG_READWRITE
Both of Read and Write Requests.
ITH_MEMDGB_READONLY
Only Read Request.
ITH_MEMDGB_WRITEONLY
Only Write Request.
Definition at line 1059 of file ith.h.
enum ITHMemDbgModule
Memory Debug module definition.
Enumerator
ITH_MEMDBG0
MEMDBG #0.
ITH_MEMDBG1
MEMDBG #1.
Definition at line 1050 of file ith.h.
Function Documentation
static void ithMemDbgClearIntr (void) inline static
Clear interrupt.
Definition at line 1205 of file ith.h.
References ITH_MEMSTAT_INTR_REG, ITH_MEMSTAT_INTR_WC_BIT, and ithSetRegBitH().
static void ithMemDbgDisable (ITHMemDbgModule module) inline static
Disables memory debug.
Parameters
module The memory debug module.
Definition at line 1119 of file ith.h.
References ITH_MEMDBG0, ITH_MEMDBG_EN_BIT, ITH_MEMDBG_EN_REG, ITH_MEMSTAT_INTR_REG, ITH_MEMSTAT_INTR_WP0_BIT, ITH_MEMSTAT_INTR_WP1_BIT, and ithClearRegBitH().
static void ithMemDbgDisableIntr (void) inline static
Disable memory debug.
interrupt
Definition at line 1085 of file ith.h.
References ITH_MEMSTAT_INTR_EN_BIT, ITH_MEMSTAT_INTR_REG, and ithClearRegBitH().
static void ithMemDbgEnable (ITHMemDbgModule module) inline static
Enables memory debug.
Parameters
module The memory debug module.
Definition at line 1101 of file ith.h.
References ITH_MEMDBG0, ITH_MEMDBG_EN_BIT, ITH_MEMDBG_EN_REG, ITH_MEMSTAT_INTR_REG, ITH_MEMSTAT_INTR_WP0_BIT, ITH_MEMSTAT_INTR_WP1_BIT, and ithSetRegBitH().
static void ithMemDbgEnableIntr (void) inline static
Enables memory debug.
interrupt
Definition at line 1070 of file ith.h.
References ITH_MEMSTAT_INTR_EN_BIT, ITH_MEMSTAT_INTR_REG, and ithSetRegBitH().
static int32_t ithMemDbgGetFlag (ITHMemDbgModule module) inline static
Gets memory debug status.
Parameters
module The memory debug module.
Returns
The flag.
Definition at line 1174 of file ith.h.
References ITH_MEMDBG0, and ithMemDbgGetStatus().
static uint16_t ithMemDbgGetStatus (void) inline static
Gets memory debug status.
Returns
The status.
Definition at line 1163 of file ith.h.
References ITH_MEMDBG_FLAG_REG, and ithReadRegH().
Referenced by ithMemDbgGetFlag().
static void ithMemDbgSetMode (ITHMemDbgModule module, ITHMemDbgMode mode) inline static
Sets memory debug mode.
Parameters
module The memory debug module.
mode The memory debug mode.
Definition at line 1138 of file ith.h.
References ITH_MEMDBG_MODE_BIT, ITH_MEMDBG_MODE_MASK, ITH_MEMDBG_MODE_REG, and ithWriteRegMaskH().
static void ithMemDbgSetRange (ITHMemDbgModule module, uint32_t topAddr, uint32_t bottomAddr) inline static
Sets memory debug range.
Parameters
module The memory debug module.
topAddr The top address.
bottomAddr The bottom address.
Definition at line 1150 of file ith.h.
References ITH_MEMDBG_BOT_ADDR_HI_BIT, ITH_MEMDBG_BOT_ADDR_HI_MASK, ITH_MEMDBG_BOT_ADDR_HI_REG, ITH_MEMDBG_BOT_ADDR_LO_REG, ITH_MEMDBG_TOP_ADDR_HI_BIT, ITH_MEMDBG_TOP_ADDR_HI_MASK, ITH_MEMDBG_TOP_ADDR_HI_REG, ITH_MEMDBG_TOP_ADDR_LO_REG, ithWriteRegH(), and ithWriteRegMaskH().