ITE SoC SDK: Register
Register
ITE Hardware Library
Macros
#define ITH_READ_REG_H(addr) *(uint16_t volatile*)(ITH_REG_BASE + ITH_HOST_BASE + (addr))
Reads host register value macro.
#define ITH_WRITE_REG_H(addr, data)
Writes host register value macro.
#define ITH_READ_REG_A(addr) *(uint32_t volatile*)(ITH_REG_BASE + (addr))
Reads AMBA register value macro.
#define ITH_WRITE_REG_A(addr, data)
Writes AMBA register value macro.
#define ITH_WRITE_REG_MASK_H(addr, data, mask)
Writes host register value with mask macro.
#define ITH_SET_REG_BIT_H(addr, bit)
Sets host register bit macro.
#define ITH_CLEAR_REG_BIT_H(addr, bit)
Clears host register bit macro.
#define ITH_WRITE_REG_MASK_A(addr, data, mask)
Writes AMBA register value with mask macro.
#define ITH_SET_REG_BIT_A(addr, bit)
Sets AMBA register bit macro.
#define ITH_CLEAR_REG_BIT_A(addr, bit)
Clears AMBA register bit macro.
Functions
static uint16_t ithReadRegH (uint16_t addr)
Reads host register value.
static void ithWriteRegH (uint16_t addr, uint16_t data)
Writes host register value.
static uint32_t ithReadRegA (uint32_t addr)
Reads amba register value.
static void ithWriteRegA (uint32_t addr, uint32_t data)
Writes amba register value.
static uint8_t ithReadReg8 (uint32_t addr)
Reads amba register value, in byte.
static void ithWriteReg8 (uint32_t addr, uint8_t data)
Writes amba register value, in byte.
static uint16_t ithReadReg16 (uint32_t addr)
Reads amba register value, in 16-bit.
static void ithWriteReg16 (uint32_t addr, uint16_t data)
Writes amba register value, in 16-bit.
static void ithWriteRegMaskH (uint16_t addr, uint16_t data, uint16_t mask)
Writes host register value with mask.
static void ithSetRegBitH (uint16_t addr, unsigned int bit)
Sets host register bit.
static void ithClearRegBitH (uint16_t addr, unsigned int bit)
Clears host register bit.
static void ithWriteRegMaskA (uint32_t addr, uint32_t data, uint32_t mask)
Writes AMBA register value with mask.
static void ithSetRegBitA (uint32_t addr, unsigned int bit)
Sets AMBA register bit.
static void ithClearRegBitA (uint32_t addr, unsigned int bit)
Clears AMBA register bit.
Detailed Description
Macro Definition Documentation
#define ITH_CLEAR_REG_BIT_A (addr, bit)
Value:
do { \
        ITH_WRITE_REG_MASK_A((addr), 0, 0x1 << (bit)); \
    } while (0)
Clears AMBA register bit macro.
Parameters
addr the register address
bit the bit index to set to 0
Definition at line 617 of file ith.h.
#define ITH_CLEAR_REG_BIT_H (addr, bit)
Value:
do { \
        ITH_WRITE_REG_MASK_H((addr), 0, 0x1 << (bit)); \
    } while (0)
Clears host register bit macro.
Parameters
addr the register address
bit the bit index to set to 0
Definition at line 582 of file ith.h.
#define ITH_READ_REG_A (addr) *(uint32_t volatile*)(ITH_REG_BASE + (addr))
Reads AMBA register value macro.
Parameters
addr The register address.
Returns
The register value.
Definition at line 466 of file ith.h.
#define ITH_READ_REG_H (addr) *(uint16_t volatile*)(ITH_REG_BASE + ITH_HOST_BASE + (addr))
Reads host register value macro.
Parameters
addr The register address.
Returns
The register value.
Definition at line 446 of file ith.h.
#define ITH_SET_REG_BIT_A (addr, bit)
Value:
do { \
        ITH_WRITE_REG_MASK_A((addr), 0x1 << (bit), 0x1 << (bit)); \
    } while (0)
Sets AMBA register bit macro.
Parameters
addr the register address
bit the bit index to set to 1
Definition at line 606 of file ith.h.
#define ITH_SET_REG_BIT_H (addr, bit)
Value:
do { \
        ITH_WRITE_REG_MASK_H((addr), 0x1 << (bit), 0x1 << (bit)); \
    } while (0)
Sets host register bit macro.
Parameters
addr the register address
bit the bit index to set to 1
Definition at line 571 of file ith.h.
#define ITH_WRITE_REG_A (addr, data)
Value:
do { \
            *(uint32_t volatile*)(ITH_REG_BASE + (addr)) = (data); \
        } while (0)
Writes AMBA register value macro.
Parameters
addr The register address.
data The value to write.
Definition at line 475 of file ith.h.
#define ITH_WRITE_REG_H (addr, data)
Value:
do { \
            *(uint16_t volatile*)(ITH_REG_BASE + ITH_HOST_BASE + (addr)) = (data); \
        } while (0)
Writes host register value macro.
Parameters
addr The register address.
data The value to write.
Definition at line 455 of file ith.h.
#define ITH_WRITE_REG_MASK_A (addr, data, mask)
Value:
do { \
        ITH_WRITE_REG_A((addr), (ITH_READ_REG_A(addr) & ~(mask)) | ((data) & (mask))); \
    } while (0)
Writes AMBA register value with mask macro.
value = (value & mask) | (oldValue & ~mask)
Parameters
addr the register address
data the value will be operated
mask the mask
Definition at line 595 of file ith.h.
#define ITH_WRITE_REG_MASK_H (addr, data, mask)
Value:
do { \
        ITH_WRITE_REG_H((addr), (ITH_READ_REG_H(addr) & ~(mask)) | ((data) & (mask))); \
    } while (0)
Writes host register value with mask macro.
value = (value & mask) | (oldValue & ~mask)
Parameters
addr the register address
data the value will be operated
mask the mask
Definition at line 560 of file ith.h.
Function Documentation
static void ithClearRegBitA (uint32_t addr, unsigned int bit) inline static
Clears AMBA register bit.
Parameters
addr the register address
bit the bit index to set to 0
Definition at line 547 of file ith.h.
References ithWriteRegMaskA().
Referenced by ithIntrClearSwFiq(), ithIntrClearSwIrq(), ithIntrDisableFiq(), ithIntrDisableIrq(), ithRtcClearIntr(), ithRtcCtrlDisable(), and ithUartDisableIntr().
static void ithClearRegBitH (uint16_t addr, unsigned int bit) inline static
Clears host register bit.
Parameters
addr the register address
bit the bit index to set to 0
Definition at line 512 of file ith.h.
References ithWriteRegMaskH().
Referenced by ithDisableSpreadSpectrum(), ithMemDbgDisable(), ithMemDbgDisableIntr(), and ithMemStatServCounterDisable().
static uint16_t ithReadReg16 (uint32_t addr) inline static
Reads amba register value, in 16-bit.
Parameters
addr The register address.
Returns
The register value.
Definition at line 424 of file ith.h.
References ITH_REG_BASE.
static uint8_t ithReadReg8 (uint32_t addr) inline static
Reads amba register value, in byte.
Parameters
addr The register address.
Returns
The register value.
Definition at line 402 of file ith.h.
References ITH_REG_BASE.
static uint32_t ithReadRegA (uint32_t addr) inline static
Reads amba register value.
Parameters
addr The register address.
Returns
The register value.
Definition at line 380 of file ith.h.
References ITH_REG_BASE.
Referenced by ithDmaIsBusy(), ithGetRevisionId(), ithIntrGetStatusFiq(), ithIntrGetStatusIrq(), ithLcdGetBaseAddrA(), ithLcdGetHeight(), ithLcdGetPitch(), ithLcdGetWidth(), ithNandGetPageSize(), ithRtcGetIntrState(), ithRtcGetState(), ithUartClearIntr(), ithUartGetChar(), ithUartGetFifoDepth(), ithUartIsRxReady(), ithUartIsTxEmpty(), ithUartIsTxFull(), ithUartIsTxWIthFifoEmpty(), and ithWriteRegMaskA().
static uint16_t ithReadRegH (uint16_t addr) inline static
Reads host register value.
Parameters
addr The register address.
Returns
The register value.
Definition at line 358 of file ith.h.
References ITH_HOST_BASE, and ITH_REG_BASE.
Referenced by ithClockGetRatio(), ithClockGetSource(), ithGetDeviceId(), ithGetRevisionId(), ithIspGetClockSource(), ithIsTilingModeOn(), ithLcdGetBaseAddrA(), ithLcdGetHeight(), ithLcdGetPitch(), ithLcdGetWidth(), ithMemDbgGetStatus(), ithMemStatGetAllServCount(), ithMemStatGetServ0Num(), ithMemStatGetServ1Num(), ithMemStatGetServCount(), ithMemStatGetServNum(), ithStcGetBaseClock(), ithTilingPitch(), and ithWriteRegMaskH().
static void ithSetRegBitA (uint32_t addr, unsigned int bit) inline static
Sets AMBA register bit.
Parameters
addr the register address
bit the bit index to set to 1
Definition at line 536 of file ith.h.
References ithWriteRegMaskA().
Referenced by ithIntrClearFiq(), ithIntrClearIrq(), ithIntrEnableFiq(), ithIntrEnableIrq(), ithIntrSetSwFiq(), ithIntrSetSwIrq(), ithRtcCtrlEnable(), and ithUartEnableIntr().
static void ithSetRegBitH (uint16_t addr, unsigned int bit) inline static
Sets host register bit.
Parameters
addr the register address
bit the bit index to set to 1
Definition at line 501 of file ith.h.
References ithWriteRegMaskH().
Referenced by ithEnableSpreadSpectrum(), ithMemDbgClearIntr(), ithMemDbgEnable(), ithMemDbgEnableIntr(), and ithMemStatServCounterEnable().
static void ithWriteReg16 (uint32_t addr, uint16_t data) inline static
Writes amba register value, in 16-bit.
Parameters
addr The register address.
data The value to write.
Definition at line 435 of file ith.h.
References data, and ITH_REG_BASE.
static void ithWriteReg8 (uint32_t addr, uint8_t data) inline static
Writes amba register value, in byte.
Parameters
addr The register address.
data The value to write.
Definition at line 413 of file ith.h.
References data, and ITH_REG_BASE.
static void ithWriteRegA (uint32_t addr, uint32_t data) inline static
Writes amba register value.
Parameters
addr The register address.
data The value to write.
Definition at line 391 of file ith.h.
References data, and ITH_REG_BASE.
Referenced by ithAhb0SetCtrlReg(), ithDmaAbort(), ithDmaSetDstAddr(), ithDmaSetRequest(), ithDmaSetSrcAddr(), ithUartPutChar(), and ithWriteRegMaskA().
static void ithWriteRegH (uint16_t addr, uint16_t data) inline static
Writes host register value.
Parameters
addr The register address.
data The value to write.
Definition at line 369 of file ith.h.
References data, ITH_HOST_BASE, and ITH_REG_BASE.
Referenced by ithMemDbgSetRange(), ithMemStatSetServCountPeriod(), and ithWriteRegMaskH().
static void ithWriteRegMaskA (uint32_t addr, uint32_t data, uint32_t mask) inline static
Writes AMBA register value with mask.
value = (value & mask) | (oldValue & ~mask)
Parameters
addr the register address
data the value will be operated
mask the mask
Definition at line 525 of file ith.h.
References ithReadRegA(), and ithWriteRegA().
Referenced by ithClearRegBitA(), ithDmaSetRequest(), ithGpioEnable(), ithRtcSetPowerEnableIoSelection(), ithRtcSetState(), ithSetRegBitA(), ithUartDisableDmaMode2(), ithUartEnableDmaMode2(), ithUsbPhyDisableClock(), and ithUsbPhyEnableClock().
static void ithWriteRegMaskH (uint16_t addr, uint16_t data, uint16_t mask) inline static
Writes host register value with mask.
value = (value & mask) | (oldValue & ~mask)
Parameters
addr the register address
data the value will be operated
mask the mask
Definition at line 490 of file ith.h.
References ithReadRegH(), and ithWriteRegH().
Referenced by ithClearRegBitH(), ithMemDbgSetMode(), ithMemDbgSetRange(), ithMemStatSetServ0Request(), ithMemStatSetServ1Request(), ithSetRegBitH(), ithUsbPhyDisableClock(), and ithUsbPhyEnableClock().