ITE SoC SDK: Stream
Stream
ITE Common Library
Data Structures
struct ITCStreamTag
Stream interface definition.
struct ITCArrayStream
Array stream is a read-only, memory-based stream.
struct ITCBufferStream
Buffer stream is a ring-buffer, memory-based stream.
struct ITCFileStream
File stream is a file-based stream.
Macros
#define itcStreamClose(stream) ((ITCStream*)(stream))->Close((ITCStream*)(stream))
Closes a opened stream.
#define itcStreamSetClose(stream, close) (((ITCStream*)(stream))->Close = (close))
Sets Close callback function of stream.
#define itcStreamRead(stream, buf, size) ((ITCStream*)(stream))->Read((ITCStream*)(stream), (buf), (size))
Reads a opened stream.
#define itcStreamSetRead(stream, read) (((ITCStream*)(stream))->Read = (read))
Sets Read callback function of stream.
#define itcStreamWrite(stream, buf, size) ((ITCStream*)(stream))->Write((ITCStream*)(stream), (buf), (size))
Writes a opened stream.
#define itcStreamSetWrite(stream, write) (((ITCStream*)(stream))->Write = (write))
Sets Write callback function of stream.
#define itcStreamSeek(stream, offset, origin) ((ITCStream*)(stream))->Seek((ITCStream*)(stream), (offset), (origin))
Set position in a stream.
#define itcStreamSetSeek(stream, seek) (((ITCStream*)(stream))->Seek = (seek))
Sets Seek callback function of stream.
#define itcStreamTell(stream) ((ITCStream*)(stream))->Tell((ITCStream*)(stream))
Gets the current position of a stream.
#define itcStreamSetTell(stream, tell) (((ITCStream*)(stream))->Tell = (tell))
Sets Tell callback function of stream.
#define itcStreamAvailable(stream) ((ITCStream*)(stream))->Available((ITCStream*)(stream))
Gets the current available size of a stream.
#define itcStreamSetAvailable(stream, avail) (((ITCStream*)(stream))->Available = (avail))
Sets Available callback function of stream.
#define itcStreamReadLock(stream, bufptr, size) ((ITCStream*)(stream))->ReadLock((ITCStream*)(stream), (void**)(bufptr), (size))
Locks internal memory buffer of a stream for reading.
#define itcStreamSetReadLock(stream, readlock) (((ITCStream*)(stream))->ReadLock = (readlock))
Sets ReadLock callback function of stream.
#define itcStreamReadUnlock(stream, size) ((ITCStream*)(stream))->ReadUnlock((ITCStream*)(stream), (size))
Unlocks internal memory buffer of a stream for reading.
#define itcStreamSetReadUnlock(stream, readunlock) (((ITCStream*)(stream))->ReadUnlock = (readunlock))
Sets ReadUnlock callback function of stream.
#define itcStreamWriteLock(stream, bufptr, size) ((ITCStream*)(stream))->WriteLock((ITCStream*)(stream), (void**)(bufptr), (size))
Locks internal memory buffer of a stream for writing.
#define itcStreamSetWriteLock(stream, writelock) (((ITCStream*)(stream))->WriteLock = (writelock))
Sets WriteLock callback function of stream.
#define itcStreamWriteUnlock(stream, size) ((ITCStream*)(stream))->WriteUnlock((ITCStream*)(stream), (size))
Unlocks internal memory buffer of a stream for writing.
#define itcStreamSetWriteUnlock(stream, writeunlock) (((ITCStream*)(stream))->WriteUnlock = (writeunlock))
Sets WriteUnlock callback function of stream.
Typedefs
typedef struct ITCStreamTag ITCStream
Stream interface definition.
Functions
void itcStreamOpen (ITCStream *stream)
Opens a stream.
int itcArrayStreamOpen (ITCArrayStream *astream, const char *array, int size)
Opens a array stream.
int itcBufferStreamOpen (ITCBufferStream *bstream, int size)
Opens a buffer stream.
int itcFileStreamOpen (ITCFileStream *fstream, const char *filename, bool write)
Opens a file stream.
int itcFileStreamClose (ITCStream *stream)
Closes a file stream.
Detailed Description
Macro Definition Documentation
#define itcStreamAvailable (stream) ((ITCStream*)(stream))->Available((ITCStream*)(stream))
Gets the current available size of a stream.
Parameters
stream Pointer referring to the opened stream.
Returns
Returns the current available size.
Definition at line 309 of file itc.h.
#define itcStreamClose (stream) ((ITCStream*)(stream))->Close((ITCStream*)(stream))
Closes a opened stream.
Parameters
stream Pointer referring to the opened stream.
Returns
Returns 0 if the stream was successfully closed. A return non-zero value indicates an error.
Definition at line 223 of file itc.h.
#define itcStreamRead (stream, buf, size) ((ITCStream*)(stream))->Read((ITCStream*)(stream), (buf), (size))
Reads a opened stream.
Parameters
stream Pointer referring to the opened stream.
buf Storage location for data.
size Maximum number of data unit, in bytes.
Returns
Returns the number of data unit read. A return value of -1 indicates an error.
Definition at line 241 of file itc.h.
#define itcStreamReadLock (stream, bufptr, size) ((ITCStream*)(stream))->ReadLock((ITCStream*)(stream), (void**)(bufptr), (size))
Locks internal memory buffer of a stream for reading.
Parameters
stream Pointer referring to the opened stream.
bufptr Internal memory buffer address to retrieve.
size buffer size to lock.
Returns
If successful, it returns the locked size. A return value of ITC_LOCK_FAIL indicates lock fail error.
Definition at line 327 of file itc.h.
#define itcStreamReadUnlock (stream, size) ((ITCStream*)(stream))->ReadUnlock((ITCStream*)(stream), (size))
Unlocks internal memory buffer of a stream for reading.
Parameters
stream Pointer referring to the opened stream.
size the locked buffer size.
Definition at line 343 of file itc.h.
#define itcStreamSeek (stream, offset, origin) ((ITCStream*)(stream))->Seek((ITCStream*)(stream), (offset), (origin))
Set position in a stream.
Parameters
stream Pointer referring to the opened stream.
offset Number of data unit from origin, in bytes.
origin Initial position.
Returns
Returns the offset, in data unit, of the new position from the beginning of the stream. The function returns -1 to indicate an error.
Definition at line 277 of file itc.h.
#define itcStreamSetAvailable (stream, avail) (((ITCStream*)(stream))->Available = (avail))
Sets Available callback function of stream.
Parameters
stream Pointer referring to the stream.
avail The callback function to set.
Definition at line 317 of file itc.h.
#define itcStreamSetClose (stream, close) (((ITCStream*)(stream))->Close = (close))
Sets Close callback function of stream.
Parameters
stream Pointer referring to the stream.
close The callback function to set.
Definition at line 231 of file itc.h.
#define itcStreamSetRead (stream, read) (((ITCStream*)(stream))->Read = (read))
Sets Read callback function of stream.
Parameters
stream Pointer referring to the stream.
read The callback function to set.
Definition at line 249 of file itc.h.
#define itcStreamSetReadLock (stream, readlock) (((ITCStream*)(stream))->ReadLock = (readlock))
Sets ReadLock callback function of stream.
Parameters
stream Pointer referring to the stream.
readlock The callback function to set.
Definition at line 335 of file itc.h.
#define itcStreamSetReadUnlock (stream, readunlock) (((ITCStream*)(stream))->ReadUnlock = (readunlock))
Sets ReadUnlock callback function of stream.
Parameters
stream Pointer referring to the stream.
readunlock The callback function to set.
Definition at line 351 of file itc.h.
#define itcStreamSetSeek (stream, seek) (((ITCStream*)(stream))->Seek = (seek))
Sets Seek callback function of stream.
Parameters
stream Pointer referring to the stream.
seek The callback function to set.
Definition at line 285 of file itc.h.
#define itcStreamSetTell (stream, tell) (((ITCStream*)(stream))->Tell = (tell))
Sets Tell callback function of stream.
Parameters
stream Pointer referring to the stream.
tell The callback function to set.
Definition at line 301 of file itc.h.
#define itcStreamSetWrite (stream, write) (((ITCStream*)(stream))->Write = (write))
Sets Write callback function of stream.
Parameters
stream Pointer referring to the stream.
write The callback function to set.
Definition at line 267 of file itc.h.
#define itcStreamSetWriteLock (stream, writelock) (((ITCStream*)(stream))->WriteLock = (writelock))
Sets WriteLock callback function of stream.
Parameters
stream Pointer referring to the stream.
writelock The callback function to set.
Definition at line 369 of file itc.h.
#define itcStreamSetWriteUnlock (stream, writeunlock) (((ITCStream*)(stream))->WriteUnlock = (writeunlock))
Sets WriteUnlock callback function of stream.
Parameters
stream Pointer referring to the stream.
writeunlock The callback function to set.
Definition at line 385 of file itc.h.
#define itcStreamTell (stream) ((ITCStream*)(stream))->Tell((ITCStream*)(stream))
Gets the current position of a stream.
Parameters
stream Pointer referring to the opened stream.
Returns
Returns the current stream position.
Definition at line 293 of file itc.h.
#define itcStreamWrite (stream, buf, size) ((ITCStream*)(stream))->Write((ITCStream*)(stream), (buf), (size))
Writes a opened stream.
Parameters
stream Pointer referring to the opened stream.
buf Data to be written.
size Number of data unit, in bytes.
Returns
If successful, it returns the number of data unit actually written. A return value of -1 indicates an error.
Definition at line 259 of file itc.h.
#define itcStreamWriteLock (stream, bufptr, size) ((ITCStream*)(stream))->WriteLock((ITCStream*)(stream), (void**)(bufptr), (size))
Locks internal memory buffer of a stream for writing.
Parameters
stream Pointer referring to the opened stream.
bufptr Internal memory buffer address to retrieve.
size buffer size to lock.
Returns
If successful, it returns the locked size. A return value of ITC_LOCK_FAIL indicates lock fail error.
Definition at line 361 of file itc.h.
#define itcStreamWriteUnlock (stream, size) ((ITCStream*)(stream))->WriteUnlock((ITCStream*)(stream), (size))
Unlocks internal memory buffer of a stream for writing.
Parameters
stream Pointer referring to the opened stream.
size the locked buffer size.
Definition at line 377 of file itc.h.
Typedef Documentation
typedef struct ITCStreamTag ITCStream
Stream interface definition.
Function Documentation
int itcArrayStreamOpen (ITCArrayStream * astream, const char * array, int size)
Opens a array stream.
Parameters
astream Pointer referring to the array stream.
array Array buffer.
size Array size.
Returns
Returns 0 if the array stream was successfully opened. A return non-zero value indicates an error.
Referenced by ahc_echo(), create_response(), and DownloadPackage().
int itcBufferStreamOpen (ITCBufferStream * bstream, int size)
Opens a buffer stream.
Parameters
bstream Pointer referring to the buffer stream.
size Buffer size.
Returns
Returns 0 if the buffer stream was successfully opened. A return non-zero value indicates an error.
int itcFileStreamClose (ITCStream * stream)
Closes a file stream.
Parameters
stream Pointer referring to the file stream.
Returns
Returns 0 if the file stream was successfully closed. A return non-zero value indicates an error.
int itcFileStreamOpen (ITCFileStream * fstream, const char * filename, bool write)
Opens a file stream.
Parameters
fstream Pointer referring to the file stream.
filename The file path to open.
write Indicates the stream is for reading or writting.
Returns
Returns 0 if the file stream was successfully opened. A return non-zero value indicates an error.
Referenced by OpenUsbPackage().
void itcStreamOpen (ITCStream * stream)
Opens a stream.
Parameters
stream Pointer referring to the stream.