ITE SoC SDK: Clock
Clock
ITE Hardware Library
Enumerations
enum ITHClock {
ITH_BCLK = ITH_HOST_CLK1_REG, ITH_MCLK = ITH_MEM_CLK1_REG, ITH_NCLK = ITH_AHB_CLK1_REG, ITH_WCLK = ITH_APB_CLK1_REG,
ITH_FCLK = ITH_ARM_CLK1_REG
}
Clock definition.
enum ITHClockSource {
ITH_CLK_PLL1_OUTPUT1 = 0, ITH_CLK_PLL1_OUTPUT2 = 1, ITH_CLK_PLL2_OUTPUT1 = 2, ITH_CLK_PLL2_OUTPUT2 = 3,
ITH_CLK_PLL3_OUTPUT1 = 4, ITH_CLK_PLL3_OUTPUT2 = 5, ITH_CLK_CKSYS = 6, ITH_CLK_RING_OSC = 7
}
Clock output definition.
enum ITHPll { ITH_PLL1 = 0, ITH_PLL2 = 1, ITH_PLL3 = 2 }
PLL definition.
enum ITHSpreadSpectrumMode { ITH_SP_UP = 0, ITH_SP_DOWN = 1, ITH_SP_CENTER = 2 }
Clock output definition.
Functions
void ithClockInit (void)
Initialize clock module.
void ithClockSleep (void)
Enter sleep mode on clock module.
void ithClockWakeup (void)
Wakeup from sleep mode on clock module.
void ithClockSuspend (void)
Enter suspend mode on clock module.
void ithClockResume (void)
Resume from suspend mode on clock module.
static ITHClockSource ithClockGetSource (ITHClock clk)
Gets clock source.
void ithClockSetSource (ITHClock clk, ITHClockSource src)
Sets clock source.
static unsigned int ithClockGetRatio (ITHClock clk)
void ithClockSetRatio (ITHClock clk, unsigned int ratio)
Sets clock ratio.
static unsigned int ithGetCpuClockRatio (void)
Gets CPU's clock ratio.
static void ithSetCpuClockRatio (unsigned int ratio)
Sets CPU's clock ratio.
static void ithSetCpuClockRatioMultiple (unsigned int ratio, unsigned int multiple)
Sets CPU's clock ratio mutiple.
static unsigned int ithGetMemClockRatio (void)
Gets memory's clock ratio.
static void ithSetMemClockRatio (unsigned int ratio)
Sets memory's clock ratio.
static void ithSetMemClockRatioMultiple (unsigned int ratio, unsigned int multiple)
Sets memory's clock ratio mutiple.
static unsigned int ithGetBusClockRatio (void)
Gets bus's clock ratio.
static void ithSetBusClockRatio (unsigned int ratio)
Sets bus's clock ratio.
static void ithSetBusClockRatioMultiple (unsigned int ratio, unsigned int multiple)
Sets bus's clock ratio mutiple.
unsigned int ithGetCpuClock (void)
Gets CPU clock.
unsigned int ithGetMemClock (void)
Gets memory clock.
unsigned int ithGetBusClock (void)
Gets bus clock.
void ithClockEnablePll (ITHPll pll)
Enables specified PLL.
void ithClockDisablePll (ITHPll pll)
Disables specified PLL.
static void ithEnableSpreadSpectrum (ITHPll pll)
Enables spread spectrum.
static void ithDisableSpreadSpectrum (ITHPll pll)
Disables spread spectrum.
void ithSetSpreadSpectrum (ITHPll pll, ITHSpreadSpectrumMode mode, uint32_t width, uint32_t freq)
Sets spread spectrum parameters.
void ithClockStats (void)
Print clock information.
Detailed Description
Enumeration Type Documentation
enum ITHClock
Clock definition.
Enumerator
ITH_BCLK
BCLK.
ITH_MCLK
MCLK.
ITH_NCLK
NCLK.
ITH_WCLK
WCLK.
ITH_FCLK
FCLK.
Definition at line 759 of file ith.h.
enum ITHClockSource
Clock output definition.
Enumerator
ITH_CLK_PLL1_OUTPUT1
From PLL1 output1.
ITH_CLK_PLL1_OUTPUT2
From PLL1 output2.
ITH_CLK_PLL2_OUTPUT1
From PLL2 output1.
ITH_CLK_PLL2_OUTPUT2
From PLL2 output2.
ITH_CLK_PLL3_OUTPUT1
From PLL3 output1.
ITH_CLK_PLL3_OUTPUT2
From PLL3 output2.
ITH_CLK_CKSYS
From CKSYS (12MHz)
ITH_CLK_RING_OSC
From Ring OSC (200KHz)
Definition at line 771 of file ith.h.
enum ITHPll
PLL definition.
Enumerator
ITH_PLL1
PLL1.
ITH_PLL2
PLL2.
ITH_PLL3
PLL3.
Definition at line 786 of file ith.h.
enum ITHSpreadSpectrumMode
Clock output definition.
Enumerator
ITH_SP_UP
up-spread
ITH_SP_DOWN
down-spread
ITH_SP_CENTER
center-spread
Definition at line 999 of file ith.h.
Function Documentation
void ithClockDisablePll (ITHPll pll)
Disables specified PLL.
Parameters
pll The PLL to disable.
void ithClockEnablePll (ITHPll pll)
Enables specified PLL.
Parameters
pll The PLL to enable.
static unsigned int ithClockGetRatio (ITHClock clk) inline static
Definition at line 837 of file ith.h.
References ITH_MCLK_RATIO_BIT, ITH_MCLK_RATIO_MASK, and ithReadRegH().
Referenced by ithGetBusClockRatio(), ithGetCpuClockRatio(), and ithGetMemClockRatio().
static ITHClockSource ithClockGetSource (ITHClock clk) inline static
Gets clock source.
Parameters
clk The clock
Returns
The clock source
Definition at line 824 of file ith.h.
References ITH_MCLK_SRC_SEL_BIT, ITH_MCLK_SRC_SEL_MASK, and ithReadRegH().
void ithClockInit (void)
Initialize clock module.
void ithClockResume (void)
Resume from suspend mode on clock module.
void ithClockSetRatio (ITHClock clk, unsigned int ratio)
Sets clock ratio.
Parameters
clk The clock
ratio The clock ratio to set.
Referenced by ithSetBusClockRatio(), ithSetBusClockRatioMultiple(), ithSetCpuClockRatio(), ithSetCpuClockRatioMultiple(), ithSetMemClockRatio(), and ithSetMemClockRatioMultiple().
void ithClockSetSource (ITHClock clk, ITHClockSource src)
Sets clock source.
Parameters
clk The clock
src The clock source to set
void ithClockSleep (void)
Enter sleep mode on clock module.
void ithClockStats (void)
Print clock information.
void ithClockSuspend (void)
Enter suspend mode on clock module.
void ithClockWakeup (void)
Wakeup from sleep mode on clock module.
static void ithDisableSpreadSpectrum (ITHPll pll) inline static
Disables spread spectrum.
Parameters
pll PLL to disable.
Definition at line 1021 of file ith.h.
References ITH_PLL1_SET6_REG, ITH_PLL1_SP_EN_BIT, and ithClearRegBitH().
static void ithEnableSpreadSpectrum (ITHPll pll) inline static
Enables spread spectrum.
Parameters
pll PLL to enable.
Definition at line 1011 of file ith.h.
References ITH_PLL1_SET6_REG, ITH_PLL1_SP_EN_BIT, and ithSetRegBitH().
unsigned int ithGetBusClock (void)
Gets bus clock.
Returns
The bus clock value.
static unsigned int ithGetBusClockRatio (void) inline static
Gets bus's clock ratio.
Returns
The bus clock ratio.
Definition at line 929 of file ith.h.
References ITH_WCLK, and ithClockGetRatio().
unsigned int ithGetCpuClock (void)
Gets CPU clock.
Returns
The CPU clock value.
static unsigned int ithGetCpuClockRatio (void) inline static
Gets CPU's clock ratio.
Returns
The CPU clock ratio.
Definition at line 855 of file ith.h.
References ITH_FCLK, and ithClockGetRatio().
unsigned int ithGetMemClock (void)
Gets memory clock.
Returns
The memory clock value.
static unsigned int ithGetMemClockRatio (void) inline static
Gets memory's clock ratio.
Returns
The memory clock ratio.
Definition at line 892 of file ith.h.
References ITH_MCLK, and ithClockGetRatio().
static void ithSetBusClockRatio (unsigned int ratio) inline static
Sets bus's clock ratio.
Parameters
ratio The clock ratio to set.
Definition at line 939 of file ith.h.
References ITH_WCLK, and ithClockSetRatio().
static void ithSetBusClockRatioMultiple (unsigned int ratio, unsigned int multiple) static
Sets bus's clock ratio mutiple.
Parameters
ratio The recent clock ratio.
multiple The recent clock ratio`s multiple to set.
Definition at line 950 of file ith.h.
References ITH_WCLK, and ithClockSetRatio().
static void ithSetCpuClockRatio (unsigned int ratio) inline static
Sets CPU's clock ratio.
Parameters
ratio The clock ratio to set.
Definition at line 865 of file ith.h.
References ITH_FCLK, and ithClockSetRatio().
static void ithSetCpuClockRatioMultiple (unsigned int ratio, unsigned int multiple) static
Sets CPU's clock ratio mutiple.
Parameters
ratio The recent clock ratio.
multiple The recent clock ratio`s multiple to set.
Definition at line 876 of file ith.h.
References ITH_FCLK, and ithClockSetRatio().
static void ithSetMemClockRatio (unsigned int ratio) inline static
Sets memory's clock ratio.
Parameters
ratio The clock ratio to set.
Definition at line 902 of file ith.h.
References ITH_MCLK, and ithClockSetRatio().
static void ithSetMemClockRatioMultiple (unsigned int ratio, unsigned int multiple) static
Sets memory's clock ratio mutiple.
Parameters
ratio The recent clock ratio.
multiple The recent clock ratio`s multiple to set.
Definition at line 913 of file ith.h.
References ITH_MCLK, and ithClockSetRatio().
void ithSetSpreadSpectrum (ITHPll pll, ITHSpreadSpectrumMode mode, uint32_t width, uint32_t freq)
Sets spread spectrum parameters.
Parameters
pll PLL to set.
mode Spread spectrum mode.
width Modulation width in 1/1000 unit, recommand 1 ~ 5.
freq Modulation frequency in Hz, recommand 30K ~ 50KHz.