ITE SoC SDK: Network
Network
ITE DoorBell Indoor Modules
Functions
void NetworkInit (void)
Initializes network module.
void NetworkExit (void)
Exits network module.
void NetworkReset (void)
Resets network module.
bool NetworkIsReady (void)
Determines whether the network is ready or not.
bool NetworkServerIsReady (void)
Determines whether the control server is online or not.
void NetworkSntpUpdate (void)
Updates current time from SNTP server.
Detailed Description
Function Documentation
void NetworkExit (void)
Exits network module.
Definition at line 480 of file doorbell_indoor/network.c.
References networkQuit.
Referenced by SDL_main().
void NetworkInit (void)
Initializes network module.
Definition at line 444 of file doorbell_indoor/network.c.
Referenced by SDL_main().
bool NetworkIsReady (void)
Determines whether the network is ready or not.
Returns
true for ready; false for net ready yet.
Definition at line 32 of file doorbell_indoor/network.c.
Referenced by CheckNetwork(), EventUploadTask(), LinphoneRecordVideoMessage(), RemoteCallElevator(), RemoteCheckCard(), RemoteGetDontDisturbConfig(), RemoteGetOutdoorInfo(), RemoteOpenDoor(), RemoteSetDontDisturbConfig(), RemoteSetOutdoorConfig(), and UpdateIndicators().
void NetworkReset (void)
Resets network module.
Definition at line 489 of file doorbell_indoor/network.c.
bool NetworkServerIsReady (void)
Determines whether the control server is online or not.
Returns
true for online; false for offline.
Definition at line 37 of file doorbell_indoor/network.c.
References networkIsReady, and networkServerIsReady.
Referenced by EventUploadTask(), LinphonePlayVideoMessage(), MessageTextContentGet(), MessageTextDelete(), MessageTextListGet(), MessageVideoDelete(), MessageVideoListGet(), RemoteCheckCard(), RemoteGetServerInfo(), RemoteGetWeather(), and RemoteGetWeatherTask().
void NetworkSntpUpdate (void)
Updates current time from SNTP server.
Definition at line 425 of file doorbell_indoor/network.c.
References AddressBookGetManagerInfoArray(), i, DeviceInfo::ip, MAX_MANAGER_COUNT, and theCenterInfo.
Referenced by ScreenSaverRefresh(), and UpgradeOnTimer().