ITE SoC SDK: Scene
Scene
ITE DoorBell Outdoor Modules
Functions
void SceneInit (void)
Initializes scene module.
void SceneExit (void)
Exits scene module.
int SceneRun (void)
Runs the main loop to receive events, update and draw scene.
void SceneQuit (QuitValue value)
Quits the scene.
QuitValue SceneGetQuitValue (void)
Gets the current quit value.
bool SceneIsCallConnected (void)
Is the call connected or not.
void SceneSetRemoteIP (char *ip)
Sets the IP address of remote side.
int CallingCall (char *num)
Makes a phone call to the specified address.
bool CallingOnTimer (void)
Check if dial time is reached.
void SceneFlagReset (void)
Reset the calling ,callend flag.
void sceneFlagdail (void)
Reset the calling ,callend flag.
Detailed Description
Function Documentation
int CallingCall (char * num)
Makes a phone call to the specified address.
Parameters
num The floor and room code for .
Returns
0 for success, otherwise for fail.
Definition at line 27 of file doorbell_outdoor/layer_calling.c.
References AddressBookGetDeviceInfoArray(), DeviceInfo::area, DeviceInfo::building, callingManagerCount, callingManagerIndex, DEVICE_OUTDOOR, Config::dial_time, dialCountDown, dialLastTick, DeviceInfo::floor, HINT_SOUND_REDIAL, DeviceInfo::ip, LINPHONE_CASTOR3_MAX_IP_COUNT, LinphoneCallDevices(), LinphonePlayHintSound(), DeviceInfo::room, sceneFlagdail(), SceneSetRemoteIP(), theCenterInfo, theConfig, theDeviceInfo, DeviceInfo::type, and DeviceInfo::unit.
Referenced by CallingOnTimer().
bool CallingOnTimer (void)
Check if dial time is reached.
Returns
true for success, otherwise for fail.
Definition at line 127 of file doorbell_outdoor/layer_calling.c.
References CallingCall(), callingCountDown, callingLastTick, dialCountDown, dialLastTick, font::f, LinphoneTerminate(), SceneFlagReset(), and SceneHangUp().
void SceneExit (void)
Exits scene module.
Definition at line 142 of file doorbell_indoor/scene.c.
References commandQueue, ituFrameFuncExit(), ituFtExit(), ituM2dExit(), ituSceneExit(), ituSWExit(), ITUScene::root, and window.
Referenced by SDL_main().
void sceneFlagdail (void)
Reset the calling ,callend flag.
for polling call
Referenced by CallingCall().
void SceneFlagReset (void)
Reset the calling ,callend flag.
Definition at line 593 of file doorbell_outdoor/scene.c.
References callend_flag, calling_flag, currCameraCount, hint_sound, HINT_SOUND_REDIAL, and LinphonePlayHintSound().
Referenced by CallingOnTimer().
QuitValue SceneGetQuitValue (void)
Gets the current quit value.
Returns
The current quit value.
Definition at line 1476 of file doorbell_indoor/scene.c.
References quitValue.
Referenced by ahc_echo(), create_response(), and UpgradeOnEnter().
void SceneInit (void)
Initializes scene module.
Definition at line 86 of file doorbell_indoor/scene.c.
References callConnected, callReceived, camera_timeout, cameraViewing, commandQueue, currCallID, currCallingCount, currCameraCount, currRemoteAddr, DONOT_DISTURB_NONE, guardOn, guardRobAlarming, hotkeyDelay, inVideoState, isReady, ITU_GLYPH_8BPP, ituFrameFuncInit(), ituFtInit(), ituFtLoadFont(), ituGetDisplaySurface, ituLcdInit(), ituM2dInit(), ituSceneInit(), ituSceneSetFunctionTable(), ituSWInit(), lastDoNotDisturbMode, linphonec_call_allow_call_waiting_callback, linphonec_call_connected_notify_callback, linphonec_call_end_notify_callback, linphonec_call_error_notify_callback, linphonec_call_imcoming_received_notify_callback, linphonec_call_is_camera_viewing_callback, MAX_COMMAND_QUEUE_SIZE, networkReady, pendingCallID, pendingRemoteAddr, SceneCallAllowCallWaiting(), SceneCallConnected(), SceneCallEnd(), SceneCallError(), SceneCallReceived(), SceneCameraIsViewing(), textMsgCount, videoMsgCount, warnPlayDelay, and window.
Referenced by SDL_main().
bool SceneIsCallConnected (void)
Is the call connected or not.
Returns
true for connected, false for not connected yet.
Definition at line 1021 of file doorbell_indoor/scene.c.
References callConnected.
Referenced by PeripheralOpenDoor().
void SceneQuit (QuitValue value)
Quits the scene.
Parameters
value The reason to quit the scene.
Definition at line 1471 of file doorbell_indoor/scene.c.
References quitValue.
Referenced by ahc_echo(), CheckQuitValue(), create_response(), SettingEngineerMiscClearConfirmOnPress(), SettingEngineerMiscDefaultButtonOnPress(), SettingEngineerMiscTerminalConfirmButtonOnPress(), SettingEngineerMiscUpgradeButtonOnPress(), SettingEngineerNetworkSaveButtonOnPress(), and UpgradeOnTimer().
int SceneRun (void)
Runs the main loop to receive events, update and draw scene.
Returns
The QuitValue.
Definition at line 1078 of file doorbell_indoor/scene.c.
References AddressBookGetDeviceInfo(), callConnected, callend_flag, calling_flag, CallingCall(), CallingCallManager(), CallingOnTimer(), callReceived, callSpottedStatus, camera_timeout, CFG_CAMERA_TIMEOUT, cfgPrivateIni, CheckDoNotDisturb(), CheckGuard(), CheckMissedCalls(), CheckNetwork(), CheckNewMessages(), CheckQuitValue(), currCameraCount, currRemoteAddr, DEVICE_CENTER, DEVICE_MANAGER, EVENT_CALLOUT_START, EVENT_CUSTOM_ANSWER, EVENT_CUSTOM_CALL_INCOMMING, EVENT_CUSTOM_GUARD, EVENT_CUSTOM_MESSAGE, EVENT_CUSTOM_MISS_CALLS, EVENT_CUSTOM_NETWORK, EVENT_CUSTOM_SCREENSAVER, EventWriteCalloutLog(), EventWriteGuardLog(), GESTURE_THRESHOLD, GUARD_DISABLE, GUARD_INFRARED, guardOn, hint_sound, hotkeyDelay, i, INI_FILENAME, DeviceInfo::ip, ITH_GPIO_MODE0, ithGpioSet(), ithGpioSetMode(), ithGpioSetOut(), ITU_EVENT_KEYDOWN, ITU_EVENT_KEYUP, ITU_EVENT_MOUSEDOUBLECLICK, ITU_EVENT_MOUSEDOWN, ITU_EVENT_MOUSEMOVE, ITU_EVENT_MOUSEUP, ITU_EVENT_TIMER, ITU_EVENT_TOUCHSLIDEDOWN, ITU_EVENT_TOUCHSLIDELEFT, ITU_EVENT_TOUCHSLIDERIGHT, ITU_EVENT_TOUCHSLIDEUP, ituFlip, ituLayerGoto(), ituSceneDraw(), ituSceneFindWidget(), ituScenePreDraw(), ituSceneSendEvent(), ituSceneUpdate(), ituWidgetIsVisible, LinphoneAnswer(), LinphonePlayKeySound(), LinphoneTerminate(), mainVoiceMemoLayer, Config::missed_call_count, MS_PER_FRAME, pre_count, predrawDelay, ProcessCommand(), quitValue, SceneCameraIsViewing(), SceneHangUp(), SceneOpenDoor(), ScreenIsOff(), ScreenOff(), SCREENSAVER_BLANK, SCREENSAVER_NONE, Config::screensaver_type, ScreenSaverCheck(), ScreenSaverRefresh(), Screenshot(), SnapshotTake(), SPOTTED_INIT, font::t, textMsgCount, theConfig, theEntranceInfo, ToggleMute(), and DeviceInfo::type.
Referenced by SDL_main().
void SceneSetRemoteIP (char * ip)
Sets the IP address of remote side.
Parameters
the IP address of remote side.
Definition at line 993 of file doorbell_indoor/scene.c.
References currRemoteAddr.
Referenced by CallingCall(), CallingCallManager(), CallingErrorOnCustom(), CallingOnTimer(), CameraOutdoorOnEnter(), CameraWatch(), and SceneCameraSetViewing().