ITE SoC SDK: RadioBox
RadioBox
ITE UI Library » Widgets
Data Structures
struct ITURadioBox
Radio box widget definition.
Functions
void ituRadioBoxInit (ITURadioBox *radiobox)
Initializes the radio box widget.
void ituRadioBoxLoad (ITURadioBox *radiobox, uint32_t base)
Loads the radio box widget.
bool ituRadioBoxClone (ITUWidget *widget, ITUWidget **cloned)
Clones the radio box widget.
bool ituRadioBoxUpdate (ITUWidget *widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the radio box widget by specified event.
void ituRadioBoxDraw (ITUWidget *widget, ITUSurface *dest, int x, int y, uint8_t alpha)
Draws the radio box widget to the specified surface.
void ituRadioBoxOnAction (ITUWidget *widget, ITUActionType action, char *param)
Do the specified action.
void ituRadioBoxSetChecked (ITURadioBox *radiobox, bool checked)
Sets the radio box widget checked or not.
bool ituRadioBoxIsChecked (ITURadioBox *radiobox)
Is the radio box widget checked or not.
Detailed Description
Function Documentation
bool ituRadioBoxClone (ITUWidget * widget, ITUWidget ** cloned)
Clones the radio box widget.
Parameters
widget The radio box widget to clone.
cloned Retrieved cloned radio box widget.
Returns
true if clone is success, false otherwise.
void ituRadioBoxDraw (ITUWidget * widget, ITUSurface * dest, int x, int y, uint8_t alpha)
Draws the radio box widget to the specified surface.
Parameters
widget The radio box widget to draw.
dest The surface to draw to.
x The x coordinate of destination surface, in pixels.
y The y coordinate of destination surface, in pixels.
alpha the alpha value to do the constant alphablending to the surface.
void ituRadioBoxInit (ITURadioBox * radiobox)
Initializes the radio box widget.
Parameters
radiobox The radio box widget to initialize.
bool ituRadioBoxIsChecked (ITURadioBox * radiobox)
Is the radio box widget checked or not.
Parameters
radiobox The radio box widget.
Returns
Is checked or not.
Referenced by SettingDisplaySaveButtonOnPress(), SettingEngineerNetworkSaveButtonOnPress(), SettingEngineerSensorSaveButtonOnPress(), and SettingPhoneDisturbSaveButtonOnPress().
void ituRadioBoxLoad (ITURadioBox * radiobox, uint32_t base)
Loads the radio box widget.
This is called by scene manager.
Parameters
radiobox The radio box widget to load.
base The address in the scene file buffer.
void ituRadioBoxOnAction (ITUWidget * widget, ITUActionType action, char * param)
Do the specified action.
This is triggered by other widget's event.
Parameters
widget The radio box widget to do the action.
action The action to do.
param The parameter of action.
void ituRadioBoxSetChecked (ITURadioBox * radiobox, bool checked)
Sets the radio box widget checked or not.
Parameters
radiobox The radio box widget to set.
checked true for checked or false for un-checked.
Referenced by GuardModeOnEnter(), GuardModeStopKeypadCancelButtonOnPress(), GuardModeStopKeypadConfirmButtonOnPress(), HouseModeIndoorRadioBoxOnPress(), HouseModeOnEnter(), HouseModeOutdoorRadioBoxOnPress(), HouseModeSleepRadioBoxOnPress(), SettingDisplayCancelButtonOnPress(), SettingDisplayOnEnter(), SettingDisplayOnLeave(), SettingEngineerNetworkOnEnter(), SettingEngineerSensorCancelButtonOnPress(), SettingEngineerSensorOnEnter(), SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnEnter(), SettingPhoneDisturbCancelButtonOnPress(), SettingPhoneDisturbOnEnter(), SettingPhoneDisturbSaveButtonOnPress(), and SettingPhoneDisturbTimeConfirmButtonOnPress().
bool ituRadioBoxUpdate (ITUWidget * widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the radio box widget by specified event.
Parameters
widget The radio box widget to update.
ev The event to notify.
arg1 The event related argument #1.
arg2 The event related argument #2.
arg3 The event related argument #3.
Returns
true if the radio box widget is modified and need to be redraw, false if no need to be redraw.