ITE SoC SDK: Utility
Utility
Data Structures
struct ITHListTag
List node.
struct ITHVmemMcb
Video memory control block definition.
struct ITHVmem
Video memory management global data definition.
Typedefs
typedef struct ITHListTag ITHList
List node.
Functions
static uint16_t ithBswap16 (uint16_t value)
Converts 16-bit value to another endian integer.
static uint32_t ithBswap32 (uint32_t value)
Converts 32-bit value to another endian integer.
static uint64_t ithBswap64 (uint64_t value)
Converts 64-bit value to another endian integer.
static void ithMemset16 (void *dst, int val, size_t len)
Sets the first len words (16-bits) of the block of memory pointed by ptr to the specified value.
static void ithMemset32 (void *dst, int val, size_t len)
Sets the first len words (32-bits) of the block of memory pointed by ptr to the specified value.
void ithListPushFront (ITHList *list, void *node)
Pushes a node to the front of list.
void ithListPushBack (ITHList *list, void *node)
Pushes a node to the back of list.
void ithListInsertBefore (ITHList *list, void *listNode, void *node)
Inserts a node before another node.
void ithListInsertAfter (ITHList *list, void *listNode, void *node)
Inserts a node after another node.
void ithListRemove (ITHList *list, void *node)
Removes a node from a list.
void ithListClear (ITHList *list, void(*dtor)(void *))
Clears every nodes in a list.
char * ithUltob (char *s, unsigned long i)
Converts unsigned long value to binary format string.
void ithPrintRegH (uint16_t addr, unsigned int size)
Prints host register values.
void ithPrintRegA (uint32_t addr, unsigned int size)
Prints AMBA register values.
void ithPrintVram8 (uint32_t addr, unsigned int size)
Prints VRAM values on 8-bit format.
void ithPrintVram16 (uint32_t addr, unsigned int size)
Prints VRAM values on 16-bit format.
void ithPrintVram32 (uint32_t addr, unsigned int size)
Prints VRAM values on 32-bit format.
int ithPrintf (const char *fmt,...)
General printf() function.
void ithVmemInit (ITHVmem *vmem)
Initializes video memory management module.
uint32_t ithVmemAlloc (uint32_t size)
Allocates video memory.
uint32_t ithVmemAlignedAlloc (uint32_t alignment, uint32_t size)
The ithVmemAlignedAlloc function is similar to the memalign function in that it returns a video memory of size bytes aligned to a multiple of alignment.
void ithVmemFree (uint32_t addr)
Releases allocated video memory.
void ithVmemStats (void)
Prints the video memory management status.
Variables
int(* ithPutcharFunc)(int c)
Putchar callback function for ithPrintf().
ITHVmem * ithVmem
Global video memory management instance.
Detailed Description
Typedef Documentation
typedef struct ITHListTag ITHList
List node.
Function Documentation
static uint16_t ithBswap16 (uint16_t value) inline static
Converts 16-bit value to another endian integer.
Parameters
value The value.
Returns
The converted value.
Definition at line 4584 of file ith.h.
Referenced by itpBetoh16().
static uint32_t ithBswap32 (uint32_t value) inline static
Converts 32-bit value to another endian integer.
Parameters
value The value.
Returns
The converted value.
Definition at line 4596 of file ith.h.
Referenced by itpBetoh32().
static uint64_t ithBswap64 (uint64_t value) inline static
Converts 64-bit value to another endian integer.
Parameters
value The value.
Returns
The converted value.
Definition at line 4610 of file ith.h.
Referenced by itpBetoh64().
void ithListClear (ITHList * list, void(*)(void *) dtor)
Clears every nodes in a list.
Parameters
list The list.
dtor The destructor to destroy every node. Can be MMP_NULL.
void ithListInsertAfter (ITHList * list, void * listNode, void * node)
Inserts a node after another node.
Parameters
list The list.
listNode The node will be before the inserted node.
node The node wiil be inserted.
void ithListInsertBefore (ITHList * list, void * listNode, void * node)
Inserts a node before another node.
Parameters
list The list.
listNode The node will be after the inserted node.
node The node wiil be inserted.
void ithListPushBack (ITHList * list, void * node)
Pushes a node to the back of list.
Parameters
list The list.
node The node wiil be pushed.
void ithListPushFront (ITHList * list, void * node)
Pushes a node to the front of list.
Parameters
list The list.
node The node wiil be pushed.
void ithListRemove (ITHList * list, void * node)
Removes a node from a list.
Parameters
list The list.
node The node wiil be removed.
static void ithMemset16 (void * dst, int val, size_t len) inline static
Sets the first len words (16-bits) of the block of memory pointed by ptr to the specified value.
Parameters
dst Pointer to the block of memory to fill.
val Value to be set. The value is passed as an int, but the function fills the block of memory using the uint16_t conversion of this value.
len Number of words (16-bits) to be set to the value.
Definition at line 4676 of file ith.h.
static void ithMemset32 (void * dst, int val, size_t len) inline static
Sets the first len words (32-bits) of the block of memory pointed by ptr to the specified value.
Parameters
dst Pointer to the block of memory to fill.
val Value to be set. The value is passed as an int, but the function fills the block of memory using the uint32_t conversion of this value.
len Number of words (32-bits) to be set to the value.
Definition at line 4691 of file ith.h.
int ithPrintf (const char * fmt, ...)
General printf() function.
Parameters
fmt Format control.
... Optional arguments.
Returns
the number of characters printed, or a negative value if an error occurs.
Referenced by SnapshotTake().
void ithPrintRegA (uint32_t addr, unsigned int size)
Prints AMBA register values.
Parameters
addr the start register address to dump
size the size of register block to dump
void ithPrintRegH (uint16_t addr, unsigned int size)
Prints host register values.
Parameters
addr the start register address to dump
size the size of register block to dump
void ithPrintVram16 (uint32_t addr, unsigned int size)
Prints VRAM values on 16-bit format.
Parameters
addr the start address to dump
size the size of block to dump
void ithPrintVram32 (uint32_t addr, unsigned int size)
Prints VRAM values on 32-bit format.
Parameters
addr the start address to dump
size the size of block to dump
void ithPrintVram8 (uint32_t addr, unsigned int size)
Prints VRAM values on 8-bit format.
Parameters
addr the start address to dump
size the size of block to dump
char* ithUltob (char * s, unsigned long i)
Converts unsigned long value to binary format string.
Parameters
s The binary format string.
i The unsigned long value.
uint32_t ithVmemAlignedAlloc (uint32_t alignment, uint32_t size)
The ithVmemAlignedAlloc function is similar to the memalign function in that it returns a video memory of size bytes aligned to a multiple of alignment.
Parameters
alignment The alignment that you want to use for the memory. This must be a multiple of size(void *).
size The amount of memory you want to allocate, in bytes.
Returns
Allocated memory address, or 0 if an error occurred
uint32_t ithVmemAlloc (uint32_t size)
Allocates video memory.
Parameters
size The amount of memory you want to allocate, in bytes.
Returns
Allocated memory address, or 0 if an error occurred
void ithVmemFree (uint32_t addr)
Releases allocated video memory.
Parameters
addr The allocated video memory address.
void ithVmemInit (ITHVmem * vmem)
Initializes video memory management module.
Parameters
vmem the video memory management instance
void ithVmemStats (void)
Prints the video memory management status.
Variable Documentation
int(* ithPutcharFunc)(int c)
Putchar callback function for ithPrintf().
Parameters
c the character to output
Returns
same as c
ITHVmem* ithVmem
Global video memory management instance.