ITE SoC SDK: Scene
Scene
ITE DoorBell Indoor Modules
Typedefs
typedef void(* SceneSettingEngineerNetworkIPCallback)(char *ip)
The function definition of getting inputted IP address.
typedef void(* SceneSettingEngineerNetworkMacCallback)(char *mac)
The function definition of getting inputted MAC address.
typedef void(* SceneSettingEngineerNetworkWiFiPasswordCallback)(char *password)
The function definition of getting inputted WiFi password.
typedef void(* SceneDeleteCallback)(bool del)
The function definition of deleting dialog.
typedef void(* SceneClearCallback)(bool clear)
The function definition of clearing dialog.
Enumerations
enum CustomEvent {
EVENT_CUSTOM_NETWORK = ITU_EVENT_CUSTOM, EVENT_CUSTOM_SCREENSAVER, EVENT_CUSTOM_MESSAGE, EVENT_CUSTOM_MESSAGE_VIDEO,
EVENT_CUSTOM_MESSAGE_TEXT, EVENT_CUSTOM_MESSAGE_RECORD, EVENT_CUSTOM_DISTURB_MODE, EVENT_CUSTOM_VOICEMEMO,
EVENT_CUSTOM_MISS_CALLS, EVENT_CUSTOM_CALL_INCOMMING, EVENT_CUSTOM_CALL_CONNECTED, EVENT_CUSTOM_CALL_END,
EVENT_CUSTOM_CALL_ERROR, EVENT_CUSTOM_CAMERA_TIMEOUT, EVENT_CUSTOM_GUARD, EVENT_CUSTOM_UPGRADE,
EVENT_CUSTOM_ANSWER
}
Custom event definition.
enum SPOTTED_STATUS { SPOTTED_NONE, SPOTTED_INIT, SPOTTED_REJECT, SPOTTED_ALLOW }
Functions
void SceneInit (void)
Initializes scene module.
void SceneExit (void)
Exits scene module.
void SceneLoad (void)
Loads ITU file.
int SceneRun (void)
Runs the main loop to receive events, update and draw scene.
void SceneOpenDoor (char *ip)
Opens the door on the remote device.
void SceneHangUp (void)
Hangs up the phone.
void SceneClearMissedCalls (void)
Clears all the missed calls.
void SceneUpdateIndicators (void)
Resets all the status of indicator UI.
int SceneCameraIsViewing (void)
Is watching camera or video message right now.
void SceneCameraSetViewing (bool viewing)
Sets the status of watching camera or video message.
void SceneSetReady (bool ready)
Sets the status of scene.
void SceneContinuePlayGuardAlarm (void)
Try to continue play guard alarm.
void SceneQuit (QuitValue value)
Quits the scene.
void SceneEnterVideoState (void)
scene erter to video state.
void SceneLeaveVideoState (void)
scene leave from video state.
QuitValue SceneGetQuitValue (void)
Gets the current quit value.
void SceneSetRemoteIP (char *ip)
Sets the IP address of remote side.
bool SceneIsCallConnected (void)
Is the call connected or not.
void SceneSetLastDoNotDisturbMode (DoNotDisturbMode mode)
Sets the last do not disturb mode.
void MainMenuNotifyUnplayVoiceMemo (int count)
Notifies the un-play count of voice memo to the scene.
void PhoneContactsAddShow (DeviceInfo *info, char *comment, ITULayer *lastLayer)
Sets the infomation to show on the add contact dialog.
void PhoneContactsModifyShow (DeviceInfo *info, char *comment, bool blacklist, char *refkey, ITULayer *lastLayer)
Sets the infomation to show on the modify contact dialog.
void PhoneContactsKeypadShow (DeviceInfo *info, ITULayer *lastLayer)
Sets the infomation to show on the contact address keypad dialog.
void PhoneContactsKeyboardShow (char *room, ITULayer *lastLayer)
Sets the infomation to show on the contact comment keyboard dialog.
void PhoneLogViewShow (char *name, char *room, char *time, char *duration, char *type, ITULayer *lastLayer)
Sets the infomation to show on the phone log detail dialog.
void MessageNotifyUnreadRecordMessage (int count)
Notifies the un-play count of captured recording files to the scene.
void MessagePhotoViewShow (char *topic, char *time, int id)
Sets the infomation to the playing video message screen.
void MessageRecordViewShow (char *topic, char *time, int id, CaptureEntry *entry)
Sets the infomation to the playing captured recording file screen.
void MessageServiceViewShow (char *image)
Sets the infomation to the viewing text message screen.
void MessageCommunityShow (char *input)
Sets the content to the community message screen.
void MessageCommunityKeyboardShow (char *input)
Sets the content to the inputing community message keyboard dialog.
void CameraViewShow (char *camera, char *ip)
Sets the infomation to the viewing camera fullscreen.
void SettingEngineerNetworkIPShow (char *ip, SceneSettingEngineerNetworkIPCallback func)
Shows the IP address setting dialog.
void SettingEngineerNetworkMacShow (char *mac, SceneSettingEngineerNetworkMacCallback func)
Shows the MAC address setting dialog.
void SettingEngineerNetworkWiFiPasswordShow (char *password, SceneSettingEngineerNetworkWiFiPasswordCallback func)
Shows the WiFi password setting dialog.
int CallingCall (char *area, char *building, char *unit, char *floor, char *room, char *ext)
Makes a phone call to the specified address.
int CallingCallByIP (char *ip)
Makes a phone call to the specified IP address.
int CallingCallManager (char *ip)
Makes a phone call to the specified IP address of administrator unit device.
void CalledIncomingShow (int id, char *addr, int video)
Sets the infomation to the receiving call screen.
void VideoRecordIncomingShow (int id, char *addr, int video)
Sets the infomation to the video record screen.
void SceneDeleteShow (SceneDeleteCallback func)
Shows the deleting dialog.
void SceneClearShow (SceneClearCallback func)
Shows the clearing dialog.
Variables
ITUScene theScene
Global instance variable of scene.
Detailed Description
Typedef Documentation
typedef void(* SceneClearCallback)(bool clear)
The function definition of clearing dialog.
Parameters
del true for confirm, false for cancel.
Definition at line 403 of file doorbell_indoor/scene.h.
typedef void(* SceneDeleteCallback)(bool del)
The function definition of deleting dialog.
Parameters
del true for confirm, false for cancel.
Definition at line 396 of file doorbell_indoor/scene.h.
typedef void(* SceneSettingEngineerNetworkIPCallback)(char *ip)
The function definition of getting inputted IP address.
Parameters
ip The inputted IP address.
Definition at line 300 of file doorbell_indoor/scene.h.
typedef void(* SceneSettingEngineerNetworkMacCallback)(char *mac)
The function definition of getting inputted MAC address.
Parameters
mac The inputted MAC address.
Definition at line 307 of file doorbell_indoor/scene.h.
typedef void(* SceneSettingEngineerNetworkWiFiPasswordCallback)(char *password)
The function definition of getting inputted WiFi password.
Parameters
password The inputted WiFi password.
Definition at line 314 of file doorbell_indoor/scene.h.
Enumeration Type Documentation
enum CustomEvent
Custom event definition.
Enumerator
EVENT_CUSTOM_NETWORK
Changes network status; The parameter "0" for not ready, "1" for ready. Custom0 event on GUI Designer.
EVENT_CUSTOM_SCREENSAVER
Ready to enter screensaver mode. Custom1 event on GUI Designer.
EVENT_CUSTOM_MESSAGE
Changes new message count status; The parameter is the string of new message count. Custom2 event on GUI Designer.
EVENT_CUSTOM_MESSAGE_VIDEO
Changes new video message count status; The parameter is the string of new video message count. Custom3 event on GUI Designer.
EVENT_CUSTOM_MESSAGE_TEXT
Changes new text message count status; The parameter is the string of new text message count. Custom4 event on GUI Designer.
EVENT_CUSTOM_MESSAGE_RECORD
Not used.
EVENT_CUSTOM_DISTURB_MODE
Changes do not disturb mode; The parameter is the string of DoNotDisturbMode. Custom6 event on GUI Designer.
EVENT_CUSTOM_VOICEMEMO
A new video memo request is incomming. The parameter is the string of IP address + call ID + having video or not (1 or 0). Custom7 event on GUI Designer.
EVENT_CUSTOM_MISS_CALLS
Changes the count status of missed calls; The parameter is the string of missed calls count. Custom8 event on GUI Designer.
EVENT_CUSTOM_CALL_INCOMMING
A new calling is incomming. The parameter is the string of IP address + call ID + having video or not (1 or 0). Custom9 event on GUI Designer.
EVENT_CUSTOM_CALL_CONNECTED
A calling is connected. Custom10 event on GUI Designer.
EVENT_CUSTOM_CALL_END
A calling is ended. Custom11 event on GUI Designer.
EVENT_CUSTOM_CALL_ERROR
A calling is error. The parameter is the string of SIP error code. Custom12 event on GUI Designer.
EVENT_CUSTOM_CAMERA_TIMEOUT
Watching camera is timeout. Custom13 event on GUI Designer.
EVENT_CUSTOM_GUARD
Changes guard mode; The parameter is "0" for disabling guard mode, "1" for enabling guard mode. Custom14 event on GUI Designer.
EVENT_CUSTOM_UPGRADE
Ready to upgrade address book or card list. Custom15 event on GUI Designer.
EVENT_CUSTOM_ANSWER
Answers current calling phone. Custom16 event on GUI Designer.
Definition at line 28 of file doorbell_indoor/scene.h.
enum SPOTTED_STATUS
Enumerator
SPOTTED_NONE
SPOTTED_INIT
SPOTTED_REJECT
SPOTTED_ALLOW
Definition at line 51 of file doorbell_indoor/scene.h.
Function Documentation
void CalledIncomingShow (int id, char * addr, int video)
Sets the infomation to the receiving call screen.
Parameters
id The call ID.
addr The IP address of target.
video 1 for has video, 0 for audio only.
Definition at line 431 of file layer_called.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, calledCountDown, calledID, calledInVideoState, calledVideoRecordEnable, CaptureGetPath(), DEVICE_INDOOR2, DEVICE_OUTDOOR, DEVICE_WALL, DeviceInfo::floor, ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, DeviceInfo::room, StringGetRoomAddress(), theDeviceInfo, theScene, DeviceInfo::type, and DeviceInfo::unit.
Referenced by MainNotifyCallIncomingOnCustom().
int CallingCall (char * area, char * building, char * unit, char * floor, char * room, char * ext)
Makes a phone call to the specified address.
Parameters
area The area code of address.
building The building code of address.
unit The unit code of address.
floor The floor code of address.
room The room code of address.
ext The ext code of address. Can be NULL if not exist.
Returns
0 for success, otherwise for fail.
Definition at line 295 of file doorbell_indoor/layer_calling.c.
References AddressBookGetDeviceInfo(), AddressBookGetDeviceInfoArray(), AddressBookGetDeviceIP(), callingInVideoState, callingManagerIndex, callingVideoRecordEnable, CaptureGetPath(), DEVICE_BUILDING, DEVICE_CENTER, DEVICE_ENTRANCE, DEVICE_INDOOR2, DEVICE_INTERCOM, DEVICE_OUTDOOR, DEVICE_WALL, Config::dial_time, dialCountDown, dialLastTick, ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, LINPHONE_CASTOR3_MAX_IP_COUNT, LinphoneCallDevices(), StringGetRoomAddress(), theConfig, theDeviceInfo, theScene, and DeviceInfo::type.
Referenced by CallError(), PhoneCallButtonOnPress(), PhoneContactsCallButtonOnPress(), PhoneLogMissedCallButtonOnPress(), PhoneLogReceivedCallButtonOnPress(), PhoneLogSentCallButtonOnPress(), and SceneRun().
int CallingCallByIP (char * ip)
Makes a phone call to the specified IP address.
Parameters
ip The IP address.
Returns
0 for success, otherwise for fail.
Definition at line 445 of file doorbell_indoor/layer_calling.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, callingInVideoState, callingManagerIndex, callingVideoRecordEnable, DEVICE_BUILDING, DEVICE_CENTER, DEVICE_ENTRANCE, DEVICE_INTERCOM, DEVICE_OUTDOOR, DEVICE_WALL, Config::dial_time, dialCountDown, dialLastTick, DeviceInfo::floor, ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, DeviceInfo::room, StringGetRoomAddress(), theConfig, theScene, DeviceInfo::type, and DeviceInfo::unit.
Referenced by PhoneCallButtonOnPress(), and PhoneLobbyCallButtonOnPress().
int CallingCallManager (char * ip)
Makes a phone call to the specified IP address of administrator unit device.
Parameters
ip The IP address of administrator unit device.
Returns
0 for success, otherwise for fail.
Definition at line 529 of file doorbell_indoor/layer_calling.c.
References AddressBookGetDeviceInfo(), AddressBookGetManagerInfoArray(), DeviceInfo::area, DeviceInfo::building, callingInVideoState, callingManagerCount, callingManagerIndex, callingManagerIPAddr, Config::dial_time, dialCountDown, dialLastTick, DeviceInfo::floor, DeviceInfo::ip, ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, MAX_MANAGER_COUNT, DeviceInfo::room, SceneSetRemoteIP(), StringGetRoomAddress(), theCenterInfo, theConfig, theScene, and DeviceInfo::unit.
Referenced by PhoneManagerButtonOnPress(), PhoneManagerCallButtonOnPress(), and SceneRun().
void CameraViewShow (char * camera, char * ip)
Sets the infomation to the viewing camera fullscreen.
Parameters
camera The camera name.
ip The IP address of camera.
Definition at line 81 of file layer_camera_view.c.
References AddressBookGetDeviceInfo(), cameraViewIsLeaving, cameraViewIsSnapshoting, cameraViewVideoRecordEnable, CaptureGetPath(), DEVICE_INDOOR2, ituSceneFindWidget(), ituTextSetString, theDeviceInfo, theScene, and DeviceInfo::type.
Referenced by CameraButtonOnPress().
void MainMenuNotifyUnplayVoiceMemo (int count)
Notifies the un-play count of voice memo to the scene.
Parameters
count The un-play count of voice memo.
Definition at line 11 of file layer_main_menu.c.
References ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, and theScene.
Referenced by MainVoiceMemoDeleteConfirmButtonOnPress(), MainVoiceMemoOnEnter(), MainVoiceMemoReload(), and MainVoiceMemoResetPlayButton().
void MessageCommunityKeyboardShow (char * input)
Sets the content to the inputing community message keyboard dialog.
Parameters
input The content string.
void MessageCommunityShow (char * input)
Sets the content to the community message screen.
Parameters
input The content string.
void MessageNotifyUnreadRecordMessage (int count)
Notifies the un-play count of captured recording files to the scene.
Parameters
count The un-play count of captured recording files.
Definition at line 14 of file layer_message.c.
References ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, and theScene.
Referenced by MessagePhotoOnEnter(), MessageRecordDeleteConfirmOnPress(), and MessageRecordViewOnEnter().
void MessagePhotoViewShow (char * topic, char * time, int id)
Sets the infomation to the playing video message screen.
Parameters
topic The topic of video message.
time The time of video message.
id The ID of video message.
Definition at line 34 of file layer_message_video_view.c.
References ituSceneFindWidget(), ituTextSetString, messagePhotoViewID, and theScene.
Referenced by MessagePhotoViewButtonOnPress().
void MessageRecordViewShow (char * topic, char * time, int id, CaptureEntry * entry)
Sets the infomation to the playing captured recording file screen.
Parameters
topic The topic of recording file.
time The time of recording file.
id The ID of recording file.
entry The captured entry.
Definition at line 36 of file layer_message_record_view.c.
References ituSceneFindWidget(), ituTextSetString, messageRecordViewID, and theScene.
Referenced by MessageRecordViewButtonOnPress().
void MessageServiceViewShow (char * image)
Sets the infomation to the viewing text message screen.
Parameters
image The URL of text message image.
Definition at line 44 of file layer_message_service_view.c.
References ituSceneFindWidget(), messageImageContent, messageImageContentSize, MessageServiceGetContent(), MessageTextContentGet(), and theScene.
Referenced by MessageServiceViewButtonOnPress().
void PhoneContactsAddShow (DeviceInfo * info, char * comment, ITULayer * lastLayer)
Sets the infomation to show on the add contact dialog.
Parameters
info The DeviceInfo of contact to add. Can be NULL.
comment The comment. Can be NULL.
lastLayer The widget of last layer. Can be NULL.
Definition at line 71 of file layer_phone_contacts_add.c.
References DeviceInfo::area, DeviceInfo::building, DeviceInfo::floor, ituCheckBoxSetChecked(), ituSceneFindWidget(), ituTextBoxSetString(), DeviceInfo::room, StringGetRoomAddress(), theScene, and DeviceInfo::unit.
Referenced by PhoneContactsAddButtonOnPress(), PhoneContactsKeyboardCloseButtonOnPress(), PhoneContactsKeyboardEnterButtonOnPress(), PhoneContactsKeypadCloseButtonOnPress(), PhoneContactsKeypadConfirmButtonOnPress(), PhoneLogMissedAddButtonOnPress(), PhoneLogReceivedAddButtonOnPress(), and PhoneLogSentAddButtonOnPress().
void PhoneContactsKeyboardShow (char * room, ITULayer * lastLayer)
Sets the infomation to show on the contact comment keyboard dialog.
Parameters
room The contact address.
lastLayer The widget of last layer.
Definition at line 396 of file layer_phone_contacts_keyboard.c.
References ituSceneFindWidget(), ituTextBoxSetString(), and theScene.
Referenced by PhoneContactsAddCommentButtonOnPress(), and PhoneContactsModifyCommentButtonOnPress().
void PhoneContactsKeypadShow (DeviceInfo * info, ITULayer * lastLayer)
Sets the infomation to show on the contact address keypad dialog.
Parameters
info The DeviceInfo of contact.
lastLayer The widget of last layer.
Definition at line 97 of file layer_phone_contacts_keypad.c.
References DeviceInfo::area, DeviceInfo::building, DeviceInfo::floor, ituSceneFindWidget(), ituTextBoxSetString(), phoneContactsKeypadAreaTextBox, phoneContactsKeypadBuildingTextBox, phoneContactsKeypadFloorTextBox, phoneContactsKeypadRoomTextBox, phoneContactsKeypadUnitTextBox, DeviceInfo::room, theScene, and DeviceInfo::unit.
Referenced by PhoneContactsAddRoomButtonOnPress(), and PhoneContactsModifyRoomButtonOnPress().
void PhoneContactsModifyShow (DeviceInfo * info, char * comment, bool blacklist, char * refkey, ITULayer * lastLayer)
Sets the infomation to show on the modify contact dialog.
Parameters
info The DeviceInfo of contact to add. Can be NULL.
comment The comment. Can be NULL.
blacklist The contact is in the black list or not.
refkey The reference key. Can be NULL.
lastLayer The widget of last layer. Can be NULL.
Definition at line 72 of file layer_phone_contacts_modify.c.
References DeviceInfo::area, DeviceInfo::building, DeviceInfo::floor, ituCheckBoxSetChecked(), ituSceneFindWidget(), ituTextBoxSetString(), phoneContactsModifyRefkey, DeviceInfo::room, StringGetRoomAddress(), theScene, and DeviceInfo::unit.
Referenced by PhoneContactsKeyboardCloseButtonOnPress(), PhoneContactsKeyboardEnterButtonOnPress(), PhoneContactsKeypadCloseButtonOnPress(), PhoneContactsKeypadConfirmButtonOnPress(), and PhoneContactsModifyButtonOnPress().
void PhoneLogViewShow (char * name, char * room, char * time, char * duration, char * type, ITULayer * lastLayer)
Sets the infomation to show on the phone log detail dialog.
Parameters
name The alias name of target on the address book.
room The contact address.
time The logging time.
duration The phone time length.
type The string of CallLogType.
lastLayer The widget of last layer.
Definition at line 23 of file layer_phone_log_view.c.
References CaptureGetPath(), CaptureGetSnapshotFileNameByTime(), data, font::f, ituIconLoadJpegData(), ituSceneFindWidget(), ituTextSetString, and theScene.
Referenced by PhoneLogMissedViewButtonOnPress(), PhoneLogReceivedViewButtonOnPress(), and PhoneLogSentViewButtonOnPress().
int SceneCameraIsViewing (void)
Is watching camera or video message right now.
Returns
1 for watching, 0 for not watching.
Definition at line 333 of file doorbell_indoor/scene.c.
References cameraViewing, and currCameraCount.
Referenced by CalledSourceListBoxOnSelection(), CameraListOnSelection(), CameraOnTimer(), LoadScene(), SceneCallAllowCallWaiting(), SceneInit(), and SceneRun().
void SceneCameraSetViewing (bool viewing)
Sets the status of watching camera or video message.
Parameters
viewing true for watching, false for not watching.
Definition at line 321 of file doorbell_indoor/scene.c.
References callReceived, cameraViewing, HOTKEY_DELAY, hotkeyDelay, and SceneSetRemoteIP().
Referenced by CameraOnEnter(), CameraOnLeave(), CameraOnTimer(), CameraOutdoorOnEnter(), CameraOutdoorOnLeave(), CameraViewOnLeave(), CameraWatch(), MainVoiceMemoRecordButtonOnPress(), MainVoiceMemoResetPlayButton(), MainVoiceMemoStopPlayButtonOnPress(), MainVoiceMemoStopRecordButtonOnPress(), MainVoiceMemoViewButtonOnPress(), MessagePhotoViewOnEnter(), MessagePhotoViewOnLeave(), MessageRecordViewOnEnter(), and MessageRecordViewOnLeave().
void SceneClearMissedCalls (void)
Clears all the missed calls.
Definition at line 799 of file doorbell_indoor/scene.c.
References CallLogClearCurrMissedCount(), ConfigSave(), EVENT_CUSTOM_MISS_CALLS, ituSceneSendEvent(), Config::missed_call_count, and theConfig.
Referenced by PhoneLogMissedOnEnter().
void SceneClearShow (SceneClearCallback func)
Shows the clearing dialog.
Parameters
func The callback function which is called when the user closes the dialog.
void SceneContinuePlayGuardAlarm (void)
Try to continue play guard alarm.
Definition at line 391 of file doorbell_indoor/scene.c.
References GuardIsAlarming(), guardRobAlarming, WARNPLAY_DELAY, and warnPlayDelay.
Referenced by CallEnd(), CallError(), CameraOnLeave(), CameraOnTimer(), CameraOutdoorOnLeave(), CameraViewOnLeave(), MainVoiceMemoDeleteConfirmButtonOnPress(), MainVoiceMemoOnLeave(), MainVoiceMemoOnTimer(), MainVoiceMemoResetPlayButton(), MainVoiceMemoStopPlayButtonOnPress(), MainVoiceMemoStopRecordButtonOnPress(), MessageRecordViewOnLeave(), and SceneHangUp().
void SceneDeleteShow (SceneDeleteCallback func)
Shows the deleting dialog.
Parameters
func The callback function which is called when the user closes the dialog.
void SceneEnterVideoState (void)
scene erter to video state.
Definition at line 476 of file doorbell_indoor/scene.c.
References inVideoState, ituFrameFuncInit(), and ituGetDisplaySurface.
Referenced by MessageRecordViewOnLeave(), and MessageServiceViewOnLeave().
void SceneExit (void)
Exits scene module.
Definition at line 142 of file doorbell_indoor/scene.c.
QuitValue SceneGetQuitValue (void)
Gets the current quit value.
Returns
The current quit value.
Definition at line 1476 of file doorbell_indoor/scene.c.
void SceneHangUp (void)
Hangs up the phone.
Definition at line 1001 of file doorbell_indoor/scene.c.
References callConnected, LinphoneCastor3::calling_ip_count, callReceived, currCallID, currCallingCount, currRemoteAddr, EVENT_CALLOUT_END, EVENT_CALLOUT_NOACK, EventWriteCalloutLog(), HOTKEY_DELAY, hotkeyDelay, linphoneCastor3, SceneContinuePlayGuardAlarm(), and LinphoneCastor3::video_msg_uri.
Referenced by CalledAnswerButtonOnPress(), CalledHangUpButtonOnPress(), CalledOnTimer(), CallingAnswerButtonOnPress(), CallingHangUpButtonOnPress(), CallingOnLeave(), CallingOnTimer(), MessagePhotoViewOnLeave(), SceneRun(), VideoRecordHangUpButtonOnPress(), and VideoRecordOnTimer().
void SceneInit (void)
Initializes scene module.
Definition at line 86 of file doorbell_indoor/scene.c.
bool SceneIsCallConnected (void)
Is the call connected or not.
Returns
true for connected, false for not connected yet.
Definition at line 1021 of file doorbell_indoor/scene.c.
void SceneLeaveVideoState (void)
scene leave from video state.
Definition at line 490 of file doorbell_indoor/scene.c.
References inVideoState, ituFrameFuncExit(), ituGetDisplaySurface, ituLcdInit(), ituM2dInit(), and ituSWInit().
Referenced by MessageRecordViewOnEnter(), and MessageServiceViewOnEnter().
void SceneLoad (void)
Loads ITU file.
Definition at line 165 of file doorbell_indoor/scene.c.
References CMD_LOAD_SCENE, commandQueue, Command::id, and isReady.
Referenced by create_response(), SDL_main(), and SettingDisplaySaveButtonOnPress().
void SceneOpenDoor (char * ip)
Opens the door on the remote device.
Parameters
ip The IP address of remote device. Can be NULL for current calling IP address of target.
Definition at line 981 of file doorbell_indoor/scene.c.
References currRemoteAddr, and RemoteOpenDoor().
Referenced by CalledUnlockButtonOnPress(), CallingUnlockButtonOnPress(), CameraOutdoorUnlockButtonOnPress(), CameraViewUnlockButtonOnPress(), and SceneRun().
void SceneQuit (QuitValue value)
Quits the scene.
Parameters
value The reason to quit the scene.
Definition at line 1471 of file doorbell_indoor/scene.c.
int SceneRun (void)
Runs the main loop to receive events, update and draw scene.
Returns
The QuitValue.
Definition at line 1078 of file doorbell_indoor/scene.c.
void SceneSetLastDoNotDisturbMode (DoNotDisturbMode mode)
Sets the last do not disturb mode.
Parameters
the the last do not disturb mode.
Definition at line 1026 of file doorbell_indoor/scene.c.
References lastDoNotDisturbMode.
Referenced by SettingPhoneDisturbSaveButtonOnPress().
void SceneSetReady (bool ready)
Sets the status of scene.
Parameters
ready true for ready, false for not ready yet.
Definition at line 343 of file doorbell_indoor/scene.c.
References isReady.
Referenced by MainVoiceMemoOnEnter().
void SceneSetRemoteIP (char * ip)
Sets the IP address of remote side.
Parameters
the IP address of remote side.
Definition at line 993 of file doorbell_indoor/scene.c.
void SceneUpdateIndicators (void)
Resets all the status of indicator UI.
Definition at line 237 of file doorbell_indoor/scene.c.
References CMD_UPDATE_INDICATORS, commandQueue, and Command::id.
Referenced by create_response(), LinphoneInitialized(), RemoteGetDontDisturbConfigTask(), and SettingDisplaySaveButtonOnPress().
void SettingEngineerNetworkIPShow (char * ip, SceneSettingEngineerNetworkIPCallback func)
Shows the IP address setting dialog.
Parameters
ip The original IP address.
func The callback function which is called when the input is finished.
Definition at line 122 of file layer_setting_engineer_network_ip.c.
References ituSceneFindWidget(), ituTextBoxSetString(), font::p, settingEngineerNetworkIP2TextBox, settingEngineerNetworkIP3TextBox, settingEngineerNetworkIP4TextBox, settingEngineerNetworkIPCloseCallback, SettingEngineerNetworkIPCloseCallbackDefault(), and theScene.
Referenced by SettingEngineerNetworkDnsButtonOnPress(), SettingEngineerNetworkGatewayButtonOnPress(), SettingEngineerNetworkIPButtonOnPress(), and SettingEngineerNetworkNetmaskButtonOnPress().
void SettingEngineerNetworkMacShow (char * mac, SceneSettingEngineerNetworkMacCallback func)
Shows the MAC address setting dialog.
Parameters
mac The original MAC address.
func The callback function which is called when the input is finished.
Definition at line 32 of file layer_setting_engineer_network_mac.c.
References ituSceneFindWidget(), ituTextBoxSetString(), settingEngineerNetworkMacCloseCallback, SettingEngineerNetworkMacCloseCallbackDefault(), and theScene.
Referenced by SettingEngineerNetworkMacButtonOnPress().
void SettingEngineerNetworkWiFiPasswordShow (char * password, SceneSettingEngineerNetworkWiFiPasswordCallback func)
Shows the WiFi password setting dialog.
Parameters
password The original WiFi password.
func The callback function which is called when the input is finished.
Definition at line 33 of file layer_setting_engineer_network_wifi_password.c.
References ituSceneFindWidget(), ituTextBoxSetString(), ituWidgetSetVisible, settingEngineerNetworkWiFiPasswordCloseCallback, SettingEngineerNetworkWiFiPasswordCloseCallbackDefault(), and theScene.
Referenced by SettingEngineerNetworkWiFiOnTimer().
void VideoRecordIncomingShow (int id, char * addr, int video)
Sets the infomation to the video record screen.
Parameters
id The call ID.
addr The IP address of target.
video 1 for has video, 0 for audio only.
Definition at line 32 of file layer_videorecord.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, Config::calling_time, DeviceInfo::floor, ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, MEDIA_AUDIO, MEDIA_VIDEO, DeviceInfo::room, StringGetRoomAddress(), theConfig, theScene, DeviceInfo::unit, VideoMemoStartRecord(), videoRecordCountDown, videoRecordID, videoRecordInVideoState, and videoRecordLastTick.
Referenced by MainNotifyVoiceMemoIncomingOnCustom().
Variable Documentation
ITUScene theScene
Global instance variable of scene.
Definition at line 76 of file doorbell_indoor/scene.c.
Referenced by CalledIncomingShow(), CalledOnEnter(), CallingCall(), CallingCallByIP(), CallingCallManager(), CallingOnEnter(), CameraListOnSelection(), CameraOnEnter(), CameraOnTimer(), CameraOutdoorButtonOnPress(), CameraOutdoorOnEnter(), CameraOutdoorOnTimer(), CameraViewButtonOnPress(), CameraViewShow(), CameraViewSnapshotButtonOnPress(), GuardLogClearConfirmOnPress(), GuardLogDeleteConfirmOnPress(), GuardLogOnEnter(), GuardModeOnEnter(), GuardPasswordOnEnter(), GuardStatusOnEnter(), GuardUserPasswordOnEnter(), GuardUserSettingOnEnter(), HouseAirConditionerOnEnter(), HouseCurtainOnEnter(), HouseLightOnEnter(), HouseModeOnEnter(), HousePlugOnEnter(), HouseTVOnEnter(), LogoOnEnter(), MainMenuNotifyUnplayVoiceMemo(), MainNotifyCallIncomingOnCustom(), MainNotifyGuardOnCustom(), MainNotifyMessagesOnCustom(), MainNotifyMissedCallsOnCustom(), MainNotifyNetworkOnCustom(), MainNotifyVoiceMemoIncomingOnCustom(), MainSetDoNotDisturbModeOnCustom(), MainVoiceMemoDeleteConfirmButtonOnPress(), MainVoiceMemoOnEnter(), MainVoiceMemoOnTimer(), MainVoiceMemoStopRecordButtonOnPress(), MainVoiceMemoViewButtonOnPress(), MainWeatherOnEnter(), MessageNotifyTextMessageOnCustom(), MessageNotifyUnreadRecordMessage(), MessageNotifyVideoMessageOnCustom(), MessagePhotoDeleteConfirmOnPress(), MessagePhotoGetList(), MessagePhotoOnEnter(), MessagePhotoViewOnEnter(), MessagePhotoViewOnTimer(), MessagePhotoViewShow(), MessageRecordOnEnter(), MessageRecordViewOnEnter(), MessageRecordViewOnTimer(), MessageRecordViewShow(), MessageServiceGetList(), MessageServiceOnEnter(), MessageServiceViewOnEnter(), MessageServiceViewShow(), PhoneContactsAddConfirmButtonOnPress(), PhoneContactsAddOnEnter(), PhoneContactsAddShow(), PhoneContactsClearConfirmButtonOnPress(), PhoneContactsDeleteConfirmButtonOnPress(), PhoneContactsKeyboardOnEnter(), PhoneContactsKeyboardShow(), PhoneContactsKeypadOnEnter(), PhoneContactsKeypadShow(), PhoneContactsModifyConfirmButtonOnPress(), PhoneContactsModifyOnEnter(), PhoneContactsModifyShow(), PhoneContactsOnEnter(), PhoneDialLobbyOnEnter(), PhoneDialManagerOnEnter(), PhoneDialResidentOnEnter(), PhoneLogMissedClearConfirmButtonOnPress(), PhoneLogMissedDeleteConfirmButtonOnPress(), PhoneLogMissedOnEnter(), PhoneLogReceivedClearConfirmButtonOnPress(), PhoneLogReceivedDeleteConfirmButtonOnPress(), PhoneLogReceivedOnEnter(), PhoneLogSentClearConfirmButtonOnPress(), PhoneLogSentDeleteConfirmButtonOnPress(), PhoneLogSentOnEnter(), PhoneLogViewShow(), ScreensaverOnEnter(), SettingDisplayOnEnter(), SettingEngineerMiscGuardOnEnter(), SettingEngineerMiscTerminalOnEnter(), SettingEngineerMiscTwiceOnEnter(), SettingEngineerNetworkIPOnEnter(), SettingEngineerNetworkIPShow(), SettingEngineerNetworkMacKeypadConfirmButtonOnPress(), SettingEngineerNetworkMacShow(), SettingEngineerNetworkOnEnter(), SettingEngineerNetworkWiFiOnEnter(), SettingEngineerNetworkWiFiPasswordConfirmButtonOnPress(), SettingEngineerNetworkWiFiPasswordShow(), SettingEngineerOnEnter(), SettingEngineerSensorOnEnter(), SettingOutdoorMainOnEnter(), SettingOutdoorMiscOnEnter(), SettingPhoneAudioOnEnter(), SettingPhoneAudioRingRadioBoxOnPress(), SettingPhoneDisturbOnEnter(), SettingPhoneDisturbSaveButtonOnPress(), SettingPhoneVoiceOnEnter(), SettingSystemOnEnter(), TimeOnEnter(), TouchCalibrationOnEnter(), UpgradeOnEnter(), VideoRecordIncomingShow(), and VideoRecordOnEnter().