ITE SoC SDK: Video Recorder
Video Recorder
ITE DoorBell Indoor Modules
Typedefs
typedef void(* VideoRecordPlayFinishedCallback)(void)
The function definition of video record play finished.
Functions
void VideoRecordInit (void)
Initializes video recorder module.
void VideoRecordExit (void)
Exits video recorder module.
int VideoRecordStartRecord (char *filepath)
Start recording to the specified file.
int VideoRecordStopRecord (void)
Stop recording.
int VideoRecordGetTimeLength (char *filepath)
Gets the time length of the specified recorded file, in seconds.
int VideoRecordStartPlay (char *filepath, VideoRecordPlayFinishedCallback func)
Plays the specified recorded file.
void VideoRecordStopPlay (void)
Stops playing recorded file.
Detailed Description
Typedef Documentation
typedef void(* VideoRecordPlayFinishedCallback)(void)
The function definition of video record play finished.
Definition at line 2253 of file doorbell_indoor/doorbell.h.
Function Documentation
void VideoRecordExit (void)
Exits video recorder module.
Definition at line 13 of file video_record.c.
Referenced by SDL_main().
int VideoRecordGetTimeLength (char * filepath)
Gets the time length of the specified recorded file, in seconds.
Parameters
filepath The specified file path.
Returns
The time length, in seconds.
Definition at line 30 of file video_record.c.
Referenced by CaptureCreateTask(), CaptureGetEntry(), VideoMemoCreateTask(), and VideoMemoGetEntry().
void VideoRecordInit (void)
Initializes video recorder module.
Definition at line 8 of file video_record.c.
Referenced by SDL_main().
int VideoRecordStartPlay (char * filepath, VideoRecordPlayFinishedCallback func)
Plays the specified recorded file.
Parameters
filepath The specified recorded file to play.
func The callback function to call when the playing finished.
Returns
0 for success, otherwise failed.
Definition at line 57 of file video_record.c.
References linphonec_video_memo_playback_event_callback, LinphoneStartVideoMemoPlay(), videoRecodrdPlayFinishedCallback, and VideoRecordPlaybackEventCallback().
Referenced by CaptureStartPlay(), and VideoMemoStartPlay().
int VideoRecordStartRecord (char * filepath)
Start recording to the specified file.
Parameters
filepath The specified file to record.
Returns
0 for success, otherwise failed.
Definition at line 18 of file video_record.c.
References LinphoneStartVideoMemoRecord().
Referenced by CaptureStartRecord(), and VideoMemoStartRecord().
void VideoRecordStopPlay (void)
Stops playing recorded file.
Definition at line 65 of file video_record.c.
References LinphoneStopVideoMemoPlay().
Referenced by CaptureStopPlay(), and VideoMemoStopPlay().
int VideoRecordStopRecord (void)
Stop recording.
Returns
0 for success, otherwise failed.
Definition at line 24 of file video_record.c.
References LinphoneStopVideoMemoRecord().
Referenced by CaptureStopRecord(), and VideoMemoStopRecord().