ITE SoC SDK: Message
Message
ITE DoorBell Indoor Modules
Data Structures
struct Message
Message definition.
Typedefs
typedef void(* MessageListGetCallback)(Message *messages, int count)
The function definition of getting message list.
typedef void(* MessageNotifyCallback)(void)
The function definition of message notify.
typedef void(* MessageTextContentGetCallback)(uint8_t *image, int imageSize)
The function definition of getting the content of text message.
Functions
void MessageInit (void)
Initializes message module.
void MessageExit (void)
Exits message module.
void MessageTextListGet (MessageListGetCallback func)
Gets the list of text messages.
void MessageTextDelete (int id, MessageNotifyCallback func)
Deletes the specified text message.
void MessageTextContentGet (char *image, MessageTextContentGetCallback func)
Gets the content of specified text message.
void MessageVideoListGet (MessageListGetCallback func)
Gets the list of video messages.
void MessageVideoDelete (int id, MessageNotifyCallback func)
Deletes the specified video message.
Detailed Description
Typedef Documentation
typedef void(* MessageListGetCallback)(Message *messages, int count)
The function definition of getting message list.
Parameters
messages The pointer to retrieve the array of Message.
count Maximum count of Message in array.
Definition at line 1551 of file doorbell_indoor/doorbell.h.
typedef void(* MessageNotifyCallback)(void)
The function definition of message notify.
Definition at line 1556 of file doorbell_indoor/doorbell.h.
typedef void(* MessageTextContentGetCallback)(uint8_t *image, int imageSize)
The function definition of getting the content of text message.
Parameters
image The pointer to retrieve the JPEG image data.
imageSize The image size.
Definition at line 1564 of file doorbell_indoor/doorbell.h.
Function Documentation
void MessageExit (void)
Exits message module.
Definition at line 68 of file message.c.
Referenced by SDL_main().
void MessageInit (void)
Initializes message module.
Definition at line 56 of file message.c.
References msgTextContentTasking, msgTextDeleteTasking, msgTextListTasking, msgTextListUrl, msgVideoDeleteTasking, msgVideoListTasking, and msgVideoListUrl.
Referenced by SDL_main().
void MessageTextContentGet (char * image, MessageTextContentGetCallback func)
Gets the content of specified text message.
Parameters
image The URL of the content of text message.
func The callback function to call when the downloading finished.
Definition at line 430 of file message.c.
References attr, DeviceInfo::ip, MessageTextContentGetTask(), msgTextContentTasking, NetworkServerIsReady(), and theCenterInfo.
Referenced by MessageServiceViewShow().
void MessageTextDelete (int id, MessageNotifyCallback func)
Deletes the specified text message.
Parameters
id The ID of text message.
func The callback function to call when the deleting finished.
Definition at line 353 of file message.c.
References attr, DeviceInfo::ip, MessageInitUrl(), MessageTextDeleteTask(), msgTextDeleteTasking, msgTextDeleteUrl, NetworkServerIsReady(), and theCenterInfo.
Referenced by MessageServiceDeleteConfirmOnPress().
void MessageTextListGet (MessageListGetCallback func)
Gets the list of text messages.
Parameters
func The callback function to call when the downloading finished.
Definition at line 289 of file message.c.
References attr, DeviceInfo::ip, MessageInitUrl(), MessageTextListGetTask(), msgTextListTasking, msgTextListUrl, NetworkServerIsReady(), and theCenterInfo.
Referenced by MessageServiceDeleteComplete(), and MessageServiceOnEnter().
void MessageVideoDelete (int id, MessageNotifyCallback func)
Deletes the specified video message.
Parameters
id The ID of video message.
func The callback function to call when the deleting finished.
Definition at line 651 of file message.c.
References attr, DeviceInfo::ip, MessageInitUrl(), MessageVideoDeleteTask(), msgVideoDeleteTasking, msgVideoDeleteUrl, NetworkServerIsReady(), and theCenterInfo.
Referenced by MessagePhotoDeleteConfirmOnPress().
void MessageVideoListGet (MessageListGetCallback func)
Gets the list of video messages.
Parameters
func The callback function to call when the downloading finished.
Definition at line 587 of file message.c.
References attr, DeviceInfo::ip, MessageInitUrl(), MessageVideoListGetTask(), msgVideoListTasking, msgVideoListUrl, NetworkServerIsReady(), and theCenterInfo.
Referenced by MessagePhotoDeleteComplete(), and MessagePhotoOnEnter().