ITE SoC SDK: Screen
Screen
ITE DoorBell Indoor Modules
Enumerations
enum ScreensaverType {
SCREENSAVER_NONE, SCREENSAVER_CLOCK, SCREENSAVER_BLANK, SCREENSAVER_PHOTO,
SCREENSAVER_NONE, SCREENSAVER_CLOCK, SCREENSAVER_BLANK, SCREENSAVER_PHOTO
}
Screensaver type definition.
Functions
void ScreenInit (void)
Initializes screen module.
void ScreenOff (void)
Turns off screen.
void ScreenOn (void)
Turns on screen.
bool ScreenIsOff (void)
Is the screen off or on.
void ScreenSetBrightness (int value)
Sets the brightness.
void ScreenSaverRefresh (void)
Re-counts the time to enter screensaver.
int ScreenSaverCheck (void)
Checks whether it is about time to enter screensaver mode.
void ScreenSaverPause (void)
Pause to count down the time to enter screensaver mode.
void ScreenSaverContinue (void)
Continue to count down the time to enter screensaver mode.
bool ScreenSaverIsScreenSaving (void)
Is on screensaver mode or not.
void Screenshot (void *lcdSurf)
Takes a screenshot to USB drive.
Detailed Description
Enumeration Type Documentation
enum ScreensaverType
Screensaver type definition.
Enumerator
SCREENSAVER_NONE
No screensaver.
SCREENSAVER_CLOCK
Clock sreensaver.
SCREENSAVER_BLANK
Black screen screensaver.
SCREENSAVER_PHOTO
Photo screensaver.
SCREENSAVER_NONE
No screensaver.
SCREENSAVER_CLOCK
Clock sreensaver.
SCREENSAVER_BLANK
Black screen screensaver.
SCREENSAVER_PHOTO
Photo screensaver.
Definition at line 1828 of file doorbell_indoor/doorbell.h.
Function Documentation
void ScreenInit (void)
Initializes screen module.
Definition at line 15 of file screen.c.
Referenced by SDL_main().
bool ScreenIsOff (void)
Is the screen off or on.
Returns
true for off; false for on.
Definition at line 24 of file screen.c.
Referenced by SceneRun().
void ScreenOff (void)
Turns off screen.
Definition at line 34 of file screen.c.
Referenced by SceneRun().
void ScreenOn (void)
Turns on screen.
Definition at line 45 of file screen.c.
int ScreenSaverCheck (void)
Checks whether it is about time to enter screensaver mode.
Returns
0 for net yet, otherwise for entering screensaver mode currently.
Definition at line 67 of file screen.c.
Referenced by SceneRun().
void ScreenSaverContinue (void)
Continue to count down the time to enter screensaver mode.
Definition at line 104 of file screen.c.
References screenSaverPause.
bool ScreenSaverIsScreenSaving (void)
Is on screensaver mode or not.
Definition at line 109 of file screen.c.
References screenOff, and screenSaverCountDown.
Referenced by CheckNetwork(), CheckQuitValue(), and create_response().
void ScreenSaverPause (void)
Pause to count down the time to enter screensaver mode.
Definition at line 99 of file screen.c.
References screenSaverPause.
void ScreenSaverRefresh (void)
Re-counts the time to enter screensaver.
Definition at line 55 of file screen.c.
Referenced by CallReceived(), CheckGuard(), CheckQuitValue(), create_response(), MainVoiceMemoOnTimer(), and SceneRun().
void ScreenSetBrightness (int value)
Sets the brightness.
Parameters
value The brightness value. Range 0~9.
Definition at line 29 of file screen.c.
References ITP_DEVICE_BACKLIGHT, and ITP_IOCTL_SET_BRIGHTNESS.
Referenced by create_response(), SettingDisplayBrightnessDownButtonOnPress(), SettingDisplayBrightnessUpButtonOnPress(), SettingDisplayCancelButtonOnPress(), and SettingDisplayOnLeave().
void Screenshot (void * lcdSurf)
Takes a screenshot to USB drive.
Parameters
lcdSurf The LCD surface widget.
Referenced by SceneRun().