ITE SoC SDK: Voice Memo
Voice Memo
ITE DoorBell Indoor Modules
Data Structures
struct VoiceMemoEntry
Voice memo definition.
Macros
#define VOICEMEMO_MAX_NAME_SIZE 40
Maximum count of voice memo item name.
Functions
void VoiceMemoInit (void)
Initializes voice memo module.
void VoiceMemoExit (void)
Exits voice memo module.
int VoiceMemoGetCount (void)
Gets total count of voice memo file.
int VoiceMemoGetUnplayCount (void)
Gets unplay count of voice memo file.
VoiceMemoEntry * VoiceMemoGetEntry (int index)
Gets the voice memo entry by index.
void VoiceMemoDeleteEntry (int index)
Deletes the voice memo entry by index.
int VoiceMemoStartPlay (int index)
Plays the voice memo file.
void VoiceMemoStopPlay (void)
Stops playing voice memo file.
int VoiceMemoStartRecord (void)
Starts recording.
int VoiceMemoStopRecord (void)
Stops recording.
bool VoiceMemoCheckDiskSpace (void)
Checks the disk space is availabe to record voice memo.
Detailed Description
Macro Definition Documentation
#define VOICEMEMO_MAX_NAME_SIZE 40
Maximum count of voice memo item name.
Definition at line 2275 of file doorbell_indoor/doorbell.h.
Referenced by VoiceMemoCreateTask(), and VoiceMemoStopRecord().
Function Documentation
bool VoiceMemoCheckDiskSpace (void)
Checks the disk space is availabe to record voice memo.
Returns
true for success, otherwise failed.
Definition at line 395 of file voicememo.c.
References VOICEMEMO_PATH.
Referenced by MainVoiceMemoOnTimer(), and VoiceMemoStartRecord().
void VoiceMemoDeleteEntry (int index)
Deletes the voice memo entry by index.
Parameters
index The index of voice memo entry.
Definition at line 267 of file voicememo.c.
References i, MAX_VOICEMEMO_COUNT, voiceMemoCount, VoiceMemoDeleteFile(), voiceMemoInited, and voiceMemoQuit.
Referenced by MainVoiceMemoDeleteConfirmButtonOnPress(), and VoiceMemoStopRecord().
void VoiceMemoExit (void)
Exits voice memo module.
Definition at line 209 of file voicememo.c.
References voiceMemoInited, and voiceMemoQuit.
Referenced by SDL_main().
int VoiceMemoGetCount (void)
Gets total count of voice memo file.
Returns
the total count of voice memo file.
Definition at line 215 of file voicememo.c.
References voiceMemoCount, voiceMemoInited, and voiceMemoQuit.
Referenced by MainVoiceMemoLengthListBoxOnLoad(), MainVoiceMemoNumberListBoxOnLoad(), and MainVoiceMemoTimeListBoxOnLoad().
VoiceMemoEntry* VoiceMemoGetEntry (int index)
Gets the voice memo entry by index.
Parameters
index The index of voice memo entry.
Returns
The voice memo entry, NULL if not found.
Definition at line 231 of file voicememo.c.
References i, MAX_VOICEMEMO_COUNT, voiceMemoCount, voiceMemoInited, and voiceMemoQuit.
Referenced by MainVoiceMemoLengthListBoxOnLoad(), MainVoiceMemoNumberListBoxOnLoad(), MainVoiceMemoTimeListBoxOnLoad(), MainVoiceMemoViewButtonOnPress(), and VoiceMemoStartPlay().
int VoiceMemoGetUnplayCount (void)
Gets unplay count of voice memo file.
Returns
unplay count of voice memo file.
Definition at line 223 of file voicememo.c.
References voiceMemoInited, voiceMemoQuit, and voiceMemoUnplayCount.
Referenced by MainVoiceMemoDeleteConfirmButtonOnPress(), MainVoiceMemoOnEnter(), MainVoiceMemoReload(), and MainVoiceMemoResetPlayButton().
void VoiceMemoInit (void)
Initializes voice memo module.
Definition at line 196 of file voicememo.c.
References attr, voiceMemoCount, VoiceMemoCreateTask(), voiceMemoIndex, voiceMemoInited, voiceMemoQuit, voiceMemoRecording, and voiceMemoUnplayCount.
Referenced by SDL_main().
int VoiceMemoStartPlay (int index)
Plays the voice memo file.
Parameters
index The index of voice memo file to play.
Returns
0 for success, otherwise failed.
Definition at line 293 of file voicememo.c.
References AudioRecordStartPlay(), ITP_DEVICE_NOR, ITP_IOCTL_FLUSH, VoiceMemoEntry::name, VoiceMemoEntry::played, VOICEMEMO_EXT, VOICEMEMO_PATH, VoiceMemoGetEntry(), voiceMemoInited, voiceMemoQuit, and voiceMemoUnplayCount.
Referenced by MainVoiceMemoViewButtonOnPress().
int VoiceMemoStartRecord (void)
Starts recording.
Returns
0 for success, otherwise failed.
Definition at line 326 of file voicememo.c.
References AudioRecordStartRecord(), VOICEMEMO_EXT, VOICEMEMO_PATH, VoiceMemoCheckDiskSpace(), voiceMemoIndex, voiceMemoInited, voiceMemoQuit, voiceMemoRecordFileName, and voiceMemoRecording.
Referenced by MainVoiceMemoRecordButtonOnPress().
void VoiceMemoStopPlay (void)
Stops playing voice memo file.
Definition at line 321 of file voicememo.c.
References AudioRecordStopPlay().
Referenced by MainVoiceMemoDeleteConfirmButtonOnPress(), MainVoiceMemoOnLeave(), MainVoiceMemoResetPlayButton(), and MainVoiceMemoStopPlayButtonOnPress().
int VoiceMemoStopRecord (void)
Stops recording.
Returns
0 for success, otherwise failed.
Definition at line 355 of file voicememo.c.
References AudioRecordGetTimeLength(), AudioRecordStopRecord(), MAX_VOICEMEMO_COUNT, VoiceMemoEntry::name, VoiceMemoEntry::played, VoiceMemoEntry::sec, VoiceMemoEntry::time, VOICEMEMO_EXT, VOICEMEMO_MAX_NAME_SIZE, VOICEMEMO_PATH, voiceMemoCount, VoiceMemoDeleteEntry(), voiceMemoInited, voiceMemoQuit, voiceMemoRecordFileName, voiceMemoRecording, and voiceMemoUnplayCount.
Referenced by MainVoiceMemoOnLeave(), MainVoiceMemoOnTimer(), and MainVoiceMemoStopRecordButtonOnPress().