ITE SoC SDK: Icon
Icon
ITE UI Library » Widgets
Data Structures
struct ITUIconTag
Icon widget definition.
Typedefs
typedef struct ITUIconTag ITUIcon
Icon widget definition.
Functions
void ituIconInit (ITUIcon *icon)
Initializes the icon widget.
void ituIconLoad (ITUIcon *icon, uint32_t base)
Loads the icon widget.
void ituIconExit (ITUWidget *widget)
Exits the icon widget.
bool ituIconClone (ITUWidget *widget, ITUWidget **cloned)
Clones the icon widget.
bool ituIconUpdate (ITUWidget *widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the icon widget by specified event.
void ituIconDraw (ITUWidget *widget, ITUSurface *dest, int x, int y, uint8_t alpha)
Draws the icon widget to the specified surface.
bool ituIconLoadJpegData (ITUIcon *icon, uint8_t *data, int size)
Loads JPEG data to the icon widget.
void ituIconLoadJpegFile (ITUIcon *icon, char *filepath)
Loads JPEG file to the icon widget.
void ituIconLoadJpegFileSync (ITUIcon *icon, char *filepath)
Loads JPEG file to the icon widget synchronously.
bool ituIconLoadPngData (ITUIcon *icon, uint8_t *data, int size)
Loads PNG data to the icon widget.
void ituIconLoadPngFile (ITUIcon *icon, char *filepath)
Loads PNG file to the icon widget.
void ituIconLoadPngFileSync (ITUIcon *icon, char *filepath)
Loads PNG file to the icon widget synchronously.
void ituIconLoadStaticData (ITUIcon *icon)
Loads static data to the icon widget.
void ituIconReleaseSurface (ITUIcon *icon)
Releases surface of icon widget.
void ituIconLinkSurface (ITUIcon *icon, ITUIcon *src)
Links surface of icon widget.
Detailed Description
Typedef Documentation
typedef struct ITUIconTag ITUIcon
Icon widget definition.
This is used for drawing bitmap icon.
Function Documentation
bool ituIconClone (ITUWidget * widget, ITUWidget ** cloned)
Clones the icon widget.
Parameters
widget The icon widget to clone.
cloned Retrieved cloned icon widget.
Returns
true if clone is success, false otherwise.
void ituIconDraw (ITUWidget * widget, ITUSurface * dest, int x, int y, uint8_t alpha)
Draws the icon widget to the specified surface.
Parameters
widget The icon widget to draw.
dest The surface to draw to.
x The x coordinate of destination surface, in pixels.
y The y coordinate of destination surface, in pixels.
alpha the alpha value to do the constant alphablending to the surface.
void ituIconExit (ITUWidget * widget)
Exits the icon widget.
Parameters
widget The icon widget to exit.
void ituIconInit (ITUIcon * icon)
Initializes the icon widget.
Parameters
icon The icon widget to initialize.
void ituIconLinkSurface (ITUIcon * icon, ITUIcon * src)
Links surface of icon widget.
Parameters
icon The icon widget to link to.
src The source icon widget to be linked.
void ituIconLoad (ITUIcon * icon, uint32_t base)
Loads the icon widget.
This is called by scene manager.
Parameters
icon The icon widget to load.
base The address in the scene file buffer.
bool ituIconLoadJpegData (ITUIcon * icon, uint8_t * data, int size)
Loads JPEG data to the icon widget.
Parameters
icon The icon widget to load.
data The JPEG data.
size The JPEG data size.
Returns
true if loaded success, false otherwise.
Examples:
test_itu/test_jpeg.c.
Referenced by MessageRecordViewOnEnter(), MessageServiceViewOnTimer(), PhoneLogViewShow(), and ScreensaverOnEnter().
void ituIconLoadJpegFile (ITUIcon * icon, char * filepath)
Loads JPEG file to the icon widget.
Parameters
icon The icon widget to load.
filepath The JPEG file path.
void ituIconLoadJpegFileSync (ITUIcon * icon, char * filepath)
Loads JPEG file to the icon widget synchronously.
Parameters
icon The icon widget to load.
filepath The JPEG file path.
Examples:
test_itu/test_jpeg.c.
bool ituIconLoadPngData (ITUIcon * icon, uint8_t * data, int size)
Loads PNG data to the icon widget.
Parameters
icon The icon widget to load.
data The PNG data.
size The PNG data size.
Returns
true if loaded success, false otherwise.
void ituIconLoadPngFile (ITUIcon * icon, char * filepath)
Loads PNG file to the icon widget.
Parameters
icon The icon widget to load.
filepath The PNG file path.
void ituIconLoadPngFileSync (ITUIcon * icon, char * filepath)
Loads PNG file to the icon widget synchronously.
Parameters
icon The icon widget to load.
filepath The PNG file path.
void ituIconLoadStaticData (ITUIcon * icon)
Loads static data to the icon widget.
Parameters
icon The icon widget to load.
void ituIconReleaseSurface (ITUIcon * icon)
Releases surface of icon widget.
Parameters
icon The icon widget to release.
Referenced by MessageServiceViewClear().
bool ituIconUpdate (ITUWidget * widget, ITUEvent ev, int arg1, int arg2, int arg3)
Updates the icon widget by specified event.
Parameters
widget The icon widget to update.
ev The event to notify.
arg1 The event related argument #1.
arg2 The event related argument #2.
arg3 The event related argument #3.
Returns
true if the icon widget is modified and need to be redraw, false if no need to be redraw.