ITE SoC SDK: Peripheral
Peripheral
ITE DoorBell Outdoor Modules
Functions
void PeripheralInit (void)
Initializes peripheral module.
void PeripheralOpenDoor (void)
Opens door.
bool PeripheralDoorIsOpened (void)
Determines whether the door is opened or not.
char * PeripheralReadCard (void)
Reads the card number.
void PeripheralCallElevator (char *floor, bool up)
Invokes the elevator.
Detailed Description
Function Documentation
void PeripheralCallElevator (char * floor, bool up)
Invokes the elevator.
Parameters
floor The floor of indoor phone.
up The direction is up or not.
Definition at line 92 of file doorbell_outdoor/peripheral.c.
Referenced by ahc_echo().
bool PeripheralDoorIsOpened (void)
Determines whether the door is opened or not.
Returns
true for opened; false for closed.
Definition at line 13 of file doorbell_indoor/peripheral.c.
void PeripheralInit (void)
Initializes peripheral module.
Definition at line 8 of file doorbell_indoor/peripheral.c.
References IOEXPANDER_0, ITH_GPIO_MODE0, ITH_GPIO_PIN48, ithGpioClear(), ithGpioSetMode(), ithGpioSetOut(), ITP_DEVICE_WIEGAND0, ITP_DEVICE_WIEGAND1, ITP_IOCTL_ENABLE, ITP_IOCTL_INIT, ITP_IOCTL_SET_BIT_COUNT, ITP_IOCTL_SET_GPIO_PIN, itpDeviceWiegand0, itpDeviceWiegand1, itpIOExpanderClear(), itpIOExpanderSetOut(), and itpRegisterDevice().
void PeripheralOpenDoor (void)
Opens door.
Definition at line 19 of file doorbell_indoor/peripheral.c.
References IOEXPANDER_0, ITH_GPIO_PIN48, ithGpioClear(), ithGpioSet(), itpIOExpanderClear(), itpIOExpanderSet(), and SceneIsCallConnected().
char* PeripheralReadCard (void)
Reads the card number.
Returns
the card number if exist; NULL for no card exists.
Definition at line 25 of file doorbell_indoor/peripheral.c.
References ITP_DEVICE_WIEGAND0, and ITP_DEVICE_WIEGAND1.