ITE SoC SDK: Memory Statistic
Memory Statistic
ITE Hardware Library
Enumerations
enum ITHMemStatRequest {
ITH_MEMSTAT_I2S_READ = 0x0, ITH_MEMSTAT_I2S_WRITE = 0x1, ITH_MEMSTAT_TSI_WRITE = 0x2, ITH_MEMSTAT_HOST_WRITE = 0x3,
ITH_MEMSTAT_HOST_READ = 0x4, ITH_MEMSTAT_LCD_READ = 0x5, ITH_MEMSTAT_ISP_READ = 0x6, ITH_MEMSTAT_CAP_READ = 0x7,
ITH_MEMSTAT_CMDQ_READ = 0x8, ITH_MEMSTAT_IQUEUE_READ = 0x9, ITH_MEMSTAT_USB = 0xA, ITH_MEMSTAT_ARM = 0xB,
ITH_MEMSTAT_VIDEO_READ = 0xC, ITH_MEMSTAT_VIDEO_WRITE = 0xD, ITH_MEMSTAT_ISP_WRITE = 0xE, ITH_MEMSTAT_TS = 0xF,
ITH_MEMSTAT_RISC = 0x10, ITH_MEMSTAT_AHB = 0x11, ITH_MEMSTAT_UENC_READ = 0x12, ITH_MEMSTAT_UENC_WRITE = 0x13,
ITH_MEMSTAT_OPENVG = 0x14, ITH_MEMSTAT_MEMBIST = 0x15, ITH_MEMSTAT_MEMBIST1 = 0x16
}
Memory Statistic request definition.
Functions
static void ithMemStatSetServCountPeriod (uint16_t period)
Sets memory access service count period.
static void ithMemStatServCounterEnable (void)
Enables Memory access service counter.
static void ithMemStatServCounterDisable (void)
Disables Memory access service counter.
static void ithMemStatSetServ0Request (ITHMemStatRequest rq)
Sets memory service0 request.
static void ithMemStatSetServ1Request (ITHMemStatRequest rq)
Sets memory service1 request.
static uint32_t ithMemStatGetServNum (void)
Gets memory service access number.
static uint32_t ithMemStatGetServ0Num (void)
Gets memory service0 access number.
static uint32_t ithMemStatGetServ1Num (void)
Gets memory service0 access number.
static uint32_t ithMemStatGetAllServCount (void)
Gets memory all service requests time counts in indication count period.
static uint32_t ithMemStatGetServCount (void)
Gets memory time counts in indication count period.
Detailed Description
Enumeration Type Documentation
enum ITHMemStatRequest
Memory Statistic request definition.
Enumerator
ITH_MEMSTAT_I2S_READ
I2S read request.
ITH_MEMSTAT_I2S_WRITE
I2S write request.
ITH_MEMSTAT_TSI_WRITE
TSI write request.
ITH_MEMSTAT_HOST_WRITE
Host bus controller write request.
ITH_MEMSTAT_HOST_READ
Host bus controller read request.
ITH_MEMSTAT_LCD_READ
LCD controller read request.
ITH_MEMSTAT_ISP_READ
ISP read request.
ITH_MEMSTAT_CAP_READ
CAP write request.
ITH_MEMSTAT_CMDQ_READ
Command queue read request.
ITH_MEMSTAT_IQUEUE_READ
I queue read request.
ITH_MEMSTAT_USB
USB controller read/write request.
ITH_MEMSTAT_ARM
ARM read/write request.
ITH_MEMSTAT_VIDEO_READ
Video engine read request.
ITH_MEMSTAT_VIDEO_WRITE
Video engine write request.
ITH_MEMSTAT_ISP_WRITE
ISP write request.
ITH_MEMSTAT_TS
TS parser read/write request.
ITH_MEMSTAT_RISC
RISC read/write request.
ITH_MEMSTAT_AHB
AHB read/write request.
ITH_MEMSTAT_UENC_READ
UEncoder engine read request.
ITH_MEMSTAT_UENC_WRITE
UEncoder engine write request.
ITH_MEMSTAT_OPENVG
Open VG read/write request.
ITH_MEMSTAT_MEMBIST
Memory BIST read/write request.
ITH_MEMSTAT_MEMBIST1
Memory BIST1 read/write request.
Definition at line 1219 of file ith.h.
Function Documentation
static uint32_t ithMemStatGetAllServCount (void) inline static
Gets memory all service requests time counts in indication count period.
Returns
The memory all service requests time counts in indication count period.
Definition at line 1330 of file ith.h.
References ITH_MEMSTAT_SERVALL_CNT_HI_REG, ITH_MEMSTAT_SERVALL_CNT_LO_REG, and ithReadRegH().
static uint32_t ithMemStatGetServ0Num (void) inline static
Gets memory service0 access number.
Returns
The memory service0 access number.
Definition at line 1308 of file ith.h.
References ITH_MEMSTAT_SERV0_NUM_HI_REG, ITH_MEMSTAT_SERV0_NUM_LO_REG, and ithReadRegH().
static uint32_t ithMemStatGetServ1Num (void) inline static
Gets memory service0 access number.
Returns
The memory service0 access number.
Definition at line 1319 of file ith.h.
References ITH_MEMSTAT_SERV1_NUM_HI_REG, ITH_MEMSTAT_SERV1_NUM_LO_REG, and ithReadRegH().
static uint32_t ithMemStatGetServCount (void) inline static
Gets memory time counts in indication count period.
Returns
The memory time counts in indication count period.
Definition at line 1341 of file ith.h.
References ITH_MEMSTAT_SERVTIME_CNT_HI_REG, ITH_MEMSTAT_SERVTIME_CNT_LO_REG, and ithReadRegH().
static uint32_t ithMemStatGetServNum (void) inline static
Gets memory service access number.
Returns
The memory service access number.
Definition at line 1297 of file ith.h.
References ITH_MEMSTAT_SERVALL_NUM_HI_REG, ITH_MEMSTAT_SERVALL_NUM_LO_REG, and ithReadRegH().
static void ithMemStatServCounterDisable (void) inline static
Disables Memory access service counter.
Definition at line 1267 of file ith.h.
References ITH_MEMSTAT_SERV_CR_REG, ITH_MEMSTAT_SERV_EN_BIT, and ithClearRegBitH().
static void ithMemStatServCounterEnable (void) inline static
Enables Memory access service counter.
Definition at line 1259 of file ith.h.
References ITH_MEMSTAT_SERV_CR_REG, ITH_MEMSTAT_SERV_EN_BIT, and ithSetRegBitH().
static void ithMemStatSetServ0Request (ITHMemStatRequest rq) inline static
Sets memory service0 request.
Parameters
rq The memory stat request.
Definition at line 1277 of file ith.h.
References ITH_MEMSTAT_SERV0_RQ_BIT, ITH_MEMSTAT_SERV0_RQ_MASK, ITH_MEMSTAT_SERV_CR_REG, and ithWriteRegMaskH().
static void ithMemStatSetServ1Request (ITHMemStatRequest rq) inline static
Sets memory service1 request.
Parameters
rq The memory stat request.
Definition at line 1287 of file ith.h.
References ITH_MEMSTAT_SERV1_RQ_BIT, ITH_MEMSTAT_SERV1_RQ_MASK, ITH_MEMSTAT_SERV_CR_REG, and ithWriteRegMaskH().
static void ithMemStatSetServCountPeriod (uint16_t period) inline static
Sets memory access service count period.
Parameters
period The memory access service count period.
Definition at line 1251 of file ith.h.
References ITH_MEMSTAT_SERV_PERIOD_REG, and ithWriteRegH().