ITE SoC SDK: GPIO Expander
GPIO Expander
Macros
#define ITP_MAX_GPIO_EXPANDER_HANDLER 8
Maximum GPIO expander handler count.
Typedefs
typedef void(* ITPGpioExpanderDeferIntrHandler)(void *pvParameter1, uint32_t ulParameter2)
GPIO expander deferred interrupt handler.
typedef void(* ITPSecondGpioExpanderDeferIntrHandler)(void *pvParameter1, uint32_t ulParameter2)
Second GPIO expander deferred interrupt handler.
Enumerations
enum ITP_IOExpander { IOEXPANDER_0 = 0, IOEXPANDER_1 = 1 }
IO expander definition.
Functions
void itpIOExpanderSetOut (ITP_IOExpander IOEXP_Port, unsigned int pin)
Sets GPIO Expander pin to output mode.
void itpIOExpanderSetIn (ITP_IOExpander IOEXP_Port, unsigned int pin)
Sets GPIO Expander pin to input mode.
void itpIOExpanderSet (ITP_IOExpander IOEXP_Port, unsigned int pin)
Sets GPIO Expander pin to 1.
void itpIOExpanderClear (ITP_IOExpander IOEXP_Port, unsigned int pin)
Sets GPIO Expander pin to 0.
uint8_t itpIOExpanderGet (ITP_IOExpander IOEXP_Port, unsigned int pin)
Gets the value of GPIO Expander pin.
uint8_t itpIOExpanderGetAllPins (ITP_IOExpander IOEXP_Port)
Gets all the value of GPIO Expander pins.
uint8_t itpIOExpanderGetInputStatus (ITP_IOExpander IOEXP_Port)
Gets input status of GPIO Expander pins.
void itpRegisterIOExpanderDeferIntrHandler (ITPGpioExpanderDeferIntrHandler handler)
Registers GPIO expander deferred interrupt handler.
void itpRegisterSecondIOExpanderDeferIntrHandler (ITPSecondGpioExpanderDeferIntrHandler handler)
Registers Second GPIO expander deferred interrupt handler.
Detailed Description
Macro Definition Documentation
#define ITP_MAX_GPIO_EXPANDER_HANDLER 8
Maximum GPIO expander handler count.
Definition at line 14 of file itp_io_expander.h.
Typedef Documentation
typedef void(* ITPGpioExpanderDeferIntrHandler)(void *pvParameter1, uint32_t ulParameter2)
GPIO expander deferred interrupt handler.
Definition at line 73 of file itp_io_expander.h.
typedef void(* ITPSecondGpioExpanderDeferIntrHandler)(void *pvParameter1, uint32_t ulParameter2)
Second GPIO expander deferred interrupt handler.
Definition at line 78 of file itp_io_expander.h.
Enumeration Type Documentation
enum ITP_IOExpander
IO expander definition.
Enumerator
IOEXPANDER_0
IOEXPANDER_0.
IOEXPANDER_1
IOEXPANDER_1.
Definition at line 19 of file itp_io_expander.h.
Function Documentation
void itpIOExpanderClear (ITP_IOExpander IOEXP_Port, unsigned int pin)
Sets GPIO Expander pin to 0.
Parameters
pin the GPIO Expander pin to set to 0.
Referenced by PeripheralInit(), and PeripheralOpenDoor().
uint8_t itpIOExpanderGet (ITP_IOExpander IOEXP_Port, unsigned int pin)
Gets the value of GPIO Expander pin.
Parameters
pin the GPIO Expander pin to get.
Referenced by GuardEnableSensor(), and GuardInit().
uint8_t itpIOExpanderGetAllPins (ITP_IOExpander IOEXP_Port)
Gets all the value of GPIO Expander pins.
uint8_t itpIOExpanderGetInputStatus (ITP_IOExpander IOEXP_Port)
Gets input status of GPIO Expander pins.
void itpIOExpanderSet (ITP_IOExpander IOEXP_Port, unsigned int pin)
Sets GPIO Expander pin to 1.
Parameters
pin the GPIO Expander pin to set to 1.
Referenced by GuardEnableSensor(), and PeripheralOpenDoor().
void itpIOExpanderSetIn (ITP_IOExpander IOEXP_Port, unsigned int pin)
Sets GPIO Expander pin to input mode.
Parameters
pin the GPIO Expander pin to set to input mode.
Referenced by GuardEnableSensor().
void itpIOExpanderSetOut (ITP_IOExpander IOEXP_Port, unsigned int pin)
Sets GPIO Expander pin to output mode.
Parameters
pin the GPIO Expander pin to set to output mode.
Referenced by PeripheralInit().
void itpRegisterIOExpanderDeferIntrHandler (ITPGpioExpanderDeferIntrHandler handler)
Registers GPIO expander deferred interrupt handler.
Parameters
handler The handler function.
Referenced by GuardEnableSensor().
void itpRegisterSecondIOExpanderDeferIntrHandler (ITPSecondGpioExpanderDeferIntrHandler handler)
Registers Second GPIO expander deferred interrupt handler.
Parameters
handler The handler function.