ITE SoC SDK: Weather
Weather
ITE DoorBell Indoor Modules
Functions
void WeatherInit (void)
Initializes weather module.
void WeatherExit (void)
Exits weather module.
void WeatherParse (char *xml, int size)
Parses the weather XML.
bool WeatherIsAvailable (void)
Is the weather XML parsed or not.
char * WeatherGetDate (int day)
Gets the date description.
int WeatherGetSymbolIndex (int day)
Gets the symbol index.
float WeatherGetTemperatureMin (int day)
Gets the minimum temperature.
float WeatherGetTemperatureMax (int day)
Gets the maximum temperature.
char * WeatherGetSymbolName (int day)
Gets the symbol description.
char * WeatherGetWindSpeedName (int day)
Gets the wind speed description.
Detailed Description
Function Documentation
void WeatherExit (void)
Exits weather module.
Definition at line 13 of file weather.c.
References weatherDoc.
Referenced by SDL_main(), and WeatherParse().
char* WeatherGetDate (int day)
Gets the date description.
Parameters
day The day index starting from today. The range is 0~4.
Returns
The date string. Remember to free it after used to avoid memory leak.
Definition at line 35 of file weather.c.
References weatherDoc.
Referenced by MainWeatherOnTimer().
int WeatherGetSymbolIndex (int day)
Gets the symbol index.
Parameters
day The day index starting from today. The range is 0~4.
Returns
The symbol index. The range is 0~8.
Definition at line 59 of file weather.c.
References weatherDoc.
Referenced by MainWeatherOnTimer().
char* WeatherGetSymbolName (int day)
Gets the symbol description.
Parameters
day The day index starting from today. The range is 0~4.
Returns
The symbol string. Remember to free it after used to avoid memory leak.
Definition at line 164 of file weather.c.
References weatherDoc.
Referenced by MainWeatherOnTimer().
float WeatherGetTemperatureMax (int day)
Gets the maximum temperature.
Parameters
day The day index starting from today. The range is 0~4.
Returns
The temperature value.
Definition at line 134 of file weather.c.
References weatherDoc.
Referenced by MainWeatherOnTimer().
float WeatherGetTemperatureMin (int day)
Gets the minimum temperature.
Parameters
day The day index starting from today. The range is 0~4.
Returns
The temperature value.
Definition at line 104 of file weather.c.
References weatherDoc.
Referenced by MainWeatherOnTimer().
char* WeatherGetWindSpeedName (int day)
Gets the wind speed description.
Parameters
day The day index starting from today. The range is 0~4.
Returns
The wind speed string. Remember to free it after used to avoid memory leak.
Definition at line 188 of file weather.c.
References weatherDoc.
Referenced by MainWeatherOnTimer().
void WeatherInit (void)
Initializes weather module.
Definition at line 8 of file weather.c.
Referenced by SDL_main().
bool WeatherIsAvailable (void)
Is the weather XML parsed or not.
Returns
true for paring success, false otherwise.
Definition at line 30 of file weather.c.
References weatherDoc.
Referenced by MainWeatherOnTimer().
void WeatherParse (char * xml, int size)
Parses the weather XML.
Parameters
xml The weather XML to parse.
size The size of XML string.
Definition at line 22 of file weather.c.
References weatherDoc, and WeatherExit().
Referenced by MainWeatherGetWeather().