ITE SoC SDK: Renderers
Renderers
ITE UI Library
Modules
LCD Display
SW Renderer
M2D Renderer
Frame Function Renderer
STN LCD
Data Structures
struct ITUSurface
Surface definition.
struct ITUMaskSurface
Macros
#define ITU_STATIC 0x1
This surface won't be deleted.
#define ITU_CLIPPING 0x2
This surface is clipping.
#define ITU_COMPRESSED 0x4
This surface is compressed.
#define ITU_JPEG 0x8
This surface is JPEG image.
Typedefs
typedef struct ITUSurface ITUSurface
Surface definition.
Enumerations
enum ITUPixelFormat {
ITU_RGB565 = 0, ITU_ARGB1555 = 1, ITU_ARGB4444 = 2, ITU_ARGB8888 = 3,
ITU_MONO = 4, ITU_RGB565A8 = 5, ITU_A8 = 6
}
Pixel format definition.
enum ITUGlyphFormat { ITU_GLYPH_1BPP, ITU_GLYPH_4BPP, ITU_GLYPH_8BPP }
Glyph format definition.
enum ITUMaskFormat {
ITU_MASK_A_8, ITU_MASK_A_4, ITU_MASK_A_2, ITU_MASK_A_1,
ITU_MASK_UNKNOWN
}
enum ITURotation { ITU_ROT_0, ITU_ROT_90, ITU_ROT_180, ITU_ROT_270 }
Rotation definition.
enum ITUGradientMode {
ITU_GF_NONE, ITU_GF_HORIZONTAL, ITU_GF_VERTICAL, ITU_GF_FORWARD_DIAGONAL,
ITU_GF_BACKWARD_DIAGONAL
}
Gradient mode definition.
enum ITUTileMode {
ITU_TILE_FILL, ITU_TILE_PAD, ITU_TILE_REPEAT, ITU_TILE_REFLECT,
ITU_TILE_UNKNOWN
}
enum ITUQualityMode { ITU_QUALITY_BETTER, ITU_QUALITY_FASTER }
enum ITUPageFlowType { ITU_PAGEFLOW_FOLD, ITU_PAGEFLOW_FLIP, ITU_PAGEFLOW_FLIP2, ITU_PAGEFLOW_FOLD2 }
PageFlow type definition.
enum ITUTransformType {
ITU_TRANSFORM_NONE = 0, ITU_TRANSFORM_TURN_LEFT = 1, ITU_TRANSFORM_TURN_TOP = 2, ITU_TRANSFORM_TURN_RIGHT = 3,
ITU_TRANSFORM_TURN_BOTTOM = 4
}
Transform type definition.
Functions
ITUSurface * ituSurfaceDecompress (ITUSurface *surf)
Decompresses the surface.
void ituSurfaceRelease (ITUSurface *surf)
Releases the surface.
void ituSurfaceSetClipping (ITUSurface *surf, int x, int y, int w, int h)
Sets clipping region to surface.
Variables
ITUSurface *(* ituGetDisplaySurface)(void)
Gets display surface.
ITUSurface *(* ituCreateSurface)(int w, int h, int pitch, ITUPixelFormat format, const uint8_t *bitmap, unsigned int flags)
Creates surface.
void(* ituDestroySurface)(ITUSurface *surf)
Destroies surface.
ITUMaskSurface *(* ituCreateMaskSurface)(int w, int h, int pitch, ITUMaskFormat format, uint8_t *buffer, uint32_t bufferLength)
void(* ituDestroyMaskSurface)(ITUMaskSurface *surf)
void(* ituSetMaskSurface)(ITUSurface *surface, ITUMaskSurface *maskSurface, bool enable)
uint8_t *(* ituLockSurface)(ITUSurface *surf, int x, int y, int w, int h)
Locks surface for software rendering.
void(* ituUnlockSurface)(ITUSurface *surf)
Unlocks surface.
void(* ituSetRotation)(ITURotation rot)
Sets rotation.
void(* ituDrawGlyph)(ITUSurface *surf, int x, int y, ITUGlyphFormat format, const uint8_t *bitmap, int w, int h)
Draws a font glyph to specified surface.
void(* ituBitBlt)(ITUSurface *dest, int dx, int dy, int w, int h, ITUSurface *src, int sx, int sy)
Bitblts source surface to destination surface.
void(* ituStretchBlt)(ITUSurface *dest, int dx, int dy, int dw, int dh, ITUSurface *src, int sx, int sy, int sw, int sh)
Stretchblts source surface to destination surface.
void(* ituAlphaBlend)(ITUSurface *dest, int dx, int dy, int w, int h, ITUSurface *src, int sx, int sy, uint8_t alpha)
AlphaBlending source surface to destination surface.
void(* ituColorFill)(ITUSurface *surf, int x, int y, int w, int h, ITUColor *color)
Fills specified color to specified surface.
void(* ituColorFillBlend)(ITUSurface *surf, int x, int y, int w, int h, ITUColor *color, bool enableAlpha, bool enableConstantAlpha, uint8_t constantAlphaValue)
void(* ituGradientFill)(ITUSurface *surf, int x, int y, int w, int h, ITUColor *startColor, ITUColor *endColor, ITUGradientMode mode)
Gradient fills specified colors and mode to specified surface.
void(* ituGradientFillBlend)(ITUSurface *surf, int x, int y, int w, int h, ITUColor *startColor, ITUColor *endColor, ITUGradientMode mode, bool enableAlpha, bool enableConstantAlpha, uint8_t constantAlphaValue)
void(* ituRotate)(ITUSurface *dest, int dx, int dy, ITUSurface *src, int cx, int cy, float angle, float scaleX, float scaleY)
Rotates source surface to destination surface.
void(* ituTransform)(ITUSurface *dest, int dx, int dy, int dw, int dh, ITUSurface *src, int sx, int sy, int sw, int sh, int cx, int cy, float scaleWidth, float scaleHeight, float angle, ITUTileMode tilemode, bool enableAlpha, bool enableConstantAlpha, uint8_t constantAlphaValue)
void(* ituFlip)(ITUSurface *surf)
Flips the specified surface.
void(* ituProjection)(ITUSurface *dest, int dx, int dy, int dw, int dh, ITUSurface *src, int sx, int sy, int sw, int sh, float scaleWidth, float scaleHeight, float degree, float FOV, float pivotX, bool enableAlpha, bool enableConstantAlpha, uint8_t constantAlphaValue)
void(* ituDrawLine)(ITUSurface *surf, int32_t fromX, int32_t fromY, int32_t toX, int32_t toY, ITUColor *lineColor, int32_t lineWidth)
Draws a line on the specified surface.
void(* ituDrawCurve)(ITUSurface *surf, ITUPoint *point1, ITUPoint *point2, ITUPoint *point3, ITUPoint *point4, ITUColor *lineColor, int32_t lineWidth)
void(* ituTransformBlt)(ITUSurface *dest, int dx, int dy, ITUSurface *src, int sx, int sy, int sw, int sh, int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3, bool bInverse, ITUPageFlowType type, ITUTransformType transformType)
Transformblits source surface to destination surface.
void(* ituReflected)(ITUSurface *dest, int dx, int dy, ITUSurface *src, int sx, int sy, int reflectedWidth, int reflectedHeight, ITUSurface *masksurf)
Reflected source surface to destination surface.
Detailed Description
Macro Definition Documentation
#define ITU_CLIPPING 0x2
This surface is clipping.
Definition at line 206 of file itu.h.
#define ITU_COMPRESSED 0x4
This surface is compressed.
Definition at line 207 of file itu.h.
#define ITU_JPEG 0x8
This surface is JPEG image.
Definition at line 208 of file itu.h.
#define ITU_STATIC 0x1
This surface won't be deleted.
Definition at line 205 of file itu.h.
Typedef Documentation
typedef struct ITUSurface ITUSurface
Surface definition.
Definition at line 240 of file itu.h.
Enumeration Type Documentation
enum ITUGlyphFormat
Glyph format definition.
Enumerator
ITU_GLYPH_1BPP
1 bit-per-pixel
ITU_GLYPH_4BPP
4 bit-per-pixel
ITU_GLYPH_8BPP
8 bit-per-pixel
Definition at line 126 of file itu.h.
enum ITUGradientMode
Gradient mode definition.
Enumerator
ITU_GF_NONE
No gradient.
ITU_GF_HORIZONTAL
Specifies a gradient from left to right.
ITU_GF_VERTICAL
Specifies a gradient from top to bottom.
ITU_GF_FORWARD_DIAGONAL
Specifies a gradient from upper left to lower right.
ITU_GF_BACKWARD_DIAGONAL
Specifies a gradient from upper right to lower left.
Definition at line 156 of file itu.h.
enum ITUMaskFormat
Enumerator
ITU_MASK_A_8
ITU_MASK_A_4
ITU_MASK_A_2
ITU_MASK_A_1
ITU_MASK_UNKNOWN
Definition at line 133 of file itu.h.
enum ITUPageFlowType
PageFlow type definition.
Enumerator
ITU_PAGEFLOW_FOLD
Fold effect.
ITU_PAGEFLOW_FLIP
Flip effect.
ITU_PAGEFLOW_FLIP2
Flip 2 pieces effect.
ITU_PAGEFLOW_FOLD2
Fold 2 effect, no clipping destWidth.
Definition at line 183 of file itu.h.
enum ITUPixelFormat
Pixel format definition.
Enumerator
ITU_RGB565
RGB565 format.
ITU_ARGB1555
ARGB1555 format.
ITU_ARGB4444
ARGB4444 format.
ITU_ARGB8888
ARGB8888 format.
ITU_MONO
1-bpp format
ITU_RGB565A8
RGB565A8 format.
ITU_A8
A8 format.
Definition at line 112 of file itu.h.
enum ITUQualityMode
Enumerator
ITU_QUALITY_BETTER
ITU_QUALITY_FASTER
Definition at line 174 of file itu.h.
enum ITURotation
Rotation definition.
Enumerator
ITU_ROT_0
No rotate.
ITU_ROT_90
90 degree rotate
ITU_ROT_180
180 degree rotate
ITU_ROT_270
270 degree rotate
Definition at line 145 of file itu.h.
enum ITUTileMode
Enumerator
ITU_TILE_FILL
ITU_TILE_PAD
ITU_TILE_REPEAT
ITU_TILE_REFLECT
ITU_TILE_UNKNOWN
Definition at line 165 of file itu.h.
enum ITUTransformType
Transform type definition.
Enumerator
ITU_TRANSFORM_NONE
No transform.
ITU_TRANSFORM_TURN_LEFT
Turn to left side.
ITU_TRANSFORM_TURN_TOP
Turn to top side.
ITU_TRANSFORM_TURN_RIGHT
Turn to right side.
ITU_TRANSFORM_TURN_BOTTOM
Turn to bottom side.
Definition at line 194 of file itu.h.
Function Documentation
ITUSurface* ituSurfaceDecompress (ITUSurface * surf)
Decompresses the surface.
Parameters
surf the surface to decompress.
Returns
the decompressed surface.
void ituSurfaceRelease (ITUSurface * surf)
Releases the surface.
Parameters
surf the surface to release.
void ituSurfaceSetClipping (ITUSurface * surf, int x, int y, int w, int h)
Sets clipping region to surface.
Parameters
surf the surface to set to.
x the clipping x coordinate.
y the clipping y coordinate.
w the clipping width.
h the clipping height.
Variable Documentation
void(* ituAlphaBlend)(ITUSurface *dest, int dx, int dy, int w, int h, ITUSurface *src, int sx, int sy, uint8_t alpha)
AlphaBlending source surface to destination surface.
Parameters
dest the destination surface to draw to.
dx the x coordinate of destination surface, in pixels.
dy the y coordinate of destination surface, in pixels.
w the width to alphablend, in pixels.
h the height to alphablend, in pixels.
src the source surface to draw.
sx the x coordinate of source surface, in pixels.
sy the y coordinate of source surface, in pixels.
alpha the alpha value to do the constant alphablending.
void(* ituBitBlt)(ITUSurface *dest, int dx, int dy, int w, int h, ITUSurface *src, int sx, int sy)
Bitblts source surface to destination surface.
Parameters
dest the destination surface to draw to.
dx the x coordinate of destination surface, in pixels.
dy the y coordinate of destination surface, in pixels.
w the width to bitblt, in pixels.
h the height to bitblt, in pixels.
src the source surface to draw.
sx the x coordinate of source surface, in pixels.
sy the y coordinate of source surface, in pixels.
void(* ituColorFill)(ITUSurface *surf, int x, int y, int w, int h, ITUColor *color)
Fills specified color to specified surface.
Parameters
surf the surface to draw to.
dx the x coordinate of surface, in pixels.
dy the y coordinate of surface, in pixels.
w the width to fill, in pixels.
h the height to fill, in pixels.
color the color value to draw.
void(* ituColorFillBlend)(ITUSurface *surf, int x, int y, int w, int h, ITUColor *color, bool enableAlpha, bool enableConstantAlpha, uint8_t constantAlphaValue)
ITUMaskSurface*(* ituCreateMaskSurface)(int w, int h, int pitch, ITUMaskFormat format, uint8_t *buffer, uint32_t bufferLength)
ITUSurface*(* ituCreateSurface)(int w, int h, int pitch, ITUPixelFormat format, const uint8_t *bitmap, unsigned int flags)
Creates surface.
Parameters
w the surface width, in pixels.
h the surface height, in pixels.
pitch the surface pitch, in bytes.
format the surface format.
bitmap surface bitmap data address, null for empty surface.
flags can be ITU_STATIC or 0.
Returns
the STN LCD display surface. null if failed
void(* ituDestroyMaskSurface)(ITUMaskSurface *surf)
void(* ituDestroySurface)(ITUSurface *surf)
Destroies surface.
Parameters
surf the surface to destroy.
void(* ituDrawCurve)(ITUSurface *surf, ITUPoint *point1, ITUPoint *point2, ITUPoint *point3, ITUPoint *point4, ITUColor *lineColor, int32_t lineWidth)
void(* ituDrawGlyph)(ITUSurface *surf, int x, int y, ITUGlyphFormat format, const uint8_t *bitmap, int w, int h)
Draws a font glyph to specified surface.
Parameters
surf the surface to draw.
x the x coordinate, in pixels.
y the y coordinate, in pixels.
format the glyph format.
bitmap the glyph bitmap.
w the glyph width, in pixels.
h the glyph height, in pixels.
void(* ituDrawLine)(ITUSurface *surf, int32_t fromX, int32_t fromY, int32_t toX, int32_t toY, ITUColor *lineColor, int32_t lineWidth)
Draws a line on the specified surface.
Parameters
surf the surface to draw.
fromX the x coordinate of start point, in pixels.
fromY the y coordinate of start point, in pixels.
toX the x coordinate of end point, in pixels.
toY the y coordinate of end point, in pixels.
lineColor the color of line.
lineWidth the width of line, in pixels.
void(* ituFlip)(ITUSurface *surf)
Flips the specified surface.
Parameters
surf the surface to flip.
Examples:
test_itu/test_array.c, test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_helloworld.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, test_itu/test_stnlcd.c, and test_itu/test_trackbar.c.
Referenced by SceneRun().
ITUSurface*(* ituGetDisplaySurface)(void)
Gets display surface.
Returns
the display surface.
Examples:
test_itu/test_array.c, test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_helloworld.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, test_itu/test_progressbar.c, test_itu/test_sdl.c, and test_itu/test_trackbar.c.
Referenced by SceneEnterVideoState(), SceneInit(), and SceneLeaveVideoState().
void(* ituGradientFill)(ITUSurface *surf, int x, int y, int w, int h, ITUColor *startColor, ITUColor *endColor, ITUGradientMode mode)
Gradient fills specified colors and mode to specified surface.
Parameters
surf the surface to draw to.
dx the x coordinate of surface, in pixels.
dy the y coordinate of surface, in pixels.
w the width to fill, in pixels.
h the height to fill, in pixels.
startColor the start color value to draw.
endColor the end color value to draw.
mode the gradinet fill mode.
void(* ituGradientFillBlend)(ITUSurface *surf, int x, int y, int w, int h, ITUColor *startColor, ITUColor *endColor, ITUGradientMode mode, bool enableAlpha, bool enableConstantAlpha, uint8_t constantAlphaValue)
uint8_t*(* ituLockSurface)(ITUSurface *surf, int x, int y, int w, int h)
Locks surface for software rendering.
Parameters
surf the surface to lock.
x the locking x coordinate.
y the locking y coordinate.
w the locking width.
h the locking height.
Returns
the locking buffer address.
void(* ituProjection)(ITUSurface *dest, int dx, int dy, int dw, int dh, ITUSurface *src, int sx, int sy, int sw, int sh, float scaleWidth, float scaleHeight, float degree, float FOV, float pivotX, bool enableAlpha, bool enableConstantAlpha, uint8_t constantAlphaValue)
void(* ituReflected)(ITUSurface *dest, int dx, int dy, ITUSurface *src, int sx, int sy, int reflectedWidth, int reflectedHeight, ITUSurface *masksurf)
Reflected source surface to destination surface.
Parameters
dest the destination surface to draw to.
dx the x coordinate of destination surface, in pixels.
dy the y coordinate of destination surface, in pixels.
src the source surface to draw.
void(* ituRotate)(ITUSurface *dest, int dx, int dy, ITUSurface *src, int cx, int cy, float angle, float scaleX, float scaleY)
Rotates source surface to destination surface.
Parameters
dest the destination surface to draw to.
dx the x coordinate of destination surface to draw the center of source surface, in pixels.
dy the y coordinate of destination surface to draw the center of source surface, in pixels.
src the source surface to draw.
cx the x coordinate of the center of rotation.
cy the y coordinate of the center of rotation.
angle the angle to rotate in degrees.
scaleX the x coordinate of scale value.
scaleY the y coordinate of scale value.
void(* ituSetMaskSurface)(ITUSurface *surface, ITUMaskSurface *maskSurface, bool enable)
void(* ituSetRotation)(ITURotation rot)
Sets rotation.
Parameters
rot the rotation.
void(* ituStretchBlt)(ITUSurface *dest, int dx, int dy, int dw, int dh, ITUSurface *src, int sx, int sy, int sw, int sh)
Stretchblts source surface to destination surface.
Parameters
dest the destination surface to draw to.
dx the x coordinate of destination surface, in pixels.
dy the y coordinate of destination surface, in pixels.
dw the destination width to stretchblt, in pixels.
dh the destination height to stretchblt, in pixels.
src the source surface to draw.
sx the x coordinate of source surface, in pixels.
sy the y coordinate of source surface, in pixels.
sw the source width to stretchblt, in pixels.
sh the source height to stretchblt, in pixels.
void(* ituTransform)(ITUSurface *dest, int dx, int dy, int dw, int dh, ITUSurface *src, int sx, int sy, int sw, int sh, int cx, int cy, float scaleWidth, float scaleHeight, float angle, ITUTileMode tilemode, bool enableAlpha, bool enableConstantAlpha, uint8_t constantAlphaValue)
void(* ituTransformBlt)(ITUSurface *dest, int dx, int dy, ITUSurface *src, int sx, int sy, int sw, int sh, int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3, bool bInverse, ITUPageFlowType type, ITUTransformType transformType)
Transformblits source surface to destination surface.
Parameters
dest the destination surface to draw to.
dx the x coordinate of destination surface, in pixels.
dy the y coordinate of destination surface, in pixels.
src the source surface to draw.
sx the x coordinate of source surface, in pixels.
sy the y coordinate of source surface, in pixels.
sw the source width to transformblt, in pixels.
sh the source height to transformblt, in pixels.
x0 the x coordinate of point 0 on source surface, in pixels.
y0 the y coordinate of point 0 of source surface, in pixels.
x1 the x coordinate of point 1 on source surface, in pixels.
y1 the y coordinate of point 1 of source surface, in pixels.
x2 the x coordinate of point 2 on source surface, in pixels.
y2 the y coordinate of point 2 of source surface, in pixels.
x3 the x coordinate of point 3 on source surface, in pixels.
y3 the y coordinate of point 3 of source surface, in pixels.
void(* ituUnlockSurface)(ITUSurface *surf)
Unlocks surface.
Parameters
surf the surface to unlock.