ITE SoC SDK: Files CRC check
Files CRC check
ITE Upgrade Library
Functions
int ugCheckFilesCrc (char *path, char *crcpath)
Checks files CRCs by crc file at specified path.
int ugSetFileCrc (char *filepath, char *path, char *crcpath)
Sets file's CRC to crc file.
int ugUpgradeFilesCrc (char *path, char *crcpath)
Upgrades the files' CRC of crc file.
int ugCopyFile (const char *destPath, const char *srcPath)
Copies file.
int ugRestoreDir (const char *dest, const char *src)
Restores directory.
int ugCopyDirectory (const char *dest, const char *src)
Copies directory recursively.
void ugDeleteDirectory (char *dirname)
Deletes directory recursively.
Detailed Description
Function Documentation
int ugCheckFilesCrc (char * path, char * crcpath)
Checks files CRCs by crc file at specified path.
Parameters
path the root path to check.
crcpath the saved crc file path to verify.
Returns
0 (OK), or otherwise (ERROR).
Referenced by UpgradeInit().
int ugCopyDirectory (const char * dest, const char * src)
Copies directory recursively.
Parameters
dest The path of destination directory.
src The path of source directory.
Returns
0 (OK), or otherwise (ERROR).
int ugCopyFile (const char * destPath, const char * srcPath)
Copies file.
Parameters
destPath The path of destination file.
srcPath The path of source file.
Returns
0 (OK), or otherwise (ERROR).
void ugDeleteDirectory (char * dirname)
Deletes directory recursively.
Parameters
dirname The path of destination directory to delete.
int ugRestoreDir (const char * dest, const char * src)
Restores directory.
Parameters
dest The path of destination directory.
src The path of source directory.
Returns
0 (OK), or otherwise (ERROR).
int ugSetFileCrc (char * filepath, char * path, char * crcpath)
Sets file's CRC to crc file.
Parameters
filepath the relative path of file to calculate crc and save.
path The path to save to crc file.
crcpath the crc file path to save.
Returns
0 (OK), or otherwise (ERROR).
Example:
 int ret;
 ret = ugCheckFilesCrc("B:", "B:/ite_crc.dat");
 if (ret)
     return ret; // check crc fail
 ret = ugSetFileCrc("/font/DroidSans.ttf", "B:", "B:/ite_crc.dat");
 if (ret)
     return ret; // set crc fail
Referenced by UpgradeSetFileCrc().
int ugUpgradeFilesCrc (char * path, char * crcpath)
Upgrades the files' CRC of crc file.
Parameters
path The path to upgrade to crc file.
crcpath the crc file path to upgrade.
Returns
0 (OK), or otherwise (ERROR).
Referenced by UpgradeFilesCrc().