ITE SoC SDK: Video Memo
Video Memo
ITE DoorBell Indoor Modules
Data Structures
struct VideoMemoEntry
Video memo definition.
Macros
#define VIDEOMEMO_MAX_FILENAME_SIZE 40
Maximum size of video memo file name.
#define VIDEOMEMO_MAX_NAME_SIZE 40
Maximum count of video memo item name.
Functions
void VideoMemoInit (void)
Initializes video memo module.
void VideoMemoExit (void)
Exits video memo module.
int VideoMemoGetCount (void)
Gets total count of video memo file.
int VideoMemoGetUnplayCount (void)
Gets unplay count of video memo file.
VideoMemoEntry * VideoMemoGetEntry (int index)
Gets the video memo entry by index.
void VideoMemoDeleteEntry (int index)
Deletes the video memo entry by index.
bool VideoMemoIsPlayFinished (void)
Playing the video memo file is finished or not.
int VideoMemoStartPlay (int index)
Plays the video memo file.
void VideoMemoStopPlay (void)
Stops playing video memo file.
int VideoMemoStartRecord (MediaType type, char *addr)
Starts recording.
int VideoMemoStopRecord (void)
Stops recording.
char * VideoMemoGetPath (void)
Gets the path of video memo directory.
bool VideoMemoCheckDiskSpace (int max_file_size)
Detailed Description
Macro Definition Documentation
#define VIDEOMEMO_MAX_FILENAME_SIZE 40
Maximum size of video memo file name.
Definition at line 2113 of file doorbell_indoor/doorbell.h.
Referenced by VideoMemoCreateTask(), and VideoMemoStopRecord().
#define VIDEOMEMO_MAX_NAME_SIZE 40
Maximum count of video memo item name.
Definition at line 2114 of file doorbell_indoor/doorbell.h.
Function Documentation
bool VideoMemoCheckDiskSpace (int max_file_size)
Definition at line 527 of file videomemo.c.
References VideoMemoGetPath().
Referenced by VideoMemoStopRecord().
void VideoMemoDeleteEntry (int index)
Deletes the video memo entry by index.
Parameters
index The index of video memo entry.
Definition at line 323 of file videomemo.c.
References i, MAX_VIDEOMEMO_COUNT, videoMemoCount, VideoMemoDeleteFile(), videoMemoInited, and videoMemoQuit.
Referenced by MessagePhotoDeleteConfirmOnPress(), and VideoMemoStopRecord().
void VideoMemoExit (void)
Exits video memo module.
Definition at line 250 of file videomemo.c.
References videoMemoInited, and videoMemoQuit.
Referenced by SDL_main().
int VideoMemoGetCount (void)
Gets total count of video memo file.
Returns
the total count of video memo file.
Definition at line 256 of file videomemo.c.
References videoMemoCount, videoMemoInited, and videoMemoQuit.
Referenced by MessagePhotoTimeListBoxOnLoad(), and MessagePhotoTopicListBoxOnLoad().
VideoMemoEntry* VideoMemoGetEntry (int index)
Gets the video memo entry by index.
Parameters
index The index of video memo entry.
Returns
The video memo entry, NULL if not found.
Definition at line 272 of file videomemo.c.
References VideoMemoEntry::filename, i, MAX_VIDEOMEMO_COUNT, VideoMemoEntry::sec, videoMemoCount, VideoMemoGetPath(), videoMemoInited, videoMemoQuit, and VideoRecordGetTimeLength().
Referenced by MessagePhotoTimeListBoxOnLoad(), MessagePhotoTopicListBoxOnLoad(), and VideoMemoStartPlay().
char* VideoMemoGetPath (void)
Gets the path of video memo directory.
Returns
The path.
Definition at line 504 of file videomemo.c.
References DEVICE_INDOOR2, theDeviceInfo, DeviceInfo::type, and UpgradeGetSDPath().
Referenced by VideoMemoCheckDiskSpace(), VideoMemoCompare(), VideoMemoCreateTask(), VideoMemoDeleteFile(), VideoMemoGetEntry(), VideoMemoStartPlay(), VideoMemoStartRecord(), and VideoMemoStopRecord().
int VideoMemoGetUnplayCount (void)
Gets unplay count of video memo file.
Returns
unplay count of video memo file.
Definition at line 264 of file videomemo.c.
References videoMemoInited, videoMemoQuit, and videoMemoUnplayCount.
Referenced by CheckNewMessages().
void VideoMemoInit (void)
Initializes video memo module.
Definition at line 237 of file videomemo.c.
References attr, videoMemoCount, VideoMemoCreateTask(), videoMemoIndex, videoMemoInited, videoMemoPlayFinished, videoMemoQuit, videoMemoRecording, and videoMemoUnplayCount.
Referenced by SDL_main().
bool VideoMemoIsPlayFinished (void)
Playing the video memo file is finished or not.
Returns
true for finished, false for otherwise.
Definition at line 349 of file videomemo.c.
References videoMemoPlayFinished.
Referenced by MessagePhotoViewOnTimer().
int VideoMemoStartPlay (int index)
Plays the video memo file.
Parameters
index The index of video memo file to play.
Returns
0 for success, otherwise failed.
Definition at line 359 of file videomemo.c.
References VideoMemoEntry::filename, ITP_DEVICE_NOR, ITP_IOCTL_FLUSH, VideoMemoEntry::played, VideoMemoGetEntry(), VideoMemoGetPath(), videoMemoInited, videoMemoPlayFinished, VideoMemoPlayFinished(), videoMemoQuit, videoMemoUnplayCount, and VideoRecordStartPlay().
Referenced by MessagePhotoViewOnEnter().
int VideoMemoStartRecord (MediaType type, char * addr)
Starts recording.
Parameters
type The media type. Only for MEDIA_VIDEO and MEDIA_AUDIO types.
addr The IP address of target to record.
Returns
0 for success, otherwise failed.
Definition at line 392 of file videomemo.c.
References MEDIA_AUDIO, MEDIA_VIDEO, VIDEOMEMO_AUDIO_EXT, VIDEOMEMO_VIDEO_EXT, VideoMemoGetPath(), videoMemoIndex, videoMemoInited, videoMemoQuit, videoMemoRecordFileName, videoMemoRecording, and VideoRecordStartRecord().
Referenced by VideoRecordIncomingShow().
void VideoMemoStopPlay (void)
Stops playing video memo file.
Definition at line 386 of file videomemo.c.
References videoMemoPlayFinished, and VideoRecordStopPlay().
Referenced by MessagePhotoViewOnLeave().
int VideoMemoStopRecord (void)
Stops recording.
Returns
0 for success, otherwise failed.
Definition at line 428 of file videomemo.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, Config::calling_time, CAPUTRE_MAX_NAME_SIZE, VideoMemoEntry::filename, DeviceInfo::floor, MAX_VIDEOMEMO_COUNT, MEDIA_AUDIO, MEDIA_TEXT, MEDIA_VIDEO, VideoMemoEntry::name, VideoMemoEntry::played, DeviceInfo::room, VideoMemoEntry::sec, StringGetRoomAddress(), theConfig, VideoMemoEntry::time, VideoMemoEntry::type, DeviceInfo::unit, VIDEOMEMO_AUDIO_EXT, VIDEOMEMO_MAX_FILENAME_SIZE, VIDEOMEMO_VIDEO_EXT, VideoMemoCheckDiskSpace(), videoMemoCount, VideoMemoDeleteEntry(), VideoMemoGetPath(), videoMemoInited, videoMemoQuit, videoMemoRecordFileName, videoMemoRecording, videoMemoUnplayCount, and VideoRecordStopRecord().
Referenced by VideoRecordOnLeave().