ITE SoC SDK: Platform
Platform
ITE Hardware Library
Used by this module internal.
Enumerations
enum ITHCpuMode {
ITH_CPU_USR = 0x10, ITH_CPU_FIQ = 0x11, ITH_CPU_IRQ = 0x12, ITH_CPU_SVC = 0x13,
ITH_CPU_ABT = 0x17, ITH_CPU_UND = 0x1B, ITH_CPU_SYS = 0x1F
}
CPU mode definitions.
Functions
void ithAssertFail (const char *exp, const char *file, int line, const char *func)
Called when assert fail.
void ithDelay (unsigned long us)
Busy-waiting delay.
void ithLockMutex (void *mutex)
Locks mutex.
void ithUnlockMutex (void *mutex)
Unlocks mutex.
void ithFlushDCache (void)
Flushes CPU's data cache.
void ithInvalidateDCache (void)
Invalidates CPU's data cache.
void ithFlushDCacheRange (void *ptr, uint32_t size)
Flushes CPU's data cache in specified range.
void ithInvalidateDCacheRange (void *ptr, uint32_t size)
Flushes CPU's data cache in specified range.
void ithInvalidateICache (void)
Invalidates CPU's instruction cache.
void ithCpuDoze (void)
CPU Doze, it's gated CPU clock until interrupt happend.
void ithFlushMemBuffer (void)
Flushes Memory buffer.
void ithFlushAhbWrap (void)
Flushes AHB Wrap.
void ithYieldFromISR (bool yield)
Reschedules task after ISR is finished.
void ithEnterCritical (void)
Saves current interrupt states and disable interrupt.
void ithExitCritical (void)
Restore previous saved interrupt states.
void ithTaskYield (void)
Forces a context switch.
ITHCpuMode ithGetCpuMode (void)
Gets CPU mode.
void ithInit (void)
Initialize this module.
void ithExit (void)
Exit this module.
Detailed Description
Used by this module internal.
Enumeration Type Documentation
enum ITHCpuMode
CPU mode definitions.
Enumerator
ITH_CPU_USR
USR_MODE.
ITH_CPU_FIQ
FIQ_MODE.
ITH_CPU_IRQ
IRQ_MODE.
ITH_CPU_SVC
SVC_MODE.
ITH_CPU_ABT
ABT_MODE.
ITH_CPU_UND
UND_MODE.
ITH_CPU_SYS
SYS_MODE.
Definition at line 173 of file ith.h.
Function Documentation
void ithAssertFail (const char * exp, const char * file, int line, const char * func)
Called when assert fail.
Parameters
exp The evaluated expression.
file The evaluated file.
line The evaluated line of file.
func The evaluated function.
void ithCpuDoze (void)
CPU Doze, it's gated CPU clock until interrupt happend.
void ithDelay (unsigned long us)
Busy-waiting delay.
Parameters
us microseconds.
void ithEnterCritical (void)
Saves current interrupt states and disable interrupt.
Examples:
test_uart/test_uart.c.
Referenced by ithIntrDisableIrq(), and ithIntrEnableIrq().
void ithExit (void)
Exit this module.
void ithExitCritical (void)
Restore previous saved interrupt states.
Examples:
test_uart/test_uart.c.
Referenced by ithIntrDisableIrq(), and ithIntrEnableIrq().
void ithFlushAhbWrap (void)
Flushes AHB Wrap.
void ithFlushDCache (void)
Flushes CPU's data cache.
void ithFlushDCacheRange (void * ptr, uint32_t size)
Flushes CPU's data cache in specified range.
Parameters
ptr the memory address to flush.
size the memory size to flush.
Examples:
test_lcd/test_backlight.c, and test_lcd/test_lcd.c.
void ithFlushMemBuffer (void)
Flushes Memory buffer.
ITHCpuMode ithGetCpuMode (void)
Gets CPU mode.
Returns
The CPU mode.
void ithInit (void)
Initialize this module.
void ithInvalidateDCache (void)
Invalidates CPU's data cache.
void ithInvalidateDCacheRange (void * ptr, uint32_t size)
Flushes CPU's data cache in specified range.
Parameters
ptr the memory address to flush.
size the memory size to flush.
void ithInvalidateICache (void)
Invalidates CPU's instruction cache.
void ithLockMutex (void * mutex)
Locks mutex.
Parameters
mutex The mutex object.
Referenced by ithCmdQLock().
void ithTaskYield (void)
Forces a context switch.
void ithUnlockMutex (void * mutex)
Unlocks mutex.
Parameters
mutex The mutex object.
Referenced by ithCmdQUnlock().
void ithYieldFromISR (bool yield)
Reschedules task after ISR is finished.
Parameters
yield task yield if yield is true.