ITE SoC SDK: guard.c File Reference
guard.c File Reference
#include <sys/ioctl.h>
#include <sys/time.h>
#include <assert.h>
#include <pthread.h>
#include <string.h>
#include "ite/itp.h"
#include "libxml/xpath.h"
#include "doorbell.h"
Data Structures
struct GuardSensorStatus
Macros
#define MAX_GUARD_LOG_COUNT 999
#define GUARD_ALARM_DELAY (1 * 1000 / 33)
Functions
static void GuardWriteLog (GuardSensor sensor, GuardStatus status, unsigned long timestamp)
static void GuardWriteSyncLog (GuardLog *log)
static void GuardEnableSensor (GuardSensor sensor)
static void GuardDisableSensor (GuardSensor sensor)
void GuardInit (void)
Initializes guard module.
void GuardExit (void)
Exits guard module.
void GuardSetMode (GuardMode mode)
Sets guard mode.
int GuardCheck (void)
Checks guard events.
GuardStatus GuardGetSensorStatus (GuardSensor sensor)
Gets the status of the specified sensor.
unsigned long GuardGetSensorTime (GuardSensor sensor)
Gets the last active time of the specified sensor.
int GuardGetLogCount (void)
Gets total count of guard logging.
GuardLog * GuardGetLog (int index)
Gets the guard logging entry by the specified index.
void GuardDeleteLog (int index)
Deletes the guard logging entry by the specified index.
void GuardClearLog (void)
Clears all the guard logging entries.
bool GuardIsAlarming (void)
Guard is alarming or not.
void GuardSetAlarming (bool alarming)
Sets the guard alarming status.
void GuardReceiveSyncLog (char *xml, int size)
Receives the XML of guard sync log.
Variables
static GuardSensorStatus guardSensorStatusArray [GUARD_SENSOR_COUNT]
static bool guardSensorAlarmedTable [GUARD_SENSOR_COUNT]
static unsigned int guardSensorLastValue = 0
static bool guardAlarming
static int guardLogCount
static GuardLog guardLogArray [MAX_GUARD_LOG_COUNT]
static pthread_mutex_t guardLogMutex
Macro Definition Documentation
#define GUARD_ALARM_DELAY (1 * 1000 / 33)
Definition at line 33 of file guard.c.
Referenced by GuardCheck().
#define MAX_GUARD_LOG_COUNT 999
Definition at line 32 of file guard.c.
Referenced by GuardDeleteLog(), GuardGetLog(), GuardWriteLog(), and GuardWriteSyncLog().
Function Documentation
static void GuardDisableSensor (GuardSensor sensor) static
Definition at line 167 of file guard.c.
References GuardSensorStatus::alarmDelay, GuardSensorStatus::alarming, GuardSensorStatus::enabled, EventWriteGuardLog(), GUARD_DISABLE, GUARD_UNALARM, GuardWriteLog(), ithGpioDisableIntr(), and GuardSensorStatus::time.
Referenced by GuardSetMode().
static void GuardEnableSensor (GuardSensor sensor) static
Definition at line 122 of file guard.c.
References GuardSensorStatus::alarmDelay, GuardSensorStatus::enabled, EventWriteGuardLog(), GUARD_ENABLE, Config::guard_sensor_initvalues, guardSensorLastValue, GuardWriteLog(), IOEXPANDER_0, ITH_GPIO_INTR_BOTHEDGE, ithGpioClear(), ithGpioCtrlEnable(), ithGpioEnable(), ithGpioEnableIntr(), ithGpioRegisterIntrHandler(), ithGpioSet(), ithGpioSetIn(), itpIOExpanderGet(), itpIOExpanderSet(), itpIOExpanderSetIn(), itpRegisterIOExpanderDeferIntrHandler(), theConfig, and GuardSensorStatus::time.
Referenced by GuardSetMode().
static void GuardWriteLog (GuardSensor sensor, GuardStatus status, unsigned long timestamp) static
Definition at line 80 of file guard.c.
References GuardDeleteLog(), guardLogCount, guardLogMutex, MAX_GUARD_LOG_COUNT, GuardLog::sensor, GuardLog::status, and GuardLog::timestamp.
Referenced by GuardCheck(), GuardDisableSensor(), and GuardEnableSensor().
static void GuardWriteSyncLog (GuardLog * log) static
Definition at line 103 of file guard.c.
References GuardDeleteLog(), guardLogCount, guardLogMutex, and MAX_GUARD_LOG_COUNT.
Referenced by GuardReceiveSyncLog().
Variable Documentation
bool guardAlarming static
Definition at line 30 of file guard.c.
Referenced by GuardInit(), GuardIsAlarming(), and GuardSetAlarming().
GuardLog guardLogArray[MAX_GUARD_LOG_COUNT] static
Definition at line 36 of file guard.c.
int guardLogCount static
Definition at line 35 of file guard.c.
Referenced by GuardClearLog(), GuardDeleteLog(), GuardGetLog(), GuardGetLogCount(), GuardInit(), GuardWriteLog(), and GuardWriteSyncLog().
pthread_mutex_t guardLogMutex static
Definition at line 37 of file guard.c.
Referenced by GuardDeleteLog(), GuardExit(), GuardInit(), GuardWriteLog(), and GuardWriteSyncLog().
bool guardSensorAlarmedTable[GUARD_SENSOR_COUNT] static
Definition at line 28 of file guard.c.
unsigned int guardSensorLastValue = 0 static
Definition at line 29 of file guard.c.
Referenced by GuardCheck(), GuardEnableSensor(), and GuardInit().
GuardSensorStatus guardSensorStatusArray[GUARD_SENSOR_COUNT] static
Definition at line 18 of file guard.c.