ITE SoC SDK: ith_dma.h File Reference
ith_dma.h File Reference
Castor DMA hardware abstraction layer.
Data Structures
struct ITHDma
Macros
#define ITH_DMA_H
#define DMA_IRQ_ENABLE
#define ITH_DMA_CH_NUM 8
#define ITH_DMA_INTS_TC 0x1
#define ITH_DMA_INTS_ERR 0x2
#define ITH_DMA_INTS_ABT 0x4
Typedefs
typedef void(* ITHDmaIntrHandler)(int ch, void *arg, uint32_t int_status)
Functions
static void ithDmaSetRequest (int ch, ITHDmaMode srcMode, ITHDmaRequest srcReq, ITHDmaMode dstMode, ITHDmaRequest dstReq)
static void ithDmaSetSrcAddr (int ch, uint32_t addr)
static void ithDmaSetDstAddr (int ch, uint32_t addr)
static void ithDmaSetTxSize (int ch, uint32_t size)
static void ithDmaSetSrcParams (int ch, ITHDmaWidth width, ITHDmaAddrCtl ctl, ITHDmaDataMaster master)
static void ithDmaSetDstParams (int ch, ITHDmaWidth width, ITHDmaAddrCtl ctl, ITHDmaDataMaster master)
static void ithDmaSetBurst (int ch, ITHDmaBurst burst)
static void ithDmaSetLLPAddr (int ch, uint32_t llpaddr)
static void ithDmaAbort (int ch)
static int ithDmaIsBusy (int ch)
void ithDmaInit (void *mutex)
int ithDmaRequestCh (char *name, ITHDmaPriority priority, ITHDmaIntrHandler isr, void *arg)
void ithDmaFreeCh (int ch)
void ithDmaReset (int ch)
void ithDmaDumpReg (int ch)
void ithDmaStart (int ch)
Variables
ITHDma dmaCtxt [ITH_DMA_CH_NUM]
ITHDmaWidth dmaWidthMap [4]
Detailed Description
Castor DMA hardware abstraction layer.
Author
Irene Lin
Version
1.0
Definition in file ith_dma.h.
Macro Definition Documentation
#define DMA_IRQ_ENABLE
Definition at line 20 of file ith_dma.h.
#define ITH_DMA_CH_NUM 8
Definition at line 22 of file ith_dma.h.
#define ITH_DMA_H
Definition at line 17 of file ith_dma.h.
#define ITH_DMA_INTS_ABT 0x4
Definition at line 28 of file ith_dma.h.
#define ITH_DMA_INTS_ERR 0x2
Definition at line 27 of file ith_dma.h.
#define ITH_DMA_INTS_TC 0x1
Definition at line 26 of file ith_dma.h.
Typedef Documentation
typedef void(* ITHDmaIntrHandler)(int ch, void *arg, uint32_t int_status)
Definition at line 25 of file ith_dma.h.
Function Documentation
static void ithDmaAbort (int ch) inline static
Definition at line 126 of file ith_dma.h.
References ITH_DMA_ABT_MASK, ITH_DMA_BASE, ITH_DMA_C0_CSR_REG, ITH_DMA_CH_OFFSET, and ithWriteRegA().
void ithDmaDumpReg (int ch)
void ithDmaFreeCh (int ch)
void ithDmaInit (void * mutex)
static int ithDmaIsBusy (int ch) inline static
Definition at line 131 of file ith_dma.h.
References ITH_DMA_BASE, ITH_DMA_C0_CSR_REG, ITH_DMA_CH_EN_MASK, ITH_DMA_CH_OFFSET, and ithReadRegA().
int ithDmaRequestCh (char * name, ITHDmaPriority priority, ITHDmaIntrHandler isr, void * arg)
void ithDmaReset (int ch)
static void ithDmaSetBurst (int ch, ITHDmaBurst burst) inline static
Definition at line 116 of file ith_dma.h.
References ITHDma::burst.
static void ithDmaSetDstAddr (int ch, uint32_t addr) inline static
Definition at line 89 of file ith_dma.h.
References ITHDma::dstAddr, ITH_DMA_BASE, ITH_DMA_C0_DSTADR_REG, ITH_DMA_CH_OFFSET, and ithWriteRegA().
static void ithDmaSetDstParams (int ch, ITHDmaWidth width, ITHDmaAddrCtl ctl, ITHDmaDataMaster master) inline static
Definition at line 109 of file ith_dma.h.
References ITHDma::dstCtrl, ITHDma::dstSel, and ITHDma::dstWidth.
static void ithDmaSetLLPAddr (int ch, uint32_t llpaddr) inline static
Definition at line 121 of file ith_dma.h.
References ITHDma::lldAddr.
static void ithDmaSetRequest (int ch, ITHDmaMode srcMode, ITHDmaRequest srcReq, ITHDmaMode dstMode, ITHDmaRequest dstReq) inline static
Definition at line 64 of file ith_dma.h.
References ITHDma::dstHw, ITHDma::hw, ITH_DMA_BASE, ITH_DMA_C0_CFG_REG, ITH_DMA_CH_OFFSET, ITH_DMA_INT_MASK, ITH_DST_HE_BIT, ITH_DST_RS_BIT, ITH_SRC_HE_BIT, ITH_SRC_RS_BIT, ithWriteRegA(), and ITHDma::srcHw.
static void ithDmaSetSrcAddr (int ch, uint32_t addr) inline static
Definition at line 81 of file ith_dma.h.
References ITH_DMA_BASE, ITH_DMA_C0_SRCADR_REG, ITH_DMA_CH_OFFSET, ithWriteRegA(), and ITHDma::srcAddr.
static void ithDmaSetSrcParams (int ch, ITHDmaWidth width, ITHDmaAddrCtl ctl, ITHDmaDataMaster master) inline static
Definition at line 102 of file ith_dma.h.
References ITHDma::srcCtrl, ITHDma::srcSel, and ITHDma::srcWidth.
static void ithDmaSetTxSize (int ch, uint32_t size) inline static
Definition at line 97 of file ith_dma.h.
References ITHDma::txSize.
void ithDmaStart (int ch)
Variable Documentation
ITHDma dmaCtxt[ITH_DMA_CH_NUM]
ITHDmaWidth dmaWidthMap[4]