ITE SoC SDK: itp_codec.h File Reference
itp_codec.h File Reference
Functions
void itp_codec_wake_up (void)
void itp_codec_standby (void)
void itp_codec_playback_init (unsigned output)
void itp_codec_playback_deinit (void)
void itp_codec_playback_amp_volume_down (void)
void itp_codec_playback_amp_volume_up (void)
void itp_codec_playback_set_direct_vol (unsigned target_vol)
void itp_codec_playback_set_direct_volperc (unsigned target_volperc)
void itp_codec_playback_get_currvol (unsigned *currvol)
void itp_codec_playback_get_currvolperc (unsigned *currvolperc)
void itp_codec_playback_get_vol_range (unsigned *max, unsigned *regular_0db, unsigned *min)
void itp_codec_playback_mute (void)
void itp_codec_playback_unmute (void)
void itp_codec_playback_linein_bypass (unsigned bypass)
void itp_codec_rec_init (unsigned input_source)
void itp_codec_rec_deinit (void)
void itp_codec_rec_set_direct_vol (unsigned target_vol)
void itp_codec_rec_get_currvol (unsigned *currvol)
void itp_codec_rec_get_vol_range (unsigned *max, unsigned *regular_0db, unsigned *min)
void itp_codec_rec_mute (void)
void itp_codec_rec_unmute (void)
void itp_codec_get_i2s_sample_rate (int *samplerate)
void itp_codec_set_i2s_sample_rate (int samplerate)
Function Documentation
void itp_codec_get_i2s_sample_rate (int * samplerate)
void itp_codec_playback_amp_volume_down (void)
void itp_codec_playback_amp_volume_up (void)
void itp_codec_playback_deinit (void)
void itp_codec_playback_get_currvol (unsigned * currvol)
void itp_codec_playback_get_currvolperc (unsigned * currvolperc)
void itp_codec_playback_get_vol_range (unsigned * max, unsigned * regular_0db, unsigned * min)
void itp_codec_playback_init (unsigned output)
void itp_codec_playback_linein_bypass (unsigned bypass)
void itp_codec_playback_mute (void)
void itp_codec_playback_set_direct_vol (unsigned target_vol)
void itp_codec_playback_set_direct_volperc (unsigned target_volperc)
void itp_codec_playback_unmute (void)
void itp_codec_rec_deinit (void)
void itp_codec_rec_get_currvol (unsigned * currvol)
void itp_codec_rec_get_vol_range (unsigned * max, unsigned * regular_0db, unsigned * min)
void itp_codec_rec_init (unsigned input_source)
void itp_codec_rec_mute (void)
void itp_codec_rec_set_direct_vol (unsigned target_vol)
void itp_codec_rec_unmute (void)
void itp_codec_set_i2s_sample_rate (int samplerate)
void itp_codec_standby (void)
Referenced by create_response(), SDL_main(), SettingEngineerNetworkSaveButtonOnPress(), and TouchCalibrationCheckBoxOnPress().
void itp_codec_wake_up (void)