ITE SoC SDK: layer_phone_contacts_keypad.c File Reference
layer_phone_contacts_keypad.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool PhoneContactsKeypadCloseButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeypadBackButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeypadConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsKeypadNumberButtonOnPress (ITUWidget *widget, char *param)
void PhoneContactsKeypadShow (DeviceInfo *info, ITULayer *lastLayer)
Sets the infomation to show on the contact address keypad dialog.
bool PhoneContactsKeypadOnEnter (ITUWidget *widget, char *param)
void PhoneContactsKeypadReset (void)
Variables
static ITULayer * phoneContactsAddLayer
static ITULayer * phoneContactsModifyLayer
static ITUTextBox * phoneContactsKeypadAreaTextBox
static ITUTextBox * phoneContactsKeypadBuildingTextBox
static ITUTextBox * phoneContactsKeypadUnitTextBox
static ITUTextBox * phoneContactsKeypadFloorTextBox
static ITUTextBox * phoneContactsKeypadRoomTextBox
static ITUTextBox * activePhoneContactsKeypadTextBox
static ITULayer * phoneContactsKeypadLastLayer
Function Documentation
bool PhoneContactsKeypadBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 31 of file layer_phone_contacts_keypad.c.
References ituTextSetString, phoneContactsKeypadAreaTextBox, phoneContactsKeypadBuildingTextBox, phoneContactsKeypadFloorTextBox, and phoneContactsKeypadUnitTextBox.
bool PhoneContactsKeypadCloseButtonOnPress (ITUWidget * widget, char * param)
Definition at line 19 of file layer_phone_contacts_keypad.c.
References ituLayerGoto(), PhoneContactsAddShow(), and PhoneContactsModifyShow().
bool PhoneContactsKeypadConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 54 of file layer_phone_contacts_keypad.c.
References DeviceInfo::area, DeviceInfo::building, DeviceInfo::floor, ituLayerGoto(), ituTextGetString, PhoneContactsAddShow(), PhoneContactsModifyShow(), DeviceInfo::room, and DeviceInfo::unit.
bool PhoneContactsKeypadNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 75 of file layer_phone_contacts_keypad.c.
References ituTextBoxInput(), ituTextGetString, ITUTextBox::maxLen, phoneContactsKeypadBuildingTextBox, phoneContactsKeypadFloorTextBox, phoneContactsKeypadRoomTextBox, phoneContactsKeypadUnitTextBox, and ITUButton::text.
bool PhoneContactsKeypadOnEnter (ITUWidget * widget, char * param)
Definition at line 139 of file layer_phone_contacts_keypad.c.
References ituSceneFindWidget(), and theScene.
void PhoneContactsKeypadReset (void)
Definition at line 170 of file layer_phone_contacts_keypad.c.
Referenced by resetScene().
Variable Documentation
ITUTextBox* activePhoneContactsKeypadTextBox static
Definition at line 16 of file layer_phone_contacts_keypad.c.
ITULayer* phoneContactsAddLayer static
Definition at line 8 of file layer_phone_contacts_keypad.c.
ITUTextBox* phoneContactsKeypadAreaTextBox static
Definition at line 10 of file layer_phone_contacts_keypad.c.
Referenced by PhoneContactsKeypadBackButtonOnPress(), and PhoneContactsKeypadShow().
ITUTextBox* phoneContactsKeypadBuildingTextBox static
Definition at line 11 of file layer_phone_contacts_keypad.c.
Referenced by PhoneContactsKeypadBackButtonOnPress(), PhoneContactsKeypadNumberButtonOnPress(), and PhoneContactsKeypadShow().
ITUTextBox* phoneContactsKeypadFloorTextBox static
Definition at line 13 of file layer_phone_contacts_keypad.c.
Referenced by PhoneContactsKeypadBackButtonOnPress(), PhoneContactsKeypadNumberButtonOnPress(), and PhoneContactsKeypadShow().
ITULayer* phoneContactsKeypadLastLayer static
Definition at line 17 of file layer_phone_contacts_keypad.c.
ITUTextBox* phoneContactsKeypadRoomTextBox static
Definition at line 14 of file layer_phone_contacts_keypad.c.
Referenced by PhoneContactsKeypadNumberButtonOnPress(), and PhoneContactsKeypadShow().
ITUTextBox* phoneContactsKeypadUnitTextBox static
Definition at line 12 of file layer_phone_contacts_keypad.c.
Referenced by PhoneContactsKeypadBackButtonOnPress(), PhoneContactsKeypadNumberButtonOnPress(), and PhoneContactsKeypadShow().
ITULayer* phoneContactsModifyLayer static
Definition at line 9 of file layer_phone_contacts_keypad.c.