ITE SoC SDK: layer_setting_outdoor_main.c File Reference
layer_setting_outdoor_main.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool SettingOutdoorMainRingVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainRingVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainPlayVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainPlayVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainMicVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingOutdoorMainMicVolUpButtonOnPress (ITUWidget *widget, char *param)
static void GetOutdoorInfoCallback (ServerInfo *info)
bool SettingOutdoorMainMessageListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingOutdoorMainMessageListBoxOnSelection (ITUWidget *widget, char *param)
bool SettingOutdoorMainOnTimer (ITUWidget *widget, char *param)
bool SettingOutdoorMainOnEnter (ITUWidget *widget, char *param)
bool SettingOutdoorMainOnLeave (ITUWidget *widget, char *param)
void SettingOutdoorMainReset (void)
Variables
static ITUListBox * settingOutdoorMainMessageListbox
static ITUSprite * settingOutdoorMainRingVolBar
static ITUSprite * settingOutdoorMainPlayVolBar
static ITUSprite * settingOutdoorMainMicVolBar
ServerInfo settingOutdoorMainOutdoorInfo
DeviceInfo settingOutdoorMainInfoArray [MAX_OUTDOOR_COUNT]
int settingOutdoorMainInfoIndex
int settingOutdoorMainLastRingLevel
int settingOutdoorMainLastPlayLevel
int settingOutdoorMainLastMicLevel
static int settingOutdoorMainInfoCount
static bool settingOutdoorMainInfoFilled
static int settingOutdoorMainMaxRingVol
static int settingOutdoorMainMaxPlayVol
static int settingOutdoorMainMaxMicVol
Function Documentation
static void GetOutdoorInfoCallback (ServerInfo * info) static
Definition at line 124 of file layer_setting_outdoor_main.c.
References settingOutdoorMainInfoFilled.
Referenced by SettingOutdoorMainMessageListBoxOnLoad().
bool SettingOutdoorMainMessageListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 130 of file layer_setting_outdoor_main.c.
References ServerInfo::addressBookVersion, DeviceInfo::area, DeviceInfo::building, ITCTreeTag::child, DeviceInfo::ext, ServerInfo::firmwareVersion, DeviceInfo::floor, ITUListBoxTag::focusIndex, GetOutdoorInfoCallback(), i, DeviceInfo::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituSpriteGoto(), ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ServerInfo::playLevel, ServerInfo::recLevel, RemoteGetOutdoorInfo(), ServerInfo::ringLevel, DeviceInfo::room, settingOutdoorMainInfoCount, settingOutdoorMainInfoFilled, settingOutdoorMainInfoIndex, settingOutdoorMainLastMicLevel, settingOutdoorMainLastPlayLevel, settingOutdoorMainLastRingLevel, settingOutdoorMainMaxMicVol, settingOutdoorMainMaxPlayVol, settingOutdoorMainMaxRingVol, ITCTreeTag::sibling, StringGetDeviceType(), StringGetRoomAddress(), DeviceInfo::type, and DeviceInfo::unit.
Referenced by SettingOutdoorMainOnTimer().
bool SettingOutdoorMainMessageListBoxOnSelection (ITUWidget * widget, char * param)
Definition at line 255 of file layer_setting_outdoor_main.c.
References ituListBoxSelect().
bool SettingOutdoorMainMicVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 92 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastMicLevel, and settingOutdoorMainMaxMicVol.
bool SettingOutdoorMainMicVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 108 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastMicLevel, and settingOutdoorMainMaxMicVol.
bool SettingOutdoorMainOnEnter (ITUWidget * widget, char * param)
Definition at line 274 of file layer_setting_outdoor_main.c.
References AddressBookGetOutdoorInfoArray(), DeviceInfo::area, DeviceInfo::building, DeviceInfo::floor, itcTreeGetChildCount, ituListBoxReload(), ituSceneFindWidget(), ituSpriteGoto(), MAX_OUTDOOR_COUNT, DeviceInfo::room, settingOutdoorMainInfoCount, settingOutdoorMainInfoFilled, settingOutdoorMainInfoIndex, settingOutdoorMainLastMicLevel, settingOutdoorMainLastPlayLevel, settingOutdoorMainLastRingLevel, settingOutdoorMainMaxMicVol, settingOutdoorMainMaxPlayVol, settingOutdoorMainMaxRingVol, theDeviceInfo, theScene, and DeviceInfo::unit.
bool SettingOutdoorMainOnLeave (ITUWidget * widget, char * param)
Definition at line 313 of file layer_setting_outdoor_main.c.
bool SettingOutdoorMainOnTimer (ITUWidget * widget, char * param)
Definition at line 264 of file layer_setting_outdoor_main.c.
References settingOutdoorMainInfoFilled, and SettingOutdoorMainMessageListBoxOnLoad().
bool SettingOutdoorMainPlayVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 60 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastPlayLevel, and settingOutdoorMainMaxPlayVol.
bool SettingOutdoorMainPlayVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 76 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastPlayLevel, and settingOutdoorMainMaxPlayVol.
void SettingOutdoorMainReset (void)
Definition at line 318 of file layer_setting_outdoor_main.c.
References settingOutdoorMainInfoCount.
Referenced by resetScene().
bool SettingOutdoorMainRingVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 28 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastRingLevel, and settingOutdoorMainMaxRingVol.
bool SettingOutdoorMainRingVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 44 of file layer_setting_outdoor_main.c.
References ituSpriteGoto(), settingOutdoorMainLastRingLevel, and settingOutdoorMainMaxRingVol.
Variable Documentation
DeviceInfo settingOutdoorMainInfoArray[MAX_OUTDOOR_COUNT]
Definition at line 15 of file layer_setting_outdoor_main.c.
int settingOutdoorMainInfoCount static
Definition at line 21 of file layer_setting_outdoor_main.c.
Referenced by SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainOnEnter(), and SettingOutdoorMainReset().
bool settingOutdoorMainInfoFilled static
Definition at line 22 of file layer_setting_outdoor_main.c.
Referenced by GetOutdoorInfoCallback(), SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainOnEnter(), and SettingOutdoorMainOnTimer().
int settingOutdoorMainInfoIndex
Definition at line 16 of file layer_setting_outdoor_main.c.
Referenced by SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainOnEnter(), SettingOutdoorMiscOnEnter(), and SettingOutdoorMiscSaveButtonOnPress().
int settingOutdoorMainLastMicLevel
Definition at line 19 of file layer_setting_outdoor_main.c.
Referenced by SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainMicVolDownButtonOnPress(), SettingOutdoorMainMicVolUpButtonOnPress(), SettingOutdoorMainOnEnter(), and SettingOutdoorMiscSaveButtonOnPress().
int settingOutdoorMainLastPlayLevel
Definition at line 18 of file layer_setting_outdoor_main.c.
Referenced by SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainOnEnter(), SettingOutdoorMainPlayVolDownButtonOnPress(), SettingOutdoorMainPlayVolUpButtonOnPress(), and SettingOutdoorMiscSaveButtonOnPress().
int settingOutdoorMainLastRingLevel
Definition at line 17 of file layer_setting_outdoor_main.c.
Referenced by SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainOnEnter(), SettingOutdoorMainRingVolDownButtonOnPress(), SettingOutdoorMainRingVolUpButtonOnPress(), and SettingOutdoorMiscSaveButtonOnPress().
int settingOutdoorMainMaxMicVol static
Definition at line 26 of file layer_setting_outdoor_main.c.
Referenced by SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainMicVolDownButtonOnPress(), SettingOutdoorMainMicVolUpButtonOnPress(), and SettingOutdoorMainOnEnter().
int settingOutdoorMainMaxPlayVol static
Definition at line 25 of file layer_setting_outdoor_main.c.
Referenced by SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainOnEnter(), SettingOutdoorMainPlayVolDownButtonOnPress(), and SettingOutdoorMainPlayVolUpButtonOnPress().
int settingOutdoorMainMaxRingVol static
Definition at line 24 of file layer_setting_outdoor_main.c.
Referenced by SettingOutdoorMainMessageListBoxOnLoad(), SettingOutdoorMainOnEnter(), SettingOutdoorMainRingVolDownButtonOnPress(), and SettingOutdoorMainRingVolUpButtonOnPress().
ITUListBox* settingOutdoorMainMessageListbox static
Definition at line 8 of file layer_setting_outdoor_main.c.
ITUSprite* settingOutdoorMainMicVolBar static
Definition at line 11 of file layer_setting_outdoor_main.c.
ServerInfo settingOutdoorMainOutdoorInfo
Definition at line 14 of file layer_setting_outdoor_main.c.
ITUSprite* settingOutdoorMainPlayVolBar static
Definition at line 10 of file layer_setting_outdoor_main.c.
ITUSprite* settingOutdoorMainRingVolBar static
Definition at line 9 of file layer_setting_outdoor_main.c.