ITE SoC SDK: layer_setting_engineer_sensor.c File Reference
layer_setting_engineer_sensor.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
Functions
bool SettingEngineerSensorSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerSensorCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerSensorOnEnter (ITUWidget *widget, char *param)
void SettingEngineerSensorReset (void)
Variables
static ITURadioBox * settingEngineerSensorEmergencyOffRadioBox
static ITURadioBox * settingEngineerSensorEmergencyOnRadioBox
static ITURadioBox * settingEngineerSensorInfraredOffRadioBox
static ITURadioBox * settingEngineerSensorInfraredOnRadioBox
static ITURadioBox * settingEngineerSensorDoorOffRadioBox
static ITURadioBox * settingEngineerSensorDoorOnRadioBox
static ITURadioBox * settingEngineerSensorWindowOffRadioBox
static ITURadioBox * settingEngineerSensorWindowOnRadioBox
static ITURadioBox * settingEngineerSensorSmokeOffRadioBox
static ITURadioBox * settingEngineerSensorSmokeOnRadioBox
static ITURadioBox * settingEngineerSensorGasOffRadioBox
static ITURadioBox * settingEngineerSensorGasOnRadioBox
static ITURadioBox * settingEngineerSensorAreaOffRadioBox
static ITURadioBox * settingEngineerSensorAreaOnRadioBox
static ITURadioBox * settingEngineerSensorRobOffRadioBox
static ITURadioBox * settingEngineerSensorRobOnRadioBox
Function Documentation
bool SettingEngineerSensorCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 40 of file layer_setting_engineer_sensor.c.
References ituRadioBoxSetChecked().
bool SettingEngineerSensorOnEnter (ITUWidget * widget, char * param)
Definition at line 53 of file layer_setting_engineer_sensor.c.
References GUARD_AREA, GUARD_DOOR, GUARD_EMERGENCY, GUARD_GAS, GUARD_INFRARED, GUARD_ROB, Config::guard_sensor_initvalues, GUARD_SMOKE, GUARD_WINDOW, ituRadioBoxSetChecked(), ituSceneFindWidget(), theConfig, and theScene.
void SettingEngineerSensorReset (void)
Definition at line 148 of file layer_setting_engineer_sensor.c.
Referenced by resetScene().
bool SettingEngineerSensorSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 25 of file layer_setting_engineer_sensor.c.
References ConfigSave(), GUARD_AREA, GUARD_DOOR, GUARD_EMERGENCY, GUARD_GAS, GUARD_INFRARED, GUARD_ROB, Config::guard_sensor_initvalues, GUARD_SMOKE, GUARD_WINDOW, ituRadioBoxIsChecked(), and theConfig.
Variable Documentation
ITURadioBox* settingEngineerSensorAreaOffRadioBox static
Definition at line 20 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorAreaOnRadioBox static
Definition at line 21 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorDoorOffRadioBox static
Definition at line 12 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorDoorOnRadioBox static
Definition at line 13 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorEmergencyOffRadioBox static
Definition at line 8 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorEmergencyOnRadioBox static
Definition at line 9 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorGasOffRadioBox static
Definition at line 18 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorGasOnRadioBox static
Definition at line 19 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorInfraredOffRadioBox static
Definition at line 10 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorInfraredOnRadioBox static
Definition at line 11 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorRobOffRadioBox static
Definition at line 22 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorRobOnRadioBox static
Definition at line 23 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorSmokeOffRadioBox static
Definition at line 16 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorSmokeOnRadioBox static
Definition at line 17 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorWindowOffRadioBox static
Definition at line 14 of file layer_setting_engineer_sensor.c.
ITURadioBox* settingEngineerSensorWindowOnRadioBox static
Definition at line 15 of file layer_setting_engineer_sensor.c.