ITE SoC SDK: layer_setting_display.c File Reference
layer_setting_display.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Macros
#define ENG "eng"
#define CHS "chs"
#define CHT "cht"
Functions
bool SettingDisplayBrightnessDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayBrightnessUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayScreensaverTimeButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayTimeKeypadConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplaySaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingDisplayOnEnter (ITUWidget *widget, char *param)
bool SettingDisplayOnLeave (ITUWidget *widget, char *param)
void SettingDisplayReset (void)
Variables
static ITULayer * mainVoiceMemoLayer
static ITUSprite * settingDisplayBrightnessBar
static ITUText * settingDisplayScreensaverTimeText
static ITUTextBox * settingDisplayTimeKeypadTextBox
static ITURadioBox * settingDisplayScreensaverClockRadioBox
static ITURadioBox * settingDisplayScreensaverBlankRadioBox
static ITURadioBox * settingDisplayScreensaverPhotoRadioBox
static ITURadioBox * settingDisplayLanguageChtRadioBox
static ITURadioBox * settingDisplayLanguageChsRadioBox
static ITURadioBox * settingDisplayLanguageEngRadioBox
static int settingDisplayMaxBrigntness
Macro Definition Documentation
#define CHS "chs"
Definition at line 9 of file layer_setting_display.c.
Referenced by SettingDisplayCancelButtonOnPress(), SettingDisplayOnEnter(), SettingDisplayOnLeave(), and SettingDisplaySaveButtonOnPress().
#define CHT "cht"
Definition at line 10 of file layer_setting_display.c.
Referenced by SettingDisplayCancelButtonOnPress(), SettingDisplayOnEnter(), SettingDisplayOnLeave(), and SettingDisplaySaveButtonOnPress().
#define ENG "eng"
Definition at line 8 of file layer_setting_display.c.
Referenced by SettingDisplaySaveButtonOnPress().
Function Documentation
bool SettingDisplayBrightnessDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 30 of file layer_setting_display.c.
References ITUSpriteTag::frame, ituSpriteGoto(), and ScreenSetBrightness().
bool SettingDisplayBrightnessUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 42 of file layer_setting_display.c.
References ITUSpriteTag::frame, ituSpriteGoto(), ScreenSetBrightness(), and settingDisplayMaxBrigntness.
bool SettingDisplayCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 125 of file layer_setting_display.c.
References Config::brightness, CHS, CHT, ituRadioBoxSetChecked(), ituSpriteGoto(), ituTextSetString, Config::lang, SCREENSAVER_BLANK, SCREENSAVER_CLOCK, SCREENSAVER_PHOTO, Config::screensaver_time, Config::screensaver_type, ScreenSetBrightness(), and theConfig.
bool SettingDisplayOnEnter (ITUWidget * widget, char * param)
Definition at line 159 of file layer_setting_display.c.
References Config::brightness, CHS, CHT, itcTreeGetChildCount, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, Config::lang, SCREENSAVER_BLANK, SCREENSAVER_CLOCK, SCREENSAVER_PHOTO, Config::screensaver_time, Config::screensaver_type, settingDisplayMaxBrigntness, theConfig, and theScene.
bool SettingDisplayOnLeave (ITUWidget * widget, char * param)
Definition at line 229 of file layer_setting_display.c.
References Config::brightness, CHS, CHT, ituRadioBoxSetChecked(), ituSpriteGoto(), ituTextSetString, Config::lang, SCREENSAVER_BLANK, SCREENSAVER_CLOCK, SCREENSAVER_PHOTO, Config::screensaver_time, Config::screensaver_type, ScreenSetBrightness(), and theConfig.
void SettingDisplayReset (void)
Definition at line 263 of file layer_setting_display.c.
Referenced by resetScene().
bool SettingDisplaySaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 70 of file layer_setting_display.c.
References Config::brightness, CHS, CHT, ConfigSave(), ENG, ITUSpriteTag::frame, Config::itufile, ituLayerGoto(), ituRadioBoxIsChecked(), ituTextGetString, Config::lang, SceneLoad(), SceneUpdateIndicators(), SCREENSAVER_BLANK, SCREENSAVER_CLOCK, SCREENSAVER_NONE, SCREENSAVER_PHOTO, Config::screensaver_time, Config::screensaver_type, and theConfig.
bool SettingDisplayScreensaverTimeButtonOnPress (ITUWidget * widget, char * param)
Definition at line 54 of file layer_setting_display.c.
References ituTextBoxSetString(), and ituTextGetString.
bool SettingDisplayTimeKeypadConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 60 of file layer_setting_display.c.
References ituTextGetString, and ituTextSetString.
Variable Documentation
ITULayer* mainVoiceMemoLayer static
Definition at line 12 of file layer_setting_display.c.
ITUSprite* settingDisplayBrightnessBar static
Definition at line 14 of file layer_setting_display.c.
ITURadioBox* settingDisplayLanguageChsRadioBox static
Definition at line 24 of file layer_setting_display.c.
ITURadioBox* settingDisplayLanguageChtRadioBox static
Definition at line 23 of file layer_setting_display.c.
ITURadioBox* settingDisplayLanguageEngRadioBox static
Definition at line 25 of file layer_setting_display.c.
int settingDisplayMaxBrigntness static
Definition at line 28 of file layer_setting_display.c.
Referenced by SettingDisplayBrightnessUpButtonOnPress(), and SettingDisplayOnEnter().
ITURadioBox* settingDisplayScreensaverBlankRadioBox static
Definition at line 20 of file layer_setting_display.c.
ITURadioBox* settingDisplayScreensaverClockRadioBox static
Definition at line 19 of file layer_setting_display.c.
ITURadioBox* settingDisplayScreensaverPhotoRadioBox static
Definition at line 21 of file layer_setting_display.c.
ITUText* settingDisplayScreensaverTimeText static
Definition at line 16 of file layer_setting_display.c.
ITUTextBox* settingDisplayTimeKeypadTextBox static
Definition at line 17 of file layer_setting_display.c.