ITE SoC SDK: layer_phone_contacts_modify.c File Reference
layer_phone_contacts_modify.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ite/ith.h"
#include "scene.h"
#include "doorbell.h"
Functions
static void PhoneContactsModifyGotoLastLayer (int arg)
bool PhoneContactsModifyConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsModifyCancelButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsModifyRoomButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsModifyCommentButtonOnPress (ITUWidget *widget, char *param)
void PhoneContactsModifyShow (DeviceInfo *info, char *comment, bool blacklist, char *refkey, ITULayer *lastLayer)
Sets the infomation to show on the modify contact dialog.
bool PhoneContactsModifyOnEnter (ITUWidget *widget, char *param)
void PhoneContactsModifyReset (void)
Variables
static ITULayer * phoneContactsLayer
static ITUBackground * phoneContactsBackground
static ITULayer * phoneContactsModifyLayer
static ITULayer * phoneContactsKeypadLayer
static ITULayer * phoneContactsKeyboardLayer
static ITUTextBox * phoneContactsModifyRoomTextBox
static ITUTextBox * phoneContactsModifyCommentTextBox
static ITUCheckBox * phoneContactsModifyBlacklistCheckBox
static ITULayer * phoneContactsModifyLastLayer
static DeviceInfo phoneContactsModifyDeviceInfo
static char * phoneContactsModifyRefkey
Function Documentation
bool PhoneContactsModifyCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 52 of file layer_phone_contacts_modify.c.
References ituLayerGoto().
bool PhoneContactsModifyCommentButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_phone_contacts_modify.c.
References ituTextGetString, and PhoneContactsKeyboardShow().
bool PhoneContactsModifyConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 28 of file layer_phone_contacts_modify.c.
References AddressBookGetDeviceIP(), DeviceInfo::area, DeviceInfo::building, DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, DeviceInfo::ip, ituCheckBoxIsChecked(), ituSceneExecuteCommand(), ituTextBoxGetString(), LinphoneAddFriend(), LinphoneDeleteFriend(), PhoneContactsModifyGotoLastLayer(), phoneContactsModifyRefkey, DeviceInfo::room, theScene, DeviceInfo::type, and DeviceInfo::unit.
static void PhoneContactsModifyGotoLastLayer (int arg) static
Definition at line 22 of file layer_phone_contacts_modify.c.
References ituLayerGoto().
Referenced by PhoneContactsModifyConfirmButtonOnPress().
bool PhoneContactsModifyOnEnter (ITUWidget * widget, char * param)
Definition at line 111 of file layer_phone_contacts_modify.c.
References ituSceneFindWidget(), ituWidgetDisable, ituWidgetSetVisible, and theScene.
void PhoneContactsModifyReset (void)
Definition at line 154 of file layer_phone_contacts_modify.c.
Referenced by resetScene().
bool PhoneContactsModifyRoomButtonOnPress (ITUWidget * widget, char * param)
Definition at line 59 of file layer_phone_contacts_modify.c.
References PhoneContactsKeypadShow().
Variable Documentation
ITUBackground* phoneContactsBackground static
Definition at line 10 of file layer_phone_contacts_modify.c.
ITULayer* phoneContactsKeyboardLayer static
Definition at line 13 of file layer_phone_contacts_modify.c.
ITULayer* phoneContactsKeypadLayer static
Definition at line 12 of file layer_phone_contacts_modify.c.
ITULayer* phoneContactsLayer static
Definition at line 9 of file layer_phone_contacts_modify.c.
ITUCheckBox* phoneContactsModifyBlacklistCheckBox static
Definition at line 16 of file layer_phone_contacts_modify.c.
ITUTextBox* phoneContactsModifyCommentTextBox static
Definition at line 15 of file layer_phone_contacts_modify.c.
DeviceInfo phoneContactsModifyDeviceInfo static
Definition at line 19 of file layer_phone_contacts_modify.c.
ITULayer* phoneContactsModifyLastLayer static
Definition at line 18 of file layer_phone_contacts_modify.c.
ITULayer* phoneContactsModifyLayer static
Definition at line 11 of file layer_phone_contacts_modify.c.
char* phoneContactsModifyRefkey static
Definition at line 20 of file layer_phone_contacts_modify.c.
Referenced by PhoneContactsModifyConfirmButtonOnPress(), and PhoneContactsModifyShow().
ITUTextBox* phoneContactsModifyRoomTextBox static
Definition at line 14 of file layer_phone_contacts_modify.c.