ITE SoC SDK: layer_main_weather.c File Reference
layer_main_weather.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
static void MainWeatherGetWeather (char *xml, int size)
bool MainWeatherOnTimer (ITUWidget *widget, char *param)
bool MainWeatherOnEnter (ITUWidget *widget, char *param)
bool MainWeatherOnLeave (ITUWidget *widget, char *param)
void MainWeatherReset (void)
Variables
static ITUText * mainWeatherDay1DateText
static ITUSprite * mainWeatherDay1SymbolSprite
static ITUText * mainWeatherDay1TemperatureMinText
static ITUText * mainWeatherDay1TemperatureMaxText
static ITUText * mainWeatherDay1SymbolText
static ITUText * mainWeatherDay1WindSpeedText
static ITUText * mainWeatherDay2DateText
static ITUSprite * mainWeatherDay2SymbolSprite
static ITUText * mainWeatherDay2TemperatureMinText
static ITUText * mainWeatherDay2TemperatureMaxText
static ITUText * mainWeatherDay2SymbolText
static ITUText * mainWeatherDay2WindSpeedText
static ITUText * mainWeatherDay3DateText
static ITUSprite * mainWeatherDay3SymbolSprite
static ITUText * mainWeatherDay3TemperatureMinText
static ITUText * mainWeatherDay3TemperatureMaxText
static ITUText * mainWeatherDay3SymbolText
static ITUText * mainWeatherDay3WindSpeedText
static ITUText * mainWeatherDay4DateText
static ITUSprite * mainWeatherDay4SymbolSprite
static ITUText * mainWeatherDay4TemperatureMinText
static ITUText * mainWeatherDay4TemperatureMaxText
static ITUText * mainWeatherDay4SymbolText
static ITUText * mainWeatherDay4WindSpeedText
static ITUText * mainWeatherDay5DateText
static ITUSprite * mainWeatherDay5SymbolSprite
static ITUText * mainWeatherDay5TemperatureMinText
static ITUText * mainWeatherDay5TemperatureMaxText
static ITUText * mainWeatherDay5SymbolText
static ITUText * mainWeatherDay5WindSpeedText
static bool mainWeatherFilled
Function Documentation
static void MainWeatherGetWeather (char * xml, int size) static
Definition at line 45 of file layer_main_weather.c.
References WeatherParse().
Referenced by MainWeatherOnEnter().
bool MainWeatherOnEnter (ITUWidget * widget, char * param)
Definition at line 170 of file layer_main_weather.c.
References ituSceneFindWidget(), mainWeatherFilled, MainWeatherGetWeather(), RemoteGetWeather(), and theScene.
bool MainWeatherOnLeave (ITUWidget * widget, char * param)
Definition at line 269 of file layer_main_weather.c.
bool MainWeatherOnTimer (ITUWidget * widget, char * param)
Definition at line 50 of file layer_main_weather.c.
References ituSpriteGoto(), ituTextSetString, mainWeatherFilled, WeatherGetDate(), WeatherGetSymbolIndex(), WeatherGetSymbolName(), WeatherGetTemperatureMax(), WeatherGetTemperatureMin(), WeatherGetWindSpeedName(), and WeatherIsAvailable().
void MainWeatherReset (void)
Definition at line 274 of file layer_main_weather.c.
Referenced by resetScene().
Variable Documentation
ITUText* mainWeatherDay1DateText static
Definition at line 8 of file layer_main_weather.c.
ITUSprite* mainWeatherDay1SymbolSprite static
Definition at line 9 of file layer_main_weather.c.
ITUText* mainWeatherDay1SymbolText static
Definition at line 12 of file layer_main_weather.c.
ITUText* mainWeatherDay1TemperatureMaxText static
Definition at line 11 of file layer_main_weather.c.
ITUText* mainWeatherDay1TemperatureMinText static
Definition at line 10 of file layer_main_weather.c.
ITUText* mainWeatherDay1WindSpeedText static
Definition at line 13 of file layer_main_weather.c.
ITUText* mainWeatherDay2DateText static
Definition at line 15 of file layer_main_weather.c.
ITUSprite* mainWeatherDay2SymbolSprite static
Definition at line 16 of file layer_main_weather.c.
ITUText* mainWeatherDay2SymbolText static
Definition at line 19 of file layer_main_weather.c.
ITUText* mainWeatherDay2TemperatureMaxText static
Definition at line 18 of file layer_main_weather.c.
ITUText* mainWeatherDay2TemperatureMinText static
Definition at line 17 of file layer_main_weather.c.
ITUText* mainWeatherDay2WindSpeedText static
Definition at line 20 of file layer_main_weather.c.
ITUText* mainWeatherDay3DateText static
Definition at line 22 of file layer_main_weather.c.
ITUSprite* mainWeatherDay3SymbolSprite static
Definition at line 23 of file layer_main_weather.c.
ITUText* mainWeatherDay3SymbolText static
Definition at line 26 of file layer_main_weather.c.
ITUText* mainWeatherDay3TemperatureMaxText static
Definition at line 25 of file layer_main_weather.c.
ITUText* mainWeatherDay3TemperatureMinText static
Definition at line 24 of file layer_main_weather.c.
ITUText* mainWeatherDay3WindSpeedText static
Definition at line 27 of file layer_main_weather.c.
ITUText* mainWeatherDay4DateText static
Definition at line 29 of file layer_main_weather.c.
ITUSprite* mainWeatherDay4SymbolSprite static
Definition at line 30 of file layer_main_weather.c.
ITUText* mainWeatherDay4SymbolText static
Definition at line 33 of file layer_main_weather.c.
ITUText* mainWeatherDay4TemperatureMaxText static
Definition at line 32 of file layer_main_weather.c.
ITUText* mainWeatherDay4TemperatureMinText static
Definition at line 31 of file layer_main_weather.c.
ITUText* mainWeatherDay4WindSpeedText static
Definition at line 34 of file layer_main_weather.c.
ITUText* mainWeatherDay5DateText static
Definition at line 36 of file layer_main_weather.c.
ITUSprite* mainWeatherDay5SymbolSprite static
Definition at line 37 of file layer_main_weather.c.
ITUText* mainWeatherDay5SymbolText static
Definition at line 40 of file layer_main_weather.c.
ITUText* mainWeatherDay5TemperatureMaxText static
Definition at line 39 of file layer_main_weather.c.
ITUText* mainWeatherDay5TemperatureMinText static
Definition at line 38 of file layer_main_weather.c.
ITUText* mainWeatherDay5WindSpeedText static
Definition at line 41 of file layer_main_weather.c.
bool mainWeatherFilled static
Definition at line 43 of file layer_main_weather.c.
Referenced by MainWeatherOnEnter(), and MainWeatherOnTimer().