ITE SoC SDK: layer_setting_phone_voice.c File Reference
layer_setting_phone_voice.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool SettingPhoneVoiceVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceMicVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceMicVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneVoiceOnEnter (ITUWidget *widget, char *param)
void SettingPhoneVoiceOnLeave (ITUWidget *widget, char *param)
void SettingPhoneVoiceReset (void)
Variables
static ITUSprite * settingPhoneVoiceVolBar
static ITUSprite * settingPhoneVoiceMicVolBar
static int settingPhoneMaxVoiceVol
static int settingPhoneLastVoiceLevel
static int settingPhoneMaxVoiceMicVol
static int settingPhoneLastMicLevel
Function Documentation
bool SettingPhoneVoiceCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 95 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneSetMicLevel(), LinphoneSetVoiceLevel(), settingPhoneLastMicLevel, settingPhoneLastVoiceLevel, settingPhoneMaxVoiceMicVol, and settingPhoneMaxVoiceVol.
bool SettingPhoneVoiceMicVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 51 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneGetMicLevel(), LinphoneSetMicLevel(), and settingPhoneMaxVoiceMicVol.
bool SettingPhoneVoiceMicVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 68 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneGetMicLevel(), LinphoneSetMicLevel(), and settingPhoneMaxVoiceMicVol.
bool SettingPhoneVoiceOnEnter (ITUWidget * widget, char * param)
Definition at line 109 of file layer_setting_phone_voice.c.
References itcTreeGetChildCount, ituSceneFindWidget(), ituSpriteGoto(), LinphoneGetMicLevel(), LinphoneGetVoiceLevel(), settingPhoneLastMicLevel, settingPhoneLastVoiceLevel, settingPhoneMaxVoiceMicVol, settingPhoneMaxVoiceVol, and theScene.
void SettingPhoneVoiceOnLeave (ITUWidget * widget, char * param)
Definition at line 135 of file layer_setting_phone_voice.c.
References LinphoneGetMicLevel(), LinphoneGetVoiceLevel(), LinphoneSetMicLevel(), LinphoneSetVoiceLevel(), settingPhoneLastMicLevel, and settingPhoneLastVoiceLevel.
void SettingPhoneVoiceReset (void)
Definition at line 145 of file layer_setting_phone_voice.c.
Referenced by resetScene().
bool SettingPhoneVoiceSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 85 of file layer_setting_phone_voice.c.
References ConfigSave(), LinphoneGetMicLevel(), LinphoneGetVoiceLevel(), settingPhoneLastMicLevel, and settingPhoneLastVoiceLevel.
bool SettingPhoneVoiceVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 17 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneGetVoiceLevel(), LinphoneSetVoiceLevel(), and settingPhoneMaxVoiceVol.
bool SettingPhoneVoiceVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 34 of file layer_setting_phone_voice.c.
References ituSpriteGoto(), LinphoneGetVoiceLevel(), LinphoneSetVoiceLevel(), and settingPhoneMaxVoiceVol.
Variable Documentation
int settingPhoneLastMicLevel static
Definition at line 15 of file layer_setting_phone_voice.c.
Referenced by SettingPhoneVoiceCancelButtonOnPress(), SettingPhoneVoiceOnEnter(), SettingPhoneVoiceOnLeave(), and SettingPhoneVoiceSaveButtonOnPress().
int settingPhoneLastVoiceLevel static
Definition at line 13 of file layer_setting_phone_voice.c.
Referenced by SettingPhoneVoiceCancelButtonOnPress(), SettingPhoneVoiceOnEnter(), SettingPhoneVoiceOnLeave(), and SettingPhoneVoiceSaveButtonOnPress().
int settingPhoneMaxVoiceMicVol static
Definition at line 14 of file layer_setting_phone_voice.c.
Referenced by SettingPhoneVoiceCancelButtonOnPress(), SettingPhoneVoiceMicVolDownButtonOnPress(), SettingPhoneVoiceMicVolUpButtonOnPress(), and SettingPhoneVoiceOnEnter().
int settingPhoneMaxVoiceVol static
Definition at line 12 of file layer_setting_phone_voice.c.
Referenced by SettingPhoneVoiceCancelButtonOnPress(), SettingPhoneVoiceOnEnter(), SettingPhoneVoiceVolDownButtonOnPress(), and SettingPhoneVoiceVolUpButtonOnPress().
ITUSprite* settingPhoneVoiceMicVolBar static
Definition at line 9 of file layer_setting_phone_voice.c.
ITUSprite* settingPhoneVoiceVolBar static
Definition at line 8 of file layer_setting_phone_voice.c.