ITE SoC SDK: layer_message_video_view.c File Reference
layer_message_video_view.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
Functions
bool MessagePhotoViewOnTimer (ITUWidget *widget, char *param)
void MessagePhotoViewShow (char *topic, char *time, int id)
Sets the infomation to the playing video message screen.
bool MessagePhotoViewOnEnter (ITUWidget *widget, char *param)
bool MessagePhotoViewOnLeave (ITUWidget *widget, char *param)
void MessagePhotoViewReset (void)
Variables
static ITULayer * messagePhotoLayer
static ITUText * messagePhotoViewTopicText
static ITUText * messagePhotoViewTimeText
static ITUBackground * messagePhotoViewBackground
static int messagePhotoViewID
static bool messagePhotoViewPlaying
Function Documentation
bool MessagePhotoViewOnEnter (ITUWidget * widget, char * param)
Definition at line 49 of file layer_message_video_view.c.
References DEVICE_INDOOR2, DeviceInfo::ip, ituSceneFindWidget(), LinphonePlayVideoMessage(), LinphoneSetWindowID(), messagePhotoViewID, messagePhotoViewPlaying, SceneCameraSetViewing(), theCenterInfo, theDeviceInfo, theScene, DeviceInfo::type, and VideoMemoStartPlay().
bool MessagePhotoViewOnLeave (ITUWidget * widget, char * param)
Definition at line 71 of file layer_message_video_view.c.
References DEVICE_INDOOR2, LinphoneTerminate(), messagePhotoViewPlaying, SceneCameraSetViewing(), SceneHangUp(), theDeviceInfo, DeviceInfo::type, and VideoMemoStopPlay().
bool MessagePhotoViewOnTimer (ITUWidget * widget, char * param)
Definition at line 15 of file layer_message_video_view.c.
References DEVICE_INDOOR2, ituLayerGoto(), ituSceneFindWidget(), messagePhotoViewPlaying, theDeviceInfo, theScene, DeviceInfo::type, and VideoMemoIsPlayFinished().
void MessagePhotoViewReset (void)
Definition at line 87 of file layer_message_video_view.c.
Referenced by resetScene().
Variable Documentation
ITULayer* messagePhotoLayer static
Definition at line 8 of file layer_message_video_view.c.
ITUBackground* messagePhotoViewBackground static
Definition at line 11 of file layer_message_video_view.c.
int messagePhotoViewID static
Definition at line 12 of file layer_message_video_view.c.
Referenced by MessagePhotoViewOnEnter(), and MessagePhotoViewShow().
bool messagePhotoViewPlaying static
Definition at line 13 of file layer_message_video_view.c.
Referenced by MessagePhotoViewOnEnter(), MessagePhotoViewOnLeave(), and MessagePhotoViewOnTimer().
ITUText* messagePhotoViewTimeText static
Definition at line 10 of file layer_message_video_view.c.
ITUText* messagePhotoViewTopicText static
Definition at line 9 of file layer_message_video_view.c.