ITE SoC SDK: layer_main_voicememo.c File Reference
layer_main_voicememo.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SDL/SDL.h"
#include "scene.h"
#include "doorbell.h"
Functions
bool MainVoiceMemoNumberListBoxOnLoad (ITUWidget *widget, char *param)
bool MainVoiceMemoTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool MainVoiceMemoLengthListBoxOnLoad (ITUWidget *widget, char *param)
static void MainVoiceMemoReload (int arg)
bool MainVoiceMemoDeleteButtonOnPress (ITUWidget *widget, char *param)
static void MainVoiceMemoResetPlayButton (int arg)
bool MainVoiceMemoDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoViewButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoStopPlayButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoRecordButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool MainVoiceMemoOnTimer (ITUWidget *widget, char *param)
bool MainVoiceMemoOnEnter (ITUWidget *widget, char *param)
bool MainVoiceMemoOnLeave (ITUWidget *widget, char *param)
void MainVoiceMemoReset (void)
Variables
static ITUListBox * mainVoiceMemoNumberListBox
static ITUListBox * mainVoiceMemoTimeListBox
static ITUListBox * mainVoiceMemoLengthListBox
static ITUButton * mainVoiceMemoViewButton
static ITUButton * mainVoiceMemoStopPlayButton
static ITUButton * mainVoiceMemoDeleteButton
static ITUButton * mainVoiceMemoRecordButton
static ITUButton * mainVoiceMemoStopRecordButton
static int mainVoiceMemoPlayingIndex
static bool mainVoiceMemoPlaying
static bool mainVoiceMemoRecording
static float mainVoiceMemoPlayingCountDown
static uint32_t mainVoiceMemoPlayingLastTick
Function Documentation
bool MainVoiceMemoDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 205 of file layer_main_voicememo.c.
References ITUListBoxTag::focusIndex.
bool MainVoiceMemoDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 227 of file layer_main_voicememo.c.
References ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, MainMenuNotifyUnplayVoiceMemo(), mainVoiceMemoPlaying, mainVoiceMemoPlayingIndex, MainVoiceMemoReload(), SceneContinuePlayGuardAlarm(), theScene, VoiceMemoDeleteEntry(), VoiceMemoGetUnplayCount(), and VoiceMemoStopPlay().
bool MainVoiceMemoLengthListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 139 of file layer_main_voicememo.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VoiceMemoEntry::played, VoiceMemoEntry::sec, ITCTreeTag::sibling, VoiceMemoGetCount(), and VoiceMemoGetEntry().
bool MainVoiceMemoNumberListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 22 of file layer_main_voicememo.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, VoiceMemoEntry::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VoiceMemoEntry::played, ITCTreeTag::sibling, VoiceMemoGetCount(), and VoiceMemoGetEntry().
bool MainVoiceMemoOnEnter (ITUWidget * widget, char * param)
Definition at line 360 of file layer_main_voicememo.c.
References ituSceneFindWidget(), ituWidgetSetVisible, MainMenuNotifyUnplayVoiceMemo(), mainVoiceMemoPlaying, mainVoiceMemoPlayingCountDown, mainVoiceMemoPlayingIndex, mainVoiceMemoRecording, SceneSetReady(), theScene, and VoiceMemoGetUnplayCount().
bool MainVoiceMemoOnLeave (ITUWidget * widget, char * param)
Definition at line 403 of file layer_main_voicememo.c.
References DEVICE_INDOOR2, LinphoneDisableBusy(), LinphoneIsInDoNotDisturb(), mainVoiceMemoPlaying, mainVoiceMemoRecording, SceneContinuePlayGuardAlarm(), theDeviceInfo, DeviceInfo::type, VoiceMemoStopPlay(), and VoiceMemoStopRecord().
bool MainVoiceMemoOnTimer (ITUWidget * widget, char * param)
Definition at line 319 of file layer_main_voicememo.c.
References DEVICE_INDOOR2, font::f, ituSceneExecuteCommand(), ituWidgetSetVisible, LinphoneDisableBusy(), LinphoneIsInDoNotDisturb(), mainVoiceMemoPlaying, mainVoiceMemoPlayingCountDown, mainVoiceMemoPlayingLastTick, mainVoiceMemoRecording, MainVoiceMemoReload(), MainVoiceMemoResetPlayButton(), SceneContinuePlayGuardAlarm(), ScreenSaverRefresh(), theDeviceInfo, theScene, DeviceInfo::type, VoiceMemoCheckDiskSpace(), and VoiceMemoStopRecord().
bool MainVoiceMemoRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 293 of file layer_main_voicememo.c.
References DEVICE_INDOOR2, LinphoneEnableBusy(), LinphoneIsInDoNotDisturb(), mainVoiceMemoRecording, SceneCameraSetViewing(), theDeviceInfo, DeviceInfo::type, and VoiceMemoStartRecord().
static void MainVoiceMemoReload (int arg) static
Definition at line 197 of file layer_main_voicememo.c.
References ituListBoxReload(), MainMenuNotifyUnplayVoiceMemo(), and VoiceMemoGetUnplayCount().
Referenced by MainVoiceMemoDeleteConfirmButtonOnPress(), MainVoiceMemoOnTimer(), and MainVoiceMemoStopRecordButtonOnPress().
void MainVoiceMemoReset (void)
Definition at line 416 of file layer_main_voicememo.c.
Referenced by resetScene().
static void MainVoiceMemoResetPlayButton (int arg) static
Definition at line 213 of file layer_main_voicememo.c.
References ituWidgetSetVisible, MainMenuNotifyUnplayVoiceMemo(), mainVoiceMemoPlaying, mainVoiceMemoPlayingIndex, SceneCameraSetViewing(), SceneContinuePlayGuardAlarm(), VoiceMemoGetUnplayCount(), and VoiceMemoStopPlay().
Referenced by MainVoiceMemoOnTimer(), and MainVoiceMemoViewButtonOnPress().
bool MainVoiceMemoStopPlayButtonOnPress (ITUWidget * widget, char * param)
Definition at line 282 of file layer_main_voicememo.c.
References ituWidgetSetVisible, mainVoiceMemoPlaying, mainVoiceMemoPlayingIndex, SceneCameraSetViewing(), SceneContinuePlayGuardAlarm(), and VoiceMemoStopPlay().
bool MainVoiceMemoStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 306 of file layer_main_voicememo.c.
References DEVICE_INDOOR2, ituSceneExecuteCommand(), LinphoneDisableBusy(), LinphoneIsInDoNotDisturb(), mainVoiceMemoRecording, MainVoiceMemoReload(), SceneCameraSetViewing(), SceneContinuePlayGuardAlarm(), theDeviceInfo, theScene, DeviceInfo::type, and VoiceMemoStopRecord().
bool MainVoiceMemoTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 78 of file layer_main_voicememo.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VoiceMemoEntry::played, ITCTreeTag::sibling, VoiceMemoEntry::time, VoiceMemoGetCount(), and VoiceMemoGetEntry().
bool MainVoiceMemoViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 248 of file layer_main_voicememo.c.
References ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, ituWidgetSetColor, ituWidgetSetVisible, mainVoiceMemoPlaying, mainVoiceMemoPlayingCountDown, mainVoiceMemoPlayingIndex, mainVoiceMemoPlayingLastTick, MainVoiceMemoResetPlayButton(), SceneCameraSetViewing(), VoiceMemoEntry::sec, theScene, VoiceMemoGetEntry(), and VoiceMemoStartPlay().
Variable Documentation
ITUButton* mainVoiceMemoDeleteButton static
Definition at line 14 of file layer_main_voicememo.c.
ITUListBox* mainVoiceMemoLengthListBox static
Definition at line 11 of file layer_main_voicememo.c.
ITUListBox* mainVoiceMemoNumberListBox static
Definition at line 9 of file layer_main_voicememo.c.
bool mainVoiceMemoPlaying static
Definition at line 18 of file layer_main_voicememo.c.
Referenced by MainVoiceMemoDeleteConfirmButtonOnPress(), MainVoiceMemoOnEnter(), MainVoiceMemoOnLeave(), MainVoiceMemoOnTimer(), MainVoiceMemoResetPlayButton(), MainVoiceMemoStopPlayButtonOnPress(), and MainVoiceMemoViewButtonOnPress().
float mainVoiceMemoPlayingCountDown static
Definition at line 19 of file layer_main_voicememo.c.
Referenced by MainVoiceMemoOnEnter(), MainVoiceMemoOnTimer(), and MainVoiceMemoViewButtonOnPress().
int mainVoiceMemoPlayingIndex static
Definition at line 17 of file layer_main_voicememo.c.
Referenced by MainVoiceMemoDeleteConfirmButtonOnPress(), MainVoiceMemoOnEnter(), MainVoiceMemoResetPlayButton(), MainVoiceMemoStopPlayButtonOnPress(), and MainVoiceMemoViewButtonOnPress().
uint32_t mainVoiceMemoPlayingLastTick static
Definition at line 20 of file layer_main_voicememo.c.
Referenced by MainVoiceMemoOnTimer(), and MainVoiceMemoViewButtonOnPress().
ITUButton* mainVoiceMemoRecordButton static
Definition at line 15 of file layer_main_voicememo.c.
bool mainVoiceMemoRecording static
Definition at line 18 of file layer_main_voicememo.c.
Referenced by MainVoiceMemoOnEnter(), MainVoiceMemoOnLeave(), MainVoiceMemoOnTimer(), MainVoiceMemoRecordButtonOnPress(), and MainVoiceMemoStopRecordButtonOnPress().
ITUButton* mainVoiceMemoStopPlayButton static
Definition at line 13 of file layer_main_voicememo.c.
ITUButton* mainVoiceMemoStopRecordButton static
Definition at line 16 of file layer_main_voicememo.c.
ITUListBox* mainVoiceMemoTimeListBox static
Definition at line 10 of file layer_main_voicememo.c.
ITUButton* mainVoiceMemoViewButton static
Definition at line 12 of file layer_main_voicememo.c.