ITE SoC SDK: layer_setting_system.c File Reference
layer_setting_system.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool SettingSystemItemListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingSystemMessageListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingSystemOnEnter (ITUWidget *widget, char *param)
void SettingSystemReset (void)
Variables
static ITUListBox * settingSystemItemListbox
static ITUListBox * settingSystemMessageListbox
static int settingSystemInfoCount
static const char ** settingSystemInfoArray
Function Documentation
bool SettingSystemItemListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_setting_system.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, settingSystemInfoArray, settingSystemInfoCount, ITCTreeTag::sibling, and StringGetSystemInfoArray().
bool SettingSystemMessageListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 64 of file layer_setting_system.c.
References AddressBookGetVersion(), ServerInfo::addressBookVersion, DeviceInfo::area, DeviceInfo::building, ITCTreeTag::child, DeviceInfoIsInEngineerMode(), DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, Config::gw, i, DeviceInfo::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, settingSystemInfoArray, settingSystemInfoCount, ITCTreeTag::sibling, StringGetDeviceType(), StringGetRoomAddress(), StringGetSystemInfoArray(), StringGetWorkMode(), theConfig, theDeviceInfo, theEntranceInfo, theOutdoorInfo, theOutdoorServerInfo, DeviceInfo::type, and DeviceInfo::unit.
bool SettingSystemOnEnter (ITUWidget * widget, char * param)
Definition at line 170 of file layer_setting_system.c.
References ituSceneFindWidget(), and theScene.
void SettingSystemReset (void)
Definition at line 183 of file layer_setting_system.c.
References settingSystemInfoCount.
Referenced by resetScene().
Variable Documentation
const char** settingSystemInfoArray static
Definition at line 12 of file layer_setting_system.c.
Referenced by SettingSystemItemListBoxOnLoad(), and SettingSystemMessageListBoxOnLoad().
int settingSystemInfoCount static
Definition at line 11 of file layer_setting_system.c.
Referenced by SettingSystemItemListBoxOnLoad(), SettingSystemMessageListBoxOnLoad(), and SettingSystemReset().
ITUListBox* settingSystemItemListbox static
Definition at line 8 of file layer_setting_system.c.
ITUListBox* settingSystemMessageListbox static
Definition at line 9 of file layer_setting_system.c.