ITE SoC SDK: layer_camera.c File Reference
layer_camera.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SDL/SDL.h"
#include "scene.h"
#include "doorbell.h"
Macros
#define CAMERA_TIMEOUT (30.999f)
Functions
bool CameraListBoxOnLoad (ITUWidget *widget, char *param)
static void CameraWatch (int arg)
bool CameraListOnSelection (ITUWidget *widget, char *param)
bool CameraButtonOnPress (ITUWidget *widget, char *param)
bool CameraOnTimer (ITUWidget *widget, char *param)
bool CameraOnEnter (ITUWidget *widget, char *param)
bool CameraOnLeave (ITUWidget *widget, char *param)
void CameraReset (void)
Variables
static ITUListBox * cameraListBox
static ITUBackground * cameraBackground
static ITUBackground * cameraCountDownBackground
static ITUText * cameraCountDownText
static ITUBackground * cameraViewBackground
static ITUButton * cameraViewRecordButton
static ITUButton * cameraViewStopRecordButton
static int cameraInfoCount
static DeviceInfo cameraInfoArray [MAX_CAMERA_COUNT]
static float cameraCountDown
static uint32_t cameraLastTick
static bool cameraVideoRecordEnable
static bool cameraViewTimeout = false
float CameraLockRecordButtonCountDown = 0
uint32_t CameraLockRecordButtonLastTick = 0
bool CameraLockRecordButton = false
Macro Definition Documentation
#define CAMERA_TIMEOUT (30.999f)
Definition at line 9 of file layer_camera.c.
Referenced by CameraWatch().
Function Documentation
bool CameraButtonOnPress (ITUWidget * widget, char * param)
Definition at line 140 of file layer_camera.c.
References CameraViewShow(), ITUListBoxTag::focusIndex, DeviceInfo::ip, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, LinphoneSetWindowID(), and ITUScrollText::text.
bool CameraListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 30 of file layer_camera.c.
References AddressBookGetCameraInfoArray(), DeviceInfo::alias, DeviceInfo::area, DeviceInfo::building, ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, MAX_CAMERA_COUNT, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, StringGetCameraPosition(), theDeviceInfo, and DeviceInfo::unit.
bool CameraListOnSelection (ITUWidget * widget, char * param)
Definition at line 109 of file layer_camera.c.
References cameraVideoRecordEnable, CameraWatch(), CaptureStopRecord(), ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, ituWidgetSetVisible, LinphoneStopCamera(), SceneCameraIsViewing(), and theScene.
bool CameraOnEnter (ITUWidget * widget, char * param)
Definition at line 219 of file layer_camera.c.
References cameraCountDown, cameraVideoRecordEnable, cameraViewTimeout, CaptureGetPath(), DEVICE_INDOOR2, ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, LinphoneSetWindowID(), SceneCameraSetViewing(), theDeviceInfo, theScene, and DeviceInfo::type.
bool CameraOnLeave (ITUWidget * widget, char * param)
Definition at line 278 of file layer_camera.c.
References cameraVideoRecordEnable, CaptureStopRecord(), LinphoneStopCamera(), SceneCameraSetViewing(), and SceneContinuePlayGuardAlarm().
bool CameraOnTimer (ITUWidget * widget, char * param)
Definition at line 153 of file layer_camera.c.
References cameraCountDown, cameraLastTick, CameraLockRecordButton, CameraLockRecordButtonCountDown, CameraLockRecordButtonLastTick, cameraVideoRecordEnable, cameraViewTimeout, CaptureStopRecord(), EVENT_CUSTOM_CAMERA_TIMEOUT, font::f, ituSceneSendEvent(), ituTextSetString, ituWidgetSetVisible, LinphoneStopCamera(), SceneCameraIsViewing(), SceneCameraSetViewing(), SceneContinuePlayGuardAlarm(), and theScene.
void CameraReset (void)
Definition at line 292 of file layer_camera.c.
Referenced by resetScene().
static void CameraWatch (int arg) static
Definition at line 86 of file layer_camera.c.
References CAMERA_TIMEOUT, cameraCountDown, cameraLastTick, ITUListBoxTag::focusIndex, DeviceInfo::ip, itcTreeGetChildAt, ituTextSetString, ituWidgetGetCustomData, ituWidgetSetVisible, LinphoneWatchCamera(), SceneCameraSetViewing(), and SceneSetRemoteIP().
Referenced by CameraListOnSelection().
Variable Documentation
ITUBackground* cameraBackground static
Definition at line 12 of file layer_camera.c.
float cameraCountDown static
Definition at line 21 of file layer_camera.c.
Referenced by CameraOnEnter(), CameraOnTimer(), and CameraWatch().
ITUBackground* cameraCountDownBackground static
Definition at line 13 of file layer_camera.c.
ITUText* cameraCountDownText static
Definition at line 14 of file layer_camera.c.
DeviceInfo cameraInfoArray[MAX_CAMERA_COUNT] static
Definition at line 20 of file layer_camera.c.
int cameraInfoCount static
Definition at line 19 of file layer_camera.c.
uint32_t cameraLastTick static
Definition at line 22 of file layer_camera.c.
Referenced by CameraOnTimer(), and CameraWatch().
ITUListBox* cameraListBox static
Definition at line 11 of file layer_camera.c.
bool CameraLockRecordButton = false
Definition at line 28 of file layer_camera.c.
Referenced by CameraOnTimer(), CameraViewRecordButtonOnPress(), and CameraViewStopRecordButtonOnPress().
float CameraLockRecordButtonCountDown = 0
Definition at line 26 of file layer_camera.c.
Referenced by CameraOnTimer(), and CameraViewRecordButtonOnPress().
uint32_t CameraLockRecordButtonLastTick = 0
Definition at line 27 of file layer_camera.c.
Referenced by CameraOnTimer(), and CameraViewRecordButtonOnPress().
bool cameraVideoRecordEnable static
Definition at line 23 of file layer_camera.c.
Referenced by CameraListOnSelection(), CameraOnEnter(), CameraOnLeave(), and CameraOnTimer().
ITUBackground* cameraViewBackground static
Definition at line 15 of file layer_camera.c.
ITUButton* cameraViewRecordButton static
Definition at line 16 of file layer_camera.c.
ITUButton* cameraViewStopRecordButton static
Definition at line 17 of file layer_camera.c.
bool cameraViewTimeout = false static
Definition at line 24 of file layer_camera.c.
Referenced by CameraOnEnter(), and CameraOnTimer().