ITE SoC SDK: layer_phone_contacts_add.c File Reference
layer_phone_contacts_add.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ite/ith.h"
#include "scene.h"
Functions
static void PhoneContactsGotoLastLayer (int arg)
bool PhoneContactsAddConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsAddCancelButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsAddRoomButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsAddCommentButtonOnPress (ITUWidget *widget, char *param)
void PhoneContactsAddShow (DeviceInfo *info, char *comment, ITULayer *lastLayer)
Sets the infomation to show on the add contact dialog.
bool PhoneContactsAddOnEnter (ITUWidget *widget, char *param)
void PhoneContactsAddReset (void)
Variables
static ITULayer * phoneContactsLayer
static ITULayer * phoneLogLayer
static ITULayer * phoneLogMissedLayer
static ITULayer * phoneLogReceivedLayer
static ITULayer * phoneLogSentLayer
static ITUBackground * phoneContactsBackground
static ITUBackground * phoneLogMissedBackground
static ITUBackground * phoneLogReceivedBackground
static ITUBackground * phoneLogSentBackground
static ITULayer * phoneContactsAddLayer
static ITUTextBox * phoneContactsAddRoomTextBox
static ITUTextBox * phoneContactsAddCommentTextBox
static ITUCheckBox * phoneContactsAddBlacklistCheckBox
static ITULayer * phoneContactsAddLastLayer
static DeviceInfo phoneContactsAddDeviceInfo
Function Documentation
bool PhoneContactsAddCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 51 of file layer_phone_contacts_add.c.
References ituLayerGoto().
bool PhoneContactsAddCommentButtonOnPress (ITUWidget * widget, char * param)
Definition at line 64 of file layer_phone_contacts_add.c.
References ituTextGetString, and PhoneContactsKeyboardShow().
bool PhoneContactsAddConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 31 of file layer_phone_contacts_add.c.
References AddressBookGetDeviceIP(), DeviceInfo::area, DeviceInfo::building, DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, DeviceInfo::ip, ituCheckBoxIsChecked(), ituSceneExecuteCommand(), ituTextBoxGetString(), LinphoneAddFriend(), PhoneContactsGotoLastLayer(), DeviceInfo::room, theScene, DeviceInfo::type, and DeviceInfo::unit.
bool PhoneContactsAddOnEnter (ITUWidget * widget, char * param)
Definition at line 114 of file layer_phone_contacts_add.c.
References ituSceneFindWidget(), ituWidgetDisable, ituWidgetSetVisible, and theScene.
void PhoneContactsAddReset (void)
Definition at line 193 of file layer_phone_contacts_add.c.
Referenced by resetScene().
bool PhoneContactsAddRoomButtonOnPress (ITUWidget * widget, char * param)
Definition at line 58 of file layer_phone_contacts_add.c.
References PhoneContactsKeypadShow().
static void PhoneContactsGotoLastLayer (int arg) static
Definition at line 26 of file layer_phone_contacts_add.c.
References ituLayerGoto().
Referenced by PhoneContactsAddConfirmButtonOnPress().
Variable Documentation
ITUCheckBox* phoneContactsAddBlacklistCheckBox static
Definition at line 21 of file layer_phone_contacts_add.c.
ITUTextBox* phoneContactsAddCommentTextBox static
Definition at line 20 of file layer_phone_contacts_add.c.
DeviceInfo phoneContactsAddDeviceInfo static
Definition at line 24 of file layer_phone_contacts_add.c.
ITULayer* phoneContactsAddLastLayer static
Definition at line 23 of file layer_phone_contacts_add.c.
ITULayer* phoneContactsAddLayer static
Definition at line 18 of file layer_phone_contacts_add.c.
ITUTextBox* phoneContactsAddRoomTextBox static
Definition at line 19 of file layer_phone_contacts_add.c.
ITUBackground* phoneContactsBackground static
Definition at line 13 of file layer_phone_contacts_add.c.
ITULayer* phoneContactsLayer static
Definition at line 8 of file layer_phone_contacts_add.c.
ITULayer* phoneLogLayer static
Definition at line 9 of file layer_phone_contacts_add.c.
ITUBackground* phoneLogMissedBackground static
Definition at line 14 of file layer_phone_contacts_add.c.
ITULayer* phoneLogMissedLayer static
Definition at line 10 of file layer_phone_contacts_add.c.
ITUBackground* phoneLogReceivedBackground static
Definition at line 15 of file layer_phone_contacts_add.c.
ITULayer* phoneLogReceivedLayer static
Definition at line 11 of file layer_phone_contacts_add.c.
ITUBackground* phoneLogSentBackground static
Definition at line 16 of file layer_phone_contacts_add.c.
ITULayer* phoneLogSentLayer static
Definition at line 12 of file layer_phone_contacts_add.c.