ITE SoC SDK: layer_setting_engineer_misc_twice.c File Reference
layer_setting_engineer_misc_twice.c File Reference
#include <assert.h>
#include <ctype.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ite/itp.h"
#include "scene.h"
#include "doorbell.h"
Functions
bool SettingEngineerMiscTwiceNumberButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceBackButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceClearButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceConfirmButtonOnPress (ITUWidget *widget, char *param)
static void GetOutdoorInfoCallback (ServerInfo *info)
bool SettingEngineerMiscTwiceSettingButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTwiceOnEnter (ITUWidget *widget, char *param)
void SettingEngineerMiscTwiceReset (void)
Variables
static ITUBackground * settingEngineerMiscTwiceBackground
static ITUTextBox * settingEngineerMiscTwiceAreaTextBox
static ITUTextBox * settingEngineerMiscTwiceBuildingTextBox
static ITUTextBox * settingEngineerMiscTwiceUnitTextBox
static ITUTextBox * settingEngineerMiscTwiceFloorTextBox
static ITUTextBox * settingEngineerMiscTwiceRoomTextBox
static ITUTextBox * settingEngineerMiscTwiceExtTextBox
static ITUBackground * settingEngineerMiscTwiceFailDiag
static ITUText * settingEngineerMiscTwiceFailText
static ITUBackground * settingEngineerMiscTwiceOKDiag
static ITUTextBox * activeSettingEngineerMiscTwiceTextBox
static sem_t settingEngineerMiscTwiceOutdoorInfoSem
static ServerInfo settingEngineerMiscTwiceOutdoorInfo
Function Documentation
static void GetOutdoorInfoCallback (ServerInfo * info) static
Definition at line 105 of file layer_setting_engineer_misc_twice.c.
References settingEngineerMiscTwiceOutdoorInfoSem.
Referenced by SettingEngineerMiscTwiceSettingButtonOnPress().
bool SettingEngineerMiscTwiceBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 51 of file layer_setting_engineer_misc_twice.c.
References ituTextSetString, settingEngineerMiscTwiceAreaTextBox, settingEngineerMiscTwiceBuildingTextBox, settingEngineerMiscTwiceFloorTextBox, settingEngineerMiscTwiceRoomTextBox, and settingEngineerMiscTwiceUnitTextBox.
bool SettingEngineerMiscTwiceClearButtonOnPress (ITUWidget * widget, char * param)
Definition at line 78 of file layer_setting_engineer_misc_twice.c.
References ituTextSetString, and settingEngineerMiscTwiceAreaTextBox.
bool SettingEngineerMiscTwiceConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 90 of file layer_setting_engineer_misc_twice.c.
References settingEngineerMiscTwiceBuildingTextBox, settingEngineerMiscTwiceExtTextBox, settingEngineerMiscTwiceFloorTextBox, settingEngineerMiscTwiceRoomTextBox, and settingEngineerMiscTwiceUnitTextBox.
bool SettingEngineerMiscTwiceNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 26 of file layer_setting_engineer_misc_twice.c.
References ituTextBoxInput(), ituTextGetString, ITUTextBox::maxLen, settingEngineerMiscTwiceBuildingTextBox, settingEngineerMiscTwiceExtTextBox, settingEngineerMiscTwiceFloorTextBox, settingEngineerMiscTwiceRoomTextBox, settingEngineerMiscTwiceUnitTextBox, and ITUButton::text.
bool SettingEngineerMiscTwiceOnEnter (ITUWidget * widget, char * param)
Definition at line 194 of file layer_setting_engineer_misc_twice.c.
References ituSceneFindWidget(), ituTextBoxSetString(), settingEngineerMiscTwiceAreaTextBox, settingEngineerMiscTwiceOutdoorInfoSem, and theScene.
void SettingEngineerMiscTwiceReset (void)
Definition at line 245 of file layer_setting_engineer_misc_twice.c.
References settingEngineerMiscTwiceOutdoorInfoSem.
Referenced by resetScene().
bool SettingEngineerMiscTwiceSettingButtonOnPress (ITUWidget * widget, char * param)
Definition at line 111 of file layer_setting_engineer_misc_twice.c.
References AddressBookGetDeviceIP(), AddressBookGetVersion(), AddressBookIsOutdoorExist(), ServerInfo::addressBookVersion, ConfigSave(), DeviceInfoIsInEngineerMode(), GetOutdoorInfoCallback(), itpSemWaitTimeout(), ituTextGetString, ituTextSetString, ituWidgetDisable, ituWidgetSetVisible, Config::outdoor_ipaddr, RemoteGetOutdoorInfo(), RemoteSetOutdoorSetting(), settingEngineerMiscTwiceOutdoorInfoSem, and theConfig.
Variable Documentation
ITUTextBox* activeSettingEngineerMiscTwiceTextBox static
Definition at line 22 of file layer_setting_engineer_misc_twice.c.
ITUTextBox* settingEngineerMiscTwiceAreaTextBox static
Definition at line 12 of file layer_setting_engineer_misc_twice.c.
Referenced by SettingEngineerMiscTwiceBackButtonOnPress(), SettingEngineerMiscTwiceClearButtonOnPress(), and SettingEngineerMiscTwiceOnEnter().
ITUBackground* settingEngineerMiscTwiceBackground static
Definition at line 11 of file layer_setting_engineer_misc_twice.c.
ITUTextBox* settingEngineerMiscTwiceBuildingTextBox static
Definition at line 13 of file layer_setting_engineer_misc_twice.c.
Referenced by SettingEngineerMiscTwiceBackButtonOnPress(), SettingEngineerMiscTwiceConfirmButtonOnPress(), and SettingEngineerMiscTwiceNumberButtonOnPress().
ITUTextBox* settingEngineerMiscTwiceExtTextBox static
Definition at line 17 of file layer_setting_engineer_misc_twice.c.
Referenced by SettingEngineerMiscTwiceConfirmButtonOnPress(), and SettingEngineerMiscTwiceNumberButtonOnPress().
ITUBackground* settingEngineerMiscTwiceFailDiag static
Definition at line 18 of file layer_setting_engineer_misc_twice.c.
ITUText* settingEngineerMiscTwiceFailText static
Definition at line 19 of file layer_setting_engineer_misc_twice.c.
ITUTextBox* settingEngineerMiscTwiceFloorTextBox static
Definition at line 15 of file layer_setting_engineer_misc_twice.c.
Referenced by SettingEngineerMiscTwiceBackButtonOnPress(), SettingEngineerMiscTwiceConfirmButtonOnPress(), and SettingEngineerMiscTwiceNumberButtonOnPress().
ITUBackground* settingEngineerMiscTwiceOKDiag static
Definition at line 20 of file layer_setting_engineer_misc_twice.c.
ServerInfo settingEngineerMiscTwiceOutdoorInfo static
Definition at line 24 of file layer_setting_engineer_misc_twice.c.
sem_t settingEngineerMiscTwiceOutdoorInfoSem static
Definition at line 23 of file layer_setting_engineer_misc_twice.c.
Referenced by GetOutdoorInfoCallback(), SettingEngineerMiscTwiceOnEnter(), SettingEngineerMiscTwiceReset(), and SettingEngineerMiscTwiceSettingButtonOnPress().
ITUTextBox* settingEngineerMiscTwiceRoomTextBox static
Definition at line 16 of file layer_setting_engineer_misc_twice.c.
Referenced by SettingEngineerMiscTwiceBackButtonOnPress(), SettingEngineerMiscTwiceConfirmButtonOnPress(), and SettingEngineerMiscTwiceNumberButtonOnPress().
ITUTextBox* settingEngineerMiscTwiceUnitTextBox static
Definition at line 14 of file layer_setting_engineer_misc_twice.c.
Referenced by SettingEngineerMiscTwiceBackButtonOnPress(), SettingEngineerMiscTwiceConfirmButtonOnPress(), and SettingEngineerMiscTwiceNumberButtonOnPress().