ITE SoC SDK: layer_message_video.c File Reference
layer_message_video.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
Functions
bool MessagePhotoTopicListBoxOnLoad (ITUWidget *widget, char *param)
bool MessagePhotoTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool MessagePhotoViewButtonOnPress (ITUWidget *widget, char *param)
static void MessagePhotoReload (int arg)
static void MessagePhotoClear (void)
static void MessagePhotoGetList (Message *msgs, int count)
static void MessagePhotoDeleteComplete (void)
bool MessagePhotoDeleteOnPress (ITUWidget *widget, char *param)
bool MessagePhotoDeleteConfirmOnPress (ITUWidget *widget, char *param)
bool MessagePhotoOnEnter (ITUWidget *widget, char *param)
bool MessagePhotoOnLeave (ITUWidget *widget, char *param)
void MessagePhotoReset (void)
Variables
static ITUListBox * messagePhotoTopicListBox
static ITUListBox * messagePhotoTimeListBox
static Message * messageVideos
static int messageVideoCount
Function Documentation
static void MessagePhotoClear (void) static
Definition at line 187 of file layer_message_video.c.
References i, messageVideoCount, Message::time, and Message::topic.
Referenced by MessagePhotoGetList(), and MessagePhotoOnLeave().
static void MessagePhotoDeleteComplete (void) static
Definition at line 216 of file layer_message_video.c.
References MessagePhotoGetList(), and MessageVideoListGet().
Referenced by MessagePhotoDeleteConfirmOnPress().
bool MessagePhotoDeleteConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 229 of file layer_message_video.c.
References DEVICE_INDOOR2, ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, MessagePhotoDeleteComplete(), MessagePhotoReload(), MessageVideoDelete(), theDeviceInfo, theScene, DeviceInfo::type, and VideoMemoDeleteEntry().
bool MessagePhotoDeleteOnPress (ITUWidget * widget, char * param)
Definition at line 221 of file layer_message_video.c.
References ITUListBoxTag::focusIndex.
static void MessagePhotoGetList (Message * msgs, int count) static
Definition at line 207 of file layer_message_video.c.
References ituSceneExecuteCommand(), MessagePhotoClear(), MessagePhotoReload(), messageVideoCount, and theScene.
Referenced by MessagePhotoDeleteComplete(), and MessagePhotoOnEnter().
bool MessagePhotoOnEnter (ITUWidget * widget, char * param)
Definition at line 247 of file layer_message_video.c.
References CaptureGetUnplayCount(), DEVICE_INDOOR2, ituSceneFindWidget(), MessageNotifyUnreadRecordMessage(), MessagePhotoGetList(), MessagePhotoReload(), MessageVideoListGet(), theDeviceInfo, theScene, and DeviceInfo::type.
bool MessagePhotoOnLeave (ITUWidget * widget, char * param)
Definition at line 266 of file layer_message_video.c.
References DEVICE_INDOOR2, MessagePhotoClear(), theDeviceInfo, and DeviceInfo::type.
static void MessagePhotoReload (int arg) static
Definition at line 181 of file layer_message_video.c.
References ituListBoxReload().
Referenced by MessagePhotoDeleteConfirmOnPress(), MessagePhotoGetList(), and MessagePhotoOnEnter().
void MessagePhotoReset (void)
Definition at line 274 of file layer_message_video.c.
Referenced by resetScene().
bool MessagePhotoTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 89 of file layer_message_video.c.
References ITCTreeTag::child, DEVICE_INDOOR2, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, messageVideoCount, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VideoMemoEntry::played, Message::read, ITCTreeTag::sibling, theDeviceInfo, Message::time, VideoMemoEntry::time, DeviceInfo::type, VideoMemoGetCount(), and VideoMemoGetEntry().
bool MessagePhotoTopicListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 13 of file layer_message_video.c.
References ITCTreeTag::child, DEVICE_INDOOR2, ITUListBoxTag::focusIndex, i, Message::id, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, messageVideoCount, VideoMemoEntry::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, VideoMemoEntry::played, Message::read, ITCTreeTag::sibling, theDeviceInfo, Message::topic, DeviceInfo::type, VideoMemoGetCount(), and VideoMemoGetEntry().
bool MessagePhotoViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 168 of file layer_message_video.c.
References ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, MessagePhotoViewShow(), and ITUScrollText::text.
Variable Documentation
ITUListBox* messagePhotoTimeListBox static
Definition at line 9 of file layer_message_video.c.
ITUListBox* messagePhotoTopicListBox static
Definition at line 8 of file layer_message_video.c.
int messageVideoCount static
Definition at line 11 of file layer_message_video.c.
Referenced by MessagePhotoClear(), MessagePhotoGetList(), MessagePhotoTimeListBoxOnLoad(), and MessagePhotoTopicListBoxOnLoad().
Message* messageVideos static
Definition at line 10 of file layer_message_video.c.