ITE SoC SDK: layer_setting_phone_audio.c File Reference
layer_setting_phone_audio.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Macros
#define RING1 "ring1.wav"
#define RING2 "ring2.wav"
#define RING3 "ring3.wav"
#define KEY1 "key1.wav"
#define KEY2 "key2.wav"
#define KEY3 "key3.wav"
Functions
static void SettingPhoneAudioPlayRingSound (int arg)
bool SettingPhoneAudioRingRadioBoxOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioRingVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioRingVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioKeypadSoundRadioBoxOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioKeypadSoundVolDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioKeypadSoundVolUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneAudioOnEnter (ITUWidget *widget, char *param)
void SettingPhoneAudioOnLeave (ITUWidget *widget, char *param)
void SettingPhoneAudioReset (void)
Variables
static ITURadioBox * settingPhoneRing1RadioBox
static ITURadioBox * settingPhoneRing2RadioBox
static ITURadioBox * settingPhoneRing3RadioBox
static ITUSprite * settingPhoneRingVolBar
static ITURadioBox * settingPhoneKeypadSound1RadioBox
static ITURadioBox * settingPhoneKeypadSound2RadioBox
static ITURadioBox * settingPhoneKeypadSound3RadioBox
static ITUSprite * settingPhoneKeypadSoundVolBar
static int settingPhoneMaxRingVol
static int settingPhoneLastRingLevel
static int settingPhoneMaxKeypadSoundVol
static int settingPhoneLastKeypadSoundLevel
static char settingPhoneLastRingSound [PATH_MAX]
static char settingPhoneLastKeySound [PATH_MAX]
Macro Definition Documentation
#define KEY1 "key1.wav"
Definition at line 11 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioKeypadSoundRadioBoxOnPress(), and SettingPhoneAudioOnEnter().
#define KEY2 "key2.wav"
Definition at line 12 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioKeypadSoundRadioBoxOnPress(), and SettingPhoneAudioOnEnter().
#define KEY3 "key3.wav"
Definition at line 13 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioKeypadSoundRadioBoxOnPress(), and SettingPhoneAudioOnEnter().
#define RING1 "ring1.wav"
Definition at line 8 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioRingRadioBoxOnPress().
#define RING2 "ring2.wav"
Definition at line 9 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnEnter(), and SettingPhoneAudioRingRadioBoxOnPress().
#define RING3 "ring3.wav"
Definition at line 10 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnEnter(), and SettingPhoneAudioRingRadioBoxOnPress().
Function Documentation
bool SettingPhoneAudioCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 157 of file layer_setting_phone_audio.c.
References ituRadioBoxSetChecked(), ituSpriteGoto(), KEY1, KEY2, KEY3, Config::keylevel, Config::keysound, LinphoneSetRingLevel(), LinphoneSetRingSound(), RING2, RING3, settingPhoneLastKeypadSoundLevel, settingPhoneLastKeySound, settingPhoneLastRingLevel, settingPhoneLastRingSound, settingPhoneMaxKeypadSoundVol, settingPhoneMaxRingVol, and theConfig.
bool SettingPhoneAudioKeypadSoundRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 92 of file layer_setting_phone_audio.c.
References KEY1, KEY2, KEY3, Config::keysound, and theConfig.
bool SettingPhoneAudioKeypadSoundVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 111 of file layer_setting_phone_audio.c.
References ituSpriteGoto(), Config::keylevel, LinphoneSetKeyLevel(), settingPhoneMaxKeypadSoundVol, and theConfig.
bool SettingPhoneAudioKeypadSoundVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 128 of file layer_setting_phone_audio.c.
References ituSpriteGoto(), Config::keylevel, LinphoneSetKeyLevel(), settingPhoneMaxKeypadSoundVol, and theConfig.
bool SettingPhoneAudioOnEnter (ITUWidget * widget, char * param)
Definition at line 190 of file layer_setting_phone_audio.c.
References itcTreeGetChildCount, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituSpriteGoto(), KEY1, KEY2, KEY3, Config::keylevel, Config::keysound, LinphoneGetRingLevel(), RING2, RING3, Config::ringsound, settingPhoneLastKeypadSoundLevel, settingPhoneLastKeySound, settingPhoneLastRingLevel, settingPhoneLastRingSound, settingPhoneMaxKeypadSoundVol, settingPhoneMaxRingVol, theConfig, and theScene.
void SettingPhoneAudioOnLeave (ITUWidget * widget, char * param)
Definition at line 250 of file layer_setting_phone_audio.c.
References Config::keylevel, Config::keysound, LinphoneGetRingLevel(), LinphoneSetRingLevel(), LinphoneSetRingSound(), Config::ringsound, settingPhoneLastKeypadSoundLevel, settingPhoneLastKeySound, settingPhoneLastRingLevel, settingPhoneLastRingSound, and theConfig.
static void SettingPhoneAudioPlayRingSound (int arg) static
Definition at line 33 of file layer_setting_phone_audio.c.
References LinphonePlayRingSound().
Referenced by SettingPhoneAudioRingRadioBoxOnPress().
void SettingPhoneAudioReset (void)
Definition at line 263 of file layer_setting_phone_audio.c.
Referenced by resetScene().
bool SettingPhoneAudioRingRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 38 of file layer_setting_phone_audio.c.
References ituSceneExecuteCommand(), LinphoneSetRingSound(), RING1, RING2, RING3, SettingPhoneAudioPlayRingSound(), and theScene.
bool SettingPhoneAudioRingVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 58 of file layer_setting_phone_audio.c.
References ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneSetRingLevel(), and settingPhoneMaxRingVol.
bool SettingPhoneAudioRingVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 75 of file layer_setting_phone_audio.c.
References ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneSetRingLevel(), and settingPhoneMaxRingVol.
bool SettingPhoneAudioSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 145 of file layer_setting_phone_audio.c.
References ConfigSave(), Config::keylevel, Config::keysound, LinphoneGetRingLevel(), Config::ringsound, settingPhoneLastKeypadSoundLevel, settingPhoneLastKeySound, settingPhoneLastRingLevel, settingPhoneLastRingSound, and theConfig.
Variable Documentation
ITURadioBox* settingPhoneKeypadSound1RadioBox static
Definition at line 20 of file layer_setting_phone_audio.c.
ITURadioBox* settingPhoneKeypadSound2RadioBox static
Definition at line 21 of file layer_setting_phone_audio.c.
ITURadioBox* settingPhoneKeypadSound3RadioBox static
Definition at line 22 of file layer_setting_phone_audio.c.
ITUSprite* settingPhoneKeypadSoundVolBar static
Definition at line 23 of file layer_setting_phone_audio.c.
int settingPhoneLastKeypadSoundLevel static
Definition at line 29 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnEnter(), SettingPhoneAudioOnLeave(), and SettingPhoneAudioSaveButtonOnPress().
char settingPhoneLastKeySound[PATH_MAX] static
Definition at line 31 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnEnter(), SettingPhoneAudioOnLeave(), and SettingPhoneAudioSaveButtonOnPress().
int settingPhoneLastRingLevel static
Definition at line 27 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnEnter(), SettingPhoneAudioOnLeave(), and SettingPhoneAudioSaveButtonOnPress().
char settingPhoneLastRingSound[PATH_MAX] static
Definition at line 30 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnEnter(), SettingPhoneAudioOnLeave(), and SettingPhoneAudioSaveButtonOnPress().
int settingPhoneMaxKeypadSoundVol static
Definition at line 28 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioKeypadSoundVolDownButtonOnPress(), SettingPhoneAudioKeypadSoundVolUpButtonOnPress(), and SettingPhoneAudioOnEnter().
int settingPhoneMaxRingVol static
Definition at line 26 of file layer_setting_phone_audio.c.
Referenced by SettingPhoneAudioCancelButtonOnPress(), SettingPhoneAudioOnEnter(), SettingPhoneAudioRingVolDownButtonOnPress(), and SettingPhoneAudioRingVolUpButtonOnPress().
ITURadioBox* settingPhoneRing1RadioBox static
Definition at line 15 of file layer_setting_phone_audio.c.
ITURadioBox* settingPhoneRing2RadioBox static
Definition at line 16 of file layer_setting_phone_audio.c.
ITURadioBox* settingPhoneRing3RadioBox static
Definition at line 17 of file layer_setting_phone_audio.c.
ITUSprite* settingPhoneRingVolBar static
Definition at line 18 of file layer_setting_phone_audio.c.