ITE SoC SDK: layer_setting_engineer_network_mac.c File Reference
layer_setting_engineer_network_mac.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
Functions
static void SettingEngineerNetworkMacCloseCallbackDefault (char *ip)
bool SettingEngineerNetworkMacKeypadCloseButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkMacKeypadConfirmButtonOnPress (ITUWidget *widget, char *param)
void SettingEngineerNetworkMacShow (char *mac, SceneSettingEngineerNetworkMacCallback func)
Shows the MAC address setting dialog.
void SettingEngineerNetworkMacReset (void)
Variables
static ITUTextBox * settingEngineerNetworkMacKeypadTextBox
static
SceneSettingEngineerNetworkMacCallback settingEngineerNetworkMacCloseCallback
Function Documentation
static void SettingEngineerNetworkMacCloseCallbackDefault (char * ip) static
Definition at line 10 of file layer_setting_engineer_network_mac.c.
Referenced by SettingEngineerNetworkMacReset(), and SettingEngineerNetworkMacShow().
bool SettingEngineerNetworkMacKeypadCloseButtonOnPress (ITUWidget * widget, char * param)
Definition at line 15 of file layer_setting_engineer_network_mac.c.
References settingEngineerNetworkMacCloseCallback.
bool SettingEngineerNetworkMacKeypadConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 21 of file layer_setting_engineer_network_mac.c.
References ituSceneFindWidget(), ituTextGetString, settingEngineerNetworkMacCloseCallback, and theScene.
void SettingEngineerNetworkMacReset (void)
Definition at line 48 of file layer_setting_engineer_network_mac.c.
References settingEngineerNetworkMacCloseCallback, and SettingEngineerNetworkMacCloseCallbackDefault().
Referenced by resetScene().
Variable Documentation
SceneSettingEngineerNetworkMacCallback settingEngineerNetworkMacCloseCallback static
Definition at line 8 of file layer_setting_engineer_network_mac.c.
Referenced by SettingEngineerNetworkMacKeypadCloseButtonOnPress(), SettingEngineerNetworkMacKeypadConfirmButtonOnPress(), SettingEngineerNetworkMacReset(), and SettingEngineerNetworkMacShow().
ITUTextBox* settingEngineerNetworkMacKeypadTextBox static
Definition at line 7 of file layer_setting_engineer_network_mac.c.