ITE SoC SDK: layer_message_service.c File Reference
layer_message_service.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
Functions
bool MessageServiceTopicListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageServiceTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageServiceViewButtonOnPress (ITUWidget *widget, char *param)
static void MessageServiceReload (int arg)
static void MessageServiceClear (void)
static void MessageServiceGetList (Message *msgs, int count)
static void MessageServiceDeleteComplete (void)
bool MessageServiceDeleteOnPress (ITUWidget *widget, char *param)
bool MessageServiceDeleteConfirmOnPress (ITUWidget *widget, char *param)
bool MessageServiceOnEnter (ITUWidget *widget, char *param)
bool MessageServiceOnLeave (ITUWidget *widget, char *param)
void MessageServiceReset (void)
Variables
static ITULayer * messageServiceViewLayer
static ITUListBox * messageServiceTopicListBox
static ITUListBox * messageServiceTimeListBox
static Message * messageTexts
static int messageTextCount
Function Documentation
static void MessageServiceClear (void) static
Definition at line 140 of file layer_message_service.c.
References i, Message::image, messageTextCount, Message::time, and Message::topic.
Referenced by MessageServiceGetList(), and MessageServiceOnLeave().
static void MessageServiceDeleteComplete (void) static
Definition at line 170 of file layer_message_service.c.
References MessageServiceGetList(), and MessageTextListGet().
Referenced by MessageServiceDeleteConfirmOnPress().
bool MessageServiceDeleteConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 183 of file layer_message_service.c.
References ITUListBoxTag::focusIndex, Message::id, itcTreeGetChildAt, ituWidgetGetCustomData, MessageServiceDeleteComplete(), and MessageTextDelete().
bool MessageServiceDeleteOnPress (ITUWidget * widget, char * param)
Definition at line 175 of file layer_message_service.c.
References ITUListBoxTag::focusIndex.
static void MessageServiceGetList (Message * msgs, int count) static
Definition at line 161 of file layer_message_service.c.
References ituSceneExecuteCommand(), MessageServiceClear(), MessageServiceReload(), messageTextCount, and theScene.
Referenced by MessageServiceDeleteComplete(), and MessageServiceOnEnter().
bool MessageServiceOnEnter (ITUWidget * widget, char * param)
Definition at line 194 of file layer_message_service.c.
References ituSceneFindWidget(), MessageServiceGetList(), MessageTextListGet(), and theScene.
bool MessageServiceOnLeave (ITUWidget * widget, char * param)
Definition at line 211 of file layer_message_service.c.
References MessageServiceClear().
static void MessageServiceReload (int arg) static
Definition at line 134 of file layer_message_service.c.
References ituListBoxReload().
Referenced by MessageServiceGetList().
void MessageServiceReset (void)
Definition at line 217 of file layer_message_service.c.
Referenced by resetScene().
bool MessageServiceTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 68 of file layer_message_service.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, messageTextCount, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, Message::read, ITCTreeTag::sibling, and Message::time.
bool MessageServiceTopicListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_message_service.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, messageTextCount, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, Message::read, ITCTreeTag::sibling, and Message::topic.
bool MessageServiceViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 121 of file layer_message_service.c.
References ITUListBoxTag::focusIndex, Message::image, itcTreeGetChildAt, ituWidgetGetCustomData, and MessageServiceViewShow().
Variable Documentation
ITUListBox* messageServiceTimeListBox static
Definition at line 10 of file layer_message_service.c.
ITUListBox* messageServiceTopicListBox static
Definition at line 9 of file layer_message_service.c.
ITULayer* messageServiceViewLayer static
Definition at line 8 of file layer_message_service.c.
int messageTextCount static
Definition at line 12 of file layer_message_service.c.
Referenced by MessageServiceClear(), MessageServiceGetList(), MessageServiceTimeListBoxOnLoad(), and MessageServiceTopicListBoxOnLoad().
Message* messageTexts static
Definition at line 11 of file layer_message_service.c.