ITE SoC SDK: layer_called.c File Reference
layer_called.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SDL/SDL.h"
#include "scene.h"
#include "doorbell.h"
Macros
#define SNAPSHOT_COUNT (1 * 1000 / 33)
Functions
static bool CalledWaitingConfirmButtonOnSimulatePressing ()
bool CalledVolDownButtonOnPress (ITUWidget *widget, char *param)
bool CalledVolUpButtonOnPress (ITUWidget *widget, char *param)
bool CalledRecordButtonOnPress (ITUWidget *widget, char *param)
bool CalledStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool CalledSnapshotButtonOnPress (ITUWidget *widget, char *param)
bool CalledAnswerButtonOnPress (ITUWidget *widget, char *param)
bool CalledUnlockButtonOnPress (ITUWidget *widget, char *param)
bool CalledHangUpButtonOnPress (ITUWidget *widget, char *param)
bool CalledWaitingCancelButtonOnPress (ITUWidget *widget, char *param)
bool CalledWaitingConfirmButtonOnPress (ITUWidget *widget, char *param)
bool CalledSourceButtonOnPress (ITUWidget *widget, char *param)
bool CalledSourceListBoxOnLoad (ITUWidget *widget, char *param)
bool CalledSourceListBoxOnSelection (ITUWidget *widget, char *param)
bool CalledIncomingOnCustom (ITUWidget *widget, char *param)
void CalledIncomingShow (int id, char *addr, int video)
Sets the infomation to the receiving call screen.
bool CalledConnectedOnCustom (ITUWidget *widget, char *param)
bool CalledOnTimer (ITUWidget *widget, char *param)
bool CalledOnEnter (ITUWidget *widget, char *param)
bool CalledOnLeave (ITUWidget *widget, char *param)
void CalledReset (void)
Variables
static ITULayer * mainVoiceMemoLayer
static ITUBackground * calledRemoteBackground
static ITUSprite * calledRemoteSprite
static ITUText * calledSourceText
static ITUSprite * calledVolBar
static ITUText * calledCountDownText
static ITUBackground * calledWaitingBackground
static ITUText * calledWaitingTypeText
static ITUText * calledWaitingRoomText
static ITUButton * calledUnlockButton
static ITUButton * calledSnapshotButton
static ITUButton * calledRecordButton
static ITUButton * calledStopRecordButton
static ITUButton * calledAnswerButton
static ITUButton * calledButtonContainer
static ITUButton * calledSourceButton
static ITUListBox * calledSourceListBox
static int calledMaxVol
static bool calledInVideoState
static bool calledConnected
static bool calledSpotted
static float calledCountDown
static float spotCountDown
static float LockRecordButtonCountDown
static uint32_t calledLastTick
static uint32_t spotLastTick
static uint32_t LockRecordButtonLastTick
static int calledID
static int calledPendingID
static bool calledPendingVideo
static char calledPendingAddr [32]
static DeviceInfo calledDeviceInfo
static int calledVoiceLevelOld
static int calledRingLevelOld
static int snapshotCountDown
static DeviceInfo calledIPCameraInfoArray [MAX_IPCAMERA_COUNT]
static int calledIPCameraInfoCount
static bool calledVideoRecordEnable
static bool LockRecordButton
SPOTTED_STATUS callSpottedStatus
Macro Definition Documentation
#define SNAPSHOT_COUNT (1 * 1000 / 33)
Definition at line 47 of file layer_called.c.
Referenced by CalledSnapshotButtonOnPress().
Function Documentation
bool CalledAnswerButtonOnPress (ITUWidget * widget, char * param)
Definition at line 205 of file layer_called.c.
References calledConnected, calledID, calledSpotted, ituLayerGoto(), LinphoneAnswer(), LinphoneTerminate(), and SceneHangUp().
bool CalledConnectedOnCustom (ITUWidget * widget, char * param)
Definition at line 509 of file layer_called.c.
References calledConnected, calledCountDown, calledLastTick, calledMaxVol, Config::calling_time, ituSpriteGoto(), ituTextSetString, LinphoneGetVoiceLevel(), and theConfig.
bool CalledHangUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 228 of file layer_called.c.
References ituButtonSetPressed(), LinphoneTerminate(), and SceneHangUp().
bool CalledIncomingOnCustom (ITUWidget * widget, char * param)
Definition at line 401 of file layer_called.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, calledPendingAddr, calledPendingID, calledPendingVideo, callSpottedStatus, Config::dial_time, DeviceInfo::floor, ituTextSetString, ituWidgetDisable, ituWidgetSetVisible, DeviceInfo::room, spotCountDown, spotLastTick, SPOTTED_INIT, StringGetDeviceType(), StringGetRoomAddress(), theConfig, DeviceInfo::type, and DeviceInfo::unit.
bool CalledOnEnter (ITUWidget * widget, char * param)
Definition at line 620 of file layer_called.c.
References calledConnected, calledCountDown, calledInVideoState, calledIPCameraInfoCount, calledMaxVol, calledRingLevelOld, calledSpotted, calledVoiceLevelOld, itcTreeGetChildCount, ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, ituWidgetSetVisible, LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetWindowID(), snapshotCountDown, spotCountDown, and theScene.
bool CalledOnLeave (ITUWidget * widget, char * param)
Definition at line 707 of file layer_called.c.
References calledID, calledInVideoState, calledPendingID, calledRingLevelOld, calledVoiceLevelOld, CaptureStopRecord(), ConfigSave(), LinphoneGetRingLevel(), and LinphoneGetVoiceLevel().
bool CalledOnTimer (ITUWidget * widget, char * param)
Definition at line 530 of file layer_called.c.
References calledCountDown, calledID, calledLastTick, calledPendingID, CalledWaitingConfirmButtonOnSimulatePressing(), callSpottedStatus, font::f, ituLayerGoto(), ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, LinphoneAnswer(), LinphoneTerminate(), LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, SceneHangUp(), snapshotCountDown, spotCountDown, spotLastTick, SPOTTED_INIT, and SPOTTED_REJECT.
bool CalledRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 176 of file layer_called.c.
References calledInVideoState, CaptureStartRecord(), DeviceInfo::ip, LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, MEDIA_AUDIO, and MEDIA_VIDEO.
void CalledReset (void)
Definition at line 720 of file layer_called.c.
Referenced by resetScene().
bool CalledSnapshotButtonOnPress (ITUWidget * widget, char * param)
Definition at line 195 of file layer_called.c.
References CaptureSnapshot(), DeviceInfo::ip, SNAPSHOT_COUNT, and snapshotCountDown.
bool CalledSourceButtonOnPress (ITUWidget * widget, char * param)
Definition at line 304 of file layer_called.c.
References ituWidgetIsVisible, and ituWidgetSetVisible.
bool CalledSourceListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 318 of file layer_called.c.
References AddressBookGetIPCameraInfoArray(), DeviceInfo::alias, ITUColor::blue, calledIPCameraInfoCount, ITCTreeTag::child, ITUWidgetTag::color, ITUListBoxTag::focusIndex, ITUColor::green, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetBackColor(), ituTextSetString, ituWidgetSetCustomData, MAX_IPCAMERA_COUNT, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITUColor::red, ITCTreeTag::sibling, and ITUScrollText::text.
bool CalledSourceListBoxOnSelection (ITUWidget * widget, char * param)
Definition at line 371 of file layer_called.c.
References calledVideoRecordEnable, CaptureStopRecord(), ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituWidgetGetCustomData, ituWidgetSetVisible, and SceneCameraIsViewing().
bool CalledStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 188 of file layer_called.c.
References CaptureStopRecord(), and LockRecordButton.
bool CalledUnlockButtonOnPress (ITUWidget * widget, char * param)
Definition at line 222 of file layer_called.c.
References SceneOpenDoor().
bool CalledVolDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 108 of file layer_called.c.
References calledConnected, calledMaxVol, ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetRingLevel(), and LinphoneSetVoiceLevel().
bool CalledVolUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 142 of file layer_called.c.
References calledConnected, calledMaxVol, ituSpriteGoto(), LinphoneGetRingLevel(), LinphoneGetVoiceLevel(), LinphoneSetRingLevel(), and LinphoneSetVoiceLevel().
bool CalledWaitingCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 238 of file layer_called.c.
References calledPendingID, calledSpotted, callSpottedStatus, ituButtonSetPressed(), ituWidgetEnable, and SPOTTED_REJECT.
bool CalledWaitingConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 252 of file layer_called.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, calledID, calledInVideoState, calledPendingAddr, calledPendingID, calledPendingVideo, calledSpotted, calledVideoRecordEnable, callSpottedStatus, CaptureStopRecord(), DEVICE_OUTDOOR, DEVICE_WALL, DeviceInfo::floor, ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, LinphoneSetWindowID(), DeviceInfo::room, SPOTTED_ALLOW, StringGetRoomAddress(), DeviceInfo::type, and DeviceInfo::unit.
static bool CalledWaitingConfirmButtonOnSimulatePressing () static
Definition at line 55 of file layer_called.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, calledID, calledInVideoState, calledPendingAddr, calledPendingID, calledPendingVideo, calledSpotted, calledVideoRecordEnable, callSpottedStatus, CaptureStopRecord(), DEVICE_OUTDOOR, DEVICE_WALL, DeviceInfo::floor, ituTextSetString, ituWidgetEnable, ituWidgetSetVisible, LinphoneSetWindowID(), DeviceInfo::room, SPOTTED_ALLOW, StringGetRoomAddress(), DeviceInfo::type, and DeviceInfo::unit.
Referenced by CalledOnTimer().
Variable Documentation
ITUButton* calledAnswerButton static
Definition at line 22 of file layer_called.c.
ITUButton* calledButtonContainer static
Definition at line 23 of file layer_called.c.
bool calledConnected static
Definition at line 30 of file layer_called.c.
Referenced by CalledAnswerButtonOnPress(), CalledConnectedOnCustom(), CalledOnEnter(), CalledVolDownButtonOnPress(), and CalledVolUpButtonOnPress().
float calledCountDown static
Definition at line 32 of file layer_called.c.
Referenced by CalledConnectedOnCustom(), CalledIncomingShow(), CalledOnEnter(), and CalledOnTimer().
ITUText* calledCountDownText static
Definition at line 14 of file layer_called.c.
DeviceInfo calledDeviceInfo static
Definition at line 37 of file layer_called.c.
int calledID static
Definition at line 34 of file layer_called.c.
Referenced by CalledAnswerButtonOnPress(), CalledIncomingShow(), CalledOnLeave(), CalledOnTimer(), CalledWaitingConfirmButtonOnPress(), and CalledWaitingConfirmButtonOnSimulatePressing().
bool calledInVideoState static
Definition at line 29 of file layer_called.c.
Referenced by CalledIncomingShow(), CalledOnEnter(), CalledOnLeave(), CalledRecordButtonOnPress(), CalledWaitingConfirmButtonOnPress(), and CalledWaitingConfirmButtonOnSimulatePressing().
DeviceInfo calledIPCameraInfoArray[MAX_IPCAMERA_COUNT] static
Definition at line 40 of file layer_called.c.
int calledIPCameraInfoCount static
Definition at line 41 of file layer_called.c.
Referenced by CalledOnEnter(), and CalledSourceListBoxOnLoad().
uint32_t calledLastTick static
Definition at line 33 of file layer_called.c.
Referenced by CalledConnectedOnCustom(), and CalledOnTimer().
int calledMaxVol static
Definition at line 28 of file layer_called.c.
Referenced by CalledConnectedOnCustom(), CalledOnEnter(), CalledVolDownButtonOnPress(), and CalledVolUpButtonOnPress().
char calledPendingAddr[32] static
Definition at line 36 of file layer_called.c.
Referenced by CalledIncomingOnCustom(), CalledWaitingConfirmButtonOnPress(), and CalledWaitingConfirmButtonOnSimulatePressing().
int calledPendingID static
Definition at line 34 of file layer_called.c.
Referenced by CalledIncomingOnCustom(), CalledOnLeave(), CalledOnTimer(), CalledWaitingCancelButtonOnPress(), CalledWaitingConfirmButtonOnPress(), and CalledWaitingConfirmButtonOnSimulatePressing().
bool calledPendingVideo static
Definition at line 35 of file layer_called.c.
Referenced by CalledIncomingOnCustom(), CalledWaitingConfirmButtonOnPress(), and CalledWaitingConfirmButtonOnSimulatePressing().
ITUButton* calledRecordButton static
Definition at line 20 of file layer_called.c.
ITUBackground* calledRemoteBackground static
Definition at line 10 of file layer_called.c.
ITUSprite* calledRemoteSprite static
Definition at line 11 of file layer_called.c.
int calledRingLevelOld static
Definition at line 38 of file layer_called.c.
Referenced by CalledOnEnter(), and CalledOnLeave().
ITUButton* calledSnapshotButton static
Definition at line 19 of file layer_called.c.
ITUButton* calledSourceButton static
Definition at line 24 of file layer_called.c.
ITUListBox* calledSourceListBox static
Definition at line 25 of file layer_called.c.
ITUText* calledSourceText static
Definition at line 12 of file layer_called.c.
bool calledSpotted static
Definition at line 31 of file layer_called.c.
Referenced by CalledAnswerButtonOnPress(), CalledOnEnter(), CalledWaitingCancelButtonOnPress(), CalledWaitingConfirmButtonOnPress(), and CalledWaitingConfirmButtonOnSimulatePressing().
ITUButton* calledStopRecordButton static
Definition at line 21 of file layer_called.c.
ITUButton* calledUnlockButton static
Definition at line 18 of file layer_called.c.
bool calledVideoRecordEnable static
Definition at line 42 of file layer_called.c.
Referenced by CalledIncomingShow(), CalledSourceListBoxOnSelection(), CalledWaitingConfirmButtonOnPress(), and CalledWaitingConfirmButtonOnSimulatePressing().
int calledVoiceLevelOld static
Definition at line 38 of file layer_called.c.
Referenced by CalledOnEnter(), and CalledOnLeave().
ITUSprite* calledVolBar static
Definition at line 13 of file layer_called.c.
ITUBackground* calledWaitingBackground static
Definition at line 15 of file layer_called.c.
ITUText* calledWaitingRoomText static
Definition at line 17 of file layer_called.c.
ITUText* calledWaitingTypeText static
Definition at line 16 of file layer_called.c.
SPOTTED_STATUS callSpottedStatus
Definition at line 46 of file doorbell_indoor/scene.c.
Referenced by CalledIncomingOnCustom(), CalledOnTimer(), CalledWaitingCancelButtonOnPress(), CalledWaitingConfirmButtonOnPress(), and CalledWaitingConfirmButtonOnSimulatePressing().
bool LockRecordButton static
Definition at line 43 of file layer_called.c.
Referenced by CalledOnTimer(), CalledRecordButtonOnPress(), and CalledStopRecordButtonOnPress().
float LockRecordButtonCountDown static
Definition at line 32 of file layer_called.c.
Referenced by CalledOnTimer(), and CalledRecordButtonOnPress().
uint32_t LockRecordButtonLastTick static
Definition at line 33 of file layer_called.c.
Referenced by CalledOnTimer(), and CalledRecordButtonOnPress().
ITULayer* mainVoiceMemoLayer static
Definition at line 9 of file layer_called.c.
Referenced by SceneRun().
int snapshotCountDown static
Definition at line 39 of file layer_called.c.
Referenced by CalledOnEnter(), CalledOnTimer(), and CalledSnapshotButtonOnPress().
float spotCountDown static
Definition at line 32 of file layer_called.c.
Referenced by CalledIncomingOnCustom(), CalledOnEnter(), and CalledOnTimer().
uint32_t spotLastTick static
Definition at line 33 of file layer_called.c.
Referenced by CalledIncomingOnCustom(), and CalledOnTimer().