ITE SoC SDK: layer_setting_engineer_misc.c File Reference
layer_setting_engineer_misc.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool SettingEngineerMiscClearConfirmOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscUpgradeButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscDefaultButtonOnPress (ITUWidget *widget, char *param)
Function Documentation
bool SettingEngineerMiscClearConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 9 of file layer_setting_engineer_misc.c.
References QUIT_RESET_TEMP_DRIVE, and SceneQuit().
bool SettingEngineerMiscDefaultButtonOnPress (ITUWidget * widget, char * param)
Definition at line 23 of file layer_setting_engineer_misc.c.
References QUIT_RESET_FACTORY, and SceneQuit().
bool SettingEngineerMiscUpgradeButtonOnPress (ITUWidget * widget, char * param)
Definition at line 15 of file layer_setting_engineer_misc.c.
References ServerInfo::firmwareUrl, QUIT_UPGRADE_FIRMWARE, RemoteGetServerInfo(), SceneQuit(), serverInfo, and UpgradeSetUrl().