ITE SoC SDK: layer_touch_calibration.c File Reference
layer_touch_calibration.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "ite/itp.h"
#include "scene.h"
#include "doorbell.h"
Functions
int Castor3_CalibrateTouch (float screenX[], float screenY[], float touchX[], float touchY[])
void Castor3_ChangeTouchMode (int raw)
void Castor3_ReadTouchRawPosition (float *x, float *y)
bool TouchCalibrationCheckBoxOnPress (ITUWidget *widget, char *param)
bool TouchCalibrationOnEnter (ITUWidget *widget, char *param)
bool TouchCalibrationOnLeave (ITUWidget *widget, char *param)
void TouchCalibrationReset (void)
Variables
static ITUWidget * touchCalibrationLayer
static ITUCheckBox * touchCalibration1CheckBox
static ITUCheckBox * touchCalibration2CheckBox
static ITUCheckBox * touchCalibration3CheckBox
static ITUCheckBox * touchCalibration4CheckBox
static ITUCheckBox * touchCalibration5CheckBox
static float screenX [5]
static float screenY [5]
static float touchX [5]
static float touchY [5]
Function Documentation
int Castor3_CalibrateTouch (float screenX[], float screenY[], float touchX[], float touchY[])
Referenced by TouchCalibrationCheckBoxOnPress().
void Castor3_ChangeTouchMode (int raw)
Referenced by TouchCalibrationOnEnter(), and TouchCalibrationOnLeave().
void Castor3_ReadTouchRawPosition (float * x, float * y)
Referenced by TouchCalibrationCheckBoxOnPress().
bool TouchCalibrationCheckBoxOnPress (ITUWidget * widget, char * param)
Definition at line 23 of file layer_touch_calibration.c.
References Castor3_CalibrateTouch(), Castor3_ReadTouchRawPosition(), ConfigSave(), itp_codec_standby(), ituCheckBoxIsChecked(), ituCheckBoxSetChecked(), screenX, screenY, theConfig, Config::touch_calibration, touchX, touchY, and font::x.
bool TouchCalibrationOnEnter (ITUWidget * widget, char * param)
Definition at line 87 of file layer_touch_calibration.c.
References Castor3_ChangeTouchMode(), ituCheckBoxSetChecked(), ituSceneFindWidget(), ituWidgetGetGlobalPosition, ituWidgetGetHeight, ituWidgetGetWidth, ituWidgetSetVisible, screenX, screenY, theScene, and font::x.
bool TouchCalibrationOnLeave (ITUWidget * widget, char * param)
Definition at line 141 of file layer_touch_calibration.c.
References Castor3_ChangeTouchMode().
void TouchCalibrationReset (void)
Definition at line 149 of file layer_touch_calibration.c.
Referenced by resetScene().
Variable Documentation
float screenX[5] static
Definition at line 21 of file layer_touch_calibration.c.
Referenced by TouchCalibrationCheckBoxOnPress(), and TouchCalibrationOnEnter().
float screenY[5] static
Definition at line 21 of file layer_touch_calibration.c.
Referenced by TouchCalibrationCheckBoxOnPress(), and TouchCalibrationOnEnter().
ITUCheckBox* touchCalibration1CheckBox static
Definition at line 15 of file layer_touch_calibration.c.
ITUCheckBox* touchCalibration2CheckBox static
Definition at line 16 of file layer_touch_calibration.c.
ITUCheckBox* touchCalibration3CheckBox static
Definition at line 17 of file layer_touch_calibration.c.
ITUCheckBox* touchCalibration4CheckBox static
Definition at line 18 of file layer_touch_calibration.c.
ITUCheckBox* touchCalibration5CheckBox static
Definition at line 19 of file layer_touch_calibration.c.
ITUWidget* touchCalibrationLayer static
Definition at line 14 of file layer_touch_calibration.c.
float touchX[5] static
Definition at line 21 of file layer_touch_calibration.c.
Referenced by TouchCalibrationCheckBoxOnPress().
float touchY[5] static
Definition at line 21 of file layer_touch_calibration.c.
Referenced by TouchCalibrationCheckBoxOnPress().