ITE SoC SDK: layer_camera_view.c File Reference
layer_camera_view.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
static void CameraViewSetCameraBackgroundWindowID (int arg)
static void CameraViewEnableSnapshot (int arg)
bool CameraViewButtonOnPress (ITUWidget *widget, char *param)
bool CameraViewRecordButtonOnPress (ITUWidget *widget, char *param)
bool CameraViewStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool CameraViewUnlockButtonOnPress (ITUWidget *widget, char *param)
bool CameraViewSnapshotButtonOnPress (ITUWidget *widget, char *param)
void CameraViewShow (char *camera, char *ip)
Sets the infomation to the viewing camera fullscreen.
bool CameraViewOnLeave (ITUWidget *widget, char *param)
void CameraViewReset (void)
Variables
static ITUBackground * cameraBackground
static ITUText * cameraViewSourceText
static DeviceInfo cameraDeviceInfo
static bool cameraViewIsLeaving
static bool cameraViewIsSnapshoting
static bool cameraViewVideoRecordEnable
float CameraLockRecordButtonCountDown
uint32_t CameraLockRecordButtonLastTick
bool CameraLockRecordButton
Function Documentation
bool CameraViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 29 of file layer_camera_view.c.
References cameraViewIsLeaving, CameraViewSetCameraBackgroundWindowID(), ituSceneExecuteCommand(), ituSceneFindWidget(), and theScene.
static void CameraViewEnableSnapshot (int arg) static
Definition at line 24 of file layer_camera_view.c.
References cameraViewIsSnapshoting.
Referenced by CameraViewSnapshotButtonOnPress().
bool CameraViewOnLeave (ITUWidget * widget, char * param)
Definition at line 99 of file layer_camera_view.c.
References cameraViewVideoRecordEnable, CaptureStopRecord(), LinphoneStopCamera(), SceneCameraSetViewing(), and SceneContinuePlayGuardAlarm().
bool CameraViewRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 41 of file layer_camera_view.c.
References CameraLockRecordButton, CameraLockRecordButtonCountDown, CameraLockRecordButtonLastTick, cameraViewVideoRecordEnable, CaptureStartRecord(), DeviceInfo::ip, and MEDIA_VIDEO.
void CameraViewReset (void)
Definition at line 113 of file layer_camera_view.c.
References cameraViewIsLeaving.
Referenced by resetScene().
static void CameraViewSetCameraBackgroundWindowID (int arg) static
Definition at line 18 of file layer_camera_view.c.
References cameraViewIsLeaving, and LinphoneSetWindowID().
Referenced by CameraViewButtonOnPress().
bool CameraViewSnapshotButtonOnPress (ITUWidget * widget, char * param)
Definition at line 70 of file layer_camera_view.c.
References CameraViewEnableSnapshot(), cameraViewIsSnapshoting, CaptureSnapshot(), DeviceInfo::ip, ituSceneExecuteCommand(), and theScene.
bool CameraViewStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 55 of file layer_camera_view.c.
References CameraLockRecordButton, cameraViewVideoRecordEnable, and CaptureStopRecord().
bool CameraViewUnlockButtonOnPress (ITUWidget * widget, char * param)
Definition at line 64 of file layer_camera_view.c.
References DeviceInfo::ip, and SceneOpenDoor().
Variable Documentation
ITUBackground* cameraBackground static
Definition at line 8 of file layer_camera_view.c.
DeviceInfo cameraDeviceInfo static
Definition at line 10 of file layer_camera_view.c.
bool CameraLockRecordButton
Definition at line 28 of file layer_camera.c.
Referenced by CameraOnTimer(), CameraViewRecordButtonOnPress(), and CameraViewStopRecordButtonOnPress().
float CameraLockRecordButtonCountDown
Definition at line 26 of file layer_camera.c.
Referenced by CameraOnTimer(), and CameraViewRecordButtonOnPress().
uint32_t CameraLockRecordButtonLastTick
Definition at line 27 of file layer_camera.c.
Referenced by CameraOnTimer(), and CameraViewRecordButtonOnPress().
bool cameraViewIsLeaving static
Definition at line 11 of file layer_camera_view.c.
Referenced by CameraViewButtonOnPress(), CameraViewReset(), CameraViewSetCameraBackgroundWindowID(), and CameraViewShow().
bool cameraViewIsSnapshoting static
Definition at line 11 of file layer_camera_view.c.
Referenced by CameraViewEnableSnapshot(), CameraViewShow(), and CameraViewSnapshotButtonOnPress().
ITUText* cameraViewSourceText static
Definition at line 9 of file layer_camera_view.c.
bool cameraViewVideoRecordEnable static
Definition at line 12 of file layer_camera_view.c.
Referenced by CameraViewOnLeave(), CameraViewRecordButtonOnPress(), CameraViewShow(), and CameraViewStopRecordButtonOnPress().