ITE SoC SDK: layer_phone_dial_lobby.c File Reference
layer_phone_dial_lobby.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool PhoneLobbyListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLobbyCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneDialLobbyOnEnter (ITUWidget *widget, char *param)
void PhoneDialLobbyReset (void)
Variables
static ITUListBox * phoneLobbyListBox
static DeviceInfo phoneCallLobbyInfoArray [MAX_CAMERA_COUNT]
static int phoneCallLobbyInfoCount
Function Documentation
bool PhoneDialLobbyOnEnter (ITUWidget * widget, char * param)
Definition at line 80 of file layer_phone_dial_lobby.c.
References ituSceneFindWidget(), and theScene.
void PhoneDialLobbyReset (void)
Definition at line 90 of file layer_phone_dial_lobby.c.
Referenced by resetScene().
bool PhoneLobbyCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_phone_dial_lobby.c.
References CallingCallByIP(), ITUListBoxTag::focusIndex, DeviceInfo::ip, itcTreeGetChildAt, and ituWidgetGetCustomData.
bool PhoneLobbyListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_phone_dial_lobby.c.
References AddressBookGetCameraInfoArray(), DeviceInfo::alias, ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, MAX_CAMERA_COUNT, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, phoneCallLobbyInfoCount, ITCTreeTag::sibling, and theDeviceInfo.
Variable Documentation
DeviceInfo phoneCallLobbyInfoArray[MAX_CAMERA_COUNT] static
Definition at line 10 of file layer_phone_dial_lobby.c.
int phoneCallLobbyInfoCount static
Definition at line 11 of file layer_phone_dial_lobby.c.
Referenced by PhoneLobbyListBoxOnLoad().
ITUListBox* phoneLobbyListBox static
Definition at line 8 of file layer_phone_dial_lobby.c.