ITE SoC SDK: layer_setting_engineer_misc_terminal.c File Reference
layer_setting_engineer_misc_terminal.c File Reference
#include <assert.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool SettingEngineerMiscTerminalNumberButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTerminalBackButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTerminalClearButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTerminalConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerMiscTerminalOnEnter (ITUWidget *widget, char *param)
void SettingEngineerMiscTerminalReset (void)
Variables
static ITUWidget * settingEngineerMiscTermLayer
static ITUTextBox * settingEngineerMiscTerminalAreaTextBox
static ITUTextBox * settingEngineerMiscTerminalBuildingTextBox
static ITUTextBox * settingEngineerMiscTerminalUnitTextBox
static ITUTextBox * settingEngineerMiscTerminalFloorTextBox
static ITUTextBox * settingEngineerMiscTerminalRoomTextBox
static ITUTextBox * settingEngineerMiscTerminalExtTextBox
static ITUButton * settingEngineerMiscTerminal0Button
static ITUButton * settingEngineerMiscTerminal1Button
static ITUButton * settingEngineerMiscTerminal2Button
static ITUButton * settingEngineerMiscTerminal3Button
static ITUButton * settingEngineerMiscTerminal4Button
static ITUButton * settingEngineerMiscTerminal5Button
static ITUButton * settingEngineerMiscTerminal6Button
static ITUButton * settingEngineerMiscTerminal7Button
static ITUButton * settingEngineerMiscTerminal8Button
static ITUButton * settingEngineerMiscTerminal9Button
static ITUButton * settingEngineerMiscTerminalAButton
static ITUButton * settingEngineerMiscTerminalBButton
static ITUButton * settingEngineerMiscTerminalCButton
static ITUButton * settingEngineerMiscTerminalStarButton
static ITUButton * settingEngineerMiscTerminalPoundButton
static ITUButton * settingEngineerMiscTerminalBackButton
static ITUButton * settingEngineerMiscTerminalClearButton
static ITUButton * settingEngineerMiscTerminalConfirmButton
static ITUButton * settingEngineerMiscTerminalCloseButton
static ITUTextBox * activeSettingEngineerMiscTerminalTextBox
Function Documentation
bool SettingEngineerMiscTerminalBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_setting_engineer_misc_terminal.c.
References ituTextBoxSetString(), settingEngineerMiscTerminalAreaTextBox, settingEngineerMiscTerminalBuildingTextBox, settingEngineerMiscTerminalFloorTextBox, settingEngineerMiscTerminalRoomTextBox, and settingEngineerMiscTerminalUnitTextBox.
bool SettingEngineerMiscTerminalClearButtonOnPress (ITUWidget * widget, char * param)
Definition at line 92 of file layer_setting_engineer_misc_terminal.c.
References ituTextBoxSetString(), and settingEngineerMiscTerminalAreaTextBox.
bool SettingEngineerMiscTerminalConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 104 of file layer_setting_engineer_misc_terminal.c.
References Config::area, Config::building, ConfigSaveAll(), Config::ext, Config::floor, ituTextBoxGetString(), QUIT_RESET_NETWORK, Config::room, SceneQuit(), theConfig, and Config::unit.
bool SettingEngineerMiscTerminalNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 41 of file layer_setting_engineer_misc_terminal.c.
References ituTextBoxGetString(), ituTextBoxInput(), ituTextGetString, ITUTextBox::maxLen, settingEngineerMiscTerminalBuildingTextBox, settingEngineerMiscTerminalExtTextBox, settingEngineerMiscTerminalFloorTextBox, settingEngineerMiscTerminalRoomTextBox, settingEngineerMiscTerminalUnitTextBox, and ITUButton::text.
bool SettingEngineerMiscTerminalOnEnter (ITUWidget * widget, char * param)
Definition at line 144 of file layer_setting_engineer_misc_terminal.c.
References Config::area, Config::building, Config::ext, Config::floor, ituSceneFindWidget(), ituTextBoxSetString(), Config::room, settingEngineerMiscTerminalAreaTextBox, settingEngineerMiscTerminalBuildingTextBox, settingEngineerMiscTerminalExtTextBox, settingEngineerMiscTerminalFloorTextBox, settingEngineerMiscTerminalRoomTextBox, settingEngineerMiscTerminalUnitTextBox, theConfig, theScene, and Config::unit.
void SettingEngineerMiscTerminalReset (void)
Definition at line 189 of file layer_setting_engineer_misc_terminal.c.
Referenced by resetScene().
Variable Documentation
ITUTextBox* activeSettingEngineerMiscTerminalTextBox static
Definition at line 39 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal0Button static
Definition at line 18 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal1Button static
Definition at line 19 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal2Button static
Definition at line 20 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal3Button static
Definition at line 21 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal4Button static
Definition at line 22 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal5Button static
Definition at line 23 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal6Button static
Definition at line 24 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal7Button static
Definition at line 25 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal8Button static
Definition at line 26 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminal9Button static
Definition at line 27 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminalAButton static
Definition at line 28 of file layer_setting_engineer_misc_terminal.c.
ITUTextBox* settingEngineerMiscTerminalAreaTextBox static
Definition at line 11 of file layer_setting_engineer_misc_terminal.c.
Referenced by SettingEngineerMiscTerminalBackButtonOnPress(), SettingEngineerMiscTerminalClearButtonOnPress(), and SettingEngineerMiscTerminalOnEnter().
ITUButton* settingEngineerMiscTerminalBackButton static
Definition at line 34 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminalBButton static
Definition at line 29 of file layer_setting_engineer_misc_terminal.c.
ITUTextBox* settingEngineerMiscTerminalBuildingTextBox static
Definition at line 12 of file layer_setting_engineer_misc_terminal.c.
Referenced by SettingEngineerMiscTerminalBackButtonOnPress(), SettingEngineerMiscTerminalNumberButtonOnPress(), and SettingEngineerMiscTerminalOnEnter().
ITUButton* settingEngineerMiscTerminalCButton static
Definition at line 30 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminalClearButton static
Definition at line 35 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminalCloseButton static
Definition at line 37 of file layer_setting_engineer_misc_terminal.c.
ITUButton* settingEngineerMiscTerminalConfirmButton static
Definition at line 36 of file layer_setting_engineer_misc_terminal.c.
ITUTextBox* settingEngineerMiscTerminalExtTextBox static
Definition at line 16 of file layer_setting_engineer_misc_terminal.c.
Referenced by SettingEngineerMiscTerminalNumberButtonOnPress(), and SettingEngineerMiscTerminalOnEnter().
ITUTextBox* settingEngineerMiscTerminalFloorTextBox static
Definition at line 14 of file layer_setting_engineer_misc_terminal.c.
Referenced by SettingEngineerMiscTerminalBackButtonOnPress(), SettingEngineerMiscTerminalNumberButtonOnPress(), and SettingEngineerMiscTerminalOnEnter().
ITUButton* settingEngineerMiscTerminalPoundButton static
Definition at line 32 of file layer_setting_engineer_misc_terminal.c.
ITUTextBox* settingEngineerMiscTerminalRoomTextBox static
Definition at line 15 of file layer_setting_engineer_misc_terminal.c.
Referenced by SettingEngineerMiscTerminalBackButtonOnPress(), SettingEngineerMiscTerminalNumberButtonOnPress(), and SettingEngineerMiscTerminalOnEnter().
ITUButton* settingEngineerMiscTerminalStarButton static
Definition at line 31 of file layer_setting_engineer_misc_terminal.c.
ITUTextBox* settingEngineerMiscTerminalUnitTextBox static
Definition at line 13 of file layer_setting_engineer_misc_terminal.c.
Referenced by SettingEngineerMiscTerminalBackButtonOnPress(), SettingEngineerMiscTerminalNumberButtonOnPress(), and SettingEngineerMiscTerminalOnEnter().
ITUWidget* settingEngineerMiscTermLayer static
Definition at line 9 of file layer_setting_engineer_misc_terminal.c.