ITE SoC SDK: layer_setting_engineer_network.c File Reference
layer_setting_engineer_network.c File Reference
#include <sys/ioctl.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "ite/itp.h"
#include "scene.h"
#include "doorbell.h"
Functions
static void SettingEngineerNetworkIPCallback (char *ip)
static void SettingEngineerNetworkNetmaskCallback (char *ip)
static void SettingEngineerNetworkMacCallback (char *mac)
static void SettingEngineerNetworkDnsCallback (char *ip)
static void SettingEngineerNetworkGatewayCallback (char *ip)
bool SettingEngineerNetworkIPButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkNetmaskButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkMacButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkDnsButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkGatewayButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkOnEnter (ITUWidget *widget, char *param)
void SettingEngineerNetworkReset (void)
Variables
static ITURadioBox * settingEngineerNetworkAutoRadioBox
static ITURadioBox * settingEngineerNetworkStaticRadioBox
static ITUTextBox * settingEngineerNetworkIPTextBox
static ITUTextBox * settingEngineerNetworkNetmaskTextBox
static ITUTextBox * settingEngineerNetworkMacTextBox
static ITUTextBox * settingEngineerNetworkDnsTextBox
static ITUTextBox * settingEngineerNetworkGatewayTextBox
static ITUButton * settingEngineerNetworkIPButton
static ITUButton * settingEngineerNetworkWiFiButton
static ITPEthernetInfo settingEngineerNetworkEthernetInfo
Function Documentation
bool SettingEngineerNetworkDnsButtonOnPress (ITUWidget * widget, char * param)
Definition at line 72 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkDnsCallback(), and SettingEngineerNetworkIPShow().
static void SettingEngineerNetworkDnsCallback (char * ip) static
Definition at line 42 of file layer_setting_engineer_network.c.
References ituTextBoxSetString().
Referenced by SettingEngineerNetworkDnsButtonOnPress().
bool SettingEngineerNetworkGatewayButtonOnPress (ITUWidget * widget, char * param)
Definition at line 78 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkGatewayCallback(), and SettingEngineerNetworkIPShow().
static void SettingEngineerNetworkGatewayCallback (char * ip) static
Definition at line 48 of file layer_setting_engineer_network.c.
References ituTextBoxSetString().
Referenced by SettingEngineerNetworkGatewayButtonOnPress().
bool SettingEngineerNetworkIPButtonOnPress (ITUWidget * widget, char * param)
Definition at line 54 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkIPCallback(), and SettingEngineerNetworkIPShow().
static void SettingEngineerNetworkIPCallback (char * ip) static
Definition at line 24 of file layer_setting_engineer_network.c.
References ituTextBoxSetString().
Referenced by SettingEngineerNetworkIPButtonOnPress().
bool SettingEngineerNetworkMacButtonOnPress (ITUWidget * widget, char * param)
Definition at line 66 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkMacCallback(), and SettingEngineerNetworkMacShow().
static void SettingEngineerNetworkMacCallback (char * mac) static
Definition at line 36 of file layer_setting_engineer_network.c.
References ituTextBoxSetString().
Referenced by SettingEngineerNetworkMacButtonOnPress().
bool SettingEngineerNetworkNetmaskButtonOnPress (ITUWidget * widget, char * param)
Definition at line 60 of file layer_setting_engineer_network.c.
References ituTextGetString, SettingEngineerNetworkIPShow(), and SettingEngineerNetworkNetmaskCallback().
static void SettingEngineerNetworkNetmaskCallback (char * ip) static
Definition at line 30 of file layer_setting_engineer_network.c.
References ituTextBoxSetString().
Referenced by SettingEngineerNetworkNetmaskButtonOnPress().
bool SettingEngineerNetworkOnEnter (ITUWidget * widget, char * param)
Definition at line 142 of file layer_setting_engineer_network.c.
References Config::dhcp, Config::dns, Config::gw, ITPEthernetInfo::hardwareAddress, ITPEthernetInfo::index, Config::ipaddr, ITP_DEVICE_ETHERNET, ITP_IOCTL_GET_INFO, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituTextBoxSetString(), ituWidgetSetVisible, Config::netmask, theConfig, and theScene.
void SettingEngineerNetworkReset (void)
Definition at line 203 of file layer_setting_engineer_network.c.
Referenced by resetScene().
bool SettingEngineerNetworkSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 84 of file layer_setting_engineer_network.c.
References Config::area, Config::building, ConfigSave(), Config::dhcp, Config::dns, Config::ext, Config::floor, Config::gw, ITPEthernetInfo::hardwareAddress, i, Config::ipaddr, itp_codec_standby(), ITP_DEVICE_ETHERNET, ITP_IOCTL_WIRTE_MAC, ituRadioBoxIsChecked(), ituTextGetString, Config::netmask, QUIT_RESET_NETWORK, Config::room, SceneQuit(), theConfig, and Config::unit.
Variable Documentation
ITURadioBox* settingEngineerNetworkAutoRadioBox static
Definition at line 11 of file layer_setting_engineer_network.c.
ITUTextBox* settingEngineerNetworkDnsTextBox static
Definition at line 17 of file layer_setting_engineer_network.c.
ITPEthernetInfo settingEngineerNetworkEthernetInfo static
Definition at line 22 of file layer_setting_engineer_network.c.
ITUTextBox* settingEngineerNetworkGatewayTextBox static
Definition at line 18 of file layer_setting_engineer_network.c.
ITUButton* settingEngineerNetworkIPButton static
Definition at line 20 of file layer_setting_engineer_network.c.
ITUTextBox* settingEngineerNetworkIPTextBox static
Definition at line 14 of file layer_setting_engineer_network.c.
ITUTextBox* settingEngineerNetworkMacTextBox static
Definition at line 16 of file layer_setting_engineer_network.c.
ITUTextBox* settingEngineerNetworkNetmaskTextBox static
Definition at line 15 of file layer_setting_engineer_network.c.
ITURadioBox* settingEngineerNetworkStaticRadioBox static
Definition at line 12 of file layer_setting_engineer_network.c.
ITUButton* settingEngineerNetworkWiFiButton static
Definition at line 21 of file layer_setting_engineer_network.c.