ITE SoC SDK: layer_phone_log_sent.c File Reference
layer_phone_log_sent.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool PhoneLogSentRoomListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogSentTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogSentDurationListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogSentCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentAddButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentViewButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentDeleteButtonOnPress (ITUWidget *widget, char *param)
static void PhoneLogSentReload (int arg)
bool PhoneLogSentDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentClearConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogSentOnEnter (ITUWidget *widget, char *param)
void PhoneLogSentReset (void)
Variables
static ITULayer * phoneLogSentLayer
static ITUListBox * phoneLogSentRoomListBox
static ITUListBox * phoneLogSentTimeListBox
static ITUListBox * phoneLogSentDurationListBox
Function Documentation
bool PhoneLogSentAddButtonOnPress (ITUWidget * widget, char * param)
Definition at line 185 of file layer_phone_log_sent.c.
References AddressBookGetDeviceInfo(), CALLLOG_SENT, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, and PhoneContactsAddShow().
bool PhoneLogSentCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 169 of file layer_phone_log_sent.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CallingCall(), CALLLOG_SENT, CallLogGetEntry(), DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, DeviceInfo::room, DeviceInfo::type, and DeviceInfo::unit.
bool PhoneLogSentClearConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 252 of file layer_phone_log_sent.c.
References CALLLOG_SENT, CallLogClearEntries(), ituSceneExecuteCommand(), PhoneLogSentReload(), and theScene.
bool PhoneLogSentDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 224 of file layer_phone_log_sent.c.
References ITUListBoxTag::focusIndex.
bool PhoneLogSentDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 239 of file layer_phone_log_sent.c.
References CALLLOG_SENT, CallLogDeleteEntry(), CallLogGetEntry(), ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, PhoneLogSentReload(), and theScene.
bool PhoneLogSentDurationListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 118 of file layer_phone_log_sent.c.
References CALLLOG_SENT, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, CallLogEntry::duration, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool PhoneLogSentOnEnter (ITUWidget * widget, char * param)
Definition at line 259 of file layer_phone_log_sent.c.
References ituSceneFindWidget(), and theScene.
static void PhoneLogSentReload (int arg) static
Definition at line 232 of file layer_phone_log_sent.c.
References ituListBoxReload().
Referenced by PhoneLogSentClearConfirmButtonOnPress(), and PhoneLogSentDeleteConfirmButtonOnPress().
void PhoneLogSentReset (void)
Definition at line 278 of file layer_phone_log_sent.c.
Referenced by resetScene().
bool PhoneLogSentRoomListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_phone_log_sent.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CALLLOG_SENT, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, ITCTreeTag::sibling, StringGetRoomAddress(), and DeviceInfo::unit.
bool PhoneLogSentTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 68 of file layer_phone_log_sent.c.
References CALLLOG_SENT, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and CallLogEntry::time.
bool PhoneLogSentViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 201 of file layer_phone_log_sent.c.
References AddressBookGetDeviceInfo(), DeviceInfo::alias, CALLLOG_SENT, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, PhoneLogViewShow(), StringGetCallLogType(), ITUScrollText::text, and CallLogEntry::time.
Variable Documentation
ITUListBox* phoneLogSentDurationListBox static
Definition at line 11 of file layer_phone_log_sent.c.
ITULayer* phoneLogSentLayer static
Definition at line 8 of file layer_phone_log_sent.c.
ITUListBox* phoneLogSentRoomListBox static
Definition at line 9 of file layer_phone_log_sent.c.
ITUListBox* phoneLogSentTimeListBox static
Definition at line 10 of file layer_phone_log_sent.c.