ITE SoC SDK: layer_setting_engineer_network_wifi.c File Reference
layer_setting_engineer_network_wifi.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "ite/itp.h"
#include "wifiMgr.h"
Functions
bool SettingEngineerNetworkWiFiNameListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiConnectButtonOnPress (ITUWidget *widget, char *param)
static void SettingEngineerNetworkWiFiPasswordCallback (char *password)
bool SettingEngineerNetworkWiFiDisconnectButtonOnPress (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiOnTimer (ITUWidget *widget, char *param)
bool SettingEngineerNetworkWiFiOnEnter (ITUWidget *widget, char *param)
void SettingEngineerNetworkWiFiReset (void)
Variables
static ITULayer * settingEngineerNetworkWiFiLayer
static ITUListBox * settingEngineerNetworkWiFiNameListBox
static ITUListBox * settingEngineerNetworkWiFiStatusListBox
static bool settingEngineerNetworkWiFiShowPasswordDialog
static WIFI_MGR_SCANAP_LIST pList [64]
static int nApCount
static int gnApSecurity
Function Documentation
bool SettingEngineerNetworkWiFiConnectButtonOnPress (ITUWidget * widget, char * param)
Definition at line 120 of file layer_setting_engineer_network_wifi.c.
References ITUListBoxTag::focusIndex, gnApSecurity, i, itcTreeGetChildAt, ituWidgetGetCustomData, nApCount, pList, Config::secumode, settingEngineerNetworkWiFiShowPasswordDialog, Config::ssid, ITUText::string, ITUScrollText::text, and theConfig.
bool SettingEngineerNetworkWiFiDisconnectButtonOnPress (ITUWidget * widget, char * param)
Definition at line 230 of file layer_setting_engineer_network_wifi.c.
References ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituWidgetGetCustomData, Config::ssid, ITUText::string, ITUScrollText::text, and theConfig.
bool SettingEngineerNetworkWiFiNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 20 of file layer_setting_engineer_network_wifi.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, nApCount, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, pList, and ITCTreeTag::sibling.
bool SettingEngineerNetworkWiFiOnEnter (ITUWidget * widget, char * param)
Definition at line 270 of file layer_setting_engineer_network_wifi.c.
References ituSceneFindWidget(), settingEngineerNetworkWiFiShowPasswordDialog, and theScene.
bool SettingEngineerNetworkWiFiOnTimer (ITUWidget * widget, char * param)
Definition at line 244 of file layer_setting_engineer_network_wifi.c.
References ConfigSave(), gnApSecurity, i, ituWidgetDisable, Config::password, Config::secumode, SettingEngineerNetworkWiFiPasswordCallback(), SettingEngineerNetworkWiFiPasswordShow(), settingEngineerNetworkWiFiShowPasswordDialog, Config::ssid, and theConfig.
static void SettingEngineerNetworkWiFiPasswordCallback (char * password) static
Definition at line 176 of file layer_setting_engineer_network_wifi.c.
References ConfigSave(), ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituWidgetGetCustomData, nApCount, Config::password, pList, Config::secumode, Config::ssid, ITUText::string, ITUScrollText::text, and theConfig.
Referenced by SettingEngineerNetworkWiFiOnTimer().
void SettingEngineerNetworkWiFiReset (void)
Definition at line 287 of file layer_setting_engineer_network_wifi.c.
Referenced by resetScene().
bool SettingEngineerNetworkWiFiStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 73 of file layer_setting_engineer_network_wifi.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
Variable Documentation
int gnApSecurity static
Definition at line 17 of file layer_setting_engineer_network_wifi.c.
Referenced by SettingEngineerNetworkWiFiConnectButtonOnPress(), and SettingEngineerNetworkWiFiOnTimer().
int nApCount static
Definition at line 16 of file layer_setting_engineer_network_wifi.c.
Referenced by SettingEngineerNetworkWiFiConnectButtonOnPress(), SettingEngineerNetworkWiFiNameListBoxOnLoad(), and SettingEngineerNetworkWiFiPasswordCallback().
WIFI_MGR_SCANAP_LIST pList[64] static
Definition at line 15 of file layer_setting_engineer_network_wifi.c.
Referenced by SettingEngineerNetworkWiFiConnectButtonOnPress(), SettingEngineerNetworkWiFiNameListBoxOnLoad(), and SettingEngineerNetworkWiFiPasswordCallback().
ITULayer* settingEngineerNetworkWiFiLayer static
Definition at line 11 of file layer_setting_engineer_network_wifi.c.
ITUListBox* settingEngineerNetworkWiFiNameListBox static
Definition at line 12 of file layer_setting_engineer_network_wifi.c.
bool settingEngineerNetworkWiFiShowPasswordDialog static
Definition at line 14 of file layer_setting_engineer_network_wifi.c.
Referenced by SettingEngineerNetworkWiFiConnectButtonOnPress(), SettingEngineerNetworkWiFiOnEnter(), and SettingEngineerNetworkWiFiOnTimer().
ITUListBox* settingEngineerNetworkWiFiStatusListBox static
Definition at line 13 of file layer_setting_engineer_network_wifi.c.