ITE SoC SDK: layer_house_mode.c File Reference
layer_house_mode.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
Macros
#define MAX_MODE_COUNT 10
Functions
bool HouseModeIndoorRadioBoxOnPress (ITUWidget *widget, char *param)
bool HouseModeOutdoorRadioBoxOnPress (ITUWidget *widget, char *param)
bool HouseModeSleepRadioBoxOnPress (ITUWidget *widget, char *param)
bool HouseModeNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseModeStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseModeStatusListBoxOnSelection (ITUWidget *widget, char *param)
bool HouseModeIndoorButtonOnPress (ITUWidget *widget, char *param)
bool HouseModeOutdoorButtonOnPress (ITUWidget *widget, char *param)
bool HouseModeSleepButtonOnPress (ITUWidget *widget, char *param)
bool HouseModeSettingSaveButtonOnPress (ITUWidget *widget, char *param)
bool HouseModeOnEnter (ITUWidget *widget, char *param)
bool HouseModeOnLeave (ITUWidget *widget, char *param)
void HouseModeReset (void)
Variables
static ITURadioBox * houseModeIndoorRadioBox
static ITURadioBox * houseModeOutdoorRadioBox
static ITURadioBox * houseModeSleepRadioBox
static ITUText * houseModeSettingLabelText
static HouseInfo houseModeInfoArray [MAX_MODE_COUNT]
static HouseMode houseMode
static HouseMode houseModeOld
static int houseModeCount
Macro Definition Documentation
#define MAX_MODE_COUNT 10
Definition at line 8 of file layer_house_mode.c.
Referenced by HouseModeIndoorButtonOnPress(), HouseModeOutdoorButtonOnPress(), and HouseModeSleepButtonOnPress().
Function Documentation
bool HouseModeIndoorButtonOnPress (ITUWidget * widget, char * param)
Definition at line 188 of file layer_house_mode.c.
References HOUSE_AIRCONDITIONER, HOUSE_CURTAIN, HOUSE_INDOOR, Config::house_indoor_airconditioners, Config::house_indoor_curtains, Config::house_indoor_lights, Config::house_indoor_plugs, Config::house_indoor_tvs, HOUSE_LIGHT, HOUSE_OFF, HOUSE_ON, HOUSE_PLUG, HOUSE_TV, HouseGetInfoArray(), houseMode, houseModeCount, i, ituTextSetString, MAX_MODE_COUNT, HouseInfo::status, StringGetHouseMode(), and theConfig.
bool HouseModeIndoorRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 19 of file layer_house_mode.c.
References HOUSE_INDOOR, Config::house_mode, HOUSE_NONE, HouseSetMode(), ituRadioBoxSetChecked(), and theConfig.
bool HouseModeNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 67 of file layer_house_mode.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, houseModeCount, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseModeOnEnter (ITUWidget * widget, char * param)
Definition at line 565 of file layer_house_mode.c.
References HOUSE_INDOOR, Config::house_mode, HOUSE_NONE, HOUSE_OUTDOOR, HOUSE_SLEEP, houseModeCount, houseModeOld, ituRadioBoxSetChecked(), ituSceneFindWidget(), theConfig, and theScene.
bool HouseModeOnLeave (ITUWidget * widget, char * param)
Definition at line 606 of file layer_house_mode.c.
References ConfigSave(), Config::house_mode, houseModeOld, and theConfig.
bool HouseModeOutdoorButtonOnPress (ITUWidget * widget, char * param)
Definition at line 254 of file layer_house_mode.c.
References HOUSE_AIRCONDITIONER, HOUSE_CURTAIN, HOUSE_LIGHT, HOUSE_OFF, HOUSE_ON, HOUSE_OUTDOOR, Config::house_outdoor_airconditioners, Config::house_outdoor_curtains, Config::house_outdoor_lights, Config::house_outdoor_plugs, Config::house_outdoor_tvs, HOUSE_PLUG, HOUSE_TV, HouseGetInfoArray(), houseMode, houseModeCount, i, ituTextSetString, MAX_MODE_COUNT, HouseInfo::status, StringGetHouseMode(), and theConfig.
bool HouseModeOutdoorRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 35 of file layer_house_mode.c.
References Config::house_mode, HOUSE_NONE, HOUSE_OUTDOOR, HouseSetMode(), ituRadioBoxSetChecked(), and theConfig.
void HouseModeReset (void)
Definition at line 614 of file layer_house_mode.c.
Referenced by resetScene().
bool HouseModeSettingSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 386 of file layer_house_mode.c.
References ConfigSave(), HOUSE_AIRCONDITIONER, HOUSE_CURTAIN, HOUSE_INDOOR, Config::house_indoor_airconditioners, Config::house_indoor_curtains, Config::house_indoor_lights, Config::house_indoor_plugs, Config::house_indoor_tvs, HOUSE_LIGHT, HOUSE_ON, HOUSE_OUTDOOR, Config::house_outdoor_airconditioners, Config::house_outdoor_curtains, Config::house_outdoor_lights, Config::house_outdoor_plugs, Config::house_outdoor_tvs, HOUSE_PLUG, HOUSE_SLEEP, Config::house_sleep_airconditioners, Config::house_sleep_curtains, Config::house_sleep_lights, Config::house_sleep_plugs, Config::house_sleep_tvs, HOUSE_TV, houseMode, houseModeCount, i, and theConfig.
bool HouseModeSleepButtonOnPress (ITUWidget * widget, char * param)
Definition at line 320 of file layer_house_mode.c.
References HOUSE_AIRCONDITIONER, HOUSE_CURTAIN, HOUSE_LIGHT, HOUSE_OFF, HOUSE_ON, HOUSE_PLUG, HOUSE_SLEEP, Config::house_sleep_airconditioners, Config::house_sleep_curtains, Config::house_sleep_lights, Config::house_sleep_plugs, Config::house_sleep_tvs, HOUSE_TV, HouseGetInfoArray(), houseMode, houseModeCount, i, ituTextSetString, MAX_MODE_COUNT, HouseInfo::status, StringGetHouseMode(), and theConfig.
bool HouseModeSleepRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 51 of file layer_house_mode.c.
References Config::house_mode, HOUSE_NONE, HOUSE_SLEEP, HouseSetMode(), ituRadioBoxSetChecked(), and theConfig.
bool HouseModeStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 116 of file layer_house_mode.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, houseModeCount, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
bool HouseModeStatusListBoxOnSelection (ITUWidget * widget, char * param)
Definition at line 168 of file layer_house_mode.c.
References ITUListBoxTag::focusIndex, HOUSE_OFF, HOUSE_ON, itcTreeGetChildAt, ituListBoxSelect(), ituTextSetString, ituWidgetGetCustomData, HouseInfo::status, and StringGetHouseStatus().
Variable Documentation
HouseMode houseMode static
Definition at line 16 of file layer_house_mode.c.
Referenced by HouseModeIndoorButtonOnPress(), HouseModeOutdoorButtonOnPress(), HouseModeSettingSaveButtonOnPress(), and HouseModeSleepButtonOnPress().
int houseModeCount static
Definition at line 17 of file layer_house_mode.c.
Referenced by HouseModeIndoorButtonOnPress(), HouseModeNameListBoxOnLoad(), HouseModeOnEnter(), HouseModeOutdoorButtonOnPress(), HouseModeSettingSaveButtonOnPress(), HouseModeSleepButtonOnPress(), and HouseModeStatusListBoxOnLoad().
ITURadioBox* houseModeIndoorRadioBox static
Definition at line 10 of file layer_house_mode.c.
HouseInfo houseModeInfoArray[MAX_MODE_COUNT] static
Definition at line 15 of file layer_house_mode.c.
HouseMode houseModeOld static
Definition at line 16 of file layer_house_mode.c.
Referenced by HouseModeOnEnter(), and HouseModeOnLeave().
ITURadioBox* houseModeOutdoorRadioBox static
Definition at line 11 of file layer_house_mode.c.
ITUText* houseModeSettingLabelText static
Definition at line 13 of file layer_house_mode.c.
ITURadioBox* houseModeSleepRadioBox static
Definition at line 12 of file layer_house_mode.c.