ITE SoC SDK: layer_guard_mode.c File Reference
layer_guard_mode.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool GuardModeIndoorRadioBoxOnPress (ITUWidget *widget, char *param)
bool GuardModeOutdoorRadioBoxOnPress (ITUWidget *widget, char *param)
bool GuardModeSleepRadioBoxOnPress (ITUWidget *widget, char *param)
bool GuardModeStopKeypadConfirmButtonOnPress (ITUWidget *widget, char *param)
bool GuardModeStopKeypadCancelButtonOnPress (ITUWidget *widget, char *param)
bool GuardModeOnEnter (ITUWidget *widget, char *param)
bool GuardModeOnLeave (ITUWidget *widget, char *param)
void GuardModeReset (void)
Variables
static ITURadioBox * guardModeIndoorRadioBox
static ITURadioBox * guardModeOutdoorRadioBox
static ITURadioBox * guardModeSleepRadioBox
static ITURadioBox * guardModeStopRadioBox
static ITUTextBox * guardModeStopKeypadTextBox
static GuardMode guardModeOld
Function Documentation
bool GuardModeIndoorRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 16 of file layer_guard_mode.c.
References GUARD_INDOOR, Config::guard_mode, GuardIsAlarming(), GuardSetMode(), and theConfig.
bool GuardModeOnEnter (ITUWidget * widget, char * param)
Definition at line 108 of file layer_guard_mode.c.
References GUARD_INDOOR, Config::guard_mode, GUARD_NONE, GUARD_OUTDOOR, GUARD_SLEEP, GuardIsAlarming(), guardModeOld, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituWidgetDisable, theConfig, and theScene.
bool GuardModeOnLeave (ITUWidget * widget, char * param)
Definition at line 177 of file layer_guard_mode.c.
References ConfigSave(), Config::guard_mode, guardModeOld, and theConfig.
bool GuardModeOutdoorRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 29 of file layer_guard_mode.c.
References Config::guard_mode, GUARD_OUTDOOR, GuardIsAlarming(), GuardSetMode(), and theConfig.
void GuardModeReset (void)
Definition at line 184 of file layer_guard_mode.c.
Referenced by resetScene().
bool GuardModeSleepRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 43 of file layer_guard_mode.c.
References Config::guard_mode, GUARD_SLEEP, GuardIsAlarming(), GuardSetMode(), and theConfig.
bool GuardModeStopKeypadCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 89 of file layer_guard_mode.c.
References GUARD_INDOOR, Config::guard_mode, GUARD_OUTDOOR, GUARD_SLEEP, ituRadioBoxSetChecked(), and theConfig.
bool GuardModeStopKeypadConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 56 of file layer_guard_mode.c.
References GUARD_INDOOR, Config::guard_mode, GUARD_NONE, GUARD_OUTDOOR, Config::guard_password, GUARD_SLEEP, GuardSetMode(), ituRadioBoxSetChecked(), ituTextGetString, ituWidgetEnable, and theConfig.
Variable Documentation
ITURadioBox* guardModeIndoorRadioBox static
Definition at line 8 of file layer_guard_mode.c.
GuardMode guardModeOld static
Definition at line 14 of file layer_guard_mode.c.
Referenced by GuardModeOnEnter(), and GuardModeOnLeave().
ITURadioBox* guardModeOutdoorRadioBox static
Definition at line 9 of file layer_guard_mode.c.
ITURadioBox* guardModeSleepRadioBox static
Definition at line 10 of file layer_guard_mode.c.
ITUTextBox* guardModeStopKeypadTextBox static
Definition at line 12 of file layer_guard_mode.c.
ITURadioBox* guardModeStopRadioBox static
Definition at line 11 of file layer_guard_mode.c.