ITE SoC SDK: layer_message_record.c File Reference
layer_message_record.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
Functions
bool MessageRecordIconListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageRecordTopicListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageRecordTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool MessageRecordViewButtonOnPress (ITUWidget *widget, char *param)
bool MessageRecordDeleteOnPress (ITUWidget *widget, char *param)
bool MessageRecordDeleteConfirmOnPress (ITUWidget *widget, char *param)
bool MessageRecordOnEnter (ITUWidget *widget, char *param)
void MessageRecordReset (void)
Variables
static ITUListBox * messageRecordTopicListBox
static ITUListBox * messageRecordTimeListBox
static ITUListBox * messageRecordIconListBox
Function Documentation
bool MessageRecordDeleteConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 207 of file layer_message_record.c.
References CaptureDeleteEntry(), CaptureGetEntry(), CaptureGetUnplayCount(), CaptureSnapshotDeleteEntry(), ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituListBoxReload(), ituWidgetGetCustomData, MEDIA_IMAGE, MessageNotifyUnreadRecordMessage(), and CaptureEntry::type.
bool MessageRecordDeleteOnPress (ITUWidget * widget, char * param)
Definition at line 199 of file layer_message_record.c.
References ITUListBoxTag::focusIndex.
bool MessageRecordIconListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 12 of file layer_message_record.c.
References CaptureGetCount(), CaptureGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and CaptureEntry::type.
bool MessageRecordOnEnter (ITUWidget * widget, char * param)
Definition at line 231 of file layer_message_record.c.
References ituListBoxReload(), ituSceneFindWidget(), MessageRecordTimeListBoxOnLoad(), MessageRecordTopicListBoxOnLoad(), and theScene.
void MessageRecordReset (void)
Definition at line 259 of file layer_message_record.c.
Referenced by resetScene().
bool MessageRecordTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 120 of file layer_message_record.c.
References CaptureGetCount(), CaptureGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, CaptureEntry::played, CaptureEntry::sec, and ITCTreeTag::sibling.
Referenced by MessageRecordOnEnter().
bool MessageRecordTopicListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 64 of file layer_message_record.c.
References CaptureGetCount(), CaptureGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, CaptureEntry::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, CaptureEntry::played, and ITCTreeTag::sibling.
Referenced by MessageRecordOnEnter().
bool MessageRecordViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 185 of file layer_message_record.c.
References CaptureGetEntry(), ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, MessageRecordViewShow(), and ITUScrollText::text.
Variable Documentation
ITUListBox* messageRecordIconListBox static
Definition at line 10 of file layer_message_record.c.
ITUListBox* messageRecordTimeListBox static
Definition at line 9 of file layer_message_record.c.
ITUListBox* messageRecordTopicListBox static
Definition at line 8 of file layer_message_record.c.