ITE SoC SDK: layer_setting_phone_disturb.c File Reference
layer_setting_phone_disturb.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ite/itp.h"
#include "scene.h"
#include "doorbell.h"
Functions
bool SettingPhoneDisturbTimeRadioBoxOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbSaveButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeTextBoxOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeUpButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeDownButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeCancelButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbTimeConfirmButtonOnPress (ITUWidget *widget, char *param)
bool SettingPhoneDisturbOnEnter (ITUWidget *widget, char *param)
void SettingPhoneDisturbReset (void)
Variables
static ITUBackground * settingPhoneDisturbBackground
static ITURadioBox * settingPhoneDisturbNormalRadioBox
static ITURadioBox * settingPhoneDisturbLocalMuteRadioBox
static ITURadioBox * settingPhoneDisturbAllRadioBox
static ITURadioBox * settingPhoneDisturbTimeRadioBox
static ITUBackground * settingPhoneDisturbOptions0
static ITUBackground * settingPhoneDisturbOptions1
static ITUBackground * settingPhoneDisturbOptions2
static ITUWidget * settingPhoneDisturbOptionContainer
static ITURadioBox * settingPhoneDisturbHangUpRadioBox
static ITURadioBox * settingPhoneDisturbVoiceMemoRadioBox
static ITURadioBox * settingPhoneDisturbMessageRadioBox
static ITURadioBox * settingPhoneDisturbTransferRadioBox
static ITUButton * settingPhoneDisturbSaveButton
static ITUButton * settingPhoneDisturbCancelButton
static ITUBackground * settingPhoneDisturbTimeBackground
static ITUTextBox * settingPhoneDisturbTimeStartHourTextBox
static ITUTextBox * settingPhoneDisturbTimeStartMinuteTextBox
static ITUTextBox * settingPhoneDisturbTimeEndHourTextBox
static ITUTextBox * settingPhoneDisturbTimeEndMinuteTextBox
static ITUTextBox * activeSettingPhoneDisturbTimeTextBox
Function Documentation
bool SettingPhoneDisturbCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 129 of file layer_setting_phone_disturb.c.
References Config::do_not_disturb_mode, Config::do_not_disturb_option, DONOT_DISTURB_ALL, DONOT_DISTURB_HANGUP, DONOT_DISTURB_MESSAGE, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_REDIRECT, DONOT_DISTURB_TIME, DONOT_DISTURB_VOICEMEMO, ituRadioBoxSetChecked(), ituWidgetSetVisible, and theConfig.
bool SettingPhoneDisturbOnEnter (ITUWidget * widget, char * param)
Definition at line 264 of file layer_setting_phone_disturb.c.
References Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_mode, Config::do_not_disturb_option, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, DONOT_DISTURB_ALL, DONOT_DISTURB_HANGUP, DONOT_DISTURB_MESSAGE, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_REDIRECT, DONOT_DISTURB_TIME, DONOT_DISTURB_VOICEMEMO, DeviceInfo::ext, ituRadioBoxSetChecked(), ituSceneFindWidget(), ituTextBoxSetString(), ituWidgetSetVisible, theConfig, theDeviceInfo, and theScene.
void SettingPhoneDisturbReset (void)
Definition at line 382 of file layer_setting_phone_disturb.c.
Referenced by resetScene().
bool SettingPhoneDisturbSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 40 of file layer_setting_phone_disturb.c.
References AudioMute(), AudioUnMute(), ConfigSave(), Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_mode, Config::do_not_disturb_option, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, DONOT_DISTURB_ALL, DONOT_DISTURB_HANGUP, DONOT_DISTURB_MESSAGE, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_REDIRECT, DONOT_DISTURB_TIME, DONOT_DISTURB_VOICEMEMO, EVENT_CUSTOM_DISTURB_MODE, DeviceInfo::ext, GuardIsAlarming(), ituRadioBoxIsChecked(), ituRadioBoxSetChecked(), ituSceneSendEvent(), ituTextBoxGetString(), LinphoneDisableDoNotDisturb(), LinphoneEnableDoNotDisturb(), RemoteSetDontDisturbConfig(), SceneSetLastDoNotDisturbMode(), theConfig, theDeviceInfo, and theScene.
bool SettingPhoneDisturbTimeCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 226 of file layer_setting_phone_disturb.c.
References Config::do_not_disturb_end_hour, Config::do_not_disturb_end_min, Config::do_not_disturb_start_hour, Config::do_not_disturb_start_min, ituTextBoxSetString(), ituWidgetEnable, ituWidgetSetVisible, and theConfig.
bool SettingPhoneDisturbTimeConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 244 of file layer_setting_phone_disturb.c.
References ituRadioBoxSetChecked(), ituTextBoxGetString(), ituWidgetEnable, and ituWidgetSetVisible.
bool SettingPhoneDisturbTimeDownButtonOnPress (ITUWidget * widget, char * param)
Definition at line 203 of file layer_setting_phone_disturb.c.
References ituTextBoxGetString(), and ituTextBoxSetString().
bool SettingPhoneDisturbTimeRadioBoxOnPress (ITUWidget * widget, char * param)
Definition at line 32 of file layer_setting_phone_disturb.c.
References ituWidgetDisable, ituWidgetSetVisible, and settingPhoneDisturbTimeStartHourTextBox.
bool SettingPhoneDisturbTimeTextBoxOnPress (ITUWidget * widget, char * param)
Definition at line 174 of file layer_setting_phone_disturb.c.
bool SettingPhoneDisturbTimeUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 180 of file layer_setting_phone_disturb.c.
References ituTextBoxGetString(), and ituTextBoxSetString().
Variable Documentation
ITUTextBox* activeSettingPhoneDisturbTimeTextBox static
Definition at line 30 of file layer_setting_phone_disturb.c.
ITURadioBox* settingPhoneDisturbAllRadioBox static
Definition at line 12 of file layer_setting_phone_disturb.c.
ITUBackground* settingPhoneDisturbBackground static
Definition at line 9 of file layer_setting_phone_disturb.c.
ITUButton* settingPhoneDisturbCancelButton static
Definition at line 23 of file layer_setting_phone_disturb.c.
ITURadioBox* settingPhoneDisturbHangUpRadioBox static
Definition at line 18 of file layer_setting_phone_disturb.c.
ITURadioBox* settingPhoneDisturbLocalMuteRadioBox static
Definition at line 11 of file layer_setting_phone_disturb.c.
ITURadioBox* settingPhoneDisturbMessageRadioBox static
Definition at line 20 of file layer_setting_phone_disturb.c.
ITURadioBox* settingPhoneDisturbNormalRadioBox static
Definition at line 10 of file layer_setting_phone_disturb.c.
ITUWidget* settingPhoneDisturbOptionContainer static
Definition at line 17 of file layer_setting_phone_disturb.c.
ITUBackground* settingPhoneDisturbOptions0 static
Definition at line 14 of file layer_setting_phone_disturb.c.
ITUBackground* settingPhoneDisturbOptions1 static
Definition at line 15 of file layer_setting_phone_disturb.c.
ITUBackground* settingPhoneDisturbOptions2 static
Definition at line 16 of file layer_setting_phone_disturb.c.
ITUButton* settingPhoneDisturbSaveButton static
Definition at line 22 of file layer_setting_phone_disturb.c.
ITUBackground* settingPhoneDisturbTimeBackground static
Definition at line 24 of file layer_setting_phone_disturb.c.
ITUTextBox* settingPhoneDisturbTimeEndHourTextBox static
Definition at line 27 of file layer_setting_phone_disturb.c.
ITUTextBox* settingPhoneDisturbTimeEndMinuteTextBox static
Definition at line 28 of file layer_setting_phone_disturb.c.
ITURadioBox* settingPhoneDisturbTimeRadioBox static
Definition at line 13 of file layer_setting_phone_disturb.c.
ITUTextBox* settingPhoneDisturbTimeStartHourTextBox static
Definition at line 25 of file layer_setting_phone_disturb.c.
Referenced by SettingPhoneDisturbTimeRadioBoxOnPress().
ITUTextBox* settingPhoneDisturbTimeStartMinuteTextBox static
Definition at line 26 of file layer_setting_phone_disturb.c.
ITURadioBox* settingPhoneDisturbTransferRadioBox static
Definition at line 21 of file layer_setting_phone_disturb.c.
ITURadioBox* settingPhoneDisturbVoiceMemoRadioBox static
Definition at line 19 of file layer_setting_phone_disturb.c.