ITE SoC SDK: layer_guard_log.c File Reference
layer_guard_log.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "doorbell.h"
#include "scene.h"
Functions
bool GuardLogSensorListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardLogTypeListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardLogTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool GuardLogDeleteOnPress (ITUWidget *widget, char *param)
static void GuardLogReload (int arg)
bool GuardLogDeleteConfirmOnPress (ITUWidget *widget, char *param)
bool GuardLogDeleteButtonOnPress (ITUWidget *widget, char *param)
bool GuardLogClearConfirmOnPress (ITUWidget *widget, char *param)
bool GuardLogOnEnter (ITUWidget *widget, char *param)
void GuardLogReset (void)
Variables
static ITUListBox * guardLogSensorListBox
static ITUListBox * guardLogTypeListBox
static ITUListBox * guardLogTimeListBox
Function Documentation
bool GuardLogClearConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 215 of file layer_guard_log.c.
References GuardClearLog(), GuardLogReload(), ituSceneExecuteCommand(), and theScene.
bool GuardLogDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 205 of file layer_guard_log.c.
References ITUListBoxTag::focusIndex.
bool GuardLogDeleteConfirmOnPress (ITUWidget * widget, char * param)
Definition at line 192 of file layer_guard_log.c.
References ITUListBoxTag::focusIndex, GuardDeleteLog(), GuardLogReload(), i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, and theScene.
bool GuardLogDeleteOnPress (ITUWidget * widget, char * param)
Definition at line 177 of file layer_guard_log.c.
References ITUListBoxTag::focusIndex.
bool GuardLogOnEnter (ITUWidget * widget, char * param)
Definition at line 222 of file layer_guard_log.c.
References ituSceneFindWidget(), and theScene.
static void GuardLogReload (int arg) static
Definition at line 185 of file layer_guard_log.c.
References ituListBoxReload().
Referenced by GuardLogClearConfirmOnPress(), and GuardLogDeleteConfirmOnPress().
void GuardLogReset (void)
Definition at line 238 of file layer_guard_log.c.
Referenced by resetScene().
bool GuardLogSensorListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 13 of file layer_guard_log.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GUARD_HANDLED, GuardGetLog(), GuardGetLogCount(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, GuardLog::sensor, ITCTreeTag::sibling, GuardLog::state, StringGetGuardSensor(), StringGetGuardType(), and GuardLog::type.
bool GuardLogTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 121 of file layer_guard_log.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GuardGetLog(), GuardGetLogCount(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and GuardLog::timestamp.
bool GuardLogTypeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 68 of file layer_guard_log.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, GUARD_HANDLED, GuardGetLog(), GuardGetLogCount(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, GuardLog::state, GuardLog::status, StringGetGuardState(), and StringGetGuardStatus().
Variable Documentation
ITUListBox* guardLogSensorListBox static
Definition at line 9 of file layer_guard_log.c.
ITUListBox* guardLogTimeListBox static
Definition at line 11 of file layer_guard_log.c.
ITUListBox* guardLogTypeListBox static
Definition at line 10 of file layer_guard_log.c.