ITE SoC SDK: layer_videorecord.c File Reference
layer_videorecord.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SDL/SDL.h"
#include "scene.h"
#include "doorbell.h"
Functions
bool VideoRecordHangUpButtonOnPress (ITUWidget *widget, char *param)
void VideoRecordIncomingShow (int id, char *addr, int video)
Sets the infomation to the video record screen.
bool VideoRecordOnTimer (ITUWidget *widget, char *param)
bool VideoRecordOnEnter (ITUWidget *widget, char *param)
bool VideoRecordOnLeave (ITUWidget *widget, char *param)
void VideoRecordReset (void)
Variables
static ITULayer * mainVoiceMemoLayer
static ITUBackground * videoRecordRemoteBackground
static ITUBackground * videoRecordBlackBackground
static ITUText * videoRecordSourceText
static ITUText * videoRecordCountDownText
static bool videoRecordInVideoState
static float videoRecordCountDown
static uint32_t videoRecordLastTick
static int videoRecordID
Function Documentation
bool VideoRecordHangUpButtonOnPress (ITUWidget * widget, char * param)
Definition at line 21 of file layer_videorecord.c.
References ituButtonSetPressed(), LinphoneTerminate(), and SceneHangUp().
bool VideoRecordOnEnter (ITUWidget * widget, char * param)
Definition at line 119 of file layer_videorecord.c.
References ituSceneFindWidget(), LinphoneSetWindowID(), theScene, and videoRecordInVideoState.
bool VideoRecordOnLeave (ITUWidget * widget, char * param)
Definition at line 149 of file layer_videorecord.c.
References VideoMemoStopRecord(), videoRecordID, and videoRecordInVideoState.
bool VideoRecordOnTimer (ITUWidget * widget, char * param)
Definition at line 81 of file layer_videorecord.c.
References font::f, ituLayerGoto(), ituTextSetString, LinphoneTerminate(), SceneHangUp(), videoRecordCountDown, and videoRecordLastTick.
void VideoRecordReset (void)
Definition at line 157 of file layer_videorecord.c.
Referenced by resetScene().
Variable Documentation
ITULayer* mainVoiceMemoLayer static
Definition at line 9 of file layer_videorecord.c.
ITUBackground* videoRecordBlackBackground static
Definition at line 11 of file layer_videorecord.c.
float videoRecordCountDown static
Definition at line 17 of file layer_videorecord.c.
Referenced by VideoRecordIncomingShow(), and VideoRecordOnTimer().
ITUText* videoRecordCountDownText static
Definition at line 13 of file layer_videorecord.c.
int videoRecordID static
Definition at line 19 of file layer_videorecord.c.
Referenced by VideoRecordIncomingShow(), and VideoRecordOnLeave().
bool videoRecordInVideoState static
Definition at line 16 of file layer_videorecord.c.
Referenced by VideoRecordIncomingShow(), VideoRecordOnEnter(), and VideoRecordOnLeave().
uint32_t videoRecordLastTick static
Definition at line 18 of file layer_videorecord.c.
Referenced by VideoRecordIncomingShow(), and VideoRecordOnTimer().
ITUBackground* videoRecordRemoteBackground static
Definition at line 10 of file layer_videorecord.c.
ITUText* videoRecordSourceText static
Definition at line 12 of file layer_videorecord.c.