ITE SoC SDK: layer_phone_log_received.c File Reference
layer_phone_log_received.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool PhoneLogReceivedRoomListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogReceivedTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogReceivedDurationListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogReceivedCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedAddButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedViewButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedDeleteButtonOnPress (ITUWidget *widget, char *param)
static void PhoneLogReceivedReload (int arg)
bool PhoneLogReceivedDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedClearConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogReceivedOnEnter (ITUWidget *widget, char *param)
void PhoneLogReceivedReset (void)
Variables
static ITULayer * phoneLogReceivedLayer
static ITUListBox * phoneLogReceivedRoomListBox
static ITUListBox * phoneLogReceivedTimeListBox
static ITUListBox * phoneLogReceivedDurationListBox
Function Documentation
bool PhoneLogReceivedAddButtonOnPress (ITUWidget * widget, char * param)
Definition at line 185 of file layer_phone_log_received.c.
References AddressBookGetDeviceInfo(), CALLLOG_RECEIVED, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, and PhoneContactsAddShow().
bool PhoneLogReceivedCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 169 of file layer_phone_log_received.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CallingCall(), CALLLOG_RECEIVED, CallLogGetEntry(), DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, DeviceInfo::room, DeviceInfo::type, and DeviceInfo::unit.
bool PhoneLogReceivedClearConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 252 of file layer_phone_log_received.c.
References CALLLOG_RECEIVED, CallLogClearEntries(), ituSceneExecuteCommand(), PhoneLogReceivedReload(), and theScene.
bool PhoneLogReceivedDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 224 of file layer_phone_log_received.c.
References ITUListBoxTag::focusIndex.
bool PhoneLogReceivedDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 239 of file layer_phone_log_received.c.
References CALLLOG_RECEIVED, CallLogDeleteEntry(), CallLogGetEntry(), ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, PhoneLogReceivedReload(), and theScene.
bool PhoneLogReceivedDurationListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 118 of file layer_phone_log_received.c.
References CALLLOG_RECEIVED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, CallLogEntry::duration, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool PhoneLogReceivedOnEnter (ITUWidget * widget, char * param)
Definition at line 259 of file layer_phone_log_received.c.
References ituSceneFindWidget(), and theScene.
static void PhoneLogReceivedReload (int arg) static
Definition at line 232 of file layer_phone_log_received.c.
References ituListBoxReload().
Referenced by PhoneLogReceivedClearConfirmButtonOnPress(), and PhoneLogReceivedDeleteConfirmButtonOnPress().
void PhoneLogReceivedReset (void)
Definition at line 278 of file layer_phone_log_received.c.
Referenced by resetScene().
bool PhoneLogReceivedRoomListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_phone_log_received.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CALLLOG_RECEIVED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, ITCTreeTag::sibling, StringGetRoomAddress(), and DeviceInfo::unit.
bool PhoneLogReceivedTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 68 of file layer_phone_log_received.c.
References CALLLOG_RECEIVED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and CallLogEntry::time.
bool PhoneLogReceivedViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 201 of file layer_phone_log_received.c.
References AddressBookGetDeviceInfo(), DeviceInfo::alias, CALLLOG_RECEIVED, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, PhoneLogViewShow(), StringGetCallLogType(), ITUScrollText::text, and CallLogEntry::time.
Variable Documentation
ITUListBox* phoneLogReceivedDurationListBox static
Definition at line 11 of file layer_phone_log_received.c.
ITULayer* phoneLogReceivedLayer static
Definition at line 8 of file layer_phone_log_received.c.
ITUListBox* phoneLogReceivedRoomListBox static
Definition at line 9 of file layer_phone_log_received.c.
ITUListBox* phoneLogReceivedTimeListBox static
Definition at line 10 of file layer_phone_log_received.c.