ITE SoC SDK: layer_phone_log_missed.c File Reference
layer_phone_log_missed.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool PhoneLogMissedRoomListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogMissedTimeListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogMissedDurationListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneLogMissedCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedAddButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedViewButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedDeleteButtonOnPress (ITUWidget *widget, char *param)
static void PhoneLogMissedReload (int arg)
bool PhoneLogMissedDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedClearConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneLogMissedOnEnter (ITUWidget *widget, char *param)
void PhoneLogMissedReset (void)
Variables
static ITULayer * phoneLogMissedLayer
static ITULayer * phoneContactsAddLayer
static ITUListBox * phoneLogMissedRoomListBox
static ITUListBox * phoneLogMissedTimeListBox
static ITUListBox * phoneLogMissedDurationListBox
Function Documentation
bool PhoneLogMissedAddButtonOnPress (ITUWidget * widget, char * param)
Definition at line 187 of file layer_phone_log_missed.c.
References AddressBookGetDeviceInfo(), CALLLOG_MISSED, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, and PhoneContactsAddShow().
bool PhoneLogMissedCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 171 of file layer_phone_log_missed.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CallingCall(), CALLLOG_MISSED, CallLogGetEntry(), DEVICE_INDOOR, DEVICE_INDOOR2, DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituWidgetGetCustomData, DeviceInfo::room, DeviceInfo::type, and DeviceInfo::unit.
bool PhoneLogMissedClearConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 254 of file layer_phone_log_missed.c.
References CALLLOG_MISSED, CallLogClearEntries(), ituSceneExecuteCommand(), PhoneLogMissedReload(), and theScene.
bool PhoneLogMissedDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 226 of file layer_phone_log_missed.c.
References ITUListBoxTag::focusIndex.
bool PhoneLogMissedDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 241 of file layer_phone_log_missed.c.
References CALLLOG_MISSED, CallLogDeleteEntry(), CallLogGetEntry(), ITUListBoxTag::focusIndex, i, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, PhoneLogMissedReload(), and theScene.
bool PhoneLogMissedDurationListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 119 of file layer_phone_log_missed.c.
References CALLLOG_MISSED, CallLogGetCount(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool PhoneLogMissedOnEnter (ITUWidget * widget, char * param)
Definition at line 261 of file layer_phone_log_missed.c.
References ituSceneFindWidget(), SceneClearMissedCalls(), and theScene.
static void PhoneLogMissedReload (int arg) static
Definition at line 234 of file layer_phone_log_missed.c.
References ituListBoxReload().
Referenced by PhoneLogMissedClearConfirmButtonOnPress(), and PhoneLogMissedDeleteConfirmButtonOnPress().
void PhoneLogMissedReset (void)
Definition at line 285 of file layer_phone_log_missed.c.
Referenced by resetScene().
bool PhoneLogMissedRoomListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 15 of file layer_phone_log_missed.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, DeviceInfo::building, CALLLOG_MISSED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, DeviceInfo::floor, ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, ITCTreeTag::sibling, StringGetRoomAddress(), and DeviceInfo::unit.
bool PhoneLogMissedTimeListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 69 of file layer_phone_log_missed.c.
References CALLLOG_MISSED, CallLogGetCount(), CallLogGetEntry(), ITCTreeTag::child, ITUListBoxTag::focusIndex, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, and CallLogEntry::time.
bool PhoneLogMissedViewButtonOnPress (ITUWidget * widget, char * param)
Definition at line 203 of file layer_phone_log_missed.c.
References AddressBookGetDeviceInfo(), DeviceInfo::alias, CALLLOG_MISSED, CallLogGetEntry(), ITUListBoxTag::focusIndex, i, CallLogEntry::ip, itcTreeGetChildAt, ituTextGetString, ituWidgetGetCustomData, PhoneLogViewShow(), StringGetCallLogType(), ITUScrollText::text, and CallLogEntry::time.
Variable Documentation
ITULayer* phoneContactsAddLayer static
Definition at line 9 of file layer_phone_log_missed.c.
ITUListBox* phoneLogMissedDurationListBox static
Definition at line 12 of file layer_phone_log_missed.c.
ITULayer* phoneLogMissedLayer static
Definition at line 8 of file layer_phone_log_missed.c.
ITUListBox* phoneLogMissedRoomListBox static
Definition at line 10 of file layer_phone_log_missed.c.
ITUListBox* phoneLogMissedTimeListBox static
Definition at line 11 of file layer_phone_log_missed.c.