ITE SoC SDK: layer_house_curtain.c File Reference
layer_house_curtain.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
#include "ite/itp.h"
Functions
bool HouseCurtainNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseCurtainStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseCurtainOnButtonOnPress (ITUWidget *widget, char *param)
bool HouseCurtainOffButtonOnPress (ITUWidget *widget, char *param)
bool HouseCurtainStopButtonOnPress (ITUWidget *widget, char *param)
bool HouseCurtainOnEnter (ITUWidget *widget, char *param)
void HouseCurtainReset (void)
Variables
static ITUSprite * houseCurtainSprite
static ITUListBox * houseCurtainNameListBox
static HouseInfo houseCurtainInfoArray [HOUSE_MAX_CURTAIN_COUNT]
Function Documentation
bool HouseCurtainNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_house_curtain.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_CURTAIN, HOUSE_MAX_CURTAIN_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseCurtainOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 136 of file layer_house_curtain.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_CURTAIN, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpritePlay(), and ituWidgetGetCustomData.
bool HouseCurtainOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 113 of file layer_house_curtain.c.
References ITUListBoxTag::focusIndex, HOUSE_CURTAIN, HOUSE_OPEN, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpritePlay(), and ituWidgetGetCustomData.
bool HouseCurtainOnEnter (ITUWidget * widget, char * param)
Definition at line 172 of file layer_house_curtain.c.
References ituSceneFindWidget(), and theScene.
void HouseCurtainReset (void)
Definition at line 185 of file layer_house_curtain.c.
Referenced by resetScene().
bool HouseCurtainStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 63 of file layer_house_curtain.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_CURTAIN, HOUSE_MAX_CURTAIN_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
bool HouseCurtainStopButtonOnPress (ITUWidget * widget, char * param)
Definition at line 159 of file layer_house_curtain.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_CURTAIN, HouseExecAction(), itcTreeGetChildAt, ituSpriteStop(), and ituWidgetGetCustomData.
Variable Documentation
HouseInfo houseCurtainInfoArray[HOUSE_MAX_CURTAIN_COUNT] static
Definition at line 12 of file layer_house_curtain.c.
ITUListBox* houseCurtainNameListBox static
Definition at line 10 of file layer_house_curtain.c.
ITUSprite* houseCurtainSprite static
Definition at line 9 of file layer_house_curtain.c.