ITE SoC SDK: layer_house_airconditioner.c File Reference
layer_house_airconditioner.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
#include "ite/itp.h"
Functions
bool HouseAirConditionerNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseAirConditionerStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseAirConditionerOnButtonOnPress (ITUWidget *widget, char *param)
bool HouseAirConditionerOffButtonOnPress (ITUWidget *widget, char *param)
bool HouseAirConditionerOnEnter (ITUWidget *widget, char *param)
void HouseAirConditionerReset (void)
Variables
static ITUSprite * houseAirConditionerSprite
static ITUListBox * houseAirConditionerNameListBox
static HouseInfo houseAirConditionerInfoArray [HOUSE_MAX_AIRCONDITIONER_COUNT]
Function Documentation
bool HouseAirConditionerNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_house_airconditioner.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_AIRCONDITIONER, HOUSE_MAX_AIRCONDITIONER_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseAirConditionerOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 136 of file layer_house_airconditioner.c.
References ITUListBoxTag::focusIndex, HOUSE_AIRCONDITIONER, HOUSE_CLOSE, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseAirConditionerOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 113 of file layer_house_airconditioner.c.
References ITUListBoxTag::focusIndex, HOUSE_AIRCONDITIONER, HOUSE_OPEN, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseAirConditionerOnEnter (ITUWidget * widget, char * param)
Definition at line 160 of file layer_house_airconditioner.c.
References ituSceneFindWidget(), and theScene.
void HouseAirConditionerReset (void)
Definition at line 174 of file layer_house_airconditioner.c.
Referenced by resetScene().
bool HouseAirConditionerStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 63 of file layer_house_airconditioner.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_AIRCONDITIONER, HOUSE_MAX_AIRCONDITIONER_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
Variable Documentation
HouseInfo houseAirConditionerInfoArray[HOUSE_MAX_AIRCONDITIONER_COUNT] static
Definition at line 12 of file layer_house_airconditioner.c.
ITUListBox* houseAirConditionerNameListBox static
Definition at line 10 of file layer_house_airconditioner.c.
ITUSprite* houseAirConditionerSprite static
Definition at line 9 of file layer_house_airconditioner.c.