ITE SoC SDK: layer_camera_outdoor.c File Reference
layer_camera_outdoor.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SDL/SDL.h"
#include "scene.h"
#include "doorbell.h"
Macros
#define CAMERA_TIMEOUT (30.999f)
#define SNAPSHOT_COUNT (1 * 1000 / 33)
Functions
bool CameraOutdoorButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorRecordButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorStopRecordButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorUnlockButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorSnapshotButtonOnPress (ITUWidget *widget, char *param)
bool CameraOutdoorOnTimer (ITUWidget *widget, char *param)
bool CameraOutdoorOnEnter (ITUWidget *widget, char *param)
bool CameraOutdoorOnLeave (ITUWidget *widget, char *param)
void CameraOutdoorReset (void)
Variables
static ITUBackground * cameraOutdoorBackground
static ITUText * cameraOutdoorSourceText
static ITUText * cameraOutdoorCountDownText
static float cameraOutdoorCountDown
static float LockRecordButtonCountDown
static uint32_t cameraOutdoorLastTick
static uint32_t LockRecordButtonLastTick
static int snapshotCountDown
static bool cameraOutdoorVideoRecordEnable
static bool LockRecordButton
Macro Definition Documentation
#define CAMERA_TIMEOUT (30.999f)
Definition at line 9 of file layer_camera_outdoor.c.
Referenced by CameraOutdoorOnEnter().
#define SNAPSHOT_COUNT (1 * 1000 / 33)
Definition at line 21 of file layer_camera_outdoor.c.
Referenced by CameraOutdoorSnapshotButtonOnPress().
Function Documentation
bool CameraOutdoorButtonOnPress (ITUWidget * widget, char * param)
Definition at line 23 of file layer_camera_outdoor.c.
References ituSceneFindWidget(), LinphoneSetWindowID(), and theScene.
bool CameraOutdoorOnEnter (ITUWidget * widget, char * param)
Definition at line 133 of file layer_camera_outdoor.c.
References DeviceInfo::alias, DeviceInfo::area, DeviceInfo::building, CAMERA_TIMEOUT, cameraOutdoorCountDown, cameraOutdoorLastTick, cameraOutdoorVideoRecordEnable, CaptureGetPath(), DEVICE_INDOOR2, DeviceInfo::ip, ituSceneFindWidget(), ituTextSetString, LinphoneSetWindowID(), LinphoneWatchCamera(), SceneCameraSetViewing(), SceneSetRemoteIP(), snapshotCountDown, StringGetCameraPosition(), theDeviceInfo, theEntranceInfo, theScene, DeviceInfo::type, and DeviceInfo::unit.
bool CameraOutdoorOnLeave (ITUWidget * widget, char * param)
Definition at line 186 of file layer_camera_outdoor.c.
References cameraOutdoorCountDown, cameraOutdoorVideoRecordEnable, CaptureStopRecord(), LinphoneStopCamera(), SceneCameraSetViewing(), and SceneContinuePlayGuardAlarm().
bool CameraOutdoorOnTimer (ITUWidget * widget, char * param)
Definition at line 73 of file layer_camera_outdoor.c.
References cameraOutdoorCountDown, cameraOutdoorLastTick, cameraOutdoorVideoRecordEnable, CaptureStopRecord(), EVENT_CUSTOM_CAMERA_TIMEOUT, font::f, ituSceneSendEvent(), ituTextSetString, LinphoneStopCamera(), LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, snapshotCountDown, and theScene.
bool CameraOutdoorRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 34 of file layer_camera_outdoor.c.
References cameraOutdoorVideoRecordEnable, CaptureStartRecord(), DeviceInfo::ip, LockRecordButton, LockRecordButtonCountDown, LockRecordButtonLastTick, MEDIA_VIDEO, and theEntranceInfo.
void CameraOutdoorReset (void)
Definition at line 198 of file layer_camera_outdoor.c.
Referenced by resetScene().
bool CameraOutdoorSnapshotButtonOnPress (ITUWidget * widget, char * param)
Definition at line 63 of file layer_camera_outdoor.c.
References CaptureSnapshot(), DeviceInfo::ip, SNAPSHOT_COUNT, snapshotCountDown, and theEntranceInfo.
bool CameraOutdoorStopRecordButtonOnPress (ITUWidget * widget, char * param)
Definition at line 48 of file layer_camera_outdoor.c.
References cameraOutdoorVideoRecordEnable, CaptureStopRecord(), and LockRecordButton.
bool CameraOutdoorUnlockButtonOnPress (ITUWidget * widget, char * param)
Definition at line 57 of file layer_camera_outdoor.c.
References DeviceInfo::ip, SceneOpenDoor(), and theEntranceInfo.
Variable Documentation
ITUBackground* cameraOutdoorBackground static
Definition at line 11 of file layer_camera_outdoor.c.
float cameraOutdoorCountDown static
Definition at line 15 of file layer_camera_outdoor.c.
Referenced by CameraOutdoorOnEnter(), CameraOutdoorOnLeave(), and CameraOutdoorOnTimer().
ITUText* cameraOutdoorCountDownText static
Definition at line 13 of file layer_camera_outdoor.c.
uint32_t cameraOutdoorLastTick static
Definition at line 16 of file layer_camera_outdoor.c.
Referenced by CameraOutdoorOnEnter(), and CameraOutdoorOnTimer().
ITUText* cameraOutdoorSourceText static
Definition at line 12 of file layer_camera_outdoor.c.
bool cameraOutdoorVideoRecordEnable static
Definition at line 18 of file layer_camera_outdoor.c.
Referenced by CameraOutdoorOnEnter(), CameraOutdoorOnLeave(), CameraOutdoorOnTimer(), CameraOutdoorRecordButtonOnPress(), and CameraOutdoorStopRecordButtonOnPress().
bool LockRecordButton static
Definition at line 19 of file layer_camera_outdoor.c.
Referenced by CameraOutdoorOnTimer(), CameraOutdoorRecordButtonOnPress(), and CameraOutdoorStopRecordButtonOnPress().
float LockRecordButtonCountDown static
Definition at line 15 of file layer_camera_outdoor.c.
Referenced by CameraOutdoorOnTimer(), and CameraOutdoorRecordButtonOnPress().
uint32_t LockRecordButtonLastTick static
Definition at line 16 of file layer_camera_outdoor.c.
Referenced by CameraOutdoorOnTimer(), and CameraOutdoorRecordButtonOnPress().
int snapshotCountDown static
Definition at line 17 of file layer_camera_outdoor.c.
Referenced by CameraOutdoorOnEnter(), CameraOutdoorOnTimer(), and CameraOutdoorSnapshotButtonOnPress().