ITE SoC SDK: layer_message.c File Reference
layer_message.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
Functions
void MessageNotifyUnreadRecordMessage (int count)
Notifies the un-play count of captured recording files to the scene.
bool MessageNotifyVideoMessageOnCustom (ITUWidget *widget, char *param)
bool MessageNotifyTextMessageOnCustom (ITUWidget *widget, char *param)
void MessageReset (void)
Variables
static ITUBackground * messagePhotoUnreadBackground
static ITUText * messagePhotoUnreadText
static ITUBackground * messageRecordUnreadBackground
static ITUText * messageRecordUnreadText
static ITUBackground * messageServiceUnreadBackground
static ITUText * messageServiceUnreadText
Function Documentation
bool MessageNotifyTextMessageOnCustom (ITUWidget * widget, char * param)
Definition at line 67 of file layer_message.c.
References ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, and theScene.
bool MessageNotifyVideoMessageOnCustom (ITUWidget * widget, char * param)
Definition at line 39 of file layer_message.c.
References ituSceneFindWidget(), ituTextSetString, ituWidgetSetVisible, and theScene.
void MessageReset (void)
Definition at line 95 of file layer_message.c.
Referenced by resetScene().
Variable Documentation
ITUBackground* messagePhotoUnreadBackground static
Definition at line 7 of file layer_message.c.
ITUText* messagePhotoUnreadText static
Definition at line 8 of file layer_message.c.
ITUBackground* messageRecordUnreadBackground static
Definition at line 9 of file layer_message.c.
ITUText* messageRecordUnreadText static
Definition at line 10 of file layer_message.c.
ITUBackground* messageServiceUnreadBackground static
Definition at line 11 of file layer_message.c.
ITUText* messageServiceUnreadText static
Definition at line 12 of file layer_message.c.