ITE SoC SDK: layer_house_tv.c File Reference
layer_house_tv.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
#include "ite/itp.h"
Functions
bool HouseTVNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseTVStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseTVOnButtonOnPress (ITUWidget *widget, char *param)
bool HouseTVOffButtonOnPress (ITUWidget *widget, char *param)
bool HouseTVOnEnter (ITUWidget *widget, char *param)
void HouseTVReset (void)
Variables
static ITUSprite * houseTVSprite
static ITUListBox * houseTVNameListBox
static HouseInfo houseTVInfoArray [HOUSE_MAX_TV_COUNT]
Function Documentation
bool HouseTVNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 15 of file layer_house_tv.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_MAX_TV_COUNT, HOUSE_TV, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseTVOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 138 of file layer_house_tv.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_TV, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseTVOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 114 of file layer_house_tv.c.
References ITUListBoxTag::focusIndex, HOUSE_OPEN, HOUSE_TV, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseTVOnEnter (ITUWidget * widget, char * param)
Definition at line 162 of file layer_house_tv.c.
References ituSceneFindWidget(), and theScene.
void HouseTVReset (void)
Definition at line 175 of file layer_house_tv.c.
Referenced by resetScene().
bool HouseTVStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 64 of file layer_house_tv.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_MAX_TV_COUNT, HOUSE_TV, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
Variable Documentation
HouseInfo houseTVInfoArray[HOUSE_MAX_TV_COUNT] static
Definition at line 13 of file layer_house_tv.c.
ITUListBox* houseTVNameListBox static
Definition at line 11 of file layer_house_tv.c.
ITUSprite* houseTVSprite static
Definition at line 10 of file layer_house_tv.c.