ITE SoC SDK: layer_message_record_view.c File Reference
layer_message_record_view.c File Reference
#include <assert.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
Macros
#define SNAPSHOT_PATH CFG_TEMP_DRIVE ":/capture"
Functions
bool MessageRecordViewOnTimer (ITUWidget *widget, char *param)
void MessageRecordViewShow (char *topic, char *time, int id, CaptureEntry *entry)
Sets the infomation to the playing captured recording file screen.
bool MessageRecordViewOnEnter (ITUWidget *widget, char *param)
bool MessageRecordViewOnLeave (ITUWidget *widget, char *param)
void MessageRecordViewReset (void)
Variables
static ITULayer * messageRecordLayer
static ITUText * messageRecordViewTopicText
static ITUText * messageRecordViewTimeText
static ITUBackground * messageRecordViewImageBackground
static ITUIcon * messageRecordViewImageIcon
static ITUBackground * messageRecordViewVideoBackground
static ITUBackground * messageRecordViewAudioBackground
static int messageRecordViewID
static CaptureEntry * messageRecordCaptureEntry
static bool messageRecordViewPlaying
Macro Definition Documentation
#define SNAPSHOT_PATH CFG_TEMP_DRIVE ":/capture"
Definition at line 8 of file layer_message_record_view.c.
Referenced by MessageRecordViewOnEnter().
Function Documentation
bool MessageRecordViewOnEnter (ITUWidget * widget, char * param)
Definition at line 52 of file layer_message_record_view.c.
References CaptureGetUnplayCount(), CaptureStartPlay(), data, font::f, CaptureEntry::filename, ituIconLoadJpegData(), ituSceneFindWidget(), ituWidgetSetVisible, LinphoneSetWindowID(), MEDIA_AUDIO, MEDIA_IMAGE, MEDIA_VIDEO, MessageNotifyUnreadRecordMessage(), messageRecordViewID, messageRecordViewPlaying, SceneCameraSetViewing(), SceneLeaveVideoState(), SNAPSHOT_PATH, theScene, and CaptureEntry::type.
bool MessageRecordViewOnLeave (ITUWidget * widget, char * param)
Definition at line 130 of file layer_message_record_view.c.
References CaptureStopPlay(), messageRecordViewPlaying, SceneCameraSetViewing(), SceneContinuePlayGuardAlarm(), and SceneEnterVideoState().
bool MessageRecordViewOnTimer (ITUWidget * widget, char * param)
Definition at line 20 of file layer_message_record_view.c.
References CaptureIsPlayFinished(), ituLayerGoto(), ituSceneFindWidget(), messageRecordViewPlaying, and theScene.
void MessageRecordViewReset (void)
Definition at line 140 of file layer_message_record_view.c.
Referenced by resetScene().
Variable Documentation
CaptureEntry* messageRecordCaptureEntry static
Definition at line 17 of file layer_message_record_view.c.
ITULayer* messageRecordLayer static
Definition at line 9 of file layer_message_record_view.c.
ITUBackground* messageRecordViewAudioBackground static
Definition at line 15 of file layer_message_record_view.c.
int messageRecordViewID static
Definition at line 16 of file layer_message_record_view.c.
Referenced by MessageRecordViewOnEnter(), and MessageRecordViewShow().
ITUBackground* messageRecordViewImageBackground static
Definition at line 12 of file layer_message_record_view.c.
ITUIcon* messageRecordViewImageIcon static
Definition at line 13 of file layer_message_record_view.c.
bool messageRecordViewPlaying static
Definition at line 18 of file layer_message_record_view.c.
Referenced by MessageRecordViewOnEnter(), MessageRecordViewOnLeave(), and MessageRecordViewOnTimer().
ITUText* messageRecordViewTimeText static
Definition at line 11 of file layer_message_record_view.c.
ITUText* messageRecordViewTopicText static
Definition at line 10 of file layer_message_record_view.c.
ITUBackground* messageRecordViewVideoBackground static
Definition at line 14 of file layer_message_record_view.c.