ITE SoC SDK: layer_guard_user_setting.c File Reference
layer_guard_user_setting.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
Functions
bool GuardUserSettingSaveButtonOnPress (ITUWidget *widget, char *param)
bool GuardUserSettingCancelButtonOnPress (ITUWidget *widget, char *param)
bool GuardUserSettingOnEnter (ITUWidget *widget, char *param)
void GuardUserSettingReset (void)
Variables
static ITUCheckBox * guardUserSettingIndoorEmergencyCheckBox
static ITUCheckBox * guardUserSettingIndoorInfraredCheckBox
static ITUCheckBox * guardUserSettingIndoorDoorCheckBox
static ITUCheckBox * guardUserSettingIndoorWindowCheckBox
static ITUCheckBox * guardUserSettingIndoorSmokeCheckBox
static ITUCheckBox * guardUserSettingIndoorGasCheckBox
static ITUCheckBox * guardUserSettingIndoorAreaCheckBox
static ITUCheckBox * guardUserSettingIndoorRobCheckBox
static ITUCheckBox * guardUserSettingOutdoorEmergencyCheckBox
static ITUCheckBox * guardUserSettingOutdoorInfraredCheckBox
static ITUCheckBox * guardUserSettingOutdoorDoorCheckBox
static ITUCheckBox * guardUserSettingOutdoorWindowCheckBox
static ITUCheckBox * guardUserSettingOutdoorSmokeCheckBox
static ITUCheckBox * guardUserSettingOutdoorGasCheckBox
static ITUCheckBox * guardUserSettingOutdoorAreaCheckBox
static ITUCheckBox * guardUserSettingOutdoorRobCheckBox
static ITUCheckBox * guardUserSettingSleepEmergencyCheckBox
static ITUCheckBox * guardUserSettingSleepInfraredCheckBox
static ITUCheckBox * guardUserSettingSleepDoorCheckBox
static ITUCheckBox * guardUserSettingSleepWindowCheckBox
static ITUCheckBox * guardUserSettingSleepSmokeCheckBox
static ITUCheckBox * guardUserSettingSleepGasCheckBox
static ITUCheckBox * guardUserSettingSleepAreaCheckBox
static ITUCheckBox * guardUserSettingSleepRobCheckBox
Function Documentation
bool GuardUserSettingCancelButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_guard_user_setting.c.
References ituCheckBoxSetChecked().
bool GuardUserSettingOnEnter (ITUWidget * widget, char * param)
Definition at line 94 of file layer_guard_user_setting.c.
References GUARD_AREA, GUARD_DOOR, GUARD_EMERGENCY, GUARD_GAS, Config::guard_indoor_sensors, GUARD_INFRARED, Config::guard_outdoor_sensors, GUARD_ROB, Config::guard_sleep_sensors, GUARD_SMOKE, GUARD_WINDOW, ituCheckBoxSetChecked(), ituSceneFindWidget(), theConfig, and theScene.
void GuardUserSettingReset (void)
Definition at line 198 of file layer_guard_user_setting.c.
Referenced by resetScene().
bool GuardUserSettingSaveButtonOnPress (ITUWidget * widget, char * param)
Definition at line 33 of file layer_guard_user_setting.c.
References ConfigSave(), GUARD_AREA, GUARD_DOOR, GUARD_EMERGENCY, GUARD_GAS, Config::guard_indoor_sensors, GUARD_INFRARED, Config::guard_mode, Config::guard_outdoor_sensors, GUARD_ROB, Config::guard_sleep_sensors, GUARD_SMOKE, GUARD_WINDOW, GuardSetMode(), ituCheckBoxIsChecked(), and theConfig.
Variable Documentation
ITUCheckBox* guardUserSettingIndoorAreaCheckBox static
Definition at line 14 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingIndoorDoorCheckBox static
Definition at line 10 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingIndoorEmergencyCheckBox static
Definition at line 8 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingIndoorGasCheckBox static
Definition at line 13 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingIndoorInfraredCheckBox static
Definition at line 9 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingIndoorRobCheckBox static
Definition at line 15 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingIndoorSmokeCheckBox static
Definition at line 12 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingIndoorWindowCheckBox static
Definition at line 11 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingOutdoorAreaCheckBox static
Definition at line 22 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingOutdoorDoorCheckBox static
Definition at line 18 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingOutdoorEmergencyCheckBox static
Definition at line 16 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingOutdoorGasCheckBox static
Definition at line 21 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingOutdoorInfraredCheckBox static
Definition at line 17 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingOutdoorRobCheckBox static
Definition at line 23 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingOutdoorSmokeCheckBox static
Definition at line 20 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingOutdoorWindowCheckBox static
Definition at line 19 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingSleepAreaCheckBox static
Definition at line 30 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingSleepDoorCheckBox static
Definition at line 26 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingSleepEmergencyCheckBox static
Definition at line 24 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingSleepGasCheckBox static
Definition at line 29 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingSleepInfraredCheckBox static
Definition at line 25 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingSleepRobCheckBox static
Definition at line 31 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingSleepSmokeCheckBox static
Definition at line 28 of file layer_guard_user_setting.c.
ITUCheckBox* guardUserSettingSleepWindowCheckBox static
Definition at line 27 of file layer_guard_user_setting.c.