ITE SoC SDK: layer_phone_dial_resident.c File Reference
layer_phone_dial_resident.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool PhoneBackButtonOnPress (ITUWidget *widget, char *param)
bool PhoneNumberButtonOnPress (ITUWidget *widget, char *param)
bool PhoneManagerButtonOnPress (ITUWidget *widget, char *param)
bool PhoneCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneDialResidentOnEnter (ITUWidget *widget, char *param)
void PhoneDialResidentReset (void)
Variables
static ITUBackground * phoneResidentRoomBackground
static ITUTextBox * phoneAreaTextBox
static ITUTextBox * phoneBuildingTextBox
static ITUTextBox * phoneUnitTextBox
static ITUTextBox * phoneFloorTextBox
static ITUTextBox * phoneRoomTextBox
static ITUBackground * phoneResidentIPBackground
static ITUTextBox * phoneIPTextBox
static ITUTextBox * activePhoneDialTextBox
Function Documentation
bool PhoneBackButtonOnPress (ITUWidget * widget, char * param)
Definition at line 22 of file layer_phone_dial_resident.c.
References ituTextBoxBack(), ituTextGetString, ituTextSetString, ituWidgetSetVisible, phoneAreaTextBox, phoneBuildingTextBox, phoneFloorTextBox, and phoneUnitTextBox.
bool PhoneCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 116 of file layer_phone_dial_resident.c.
References CallingCall(), CallingCallByIP(), and ituTextGetString.
bool PhoneDialResidentOnEnter (ITUWidget * widget, char * param)
Definition at line 143 of file layer_phone_dial_resident.c.
References ituSceneFindWidget(), ituTextBoxSetString(), ituWidgetSetVisible, phoneAreaTextBox, and theScene.
void PhoneDialResidentReset (void)
Definition at line 185 of file layer_phone_dial_resident.c.
Referenced by resetScene().
bool PhoneManagerButtonOnPress (ITUWidget * widget, char * param)
Definition at line 108 of file layer_phone_dial_resident.c.
References CallingCallManager().
bool PhoneNumberButtonOnPress (ITUWidget * widget, char * param)
Definition at line 65 of file layer_phone_dial_resident.c.
References ituTextBoxInput(), ituTextGetString, ituWidgetSetVisible, ITUTextBox::maxLen, phoneBuildingTextBox, phoneFloorTextBox, phoneIPTextBox, phoneRoomTextBox, phoneUnitTextBox, and ITUButton::text.
Variable Documentation
ITUTextBox* activePhoneDialTextBox static
Definition at line 19 of file layer_phone_dial_resident.c.
ITUTextBox* phoneAreaTextBox static
Definition at line 9 of file layer_phone_dial_resident.c.
Referenced by PhoneBackButtonOnPress(), and PhoneDialResidentOnEnter().
ITUTextBox* phoneBuildingTextBox static
Definition at line 10 of file layer_phone_dial_resident.c.
Referenced by PhoneBackButtonOnPress(), and PhoneNumberButtonOnPress().
ITUTextBox* phoneFloorTextBox static
Definition at line 12 of file layer_phone_dial_resident.c.
Referenced by PhoneBackButtonOnPress(), and PhoneNumberButtonOnPress().
ITUTextBox* phoneIPTextBox static
Definition at line 16 of file layer_phone_dial_resident.c.
Referenced by PhoneNumberButtonOnPress().
ITUBackground* phoneResidentIPBackground static
Definition at line 15 of file layer_phone_dial_resident.c.
ITUBackground* phoneResidentRoomBackground static
Definition at line 8 of file layer_phone_dial_resident.c.
ITUTextBox* phoneRoomTextBox static
Definition at line 13 of file layer_phone_dial_resident.c.
Referenced by PhoneNumberButtonOnPress().
ITUTextBox* phoneUnitTextBox static
Definition at line 11 of file layer_phone_dial_resident.c.
Referenced by PhoneBackButtonOnPress(), and PhoneNumberButtonOnPress().