ITE SoC SDK: layer_main.c File Reference
layer_main.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "scene.h"
#include "doorbell.h"
Functions
bool MainSetDoNotDisturbModeOnCustom (ITUWidget *widget, char *param)
bool MainNotifyMissedCallsOnCustom (ITUWidget *widget, char *param)
bool MainNotifyMessagesOnCustom (ITUWidget *widget, char *param)
bool MainNotifyGuardOnCustom (ITUWidget *widget, char *param)
bool MainNotifyNetworkOnCustom (ITUWidget *widget, char *param)
bool MainNotifyCallIncomingOnCustom (ITUWidget *widget, char *param)
bool MainNotifyVoiceMemoIncomingOnCustom (ITUWidget *widget, char *param)
void MainReset (void)
Variables
static ITULayer * calledLayer
static ITULayer * videoRecordLayer
static ITUSprite * guardIndicatorSprite
static ITUSprite * networkIndicatorSprite
static ITUSprite * phoneIndicatorSprite
static ITUBackground * missedCallsCountBackground
static ITUText * missedCallsCountText
static ITUSprite * messageIndicatorSprite
static ITUBackground * messagesCountBackground
static ITUText * messagesCountText
Function Documentation
bool MainNotifyCallIncomingOnCustom (ITUWidget * widget, char * param)
Definition at line 175 of file layer_main.c.
References CalledIncomingShow(), ituLayerGoto(), ituSceneFindWidget(), and theScene.
bool MainNotifyGuardOnCustom (ITUWidget * widget, char * param)
Definition at line 139 of file layer_main.c.
References ituSceneFindWidget(), ituSpriteGoto(), and theScene.
bool MainNotifyMessagesOnCustom (ITUWidget * widget, char * param)
Definition at line 107 of file layer_main.c.
References ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, ituWidgetSetVisible, and theScene.
bool MainNotifyMissedCallsOnCustom (ITUWidget * widget, char * param)
Definition at line 57 of file layer_main.c.
References ITUSpriteTag::frame, ituSceneFindWidget(), ituSpriteGoto(), ituTextSetString, ituWidgetSetVisible, and theScene.
bool MainNotifyNetworkOnCustom (ITUWidget * widget, char * param)
Definition at line 157 of file layer_main.c.
References ituSceneFindWidget(), ituSpriteGoto(), and theScene.
bool MainNotifyVoiceMemoIncomingOnCustom (ITUWidget * widget, char * param)
Definition at line 192 of file layer_main.c.
References DEVICE_INDOOR2, ituLayerGoto(), ituSceneFindWidget(), theDeviceInfo, theScene, DeviceInfo::type, and VideoRecordIncomingShow().
void MainReset (void)
Definition at line 212 of file layer_main.c.
Referenced by resetScene().
bool MainSetDoNotDisturbModeOnCustom (ITUWidget * widget, char * param)
Definition at line 22 of file layer_main.c.
References DONOT_DISTURB_ALL, DONOT_DISTURB_MUTE, DONOT_DISTURB_NONE, DONOT_DISTURB_TIME, ituSceneFindWidget(), ituSpriteGoto(), ituWidgetIsVisible, and theScene.
Variable Documentation
ITULayer* calledLayer static
Definition at line 9 of file layer_main.c.
ITUSprite* guardIndicatorSprite static
Definition at line 11 of file layer_main.c.
ITUSprite* messageIndicatorSprite static
Definition at line 17 of file layer_main.c.
ITUBackground* messagesCountBackground static
Definition at line 18 of file layer_main.c.
ITUText* messagesCountText static
Definition at line 19 of file layer_main.c.
ITUBackground* missedCallsCountBackground static
Definition at line 14 of file layer_main.c.
ITUText* missedCallsCountText static
Definition at line 15 of file layer_main.c.
ITUSprite* networkIndicatorSprite static
Definition at line 12 of file layer_main.c.
ITUSprite* phoneIndicatorSprite static
Definition at line 13 of file layer_main.c.
ITULayer* videoRecordLayer static
Definition at line 10 of file layer_main.c.