ITE SoC SDK: layer_phone_contacts.c File Reference
layer_phone_contacts.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "linphone/linphone_castor3.h"
#include "scene.h"
#include "doorbell.h"
Functions
bool PhoneContactsRoomListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneContactsCommentListBoxOnLoad (ITUWidget *widget, char *param)
bool PhoneContactsCallButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsAddButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsModifyButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsDeleteButtonOnPress (ITUWidget *widget, char *param)
static void PhoneContactsReload (int arg)
bool PhoneContactsDeleteConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsClearConfirmButtonOnPress (ITUWidget *widget, char *param)
bool PhoneContactsOnEnter (ITUWidget *widget, char *param)
void PhoneContactsReset (void)
Variables
static ITULayer * phoneContactsLayer
static ITUListBox * phoneRoomListBox
static ITUListBox * phoneCommentListBox
Function Documentation
bool PhoneContactsAddButtonOnPress (ITUWidget * widget, char * param)
Definition at line 154 of file layer_phone_contacts.c.
References PhoneContactsAddShow().
bool PhoneContactsCallButtonOnPress (ITUWidget * widget, char * param)
Definition at line 132 of file layer_phone_contacts.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, LinphoneCastor3Friend::blacklist, DeviceInfo::building, CallingCall(), DEVICE_ENTRANCE, DeviceInfo::ext, DeviceInfo::floor, ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituWidgetGetCustomData, DeviceInfo::room, DeviceInfo::type, DeviceInfo::unit, and LinphoneCastor3Friend::uri.
bool PhoneContactsClearConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 201 of file layer_phone_contacts.c.
References ituSceneExecuteCommand(), LinphoneClearFriends(), PhoneContactsReload(), and theScene.
bool PhoneContactsCommentListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 77 of file layer_phone_contacts.c.
References LinphoneCastor3Friend::blacklist, ITCTreeTag::child, LinphoneCastor3Friend::comment, ITUListBoxTag::focusIndex, LinphoneCastor3::friend_count, LinphoneCastor3::friends, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, linphoneCastor3, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool PhoneContactsDeleteButtonOnPress (ITUWidget * widget, char * param)
Definition at line 174 of file layer_phone_contacts.c.
References ITUListBoxTag::focusIndex.
bool PhoneContactsDeleteConfirmButtonOnPress (ITUWidget * widget, char * param)
Definition at line 188 of file layer_phone_contacts.c.
References ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituSceneExecuteCommand(), ituWidgetGetCustomData, LinphoneDeleteFriend(), PhoneContactsReload(), LinphoneCastor3Friend::refkey, and theScene.
bool PhoneContactsModifyButtonOnPress (ITUWidget * widget, char * param)
Definition at line 160 of file layer_phone_contacts.c.
References AddressBookGetDeviceInfo(), LinphoneCastor3Friend::blacklist, LinphoneCastor3Friend::comment, ITUListBoxTag::focusIndex, itcTreeGetChildAt, ituWidgetGetCustomData, PhoneContactsModifyShow(), LinphoneCastor3Friend::refkey, and LinphoneCastor3Friend::uri.
bool PhoneContactsOnEnter (ITUWidget * widget, char * param)
Definition at line 208 of file layer_phone_contacts.c.
References ituSceneFindWidget(), and theScene.
static void PhoneContactsReload (int arg) static
Definition at line 182 of file layer_phone_contacts.c.
References ituListBoxReload().
Referenced by PhoneContactsClearConfirmButtonOnPress(), and PhoneContactsDeleteConfirmButtonOnPress().
void PhoneContactsReset (void)
Definition at line 224 of file layer_phone_contacts.c.
Referenced by resetScene().
bool PhoneContactsRoomListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 16 of file layer_phone_contacts.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, LinphoneCastor3Friend::blacklist, DeviceInfo::building, ITCTreeTag::child, DeviceInfo::floor, ITUListBoxTag::focusIndex, LinphoneCastor3::friend_count, LinphoneCastor3::friends, i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetColor, ituWidgetSetCustomData, linphoneCastor3, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, DeviceInfo::room, ITCTreeTag::sibling, StringGetRoomAddress(), DeviceInfo::unit, and LinphoneCastor3Friend::uri.
Variable Documentation
ITUListBox* phoneCommentListBox static
Definition at line 13 of file layer_phone_contacts.c.
ITULayer* phoneContactsLayer static
Definition at line 9 of file layer_phone_contacts.c.
ITUListBox* phoneRoomListBox static
Definition at line 12 of file layer_phone_contacts.c.