ITE SoC SDK: layer_house_light.c File Reference
layer_house_light.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
#include "ite/itp.h"
Functions
bool HouseLightNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseLightStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HouseLightOnButtonOnPress (ITUWidget *widget, char *param)
bool HouseLightOffButtonOnPress (ITUWidget *widget, char *param)
bool HouseLightOnEnter (ITUWidget *widget, char *param)
void HouseLightReset (void)
Variables
static ITUSprite * houseLightSprite
static ITUListBox * houseLightNameListBox
static HouseInfo houseLightInfoArray [HOUSE_MAX_LIGHT_COUNT]
Function Documentation
bool HouseLightNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_house_light.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_LIGHT, HOUSE_MAX_LIGHT_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HouseLightOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 137 of file layer_house_light.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_LIGHT, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseLightOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 113 of file layer_house_light.c.
References ITUListBoxTag::focusIndex, HOUSE_LIGHT, HOUSE_OPEN, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HouseLightOnEnter (ITUWidget * widget, char * param)
Definition at line 160 of file layer_house_light.c.
References ituSceneFindWidget(), and theScene.
void HouseLightReset (void)
Definition at line 173 of file layer_house_light.c.
Referenced by resetScene().
bool HouseLightStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 63 of file layer_house_light.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_LIGHT, HOUSE_MAX_LIGHT_COUNT, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
Variable Documentation
HouseInfo houseLightInfoArray[HOUSE_MAX_LIGHT_COUNT] static
Definition at line 12 of file layer_house_light.c.
ITUListBox* houseLightNameListBox static
Definition at line 10 of file layer_house_light.c.
ITUSprite* houseLightSprite static
Definition at line 9 of file layer_house_light.c.