ITE SoC SDK: layer_house_plug.c File Reference
layer_house_plug.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doorbell.h"
#include "scene.h"
#include "ite/itp.h"
Functions
bool HousePlugNameListBoxOnLoad (ITUWidget *widget, char *param)
bool HousePlugStatusListBoxOnLoad (ITUWidget *widget, char *param)
bool HousePlugOnButtonOnPress (ITUWidget *widget, char *param)
bool HousePlugOffButtonOnPress (ITUWidget *widget, char *param)
bool HousePlugOnEnter (ITUWidget *widget, char *param)
void HousePlugReset (void)
Variables
static ITUSprite * housePlugSprite
static ITUListBox * housePlugNameListBox
static HouseInfo housePlugInfoArray [HOUSE_MAX_PLUG_COUNT]
Function Documentation
bool HousePlugNameListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 14 of file layer_house_plug.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_MAX_PLUG_COUNT, HOUSE_PLUG, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ituWidgetSetCustomData, HouseInfo::name, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, and ITCTreeTag::sibling.
bool HousePlugOffButtonOnPress (ITUWidget * widget, char * param)
Definition at line 136 of file layer_house_plug.c.
References ITUListBoxTag::focusIndex, HOUSE_CLOSE, HOUSE_PLUG, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HousePlugOnButtonOnPress (ITUWidget * widget, char * param)
Definition at line 113 of file layer_house_plug.c.
References ITUListBoxTag::focusIndex, HOUSE_OPEN, HOUSE_PLUG, HouseExecAction(), itcTreeGetChildAt, ITH_RS485_0, ITH_UART_NONE, ITP_DEVICE_RS485_0, ITP_IOCTL_ON, ITP_IOCTL_RESET, ituSpriteGoto(), and ituWidgetGetCustomData.
bool HousePlugOnEnter (ITUWidget * widget, char * param)
Definition at line 159 of file layer_house_plug.c.
References ituSceneFindWidget(), and theScene.
void HousePlugReset (void)
Definition at line 172 of file layer_house_plug.c.
Referenced by resetScene().
bool HousePlugStatusListBoxOnLoad (ITUWidget * widget, char * param)
Definition at line 63 of file layer_house_plug.c.
References ITCTreeTag::child, ITUListBoxTag::focusIndex, HOUSE_MAX_PLUG_COUNT, HOUSE_PLUG, HouseGetInfoArray(), i, itcTreeGetChildCount, ITUListBoxTag::itemCount, ituTextSetString, ITUListBoxTag::pageCount, ITUListBoxTag::pageIndex, ITCTreeTag::sibling, HouseInfo::status, and StringGetHouseStatus().
Variable Documentation
HouseInfo housePlugInfoArray[HOUSE_MAX_PLUG_COUNT] static
Definition at line 12 of file layer_house_plug.c.
ITUListBox* housePlugNameListBox static
Definition at line 10 of file layer_house_plug.c.
ITUSprite* housePlugSprite static
Definition at line 9 of file layer_house_plug.c.