ITE SoC SDK: font Namespace Reference
font Namespace Reference
Functions
def ParseXMLText
def ConvertListToString
def RemoveDuplicateElements
def CreateSelectedList
def RemoveFile
def GenerateARGV
def SplitText
def ParseArgv
def ParseArgOpt
def ParseArgc
Variables
list ts = []
# #
list t = []
string xml = ""
string tar = "text.txt"
string font = ""
string fontn = ""
int sym = 1
string gb2313Symbol = " 、。·ˉˇ¨〃々—～‖…‘’“”〔〕〈〉《》「」『』〖〗【】±×÷∶∧∨∑∏∪∩∈∷√⊥∥∠⌒⊙∫∮≡≌≈∽∝≠≮≯≤≥∞∵∴♂♀°′″℃＄¤￠￡‰§№☆★○●◎◇◆□■△▲※→←↑↓〓ⅰⅱⅲⅳⅴⅵⅶⅷⅸⅹ⒈⒉⒊⒋⒌⒍⒎⒏⒐⒑⒒⒓⒔⒕⒖⒗⒘⒙⒚⒛⑴⑵⑶⑷⑸⑹⑺⑻⑼⑽⑾⑿⒀⒁⒂⒃⒄⒅⒆⒇①②③④⑤⑥⑦⑧⑨⑩㈠㈡㈢㈣㈤㈥㈦㈧㈨㈩ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫ！＂＃￥％＆＇（）＊＋，－．／０１２３４５６７８９：；＜＝＞？＠ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ［＼］＾＿｀ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ｛｜｝￣ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろゎわゐゑをんァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロヮワヰヱヲンヴヵヶΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφχψω︵︶︹︺︿﹀︽︾﹁﹂﹃﹄︻︼︷︸︱︳︴АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜüêɑńňǹɡㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦㄧㄨㄩ─━│┃┄┅┆┇┈┉┊┋┌┍┎┏┐┑┒┓└┕┖┗┘┙┚┛├┝┞┟┠┡┢┣┤┥┦┧┨┩┪┫┬┭┮┯┰┱┲┳┴┵┶┷┸┹┺┻┼┽┾┿╀╁╂╃╄╅╆╇╈╉╊╋"
tuple p = GenerateARGV(sys.argv)
tuple x = ParseArgc(sys.argv, "-x")
tuple f = open(tar, "w", encoding = 'UTF-8')
Function Documentation
def font.ConvertListToString (ts)
Definition at line 48 of file font.py.
def font.CreateSelectedList (ts)
Definition at line 63 of file font.py.
def font.GenerateARGV (t)
Definition at line 81 of file font.py.
def font.ParseArgc (argv, p)
Definition at line 117 of file font.py.
def font.ParseArgOpt (argv, p)
Definition at line 109 of file font.py.
def font.ParseArgv (argv, p)
Definition at line 99 of file font.py.
def font.ParseXMLText (src)
Definition at line 9 of file font.py.
def font.RemoveDuplicateElements (ts)
Definition at line 58 of file font.py.
def font.RemoveFile (filename)
Definition at line 73 of file font.py.
def font.SplitText (ts)
Definition at line 87 of file font.py.
Variable Documentation
tuple f = open(tar, "w", encoding = 'UTF-8')
Examples:
test_itu/test_jpeg.c.
Definition at line 194 of file font.py.
Referenced by AddressBookExport(), AddressBookInit(), CalledOnTimer(), CallingOnTimer(), CameraOnTimer(), CameraOutdoorOnTimer(), ConfigSavePrivate(), ConfigSavePublic(), MainVoiceMemoOnTimer(), MessageRecordViewOnEnter(), Parse_UCL2MEM(), PhoneLogViewShow(), ScreenSaverCheck(), ScreensaverOnEnter(), and VideoRecordOnTimer().
tuple font = ""
Definition at line 138 of file font.py.
list fontn = ""
Definition at line 139 of file font.py.
string gb2313Symbol = " 、。·ˉˇ¨〃々—～‖…‘’“”〔〕〈〉《》「」『』〖〗【】±×÷∶∧∨∑∏∪∩∈∷√⊥∥∠⌒⊙∫∮≡≌≈∽∝≠≮≯≤≥∞∵∴♂♀°′″℃＄¤￠￡‰§№☆★○●◎◇◆□■△▲※→←↑↓〓ⅰⅱⅲⅳⅴⅵⅶⅷⅸⅹ⒈⒉⒊⒋⒌⒍⒎⒏⒐⒑⒒⒓⒔⒕⒖⒗⒘⒙⒚⒛⑴⑵⑶⑷⑸⑹⑺⑻⑼⑽⑾⑿⒀⒁⒂⒃⒄⒅⒆⒇①②③④⑤⑥⑦⑧⑨⑩㈠㈡㈢㈣㈤㈥㈦㈧㈨㈩ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫ！＂＃￥％＆＇（）＊＋，－．／０１２３４５６７８９：；＜＝＞？＠ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ［＼］＾＿｀ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ｛｜｝￣ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろゎわゐゑをんァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロヮワヰヱヲンヴヵヶΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφχψω︵︶︹︺︿﹀︽︾﹁﹂﹃﹄︻︼︷︸︱︳︴АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜüêɑńňǹɡㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦㄧㄨㄩ─━│┃┄┅┆┇┈┉┊┋┌┍┎┏┐┑┒┓└┕┖┗┘┙┚┛├┝┞┟┠┡┢┣┤┥┦┧┨┩┪┫┬┭┮┯┰┱┲┳┴┵┶┷┸┹┺┻┼┽┾┿╀╁╂╃╄╅╆╇╈╉╊╋"
Definition at line 141 of file font.py.
tuple p = GenerateARGV(sys.argv)
Definition at line 143 of file font.py.
Referenced by EventUploadTask(), func1(), SettingEngineerNetworkIPShow(), and test_malloc_stats().
int sym = 1
Definition at line 140 of file font.py.
tuple t = []
Examples:
test_itu/test_button.c, test_itu/test_cursor.c, test_itu/test_jpeg.c, test_itu/test_language.c, test_itu/test_listbox.c, and test_itu/test_progressbar.c.
Definition at line 134 of file font.py.
Referenced by ahc_echo(), CaptureGetSnapshotFileNameByTime(), CaptureSnapshot(), CardListCheckTask(), SceneRun(), and Test_sleep().
string tar = "text.txt"
Definition at line 137 of file font.py.
tuple ts = []
# #
Definition at line 133 of file font.py.
tuple x = ParseArgc(sys.argv, "-x")
Examples:
test_itu/test_sdl.c, test_lcd/test_backlight.c, and test_lcd/test_lcd.c.
Definition at line 151 of file font.py.
Referenced by LinphoneSetWindowID(), test_stgt_env(), TouchCalibrationCheckBoxOnPress(), and TouchCalibrationOnEnter().
string xml = ""
Definition at line 136 of file font.py.