ITE SoC SDK: reset.c File Reference
reset.c File Reference
#include "ite/itu.h"
Functions
void MainReset (void)
void MainMenuReset (void)
void MainVoiceMemoReset (void)
void MainWeatherReset (void)
void TimeReset (void)
void TouchCalibrationReset (void)
void UpgradeReset (void)
void ScreensaverReset (void)
void VideoRecordReset (void)
void PhoneDialResidentReset (void)
void PhoneDialManagerReset (void)
void PhoneDialLobbyReset (void)
void PhoneContactsReset (void)
void PhoneContactsAddReset (void)
void PhoneContactsModifyReset (void)
void PhoneContactsKeypadReset (void)
void PhoneContactsKeyboardReset (void)
void PhoneLogMissedReset (void)
void PhoneLogReceivedReset (void)
void PhoneLogSentReset (void)
void PhoneLogViewReset (void)
void CalledReset (void)
void CallingReset (void)
void MessageReset (void)
void MessagePhotoReset (void)
void MessagePhotoViewReset (void)
void MessageRecordReset (void)
void MessageRecordViewReset (void)
void MessageServiceReset (void)
void MessageServiceViewReset (void)
void CameraReset (void)
void CameraViewReset (void)
void CameraOutdoorReset (void)
void GuardLogReset (void)
void GuardModeReset (void)
void GuardPasswordReset (void)
void GuardStatusReset (void)
void GuardUserReset (void)
void GuardUserSettingReset (void)
void HouseAirConditionerReset (void)
void HouseCurtainReset (void)
void HouseLightReset (void)
void HouseModeReset (void)
void HousePlugReset (void)
void HouseTVReset (void)
void SettingDisplayReset (void)
void SettingEngineerReset (void)
void SettingEngineerMiscTerminalReset (void)
void SettingEngineerMiscTwiceReset (void)
void SettingEngineerNetworkReset (void)
void SettingEngineerNetworkIPReset (void)
void SettingEngineerNetworkMacReset (void)
void SettingEngineerNetworkWiFiReset (void)
void SettingEngineerNetworkWiFiPasswordReset (void)
void SettingEngineerSensorReset (void)
void SettingOutdoorMainReset (void)
void SettingOutdoorMiscReset (void)
void SettingPhoneAudioReset (void)
void SettingPhoneVoiceReset (void)
void SettingPhoneDisturbReset (void)
void SettingSystemReset (void)
void resetScene (void)
Function Documentation
void CalledReset (void)
Definition at line 720 of file layer_called.c.
Referenced by resetScene().
void CallingReset (void)
Definition at line 1005 of file doorbell_indoor/layer_calling.c.
Referenced by resetScene().
void CameraOutdoorReset (void)
Definition at line 198 of file layer_camera_outdoor.c.
Referenced by resetScene().
void CameraReset (void)
Definition at line 292 of file layer_camera.c.
Referenced by resetScene().
void CameraViewReset (void)
Definition at line 113 of file layer_camera_view.c.
References cameraViewIsLeaving.
Referenced by resetScene().
void GuardLogReset (void)
Definition at line 238 of file layer_guard_log.c.
Referenced by resetScene().
void GuardModeReset (void)
Definition at line 184 of file layer_guard_mode.c.
Referenced by resetScene().
void GuardPasswordReset (void)
Definition at line 127 of file layer_guard_password.c.
Referenced by resetScene().
void GuardStatusReset (void)
Definition at line 185 of file layer_guard_status.c.
Referenced by resetScene().
void GuardUserReset (void)
Definition at line 31 of file layer_guard_user.c.
Referenced by resetScene().
void GuardUserSettingReset (void)
Definition at line 198 of file layer_guard_user_setting.c.
Referenced by resetScene().
void HouseAirConditionerReset (void)
Definition at line 174 of file layer_house_airconditioner.c.
Referenced by resetScene().
void HouseCurtainReset (void)
Definition at line 185 of file layer_house_curtain.c.
Referenced by resetScene().
void HouseLightReset (void)
Definition at line 173 of file layer_house_light.c.
Referenced by resetScene().
void HouseModeReset (void)
Definition at line 614 of file layer_house_mode.c.
Referenced by resetScene().
void HousePlugReset (void)
Definition at line 172 of file layer_house_plug.c.
Referenced by resetScene().
void HouseTVReset (void)
Definition at line 175 of file layer_house_tv.c.
Referenced by resetScene().
void MainMenuReset (void)
Definition at line 36 of file layer_main_menu.c.
Referenced by resetScene().
void MainReset (void)
Definition at line 212 of file layer_main.c.
Referenced by resetScene().
void MainVoiceMemoReset (void)
Definition at line 416 of file layer_main_voicememo.c.
Referenced by resetScene().
void MainWeatherReset (void)
Definition at line 274 of file layer_main_weather.c.
Referenced by resetScene().
void MessagePhotoReset (void)
Definition at line 274 of file layer_message_video.c.
Referenced by resetScene().
void MessagePhotoViewReset (void)
Definition at line 87 of file layer_message_video_view.c.
Referenced by resetScene().
void MessageRecordReset (void)
Definition at line 259 of file layer_message_record.c.
Referenced by resetScene().
void MessageRecordViewReset (void)
Definition at line 140 of file layer_message_record_view.c.
Referenced by resetScene().
void MessageReset (void)
Definition at line 95 of file layer_message.c.
Referenced by resetScene().
void MessageServiceReset (void)
Definition at line 217 of file layer_message_service.c.
Referenced by resetScene().
void MessageServiceViewReset (void)
Definition at line 89 of file layer_message_service_view.c.
Referenced by resetScene().
void PhoneContactsAddReset (void)
Definition at line 193 of file layer_phone_contacts_add.c.
Referenced by resetScene().
void PhoneContactsKeyboardReset (void)
Definition at line 503 of file layer_phone_contacts_keyboard.c.
Referenced by resetScene().
void PhoneContactsKeypadReset (void)
Definition at line 170 of file layer_phone_contacts_keypad.c.
Referenced by resetScene().
void PhoneContactsModifyReset (void)
Definition at line 154 of file layer_phone_contacts_modify.c.
Referenced by resetScene().
void PhoneContactsReset (void)
Definition at line 224 of file layer_phone_contacts.c.
Referenced by resetScene().
void PhoneDialLobbyReset (void)
Definition at line 90 of file layer_phone_dial_lobby.c.
Referenced by resetScene().
void PhoneDialManagerReset (void)
Definition at line 90 of file layer_phone_dial_manager.c.
Referenced by resetScene().
void PhoneDialResidentReset (void)
Definition at line 185 of file layer_phone_dial_resident.c.
Referenced by resetScene().
void PhoneLogMissedReset (void)
Definition at line 285 of file layer_phone_log_missed.c.
Referenced by resetScene().
void PhoneLogReceivedReset (void)
Definition at line 278 of file layer_phone_log_received.c.
Referenced by resetScene().
void PhoneLogSentReset (void)
Definition at line 278 of file layer_phone_log_sent.c.
Referenced by resetScene().
void PhoneLogViewReset (void)
Definition at line 92 of file layer_phone_log_view.c.
Referenced by resetScene().
void resetScene (void)
Definition at line 77 of file reset.c.
References CalledReset(), CallingReset(), CameraOutdoorReset(), CameraReset(), CameraViewReset(), GuardLogReset(), GuardModeReset(), GuardPasswordReset(), GuardStatusReset(), GuardUserReset(), GuardUserSettingReset(), HouseAirConditionerReset(), HouseCurtainReset(), HouseLightReset(), HouseModeReset(), HousePlugReset(), HouseTVReset(), MainMenuReset(), MainReset(), MainVoiceMemoReset(), MainWeatherReset(), MessagePhotoReset(), MessagePhotoViewReset(), MessageRecordReset(), MessageRecordViewReset(), MessageReset(), MessageServiceReset(), MessageServiceViewReset(), PhoneContactsAddReset(), PhoneContactsKeyboardReset(), PhoneContactsKeypadReset(), PhoneContactsModifyReset(), PhoneContactsReset(), PhoneDialLobbyReset(), PhoneDialManagerReset(), PhoneDialResidentReset(), PhoneLogMissedReset(), PhoneLogReceivedReset(), PhoneLogSentReset(), PhoneLogViewReset(), ScreensaverReset(), SettingDisplayReset(), SettingEngineerMiscTerminalReset(), SettingEngineerMiscTwiceReset(), SettingEngineerNetworkIPReset(), SettingEngineerNetworkMacReset(), SettingEngineerNetworkReset(), SettingEngineerNetworkWiFiPasswordReset(), SettingEngineerNetworkWiFiReset(), SettingEngineerReset(), SettingEngineerSensorReset(), SettingOutdoorMainReset(), SettingOutdoorMiscReset(), SettingPhoneAudioReset(), SettingPhoneDisturbReset(), SettingPhoneVoiceReset(), SettingSystemReset(), TimeReset(), TouchCalibrationReset(), UpgradeReset(), and VideoRecordReset().
Referenced by LoadScene().
void ScreensaverReset (void)
Definition at line 59 of file layer_screensaver.c.
Referenced by resetScene().
void SettingDisplayReset (void)
Definition at line 263 of file layer_setting_display.c.
Referenced by resetScene().
void SettingEngineerMiscTerminalReset (void)
Definition at line 189 of file layer_setting_engineer_misc_terminal.c.
Referenced by resetScene().
void SettingEngineerMiscTwiceReset (void)
Definition at line 245 of file layer_setting_engineer_misc_twice.c.
References settingEngineerMiscTwiceOutdoorInfoSem.
Referenced by resetScene().
void SettingEngineerNetworkIPReset (void)
Definition at line 205 of file layer_setting_engineer_network_ip.c.
References settingEngineerNetworkIPCloseCallback, and SettingEngineerNetworkIPCloseCallbackDefault().
Referenced by resetScene().
void SettingEngineerNetworkMacReset (void)
Definition at line 48 of file layer_setting_engineer_network_mac.c.
References settingEngineerNetworkMacCloseCallback, and SettingEngineerNetworkMacCloseCallbackDefault().
Referenced by resetScene().
void SettingEngineerNetworkReset (void)
Definition at line 203 of file layer_setting_engineer_network.c.
Referenced by resetScene().
void SettingEngineerNetworkWiFiPasswordReset (void)
Definition at line 54 of file layer_setting_engineer_network_wifi_password.c.
References settingEngineerNetworkWiFiPasswordCloseCallback, and SettingEngineerNetworkWiFiPasswordCloseCallbackDefault().
Referenced by resetScene().
void SettingEngineerNetworkWiFiReset (void)
Definition at line 287 of file layer_setting_engineer_network_wifi.c.
Referenced by resetScene().
void SettingEngineerReset (void)
Definition at line 35 of file layer_setting_engineer.c.
Referenced by resetScene().
void SettingEngineerSensorReset (void)
Definition at line 148 of file layer_setting_engineer_sensor.c.
Referenced by resetScene().
void SettingOutdoorMainReset (void)
Definition at line 318 of file layer_setting_outdoor_main.c.
References settingOutdoorMainInfoCount.
Referenced by resetScene().
void SettingOutdoorMiscReset (void)
Definition at line 156 of file layer_setting_outdoor_misc.c.
Referenced by resetScene().
void SettingPhoneAudioReset (void)
Definition at line 263 of file layer_setting_phone_audio.c.
Referenced by resetScene().
void SettingPhoneDisturbReset (void)
Definition at line 382 of file layer_setting_phone_disturb.c.
Referenced by resetScene().
void SettingPhoneVoiceReset (void)
Definition at line 145 of file layer_setting_phone_voice.c.
Referenced by resetScene().
void SettingSystemReset (void)
Definition at line 183 of file layer_setting_system.c.
References settingSystemInfoCount.
Referenced by resetScene().
void TimeReset (void)
Definition at line 156 of file layer_time.c.
Referenced by resetScene().
void TouchCalibrationReset (void)
Definition at line 149 of file layer_touch_calibration.c.
Referenced by resetScene().
void UpgradeReset (void)
Definition at line 32 of file layer_upgrade.c.
Referenced by resetScene().
void VideoRecordReset (void)
Definition at line 157 of file layer_videorecord.c.
Referenced by resetScene().