ITE SoC SDK: test_stdlib.c File Reference
test_stdlib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include "ite/itp.h"
Functions
void test_stgt_env ()
void test_exit ()
void * TestFunc (void *arg)
Variables
FILE * stream
Function Documentation
void test_exit ()
Definition at line 35 of file test_stdlib.c.
Referenced by TestFunc().
void test_stgt_env ()
Definition at line 11 of file test_stdlib.c.
References font::x.
Referenced by TestFunc().
void* TestFunc (void * arg)
Definition at line 40 of file test_stdlib.c.
References itpInit(), test_exit(), and test_stgt_env().
Variable Documentation
FILE* stream
Definition at line 9 of file test_stdlib.c.
Referenced by Test_chmod(), test_fclose(), test_fread(), test_fseek(), test_fwrite(), and UpgradeSetStream().