ITE SoC SDK: test_win32.c File Reference
test_win32.c File Reference
#include <windows.h>
#include <pthread.h>
#include "ite/ith.h"
Functions
void BootInit (void)
void * TestFunc (void *arg)
static LRESULT CALLBACK WndProc (HWND hwnd, UINT msg, WPARAM wparam, LPARAM lparam)
int main (void)
Variables
static HWND hWnd
Function Documentation
void BootInit (void)
Referenced by main().
int main (void)
Definition at line 48 of file test_win32.c.
References attr, BootInit(), hWnd, TestFunc(), and WndProc().
void* TestFunc (void * arg)
Definition at line 152 of file test_pthread_attr.c.
References attr, itpInit(), policy, test_callmalloc(), Test_chmod(), test_clock(), test_closedir(), Test_Cond_Others(), test_difftime(), test_end_clock(), test_exit(), test_fclose(), test_fread(), test_fseek(), Test_fstat(), test_fwrite(), test_getchar(), Test_getcwd(), test_gettimeofday(), Test_lseek(), test_mallinfo(), test_malloc_stats(), test_memalign(), Test_mkdir(), test_mktime(), Test_mqueue(), Test_Mutex_Others(), test_opendir(), test_printf(), Test_pthread_attr_getschedparam(), Test_pthread_attr_setdetachstate(), Test_pthread_attr_setschedparam(), Test_pthread_attr_setstacksize(), Test_pthread_cancel(), Test_pthread_cond_timedwait(), Test_pthread_cond_wait(), Test_pthread_detach(), Test_pthread_equal(), Test_pthread_exit(), Test_pthread_getspecific(), Test_pthread_join(), Test_pthread_key(), Test_pthread_mutex_trylock(), Test_pthread_mutex_unlock(), Test_pthread_once(), Test_pthread_self(), Test_pthread_setschedparam(), Test_pthread_setspecific(), test_puts(), Test_read(), test_readdir(), test_remove(), test_rename(), test_rewinddir(), Test_rmdir(), Test_sched_yield(), Test_sem_post(), Test_sem_trywait(), test_settimeofday(), Test_show_thread_priority(), Test_sleep(), test_start_clock(), Test_stat(), test_statvfs(), test_stgt_env(), test_time(), Test_timer(), Test_usleep(), and Test_write().
Referenced by main().
static LRESULT CALLBACK WndProc (HWND hwnd, UINT msg, WPARAM wparam, LPARAM lparam) static
Definition at line 11 of file test_win32.c.
Referenced by main().
Variable Documentation
HWND hWnd static
Definition at line 8 of file test_win32.c.
Referenced by main().