ITE SoC SDK: test_pthread_key.c File Reference
test_pthread_key.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
Functions
static void checkResults (char *string, int rc)
void globalDestructor (void *value)
void Test_pthread_key ()
void * TestFunc (void *arg)
Variables
pthread_key_t tlsKey = 0
Function Documentation
static void checkResults (char * string, int rc) static
Definition at line 8 of file test_pthread_key.c.
Referenced by Test_pthread_key().
void globalDestructor (void * value)
Definition at line 17 of file test_pthread_key.c.
References tlsKey.
Referenced by Test_pthread_key().
void Test_pthread_key ()
Definition at line 24 of file test_pthread_key.c.
References checkResults(), globalDestructor(), i, and tlsKey.
Referenced by TestFunc().
void* TestFunc (void * arg)
Definition at line 44 of file test_pthread_key.c.
References itpInit(), and Test_pthread_key().
Variable Documentation
pthread_key_t tlsKey = 0
Definition at line 6 of file test_pthread_key.c.
Referenced by globalDestructor(), and Test_pthread_key().