ITE SoC SDK: test_pthread_others.c File Reference
test_pthread_others.c File Reference
#include <errno.h>
#include <pthread.h>
#include <sched.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Macros
#define THREADNUM 3
#define threads 3
#define BUFFSZ 48
#define threads 3
#define BUFFSZ 48
Functions
void * HelloFunc (void *arg)
void Test_pthread_detach ()
void Test_pthread_join ()
void dosleep (int millis)
void domsg (const char *msg)
void dowait ()
void * fn1 (void *param)
void * fn2 (void *param)
void Test_pthread_setschedparam ()
void * threadfunc (void *parm)
void destr_fn (void *parm)
void Test_pthread_setspecific ()
void once_fn ()
void * thread_pthread_once (void *parm)
void Test_pthread_once ()
void * thread_getspecific (void *parm)
void Test_pthread_getspecific ()
void * thread_exit (void *arg)
void Test_pthread_exit ()
void * thread_equal (void *arg)
void Test_pthread_equal ()
void * thread_self (void *arg)
void Test_pthread_self ()
void * mythread (void *arg)
void Test_pthread_cancel ()
void * TestFunc (void *arg)
Variables
pthread_mutex_t m_mtx
int m_goahead
pthread_key_t key
int once_counter =0
pthread_once_t once_control = PTHREAD_ONCE_INIT
pthread_t thid
pthread_t IPT
Macro Definition Documentation
#define BUFFSZ 48
Definition at line 280 of file test_pthread_others.c.
Referenced by thread_getspecific(), and threadfunc().
#define BUFFSZ 48
Definition at line 280 of file test_pthread_others.c.
#define THREADNUM 3
Definition at line 9 of file test_pthread_others.c.
Referenced by Test_pthread_detach(), and Test_pthread_join().
#define threads 3
Definition at line 279 of file test_pthread_others.c.
Referenced by Test_pthread_getspecific(), Test_pthread_once(), and Test_pthread_setspecific().
#define threads 3
Definition at line 279 of file test_pthread_others.c.
Function Documentation
void destr_fn (void * parm)
Definition at line 232 of file test_pthread_others.c.
Referenced by Test_pthread_getspecific(), and Test_pthread_setspecific().
void domsg (const char * msg)
Definition at line 84 of file test_pthread_others.c.
References m_mtx.
Referenced by fn1(), and fn2().
void dosleep (int millis)
Definition at line 79 of file test_pthread_others.c.
Referenced by dowait(), fn1(), and Test_pthread_setschedparam().
void dowait ()
Definition at line 91 of file test_pthread_others.c.
References dosleep(), and m_goahead.
Referenced by fn1(), and fn2().
void* fn1 (void * param)
Definition at line 97 of file test_pthread_others.c.
References domsg(), dosleep(), dowait(), and m_goahead.
Referenced by Test_pthread_setschedparam().
void* fn2 (void * param)
Definition at line 108 of file test_pthread_others.c.
References domsg(), and dowait().
Referenced by Test_pthread_setschedparam().
void* HelloFunc (void * arg)
Definition at line 10 of file test_pthread_others.c.
Referenced by Test_pthread_detach(), and Test_pthread_join().
void* mythread (void * arg)
Definition at line 485 of file test_pthread_others.c.
References i.
Referenced by Test_pthread_cancel().
void once_fn ()
Definition at line 285 of file test_pthread_others.c.
References once_counter.
Referenced by thread_pthread_once().
void Test_pthread_cancel ()
Definition at line 495 of file test_pthread_others.c.
References i, and mythread().
Referenced by TestFunc().
void Test_pthread_detach ()
Definition at line 18 of file test_pthread_others.c.
References attr, HelloFunc(), i, thid, and THREADNUM.
Referenced by TestFunc().
void Test_pthread_equal ()
Definition at line 450 of file test_pthread_others.c.
References IPT, thid, and thread_equal().
Referenced by TestFunc().
void Test_pthread_exit ()
Definition at line 427 of file test_pthread_others.c.
References thid, and thread_exit().
Referenced by TestFunc().
void Test_pthread_getspecific ()
Definition at line 382 of file test_pthread_others.c.
References destr_fn(), i, key, thread_getspecific(), and threads.
Referenced by TestFunc().
void Test_pthread_join ()
Definition at line 47 of file test_pthread_others.c.
References attr, HelloFunc(), i, thid, and THREADNUM.
Referenced by TestFunc().
void Test_pthread_once ()
Definition at line 309 of file test_pthread_others.c.
References i, once_counter, thread_pthread_once(), and threads.
Referenced by TestFunc().
void Test_pthread_self ()
Definition at line 474 of file test_pthread_others.c.
References IPT, thid, and thread_self().
Referenced by TestFunc().
void Test_pthread_setschedparam ()
Definition at line 114 of file test_pthread_others.c.
References dosleep(), fn1(), fn2(), m_goahead, and m_mtx.
Referenced by TestFunc().
void Test_pthread_setspecific ()
Definition at line 238 of file test_pthread_others.c.
References destr_fn(), i, key, threadfunc(), and threads.
Referenced by TestFunc().
void* TestFunc (void * arg)
Definition at line 514 of file test_pthread_others.c.
References itpInit(), Test_pthread_cancel(), Test_pthread_detach(), Test_pthread_equal(), Test_pthread_exit(), Test_pthread_getspecific(), Test_pthread_join(), Test_pthread_once(), Test_pthread_self(), Test_pthread_setschedparam(), and Test_pthread_setspecific().
void* thread_equal (void * arg)
Definition at line 443 of file test_pthread_others.c.
References IPT, and thid.
Referenced by Test_pthread_equal().
void* thread_exit (void * arg)
Definition at line 417 of file test_pthread_others.c.
Referenced by Test_pthread_exit().
void* thread_getspecific (void * parm)
Definition at line 339 of file test_pthread_others.c.
References BUFFSZ, and key.
Referenced by Test_pthread_getspecific().
void* thread_pthread_once (void * parm)
Definition at line 291 of file test_pthread_others.c.
References once_control, and once_fn().
Referenced by Test_pthread_once().
void* thread_self (void * arg)
Definition at line 462 of file test_pthread_others.c.
References IPT, and thid.
Referenced by Test_pthread_self().
void* threadfunc (void * parm)
Definition at line 190 of file test_pthread_others.c.
References BUFFSZ, and key.
Referenced by Test_pthread_setspecific().
Variable Documentation
pthread_t IPT
Definition at line 441 of file test_pthread_others.c.
Referenced by Test_pthread_equal(), Test_pthread_self(), thread_equal(), and thread_self().
pthread_key_t key
Definition at line 188 of file test_pthread_others.c.
Referenced by Test_pthread_getspecific(), Test_pthread_setspecific(), thread_getspecific(), and threadfunc().
int m_goahead
Definition at line 77 of file test_pthread_others.c.
Referenced by dowait(), fn1(), and Test_pthread_setschedparam().
pthread_mutex_t m_mtx
Definition at line 76 of file test_pthread_others.c.
Referenced by domsg(), and Test_pthread_setschedparam().
pthread_once_t once_control = PTHREAD_ONCE_INIT
Definition at line 283 of file test_pthread_others.c.
Referenced by thread_pthread_once().
int once_counter =0
Definition at line 282 of file test_pthread_others.c.
Referenced by once_fn(), and Test_pthread_once().
pthread_t thid
Definition at line 441 of file test_pthread_others.c.
Referenced by Test_pthread_attr_setstacksize(), Test_pthread_cond_wait(), Test_pthread_detach(), Test_pthread_equal(), Test_pthread_exit(), Test_pthread_join(), Test_pthread_mutex_trylock(), Test_pthread_mutex_unlock(), Test_pthread_self(), thread_equal(), and thread_self().