ITE SoC SDK: test_systimes.c File Reference
test_systimes.c File Reference
#include <sys/time.h>
#include <sys/times.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <pthread.h>
#include <time.h>
#include <stdio.h>
#include <unistd.h>
#include "ite/itp.h"
Functions
void start_clock (void)
void end_clock (char *msg)
void test_start_clock ()
void test_end_clock (char *msg)
void * TestFunc (void *arg)
Variables
static clock_t st_time
static clock_t en_time
static struct tms st_cpu
static struct tms en_cpu
Function Documentation
void end_clock (char * msg)
void start_clock (void)
void test_end_clock (char * msg)
Definition at line 27 of file test_systimes.c.
References en_cpu, en_time, st_cpu, and st_time.
Referenced by TestFunc().
void test_start_clock ()
Definition at line 19 of file test_systimes.c.
References st_cpu, and st_time.
Referenced by TestFunc().
void* TestFunc (void * arg)
Definition at line 38 of file test_systimes.c.
References itpInit(), test_end_clock(), and test_start_clock().
Variable Documentation
struct tms en_cpu static
Definition at line 17 of file test_systimes.c.
Referenced by test_end_clock().
clock_t en_time static
Definition at line 15 of file test_systimes.c.
Referenced by test_end_clock().
struct tms st_cpu static
Definition at line 16 of file test_systimes.c.
Referenced by test_end_clock(), and test_start_clock().
clock_t st_time static
Definition at line 14 of file test_systimes.c.
Referenced by test_end_clock(), and test_start_clock().