#ifndef SPI_FTSSP_H
#define SPI_FTSSP_H

#include "ite/ith_defs.h"

#ifdef _WIN32
#define REG_SPI_PORT_OFFSET					0x400
#else
#define REG_SPI_PORT_OFFSET					0x100000
#endif

#define SPI0_BASE							ITH_SSP0_BASE
#define SPI1_BASE							SPI0_BASE + REG_SPI_PORT_OFFSET

#define REG_SPI_CONTROL_0					(0x00)
#define REG_SPI_CONTROL_1					(0x04)
#define REG_SPI_CONTROL_2					(0x08)
#define REG_SPI_STATUS						(0x0C)
#define REG_SPI_INTR_CONTROL				(0x10)
#define REG_SPI_INTR_STATUS					(0x14)
#define REG_SPI_DATA						(0x18)
#define REG_SPI_FREERUN						(0x1C)
#define REG_SPI_REVERSION					(0x7C)
#define REG_SPI_FEATURE						(0x78)
#define REG_SPI_MISC						(0x74)
#define REG_CLKSRC_OFFSET                   30
#define REG_CLKSRC_MASK                     (1<<30)


/*SPI Control Register 0*/
#define REG_CR0_TXENDIAN_LITTLE				(0 << 17)
#define REG_CR0_TXENDIAN_BIG				(1 << 17)
#define REG_CR0_TXENDIAN_MASK				0x00020000
#define REG_CR0_RXENDIAN_LITTLE				0
#define REG_CR0_RXENDIAN_BIG				1
#define REG_CR0_RXENDIAN_MASK				0x00010000
#define REG_CR0_FFMT_SPI					(1 << 12)
#define REG_CR0_FFMT_MASK					0x00007000
#define REG_CR0_FSPO_HIGH					0
#define REG_CR0_FSPO_LOW					(1 << 5)
#define REG_CR0_FSPO_MASK					0x00000020
#define REG_CR0_OPM_SLAVE					0x00
#define REG_CR0_OPM_MASTER					(0x03 << 2)
#define REG_CR0_OPM_MASK					0x0000000C
#define REG_CR0_SCLKPO_LOW					0
#define REG_CR0_SCLKPO_HIGH					(1 << 1)
#define REG_CR0_SCLKPO_MASK					0x00000002
#define REG_CR0_SCLKPH_DISABLE				0
#define REG_CR0_SCLKPH_ENABLE				(1 << 0)
#define REG_CR0_SCLKPH_MASK					0x00000001

/*SPI Control Register 1*/
#define REG_CR1_SDL_MAX_VALUE				31
#define REG_CR1_SDL_OFFSET					16
#define REG_CR1_SDL_MASK					0x001F0000
#define REG_CR1_SCLKDIV_MAX_VALUE			65535
#define REG_CR1_SCLKDIV_MASK				0x0000FFFF

/*SPI Control Register 2*/
#define REG_CR2_TXFCLR_ENABLE				(1 << 3)
#define REG_CR2_TXFCLR_NO_EFFECT			0
#define REG_CR2_TXFCLR_MASK					0x00000008
#define REG_CR2_RXFCLR_ENABLE				(1 << 2)
#define REG_CR2_RXFCLR_NO_EFFECT			0
#define REG_CR2_RXFCLR_MASK					0x00000004
#define REG_CR2_TXDOE_ENABLE				(1 << 1)
#define REG_CR2_TXDOE_DISABLE				0
#define REG_CR2_TXDOE_MASK					0x00000002
#define REG_CR2_SPI_ENABLE					1
#define REG_CR2_SPI_DISABLE					0
#define REG_CR2_SPI_MASK					0x00000001

/*SPI Status Register */
#define REG_STR_TFVE_OFFSET					12
#define REG_STR_TFVE_MASK					0x0007F000
#define REG_STR_RFVE_OFFSET					4
#define REG_STR_RFVE_MASK					0x000007F0
#define REG_STR_BUSY_OFFSET					2
#define REG_STR_BUSY_MASK					0x00000004
#define REG_STR_TFNF_OFFSET					1
#define REG_STR_TFNF_MASK					0x00000002
#define REG_STR_RFF_MASK					0x00000001

/*SSP Interrupt Control Register */
#define REG_ICR_TFTHOD_MAX					63
#define REG_ICR_TFTHOD_OFFSET				16
#define REG_ICR_TFTHOD_MASK					0x003F0000
#define REG_ICR_RFTHOD_MAX					63
#define REG_ICR_RFTHOD_OFFSET				8
#define REG_ICR_RFTHOD_MASK					0x00003F00
#define REG_ICR_TX_DMA_ENABLE				(1 << 5)
#define REG_ICR_TX_DMA_DISABLE				0
#define REG_ICR_TX_DMA_MASK					0x00000020
#define REG_ICR_RX_DMA_ENABLE				(1 << 4)
#define REG_ICR_RX_DMA_DISABLE				0
#define REG_ICR_RX_DMA_MASK					0x00000010
#define REG_ICR_TX_THRESHOLD_INTR_ENABLE	(1 << 3)
#define REG_ICR_TX_THRESHOLD_INTR_DISABLE	0
#define REG_ICR_TX_THRESHOLD_INTR_MASK		0x00000008
#define REG_ICR_RX_THRESHOLD_INTR_ENABLE	(1 << 2)
#define REG_ICR_RX_THRESHOLD_INTR_DISABLE	0
#define REG_ICR_RX_THRESHOLD_INTR_MASK		0x00000004
#define REG_ICR_TX_UNDERRUN_INTR_ENABLE		(1 << 1)
#define REG_ICR_TX_UNDERRUN_INTR_DISABLE	0
#define REG_ICR_TX_UNDERRUN_INTR_MASK		0x00000002
#define REG_ICR_RX_OVERRUN_INTR_ENABLE		(1 << 0)
#define REG_ICR_RX_OVERRUN_INTR_DISABLE		0
#define REG_ICR_RX_OVERRUN_INTR_MASK		0x00000001

/*SSP Interrupt Status Register */
#define REG_ISR_TX_THRESHOLD_INTR_MASK		0x00000008
#define REG_ISR_RX_THRESHOLD_INTR_MASK		0x00000004
#define REG_ISR_TX_UNDERRUN_INTR_MASK		0x00000002
#define REG_ISR_RX_OVERRUN_INTR_MASK		0x00000001

/*TX FIFO Free Run Register*/
#define REG_TXFR_FRUN_COUNT_MAX_VALUE		65535
#define REG_TXFR_FRUN_COUNT_OFFSET			16
#define REG_TXFR_FRUN_COUNT_MASK			0xFFFF0000

#define REG_TXFR_FRUN_FILTER_LENG_MAX_VALUE 255
#define REG_TXFR_FRUN_FILTER_LENG_OFFSET    8
#define REG_TXFR_FRUN_FILTER_LENG_MASK      0x0000FF00
#define REG_TXFR_FRUN_FILTER_ENABLE         (1 << 4)
#define REG_TXFR_FRUN_FILTER_DISABLE        0
#define REG_TXFR_FRUN_FILTER_MASK           0x00000010

#define REG_TXFR_CSNCLR_NORMAL				0
#define REG_TXFR_CSNCLR_ALWAYS_ZERO			(1 << 2)
#define REG_TXFR_CSNCLR_MASK				0x00000004

#define REG_TXFR_FRUN_RXLOCK_0				0
#define REG_TXFR_FRUN_RXLOCK_1				(1 << 1)
#define REG_TXFR_FRUN_RXLOCK_MASK			0x00000002

#define REG_TXFR_FRUN_FIRE_ENABLE			1
#define REG_TXFR_FRUN_FIRE_DISABLE			0
#define REG_TXFR_FRUN_FIRE_MASK				0x00000001

/*SPI Revision Register */
#define REG_REV_MAJOR_REV_OFFSET			16
#define REG_REV_MAJOR_REV_MASK				0x00FF0000
#define REG_REV_MINOR_REV_OFFSET			8
#define REG_REV_MINOR_REV_MASK				0x0000FF00
#define REG_REV_RELEASE_REV_MASK			0x000000FF

/*SPI Misc Register */
#define REG_CLKOUT_INV_ENABLE				1
#define REG_CLKOUT_INV_DISABLE              0
#define REG_CLKOUT_INV_OFFSET               25
#define REG_CLKOUT_INV_MASK                 (1 << 25)
#define REG_CLKOUT_BYPASS_ENABLE            1
#define REG_CLKOUT_BYPASS_DISABLE           0
#define REG_CLKOUT_BYPASS_OFFSET			24
#define REG_CLKOUT_BYPASS_MASK              (1 << 24)
#define REG_CLKOUT_DALAY_MASK               (0xFF << 16)
#define REG_CLKOUT_DALAY_OFFSET             16
#endif

