#ifndef	FSG_ERROR_H
#define	FSG_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif


#define ERR_FSG_BASE	0xF000

#define ERR_FSG_ALLOC_CTXT_FAIL			(ERR_FSG_BASE + 0x01)
#define ERR_FSG_AUTOCONFIG_FAIL			(ERR_FSG_BASE + 0x02)
#define ERR_FSG_ALLOC_EP0REQ_FAIL		(ERR_FSG_BASE + 0x03)
#define ERR_FSG_ALLOC_EP0BUF_FAIL		(ERR_FSG_BASE + 0x04)
#define ERR_FSG_ALLOC_BUFFHD_FAIL		(ERR_FSG_BASE + 0x05)
#define ERR_FSG_REQ_NOT_SUPPORT 		(ERR_FSG_BASE + 0x06)
#define ERR_FSG_ALLOC_EPREQ_FAIL		(ERR_FSG_BASE + 0x07)
#define ERR_FSG_NOT_CONFIG				(ERR_FSG_BASE + 0x08)
#define ERR_FSG_REQ_INVALID_PARAM		(ERR_FSG_BASE + 0x09)
#define ERR_FSG_CBW_NO_BUF				(ERR_FSG_BASE + 0x0A)
//#define ERR_FSG_CBW_TIMEOUT				(ERR_FSG_BASE + 0x0B)
#define ERR_FSG_CBW_INVALID  			(ERR_FSG_BASE + 0x0C)
#define ERR_FSG_DIR_CONFLICT  			(ERR_FSG_BASE + 0x0D)
#define ERR_FSG_CMD_SIZE_CONFLICT		(ERR_FSG_BASE + 0x0E)
#define ERR_FSG_LUN_INVALID				(ERR_FSG_BASE + 0x0F)
#define ERR_FSG_RESERVED_BITS_INVALID	(ERR_FSG_BASE + 0x10)
#define ERR_FSG_MEDIA_NOT_READY			(ERR_FSG_BASE + 0x11)
#define ERR_FSG_EXCEPTION				(ERR_FSG_BASE + 0x12)
#define ERR_FSG_CSW_NO_BUF				(ERR_FSG_BASE + 0x13)
#define ERR_FSG_SCSI_NO_BUF				(ERR_FSG_BASE + 0x14)
#define ERR_FSG_UNIT_ATTENTION_DATA		(ERR_FSG_BASE + 0x15)
#define ERR_FSG_READ_ZERO_SIZE  		(ERR_FSG_BASE + 0x16)




#ifdef __cplusplus
}
#endif

#endif
